{"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"metadata":{"externalID":"c:@M@PushwooshVoIP@objc(pl)PWVoIPCallDelegate(im)activatedAudioSession:didActivate:","roleHeading":"Instance Method","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"activatedAudioSession","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)CXProvider","kind":"typeIdentifier","text":"CXProvider"},{"kind":"text","text":", "},{"text":"didActivate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AVAudioSession","preciseIdentifier":"c:objc(cs)AVAudioSession","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"activatedAudioSession:didActivate:","kind":"identifier"}],"title":"activatedAudioSession(_:didActivate:)","role":"symbol","modules":[{"name":"PushwooshVoIP"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate\/activatedAudioSession(_:didActivate:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"optional","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"activatedAudioSession","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"provider"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CXProvider","text":"CXProvider"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didActivate"},{"kind":"text","text":" "},{"text":"audioSession","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)AVAudioSession","text":"AVAudioSession","kind":"typeIdentifier"},{"text":")","kind":"text"}]}]},{"kind":"parameters","parameters":[{"name":"provider","content":[{"inlineContent":[{"type":"text","text":"The CallKit provider managing the call."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The activated AVAudioSession instance. Configure audio settings as needed."}]}],"name":"audioSession"}]},{"kind":"content","content":[{"anchor":"discussion","text":"Discussion","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"This method is invoked when CallKit activates the audio session for a call. Use this callback to configure"},{"text":" ","type":"text"},{"text":"audio routing, start audio processing, or begin media playback.","type":"text"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"This is an optional delegate method. Implement it to manage audio session activation and configure audio routing.","type":"text"}]}],"style":"note","type":"aside","name":"Note"}]}],"abstract":[{"text":"Called when audio session is activated.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate"]]},"variants":[{"paths":["\/documentation\/pushwooshvoip\/pwvoipcalldelegate\/activatedaudiosession(_:didactivate:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshvoip\/pwvoipcalldelegate\/activatedaudiosession(_:didactivate:)"]}],"references":{"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPCallDelegate":{"url":"\/documentation\/pushwooshvoip\/pwvoipcalldelegate","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate","title":"PWVoIPCallDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PWVoIPCallDelegate"}],"kind":"symbol","navigatorTitle":[{"text":"PWVoIPCallDelegate","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Delegate protocol for receiving VoIP call events and CallKit callbacks."}]},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP":{"abstract":[{"type":"text","text":"VoIP push notifications with native call UI for iOS applications."}],"url":"\/documentation\/pushwooshvoip","title":"PushwooshVoIP","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP","kind":"symbol","role":"collection","type":"topic"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPCallDelegate/activatedAudioSession(_:didActivate:)":{"url":"\/documentation\/pushwooshvoip\/pwvoipcalldelegate\/activatedaudiosession(_:didactivate:)","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate\/activatedAudioSession(_:didActivate:)","type":"topic","abstract":[{"text":"Called when audio session is activated.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"activatedAudioSession","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CXProvider","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CXProvider"},{"kind":"text","text":", "},{"text":"didActivate","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)AVAudioSession","kind":"typeIdentifier","text":"AVAudioSession"},{"kind":"text","text":")"}],"title":"activatedAudioSession(_:didActivate:)","navigatorTitle":[{"text":"activatedAudioSession:didActivate:","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"activatedAudioSession:didActivate:","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"activatedAudioSession:didActivate:","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"activatedAudioSession:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CXProvider","text":"CXProvider"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"provider"},{"text":" ","kind":"text"},{"text":"didActivate:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)AVAudioSession","text":"AVAudioSession","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"audioSession"},{"text":";","kind":"text"}]}]}},{"value":"PWVoIPCallDelegate","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate\/title"},{"value":[{"text":"PWVoIPCallDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate\/fragments"},{"value":"activatedAudioSession:didActivate:","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate~1activatedAudioSession(_:didActivate:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate~1activatedAudioSession(_:didActivate:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"activatedAudioSession:didActivate:"}]}]}]}