{"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"deactivatedAudioSession","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"provider"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CXProvider","text":"CXProvider"},{"text":", ","kind":"text"},{"text":"didDeactivate","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"audioSession"},{"kind":"text","text":": "},{"text":"AVAudioSession","preciseIdentifier":"c:objc(cs)AVAudioSession","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The CallKit provider managing the call."}]}],"name":"provider"},{"content":[{"inlineContent":[{"text":"The deactivated AVAudioSession instance.","type":"text"}],"type":"paragraph"}],"name":"audioSession"}],"kind":"parameters"},{"kind":"content","content":[{"text":"Discussion","type":"heading","anchor":"discussion","level":2},{"inlineContent":[{"text":"This method is invoked when CallKit deactivates the audio session after a call ends. Use this callback to","type":"text"},{"type":"text","text":" "},{"type":"text","text":"stop audio processing and release audio resources."}],"type":"paragraph"},{"name":"Note","type":"aside","style":"note","content":[{"type":"paragraph","inlineContent":[{"text":"This is an optional delegate method. Implement it to handle audio session deactivation and cleanup audio resources.","type":"text"}]}]}]}],"abstract":[{"type":"text","text":"Called when audio session is deactivated."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshvoip\/pwvoipcalldelegate\/deactivatedaudiosession(_:diddeactivate:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshvoip\/pwvoipcalldelegate\/deactivatedaudiosession(_:diddeactivate:)"]}],"kind":"symbol","sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate\/deactivatedAudioSession(_:didDeactivate:)","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@M@PushwooshVoIP@objc(pl)PWVoIPCallDelegate(im)deactivatedAudioSession:didDeactivate:","title":"deactivatedAudioSession(_:didDeactivate:)","navigatorTitle":[{"kind":"identifier","text":"deactivatedAudioSession:didDeactivate:"}],"symbolKind":"method","roleHeading":"Instance Method","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"deactivatedAudioSession","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)CXProvider","kind":"typeIdentifier","text":"CXProvider"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didDeactivate"},{"text":": ","kind":"text"},{"text":"AVAudioSession","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVAudioSession"},{"text":")","kind":"text"}],"modules":[{"name":"PushwooshVoIP"}]},"references":{"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP":{"url":"\/documentation\/pushwooshvoip","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"VoIP push notifications with native call UI for iOS applications."}],"identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP","title":"PushwooshVoIP","type":"topic"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPCallDelegate":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PWVoIPCallDelegate","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Delegate protocol for receiving VoIP call events and CallKit callbacks."}],"url":"\/documentation\/pushwooshvoip\/pwvoipcalldelegate","title":"PWVoIPCallDelegate","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PWVoIPCallDelegate"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPCallDelegate/deactivatedAudioSession(_:didDeactivate:)":{"identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate\/deactivatedAudioSession(_:didDeactivate:)","navigatorTitle":[{"text":"deactivatedAudioSession:didDeactivate:","kind":"identifier"}],"url":"\/documentation\/pushwooshvoip\/pwvoipcalldelegate\/deactivatedaudiosession(_:diddeactivate:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"deactivatedAudioSession","kind":"identifier"},{"kind":"text","text":"("},{"text":"CXProvider","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CXProvider"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didDeactivate"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)AVAudioSession","kind":"typeIdentifier","text":"AVAudioSession"},{"kind":"text","text":")"}],"abstract":[{"text":"Called when audio session is deactivated.","type":"text"}],"title":"deactivatedAudioSession(_:didDeactivate:)","role":"symbol","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"deactivatedAudioSession:didDeactivate:","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"text":"deactivatedAudioSession:didDeactivate:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"deactivatedAudioSession:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CXProvider","text":"CXProvider"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"provider"},{"kind":"text","text":" "},{"text":"didDeactivate:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)AVAudioSession","text":"AVAudioSession","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"audioSession"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate\/title","value":"PWVoIPCallDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate\/fragments","value":[{"kind":"identifier","text":"PWVoIPCallDelegate"}]},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate~1deactivatedAudioSession(_:didDeactivate:)\/title","value":"deactivatedAudioSession:didDeactivate:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate~1deactivatedAudioSession(_:didDeactivate:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"deactivatedAudioSession:didDeactivate:"}]}]}]}