{"metadata":{"symbolKind":"method","modules":[{"name":"PushwooshVoIP"}],"roleHeading":"Instance Method","title":"heldCall(_:perform:)","required":true,"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"heldCall"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CXProvider","preciseIdentifier":"c:objc(cs)CXProvider"},{"kind":"text","text":", "},{"kind":"externalParam","text":"perform"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CXSetHeldCallAction","text":"CXSetHeldCallAction"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"heldCall:perform:"}],"role":"symbol","externalID":"c:@M@PushwooshVoIP@objc(pl)PWVoIPCallDelegate(im)heldCall:perform:"},"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate\/heldCall(_:perform:)","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate"]]},"abstract":[{"type":"text","text":"Called when user puts the call on hold or resumes it."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"heldCall","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"provider"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)CXProvider","text":"CXProvider","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"perform","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"action","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CXSetHeldCallAction","text":"CXSetHeldCallAction"},{"text":")","kind":"text"}]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The CallKit provider managing the call."}],"type":"paragraph"}],"name":"provider"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The action containing hold state. Use "},{"code":"action.isOnHold","type":"codeVoice"},{"type":"text","text":" to determine the new hold state."},{"text":" ","type":"text"},{"text":"Call ","type":"text"},{"type":"codeVoice","code":"action.fulfill()"},{"text":" after updating the call state.","type":"text"}]}],"name":"action"}]},{"kind":"content","content":[{"level":2,"type":"heading","anchor":"discussion","text":"Discussion"},{"inlineContent":[{"type":"text","text":"This method is invoked when the user toggles the hold button in CallKit UI. Implement this method"},{"type":"text","text":" "},{"type":"text","text":"to pause or resume media streaming and notify the remote party of the hold state."}],"type":"paragraph"},{"content":[{"type":"paragraph","inlineContent":[{"text":"This is an optional delegate method. Implement it if your app supports call hold functionality.","type":"text"}]}],"style":"note","name":"Note","type":"aside"}]}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/pushwooshvoip\/pwvoipcalldelegate\/heldcall(_:perform:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshvoip\/pwvoipcalldelegate\/heldcall(_:perform:)"]}],"references":{"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPCallDelegate":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PWVoIPCallDelegate"}],"navigatorTitle":[{"text":"PWVoIPCallDelegate","kind":"identifier"}],"abstract":[{"type":"text","text":"Delegate protocol for receiving VoIP call events and CallKit callbacks."}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate","title":"PWVoIPCallDelegate","url":"\/documentation\/pushwooshvoip\/pwvoipcalldelegate","type":"topic"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPCallDelegate/heldCall(_:perform:)":{"identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate\/heldCall(_:perform:)","url":"\/documentation\/pushwooshvoip\/pwvoipcalldelegate\/heldcall(_:perform:)","title":"heldCall(_:perform:)","kind":"symbol","type":"topic","required":true,"abstract":[{"type":"text","text":"Called when user puts the call on hold or resumes it."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"heldCall","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"CXProvider","preciseIdentifier":"c:objc(cs)CXProvider"},{"text":", ","kind":"text"},{"text":"perform","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)CXSetHeldCallAction","text":"CXSetHeldCallAction","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"heldCall:perform:"}],"role":"symbol"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP":{"abstract":[{"type":"text","text":"VoIP push notifications with native call UI for iOS applications."}],"title":"PushwooshVoIP","url":"\/documentation\/pushwooshvoip","role":"collection","type":"topic","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"heldCall:perform:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"heldCall:perform:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"text":"heldCall:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CXProvider","preciseIdentifier":"c:objc(cs)CXProvider","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"provider","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"perform:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)CXSetHeldCallAction","kind":"typeIdentifier","text":"CXSetHeldCallAction"},{"text":" *) ","kind":"text"},{"text":"action","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate\/title","value":"PWVoIPCallDelegate","op":"replace"},{"value":[{"text":"PWVoIPCallDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate~1heldCall(_:perform:)\/title","op":"replace","value":"heldCall:perform:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"heldCall:perform:"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate~1heldCall(_:perform:)\/fragments"}]}]}