{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"optional"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"playDTMF"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"provider"},{"text":": ","kind":"text"},{"text":"CXProvider","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CXProvider"},{"text":", ","kind":"text"},{"text":"perform","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"action"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CXPlayDTMFCallAction","text":"CXPlayDTMFCallAction"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"provider","content":[{"inlineContent":[{"type":"text","text":"The CallKit provider managing the call."}],"type":"paragraph"}]},{"name":"action","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The action containing the digit. Use "},{"type":"codeVoice","code":"action.digits"},{"type":"text","text":" to get the pressed digit."},{"type":"text","text":" "},{"type":"text","text":"Call "},{"type":"codeVoice","code":"action.fulfill()"},{"type":"text","text":" after playing the tone."}]}]}]},{"kind":"content","content":[{"level":2,"type":"heading","anchor":"discussion","text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"This method is invoked when the user presses a keypad digit in CallKit UI during an active call.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Implement this method to send DTMF tones to the remote party for interactive voice response systems."}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"This is an optional delegate method. Implement it if your app supports DTMF tone generation."}]}],"style":"note","name":"Note","type":"aside"}]}],"metadata":{"roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"playDTMF","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CXProvider","text":"CXProvider"},{"text":", ","kind":"text"},{"text":"perform","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CXPlayDTMFCallAction","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CXPlayDTMFCallAction"},{"kind":"text","text":")"}],"modules":[{"name":"PushwooshVoIP"}],"navigatorTitle":[{"kind":"identifier","text":"playDTMF:perform:"}],"externalID":"c:@M@PushwooshVoIP@objc(pl)PWVoIPCallDelegate(im)playDTMF:perform:","title":"playDTMF(_:perform:)","role":"symbol","symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshvoip\/pwvoipcalldelegate\/playdtmf(_:perform:)"]},{"paths":["\/documentation\/pushwooshvoip\/pwvoipcalldelegate\/playdtmf(_:perform:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate\/playDTMF(_:perform:)"},"kind":"symbol","abstract":[{"type":"text","text":"Called when user plays DTMF tone during the call."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPCallDelegate/playDTMF(_:perform:)":{"title":"playDTMF(_:perform:)","abstract":[{"text":"Called when user plays DTMF tone during the call.","type":"text"}],"url":"\/documentation\/pushwooshvoip\/pwvoipcalldelegate\/playdtmf(_:perform:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"playDTMF"},{"kind":"text","text":"("},{"text":"CXProvider","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CXProvider"},{"kind":"text","text":", "},{"kind":"externalParam","text":"perform"},{"text":": ","kind":"text"},{"text":"CXPlayDTMFCallAction","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CXPlayDTMFCallAction"},{"kind":"text","text":")"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"playDTMF:perform:"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate\/playDTMF(_:perform:)","kind":"symbol","role":"symbol"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPCallDelegate":{"title":"PWVoIPCallDelegate","abstract":[{"text":"Delegate protocol for receiving VoIP call events and CallKit callbacks.","type":"text"}],"url":"\/documentation\/pushwooshvoip\/pwvoipcalldelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"PWVoIPCallDelegate","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"PWVoIPCallDelegate"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate","kind":"symbol","role":"symbol"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP":{"title":"PushwooshVoIP","url":"\/documentation\/pushwooshvoip","abstract":[{"text":"VoIP push notifications with native call UI for iOS applications.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP","kind":"symbol","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"playDTMF:perform:","op":"replace","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"playDTMF:perform:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"playDTMF:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CXProvider","preciseIdentifier":"c:objc(cs)CXProvider"},{"kind":"text","text":" *) "},{"text":"provider","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"perform:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)CXPlayDTMFCallAction","text":"CXPlayDTMFCallAction","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"action"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"value":"playDTMF:perform:","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate~1playDTMF(_:perform:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"playDTMF:perform:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate~1playDTMF(_:perform:)\/fragments"},{"value":"PWVoIPCallDelegate","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate\/fragments","value":[{"kind":"identifier","text":"PWVoIPCallDelegate"}],"op":"replace"}]}]}