{"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pwProviderDidReset"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"provider"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)CXProvider","text":"CXProvider","kind":"typeIdentifier"},{"kind":"text","text":")"}]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The CallKit provider that was reset.","type":"text"}]}],"name":"provider"}],"kind":"parameters"},{"kind":"content","content":[{"anchor":"discussion","level":2,"text":"Discussion","type":"heading"},{"inlineContent":[{"type":"text","text":"This method is invoked when CallKit provider encounters a critical error or system reset."},{"type":"text","text":" "},{"type":"text","text":"When this occurs, all active calls are terminated and you should clean up any call-related resources."}],"type":"paragraph"},{"type":"aside","style":"important","name":"Important","content":[{"inlineContent":[{"text":"This is a required delegate method. Always implement it to handle provider resets and perform cleanup.","type":"text"}],"type":"paragraph"}]}]}],"variants":[{"paths":["\/documentation\/pushwooshvoip\/pwvoipcalldelegate\/pwproviderdidreset(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pushwooshvoip\/pwvoipcalldelegate\/pwproviderdidreset(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate"]]},"abstract":[{"text":"Called when the CallKit provider resets.","type":"text"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate\/pwProviderDidReset(_:)","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Instance Method","role":"symbol","required":true,"title":"pwProviderDidReset(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"pwProviderDidReset"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CXProvider","text":"CXProvider"},{"text":")","kind":"text"}],"externalID":"c:@M@PushwooshVoIP@objc(pl)PWVoIPCallDelegate(im)pwProviderDidReset:","navigatorTitle":[{"text":"pwProviderDidReset:","kind":"identifier"}],"symbolKind":"method","modules":[{"name":"PushwooshVoIP"}]},"references":{"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP":{"role":"collection","type":"topic","url":"\/documentation\/pushwooshvoip","title":"PushwooshVoIP","abstract":[{"text":"VoIP push notifications with native call UI for iOS applications.","type":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP","kind":"symbol"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPCallDelegate/pwProviderDidReset(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"pwProviderDidReset","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)CXProvider","kind":"typeIdentifier","text":"CXProvider"},{"text":")","kind":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"pwProviderDidReset:"}],"title":"pwProviderDidReset(_:)","required":true,"kind":"symbol","abstract":[{"text":"Called when the CallKit provider resets.","type":"text"}],"type":"topic","url":"\/documentation\/pushwooshvoip\/pwvoipcalldelegate\/pwproviderdidreset(_:)","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate\/pwProviderDidReset(_:)"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPCallDelegate":{"kind":"symbol","abstract":[{"type":"text","text":"Delegate protocol for receiving VoIP call events and CallKit callbacks."}],"navigatorTitle":[{"text":"PWVoIPCallDelegate","kind":"identifier"}],"role":"symbol","title":"PWVoIPCallDelegate","url":"\/documentation\/pushwooshvoip\/pwvoipcalldelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PWVoIPCallDelegate"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"pwProviderDidReset:","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"pwProviderDidReset:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"text":"pwProviderDidReset:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)CXProvider","kind":"typeIdentifier","text":"CXProvider"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"provider"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"pwProviderDidReset:","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate~1pwProviderDidReset(_:)\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate~1pwProviderDidReset(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"pwProviderDidReset:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate\/title","op":"replace","value":"PWVoIPCallDelegate"},{"value":[{"kind":"identifier","text":"PWVoIPCallDelegate"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}