{"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"required":true,"title":"pwProviderDidBegin(_:)","navigatorTitle":[{"text":"pwProviderDidBegin:","kind":"identifier"}],"symbolKind":"method","modules":[{"name":"PushwooshVoIP"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pwProviderDidBegin"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CXProvider","text":"CXProvider"},{"kind":"text","text":")"}],"externalID":"c:@M@PushwooshVoIP@objc(pl)PWVoIPCallDelegate(im)pwProviderDidBegin:","role":"symbol","roleHeading":"Instance Method"},"abstract":[{"type":"text","text":"Called when the CallKit provider is ready to handle calls."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshvoip\/pwvoipcalldelegate\/pwproviderdidbegin(_:)"]},{"paths":["\/documentation\/pushwooshvoip\/pwvoipcalldelegate\/pwproviderdidbegin(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate\/pwProviderDidBegin(_:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"pwProviderDidBegin","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"provider","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)CXProvider","text":"CXProvider","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The CallKit provider that is now active."}]}],"name":"provider"}],"kind":"parameters"},{"kind":"content","content":[{"level":2,"text":"Discussion","anchor":"discussion","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"This method is invoked when the CallKit provider has been initialized and is ready to manage calls.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Use this callback to perform any initialization that depends on CallKit being available."}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"This is a required delegate method. Implement it to track CallKit provider lifecycle.","type":"text"}]}],"style":"important","type":"aside","name":"Important"}]}],"kind":"symbol","references":{"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPCallDelegate":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PWVoIPCallDelegate"}],"navigatorTitle":[{"text":"PWVoIPCallDelegate","kind":"identifier"}],"abstract":[{"type":"text","text":"Delegate protocol for receiving VoIP call events and CallKit callbacks."}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate","title":"PWVoIPCallDelegate","url":"\/documentation\/pushwooshvoip\/pwvoipcalldelegate","type":"topic"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPCallDelegate/pwProviderDidBegin(_:)":{"required":true,"role":"symbol","title":"pwProviderDidBegin(_:)","navigatorTitle":[{"text":"pwProviderDidBegin:","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate\/pwProviderDidBegin(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"pwProviderDidBegin","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CXProvider","text":"CXProvider"},{"kind":"text","text":")"}],"type":"topic","url":"\/documentation\/pushwooshvoip\/pwvoipcalldelegate\/pwproviderdidbegin(_:)","abstract":[{"text":"Called when the CallKit provider is ready to handle calls.","type":"text"}],"kind":"symbol"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP":{"abstract":[{"type":"text","text":"VoIP push notifications with native call UI for iOS applications."}],"title":"PushwooshVoIP","url":"\/documentation\/pushwooshvoip","role":"collection","type":"topic","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"pwProviderDidBegin:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"pwProviderDidBegin:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"pwProviderDidBegin:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CXProvider","preciseIdentifier":"c:objc(cs)CXProvider","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"provider"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"PWVoIPCallDelegate","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate\/title"},{"value":[{"kind":"identifier","text":"PWVoIPCallDelegate"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate\/fragments","op":"replace"},{"op":"replace","value":"pwProviderDidBegin:","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate~1pwProviderDidBegin(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate~1pwProviderDidBegin(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"pwProviderDidBegin:"}]}]}]}