{"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate"]]},"abstract":[{"text":"Called to provide the call controller instance.","type":"text"}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate\/returnedCallController(_:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"optional"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"returnedCallController"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"controller"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CXCallController","text":"CXCallController"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The CXCallController instance for managing call actions.","type":"text"}]}],"name":"controller"}],"kind":"parameters"},{"kind":"content","content":[{"anchor":"discussion","text":"Discussion","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"This method is invoked to give your app access to the CXCallController instance managed by the SDK."},{"text":" ","type":"text"},{"text":"Use the controller to request call actions programmatically, such as ending calls or updating call state.","type":"text"}]},{"style":"note","type":"aside","content":[{"type":"paragraph","inlineContent":[{"text":"This is an optional delegate method. Implement it if you need direct access to the call controller.","type":"text"}]}],"name":"Note"}]}],"metadata":{"navigatorTitle":[{"text":"returnedCallController:","kind":"identifier"}],"role":"symbol","roleHeading":"Instance Method","externalID":"c:@M@PushwooshVoIP@objc(pl)PWVoIPCallDelegate(im)returnedCallController:","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"returnedCallController","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)CXCallController","kind":"typeIdentifier","text":"CXCallController"},{"text":")","kind":"text"}],"symbolKind":"method","modules":[{"name":"PushwooshVoIP"}],"title":"returnedCallController(_:)"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshvoip\/pwvoipcalldelegate\/returnedcallcontroller(_:)"]},{"paths":["\/documentation\/pushwooshvoip\/pwvoipcalldelegate\/returnedcallcontroller(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPCallDelegate/returnedCallController(_:)":{"url":"\/documentation\/pushwooshvoip\/pwvoipcalldelegate\/returnedcallcontroller(_:)","navigatorTitle":[{"kind":"identifier","text":"returnedCallController:"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"returnedCallController","kind":"identifier"},{"kind":"text","text":"("},{"text":"CXCallController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CXCallController"},{"text":")","kind":"text"}],"abstract":[{"text":"Called to provide the call controller instance.","type":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate\/returnedCallController(_:)","kind":"symbol","title":"returnedCallController(_:)","type":"topic"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP":{"identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP","type":"topic","role":"collection","kind":"symbol","abstract":[{"text":"VoIP push notifications with native call UI for iOS applications.","type":"text"}],"url":"\/documentation\/pushwooshvoip","title":"PushwooshVoIP"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPCallDelegate":{"type":"topic","navigatorTitle":[{"text":"PWVoIPCallDelegate","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"PWVoIPCallDelegate","kind":"identifier"}],"url":"\/documentation\/pushwooshvoip\/pwvoipcalldelegate","kind":"symbol","abstract":[{"type":"text","text":"Delegate protocol for receiving VoIP call events and CallKit callbacks."}],"identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate","title":"PWVoIPCallDelegate","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"returnedCallController:","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"returnedCallController:","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"returnedCallController:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)CXCallController","kind":"typeIdentifier","text":"CXCallController"},{"text":" *) ","kind":"text"},{"text":"controller","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate~1returnedCallController(_:)\/title","value":"returnedCallController:"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate~1returnedCallController(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"returnedCallController:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate\/title","value":"PWVoIPCallDelegate","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate\/fragments","value":[{"kind":"identifier","text":"PWVoIPCallDelegate"}]}]}]}