{"abstract":[{"type":"text","text":"Called when user initiates an outgoing call."}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate"]]},"kind":"symbol","metadata":{"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"startCall:perform:"}],"modules":[{"name":"PushwooshVoIP"}],"role":"symbol","externalID":"c:@M@PushwooshVoIP@objc(pl)PWVoIPCallDelegate(im)startCall:perform:","roleHeading":"Instance Method","title":"startCall(_:perform:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"startCall","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)CXProvider","kind":"typeIdentifier","text":"CXProvider"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"perform"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)CXStartCallAction","kind":"typeIdentifier","text":"CXStartCallAction"},{"text":")","kind":"text"}]},"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate\/startCall(_:perform:)","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"startCall"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"provider"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)CXProvider","kind":"typeIdentifier","text":"CXProvider"},{"kind":"text","text":", "},{"kind":"externalParam","text":"perform"},{"text":" ","kind":"text"},{"text":"action","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CXStartCallAction","text":"CXStartCallAction"},{"kind":"text","text":")"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The CallKit provider managing the call."}]}],"name":"provider"},{"name":"action","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The action containing call details. Call "},{"code":"action.fulfill()","type":"codeVoice"},{"type":"text","text":" when setup completes successfully,"},{"text":" ","type":"text"},{"type":"text","text":"or "},{"code":"action.fail()","type":"codeVoice"},{"type":"text","text":" if setup fails."}]}]}]},{"kind":"content","content":[{"text":"Discussion","level":2,"type":"heading","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This method is invoked when the user starts an outgoing call through CallKit. Implement this method"},{"type":"text","text":" "},{"type":"text","text":"to set up your call session and establish the connection with the remote party."}]},{"name":"Note","type":"aside","style":"note","content":[{"inlineContent":[{"type":"text","text":"This is an optional delegate method. Implement it if your app supports outgoing calls."}],"type":"paragraph"}]}]}],"variants":[{"paths":["\/documentation\/pushwooshvoip\/pwvoipcalldelegate\/startcall(_:perform:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pushwooshvoip\/pwvoipcalldelegate\/startcall(_:perform:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPCallDelegate/startCall(_:perform:)":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"startCall:perform:"}],"kind":"symbol","url":"\/documentation\/pushwooshvoip\/pwvoipcalldelegate\/startcall(_:perform:)","role":"symbol","abstract":[{"text":"Called when user initiates an outgoing call.","type":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate\/startCall(_:perform:)","title":"startCall(_:perform:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startCall"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)CXProvider","kind":"typeIdentifier","text":"CXProvider"},{"kind":"text","text":", "},{"text":"perform","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CXStartCallAction","preciseIdentifier":"c:objc(cs)CXStartCallAction"},{"kind":"text","text":")"}]},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPCallDelegate":{"type":"topic","abstract":[{"text":"Delegate protocol for receiving VoIP call events and CallKit callbacks.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PWVoIPCallDelegate","kind":"identifier"}],"title":"PWVoIPCallDelegate","role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate","navigatorTitle":[{"text":"PWVoIPCallDelegate","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/pushwooshvoip\/pwvoipcalldelegate"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP":{"type":"topic","abstract":[{"type":"text","text":"VoIP push notifications with native call UI for iOS applications."}],"title":"PushwooshVoIP","role":"collection","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP","kind":"symbol","url":"\/documentation\/pushwooshvoip"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"startCall:perform:","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startCall:perform:"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"startCall:","kind":"identifier"},{"kind":"text","text":"("},{"text":"CXProvider","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CXProvider"},{"text":" *) ","kind":"text"},{"text":"provider","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"perform:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CXStartCallAction","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CXStartCallAction"},{"kind":"text","text":" *) "},{"text":"action","kind":"internalParam"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate~1startCall(_:perform:)\/title","value":"startCall:perform:"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate~1startCall(_:perform:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"startCall:perform:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate\/title","value":"PWVoIPCallDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate\/fragments","value":[{"text":"PWVoIPCallDelegate","kind":"identifier"}]}]}]}