{"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate\/voipDidFailToReportIncomingCall(error:)"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"externalID":"c:@M@PushwooshVoIP@objc(pl)PWVoIPCallDelegate(im)voipDidFailToReportIncomingCallWithError:","navigatorTitle":[{"kind":"identifier","text":"voipDidFailToReportIncomingCallWithError:"}],"symbolKind":"method","title":"voipDidFailToReportIncomingCall(error:)","role":"symbol","modules":[{"name":"PushwooshVoIP"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"voipDidFailToReportIncomingCall","kind":"identifier"},{"kind":"text","text":"("},{"text":"error","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"kind":"text","text":")"}],"roleHeading":"Instance Method"},"sections":[],"abstract":[{"text":"Called when reporting incoming call to CallKit fails.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"voipDidFailToReportIncomingCall"},{"kind":"text","text":"("},{"text":"error","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}]}]},{"parameters":[{"name":"error","content":[{"inlineContent":[{"type":"text","text":"The error that occurred while reporting to CallKit. Check "},{"code":"error.localizedDescription","type":"codeVoice"},{"text":" for details.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},{"content":[{"anchor":"discussion","text":"Discussion","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"This method is invoked when the SDK fails to report the incoming call to CallKit framework."},{"text":" ","type":"text"},{"type":"text","text":"Common causes include CallKit permission issues, invalid call parameters, or system restrictions."}],"type":"paragraph"},{"name":"Note","content":[{"inlineContent":[{"type":"text","text":"This is an optional delegate method. Implement it to handle CallKit reporting failures."}],"type":"paragraph"}],"style":"note","type":"aside"}],"kind":"content"}],"variants":[{"paths":["\/documentation\/pushwooshvoip\/pwvoipcalldelegate\/voipdidfailtoreportincomingcall(error:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pushwooshvoip\/pwvoipcalldelegate\/voipdidfailtoreportincomingcall(error:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPCallDelegate/voipDidFailToReportIncomingCall(error:)":{"navigatorTitle":[{"kind":"identifier","text":"voipDidFailToReportIncomingCallWithError:"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"voipDidFailToReportIncomingCall"},{"kind":"text","text":"("},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"text":")","kind":"text"}],"abstract":[{"text":"Called when reporting incoming call to CallKit fails.","type":"text"}],"url":"\/documentation\/pushwooshvoip\/pwvoipcalldelegate\/voipdidfailtoreportincomingcall(error:)","type":"topic","role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate\/voipDidFailToReportIncomingCall(error:)","title":"voipDidFailToReportIncomingCall(error:)","kind":"symbol"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP":{"url":"\/documentation\/pushwooshvoip","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP","abstract":[{"type":"text","text":"VoIP push notifications with native call UI for iOS applications."}],"title":"PushwooshVoIP","type":"topic","kind":"symbol","role":"collection"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPCallDelegate":{"navigatorTitle":[{"text":"PWVoIPCallDelegate","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PWVoIPCallDelegate","kind":"identifier"}],"abstract":[{"type":"text","text":"Delegate protocol for receiving VoIP call events and CallKit callbacks."}],"title":"PWVoIPCallDelegate","role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate","type":"topic","url":"\/documentation\/pushwooshvoip\/pwvoipcalldelegate"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"voipDidFailToReportIncomingCallWithError:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"voipDidFailToReportIncomingCallWithError:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"voipDidFailToReportIncomingCallWithError:"},{"text":"(","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" *) "},{"text":"error","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate~1voipDidFailToReportIncomingCall(error:)\/title","value":"voipDidFailToReportIncomingCallWithError:"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate~1voipDidFailToReportIncomingCall(error:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"voipDidFailToReportIncomingCallWithError:","kind":"identifier"}]},{"op":"replace","value":"PWVoIPCallDelegate","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate\/title"},{"value":[{"text":"PWVoIPCallDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate\/fragments"}]}]}