{"sections":[],"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate\/voipDidRegisterTokenSuccessfully()","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"voipDidRegisterTokenSuccessfully","kind":"identifier"},{"text":"()","kind":"text"}],"externalID":"c:@M@PushwooshVoIP@objc(pl)PWVoIPCallDelegate(im)voipDidRegisterTokenSuccessfully","title":"voipDidRegisterTokenSuccessfully()","navigatorTitle":[{"kind":"identifier","text":"voipDidRegisterTokenSuccessfully"}],"modules":[{"name":"PushwooshVoIP"}],"role":"symbol","symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"voipDidRegisterTokenSuccessfully"},{"kind":"text","text":"()"}],"platforms":["iOS"]}]},{"kind":"content","content":[{"type":"heading","anchor":"discussion","level":2,"text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This method is invoked after the VoIP push token has been successfully sent to Pushwoosh backend"},{"type":"text","text":" "},{"type":"text","text":"and the device is ready to receive VoIP push notifications."}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"This is an optional delegate method. Use it to update your UI or log successful registration."}]}],"type":"aside","name":"Note","style":"note"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Called when VoIP token is successfully registered with Pushwoosh servers."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshvoip\/pwvoipcalldelegate\/voipdidregistertokensuccessfully()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshvoip\/pwvoipcalldelegate\/voipdidregistertokensuccessfully()"]}],"references":{"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP":{"title":"PushwooshVoIP","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP","url":"\/documentation\/pushwooshvoip","kind":"symbol","abstract":[{"type":"text","text":"VoIP push notifications with native call UI for iOS applications."}],"type":"topic","role":"collection"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPCallDelegate/voipDidRegisterTokenSuccessfully()":{"navigatorTitle":[{"kind":"identifier","text":"voipDidRegisterTokenSuccessfully"}],"title":"voipDidRegisterTokenSuccessfully()","url":"\/documentation\/pushwooshvoip\/pwvoipcalldelegate\/voipdidregistertokensuccessfully()","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate\/voipDidRegisterTokenSuccessfully()","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Called when VoIP token is successfully registered with Pushwoosh servers."}],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"voipDidRegisterTokenSuccessfully"},{"kind":"text","text":"()"}]},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPCallDelegate":{"title":"PWVoIPCallDelegate","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate","url":"\/documentation\/pushwooshvoip\/pwvoipcalldelegate","navigatorTitle":[{"text":"PWVoIPCallDelegate","kind":"identifier"}],"abstract":[{"type":"text","text":"Delegate protocol for receiving VoIP call events and CallKit callbacks."}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PWVoIPCallDelegate","kind":"identifier"}],"role":"symbol","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"voipDidRegisterTokenSuccessfully","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"voipDidRegisterTokenSuccessfully","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"voipDidRegisterTokenSuccessfully"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate~1voipDidRegisterTokenSuccessfully()\/title","value":"voipDidRegisterTokenSuccessfully"},{"value":[{"text":"- ","kind":"text"},{"text":"voipDidRegisterTokenSuccessfully","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate~1voipDidRegisterTokenSuccessfully()\/fragments"},{"value":"PWVoIPCallDelegate","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate\/title","op":"replace"},{"value":[{"kind":"identifier","text":"PWVoIPCallDelegate"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}