{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"voipDidCancelCall"},{"text":"(","kind":"text"},{"text":"voipMessage","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPMessage","text":"PWVoIPMessage","preciseIdentifier":"c:@M@PushwooshVoIP@objc(cs)PWVoIPMessage"},{"kind":"text","text":")"}],"platforms":["iOS"]}]},{"parameters":[{"name":"voipMessage","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The VoIP message containing call information. Use "},{"type":"codeVoice","code":"voipMessage.callId"},{"type":"text","text":" to identify which call was cancelled."}]}]}],"kind":"parameters"},{"kind":"content","content":[{"level":2,"text":"Discussion","anchor":"discussion","type":"heading"},{"inlineContent":[{"type":"text","text":"This method is invoked when the remote party cancels their outgoing call before the local user has a chance to answer."},{"type":"text","text":" "},{"text":"The SDK automatically dismisses the CallKit incoming call UI when this occurs.","type":"text"}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"type":"text","text":"To enable call cancellation, include these fields in your VoIP push payload:"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"callId"},{"type":"text","text":" - A unique server-provided identifier for the call"}]}]},{"content":[{"inlineContent":[{"code":"cancelCall","type":"codeVoice"},{"type":"text","text":" - Set to "},{"type":"codeVoice","code":"true"},{"text":" for cancellation requests","type":"text"}],"type":"paragraph"}]}]},{"inlineContent":[{"text":"The SDK matches cancellation requests to active calls using the ","type":"text"},{"code":"callId","type":"codeVoice"},{"type":"text","text":" field. When a cancellation push is received,"},{"type":"text","text":" "},{"text":"CallKit UI is automatically dismissed with ","type":"text"},{"type":"codeVoice","code":"CXCallEndedReason.remoteEnded"},{"type":"text","text":"."}],"type":"paragraph"},{"content":[{"type":"paragraph","inlineContent":[{"text":"This is an optional delegate method. If not implemented, the SDK will still automatically dismiss the CallKit UI.","type":"text"}]}],"type":"aside","name":"Note","style":"note"},{"type":"aside","style":"important","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Cancellation only works for calls that haven’t been answered yet. Once answered, cancellation requests are ignored."}]}],"name":"Important"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate\/voipDidCancelCall(voipMessage:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Called when a call is remotely cancelled via VoIP push before the user answers."}],"metadata":{"role":"symbol","modules":[{"name":"PushwooshVoIP"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"voipDidCancelCall"},{"kind":"text","text":"("},{"kind":"externalParam","text":"voipMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PWVoIPMessage","preciseIdentifier":"c:@M@PushwooshVoIP@objc(cs)PWVoIPMessage"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"voipDidCancelCallWithVoipMessage:","kind":"identifier"}],"externalID":"c:@M@PushwooshVoIP@objc(pl)PWVoIPCallDelegate(im)voipDidCancelCallWithVoipMessage:","required":true,"symbolKind":"method","title":"voipDidCancelCall(voipMessage:)","roleHeading":"Instance Method"},"variants":[{"paths":["\/documentation\/pushwooshvoip\/pwvoipcalldelegate\/voipdidcancelcall(voipmessage:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pushwooshvoip\/pwvoipcalldelegate\/voipdidcancelcall(voipmessage:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate"]]},"references":{"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPMessage":{"role":"symbol","abstract":[{"text":"An encapsulation of VoIP push notification payload data.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PWVoIPMessage"}],"url":"\/documentation\/pushwooshvoip\/pwvoipmessage","navigatorTitle":[{"kind":"identifier","text":"PWVoIPMessage"}],"title":"PWVoIPMessage","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPMessage","kind":"symbol"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPCallDelegate/voipDidCancelCall(voipMessage:)":{"type":"topic","title":"voipDidCancelCall(voipMessage:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"voipDidCancelCall","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"voipMessage"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@PushwooshVoIP@objc(cs)PWVoIPMessage","kind":"typeIdentifier","text":"PWVoIPMessage"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate\/voipDidCancelCall(voipMessage:)","abstract":[{"type":"text","text":"Called when a call is remotely cancelled via VoIP push before the user answers."}],"required":true,"role":"symbol","navigatorTitle":[{"text":"voipDidCancelCallWithVoipMessage:","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/pushwooshvoip\/pwvoipcalldelegate\/voipdidcancelcall(voipmessage:)"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP":{"url":"\/documentation\/pushwooshvoip","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP","title":"PushwooshVoIP","kind":"symbol","abstract":[{"text":"VoIP push notifications with native call UI for iOS applications.","type":"text"}],"type":"topic","role":"collection"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPCallDelegate":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PWVoIPCallDelegate"}],"url":"\/documentation\/pushwooshvoip\/pwvoipcalldelegate","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate","navigatorTitle":[{"text":"PWVoIPCallDelegate","kind":"identifier"}],"title":"PWVoIPCallDelegate","abstract":[{"text":"Delegate protocol for receiving VoIP call events and CallKit callbacks.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"voipDidCancelCallWithVoipMessage:","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"voipDidCancelCallWithVoipMessage:"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"voipDidCancelCallWithVoipMessage:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPMessage","preciseIdentifier":"c:@M@PushwooshVoIP@objc(cs)PWVoIPMessage","kind":"typeIdentifier","text":"PWVoIPMessage"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"voipMessage"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","value":"PWVoIPMessage","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPMessage\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPMessage\/fragments","op":"replace","value":[{"text":"PWVoIPMessage","kind":"identifier"}]},{"op":"replace","value":"voipDidCancelCallWithVoipMessage:","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate~1voipDidCancelCall(voipMessage:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"voipDidCancelCallWithVoipMessage:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate~1voipDidCancelCall(voipMessage:)\/fragments"},{"value":"PWVoIPCallDelegate","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate\/title"},{"value":[{"text":"PWVoIPCallDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate\/fragments"}]}]}