{"metadata":{"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"voipDidFailToRegisterTokenWithError:"}],"role":"symbol","modules":[{"name":"PushwooshVoIP"}],"roleHeading":"Instance Method","required":true,"title":"voipDidFailToRegisterToken(error:)","externalID":"c:@M@PushwooshVoIP@objc(pl)PWVoIPCallDelegate(im)voipDidFailToRegisterTokenWithError:","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"voipDidFailToRegisterToken","kind":"identifier"},{"kind":"text","text":"("},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":")","kind":"text"}]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshvoip\/pwvoipcalldelegate\/voipdidfailtoregistertoken(error:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshvoip\/pwvoipcalldelegate\/voipdidfailtoregistertoken(error:)"]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"voipDidFailToRegisterToken"},{"kind":"text","text":"("},{"kind":"externalParam","text":"error"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"text":")","kind":"text"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate"]]},"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate\/voipDidFailToRegisterToken(error:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Called when VoIP token registration fails."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPCallDelegate":{"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PWVoIPCallDelegate"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate","url":"\/documentation\/pushwooshvoip\/pwvoipcalldelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"PWVoIPCallDelegate","kind":"identifier"}],"role":"symbol","title":"PWVoIPCallDelegate","abstract":[{"text":"Delegate protocol for receiving VoIP call events and CallKit callbacks.","type":"text"}]},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPCallDelegate/voipDidFailToRegisterToken(error:)":{"url":"\/documentation\/pushwooshvoip\/pwvoipcalldelegate\/voipdidfailtoregistertoken(error:)","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate\/voipDidFailToRegisterToken(error:)","role":"symbol","navigatorTitle":[{"text":"voipDidFailToRegisterTokenWithError:","kind":"identifier"}],"title":"voipDidFailToRegisterToken(error:)","required":true,"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"voipDidFailToRegisterToken"},{"kind":"text","text":"("},{"kind":"externalParam","text":"error"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"text":"Called when VoIP token registration fails.","type":"text"}],"kind":"symbol"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP","url":"\/documentation\/pushwooshvoip","role":"collection","title":"PushwooshVoIP","abstract":[{"text":"VoIP push notifications with native call UI for iOS applications.","type":"text"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"voipDidFailToRegisterTokenWithError:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"voipDidFailToRegisterTokenWithError:"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"voipDidFailToRegisterTokenWithError:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"error"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate\/title","value":"PWVoIPCallDelegate"},{"value":[{"text":"PWVoIPCallDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate~1voipDidFailToRegisterToken(error:)\/title","value":"voipDidFailToRegisterTokenWithError:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"voipDidFailToRegisterTokenWithError:"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate~1voipDidFailToRegisterToken(error:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}