{"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/pushwooshvoip\/pwvoipcalldelegate\/voipdidreceiveincomingcall(payload:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pushwooshvoip\/pwvoipcalldelegate\/voipdidreceiveincomingcall(payload:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate"]]},"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate\/voipDidReceiveIncomingCall(payload:)","interfaceLanguage":"swift"},"metadata":{"title":"voipDidReceiveIncomingCall(payload:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"voipDidReceiveIncomingCall","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"payload"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@PushwooshVoIP@objc(cs)PWVoIPMessage","text":"PWVoIPMessage"},{"text":")","kind":"text"}],"modules":[{"name":"PushwooshVoIP"}],"symbolKind":"method","navigatorTitle":[{"text":"voipDidReceiveIncomingCallWithPayload:","kind":"identifier"}],"required":true,"roleHeading":"Instance Method","role":"symbol","externalID":"c:@M@PushwooshVoIP@objc(pl)PWVoIPCallDelegate(im)voipDidReceiveIncomingCallWithPayload:"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"voipDidReceiveIncomingCall","kind":"identifier"},{"text":"(","kind":"text"},{"text":"payload","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@PushwooshVoIP@objc(cs)PWVoIPMessage","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPMessage","text":"PWVoIPMessage"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"payload","content":[{"type":"paragraph","inlineContent":[{"text":"The VoIP message containing call information such as caller name, handle type, and video support.","type":"text"}]}]}]},{"kind":"content","content":[{"anchor":"discussion","type":"heading","level":2,"text":"Discussion"},{"inlineContent":[{"text":"This is the main entry point for handling incoming VoIP calls. The method is invoked when a VoIP push","type":"text"},{"type":"text","text":" "},{"text":"is received from Pushwoosh servers. Use the payload information to display caller details and handle","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"call setup in your application."}],"type":"paragraph"},{"name":"Important","style":"important","type":"aside","content":[{"inlineContent":[{"type":"text","text":"This is a required delegate method. You must implement it to handle incoming VoIP calls."}],"type":"paragraph"}]}]}],"abstract":[{"type":"text","text":"Called when a VoIP push notification arrives."}],"sections":[],"references":{"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPCallDelegate/voipDidReceiveIncomingCall(payload:)":{"required":true,"url":"\/documentation\/pushwooshvoip\/pwvoipcalldelegate\/voipdidreceiveincomingcall(payload:)","navigatorTitle":[{"text":"voipDidReceiveIncomingCallWithPayload:","kind":"identifier"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"voipDidReceiveIncomingCall","kind":"identifier"},{"kind":"text","text":"("},{"text":"payload","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@PushwooshVoIP@objc(cs)PWVoIPMessage","text":"PWVoIPMessage","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate\/voipDidReceiveIncomingCall(payload:)","type":"topic","abstract":[{"text":"Called when a VoIP push notification arrives.","type":"text"}],"kind":"symbol","title":"voipDidReceiveIncomingCall(payload:)"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPMessage":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PWVoIPMessage"}],"navigatorTitle":[{"text":"PWVoIPMessage","kind":"identifier"}],"abstract":[{"type":"text","text":"An encapsulation of VoIP push notification payload data."}],"identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPMessage","type":"topic","title":"PWVoIPMessage","kind":"symbol","url":"\/documentation\/pushwooshvoip\/pwvoipmessage"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPCallDelegate":{"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PWVoIPCallDelegate"}],"navigatorTitle":[{"text":"PWVoIPCallDelegate","kind":"identifier"}],"abstract":[{"type":"text","text":"Delegate protocol for receiving VoIP call events and CallKit callbacks."}],"identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate","type":"topic","title":"PWVoIPCallDelegate","kind":"symbol","url":"\/documentation\/pushwooshvoip\/pwvoipcalldelegate"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP":{"title":"PushwooshVoIP","role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP","url":"\/documentation\/pushwooshvoip","abstract":[{"type":"text","text":"VoIP push notifications with native call UI for iOS applications."}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"voipDidReceiveIncomingCallWithPayload:","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"voipDidReceiveIncomingCallWithPayload:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"voipDidReceiveIncomingCallWithPayload:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"PWVoIPMessage","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPMessage","preciseIdentifier":"c:@M@PushwooshVoIP@objc(cs)PWVoIPMessage"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"payload"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"value":"voipDidReceiveIncomingCallWithPayload:","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate~1voipDidReceiveIncomingCall(payload:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate~1voipDidReceiveIncomingCall(payload:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"voipDidReceiveIncomingCallWithPayload:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPMessage\/title","value":"PWVoIPMessage"},{"value":[{"kind":"identifier","text":"PWVoIPMessage"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPMessage\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate\/title","value":"PWVoIPCallDelegate"},{"value":[{"kind":"identifier","text":"PWVoIPCallDelegate"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}