{"variants":[{"paths":["\/documentation\/pushwooshvoip\/pwvoipcalldelegate\/voipdidfailtocancelcall(callid:reason:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshvoip\/pwvoipcalldelegate\/voipdidfailtocancelcall(callid:reason:)"]}],"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate\/voipDidFailToCancelCall(callId:reason:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Called when a call cancellation attempt fails."}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"voipDidFailToCancelCall"},{"text":"(","kind":"text"},{"text":"callId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"reason","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The call identifier from the cancellation request, or nil if not provided."}],"type":"paragraph"}],"name":"callId"},{"name":"reason","content":[{"inlineContent":[{"text":"A human-readable description of why the cancellation failed.","type":"text"}],"type":"paragraph"}]}]},{"content":[{"level":2,"anchor":"discussion","type":"heading","text":"Discussion"},{"inlineContent":[{"type":"text","text":"This method is invoked when the SDK receives a cancellation request but cannot cancel the call."},{"type":"text","text":" "},{"type":"text","text":"Common failure reasons include:"}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"No active call found with the provided "},{"type":"codeVoice","code":"callId"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"The call has already been answered by the user","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"The call has already ended","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Missing "},{"code":"callId","type":"codeVoice"},{"type":"text","text":" in the cancellation payload"}]}]}],"type":"unorderedList"},{"style":"note","type":"aside","content":[{"inlineContent":[{"text":"This is an optional delegate method. Implement it to track cancellation failures for debugging or analytics.","type":"text"}],"type":"paragraph"}],"name":"Note"}],"kind":"content"}],"sections":[],"metadata":{"navigatorTitle":[{"text":"voipDidFailToCancelCallWithCallId:reason:","kind":"identifier"}],"title":"voipDidFailToCancelCall(callId:reason:)","modules":[{"name":"PushwooshVoIP"}],"externalID":"c:@M@PushwooshVoIP@objc(pl)PWVoIPCallDelegate(im)voipDidFailToCancelCallWithCallId:reason:","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"voipDidFailToCancelCall"},{"kind":"text","text":"("},{"text":"callId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"reason","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","references":{"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP":{"abstract":[{"text":"VoIP push notifications with native call UI for iOS applications.","type":"text"}],"title":"PushwooshVoIP","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP","kind":"symbol","role":"collection","url":"\/documentation\/pushwooshvoip"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPCallDelegate/voipDidFailToCancelCall(callId:reason:)":{"role":"symbol","navigatorTitle":[{"text":"voipDidFailToCancelCallWithCallId:reason:","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate\/voipDidFailToCancelCall(callId:reason:)","abstract":[{"type":"text","text":"Called when a call cancellation attempt fails."}],"url":"\/documentation\/pushwooshvoip\/pwvoipcalldelegate\/voipdidfailtocancelcall(callid:reason:)","title":"voipDidFailToCancelCall(callId:reason:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"voipDidFailToCancelCall"},{"kind":"text","text":"("},{"kind":"externalParam","text":"callId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"text":"reason","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}],"type":"topic","kind":"symbol"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPCallDelegate":{"title":"PWVoIPCallDelegate","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate","url":"\/documentation\/pushwooshvoip\/pwvoipcalldelegate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PWVoIPCallDelegate"}],"abstract":[{"type":"text","text":"Delegate protocol for receiving VoIP call events and CallKit callbacks."}],"kind":"symbol","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"PWVoIPCallDelegate","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"voipDidFailToCancelCallWithCallId:reason:","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"voipDidFailToCancelCallWithCallId:reason:"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"voipDidFailToCancelCallWithCallId:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"callId"},{"text":" ","kind":"text"},{"text":"reason:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"reason"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"voipDidFailToCancelCallWithCallId:reason:","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate~1voipDidFailToCancelCall(callId:reason:)\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate~1voipDidFailToCancelCall(callId:reason:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"voipDidFailToCancelCallWithCallId:reason:","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"PWVoIPCallDelegate","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate\/title"},{"value":[{"text":"PWVoIPCallDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate\/fragments"}]}]}