{"variants":[{"paths":["\/documentation\/pushwooshframework"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pushwooshframework"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"hierarchy":{"paths":[[]]},"metadata":{"modules":[{"name":"PushwooshFramework"}],"role":"collection","symbolKind":"module","title":"PushwooshFramework","roleHeading":"Framework","externalID":"PushwooshFramework"},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"text":"Push notification SDK for iOS applications.","type":"text"}],"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","interfaceLanguage":"swift"},"topicSections":[{"title":"Getting Started","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/QuickStart","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/GettingStarted","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/AdvancedIntegration"]},{"title":"Classes","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWNotificationCenterDelegateProxy","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWNotificationExtensionManager","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWTags","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWTagsBuilder","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh"]},{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWMessagingDelegate","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWPurchaseDelegate","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationDelegate"],"title":"Protocols"},{"title":"Variables","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PUSHWOOSH_VERSION"]},{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushwooshErrorHandler","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushwooshGetTagsHandler"],"title":"Type Aliases"},{"title":"Type Properties","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Foundation\/NSNotification\/Name\/PWInboxMessagesDidUpdate"]},{"title":"Extended Modules","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Foundation","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushwooshCore"]}],"primaryContentSections":[{"kind":"content","content":[{"anchor":"Overview","text":"Overview","level":2,"type":"heading"},{"type":"paragraph","inlineContent":[{"text":"PushwooshiOS provides a comprehensive solution for integrating push notifications into iOS applications. The SDK handles device registration, token management, notification delivery, and rich media content display automatically.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"Key features include:","type":"text"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Remote and local push notification support","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Rich media notifications with HTML content"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"In-app messaging"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"User tags and attributes"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Geolocation tracking"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Inbox functionality","type":"text"}]}]}]}]}],"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"url":"\/documentation\/pushwooshframework","kind":"symbol","abstract":[{"text":"Push notification SDK for iOS applications.","type":"text"}],"type":"topic","role":"collection","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","title":"PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWTags":{"kind":"symbol","title":"PWTags","url":"\/documentation\/pushwooshframework\/pwtags","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWTags","navigatorTitle":[{"kind":"identifier","text":"PWTags"}],"type":"topic","role":"symbol","abstract":[{"code":"PWTags","type":"codeVoice"},{"text":" class encapsulates the methods for creating tags parameters for sending them to the server.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PWTags"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationDelegate":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationDelegate","kind":"symbol","abstract":[{"type":"codeVoice","code":"PushNotificationDelegate"},{"type":"text","text":" protocol defines the methods that can be implemented in the delegate of the "},{"code":"PushNotificationManager","type":"codeVoice"},{"type":"text","text":" class’ singleton object."},{"text":" ","type":"text"},{"text":"These methods provide information about the key events for push notification manager such as registering with APS services, receiving push notifications or working with the received notification.","type":"text"},{"text":" ","type":"text"},{"text":"These methods implementation allows to react on these events properly.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"PushNotificationDelegate","kind":"identifier"}],"url":"\/documentation\/pushwooshframework\/pushnotificationdelegate","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"PushNotificationDelegate","kind":"identifier"}],"title":"PushNotificationDelegate"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWNotificationCenterDelegateProxy":{"kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWNotificationCenterDelegateProxy","url":"\/documentation\/pushwooshframework\/pwnotificationcenterdelegateproxy","type":"topic","abstract":[],"title":"PWNotificationCenterDelegateProxy","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PWNotificationCenterDelegateProxy","kind":"identifier"}],"navigatorTitle":[{"text":"PWNotificationCenterDelegateProxy","kind":"identifier"}],"role":"symbol"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/AdvancedIntegration":{"url":"\/documentation\/pushwooshframework\/advancedintegration","abstract":[{"type":"text","text":"Advanced configuration options for Pushwoosh iOS SDK integration."}],"role":"article","kind":"article","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/AdvancedIntegration","title":"Advanced Integration Guide","type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Foundation":{"kind":"symbol","title":"Foundation","role":"collection","abstract":[],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Foundation","type":"topic","url":"\/documentation\/pushwooshframework\/foundation"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Foundation/NSNotification/Name/PWInboxMessagesDidUpdate":{"abstract":[{"text":"The notification arriving on the Inbox messages renewal","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"PWInboxMessagesDidUpdateNotification"}],"title":"PWInboxMessagesDidUpdate","type":"topic","url":"\/documentation\/pushwooshframework\/foundation\/nsnotification\/name\/pwinboxmessagesdidupdate","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PWInboxMessagesDidUpdate"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNotification","text":"NSNotification"},{"text":".","kind":"text"},{"text":"Name","preciseIdentifier":"c:@T@NSNotificationName","kind":"typeIdentifier"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Foundation\/NSNotification\/Name\/PWInboxMessagesDidUpdate"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushwooshErrorHandler":{"kind":"symbol","url":"\/documentation\/pushwooshframework\/pushwoosherrorhandler","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushwooshErrorHandler","type":"topic","abstract":[{"text":"Completion handler called when an operation fails.","type":"text"}],"title":"PushwooshErrorHandler","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"PushwooshErrorHandler","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PushwooshErrorHandler"}],"role":"symbol"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInbox":{"abstract":[],"navigatorTitle":[{"text":"PWInbox","kind":"identifier"}],"title":"PWInbox","type":"topic","url":"\/documentation\/pushwooshframework\/pwinbox","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PWInbox","kind":"identifier"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationManager":{"url":"\/documentation\/pushwooshframework\/pushnotificationmanager","kind":"symbol","abstract":[{"code":"PushNotificationManager","type":"codeVoice"},{"text":" class offers access to the singleton-instance of the push manager responsible for registering the device with the APS servers, receiving and processing push notifications.","type":"text"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager","navigatorTitle":[{"text":"PushNotificationManager","kind":"identifier"}],"title":"PushNotificationManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PushNotificationManager","kind":"identifier"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWTagsBuilder":{"navigatorTitle":[{"text":"PWTagsBuilder","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PWTagsBuilder"}],"kind":"symbol","title":"PWTagsBuilder","role":"symbol","abstract":[{"code":"PWTagsBuilder","type":"codeVoice"},{"text":" class encapsulates the methods for creating tags parameters for sending them to the server.","type":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWTagsBuilder","type":"topic","url":"\/documentation\/pushwooshframework\/pwtagsbuilder"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWPurchaseDelegate":{"url":"\/documentation\/pushwooshframework\/pwpurchasedelegate","abstract":[{"type":"text","text":"Delegate protocol for handling in-app purchase events from rich media."}],"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWPurchaseDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"PWPurchaseDelegate","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"PWPurchaseDelegate","navigatorTitle":[{"kind":"identifier","text":"PWPurchaseDelegate"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWMessagingDelegate":{"kind":"symbol","url":"\/documentation\/pushwooshframework\/pwmessagingdelegate","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWMessagingDelegate","type":"topic","abstract":[{"type":"text","text":"Delegate protocol for handling push notification events."}],"title":"PWMessagingDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PWMessagingDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"PWMessagingDelegate","kind":"identifier"}],"role":"symbol"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWNotificationExtensionManager":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWNotificationExtensionManager","abstract":[],"type":"topic","url":"\/documentation\/pushwooshframework\/pwnotificationextensionmanager","title":"PWNotificationExtensionManager","role":"symbol","navigatorTitle":[{"text":"PWNotificationExtensionManager","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PWNotificationExtensionManager","kind":"identifier"}],"kind":"symbol"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushwooshRegistrationHandler":{"fragments":[{"text":"PushwooshRegistrationHandler","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/pushwooshframework\/pushwooshregistrationhandler","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushwooshRegistrationHandler","title":"PushwooshRegistrationHandler","abstract":[{"type":"text","text":"Completion handler called when push notification registration completes."}],"role":"symbol"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/GettingStarted":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/GettingStarted","abstract":[{"type":"text","text":"Set up push notifications in your iOS application with Pushwoosh SDK."}],"type":"topic","url":"\/documentation\/pushwooshframework\/gettingstarted","title":"Getting Started","role":"article","kind":"article"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushwooshCore":{"title":"PushwooshCore","role":"collection","abstract":[],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushwooshCore","url":"\/documentation\/pushwooshframework\/pushwooshcore","kind":"symbol","type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PUSHWOOSH_VERSION":{"navigatorTitle":[{"kind":"identifier","text":"PUSHWOOSH_VERSION"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PUSHWOOSH_VERSION","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"kind":"symbol","title":"PUSHWOOSH_VERSION","role":"symbol","abstract":[{"text":"The current version of the Pushwoosh SDK.","type":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PUSHWOOSH_VERSION","type":"topic","url":"\/documentation\/pushwooshframework\/pushwoosh_version"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh":{"abstract":[{"text":"Main SDK interface for push notification management.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"Pushwoosh"}],"type":"topic","url":"\/documentation\/pushwooshframework\/pushwoosh","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Pushwoosh","kind":"identifier"}],"title":"Pushwoosh"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/QuickStart":{"title":"Quick Start","kind":"article","role":"article","abstract":[{"text":"Get your first push notification running in minutes.","type":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/QuickStart","type":"topic","url":"\/documentation\/pushwooshframework\/quickstart"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushwooshGetTagsHandler":{"kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushwooshGetTagsHandler","url":"\/documentation\/pushwooshframework\/pushwooshgettagshandler","type":"topic","abstract":[{"text":"Completion handler called when tags are successfully retrieved from the server.","type":"text"}],"title":"PushwooshGetTagsHandler","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PushwooshGetTagsHandler"}],"navigatorTitle":[{"kind":"identifier","text":"PushwooshGetTagsHandler"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/QuickStart","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/GettingStarted","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/AdvancedIntegration"],"title":"Getting Started"},{"title":"Classes","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWNotificationCenterDelegateProxy","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWNotificationExtensionManager","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWTags","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWTagsBuilder","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh"]},{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWMessagingDelegate","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWPurchaseDelegate","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationDelegate"],"title":"Protocols"},{"title":"Variables","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Foundation\/NSNotification\/Name\/PWInboxMessagesDidUpdate"]},{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PUSHWOOSH_VERSION"],"title":"Macros"},{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushwooshErrorHandler","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushwooshGetTagsHandler","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushwooshRegistrationHandler"],"title":"Type Aliases"}],"op":"replace"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWTags\/title","value":"PWTags"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWTags\/fragments","value":[{"text":"PWTags","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationDelegate\/title","value":"PushNotificationDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationDelegate\/fragments","value":[{"text":"PushNotificationDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWNotificationCenterDelegateProxy\/title","value":"PWNotificationCenterDelegateProxy"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWNotificationCenterDelegateProxy\/fragments","value":[{"text":"PWNotificationCenterDelegateProxy","kind":"identifier"}],"op":"replace"},{"value":"PWInboxMessagesDidUpdateNotification","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Foundation~1NSNotification~1Name~1PWInboxMessagesDidUpdate\/title"},{"op":"replace","value":[{"kind":"identifier","text":"PWInboxMessagesDidUpdateNotification"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Foundation~1NSNotification~1Name~1PWInboxMessagesDidUpdate\/fragments"},{"value":"PushwooshErrorHandler","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushwooshErrorHandler\/title"},{"value":[{"kind":"identifier","text":"PushwooshErrorHandler"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushwooshErrorHandler\/fragments","op":"replace"},{"value":"PWInbox","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInbox\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInbox\/fragments","value":[{"text":"PWInbox","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager\/title","op":"replace","value":"PushNotificationManager"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager\/fragments","value":[{"text":"PushNotificationManager","kind":"identifier"}]},{"value":"PWTagsBuilder","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWTagsBuilder\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWTagsBuilder\/fragments","op":"replace","value":[{"text":"PWTagsBuilder","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWPurchaseDelegate\/title","value":"PWPurchaseDelegate","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWPurchaseDelegate\/fragments","value":[{"text":"PWPurchaseDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWMessagingDelegate\/title","value":"PWMessagingDelegate","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWMessagingDelegate\/fragments","value":[{"kind":"identifier","text":"PWMessagingDelegate"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWNotificationExtensionManager\/title","value":"PWNotificationExtensionManager"},{"value":[{"kind":"identifier","text":"PWNotificationExtensionManager"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWNotificationExtensionManager\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PUSHWOOSH_VERSION\/title","value":"PUSHWOOSH_VERSION"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PUSHWOOSH_VERSION\/fragments","op":"replace","value":[{"kind":"identifier","text":"PUSHWOOSH_VERSION"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh\/title","value":"Pushwoosh"},{"value":[{"text":"Pushwoosh","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushwooshGetTagsHandler\/title","value":"PushwooshGetTagsHandler"},{"value":[{"kind":"identifier","text":"PushwooshGetTagsHandler"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushwooshGetTagsHandler\/fragments"}]}]}