{"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/additionalAuthorizationOptions","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"Additional notification authorization options beyond the SDK defaults."}],"seeAlsoSections":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/registerForPushNotifications()"],"title":"Related Documentation"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh"]]},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"additionalAuthorizationOptions"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UNAuthorizationOptions","preciseIdentifier":"c:@E@UNAuthorizationOptions"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","anchor":"Overview","level":2,"text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"When the SDK calls "},{"type":"codeVoice","code":"registerForPushNotifications"},{"type":"text","text":", it automatically requests these permissions:"}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"code":".badge","type":"codeVoice"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"code":".sound","type":"codeVoice"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":".alert"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"code":".carPlay","type":"codeVoice"}]}]}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Use "},{"code":"setAdditionalAuthorizationOptions","type":"codeVoice"},{"text":" to request extra capabilities on top of the defaults. The options are combined (bitwise OR) with the defaults before being passed to ","type":"text"},{"type":"codeVoice","code":"UNUserNotificationCenter.requestAuthorization(options:)"},{"text":".","type":"text"}]},{"text":"Available Options","type":"heading","level":3,"anchor":"Available-Options"},{"header":"row","rows":[[[{"inlineContent":[{"text":"Option","type":"text"}],"type":"paragraph"}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"iOS"}]}],[{"inlineContent":[{"text":"Description","type":"text"}],"type":"paragraph"}]],[[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":".provisional"}]}],[{"inlineContent":[{"type":"text","text":"12+"}],"type":"paragraph"}],[{"inlineContent":[{"type":"text","text":"Deliver notifications quietly without showing a permission dialog. Users see them in Notification Center and decide whether to keep or disable."}],"type":"paragraph"}]],[[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":".criticalAlert"}]}],[{"type":"paragraph","inlineContent":[{"text":"12+","type":"text"}]}],[{"inlineContent":[{"type":"text","text":"Bypass Do Not Disturb and the mute switch. Requires a special entitlement from Apple. For medical, health, safety, and public security apps."}],"type":"paragraph"}]],[[{"inlineContent":[{"code":".providesAppNotificationSettings","type":"codeVoice"}],"type":"paragraph"}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"12+"}]}],[{"inlineContent":[{"type":"text","text":"Adds a “Configure in App” button in the system notification settings. When tapped, iOS calls "},{"code":"userNotificationCenter(_:openSettingsFor:)","type":"codeVoice"},{"text":" on your delegate.","type":"text"}],"type":"paragraph"}]],[[{"inlineContent":[{"code":".announcement","type":"codeVoice"}],"type":"paragraph"}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"13+"}]}],[{"type":"paragraph","inlineContent":[{"text":"Allows Siri to read notifications aloud through AirPods and compatible headphones.","type":"text"}]}]]],"type":"table"},{"level":2,"type":"heading","anchor":"Important","text":"Important"},{"inlineContent":[{"type":"text","text":"Call "},{"type":"codeVoice","code":"setAdditionalAuthorizationOptions"},{"text":" ","type":"text"},{"inlineContent":[{"type":"text","text":"before"}],"type":"strong"},{"type":"text","text":" "},{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/registerForPushNotifications()","isActive":true,"type":"reference"},{"type":"text","text":". Options set after registration have no effect until the next authorization request."}],"type":"paragraph"},{"level":2,"text":"Provisional (Soft Opt-In)","type":"heading","anchor":"Provisional-Soft-Opt-In"},{"inlineContent":[{"text":"Deliver notifications silently without prompting the user for permission. This is useful to demonstrate value before asking for full notification access:","type":"text"}],"type":"paragraph"},{"type":"codeListing","code":["func application(_ application: UIApplication,","                didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {","","    if #available(iOS 12.0, *) {","        Pushwoosh.configure.setAdditionalAuthorizationOptions([.provisional])","    }","","    Pushwoosh.configure.registerForPushNotifications()","","    return true","}"],"syntax":"swift"},{"type":"heading","level":2,"text":"In-App Notification Settings","anchor":"In-App-Notification-Settings"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Add a “Configure in App” button to the system Settings > Notifications screen for your app. When the user taps it, implement the "},{"type":"codeVoice","code":"openSettingsFor"},{"text":" callback to navigate to your custom settings screen:","type":"text"}]},{"type":"codeListing","syntax":"swift","code":["func application(_ application: UIApplication,","                didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {","","    if #available(iOS 12.0, *) {","        Pushwoosh.configure.setAdditionalAuthorizationOptions([.providesAppNotificationSettings])","    }","","    Pushwoosh.configure.addNotificationCenterDelegate(self)","    Pushwoosh.configure.registerForPushNotifications()","","    return true","}","","\/\/ Called when user taps \"Configure in App\" in system notification settings","func userNotificationCenter(_ center: UNUserNotificationCenter,","                            openSettingsFor notification: UNNotification?) {","    \/\/ Navigate to your in-app notification settings screen","}"]},{"level":2,"anchor":"Critical-Alerts","text":"Critical Alerts","type":"heading"},{"inlineContent":[{"text":"For medical, health, and safety apps that need to bypass Do Not Disturb and the mute switch. Requires a special entitlement approved by Apple:","type":"text"}],"type":"paragraph"},{"syntax":"swift","type":"codeListing","code":["if #available(iOS 12.0, *) {","    Pushwoosh.configure.setAdditionalAuthorizationOptions([.criticalAlert])","}","","Pushwoosh.configure.registerForPushNotifications()"]},{"type":"heading","text":"Combining Multiple Options","level":2,"anchor":"Combining-Multiple-Options"},{"type":"paragraph","inlineContent":[{"text":"Options can be combined:","type":"text"}]},{"code":["if #available(iOS 12.0, *) {","    Pushwoosh.configure.setAdditionalAuthorizationOptions([.provisional, .providesAppNotificationSettings])","}"],"syntax":"swift","type":"codeListing"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Objective-C:"}]},{"code":["if (@available(iOS 12.0, *)) {","    [Pushwoosh.configure setAdditionalAuthorizationOptions:UNAuthorizationOptionProvisional | UNAuthorizationOptionProvidesAppNotificationSettings];","}","","[Pushwoosh.configure registerForPushNotifications];"],"syntax":"objc","type":"codeListing"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pushwoosh\/additionalauthorizationoptions"]},{"paths":["\/documentation\/pushwooshframework\/pushwoosh\/additionalauthorizationoptions"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"symbol","title":"additionalAuthorizationOptions","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"additionalAuthorizationOptions"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@UNAuthorizationOptions","text":"UNAuthorizationOptions","kind":"typeIdentifier"}],"modules":[{"name":"PushwooshFramework"}],"roleHeading":"Instance Property","symbolKind":"property","externalID":"c:objc(cs)Pushwoosh(py)additionalAuthorizationOptions","platforms":[{"introducedAt":"12.0","deprecated":false,"beta":false,"unavailable":false,"name":"iOS"}],"navigatorTitle":[{"text":"additionalAuthorizationOptions","kind":"identifier"}]},"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh":{"title":"Pushwoosh","abstract":[{"type":"text","text":"Main SDK interface for push notification management."}],"kind":"symbol","url":"\/documentation\/pushwooshframework\/pushwoosh","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Pushwoosh","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Pushwoosh"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/registerForPushNotifications()":{"abstract":[{"type":"text","text":"Registers the device for push notifications."}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/registerForPushNotifications()","url":"\/documentation\/pushwooshframework\/pushwoosh\/registerforpushnotifications()","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"registerForPushNotifications","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"registerForPushNotifications","kind":"identifier"}],"title":"registerForPushNotifications()","kind":"symbol","type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"type":"topic","abstract":[{"text":"Push notification SDK for iOS applications.","type":"text"}],"title":"PushwooshFramework","url":"\/documentation\/pushwooshframework","kind":"symbol","role":"collection","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/additionalAuthorizationOptions":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"additionalAuthorizationOptions"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@UNAuthorizationOptions","kind":"typeIdentifier","text":"UNAuthorizationOptions"}],"title":"additionalAuthorizationOptions","kind":"symbol","abstract":[{"type":"text","text":"Additional notification authorization options beyond the SDK defaults."}],"type":"topic","url":"\/documentation\/pushwooshframework\/pushwoosh\/additionalauthorizationoptions","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/additionalAuthorizationOptions","navigatorTitle":[{"text":"additionalAuthorizationOptions","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":[{"name":"iOS","introducedAt":"12.0","deprecated":false,"unavailable":false,"beta":false}],"op":"replace","path":"\/metadata\/platforms"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"additionalAuthorizationOptions"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"text":"additionalAuthorizationOptions","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"replace","value":[{"title":"Related Documentation","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/registerForPushNotifications()"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@UNAuthorizationOptions","text":"UNAuthorizationOptions"},{"kind":"text","text":" "},{"kind":"identifier","text":"additionalAuthorizationOptions"},{"kind":"text","text":";"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh\/title","value":"Pushwoosh"},{"value":[{"text":"Pushwoosh","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1registerForPushNotifications()\/title","value":"registerForPushNotifications"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1registerForPushNotifications()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"registerForPushNotifications","kind":"identifier"}]},{"op":"replace","value":"additionalAuthorizationOptions","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1additionalAuthorizationOptions\/title"},{"value":[{"text":"additionalAuthorizationOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1additionalAuthorizationOptions\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}