{"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/applicationCode"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"applicationCode"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"content":[{"type":"heading","text":"Overview","level":2,"anchor":"Overview"},{"inlineContent":[{"type":"text","text":"Your unique Pushwoosh Application Code that identifies your app. This value is typically configured in Info.plist with key "},{"type":"codeVoice","code":"Pushwoosh_APPID"},{"text":".","type":"text"}],"type":"paragraph"},{"level":2,"text":"Configuration","type":"heading","anchor":"Configuration"},{"type":"paragraph","inlineContent":[{"text":"Set in Info.plist:","type":"text"}]},{"code":["<key>Pushwoosh_APPID<\/key>","<string>XXXXX-XXXXX<\/string>"],"type":"codeListing","syntax":"xml"},{"inlineContent":[{"type":"text","text":"Or programmatically before registration:"}],"type":"paragraph"},{"type":"codeListing","syntax":"swift","code":["Pushwoosh.configure.setAppCode(\"XXXXX-XXXXX\")"]},{"anchor":"Example","text":"Example","level":2,"type":"heading"},{"inlineContent":[{"text":"Include app code in diagnostics:","type":"text"}],"type":"paragraph"},{"code":["func createDiagnosticReport() -> DiagnosticReport {","    return DiagnosticReport(","        appCode: Pushwoosh.configure.applicationCode ?? \"Not configured\",","        hwid: Pushwoosh.configure.getHWID(),","        pushToken: Pushwoosh.configure.getPushToken(),","        sdkVersion: Pushwoosh.version()","    )","}"],"syntax":"swift","type":"codeListing"},{"inlineContent":[{"type":"text","text":"Verify configuration:"}],"type":"paragraph"},{"syntax":"swift","type":"codeListing","code":["func verifyPushwooshSetup() -> Bool {","    guard let appCode = Pushwoosh.configure.applicationCode,","          !appCode.isEmpty else {","        print(\"Pushwoosh App Code not configured\")","        return false","    }","    return true","}"]}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pushwoosh\/applicationcode"]},{"paths":["\/documentation\/pushwooshframework\/pushwoosh\/applicationcode"],"traits":[{"interfaceLanguage":"occ"}]}],"seeAlsoSections":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/getHWID()","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/version()"],"title":"Related Documentation"}],"metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"applicationCode"}],"externalID":"c:objc(cs)Pushwoosh(py)applicationCode","modules":[{"name":"PushwooshFramework"}],"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"applicationCode"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"title":"applicationCode","roleHeading":"Instance Property"},"sections":[],"abstract":[{"text":"The Pushwoosh Application ID.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh"]]},"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/version()":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"version"}],"kind":"symbol","title":"version()","url":"\/documentation\/pushwooshframework\/pushwoosh\/version()","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"version","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/version()","abstract":[{"type":"text","text":"Returns the Pushwoosh SDK version."}],"type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/getHWID()":{"navigatorTitle":[{"text":"getHWID","kind":"identifier"}],"kind":"symbol","title":"getHWID()","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/getHWID()","url":"\/documentation\/pushwooshframework\/pushwoosh\/gethwid()","role":"symbol","abstract":[{"type":"text","text":"Returns the Pushwoosh Hardware ID (HWID) for this device."}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"getHWID","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"type":"topic","role":"collection","kind":"symbol","abstract":[{"text":"Push notification SDK for iOS applications.","type":"text"}],"url":"\/documentation\/pushwooshframework","title":"PushwooshFramework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/applicationCode":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/applicationCode","abstract":[{"text":"The Pushwoosh Application ID.","type":"text"}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"applicationCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"title":"applicationCode","type":"topic","url":"\/documentation\/pushwooshframework\/pushwoosh\/applicationcode","role":"symbol","navigatorTitle":[{"text":"applicationCode","kind":"identifier"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh","title":"Pushwoosh","url":"\/documentation\/pushwooshframework\/pushwoosh","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Pushwoosh","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Pushwoosh"}],"abstract":[{"text":"Main SDK interface for push notification management.","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","value":"applicationCode","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"applicationCode"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"replace","value":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/getHWID()","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/version()"],"title":"Related Documentation"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"identifier","text":"applicationCode"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"version","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1version()\/title"},{"value":[{"kind":"text","text":"+ "},{"text":"version","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1version()\/fragments"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1getHWID()\/title","op":"replace","value":"getHWID"},{"value":[{"text":"- ","kind":"text"},{"text":"getHWID","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1getHWID()\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1applicationCode\/title","value":"applicationCode"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1applicationCode\/fragments","value":[{"text":"applicationCode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh\/title","value":"Pushwoosh"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh\/fragments","value":[{"text":"Pushwoosh","kind":"identifier"}]}]}]}