{"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"text":"Clears all notifications from the notification center.","type":"text"}],"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/clearNotificationCenter()","interfaceLanguage":"swift"},"sections":[],"seeAlsoSections":[{"title":"Related Documentation","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/sendBadges(_:)"]}],"metadata":{"navigatorTitle":[{"text":"clearNotificationCenter","kind":"identifier"}],"roleHeading":"Type Method","role":"symbol","modules":[{"name":"PushwooshFramework"}],"externalID":"c:objc(cs)Pushwoosh(cm)clearNotificationCenter","symbolKind":"method","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"clearNotificationCenter"},{"kind":"text","text":"()"}],"title":"clearNotificationCenter()"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pushwoosh\/clearnotificationcenter()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pushwoosh\/clearnotificationcenter()"]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"clearNotificationCenter"},{"text":"()","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"anchor":"Overview","text":"Overview","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"Removes all delivered notifications for your app from iOS Notification Center. Use this to:"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"Clean up when user opens the app"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Clear notifications after user reads content"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Remove outdated notifications","type":"text"}]}]},{"content":[{"inlineContent":[{"text":"Provide a fresh notification experience","type":"text"}],"type":"paragraph"}]}]},{"anchor":"Example","level":2,"text":"Example","type":"heading"},{"inlineContent":[{"type":"text","text":"Clear notifications when app becomes active:"}],"type":"paragraph"},{"type":"codeListing","code":["func applicationDidBecomeActive(_ application: UIApplication) {","    Pushwoosh.configure.clearNotificationCenter()","","    UIApplication.shared.applicationIconBadgeNumber = 0","    Pushwoosh.configure.sendBadges(0)","}"],"syntax":"swift"},{"inlineContent":[{"text":"Clear notifications when user views notification inbox:","type":"text"}],"type":"paragraph"},{"syntax":"swift","code":["func viewWillAppear(_ animated: Bool) {","    super.viewWillAppear(animated)","","    Pushwoosh.configure.clearNotificationCenter()","    loadInboxMessages()","}"],"type":"codeListing"},{"type":"paragraph","inlineContent":[{"text":"Clear after handling notification:","type":"text"}]},{"syntax":"swift","code":["func pushwoosh(_ pushwoosh: Pushwoosh, onMessageOpened message: PWMessage) {","    handleDeepLink(from: message)","","    Pushwoosh.configure.clearNotificationCenter()","}"],"type":"codeListing"}]}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh"]]},"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/clearNotificationCenter()":{"navigatorTitle":[{"kind":"identifier","text":"clearNotificationCenter"}],"url":"\/documentation\/pushwooshframework\/pushwoosh\/clearnotificationcenter()","role":"symbol","title":"clearNotificationCenter()","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"clearNotificationCenter","kind":"identifier"},{"kind":"text","text":"()"}],"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/clearNotificationCenter()","kind":"symbol","abstract":[{"type":"text","text":"Clears all notifications from the notification center."}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/sendBadges(_:)":{"abstract":[{"text":"Synchronizes the application badge number with Pushwoosh servers.","type":"text"}],"role":"symbol","title":"sendBadges(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendBadges"},{"text":"(","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"sendBadges:"}],"url":"\/documentation\/pushwooshframework\/pushwoosh\/sendbadges(_:)","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/sendBadges(_:)","type":"topic","kind":"symbol"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","kind":"symbol","role":"collection","title":"PushwooshFramework","url":"\/documentation\/pushwooshframework","type":"topic","abstract":[{"text":"Push notification SDK for iOS applications.","type":"text"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh":{"title":"Pushwoosh","navigatorTitle":[{"kind":"identifier","text":"Pushwoosh"}],"abstract":[{"text":"Main SDK interface for push notification management.","type":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh","url":"\/documentation\/pushwooshframework\/pushwoosh","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Pushwoosh","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"clearNotificationCenter","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"clearNotificationCenter"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"replace","value":[{"title":"Related Documentation","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/sendBadges(_:)"]}],"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"clearNotificationCenter"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"clearNotificationCenter","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1clearNotificationCenter()\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1clearNotificationCenter()\/fragments","value":[{"kind":"text","text":"+ "},{"text":"clearNotificationCenter","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1sendBadges(_:)\/title","op":"replace","value":"sendBadges:"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1sendBadges(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"sendBadges:","kind":"identifier"}],"op":"replace"},{"value":"Pushwoosh","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh\/fragments","value":[{"text":"Pushwoosh","kind":"identifier"}]}]}]}