{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/delegate"},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"weak"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"delegate"},{"text":": (any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)PWMessagingDelegate","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWMessagingDelegate","text":"PWMessagingDelegate"},{"kind":"text","text":")? { "},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}]},{"content":[{"level":2,"type":"heading","anchor":"Overview","text":"Overview"},{"inlineContent":[{"type":"text","text":"Set this property to receive callbacks when:"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Push notifications are received","type":"text"}]}]},{"content":[{"inlineContent":[{"text":"User taps on a push notification","type":"text"}],"type":"paragraph"}]}]},{"inlineContent":[{"type":"text","text":"The delegate must conform to "},{"isActive":true,"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWMessagingDelegate","type":"reference"},{"type":"text","text":" protocol."}],"type":"paragraph"},{"type":"heading","level":2,"anchor":"Default-Behavior","text":"Default Behavior"},{"type":"paragraph","inlineContent":[{"type":"text","text":"By default, Pushwoosh sets "},{"code":"AppDelegate","type":"codeVoice"},{"type":"text","text":" as the delegate if it conforms to "},{"code":"PWMessagingDelegate","type":"codeVoice"},{"type":"text","text":". You can override this with any other object."}]},{"anchor":"Example","level":2,"type":"heading","text":"Example"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Set delegate in AppDelegate:"}]},{"type":"codeListing","code":["func application(_ application: UIApplication,","                didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {","","    Pushwoosh.configure.delegate = self","    Pushwoosh.configure.registerForPushNotifications()","","    return true","}"],"syntax":"swift"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Use a dedicated notification handler:"}]},{"syntax":"swift","type":"codeListing","code":["class NotificationHandler: NSObject, PWMessagingDelegate {","    static let shared = NotificationHandler()","","    func pushwoosh(_ pushwoosh: Pushwoosh, onMessageReceived message: PWMessage) {","        NotificationCenter.default.post(","            name: .pushReceived,","            object: nil,","            userInfo: [\"message\": message]","        )","    }","","    func pushwoosh(_ pushwoosh: Pushwoosh, onMessageOpened message: PWMessage) {","        DeepLinkRouter.shared.handle(message.customData)","    }","}","","\/\/ In AppDelegate","Pushwoosh.configure.delegate = NotificationHandler.shared"]}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pushwoosh\/delegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pushwoosh\/delegate"]}],"seeAlsoSections":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWMessagingDelegate","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWMessagingDelegate\/pushwoosh(_:onMessageReceived:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWMessagingDelegate\/pushwoosh(_:onMessageOpened:)"],"title":"Related Documentation"}],"kind":"symbol","metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": (any "},{"text":"PWMessagingDelegate","preciseIdentifier":"c:objc(pl)PWMessagingDelegate","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"modules":[{"name":"PushwooshFramework"}],"externalID":"c:objc(cs)Pushwoosh(py)delegate","navigatorTitle":[{"text":"delegate","kind":"identifier"}],"roleHeading":"Instance Property","title":"delegate","role":"symbol","symbolKind":"property"},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh"]]},"abstract":[{"type":"text","text":"Delegate that receives push notification events."}],"sections":[],"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/delegate":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/delegate","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"kind":"text","text":": (any "},{"preciseIdentifier":"c:objc(pl)PWMessagingDelegate","kind":"typeIdentifier","text":"PWMessagingDelegate"},{"kind":"text","text":")?"}],"url":"\/documentation\/pushwooshframework\/pushwoosh\/delegate","type":"topic","kind":"symbol","navigatorTitle":[{"text":"delegate","kind":"identifier"}],"title":"delegate","abstract":[{"type":"text","text":"Delegate that receives push notification events."}],"role":"symbol"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh":{"abstract":[{"type":"text","text":"Main SDK interface for push notification management."}],"navigatorTitle":[{"kind":"identifier","text":"Pushwoosh"}],"title":"Pushwoosh","url":"\/documentation\/pushwooshframework\/pushwoosh","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Pushwoosh","kind":"identifier"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"type":"topic","kind":"symbol","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","title":"PushwooshFramework","abstract":[{"type":"text","text":"Push notification SDK for iOS applications."}],"role":"collection"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWMessagingDelegate":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWMessagingDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PWMessagingDelegate"}],"url":"\/documentation\/pushwooshframework\/pwmessagingdelegate","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PWMessagingDelegate"}],"title":"PWMessagingDelegate","abstract":[{"type":"text","text":"Delegate protocol for handling push notification events."}],"role":"symbol"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWMessagingDelegate/pushwoosh(_:onMessageOpened:)":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWMessagingDelegate\/pushwoosh(_:onMessageOpened:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pushwoosh"},{"text":"(","kind":"text"},{"text":"Pushwoosh","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)Pushwoosh"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"onMessageOpened"},{"text":": ","kind":"text"},{"text":"PWMessage","preciseIdentifier":"c:objc(cs)PWMessage","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/pushwooshframework\/pwmessagingdelegate\/pushwoosh(_:onmessageopened:)","type":"topic","kind":"symbol","navigatorTitle":[{"text":"pushwoosh:onMessageOpened:","kind":"identifier"}],"title":"pushwoosh(_:onMessageOpened:)","abstract":[{"type":"text","text":"Called when the user taps on a push notification."}],"required":true},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWMessagingDelegate/pushwoosh(_:onMessageReceived:)":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWMessagingDelegate\/pushwoosh(_:onMessageReceived:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pushwoosh","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"Pushwoosh","preciseIdentifier":"c:objc(cs)Pushwoosh"},{"text":", ","kind":"text"},{"text":"onMessageReceived","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"PWMessage","preciseIdentifier":"c:objc(cs)PWMessage"},{"kind":"text","text":")"}],"url":"\/documentation\/pushwooshframework\/pwmessagingdelegate\/pushwoosh(_:onmessagereceived:)","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"pushwoosh:onMessageReceived:"}],"title":"pushwoosh(_:onMessageReceived:)","abstract":[{"type":"text","text":"Called when the application receives a push notification."}],"required":true}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"delegate","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"delegate","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"replace","value":[{"title":"Related Documentation","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWMessagingDelegate","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWMessagingDelegate\/pushwoosh(_:onMessageReceived:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWMessagingDelegate\/pushwoosh(_:onMessageOpened:)"]}]},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"weak"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"NSObject<PWMessagingDelegate>","preciseIdentifier":"c:Q$objc(cs)NSObjectobjc(pl)PWMessagingDelegate"},{"kind":"text","text":" * "},{"kind":"identifier","text":"delegate"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"value":"delegate","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1delegate\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1delegate\/fragments","op":"replace","value":[{"text":"delegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh\/title","value":"Pushwoosh"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh\/fragments","value":[{"text":"Pushwoosh","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWMessagingDelegate\/title","value":"PWMessagingDelegate","op":"replace"},{"value":[{"text":"PWMessagingDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWMessagingDelegate\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWMessagingDelegate~1pushwoosh(_:onMessageOpened:)\/title","value":"pushwoosh:onMessageOpened:"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWMessagingDelegate~1pushwoosh(_:onMessageOpened:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"pushwoosh:onMessageOpened:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWMessagingDelegate~1pushwoosh(_:onMessageReceived:)\/title","value":"pushwoosh:onMessageReceived:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"pushwoosh:onMessageReceived:"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWMessagingDelegate~1pushwoosh(_:onMessageReceived:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}