{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pushwoosh\/disablereverseproxy()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pushwoosh\/disablereverseproxy()"]}],"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/disableReverseProxy()","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","abstract":[{"text":"Disables reverse proxy configuration.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh"]]},"metadata":{"role":"symbol","modules":[{"name":"PushwooshFramework"}],"roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"disableReverseProxy","kind":"identifier"},{"kind":"text","text":"()"}],"symbolKind":"method","title":"disableReverseProxy()","navigatorTitle":[{"text":"disableReverseProxy","kind":"identifier"}],"externalID":"c:objc(cs)Pushwoosh(im)disableReverseProxy"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"disableReverseProxy","kind":"identifier"},{"text":"()","kind":"text"}]}]},{"kind":"content","content":[{"level":2,"text":"Discussion","anchor":"Discussion","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Reverts API requests to use the default Pushwoosh server URLs. Call this method to restore normal operation after previously configuring a reverse proxy with "},{"type":"codeVoice","code":"setReverseProxy:"},{"type":"text","text":"."}]}]}],"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"type":"topic","kind":"symbol","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","title":"PushwooshFramework","role":"collection","abstract":[]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/disableReverseProxy()":{"title":"disableReverseProxy()","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/disableReverseProxy()","url":"\/documentation\/pushwooshframework\/pushwoosh\/disablereverseproxy()","navigatorTitle":[{"text":"disableReverseProxy","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Disables reverse proxy configuration."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"disableReverseProxy"},{"text":"()","kind":"text"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh":{"kind":"symbol","title":"Pushwoosh","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh","url":"\/documentation\/pushwooshframework\/pushwoosh","navigatorTitle":[{"text":"Pushwoosh","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Main SDK interface for push notification management."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Pushwoosh","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"disableReverseProxy","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"disableReverseProxy","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"disableReverseProxy","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"disableReverseProxy","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1disableReverseProxy()\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1disableReverseProxy()\/fragments","value":[{"kind":"text","text":"- "},{"text":"disableReverseProxy","kind":"identifier"}]},{"op":"replace","value":"Pushwoosh","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh\/fragments","value":[{"text":"Pushwoosh","kind":"identifier"}]}]}]}