{"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/pushwooshframework\/pushwoosh\/gethwid()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pushwooshframework\/pushwoosh\/gethwid()"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"getHWID","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Overview","level":2,"type":"heading","anchor":"Overview"},{"type":"paragraph","inlineContent":[{"text":"The HWID (Hardware ID) is a unique device identifier that Pushwoosh uses to identify devices across all API operations. This identifier is essential for:","type":"text"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Tracking devices in Pushwoosh Control Panel"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Server-to-server API calls"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"Matching user data across different systems","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Analytics and reporting"}]}]}]},{"text":"Platform-Specific Implementation","anchor":"Platform-Specific-Implementation","level":2,"type":"heading"},{"header":"row","type":"table","rows":[[[{"type":"paragraph","inlineContent":[{"type":"text","text":"Platform"}]}],[{"inlineContent":[{"text":"Underlying Identifier","type":"text"}],"type":"paragraph"}]],[[{"type":"paragraph","inlineContent":[{"text":"iOS","type":"text"}]}],[{"inlineContent":[{"code":"UIDevice.identifierForVendor","type":"codeVoice"}],"type":"paragraph"}]],[[{"type":"paragraph","inlineContent":[{"type":"text","text":"macOS"}]}],[{"type":"paragraph","inlineContent":[{"code":"IOPlatformUUID","type":"codeVoice"}]}]]]},{"level":2,"anchor":"Lifecycle","text":"Lifecycle","type":"heading"},{"inlineContent":[{"type":"text","text":"The HWID is generated on first SDK initialization and persists across:"}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"App launches","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"App updates","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"SDK updates"}],"type":"paragraph"}]}],"type":"unorderedList"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The HWID will change if:"}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"User reinstalls the app (iOS)"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"User deletes all apps from the same vendor (iOS)"}]}]}]},{"type":"heading","text":"Example","level":2,"anchor":"Example"},{"inlineContent":[{"text":"Sync device identifier with your backend for cross-system user matching:","type":"text"}],"type":"paragraph"},{"code":["func syncDeviceWithBackend(userId: String) {","    let hwid = Pushwoosh.configure.getHWID()","","    let payload: [String: Any] = [","        \"hwid\": hwid,","        \"userId\": userId,","        \"platform\": \"ios\"","    ]","","    apiClient.post(\"\/devices\/register\", body: payload)","}"],"syntax":"swift","type":"codeListing"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Use HWID for server-to-server push notification targeting:"}]},{"code":["func sendPushFromServer(to userId: String, message: String) {","    let hwid = Pushwoosh.configure.getHWID()","","    serverAPI.sendPush(","        targetHWID: hwid,","        content: message","    )","}"],"syntax":"swift","type":"codeListing"}]}],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"getHWID","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"role":"symbol","modules":[{"name":"PushwooshFramework"}],"roleHeading":"Instance Method","externalID":"c:objc(cs)Pushwoosh(im)getHWID","title":"getHWID()","symbolKind":"method","navigatorTitle":[{"text":"getHWID","kind":"identifier"}]},"abstract":[{"type":"text","text":"Returns the Pushwoosh Hardware ID (HWID) for this device."}],"seeAlsoSections":[{"title":"Related Documentation","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/getPushToken()","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/getUserId()","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/setUserId(_:)"]}],"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/getHWID()","interfaceLanguage":"swift"},"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/getHWID()":{"url":"\/documentation\/pushwooshframework\/pushwoosh\/gethwid()","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getHWID"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/getHWID()","role":"symbol","abstract":[{"type":"text","text":"Returns the Pushwoosh Hardware ID (HWID) for this device."}],"title":"getHWID()","kind":"symbol","navigatorTitle":[{"text":"getHWID","kind":"identifier"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Pushwoosh","kind":"identifier"}],"url":"\/documentation\/pushwooshframework\/pushwoosh","kind":"symbol","title":"Pushwoosh","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Pushwoosh"}],"abstract":[{"type":"text","text":"Main SDK interface for push notification management."}],"type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/getUserId()":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getUserId","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"url":"\/documentation\/pushwooshframework\/pushwoosh\/getuserid()","kind":"symbol","title":"getUserId()","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/getUserId()","role":"symbol","navigatorTitle":[{"text":"getUserId","kind":"identifier"}],"abstract":[{"type":"text","text":"Returns the current user identifier."}],"type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/setUserId(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setUserId","kind":"identifier"},{"kind":"text","text":"("},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"url":"\/documentation\/pushwooshframework\/pushwoosh\/setuserid(_:)","kind":"symbol","title":"setUserId(_:)","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/setUserId(_:)","role":"symbol","navigatorTitle":[{"text":"setUserId:","kind":"identifier"}],"abstract":[{"type":"text","text":"Associates a unique identifier with the current device."}],"type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/getPushToken()":{"url":"\/documentation\/pushwooshframework\/pushwoosh\/getpushtoken()","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"getPushToken","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/getPushToken()","role":"symbol","abstract":[{"text":"Retrieves the current device push token.","type":"text"}],"title":"getPushToken()","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"getPushToken"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"type":"topic","abstract":[{"type":"text","text":"Push notification SDK for iOS applications."}],"title":"PushwooshFramework","kind":"symbol","url":"\/documentation\/pushwooshframework","role":"collection","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","value":"getHWID","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"getHWID","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"replace","value":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/getPushToken()","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/getUserId()","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/setUserId(_:)"],"title":"Related Documentation"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"getHWID","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1getHWID()\/title","value":"getHWID"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1getHWID()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getHWID"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh\/title","value":"Pushwoosh"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh\/fragments","value":[{"text":"Pushwoosh","kind":"identifier"}]},{"value":"getUserId","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1getUserId()\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getUserId"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1getUserId()\/fragments","op":"replace"},{"op":"replace","value":"setUserId:","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1setUserId(_:)\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1setUserId(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setUserId:"}],"op":"replace"},{"value":"getPushToken","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1getPushToken()\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getPushToken"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1getPushToken()\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}