{"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh"]]},"variants":[{"paths":["\/documentation\/pushwooshframework\/pushwoosh\/getremotenotificationstatus()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pushwooshframework\/pushwoosh\/getremotenotificationstatus()"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/getRemoteNotificationStatus()","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"PushwooshFramework"}],"externalID":"c:objc(cs)Pushwoosh(cm)getRemoteNotificationStatus","symbolKind":"method","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"getRemoteNotificationStatus","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"NSMutableDictionary","preciseIdentifier":"c:objc(cs)NSMutableDictionary"},{"kind":"text","text":"?"}],"roleHeading":"Type Method","title":"getRemoteNotificationStatus()","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"getRemoteNotificationStatus"}]},"abstract":[{"text":"Returns a dictionary with enabled remote notification types.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getRemoteNotificationStatus"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"c:objc(cs)NSMutableDictionary","kind":"typeIdentifier","text":"NSMutableDictionary"},{"text":"?","kind":"text"}]}]},{"kind":"content","content":[{"text":"Overview","level":2,"type":"heading","anchor":"Overview"},{"inlineContent":[{"text":"Retrieves the current push notification permission status. Use this to:","type":"text"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Check if user has enabled notifications"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Determine which notification types are allowed"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Show appropriate UI based on permission state"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Debug notification issues","type":"text"}]}]}]},{"text":"Response Format","level":2,"type":"heading","anchor":"Response-Format"},{"type":"codeListing","syntax":null,"code":["{","   enabled = 1;      \/\/ Device can receive pushes","   pushAlert = 1;    \/\/ Alerts enabled","   pushBadge = 1;    \/\/ Badges enabled","   pushSound = 1;    \/\/ Sounds enabled","   type = 7;         \/\/ UIUserNotificationType bitmask","}"]},{"level":2,"type":"heading","text":"Example","anchor":"Example"},{"type":"paragraph","inlineContent":[{"text":"Check notification status and prompt user:","type":"text"}]},{"syntax":"swift","type":"codeListing","code":["func checkNotificationPermissions() {","    guard let status = Pushwoosh.configure.getRemoteNotificationStatus() else {","        return","    }","","    let enabled = status[\"enabled\"] as? Bool ?? false","    let alertsEnabled = status[\"pushAlert\"] as? Bool ?? false","","    if !enabled {","        showEnableNotificationsPrompt()","    } else if !alertsEnabled {","        showNotificationsDisabledInSettingsAlert()","    }","}"]},{"inlineContent":[{"text":"Display notification settings in app:","type":"text"}],"type":"paragraph"},{"syntax":"swift","type":"codeListing","code":["func loadNotificationSettings() -> NotificationSettings {","    guard let status = Pushwoosh.configure.getRemoteNotificationStatus() else {","        return NotificationSettings.default","    }","","    return NotificationSettings(","        enabled: status[\"enabled\"] as? Bool ?? false,","        alerts: status[\"pushAlert\"] as? Bool ?? false,","        badges: status[\"pushBadge\"] as? Bool ?? false,","        sounds: status[\"pushSound\"] as? Bool ?? false","    )","}"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Log notification status for debugging:"}]},{"type":"codeListing","syntax":"swift","code":["func debugNotificationStatus() {","    if let status = Pushwoosh.configure.getRemoteNotificationStatus() {","        print(\"Notification status: \\(status)\")","    }","}"]}]}],"seeAlsoSections":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/registerForPushNotifications()"],"title":"Related Documentation"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/getRemoteNotificationStatus()":{"title":"getRemoteNotificationStatus()","role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/getRemoteNotificationStatus()","navigatorTitle":[{"text":"getRemoteNotificationStatus","kind":"identifier"}],"type":"topic","url":"\/documentation\/pushwooshframework\/pushwoosh\/getremotenotificationstatus()","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getRemoteNotificationStatus"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSMutableDictionary","text":"NSMutableDictionary","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Returns a dictionary with enabled remote notification types."}],"kind":"symbol"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/registerForPushNotifications()":{"abstract":[{"type":"text","text":"Registers the device for push notifications."}],"navigatorTitle":[{"kind":"identifier","text":"registerForPushNotifications"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/registerForPushNotifications()","url":"\/documentation\/pushwooshframework\/pushwoosh\/registerforpushnotifications()","type":"topic","role":"symbol","title":"registerForPushNotifications()","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"registerForPushNotifications"},{"kind":"text","text":"()"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"type":"topic","abstract":[{"type":"text","text":"Push notification SDK for iOS applications."}],"url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","kind":"symbol","title":"PushwooshFramework","role":"collection"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh":{"type":"topic","abstract":[{"type":"text","text":"Main SDK interface for push notification management."}],"url":"\/documentation\/pushwooshframework\/pushwoosh","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh","navigatorTitle":[{"text":"Pushwoosh","kind":"identifier"}],"title":"Pushwoosh","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Pushwoosh","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"getRemoteNotificationStatus","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getRemoteNotificationStatus"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/registerForPushNotifications()"],"title":"Related Documentation"}],"op":"replace"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:objc(cs)NSMutableDictionary","kind":"typeIdentifier","text":"NSMutableDictionary"},{"text":" *) ","kind":"text"},{"text":"getRemoteNotificationStatus","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1getRemoteNotificationStatus()\/title","value":"getRemoteNotificationStatus","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1getRemoteNotificationStatus()\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"text":"getRemoteNotificationStatus","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1registerForPushNotifications()\/title","value":"registerForPushNotifications"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"registerForPushNotifications"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1registerForPushNotifications()\/fragments"},{"value":"Pushwoosh","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh\/fragments","value":[{"kind":"identifier","text":"Pushwoosh"}]}]}]}