{"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh"]]},"sections":[],"metadata":{"roleHeading":"Instance Method","navigatorTitle":[{"text":"getTags:onFailure:","kind":"identifier"}],"modules":[{"name":"PushwooshFramework"}],"externalID":"c:objc(cs)Pushwoosh(im)getTags:onFailure:","role":"symbol","title":"getTags(_:onFailure:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getTags","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"PushwooshGetTagsHandler","preciseIdentifier":"c:PushNotificationManager.h@T@PushwooshGetTagsHandler"},{"text":"?, ","kind":"text"},{"text":"onFailure","kind":"externalParam"},{"kind":"text","text":": "},{"text":"PushwooshErrorHandler","kind":"typeIdentifier","preciseIdentifier":"c:PushNotificationManager.h@T@PushwooshErrorHandler"},{"text":"?)","kind":"text"}],"symbolKind":"method"},"kind":"symbol","identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/getTags(_:onFailure:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Retrieves the current device’s tags from the Pushwoosh server."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getTags","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"successHandler"},{"kind":"text","text":": "},{"text":"PushwooshGetTagsHandler","kind":"typeIdentifier","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushwooshGetTagsHandler","preciseIdentifier":"c:PushNotificationManager.h@T@PushwooshGetTagsHandler"},{"kind":"text","text":"?, "},{"text":"onFailure","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"errorHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PushwooshErrorHandler","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushwooshErrorHandler","preciseIdentifier":"c:PushNotificationManager.h@T@PushwooshErrorHandler"},{"text":"? = nil)","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"level":2,"type":"heading","text":"Discussion","anchor":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Fetches all tags currently set for this device. Tags are returned as a dictionary where keys are tag names and values are the corresponding tag values."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"The operation is performed asynchronously and does not block the calling thread."}]},{"type":"heading","text":"Parameters","anchor":"Parameters","level":2},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"text":"successHandler: Block called when tags are successfully retrieved. Receives a dictionary containing all device tags.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"errorHandler: Block called if the request fails. Receives an error describing the failure."}]}]}]}],"kind":"content"}],"variants":[{"paths":["\/documentation\/pushwooshframework\/pushwoosh\/gettags(_:onfailure:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pushwooshframework\/pushwoosh\/gettags(_:onfailure:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"Pushwoosh"}],"abstract":[{"type":"text","text":"Main SDK interface for push notification management."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Pushwoosh"}],"title":"Pushwoosh","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh","kind":"symbol","url":"\/documentation\/pushwooshframework\/pushwoosh","role":"symbol"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushwooshErrorHandler":{"type":"topic","url":"\/documentation\/pushwooshframework\/pushwoosherrorhandler","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushwooshErrorHandler","navigatorTitle":[{"text":"PushwooshErrorHandler","kind":"identifier"}],"role":"symbol","title":"PushwooshErrorHandler","kind":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PushwooshErrorHandler"}],"abstract":[{"type":"text","text":"Completion handler called when an operation fails."}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushwooshGetTagsHandler":{"type":"topic","url":"\/documentation\/pushwooshframework\/pushwooshgettagshandler","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushwooshGetTagsHandler","navigatorTitle":[{"text":"PushwooshGetTagsHandler","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"PushwooshGetTagsHandler","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PushwooshGetTagsHandler"}],"abstract":[{"type":"text","text":"Completion handler called when tags are successfully retrieved from the server."}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/getTags(_:onFailure:)":{"type":"topic","url":"\/documentation\/pushwooshframework\/pushwoosh\/gettags(_:onfailure:)","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/getTags(_:onFailure:)","navigatorTitle":[{"kind":"identifier","text":"getTags:onFailure:"}],"role":"symbol","title":"getTags(_:onFailure:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getTags"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:PushNotificationManager.h@T@PushwooshGetTagsHandler","text":"PushwooshGetTagsHandler"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"onFailure"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PushwooshErrorHandler","preciseIdentifier":"c:PushNotificationManager.h@T@PushwooshErrorHandler"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Retrieves the current device’s tags from the Pushwoosh server."}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"kind":"symbol","abstract":[],"url":"\/documentation\/pushwooshframework","role":"collection","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","title":"PushwooshFramework"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"getTags:onFailure:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getTags:onFailure:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"text":"getTags:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:BFv(#*$objc(cs)NSDictionary)","text":"void (^)(NSDictionary *)"},{"kind":"text","text":") "},{"kind":"internalParam","text":"successHandler"},{"kind":"text","text":" "},{"kind":"identifier","text":"onFailure:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:BFv(#*$objc(cs)NSError)","text":"void (^)(NSError *)","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"errorHandler","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"Pushwoosh","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh\/fragments","value":[{"kind":"identifier","text":"Pushwoosh"}]},{"value":"PushwooshErrorHandler","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushwooshErrorHandler\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"PushwooshErrorHandler"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushwooshErrorHandler\/fragments"},{"value":"PushwooshGetTagsHandler","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushwooshGetTagsHandler\/title"},{"op":"replace","value":[{"kind":"identifier","text":"PushwooshGetTagsHandler"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushwooshGetTagsHandler\/fragments"},{"value":"getTags:onFailure:","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1getTags(_:onFailure:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1getTags(_:onFailure:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"getTags:onFailure:","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}