{"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/getUserId()","interfaceLanguage":"swift"},"seeAlsoSections":[{"title":"Related Documentation","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/setUserId(_:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/setUserId(_:completion:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/getHWID()"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/pushwooshframework\/pushwoosh\/getuserid()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pushwoosh\/getuserid()"]}],"abstract":[{"text":"Returns the current user identifier.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"getUserId","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"platforms":["iOS"]}]},{"content":[{"text":"Overview","type":"heading","anchor":"Overview","level":2},{"inlineContent":[{"type":"text","text":"The user ID is used to identify users across multiple devices and sessions. This enables:"}],"type":"paragraph"},{"items":[{"content":[{"inlineContent":[{"text":"Cross-device push notification targeting","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"User-level analytics and segmentation"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Merging user data when users log in on new devices"}]}]}],"type":"unorderedList"},{"level":2,"anchor":"Default-Behavior","type":"heading","text":"Default Behavior"},{"inlineContent":[{"type":"text","text":"If no custom user ID has been set via "},{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/setUserId(_:)","isActive":true,"type":"reference"},{"text":", this method returns the Hardware ID (HWID) as the default identifier.","type":"text"}],"type":"paragraph"},{"level":2,"anchor":"Example","type":"heading","text":"Example"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Sync Pushwoosh user ID with your analytics platform:"}]},{"code":["func setupAnalytics() {","    let userId = Pushwoosh.configure.getUserId()","","    Analytics.shared.identify(userId)","    Crashlytics.setUserID(userId)","}"],"type":"codeListing","syntax":"swift"},{"type":"paragraph","inlineContent":[{"text":"Include user ID in support tickets:","type":"text"}]},{"code":["func createSupportTicket(issue: String) -> SupportTicket {","    return SupportTicket(","        userId: Pushwoosh.configure.getUserId(),","        hwid: Pushwoosh.configure.getHWID(),","        issue: issue,","        appVersion: Bundle.main.appVersion","    )","}"],"syntax":"swift","type":"codeListing"}],"kind":"content"}],"sections":[],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"getUserId"}],"role":"symbol","title":"getUserId()","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getUserId","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"symbolKind":"method","modules":[{"name":"PushwooshFramework"}],"externalID":"c:objc(cs)Pushwoosh(im)getUserId"},"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/setUserId(_:)":{"type":"topic","url":"\/documentation\/pushwooshframework\/pushwoosh\/setuserid(_:)","abstract":[{"type":"text","text":"Associates a unique identifier with the current device."}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/setUserId(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setUserId"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"setUserId:","kind":"identifier"}],"kind":"symbol","title":"setUserId(_:)"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh":{"url":"\/documentation\/pushwooshframework\/pushwoosh","role":"symbol","title":"Pushwoosh","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh","type":"topic","kind":"symbol","navigatorTitle":[{"text":"Pushwoosh","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Pushwoosh","kind":"identifier"}],"abstract":[{"type":"text","text":"Main SDK interface for push notification management."}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/setUserId(_:completion:)":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/setUserId(_:completion:)","kind":"symbol","title":"setUserId(_:completion:)","type":"topic","navigatorTitle":[{"text":"setUserId:completion:","kind":"identifier"}],"abstract":[{"type":"text","text":"Associates a unique identifier with the current device with a completion handler."}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setUserId","kind":"identifier"},{"kind":"text","text":"("},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": (((any ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":")?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")?)"}],"url":"\/documentation\/pushwooshframework\/pushwoosh\/setuserid(_:completion:)"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"type":"topic","kind":"symbol","title":"PushwooshFramework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","url":"\/documentation\/pushwooshframework","role":"collection","abstract":[{"type":"text","text":"Push notification SDK for iOS applications."}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/getUserId()":{"title":"getUserId()","type":"topic","navigatorTitle":[{"text":"getUserId","kind":"identifier"}],"url":"\/documentation\/pushwooshframework\/pushwoosh\/getuserid()","role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getUserId"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/getUserId()","abstract":[{"text":"Returns the current user identifier.","type":"text"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/getHWID()":{"title":"getHWID()","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/getHWID()","navigatorTitle":[{"text":"getHWID","kind":"identifier"}],"url":"\/documentation\/pushwooshframework\/pushwoosh\/gethwid()","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getHWID"},{"text":"() -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"type":"topic","abstract":[{"text":"Returns the Pushwoosh Hardware ID (HWID) for this device.","type":"text"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","value":"getUserId","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"getUserId"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Related Documentation","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/setUserId(_:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/setUserId(_:completion:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/getHWID()"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"getUserId","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1setUserId(_:)\/title","value":"setUserId:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1setUserId(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"setUserId:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh\/title","op":"replace","value":"Pushwoosh"},{"value":[{"text":"Pushwoosh","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1setUserId(_:completion:)\/title","value":"setUserId:completion:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setUserId:completion:"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1setUserId(_:completion:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1getUserId()\/title","value":"getUserId"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"getUserId"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1getUserId()\/fragments"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1getHWID()\/title","value":"getHWID","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1getHWID()\/fragments","value":[{"kind":"text","text":"- "},{"text":"getHWID","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}