{"kind":"symbol","seeAlsoSections":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/delegate","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWMessagingDelegate","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWMessagingDelegate\/pushwoosh(_:onMessageReceived:)"],"title":"Related Documentation"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"handlePushReceived","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"userInfo"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]) -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"content","content":[{"anchor":"Overview","level":2,"text":"Overview","type":"heading"},{"inlineContent":[{"text":"Manually processes a push notification payload. The SDK handles this automatically in most cases.","type":"text"}],"type":"paragraph"},{"level":2,"anchor":"When-to-Use","text":"When to Use","type":"heading"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Custom notification handling flow"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Processing notifications from multiple providers"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Background fetch implementations"}]}]},{"content":[{"inlineContent":[{"text":"Testing and debugging","type":"text"}],"type":"paragraph"}]}]},{"text":"Return Value","type":"heading","anchor":"Return-Value","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Returns "},{"type":"codeVoice","code":"true"},{"type":"text","text":" if the notification was a Pushwoosh notification and was processed, "},{"code":"false","type":"codeVoice"},{"type":"text","text":" if it was from another provider."}]},{"anchor":"Example","text":"Example","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"text":"Handle notifications in AppDelegate:","type":"text"}]},{"code":["func application(_ application: UIApplication,","                didReceiveRemoteNotification userInfo: [AnyHashable: Any],","                fetchCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult) -> Void) {","","    let handled = Pushwoosh.configure.handlePushReceived(userInfo)","","    if handled {","        completionHandler(.newData)","    } else {","        handleOtherPushProvider(userInfo, completion: completionHandler)","    }","}"],"type":"codeListing","syntax":"swift"},{"inlineContent":[{"text":"Route notifications to correct handler:","type":"text"}],"type":"paragraph"},{"syntax":"swift","code":["func routeNotification(_ userInfo: [AnyHashable: Any]) {","    if Pushwoosh.configure.handlePushReceived(userInfo) {","        return","    }","","    if let firebaseData = userInfo[\"gcm.message_id\"] {","        FirebaseHandler.handle(userInfo)","        return","    }","","    CustomNotificationHandler.handle(userInfo)","}"],"type":"codeListing"}]}],"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/handlePushReceived(_:)","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"PushwooshFramework"}],"symbolKind":"method","roleHeading":"Instance Method","navigatorTitle":[{"text":"handlePushReceived:","kind":"identifier"}],"title":"handlePushReceived(_:)","externalID":"c:objc(cs)Pushwoosh(im)handlePushReceived:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"handlePushReceived"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]) -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pushwoosh\/handlepushreceived(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pushwoosh\/handlepushreceived(_:)"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh"]]},"sections":[],"abstract":[{"text":"Handles received push notifications.","type":"text"}],"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh":{"abstract":[{"text":"Main SDK interface for push notification management.","type":"text"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh","title":"Pushwoosh","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Pushwoosh","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Pushwoosh"}],"url":"\/documentation\/pushwooshframework\/pushwoosh"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWMessagingDelegate/pushwoosh(_:onMessageReceived:)":{"required":true,"abstract":[{"text":"Called when the application receives a push notification.","type":"text"}],"kind":"symbol","title":"pushwoosh(_:onMessageReceived:)","role":"symbol","url":"\/documentation\/pushwooshframework\/pwmessagingdelegate\/pushwoosh(_:onmessagereceived:)","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWMessagingDelegate\/pushwoosh(_:onMessageReceived:)","navigatorTitle":[{"text":"pushwoosh:onMessageReceived:","kind":"identifier"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pushwoosh","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)Pushwoosh","text":"Pushwoosh"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"onMessageReceived"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)PWMessage","kind":"typeIdentifier","text":"PWMessage"},{"kind":"text","text":")"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/handlePushReceived(_:)":{"role":"symbol","type":"topic","url":"\/documentation\/pushwooshframework\/pushwoosh\/handlepushreceived(_:)","kind":"symbol","abstract":[{"type":"text","text":"Handles received push notifications."}],"title":"handlePushReceived(_:)","navigatorTitle":[{"kind":"identifier","text":"handlePushReceived:"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/handlePushReceived(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handlePushReceived"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"]) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/delegate":{"url":"\/documentation\/pushwooshframework\/pushwoosh\/delegate","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/delegate","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"text":": (any ","kind":"text"},{"text":"PWMessagingDelegate","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)PWMessagingDelegate"},{"kind":"text","text":")?"}],"title":"delegate","abstract":[{"type":"text","text":"Delegate that receives push notification events."}],"navigatorTitle":[{"text":"delegate","kind":"identifier"}],"kind":"symbol"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWMessagingDelegate":{"abstract":[{"type":"text","text":"Delegate protocol for handling push notification events."}],"kind":"symbol","title":"PWMessagingDelegate","role":"symbol","url":"\/documentation\/pushwooshframework\/pwmessagingdelegate","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWMessagingDelegate","navigatorTitle":[{"text":"PWMessagingDelegate","kind":"identifier"}],"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"PWMessagingDelegate","kind":"identifier"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"kind":"symbol","type":"topic","abstract":[{"text":"Push notification SDK for iOS applications.","type":"text"}],"url":"\/documentation\/pushwooshframework","title":"PushwooshFramework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","role":"collection"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","value":"handlePushReceived:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"handlePushReceived:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Related Documentation","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/delegate","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWMessagingDelegate","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWMessagingDelegate\/pushwoosh(_:onMessageReceived:)"]}]},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"kind":"identifier","text":"handlePushReceived:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSDictionary","preciseIdentifier":"c:objc(cs)NSDictionary"},{"kind":"text","text":" *) "},{"text":"userInfo","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh\/title","value":"Pushwoosh"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh\/fragments","value":[{"kind":"identifier","text":"Pushwoosh"}]},{"value":"pushwoosh:onMessageReceived:","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWMessagingDelegate~1pushwoosh(_:onMessageReceived:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"pushwoosh:onMessageReceived:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWMessagingDelegate~1pushwoosh(_:onMessageReceived:)\/fragments"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1handlePushReceived(_:)\/title","op":"replace","value":"handlePushReceived:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"handlePushReceived:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1handlePushReceived(_:)\/fragments"},{"value":"delegate","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1delegate\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1delegate\/fragments","op":"replace","value":[{"text":"delegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWMessagingDelegate\/title","value":"PWMessagingDelegate","op":"replace"},{"value":[{"text":"PWMessagingDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWMessagingDelegate\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}