{"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh"]]},"seeAlsoSections":[{"title":"Related Documentation","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/handlePushRegistration(_:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/registerForPushNotifications()"]}],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"handlePushRegistrationFailure","kind":"identifier"},{"text":"(any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":")","kind":"text"}],"modules":[{"name":"PushwooshFramework"}],"role":"symbol","externalID":"c:objc(cs)Pushwoosh(im)handlePushRegistrationFailure:","symbolKind":"method","navigatorTitle":[{"text":"handlePushRegistrationFailure:","kind":"identifier"}],"title":"handlePushRegistrationFailure(_:)","roleHeading":"Instance Method"},"kind":"symbol","abstract":[{"text":"Handles push notification registration failures.","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"handlePushRegistrationFailure"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": any "},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":")","kind":"text"}]}],"kind":"declarations"},{"content":[{"anchor":"Overview","text":"Overview","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"Notifies Pushwoosh when APNs registration fails. This enables:"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"Error tracking and analytics"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"Debugging registration issues","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"Server-side error monitoring","type":"text"}],"type":"paragraph"}]}]},{"anchor":"Common-Failure-Reasons","level":2,"text":"Common Failure Reasons","type":"heading"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Missing Push Notifications capability","type":"text"}]}]},{"content":[{"inlineContent":[{"text":"Invalid provisioning profile","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Simulator without push support"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Network connectivity issues"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"APNs server unavailable","type":"text"}]}]}],"type":"unorderedList"},{"text":"Example","anchor":"Example","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Standard AppDelegate implementation:"}]},{"syntax":"swift","code":["func application(_ application: UIApplication,","                didFailToRegisterForRemoteNotificationsWithError error: Error) {","    Pushwoosh.configure.handlePushRegistrationFailure(error as NSError)","}"],"type":"codeListing"},{"inlineContent":[{"text":"With additional error logging:","type":"text"}],"type":"paragraph"},{"code":["func application(_ application: UIApplication,","                didFailToRegisterForRemoteNotificationsWithError error: Error) {","    Pushwoosh.configure.handlePushRegistrationFailure(error as NSError)","","    Analytics.log(\"push_registration_failed\", [","        \"error\": error.localizedDescription,","        \"code\": (error as NSError).code","    ])","","    #if DEBUG","    print(\"Push registration failed: \\(error)\")","    #endif","}"],"type":"codeListing","syntax":"swift"}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pushwoosh\/handlepushregistrationfailure(_:)"]},{"paths":["\/documentation\/pushwooshframework\/pushwoosh\/handlepushregistrationfailure(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/handlePushRegistrationFailure(_:)"},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/handlePushRegistration(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"handlePushRegistration"},{"kind":"text","text":"("},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/handlePushRegistration(_:)","role":"symbol","url":"\/documentation\/pushwooshframework\/pushwoosh\/handlepushregistration(_:)","abstract":[{"text":"Manually handles the device push token registration.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"handlePushRegistration:"}],"type":"topic","kind":"symbol","title":"handlePushRegistration(_:)"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","kind":"symbol","role":"collection","title":"PushwooshFramework","url":"\/documentation\/pushwooshframework","type":"topic","abstract":[{"text":"Push notification SDK for iOS applications.","type":"text"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/handlePushRegistrationFailure(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"handlePushRegistrationFailure","kind":"identifier"},{"kind":"text","text":"(any "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/handlePushRegistrationFailure(_:)","role":"symbol","url":"\/documentation\/pushwooshframework\/pushwoosh\/handlepushregistrationfailure(_:)","abstract":[{"type":"text","text":"Handles push notification registration failures."}],"navigatorTitle":[{"text":"handlePushRegistrationFailure:","kind":"identifier"}],"type":"topic","kind":"symbol","title":"handlePushRegistrationFailure(_:)"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh":{"title":"Pushwoosh","navigatorTitle":[{"kind":"identifier","text":"Pushwoosh"}],"abstract":[{"text":"Main SDK interface for push notification management.","type":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh","url":"\/documentation\/pushwooshframework\/pushwoosh","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Pushwoosh","kind":"identifier"}],"type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/registerForPushNotifications()":{"title":"registerForPushNotifications()","navigatorTitle":[{"text":"registerForPushNotifications","kind":"identifier"}],"abstract":[{"text":"Registers the device for push notifications.","type":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/registerForPushNotifications()","url":"\/documentation\/pushwooshframework\/pushwoosh\/registerforpushnotifications()","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"registerForPushNotifications","kind":"identifier"},{"kind":"text","text":"()"}],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"handlePushRegistrationFailure:","path":"\/metadata\/title","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"handlePushRegistrationFailure:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/handlePushRegistration(_:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/registerForPushNotifications()"],"title":"Related Documentation"}],"op":"replace","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"text":"handlePushRegistrationFailure:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"text":" *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"value":"handlePushRegistration:","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1handlePushRegistration(_:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1handlePushRegistration(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"handlePushRegistration:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1handlePushRegistrationFailure(_:)\/title","value":"handlePushRegistrationFailure:","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"handlePushRegistrationFailure:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1handlePushRegistrationFailure(_:)\/fragments"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh\/title","value":"Pushwoosh","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh\/fragments","op":"replace","value":[{"text":"Pushwoosh","kind":"identifier"}]},{"value":"registerForPushNotifications","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1registerForPushNotifications()\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"registerForPushNotifications","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1registerForPushNotifications()\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}