{"schemaVersion":{"major":0,"minor":3,"patch":0},"seeAlsoSections":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/handlePushRegistrationFailure(_:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/registerForPushNotifications()","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/getPushToken()"],"title":"Related Documentation"}],"variants":[{"paths":["\/documentation\/pushwooshframework\/pushwoosh\/handlepushregistration(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pushwoosh\/handlepushregistration(_:)"]}],"abstract":[{"text":"Manually handles the device push token registration.","type":"text"}],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"handlePushRegistration","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"handlePushRegistration:"}],"modules":[{"name":"PushwooshFramework"}],"title":"handlePushRegistration(_:)","externalID":"c:objc(cs)Pushwoosh(im)handlePushRegistration:","symbolKind":"method","roleHeading":"Instance Method","role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"handlePushRegistration"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"devToken"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"level":2,"text":"Overview","type":"heading","anchor":"Overview"},{"type":"paragraph","inlineContent":[{"text":"Forwards the APNs device token to Pushwoosh for push notification delivery.","type":"text"}]},{"anchor":"Automatic-vs-Manual-Handling","type":"heading","level":2,"text":"Automatic vs Manual Handling"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The SDK handles token registration automatically in most cases. Use this method only when:"}]},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Using custom push notification setup"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Integrating multiple push providers"}]}]},{"content":[{"inlineContent":[{"text":"Implementing manual swizzling control","type":"text"}],"type":"paragraph"}]}],"type":"unorderedList"},{"level":2,"anchor":"Example","text":"Example","type":"heading"},{"inlineContent":[{"type":"text","text":"Standard AppDelegate implementation:"}],"type":"paragraph"},{"syntax":"swift","type":"codeListing","code":["func application(_ application: UIApplication,","                didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {","    Pushwoosh.configure.handlePushRegistration(deviceToken)","}"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"With multiple push providers:"}]},{"code":["func application(_ application: UIApplication,","                didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {","    Pushwoosh.configure.handlePushRegistration(deviceToken)","","    FirebaseMessaging.messaging().apnsToken = deviceToken","","    OtherPushProvider.shared.registerToken(deviceToken)","}"],"type":"codeListing","syntax":"swift"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh"]]},"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/handlePushRegistration(_:)","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh","type":"topic","url":"\/documentation\/pushwooshframework\/pushwoosh","abstract":[{"type":"text","text":"Main SDK interface for push notification management."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Pushwoosh","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Pushwoosh"}],"title":"Pushwoosh","role":"symbol","kind":"symbol"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/getPushToken()":{"kind":"symbol","title":"getPushToken()","url":"\/documentation\/pushwooshframework\/pushwoosh\/getpushtoken()","abstract":[{"text":"Retrieves the current device push token.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"getPushToken","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/getPushToken()","navigatorTitle":[{"text":"getPushToken","kind":"identifier"}],"type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/handlePushRegistration(_:)":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"handlePushRegistration:"}],"kind":"symbol","title":"handlePushRegistration(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"handlePushRegistration"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/handlePushRegistration(_:)","url":"\/documentation\/pushwooshframework\/pushwoosh\/handlepushregistration(_:)","abstract":[{"type":"text","text":"Manually handles the device push token registration."}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"abstract":[{"text":"Push notification SDK for iOS applications.","type":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","title":"PushwooshFramework","kind":"symbol","role":"collection","url":"\/documentation\/pushwooshframework","type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/handlePushRegistrationFailure(_:)":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"handlePushRegistrationFailure:"}],"kind":"symbol","title":"handlePushRegistrationFailure(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handlePushRegistrationFailure"},{"kind":"text","text":"(any "},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/handlePushRegistrationFailure(_:)","url":"\/documentation\/pushwooshframework\/pushwoosh\/handlepushregistrationfailure(_:)","abstract":[{"type":"text","text":"Handles push notification registration failures."}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/registerForPushNotifications()":{"navigatorTitle":[{"text":"registerForPushNotifications","kind":"identifier"}],"title":"registerForPushNotifications()","kind":"symbol","url":"\/documentation\/pushwooshframework\/pushwoosh\/registerforpushnotifications()","abstract":[{"text":"Registers the device for push notifications.","type":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/registerForPushNotifications()","role":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"registerForPushNotifications"},{"kind":"text","text":"()"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"handlePushRegistration:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"handlePushRegistration:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"replace","value":[{"title":"Related Documentation","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/handlePushRegistrationFailure(_:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/registerForPushNotifications()","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/getPushToken()"]}],"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"handlePushRegistration:"},{"kind":"text","text":"("},{"text":"NSData","preciseIdentifier":"c:objc(cs)NSData","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"devToken","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"Pushwoosh","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh\/fragments","value":[{"text":"Pushwoosh","kind":"identifier"}],"op":"replace"},{"value":"getPushToken","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1getPushToken()\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1getPushToken()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getPushToken"}]},{"value":"handlePushRegistration:","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1handlePushRegistration(_:)\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1handlePushRegistration(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"handlePushRegistration:","kind":"identifier"}],"op":"replace"},{"value":"handlePushRegistrationFailure:","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1handlePushRegistrationFailure(_:)\/title","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"handlePushRegistrationFailure:"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1handlePushRegistrationFailure(_:)\/fragments"},{"value":"registerForPushNotifications","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1registerForPushNotifications()\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1registerForPushNotifications()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"registerForPushNotifications"}]}]}]}