{"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"initialize","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withAppCode","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"role":"symbol","externalID":"c:objc(cs)Pushwoosh(cm)initializeWithAppCode:","roleHeading":"Type Method","title":"initialize(withAppCode:)","symbolKind":"method","navigatorTitle":[{"text":"initializeWithAppCode:","kind":"identifier"}],"modules":[{"name":"PushwooshFramework"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"initialize","kind":"identifier"},{"kind":"text","text":"("},{"text":"withAppCode","kind":"externalParam"},{"kind":"text","text":" "},{"text":"appCode","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}],"languages":["swift"]}]},{"content":[{"type":"heading","anchor":"Discussion","level":2,"text":"Discussion"},{"inlineContent":[{"text":"Use this method to manually initialize the SDK with your Pushwoosh Application Code. Alternatively, you can configure the Application Code in Info.plist with key ","type":"text"},{"type":"codeVoice","code":"Pushwoosh_APPID"},{"type":"text","text":" to enable automatic initialization."}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"type":"text","text":"After initialization, access the SDK through the shared instance to perform operations like registering for push notifications, setting tags, and managing user data."}]},{"type":"heading","text":"Parameters","level":2,"anchor":"Parameters"},{"items":[{"content":[{"inlineContent":[{"text":"appCode: Your Pushwoosh Application Code from the Pushwoosh Control Panel","type":"text"}],"type":"paragraph"}]}],"type":"unorderedList"}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh"]]},"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/initialize(withAppCode:)"},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Initializes the Pushwoosh SDK with your application code.","type":"text"}],"variants":[{"paths":["\/documentation\/pushwooshframework\/pushwoosh\/initialize(withappcode:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pushwoosh\/initialize(withappcode:)"]}],"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/initialize(withAppCode:)":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"initialize"},{"text":"(","kind":"text"},{"text":"withAppCode","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"role":"symbol","url":"\/documentation\/pushwooshframework\/pushwoosh\/initialize(withappcode:)","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/initialize(withAppCode:)","title":"initialize(withAppCode:)","navigatorTitle":[{"text":"initializeWithAppCode:","kind":"identifier"}],"abstract":[{"type":"text","text":"Initializes the Pushwoosh SDK with your application code."}],"type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"title":"PushwooshFramework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","kind":"symbol","type":"topic","url":"\/documentation\/pushwooshframework","role":"collection","abstract":[]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Pushwoosh","kind":"identifier"}],"abstract":[{"type":"text","text":"Main SDK interface for push notification management."}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh","title":"Pushwoosh","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Pushwoosh"}],"url":"\/documentation\/pushwooshframework\/pushwoosh"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"initializeWithAppCode:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"initializeWithAppCode:"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"initializeWithAppCode:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"appCode","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1initialize(withAppCode:)\/title","value":"initializeWithAppCode:"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1initialize(withAppCode:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"initializeWithAppCode:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh\/title","value":"Pushwoosh","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh\/fragments","op":"replace","value":[{"kind":"identifier","text":"Pushwoosh"}]}]}]}