{"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/launchNotification","interfaceLanguage":"swift"},"metadata":{"title":"launchNotification","modules":[{"name":"PushwooshFramework"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"launchNotification","kind":"identifier"},{"kind":"text","text":": ["},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"text":"]?","kind":"text"}],"symbolKind":"property","externalID":"c:objc(cs)Pushwoosh(py)launchNotification","roleHeading":"Instance Property","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"launchNotification"}]},"seeAlsoSections":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/delegate","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWMessagingDelegate\/pushwoosh(_:onMessageOpened:)"],"title":"Related Documentation"}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"launchNotification","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"]? { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"level":2,"type":"heading","text":"Overview","anchor":"Overview"},{"inlineContent":[{"type":"text","text":"Contains the notification payload if the app was launched by tapping a push notification. Returns "},{"type":"codeVoice","code":"nil"},{"text":" if the app was launched normally.","type":"text"}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"text":"Use this for:","type":"text"}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"Cold start deep linking"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Handling notification actions on app launch"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Restoring state from notification data","type":"text"}]}]}]},{"type":"heading","anchor":"Timing","level":2,"text":"Timing"},{"type":"paragraph","inlineContent":[{"text":"This property is available immediately after SDK initialization. Check it early in your app lifecycle to handle launch notifications.","type":"text"}]},{"text":"Example","type":"heading","level":2,"anchor":"Example"},{"inlineContent":[{"text":"Handle launch notification in AppDelegate:","type":"text"}],"type":"paragraph"},{"syntax":"swift","type":"codeListing","code":["func application(_ application: UIApplication,","                didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {","","    Pushwoosh.configure.delegate = self","    Pushwoosh.configure.registerForPushNotifications()","","    if let launchNotification = Pushwoosh.configure.launchNotification {","        handleLaunchNotification(launchNotification)","    }","","    return true","}","","func handleLaunchNotification(_ payload: [AnyHashable: Any]) {","    guard let customData = payload[\"u\"] as? [String: Any],","          let screen = customData[\"screen\"] as? String else {","        return","    }","","    DispatchQueue.main.asyncAfter(deadline: .now() + 0.5) {","        DeepLinkRouter.shared.navigate(to: screen, params: customData)","    }","}"]},{"type":"paragraph","inlineContent":[{"text":"Check for launch notification in SceneDelegate:","type":"text"}]},{"code":["func scene(_ scene: UIScene, willConnectTo session: UISceneSession, options: UIScene.ConnectionOptions) {","","    if let launchNotification = Pushwoosh.configure.launchNotification {","        pendingDeepLink = extractDeepLink(from: launchNotification)","    }","}"],"type":"codeListing","syntax":"swift"}]}],"kind":"symbol","abstract":[{"text":"The push notification payload that launched the app.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pushwoosh\/launchnotification"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pushwoosh\/launchnotification"]}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh"]]},"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/launchNotification":{"url":"\/documentation\/pushwooshframework\/pushwoosh\/launchnotification","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"launchNotification"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]?"}],"role":"symbol","navigatorTitle":[{"text":"launchNotification","kind":"identifier"}],"type":"topic","title":"launchNotification","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/launchNotification","abstract":[{"text":"The push notification payload that launched the app.","type":"text"}],"kind":"symbol"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","title":"PushwooshFramework","type":"topic","kind":"symbol","abstract":[{"text":"Push notification SDK for iOS applications.","type":"text"}],"url":"\/documentation\/pushwooshframework","role":"collection"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh":{"url":"\/documentation\/pushwooshframework\/pushwoosh","kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Pushwoosh"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Pushwoosh","kind":"identifier"}],"title":"Pushwoosh","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh","abstract":[{"type":"text","text":"Main SDK interface for push notification management."}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/delegate":{"url":"\/documentation\/pushwooshframework\/pushwoosh\/delegate","kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"delegate"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"delegate","kind":"identifier"},{"text":": (any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)PWMessagingDelegate","text":"PWMessagingDelegate"},{"kind":"text","text":")?"}],"title":"delegate","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/delegate","abstract":[{"type":"text","text":"Delegate that receives push notification events."}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWMessagingDelegate/pushwoosh(_:onMessageOpened:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pushwoosh"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)Pushwoosh","text":"Pushwoosh","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"onMessageOpened"},{"text":": ","kind":"text"},{"text":"PWMessage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PWMessage"},{"text":")","kind":"text"}],"type":"topic","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Called when the user taps on a push notification."}],"navigatorTitle":[{"text":"pushwoosh:onMessageOpened:","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWMessagingDelegate\/pushwoosh(_:onMessageOpened:)","url":"\/documentation\/pushwooshframework\/pwmessagingdelegate\/pushwoosh(_:onmessageopened:)","title":"pushwoosh(_:onMessageOpened:)"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"launchNotification"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"launchNotification","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"replace","path":"\/seeAlsoSections","value":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/delegate","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWMessagingDelegate\/pushwoosh(_:onMessageOpened:)"],"title":"Related Documentation"}]},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"NSDictionary","preciseIdentifier":"c:objc(cs)NSDictionary","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"launchNotification","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1launchNotification\/title","value":"launchNotification"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1launchNotification\/fragments","value":[{"text":"launchNotification","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh\/title","value":"Pushwoosh"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh\/fragments","op":"replace","value":[{"text":"Pushwoosh","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1delegate\/title","op":"replace","value":"delegate"},{"value":[{"text":"delegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1delegate\/fragments","op":"replace"},{"value":"pushwoosh:onMessageOpened:","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWMessagingDelegate~1pushwoosh(_:onMessageOpened:)\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWMessagingDelegate~1pushwoosh(_:onMessageOpened:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"pushwoosh:onMessageOpened:","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}