{"variants":[{"paths":["\/documentation\/pushwooshframework\/pushwoosh\/notificationcenterdelegateproxy"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pushwooshframework\/pushwoosh\/notificationcenterdelegateproxy"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/notificationCenterDelegateProxy"},"metadata":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"notificationCenterDelegateProxy"},{"kind":"text","text":": "},{"text":"PWNotificationCenterDelegateProxy","preciseIdentifier":"c:objc(cs)PWNotificationCenterDelegateProxy","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"externalID":"c:objc(cs)Pushwoosh(py)notificationCenterDelegateProxy","title":"notificationCenterDelegateProxy","modules":[{"name":"PushwooshFramework"}],"navigatorTitle":[{"kind":"identifier","text":"notificationCenterDelegateProxy"}],"symbolKind":"property","roleHeading":"Instance Property"},"seeAlsoSections":[{"title":"Related Documentation","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/delegate","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWMessagingDelegate"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"notificationCenterDelegateProxy","kind":"identifier"},{"kind":"text","text":": "},{"text":"PWNotificationCenterDelegateProxy","preciseIdentifier":"c:objc(cs)PWNotificationCenterDelegateProxy","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWNotificationCenterDelegateProxy","kind":"typeIdentifier"},{"kind":"text","text":"? { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"content":[{"anchor":"Overview","type":"heading","text":"Overview","level":2},{"type":"paragraph","inlineContent":[{"text":"Allows multiple objects to receive ","type":"text"},{"code":"UNUserNotificationCenterDelegate","type":"codeVoice"},{"type":"text","text":" callbacks alongside Pushwoosh’s default handling. Use this when:"}]},{"items":[{"content":[{"inlineContent":[{"text":"Integrating multiple push notification SDKs","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Adding custom notification handling logic"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Implementing notification actions"}]}]}],"type":"unorderedList"},{"level":2,"anchor":"How-It-Works","text":"How It Works","type":"heading"},{"inlineContent":[{"text":"The proxy forwards all delegate methods to registered delegates, enabling multiple components to respond to notification events without conflicts.","type":"text"}],"type":"paragraph"},{"type":"heading","text":"Example","anchor":"Example","level":2},{"inlineContent":[{"type":"text","text":"Add custom notification delegate:"}],"type":"paragraph"},{"type":"codeListing","syntax":"swift","code":["class NotificationHandler: NSObject, UNUserNotificationCenterDelegate {","","    func userNotificationCenter(_ center: UNUserNotificationCenter,","                               willPresent notification: UNNotification,","                               withCompletionHandler completionHandler: @escaping (UNNotificationPresentationOptions) -> Void) {","        Analytics.log(\"notification_will_present\")","        completionHandler([.banner, .sound])","    }","","    func userNotificationCenter(_ center: UNUserNotificationCenter,","                               didReceive response: UNNotificationResponse,","                               withCompletionHandler completionHandler: @escaping () -> Void) {","        handleNotificationAction(response.actionIdentifier)","        completionHandler()","    }","}","","\/\/ Register with proxy","let handler = NotificationHandler()","Pushwoosh.configure.addNotificationCenterDelegate(handler)"]}],"kind":"content"}],"abstract":[{"type":"text","text":"Proxy that manages UNUserNotificationCenterDelegate objects."}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh"]]},"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/notificationCenterDelegateProxy":{"role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/notificationCenterDelegateProxy","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"notificationCenterDelegateProxy","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PWNotificationCenterDelegateProxy","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PWNotificationCenterDelegateProxy"},{"text":"?","kind":"text"}],"kind":"symbol","url":"\/documentation\/pushwooshframework\/pushwoosh\/notificationcenterdelegateproxy","type":"topic","title":"notificationCenterDelegateProxy","navigatorTitle":[{"kind":"identifier","text":"notificationCenterDelegateProxy"}],"abstract":[{"type":"text","text":"Proxy that manages UNUserNotificationCenterDelegate objects."}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWNotificationCenterDelegateProxy":{"kind":"symbol","title":"PWNotificationCenterDelegateProxy","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PWNotificationCenterDelegateProxy","kind":"identifier"}],"url":"\/documentation\/pushwooshframework\/pwnotificationcenterdelegateproxy","navigatorTitle":[{"text":"PWNotificationCenterDelegateProxy","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWNotificationCenterDelegateProxy","abstract":[]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/delegate":{"kind":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"delegate","kind":"identifier"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","text":"PWMessagingDelegate","preciseIdentifier":"c:objc(pl)PWMessagingDelegate"},{"text":")?","kind":"text"}],"abstract":[{"text":"Delegate that receives push notification events.","type":"text"}],"url":"\/documentation\/pushwooshframework\/pushwoosh\/delegate","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/delegate","role":"symbol","title":"delegate","navigatorTitle":[{"text":"delegate","kind":"identifier"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"kind":"symbol","title":"PushwooshFramework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","url":"\/documentation\/pushwooshframework","role":"collection","abstract":[{"text":"Push notification SDK for iOS applications.","type":"text"}],"type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh":{"navigatorTitle":[{"text":"Pushwoosh","kind":"identifier"}],"role":"symbol","url":"\/documentation\/pushwooshframework\/pushwoosh","abstract":[{"type":"text","text":"Main SDK interface for push notification management."}],"kind":"symbol","title":"Pushwoosh","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Pushwoosh"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWMessagingDelegate":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWMessagingDelegate","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"PWMessagingDelegate","kind":"identifier"}],"title":"PWMessagingDelegate","navigatorTitle":[{"text":"PWMessagingDelegate","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/pushwooshframework\/pwmessagingdelegate","abstract":[{"type":"text","text":"Delegate protocol for handling push notification events."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"notificationCenterDelegateProxy"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"notificationCenterDelegateProxy"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":[{"title":"Related Documentation","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/delegate","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWMessagingDelegate"]}],"op":"replace","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)PWNotificationCenterDelegateProxy","kind":"typeIdentifier","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWNotificationCenterDelegateProxy","text":"PWNotificationCenterDelegateProxy"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"notificationCenterDelegateProxy"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1notificationCenterDelegateProxy\/title","value":"notificationCenterDelegateProxy"},{"op":"replace","value":[{"kind":"identifier","text":"notificationCenterDelegateProxy"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1notificationCenterDelegateProxy\/fragments"},{"value":"PWNotificationCenterDelegateProxy","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWNotificationCenterDelegateProxy\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"PWNotificationCenterDelegateProxy"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWNotificationCenterDelegateProxy\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1delegate\/title","value":"delegate"},{"value":[{"kind":"identifier","text":"delegate"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1delegate\/fragments"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh\/title","op":"replace","value":"Pushwoosh"},{"value":[{"text":"Pushwoosh","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh\/fragments"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWMessagingDelegate\/title","value":"PWMessagingDelegate","op":"replace"},{"value":[{"kind":"identifier","text":"PWMessagingDelegate"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWMessagingDelegate\/fragments","op":"replace"}]}]}