{"variants":[{"paths":["\/documentation\/pushwooshframework\/pushwoosh\/purchasedelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pushwooshframework\/pushwoosh\/purchasedelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"purchaseDelegate"},{"text":": (any ","kind":"text"},{"text":"PWPurchaseDelegate","preciseIdentifier":"c:objc(pl)PWPurchaseDelegate","kind":"typeIdentifier"},{"kind":"text","text":")?"}],"title":"purchaseDelegate","modules":[{"name":"PushwooshFramework"}],"navigatorTitle":[{"kind":"identifier","text":"purchaseDelegate"}],"role":"symbol","symbolKind":"property","externalID":"c:objc(cs)Pushwoosh(py)purchaseDelegate"},"sections":[],"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/purchaseDelegate","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh"]]},"seeAlsoSections":[{"title":"Related Documentation","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWPurchaseDelegate","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/delegate"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"weak","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"purchaseDelegate"},{"text":": (any ","kind":"text"},{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWPurchaseDelegate","kind":"typeIdentifier","text":"PWPurchaseDelegate","preciseIdentifier":"c:objc(pl)PWPurchaseDelegate"},{"text":")? { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]},{"kind":"content","content":[{"text":"Overview","anchor":"Overview","level":2,"type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Set this property to handle purchase events triggered from Pushwoosh rich media notifications. The delegate receives callbacks for:"}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"Product information requests"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Successful purchases"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Failed payments"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Promoted purchases"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Transaction restoration failures"}],"type":"paragraph"}]}]},{"type":"heading","anchor":"Platform","level":2,"text":"Platform"},{"inlineContent":[{"type":"text","text":"This property is only available on iOS."}],"type":"paragraph"},{"anchor":"Example","level":2,"text":"Example","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"Set up purchase delegate:","type":"text"}]},{"syntax":"swift","type":"codeListing","code":["func application(_ application: UIApplication,","                didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {","","    Pushwoosh.configure.delegate = self","    Pushwoosh.configure.purchaseDelegate = self","    Pushwoosh.configure.registerForPushNotifications()","","    return true","}"]},{"type":"paragraph","inlineContent":[{"text":"Use a dedicated purchase handler:","type":"text"}]},{"syntax":"swift","type":"codeListing","code":["class PurchaseHandler: NSObject, PWPurchaseDelegate {","    static let shared = PurchaseHandler()","","    func onPWInAppPurchaseHelperPaymentComplete(_ identifier: String?) {","        guard let identifier = identifier else { return }","        PremiumManager.shared.unlock(productId: identifier)","    }","}","","\/\/ In AppDelegate","Pushwoosh.configure.purchaseDelegate = PurchaseHandler.shared"]}]}],"kind":"symbol","abstract":[{"text":"Delegate that receives in-app purchase events from rich media.","type":"text"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","abstract":[{"text":"Push notification SDK for iOS applications.","type":"text"}],"title":"PushwooshFramework","kind":"symbol","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","url":"\/documentation\/pushwooshframework"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWPurchaseDelegate":{"url":"\/documentation\/pushwooshframework\/pwpurchasedelegate","navigatorTitle":[{"kind":"identifier","text":"PWPurchaseDelegate"}],"abstract":[{"type":"text","text":"Delegate protocol for handling in-app purchase events from rich media."}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWPurchaseDelegate","kind":"symbol","title":"PWPurchaseDelegate","type":"topic","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"PWPurchaseDelegate","kind":"identifier"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh":{"title":"Pushwoosh","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh","abstract":[{"type":"text","text":"Main SDK interface for push notification management."}],"type":"topic","role":"symbol","url":"\/documentation\/pushwooshframework\/pushwoosh","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Pushwoosh"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Pushwoosh"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/delegate":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"delegate"}],"url":"\/documentation\/pushwooshframework\/pushwoosh\/delegate","title":"delegate","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/delegate","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"delegate"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)PWMessagingDelegate","text":"PWMessagingDelegate","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"abstract":[{"text":"Delegate that receives push notification events.","type":"text"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/purchaseDelegate":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"purchaseDelegate","kind":"identifier"},{"kind":"text","text":": (any "},{"text":"PWPurchaseDelegate","preciseIdentifier":"c:objc(pl)PWPurchaseDelegate","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"title":"purchaseDelegate","navigatorTitle":[{"kind":"identifier","text":"purchaseDelegate"}],"abstract":[{"type":"text","text":"Delegate that receives in-app purchase events from rich media."}],"type":"topic","kind":"symbol","url":"\/documentation\/pushwooshframework\/pushwoosh\/purchasedelegate","role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/purchaseDelegate"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"purchaseDelegate","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"purchaseDelegate","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":[{"title":"Related Documentation","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWPurchaseDelegate","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/delegate"]}],"op":"replace","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"weak","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSObjectobjc(pl)PWPurchaseDelegate","text":"NSObject<PWPurchaseDelegate>","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"purchaseDelegate","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWPurchaseDelegate\/title","op":"replace","value":"PWPurchaseDelegate"},{"value":[{"text":"PWPurchaseDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWPurchaseDelegate\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh\/title","value":"Pushwoosh"},{"value":[{"kind":"identifier","text":"Pushwoosh"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh\/fragments"},{"value":"delegate","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1delegate\/title","op":"replace"},{"value":[{"text":"delegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1delegate\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1purchaseDelegate\/title","value":"purchaseDelegate"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1purchaseDelegate\/fragments","op":"replace","value":[{"text":"purchaseDelegate","kind":"identifier"}]}]}]}