{"abstract":[{"type":"text","text":"Registers the device for push notifications."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"seeAlsoSections":[{"title":"Related Documentation","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/registerForPushNotifications(completion:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/unregisterForPushNotifications()","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/delegate","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWMessagingDelegate"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pushwoosh\/registerforpushnotifications()"]},{"paths":["\/documentation\/pushwooshframework\/pushwoosh\/registerforpushnotifications()"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"registerForPushNotifications","kind":"identifier"},{"text":"()","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"content","content":[{"anchor":"Overview","type":"heading","level":2,"text":"Overview"},{"type":"paragraph","inlineContent":[{"text":"This method initiates the push notification registration process:","type":"text"}]},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Requests user permission to display notifications"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Registers the device with Apple Push Notification service (APNs)"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Sends the device token to Pushwoosh servers"}]}]}],"type":"orderedList"},{"level":2,"text":"Permission Dialog","anchor":"Permission-Dialog","type":"heading"},{"inlineContent":[{"text":"The system permission dialog is shown only once per app installation. If the user:","type":"text"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"inlineContent":[{"type":"text","text":"Grants permission"}],"type":"strong"},{"type":"text","text":": Device receives a push token from APNs"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Denies permission"}]},{"text":": No token is received; user must enable notifications in Settings","type":"text"}],"type":"paragraph"}]}]},{"text":"When to Call","type":"heading","anchor":"When-to-Call","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Call this method:"}]},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"In ","type":"text"},{"code":"application(_:didFinishLaunchingWithOptions:)","type":"codeVoice"},{"type":"text","text":" for immediate registration"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"After onboarding flow to explain notification benefits first","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"When user explicitly enables notifications in your app settings","type":"text"}]}]}],"type":"unorderedList"},{"anchor":"Example","text":"Example","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"Register for push notifications at app launch:"}],"type":"paragraph"},{"type":"codeListing","code":["func application(_ application: UIApplication,","                didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {","","    Pushwoosh.configure.delegate = self","    Pushwoosh.configure.registerForPushNotifications()","","    return true","}"],"syntax":"swift"},{"inlineContent":[{"text":"Register after user completes onboarding:","type":"text"}],"type":"paragraph"},{"code":["func completeOnboarding() {","    userDefaults.set(true, forKey: \"onboardingComplete\")","","    Pushwoosh.configure.registerForPushNotifications()","","    navigateToMainScreen()","}"],"type":"codeListing","syntax":"swift"},{"inlineContent":[{"text":"Prompt user before requesting permission:","type":"text"}],"type":"paragraph"},{"code":["func showNotificationPrompt() {","    let alert = UIAlertController(","        title: \"Stay Updated\",","        message: \"Enable notifications to receive order updates and exclusive offers\",","        preferredStyle: .alert","    )","","    alert.addAction(UIAlertAction(title: \"Enable\", style: .default) { _ in","        Pushwoosh.configure.registerForPushNotifications()","    })","","    alert.addAction(UIAlertAction(title: \"Later\", style: .cancel))","","    present(alert, animated: true)","}"],"type":"codeListing","syntax":"swift"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/registerForPushNotifications()"},"sections":[],"metadata":{"symbolKind":"method","title":"registerForPushNotifications()","externalID":"c:objc(cs)Pushwoosh(im)registerForPushNotifications","navigatorTitle":[{"text":"registerForPushNotifications","kind":"identifier"}],"roleHeading":"Instance Method","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"registerForPushNotifications","kind":"identifier"},{"kind":"text","text":"()"}],"modules":[{"name":"PushwooshFramework"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh"]]},"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/delegate":{"kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/delegate","url":"\/documentation\/pushwooshframework\/pushwoosh\/delegate","role":"symbol","navigatorTitle":[{"text":"delegate","kind":"identifier"}],"type":"topic","abstract":[{"text":"Delegate that receives push notification events.","type":"text"}],"title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"delegate"},{"text":": (any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)PWMessagingDelegate","text":"PWMessagingDelegate"},{"text":")?","kind":"text"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh":{"type":"topic","title":"Pushwoosh","abstract":[{"type":"text","text":"Main SDK interface for push notification management."}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh","kind":"symbol","navigatorTitle":[{"text":"Pushwoosh","kind":"identifier"}],"role":"symbol","url":"\/documentation\/pushwooshframework\/pushwoosh","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Pushwoosh","kind":"identifier"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWMessagingDelegate":{"title":"PWMessagingDelegate","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PWMessagingDelegate","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"PWMessagingDelegate"}],"abstract":[{"type":"text","text":"Delegate protocol for handling push notification events."}],"kind":"symbol","url":"\/documentation\/pushwooshframework\/pwmessagingdelegate","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWMessagingDelegate"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/registerForPushNotifications()":{"kind":"symbol","url":"\/documentation\/pushwooshframework\/pushwoosh\/registerforpushnotifications()","abstract":[{"text":"Registers the device for push notifications.","type":"text"}],"type":"topic","role":"symbol","title":"registerForPushNotifications()","navigatorTitle":[{"kind":"identifier","text":"registerForPushNotifications"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"registerForPushNotifications"},{"text":"()","kind":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/registerForPushNotifications()"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/unregisterForPushNotifications()":{"navigatorTitle":[{"kind":"identifier","text":"unregisterForPushNotifications"}],"abstract":[{"text":"Unregisters the device from push notifications.","type":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/unregisterForPushNotifications()","role":"symbol","kind":"symbol","type":"topic","title":"unregisterForPushNotifications()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unregisterForPushNotifications","kind":"identifier"},{"kind":"text","text":"()"}],"url":"\/documentation\/pushwooshframework\/pushwoosh\/unregisterforpushnotifications()"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"abstract":[{"text":"Push notification SDK for iOS applications.","type":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","type":"topic","title":"PushwooshFramework","url":"\/documentation\/pushwooshframework","kind":"symbol","role":"collection"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/registerForPushNotifications(completion:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"registerForPushNotifications"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"text":": ","kind":"text"},{"text":"PushwooshRegistrationHandler","kind":"typeIdentifier","preciseIdentifier":"c:PWTypes.h@T@PushwooshRegistrationHandler"},{"kind":"text","text":"?)"}],"title":"registerForPushNotifications(completion:)","navigatorTitle":[{"text":"registerForPushNotificationsWithCompletion:","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Registers the device for push notifications with a completion handler."}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/registerForPushNotifications(completion:)","url":"\/documentation\/pushwooshframework\/pushwoosh\/registerforpushnotifications(completion:)","kind":"symbol","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"registerForPushNotifications","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"registerForPushNotifications","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"replace","value":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/registerForPushNotifications(completion:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/unregisterForPushNotifications()","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/delegate","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWMessagingDelegate"],"title":"Related Documentation"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"text":"registerForPushNotifications","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"delegate","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1delegate\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1delegate\/fragments","value":[{"text":"delegate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh\/title","op":"replace","value":"Pushwoosh"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh\/fragments","value":[{"kind":"identifier","text":"Pushwoosh"}],"op":"replace"},{"value":"PWMessagingDelegate","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWMessagingDelegate\/title"},{"op":"replace","value":[{"text":"PWMessagingDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWMessagingDelegate\/fragments"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1registerForPushNotifications()\/title","value":"registerForPushNotifications","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1registerForPushNotifications()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"registerForPushNotifications","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1unregisterForPushNotifications()\/title","op":"replace","value":"unregisterForPushNotifications"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1unregisterForPushNotifications()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"unregisterForPushNotifications"}]},{"op":"replace","value":"registerForPushNotificationsWithCompletion:","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1registerForPushNotifications(completion:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1registerForPushNotifications(completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"registerForPushNotificationsWithCompletion:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}