{"seeAlsoSections":[{"title":"Related Documentation","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/registerSmsNumber(_:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/setEmail(_:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/registerWhatsappNumber(_:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"registerWhatsappNumber","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"number"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"level":2,"type":"heading","text":"Overview","anchor":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Associates a WhatsApp number with the device to enable WhatsApp Business campaigns. This enables:"}]},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"WhatsApp marketing messages","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Rich media messages via WhatsApp"}]}]},{"content":[{"inlineContent":[{"text":"Interactive message templates","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Multi-channel engagement strategy"}]}]}],"type":"unorderedList"},{"text":"Phone Number Format","anchor":"Phone-Number-Format","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"Use international format with country code:"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"codeVoice","code":"\"+1234567890\""},{"type":"text","text":" (with plus)"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"code":"\"1234567890\"","type":"codeVoice"},{"type":"text","text":" (without plus)"}]}]}]},{"anchor":"Example","level":2,"type":"heading","text":"Example"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Register WhatsApp number after verification:"}]},{"type":"codeListing","code":["func handleWhatsAppVerified(phoneNumber: String) {","    Pushwoosh.configure.registerWhatsappNumber(phoneNumber)","","    Pushwoosh.configure.setTags([","        \"whatsapp_enabled\": true,","        \"preferred_channel\": \"whatsapp\"","    ])","}"],"syntax":"swift"},{"inlineContent":[{"type":"text","text":"Offer WhatsApp opt-in:"}],"type":"paragraph"},{"syntax":"swift","type":"codeListing","code":["func showWhatsAppOptIn() {","    let alert = UIAlertController(","        title: \"Get Updates on WhatsApp\",","        message: \"Receive order updates and offers on WhatsApp\",","        preferredStyle: .alert","    )","","    alert.addAction(UIAlertAction(title: \"Enable\", style: .default) { _ in","        if let phone = self.userProfile.phoneNumber {","            Pushwoosh.configure.registerWhatsappNumber(phone)","        }","    })","","    alert.addAction(UIAlertAction(title: \"Not Now\", style: .cancel))","","    present(alert, animated: true)","}"]}]}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh"]]},"sections":[],"metadata":{"title":"registerWhatsappNumber(_:)","roleHeading":"Instance Method","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"registerWhatsappNumber","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":")"}],"externalID":"c:objc(cs)Pushwoosh(im)registerWhatsappNumber:","modules":[{"name":"PushwooshFramework"}],"navigatorTitle":[{"text":"registerWhatsappNumber:","kind":"identifier"}],"symbolKind":"method"},"abstract":[{"text":"Registers a WhatsApp phone number for multi-channel messaging.","type":"text"}],"variants":[{"paths":["\/documentation\/pushwooshframework\/pushwoosh\/registerwhatsappnumber(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pushwooshframework\/pushwoosh\/registerwhatsappnumber(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/registerWhatsappNumber(_:)":{"title":"registerWhatsappNumber(_:)","kind":"symbol","abstract":[{"text":"Registers a WhatsApp phone number for multi-channel messaging.","type":"text"}],"url":"\/documentation\/pushwooshframework\/pushwoosh\/registerwhatsappnumber(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"registerWhatsappNumber"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"registerWhatsappNumber:"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/registerWhatsappNumber(_:)","type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","kind":"symbol","url":"\/documentation\/pushwooshframework","type":"topic","title":"PushwooshFramework","abstract":[{"type":"text","text":"Push notification SDK for iOS applications."}],"role":"collection"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/setEmail(_:)":{"title":"setEmail(_:)","kind":"symbol","abstract":[{"type":"text","text":"Associates an email address with the current device."}],"url":"\/documentation\/pushwooshframework\/pushwoosh\/setemail(_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setEmail","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"setEmail:"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/setEmail(_:)","type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh":{"url":"\/documentation\/pushwooshframework\/pushwoosh","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh","role":"symbol","abstract":[{"type":"text","text":"Main SDK interface for push notification management."}],"title":"Pushwoosh","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Pushwoosh"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Pushwoosh"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/registerSmsNumber(_:)":{"title":"registerSmsNumber(_:)","kind":"symbol","abstract":[{"type":"text","text":"Registers an SMS phone number for multi-channel messaging."}],"url":"\/documentation\/pushwooshframework\/pushwoosh\/registersmsnumber(_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"registerSmsNumber","kind":"identifier"},{"kind":"text","text":"("},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"registerSmsNumber:","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/registerSmsNumber(_:)","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"registerWhatsappNumber:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"registerWhatsappNumber:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/registerSmsNumber(_:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/setEmail(_:)"],"title":"Related Documentation"}],"path":"\/seeAlsoSections","op":"replace"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"registerWhatsappNumber:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"number"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1registerWhatsappNumber(_:)\/title","op":"replace","value":"registerWhatsappNumber:"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1registerWhatsappNumber(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"registerWhatsappNumber:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1setEmail(_:)\/title","value":"setEmail:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setEmail:"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1setEmail(_:)\/fragments"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh\/title","op":"replace","value":"Pushwoosh"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh\/fragments","op":"replace","value":[{"text":"Pushwoosh","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1registerSmsNumber(_:)\/title","op":"replace","value":"registerSmsNumber:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"registerSmsNumber:"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1registerSmsNumber(_:)\/fragments"}]}]}