{"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/registerForPushNotifications(with:completion:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"registerForPushNotifications"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"tags"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"], "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PushwooshRegistrationHandler","preciseIdentifier":"c:PWTypes.h@T@PushwooshRegistrationHandler","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushwooshRegistrationHandler"},{"kind":"text","text":"? = nil)"}],"languages":["swift"]}]},{"kind":"content","content":[{"type":"heading","level":2,"text":"Discussion","anchor":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"This method combines device registration and tag assignment, providing a callback when the operation completes. Use this when you need to know whether registration succeeded and want to set initial tags.","type":"text"}]},{"inlineContent":[{"type":"text","text":"The tags are only set if registration succeeds. If registration fails, the tags will not be applied."}],"type":"paragraph"},{"type":"heading","text":"Parameters","level":2,"anchor":"Parameters"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"tags: Dictionary of tag names and values to set during registration"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"completion: Block called when registration completes, providing the push token or an error"}],"type":"paragraph"}]}]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh"]]},"metadata":{"roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"registerForPushNotifications","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"], ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:PWTypes.h@T@PushwooshRegistrationHandler","kind":"typeIdentifier","text":"PushwooshRegistrationHandler"},{"kind":"text","text":"?)"}],"title":"registerForPushNotifications(with:completion:)","symbolKind":"method","modules":[{"name":"PushwooshFramework"}],"role":"symbol","navigatorTitle":[{"text":"registerForPushNotificationsWith:completion:","kind":"identifier"}],"externalID":"c:objc(cs)Pushwoosh(im)registerForPushNotificationsWith:completion:"},"abstract":[{"type":"text","text":"Registers the device for push notifications with initial tags and a completion handler."}],"variants":[{"paths":["\/documentation\/pushwooshframework\/pushwoosh\/registerforpushnotifications(with:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pushwoosh\/registerforpushnotifications(with:completion:)"]}],"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh":{"abstract":[{"text":"Main SDK interface for push notification management.","type":"text"}],"title":"Pushwoosh","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Pushwoosh"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh","url":"\/documentation\/pushwooshframework\/pushwoosh","role":"symbol","navigatorTitle":[{"text":"Pushwoosh","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushwooshRegistrationHandler":{"role":"symbol","title":"PushwooshRegistrationHandler","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushwooshRegistrationHandler","abstract":[{"text":"Completion handler called when push notification registration completes.","type":"text"}],"type":"topic","url":"\/documentation\/pushwooshframework\/pushwooshregistrationhandler","kind":"symbol","fragments":[{"kind":"identifier","text":"PushwooshRegistrationHandler"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"abstract":[],"kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","url":"\/documentation\/pushwooshframework","type":"topic","role":"collection","title":"PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/registerForPushNotifications(with:completion:)":{"navigatorTitle":[{"text":"registerForPushNotificationsWith:completion:","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/registerForPushNotifications(with:completion:)","kind":"symbol","url":"\/documentation\/pushwooshframework\/pushwoosh\/registerforpushnotifications(with:completion:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"registerForPushNotifications"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"with"},{"kind":"text","text":": ["},{"text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"], ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PushwooshRegistrationHandler","preciseIdentifier":"c:PWTypes.h@T@PushwooshRegistrationHandler"},{"text":"?)","kind":"text"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Registers the device for push notifications with initial tags and a completion handler."}],"title":"registerForPushNotifications(with:completion:)"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"registerForPushNotificationsWith:completion:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"registerForPushNotificationsWith:completion:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"registerForPushNotificationsWith:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSDictionary","preciseIdentifier":"c:objc(cs)NSDictionary"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"tags"},{"text":" ","kind":"text"},{"kind":"identifier","text":"completion:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:BFv(#*$objc(cs)NSString#*$objc(cs)NSError)","text":"void (^)(NSString *, NSError *)","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"completion","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"value":"Pushwoosh","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh\/title"},{"value":[{"kind":"identifier","text":"Pushwoosh"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh\/fragments"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1registerForPushNotifications(with:completion:)\/title","value":"registerForPushNotificationsWith:completion:","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1registerForPushNotifications(with:completion:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"registerForPushNotificationsWith:completion:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}