{"metadata":{"role":"symbol","roleHeading":"Instance Method","title":"registerForPushNotifications(completion:)","symbolKind":"method","externalID":"c:objc(cs)Pushwoosh(im)registerForPushNotificationsWithCompletion:","navigatorTitle":[{"text":"registerForPushNotificationsWithCompletion:","kind":"identifier"}],"modules":[{"name":"PushwooshFramework"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"registerForPushNotifications","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"text":": ","kind":"text"},{"text":"PushwooshRegistrationHandler","kind":"typeIdentifier","preciseIdentifier":"c:PWTypes.h@T@PushwooshRegistrationHandler"},{"kind":"text","text":"?)"}]},"sections":[],"kind":"symbol","abstract":[{"text":"Registers the device for push notifications with a completion handler.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"registerForPushNotifications"},{"kind":"text","text":"("},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"PushwooshRegistrationHandler","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushwooshRegistrationHandler","preciseIdentifier":"c:PWTypes.h@T@PushwooshRegistrationHandler"},{"kind":"text","text":"? = nil)"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"anchor":"Overview","type":"heading","text":"Overview","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Same as "},{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/registerForPushNotifications()","isActive":true,"type":"reference"},{"type":"text","text":" but provides a completion callback with the registration result."}]},{"type":"paragraph","inlineContent":[{"text":"Use this variant when you need to:","type":"text"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Confirm registration succeeded","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Get the push token immediately"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Handle registration errors"}]}]},{"content":[{"inlineContent":[{"text":"Chain operations after registration","type":"text"}],"type":"paragraph"}]}]},{"type":"heading","anchor":"Example","level":2,"text":"Example"},{"type":"paragraph","inlineContent":[{"text":"Register and wait for result:","type":"text"}]},{"syntax":"swift","type":"codeListing","code":["func enablePushNotifications() {","    Pushwoosh.configure.registerForPushNotifications { token, error in","        if let error = error {","            self.showError(\"Push registration failed: \\(error.localizedDescription)\")","            return","        }","","        if let token = token {","            self.syncTokenWithBackend(token)","        }","","        self.updateUI(pushEnabled: true)","    }","}"]},{"inlineContent":[{"type":"text","text":"Register with async\/await:"}],"type":"paragraph"},{"code":["func enablePushNotifications() async throws -> String? {","    try await withCheckedThrowingContinuation { continuation in","        Pushwoosh.configure.registerForPushNotifications { token, error in","            if let error = error {","                continuation.resume(throwing: error)","            } else {","                continuation.resume(returning: token)","            }","        }","    }","}"],"type":"codeListing","syntax":"swift"},{"type":"paragraph","inlineContent":[{"text":"Show different UI based on result:","type":"text"}]},{"type":"codeListing","syntax":"swift","code":["func requestPushPermission() {","    Pushwoosh.configure.registerForPushNotifications { token, error in","        DispatchQueue.main.async {","            if token != nil {","                self.showSuccessState()","            } else if let error = error as NSError?,","                      error.code == 3010 {","                self.showPermissionDeniedState()","            } else {","                self.showErrorState()","            }","        }","    }","}"]}]}],"seeAlsoSections":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/registerForPushNotifications()","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/unregisterForPushNotifications(completion:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/getPushToken()"],"title":"Related Documentation"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/registerForPushNotifications(completion:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh"]]},"variants":[{"paths":["\/documentation\/pushwooshframework\/pushwoosh\/registerforpushnotifications(completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pushwoosh\/registerforpushnotifications(completion:)"]}],"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/registerForPushNotifications()":{"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/registerForPushNotifications()","role":"symbol","title":"registerForPushNotifications()","url":"\/documentation\/pushwooshframework\/pushwoosh\/registerforpushnotifications()","abstract":[{"text":"Registers the device for push notifications.","type":"text"}],"navigatorTitle":[{"text":"registerForPushNotifications","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"registerForPushNotifications"},{"text":"()","kind":"text"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushwooshRegistrationHandler":{"role":"symbol","type":"topic","title":"PushwooshRegistrationHandler","abstract":[{"type":"text","text":"Completion handler called when push notification registration completes."}],"url":"\/documentation\/pushwooshframework\/pushwooshregistrationhandler","kind":"symbol","fragments":[{"text":"PushwooshRegistrationHandler","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushwooshRegistrationHandler"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh":{"navigatorTitle":[{"text":"Pushwoosh","kind":"identifier"}],"abstract":[{"text":"Main SDK interface for push notification management.","type":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Pushwoosh"}],"title":"Pushwoosh","type":"topic","url":"\/documentation\/pushwooshframework\/pushwoosh"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/registerForPushNotifications(completion:)":{"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/registerForPushNotifications(completion:)","role":"symbol","title":"registerForPushNotifications(completion:)","abstract":[{"text":"Registers the device for push notifications with a completion handler.","type":"text"}],"url":"\/documentation\/pushwooshframework\/pushwoosh\/registerforpushnotifications(completion:)","navigatorTitle":[{"kind":"identifier","text":"registerForPushNotificationsWithCompletion:"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"registerForPushNotifications","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:PWTypes.h@T@PushwooshRegistrationHandler","text":"PushwooshRegistrationHandler","kind":"typeIdentifier"},{"text":"?)","kind":"text"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/unregisterForPushNotifications(completion:)":{"abstract":[{"text":"Unregisters the device from push notifications with a completion handler.","type":"text"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/unregisterForPushNotifications(completion:)","title":"unregisterForPushNotifications(completion:)","kind":"symbol","navigatorTitle":[{"text":"unregisterForPushNotificationsWithCompletion:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unregisterForPushNotifications","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": (((any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")?)"}],"url":"\/documentation\/pushwooshframework\/pushwoosh\/unregisterforpushnotifications(completion:)"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","kind":"symbol","type":"topic","url":"\/documentation\/pushwooshframework","role":"collection","title":"PushwooshFramework","abstract":[{"text":"Push notification SDK for iOS applications.","type":"text"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/getPushToken()":{"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/getPushToken()","role":"symbol","title":"getPushToken()","abstract":[{"type":"text","text":"Retrieves the current device push token."}],"url":"\/documentation\/pushwooshframework\/pushwoosh\/getpushtoken()","navigatorTitle":[{"text":"getPushToken","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getPushToken"},{"kind":"text","text":"() -> "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","value":"registerForPushNotificationsWithCompletion:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"registerForPushNotificationsWithCompletion:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":[{"title":"Related Documentation","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/registerForPushNotifications()","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/unregisterForPushNotifications(completion:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/getPushToken()"]}],"op":"replace"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"registerForPushNotificationsWithCompletion:","kind":"identifier"},{"kind":"text","text":"("},{"text":"void (^)(NSString *, NSError *)","kind":"typeIdentifier","preciseIdentifier":"c:BFv(#*$objc(cs)NSString#*$objc(cs)NSError)"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"completion"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"registerForPushNotifications","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1registerForPushNotifications()\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1registerForPushNotifications()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"registerForPushNotifications","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh\/title","op":"replace","value":"Pushwoosh"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh\/fragments","value":[{"kind":"identifier","text":"Pushwoosh"}]},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1registerForPushNotifications(completion:)\/title","op":"replace","value":"registerForPushNotificationsWithCompletion:"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1registerForPushNotifications(completion:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"registerForPushNotificationsWithCompletion:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1unregisterForPushNotifications(completion:)\/title","value":"unregisterForPushNotificationsWithCompletion:"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1unregisterForPushNotifications(completion:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"unregisterForPushNotificationsWithCompletion:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1getPushToken()\/title","value":"getPushToken","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"getPushToken","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1getPushToken()\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}