{"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/registerSmsNumber(_:)"},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh"]]},"abstract":[{"text":"Registers an SMS phone number for multi-channel messaging.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"registerSmsNumber","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"number","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"content":[{"type":"heading","text":"Overview","anchor":"Overview","level":2},{"inlineContent":[{"type":"text","text":"Associates a phone number with the device to enable SMS campaigns alongside push notifications. This enables:"}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"SMS marketing campaigns","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Transactional SMS messages"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Multi-channel user engagement"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Fallback communication when push is unavailable"}]}]}],"type":"unorderedList"},{"text":"Phone Number Format","anchor":"Phone-Number-Format","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"text":"Use international format with country code:","type":"text"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"code":"\"+1234567890\"","type":"codeVoice"},{"type":"text","text":" (with plus)"}]}]},{"content":[{"inlineContent":[{"type":"codeVoice","code":"\"1234567890\""},{"text":" (without plus)","type":"text"}],"type":"paragraph"}]}]},{"level":2,"type":"heading","anchor":"Example","text":"Example"},{"type":"paragraph","inlineContent":[{"text":"Register phone number during onboarding:","type":"text"}]},{"type":"codeListing","code":["func completePhoneVerification(phoneNumber: String) {","    Pushwoosh.configure.registerSmsNumber(phoneNumber)","","    Pushwoosh.configure.setTags([","        \"phone_verified\": true,","        \"phone_country\": extractCountryCode(from: phoneNumber)","    ])","}"],"syntax":"swift"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Update phone number in settings:"}]},{"code":["func updatePhoneNumber(_ phoneNumber: String) {","    let formattedNumber = formatInternational(phoneNumber)","","    Pushwoosh.configure.registerSmsNumber(formattedNumber)","","    showSuccess(\"Phone number updated\")","}"],"syntax":"swift","type":"codeListing"}],"kind":"content"}],"variants":[{"paths":["\/documentation\/pushwooshframework\/pushwoosh\/registersmsnumber(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pushwoosh\/registersmsnumber(_:)"]}],"kind":"symbol","metadata":{"title":"registerSmsNumber(_:)","modules":[{"name":"PushwooshFramework"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"registerSmsNumber"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"registerSmsNumber:"}],"externalID":"c:objc(cs)Pushwoosh(im)registerSmsNumber:","role":"symbol","roleHeading":"Instance Method"},"sections":[],"seeAlsoSections":[{"title":"Related Documentation","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/registerWhatsappNumber(_:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/setEmail(_:)"]}],"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/setEmail(_:)":{"url":"\/documentation\/pushwooshframework\/pushwoosh\/setemail(_:)","type":"topic","role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/setEmail(_:)","navigatorTitle":[{"kind":"identifier","text":"setEmail:"}],"abstract":[{"type":"text","text":"Associates an email address with the current device."}],"title":"setEmail(_:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setEmail","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh":{"type":"topic","abstract":[{"type":"text","text":"Main SDK interface for push notification management."}],"url":"\/documentation\/pushwooshframework\/pushwoosh","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh","navigatorTitle":[{"text":"Pushwoosh","kind":"identifier"}],"title":"Pushwoosh","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Pushwoosh","kind":"identifier"}],"role":"symbol"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/registerSmsNumber(_:)":{"title":"registerSmsNumber(_:)","role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/registerSmsNumber(_:)","navigatorTitle":[{"text":"registerSmsNumber:","kind":"identifier"}],"type":"topic","url":"\/documentation\/pushwooshframework\/pushwoosh\/registersmsnumber(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"registerSmsNumber","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Registers an SMS phone number for multi-channel messaging."}],"kind":"symbol"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"type":"topic","abstract":[{"type":"text","text":"Push notification SDK for iOS applications."}],"url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","kind":"symbol","title":"PushwooshFramework","role":"collection"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/registerWhatsappNumber(_:)":{"title":"registerWhatsappNumber(_:)","role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/registerWhatsappNumber(_:)","navigatorTitle":[{"kind":"identifier","text":"registerWhatsappNumber:"}],"type":"topic","url":"\/documentation\/pushwooshframework\/pushwoosh\/registerwhatsappnumber(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"registerWhatsappNumber","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":")","kind":"text"}],"abstract":[{"text":"Registers a WhatsApp phone number for multi-channel messaging.","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"registerSmsNumber:","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"registerSmsNumber:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Related Documentation","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/registerWhatsappNumber(_:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/setEmail(_:)"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"registerSmsNumber:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"number"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"value":"setEmail:","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1setEmail(_:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1setEmail(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setEmail:"}],"op":"replace"},{"value":"Pushwoosh","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh\/title","op":"replace"},{"value":[{"text":"Pushwoosh","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh\/fragments"},{"value":"registerSmsNumber:","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1registerSmsNumber(_:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"registerSmsNumber:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1registerSmsNumber(_:)\/fragments"},{"op":"replace","value":"registerWhatsappNumber:","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1registerWhatsappNumber(_:)\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1registerWhatsappNumber(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"registerWhatsappNumber:","kind":"identifier"}],"op":"replace"}]}]}