{"metadata":{"symbolKind":"method","modules":[{"name":"PushwooshFramework"}],"externalID":"c:objc(cs)Pushwoosh(im)registerForPushNotificationsWith:","title":"registerForPushNotifications(with:)","roleHeading":"Instance Method","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"registerForPushNotifications"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"with"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier","text":"AnyHashable"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"])","kind":"text"}],"navigatorTitle":[{"text":"registerForPushNotificationsWith:","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh"]]},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"text":"Registers the device for push notifications and sets initial tags.","type":"text"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pushwoosh\/registerforpushnotifications(with:)"]},{"paths":["\/documentation\/pushwooshframework\/pushwoosh\/registerforpushnotifications(with:)"],"traits":[{"interfaceLanguage":"occ"}]}],"seeAlsoSections":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/registerForPushNotifications(with:completion:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/registerForPushNotifications()"],"title":"Related Documentation"}],"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/registerForPushNotifications(with:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"registerForPushNotifications"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"kind":"internalParam","text":"tags"},{"text":": [","kind":"text"},{"text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"])","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"content":[{"anchor":"Overview","text":"Overview","level":2,"type":"heading"},{"inlineContent":[{"text":"This method combines device registration with tag assignment in a single call. It requests user permission for notifications, registers with APNs, and immediately sets the provided tags on the device.","type":"text"}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"text":"This is equivalent to calling ","type":"text"},{"code":"registerForPushNotifications()","type":"codeVoice"},{"text":" followed by ","type":"text"},{"code":"setTags:","type":"codeVoice"},{"text":", but more efficient as it combines both operations.","type":"text"}]},{"level":2,"type":"heading","anchor":"Example","text":"Example"},{"type":"paragraph","inlineContent":[{"text":"Register with user context tags:","type":"text"}]},{"type":"codeListing","syntax":"swift","code":["func completeOnboarding(user: OnboardingResult) {","    let initialTags: [String: Any] = [","        \"onboarding_completed\": true,","        \"interests\": user.selectedInterests,","        \"language\": Locale.current.languageCode ?? \"en\",","        \"timezone\": TimeZone.current.identifier","    ]","","    Pushwoosh.configure.registerForPushNotifications(with: initialTags)","}"]},{"inlineContent":[{"type":"text","text":"Register with app version and install source:"}],"type":"paragraph"},{"code":["func setupPushNotifications() {","    let appVersion = Bundle.main.infoDictionary?[\"CFBundleShortVersionString\"] as? String","    let installSource = InstallTracker.getInstallSource()","","    Pushwoosh.configure.registerForPushNotifications(with: [","        \"app_version\": appVersion ?? \"unknown\",","        \"install_source\": installSource,","        \"first_launch\": true","    ])","}"],"type":"codeListing","syntax":"swift"}],"kind":"content"}],"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh":{"title":"Pushwoosh","navigatorTitle":[{"kind":"identifier","text":"Pushwoosh"}],"abstract":[{"text":"Main SDK interface for push notification management.","type":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh","url":"\/documentation\/pushwooshframework\/pushwoosh","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Pushwoosh","kind":"identifier"}],"type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/registerForPushNotifications(with:)":{"title":"registerForPushNotifications(with:)","abstract":[{"text":"Registers the device for push notifications and sets initial tags.","type":"text"}],"navigatorTitle":[{"text":"registerForPushNotificationsWith:","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"registerForPushNotifications","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"])"}],"type":"topic","url":"\/documentation\/pushwooshframework\/pushwoosh\/registerforpushnotifications(with:)","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/registerForPushNotifications(with:)"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","kind":"symbol","role":"collection","title":"PushwooshFramework","url":"\/documentation\/pushwooshframework","type":"topic","abstract":[{"text":"Push notification SDK for iOS applications.","type":"text"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/registerForPushNotifications(with:completion:)":{"title":"registerForPushNotifications(with:completion:)","abstract":[{"type":"text","text":"Registers the device for push notifications with initial tags and a completion handler."}],"navigatorTitle":[{"kind":"identifier","text":"registerForPushNotificationsWith:completion:"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"registerForPushNotifications","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"], ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:PWTypes.h@T@PushwooshRegistrationHandler","text":"PushwooshRegistrationHandler"},{"kind":"text","text":"?)"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/registerForPushNotifications(with:completion:)","url":"\/documentation\/pushwooshframework\/pushwoosh\/registerforpushnotifications(with:completion:)"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/registerForPushNotifications()":{"title":"registerForPushNotifications()","navigatorTitle":[{"text":"registerForPushNotifications","kind":"identifier"}],"abstract":[{"text":"Registers the device for push notifications.","type":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/registerForPushNotifications()","url":"\/documentation\/pushwooshframework\/pushwoosh\/registerforpushnotifications()","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"registerForPushNotifications","kind":"identifier"},{"kind":"text","text":"()"}],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"registerForPushNotificationsWith:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"registerForPushNotificationsWith:"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/registerForPushNotifications(with:completion:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/registerForPushNotifications()"],"title":"Related Documentation"}],"op":"replace","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"registerForPushNotificationsWith:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSDictionary","kind":"typeIdentifier","text":"NSDictionary"},{"text":" *) ","kind":"text"},{"text":"tags","kind":"internalParam"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh\/title","value":"Pushwoosh"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh\/fragments","value":[{"kind":"identifier","text":"Pushwoosh"}]},{"value":"registerForPushNotificationsWith:","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1registerForPushNotifications(with:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"registerForPushNotificationsWith:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1registerForPushNotifications(with:)\/fragments"},{"op":"replace","value":"registerForPushNotificationsWith:completion:","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1registerForPushNotifications(with:completion:)\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1registerForPushNotifications(with:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"registerForPushNotificationsWith:completion:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1registerForPushNotifications()\/title","value":"registerForPushNotifications"},{"value":[{"kind":"text","text":"- "},{"text":"registerForPushNotifications","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1registerForPushNotifications()\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}