{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pushwoosh\/sendpurchase(_:withprice:currencycode:anddate:)"]},{"paths":["\/documentation\/pushwooshframework\/pushwoosh\/sendpurchase(_:withprice:currencycode:anddate:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh"]]},"sections":[],"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/sendPurchase(_:withPrice:currencyCode:andDate:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Tracks an individual in-app purchase."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sendPurchase","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"productIdentifier","kind":"internalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"withPrice","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"price"},{"text":": ","kind":"text"},{"text":"NSDecimalNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDecimalNumber"},{"kind":"text","text":", "},{"text":"currencyCode","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"andDate","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"date","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier","text":"Date"},{"kind":"text","text":")"}],"languages":["swift"]}]},{"kind":"content","content":[{"level":2,"text":"Discussion","anchor":"Discussion","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Manually reports a single in-app purchase to Pushwoosh for analytics and segmentation. For automatic tracking, use the recommended "},{"code":"sendSKPaymentTransactions:","type":"codeVoice"},{"type":"text","text":" method instead."}]},{"inlineContent":[{"text":"This method is useful when you need granular control over purchase tracking or are using a non-standard payment system.","type":"text"}],"type":"paragraph"},{"anchor":"Parameters","text":"Parameters","level":2,"type":"heading"},{"items":[{"content":[{"inlineContent":[{"type":"text","text":"productIdentifier: The purchased product ID"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"price: The price paid for the product","type":"text"}]}]},{"content":[{"inlineContent":[{"text":"currencyCode: The currency code (e.g., “USD”, “EUR”)","type":"text"}],"type":"paragraph"}]}],"type":"unorderedList"},{"type":"aside","style":"note","name":"Date","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The time of purchase"}]}]}]}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"externalID":"c:objc(cs)Pushwoosh(im)sendPurchase:withPrice:currencyCode:andDate:","symbolKind":"method","roleHeading":"Instance Method","modules":[{"name":"PushwooshFramework"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sendPurchase"},{"kind":"text","text":"("},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"withPrice","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSDecimalNumber","preciseIdentifier":"c:objc(cs)NSDecimalNumber"},{"kind":"text","text":", "},{"text":"currencyCode","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"andDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":")"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"sendPurchase:withPrice:currencyCode:andDate:"}],"title":"sendPurchase(_:withPrice:currencyCode:andDate:)"},"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Pushwoosh","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh","abstract":[{"type":"text","text":"Main SDK interface for push notification management."}],"navigatorTitle":[{"text":"Pushwoosh","kind":"identifier"}],"url":"\/documentation\/pushwooshframework\/pushwoosh","title":"Pushwoosh","type":"topic","role":"symbol"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/sendPurchase(_:withPrice:currencyCode:andDate:)":{"url":"\/documentation\/pushwooshframework\/pushwoosh\/sendpurchase(_:withprice:currencycode:anddate:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"sendPurchase","kind":"identifier"},{"kind":"text","text":"("},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"withPrice"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSDecimalNumber","text":"NSDecimalNumber","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"currencyCode"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"andDate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":")"}],"type":"topic","abstract":[{"type":"text","text":"Tracks an individual in-app purchase."}],"title":"sendPurchase(_:withPrice:currencyCode:andDate:)","navigatorTitle":[{"kind":"identifier","text":"sendPurchase:withPrice:currencyCode:andDate:"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/sendPurchase(_:withPrice:currencyCode:andDate:)","kind":"symbol","role":"symbol"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","type":"topic","kind":"symbol","abstract":[],"title":"PushwooshFramework","url":"\/documentation\/pushwooshframework"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"sendPurchase:withPrice:currencyCode:andDate:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"sendPurchase:withPrice:currencyCode:andDate:"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"sendPurchase:"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"productIdentifier","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"withPrice:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDecimalNumber","text":"NSDecimalNumber"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"price"},{"kind":"text","text":" "},{"kind":"identifier","text":"currencyCode:"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"currencyCode","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"andDate:"},{"kind":"text","text":"("},{"text":"NSDate","preciseIdentifier":"c:objc(cs)NSDate","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"date","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh\/title","value":"Pushwoosh","op":"replace"},{"value":[{"text":"Pushwoosh","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh\/fragments"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1sendPurchase(_:withPrice:currencyCode:andDate:)\/title","value":"sendPurchase:withPrice:currencyCode:andDate:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"sendPurchase:withPrice:currencyCode:andDate:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1sendPurchase(_:withPrice:currencyCode:andDate:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}