{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/sendSKPaymentTransactions(_:)"},"abstract":[{"type":"text","text":"Sends in-app purchase transactions to Pushwoosh."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pushwoosh\/sendskpaymenttransactions(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pushwoosh\/sendskpaymenttransactions(_:)"]}],"sections":[],"seeAlsoSections":[{"title":"Related Documentation","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/sendPurchase(_:withPrice:currencyCode:andDate:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWPurchaseDelegate"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sendSKPaymentTransactions"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"transactions"},{"kind":"text","text":": ["},{"text":"Any","kind":"keyword"},{"text":"])","kind":"text"}],"platforms":["iOS"]}]},{"kind":"content","content":[{"text":"Overview","level":2,"anchor":"Overview","type":"heading"},{"inlineContent":[{"type":"text","text":"Automatically tracks StoreKit purchases for:"}],"type":"paragraph"},{"items":[{"content":[{"inlineContent":[{"text":"Revenue analytics in Pushwoosh Control Panel","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Purchase-based user segmentation"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Conversion tracking"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"LTV (Lifetime Value) calculations"}]}]}],"type":"unorderedList"},{"type":"paragraph","inlineContent":[{"text":"This is the recommended method for tracking StoreKit purchases.","type":"text"}]},{"type":"heading","level":2,"text":"Example","anchor":"Example"},{"inlineContent":[{"type":"text","text":"Track purchases in payment queue observer:"}],"type":"paragraph"},{"code":["class StoreManager: NSObject, SKPaymentTransactionObserver {","","    func paymentQueue(_ queue: SKPaymentQueue, updatedTransactions transactions: [SKPaymentTransaction]) {","        Pushwoosh.configure.sendSKPaymentTransactions(transactions)","","        for transaction in transactions {","            switch transaction.transactionState {","            case .purchased:","                handlePurchase(transaction)","                queue.finishTransaction(transaction)","            case .failed:","                handleFailure(transaction)","                queue.finishTransaction(transaction)","            case .restored:","                handleRestore(transaction)","                queue.finishTransaction(transaction)","            default:","                break","            }","        }","    }","}"],"type":"codeListing","syntax":"swift"},{"type":"paragraph","inlineContent":[{"text":"Filter transactions before sending:","type":"text"}]},{"type":"codeListing","syntax":"swift","code":["func paymentQueue(_ queue: SKPaymentQueue, updatedTransactions transactions: [SKPaymentTransaction]) {","    let completedTransactions = transactions.filter {","        $0.transactionState == .purchased || $0.transactionState == .restored","    }","","    if !completedTransactions.isEmpty {","        Pushwoosh.configure.sendSKPaymentTransactions(completedTransactions)","    }","}"]}]}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh"]]},"metadata":{"externalID":"c:objc(cs)Pushwoosh(im)sendSKPaymentTransactions:","title":"sendSKPaymentTransactions(_:)","symbolKind":"method","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sendSKPaymentTransactions"},{"kind":"text","text":"(["},{"kind":"keyword","text":"Any"},{"text":"])","kind":"text"}],"navigatorTitle":[{"text":"sendSKPaymentTransactions:","kind":"identifier"}],"role":"symbol","modules":[{"name":"PushwooshFramework"}]},"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/sendSKPaymentTransactions(_:)":{"title":"sendSKPaymentTransactions(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"sendSKPaymentTransactions","kind":"identifier"},{"text":"([","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"])","kind":"text"}],"abstract":[{"type":"text","text":"Sends in-app purchase transactions to Pushwoosh."}],"role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/sendSKPaymentTransactions(_:)","type":"topic","url":"\/documentation\/pushwooshframework\/pushwoosh\/sendskpaymenttransactions(_:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"sendSKPaymentTransactions:"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/sendPurchase(_:withPrice:currencyCode:andDate:)":{"title":"sendPurchase(_:withPrice:currencyCode:andDate:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"sendPurchase","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"withPrice","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDecimalNumber","text":"NSDecimalNumber"},{"kind":"text","text":", "},{"kind":"externalParam","text":"currencyCode"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"andDate","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Tracks an individual in-app purchase."}],"role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/sendPurchase(_:withPrice:currencyCode:andDate:)","type":"topic","url":"\/documentation\/pushwooshframework\/pushwoosh\/sendpurchase(_:withprice:currencycode:anddate:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"sendPurchase:withPrice:currencyCode:andDate:"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","type":"topic","role":"collection","abstract":[{"text":"Push notification SDK for iOS applications.","type":"text"}],"title":"PushwooshFramework","url":"\/documentation\/pushwooshframework"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh":{"title":"Pushwoosh","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Pushwoosh"}],"abstract":[{"type":"text","text":"Main SDK interface for push notification management."}],"role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh","type":"topic","url":"\/documentation\/pushwooshframework\/pushwoosh","kind":"symbol","navigatorTitle":[{"text":"Pushwoosh","kind":"identifier"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWPurchaseDelegate":{"kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWPurchaseDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PWPurchaseDelegate","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"PWPurchaseDelegate","kind":"identifier"}],"url":"\/documentation\/pushwooshframework\/pwpurchasedelegate","role":"symbol","title":"PWPurchaseDelegate","abstract":[{"text":"Delegate protocol for handling in-app purchase events from rich media.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","value":"sendSKPaymentTransactions:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"sendSKPaymentTransactions:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"replace","path":"\/seeAlsoSections","value":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/sendPurchase(_:withPrice:currencyCode:andDate:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWPurchaseDelegate"],"title":"Related Documentation"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"sendSKPaymentTransactions:"},{"kind":"text","text":"("},{"text":"NSArray","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"transactions"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1sendSKPaymentTransactions(_:)\/title","value":"sendSKPaymentTransactions:"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1sendSKPaymentTransactions(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"sendSKPaymentTransactions:","kind":"identifier"}]},{"value":"sendPurchase:withPrice:currencyCode:andDate:","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1sendPurchase(_:withPrice:currencyCode:andDate:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1sendPurchase(_:withPrice:currencyCode:andDate:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sendPurchase:withPrice:currencyCode:andDate:"}]},{"value":"Pushwoosh","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh\/fragments","value":[{"text":"Pushwoosh","kind":"identifier"}]},{"value":"PWPurchaseDelegate","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWPurchaseDelegate\/title","op":"replace"},{"value":[{"kind":"identifier","text":"PWPurchaseDelegate"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWPurchaseDelegate\/fragments"}]}]}