{"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"title":"sendPush(toStartLiveActivityToken:)","platforms":[],"symbolKind":"method","modules":[{"name":"PushwooshFramework"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"sendPushToStartLiveActivityToken:"}],"roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sendPush"},{"kind":"text","text":"("},{"kind":"externalParam","text":"toStartLiveActivityToken"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?)","kind":"text"}],"externalID":"c:objc(cs)Pushwoosh(im)sendPushToStartLiveActivityToken:"},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Since 6.8.0: This method is deprecated and will be removed in a future release. Use Pushwoosh.LiveActivities.sendPushToStartLiveActivity(token: ) instead."}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/sendPush(toStartLiveActivityToken:)"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/pushwooshframework\/pushwoosh\/sendpush(tostartliveactivitytoken:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pushwooshframework\/pushwoosh\/sendpush(tostartliveactivitytoken:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"sendPush","kind":"identifier"},{"kind":"text","text":"("},{"text":"toStartLiveActivityToken","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"token"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?)","kind":"text"}]}],"kind":"declarations"},{"content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"inlineContent":[{"text":"Example:","type":"text"}],"type":"paragraph"},{"syntax":"swift","type":"codeListing","code":["if #available(iOS 17.2, *) {","    Task {","        for await data in Activity<LiveActivityAttributes>.pushToStartTokenUpdates {","            let token = data.map { String(format: \"%02x\", $0) }.joined()","            try? await Pushwoosh.LiveActivities.sendPushToStartLiveActivity(token: token)","        }","    }","}"]}],"kind":"content"}],"abstract":[{"text":"Sends push to start live activity token to the server.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Call this method when you want to initiate live activity via push notification"}],"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh":{"role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh","title":"Pushwoosh","abstract":[{"type":"text","text":"Main SDK interface for push notification management."}],"type":"topic","navigatorTitle":[{"text":"Pushwoosh","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/pushwooshframework\/pushwoosh","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Pushwoosh"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"kind":"symbol","role":"collection","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","title":"PushwooshFramework","abstract":[{"text":"Push notification SDK for iOS applications.","type":"text"}],"url":"\/documentation\/pushwooshframework","type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/sendPush(toStartLiveActivityToken:)":{"title":"sendPush(toStartLiveActivityToken:)","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/sendPush(toStartLiveActivityToken:)","abstract":[{"text":"Sends push to start live activity token to the server.","type":"text"},{"text":" ","type":"text"},{"text":"Call this method when you want to initiate live activity via push notification","type":"text"}],"deprecated":true,"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"sendPushToStartLiveActivityToken:"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sendPush","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"toStartLiveActivityToken"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"kind":"symbol","url":"\/documentation\/pushwooshframework\/pushwoosh\/sendpush(tostartliveactivitytoken:)"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"sendPushToStartLiveActivityToken:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"sendPushToStartLiveActivityToken:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"sendPushToStartLiveActivityToken:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"token"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh\/title","value":"Pushwoosh"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh\/fragments","value":[{"text":"Pushwoosh","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1sendPush(toStartLiveActivityToken:)\/title","op":"replace","value":"sendPushToStartLiveActivityToken:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"sendPushToStartLiveActivityToken:"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1sendPush(toStartLiveActivityToken:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}