{"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setEmails"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"emails","kind":"internalParam"},{"text":": [","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"], ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (((any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")? = nil)"}]}]},{"content":[{"type":"heading","anchor":"Overview","text":"Overview","level":2},{"inlineContent":[{"text":"Same as ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/setEmails(_:)","isActive":true},{"text":" but provides a completion callback to confirm the emails were successfully synchronized.","type":"text"}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Use this variant when you need to:"}]},{"items":[{"content":[{"inlineContent":[{"text":"Confirm emails were registered before proceeding","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Show user feedback about registration status"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Handle validation errors","type":"text"}]}]}],"type":"unorderedList"},{"text":"Example","anchor":"Example","type":"heading","level":2},{"inlineContent":[{"text":"Register emails with confirmation:","type":"text"}],"type":"paragraph"},{"type":"codeListing","code":["func saveUserEmails(_ emails: [String], completion: @escaping (Bool) -> Void) {","    Pushwoosh.configure.setEmails(emails) { error in","        if let error = error {","            Analytics.log(\"emails_registration_failed\", error: error)","            completion(false)","        } else {","            self.userDefaults.set(emails, forKey: \"registeredEmails\")","            completion(true)","        }","    }","}"],"syntax":"swift"},{"type":"paragraph","inlineContent":[{"text":"Import emails from account with feedback:","type":"text"}]},{"type":"codeListing","code":["func importAccountEmails() {","    let emails = accountService.verifiedEmails","","    Pushwoosh.configure.setEmails(emails) { error in","        DispatchQueue.main.async {","            if error == nil {","                self.showSuccess(\"Emails synced successfully\")","            } else {","                self.showError(\"Failed to sync emails\")","            }","        }","    }","}"],"syntax":"swift"}],"kind":"content"}],"variants":[{"paths":["\/documentation\/pushwooshframework\/pushwoosh\/setemails(_:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pushwoosh\/setemails(_:completion:)"]}],"sections":[],"seeAlsoSections":[{"title":"Related Documentation","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/setEmails(_:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/setEmail(_:completion:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/setEmails(_:completion:)"},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh"]]},"kind":"symbol","metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setEmails","kind":"identifier"},{"text":"([","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"], "},{"text":"completion","kind":"externalParam"},{"text":": (((any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":")?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")?)"}],"navigatorTitle":[{"text":"setEmails:completion:","kind":"identifier"}],"roleHeading":"Instance Method","title":"setEmails(_:completion:)","symbolKind":"method","modules":[{"name":"PushwooshFramework"}],"externalID":"c:objc(cs)Pushwoosh(im)setEmails:completion:","role":"symbol"},"abstract":[{"text":"Registers a list of email addresses with a completion handler.","type":"text"}],"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"abstract":[{"text":"Push notification SDK for iOS applications.","type":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","type":"topic","title":"PushwooshFramework","url":"\/documentation\/pushwooshframework","kind":"symbol","role":"collection"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/setEmails(_:completion:)":{"type":"topic","title":"setEmails(_:completion:)","abstract":[{"text":"Registers a list of email addresses with a completion handler.","type":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/setEmails(_:completion:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"setEmails:completion:"}],"role":"symbol","url":"\/documentation\/pushwooshframework\/pushwoosh\/setemails(_:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"setEmails","kind":"identifier"},{"text":"([","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (((any "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":")?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")?)","kind":"text"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh":{"type":"topic","title":"Pushwoosh","abstract":[{"type":"text","text":"Main SDK interface for push notification management."}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh","kind":"symbol","navigatorTitle":[{"text":"Pushwoosh","kind":"identifier"}],"role":"symbol","url":"\/documentation\/pushwooshframework\/pushwoosh","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Pushwoosh","kind":"identifier"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/setEmail(_:completion:)":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"setEmail:completion:","kind":"identifier"}],"url":"\/documentation\/pushwooshframework\/pushwoosh\/setemail(_:completion:)","type":"topic","abstract":[{"type":"text","text":"Associates an email address with the current device with a completion handler."}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setEmail"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (((any "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/setEmail(_:completion:)","title":"setEmail(_:completion:)"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/setEmails(_:)":{"type":"topic","title":"setEmails(_:)","abstract":[{"text":"Registers a list of email addresses associated with the current user.","type":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/setEmails(_:)","kind":"symbol","navigatorTitle":[{"text":"setEmails:","kind":"identifier"}],"role":"symbol","url":"\/documentation\/pushwooshframework\/pushwoosh\/setemails(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"setEmails","kind":"identifier"},{"text":"([","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"])"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"setEmails:completion:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"setEmails:completion:","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"replace","value":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/setEmails(_:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/setEmail(_:completion:)"],"title":"Related Documentation"}],"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"setEmails:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSArray","text":"NSArray"},{"text":" *) ","kind":"text"},{"text":"emails","kind":"internalParam"},{"kind":"text","text":" "},{"text":"completion:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":" (^","kind":"text"},{"text":")(","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * "},{"text":"error","kind":"internalParam"},{"kind":"text","text":")) "},{"kind":"internalParam","text":"completion"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace"},{"value":"setEmails:completion:","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1setEmails(_:completion:)\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1setEmails(_:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setEmails:completion:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh\/title","value":"Pushwoosh","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh\/fragments","value":[{"text":"Pushwoosh","kind":"identifier"}]},{"op":"replace","value":"setEmail:completion:","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1setEmail(_:completion:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1setEmail(_:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"setEmail:completion:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1setEmails(_:)\/title","op":"replace","value":"setEmails:"},{"value":[{"kind":"text","text":"- "},{"text":"setEmails:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1setEmails(_:)\/fragments"}]}]}