{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setEmail","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"email","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"level":2,"type":"heading","text":"Overview","anchor":"Overview"},{"inlineContent":[{"type":"text","text":"Register a user’s email to enable:"}],"type":"paragraph"},{"items":[{"content":[{"inlineContent":[{"type":"text","text":"Email channel campaigns in Pushwoosh"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Cross-channel messaging (push + email)","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"User identification by email address","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Email-based segmentation"}],"type":"paragraph"}]}],"type":"unorderedList"},{"level":2,"text":"Validation","anchor":"Validation","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The email must be:"}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"Non-empty string"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"Valid email format","type":"text"}],"type":"paragraph"}]}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Invalid emails will be rejected by the server."}]},{"type":"heading","text":"Example","level":2,"anchor":"Example"},{"inlineContent":[{"type":"text","text":"Set email during user registration:"}],"type":"paragraph"},{"type":"codeListing","code":["func completeRegistration(email: String, password: String) async throws {","    let user = try await authService.register(email: email, password: password)","","    Pushwoosh.configure.setUserId(user.id)","    Pushwoosh.configure.setEmail(email)","","    Pushwoosh.configure.setTags([","        \"registration_date\": Date(),","        \"registration_source\": \"ios_app\"","    ])","}"],"syntax":"swift"},{"inlineContent":[{"text":"Update email when user changes it in settings:","type":"text"}],"type":"paragraph"},{"code":["func updateEmail(newEmail: String) {","    Pushwoosh.configure.setEmail(newEmail)","","    Pushwoosh.configure.setTags([","        \"email_updated\": Date()","    ])","}"],"type":"codeListing","syntax":"swift"}],"kind":"content"}],"sections":[],"abstract":[{"text":"Associates an email address with the current device.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/setEmail(_:)"},"metadata":{"role":"symbol","title":"setEmail(_:)","modules":[{"name":"PushwooshFramework"}],"symbolKind":"method","externalID":"c:objc(cs)Pushwoosh(im)setEmail:","roleHeading":"Instance Method","navigatorTitle":[{"text":"setEmail:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setEmail"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pushwoosh\/setemail(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pushwoosh\/setemail(_:)"]}],"seeAlsoSections":[{"title":"Related Documentation","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/setEmail(_:completion:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/setEmails(_:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/setUserId(_:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/setTags(_:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/setEmail(_:completion:)":{"navigatorTitle":[{"text":"setEmail:completion:","kind":"identifier"}],"title":"setEmail(_:completion:)","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/setEmail(_:completion:)","abstract":[{"type":"text","text":"Associates an email address with the current device with a completion handler."}],"url":"\/documentation\/pushwooshframework\/pushwoosh\/setemail(_:completion:)","type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setEmail"},{"kind":"text","text":"("},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": (((any ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":")?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")?)","kind":"text"}],"kind":"symbol"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"kind":"symbol","role":"collection","abstract":[{"text":"Push notification SDK for iOS applications.","type":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","type":"topic","url":"\/documentation\/pushwooshframework","title":"PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/setTags(_:)":{"abstract":[{"text":"Sets user tags for device segmentation.","type":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/setTags(_:)","role":"symbol","url":"\/documentation\/pushwooshframework\/pushwoosh\/settags(_:)","navigatorTitle":[{"text":"setTags:","kind":"identifier"}],"type":"topic","title":"setTags(_:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setTags","kind":"identifier"},{"text":"([","kind":"text"},{"text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"text":"])","kind":"text"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh":{"navigatorTitle":[{"text":"Pushwoosh","kind":"identifier"}],"abstract":[{"text":"Main SDK interface for push notification management.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Pushwoosh","kind":"identifier"}],"url":"\/documentation\/pushwooshframework\/pushwoosh","role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh","title":"Pushwoosh","type":"topic","kind":"symbol"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/setUserId(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setUserId"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"title":"setUserId(_:)","abstract":[{"type":"text","text":"Associates a unique identifier with the current device."}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/setUserId(_:)","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"setUserId:"}],"type":"topic","url":"\/documentation\/pushwooshframework\/pushwoosh\/setuserid(_:)"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/setEmails(_:)":{"navigatorTitle":[{"kind":"identifier","text":"setEmails:"}],"title":"setEmails(_:)","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/setEmails(_:)","abstract":[{"type":"text","text":"Registers a list of email addresses associated with the current user."}],"url":"\/documentation\/pushwooshframework\/pushwoosh\/setemails(_:)","type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setEmails"},{"kind":"text","text":"(["},{"text":"Any","kind":"keyword"},{"text":"])","kind":"text"}],"kind":"symbol"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/setEmail(_:)":{"navigatorTitle":[{"kind":"identifier","text":"setEmail:"}],"abstract":[{"type":"text","text":"Associates an email address with the current device."}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setEmail"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}],"url":"\/documentation\/pushwooshframework\/pushwoosh\/setemail(_:)","role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/setEmail(_:)","kind":"symbol","title":"setEmail(_:)","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"setEmail:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setEmail:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"replace","value":[{"title":"Related Documentation","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/setEmail(_:completion:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/setEmails(_:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/setUserId(_:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/setTags(_:)"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"setEmail:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"email"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"setEmail:completion:","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1setEmail(_:completion:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1setEmail(_:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"setEmail:completion:","kind":"identifier"}]},{"value":"setTags:","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1setTags(_:)\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1setTags(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setTags:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh\/title","value":"Pushwoosh"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh\/fragments","value":[{"text":"Pushwoosh","kind":"identifier"}]},{"value":"setUserId:","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1setUserId(_:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"setUserId:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1setUserId(_:)\/fragments"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1setEmails(_:)\/title","op":"replace","value":"setEmails:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"setEmails:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1setEmails(_:)\/fragments"},{"op":"replace","value":"setEmail:","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1setEmail(_:)\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1setEmail(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"setEmail:","kind":"identifier"}],"op":"replace"}]}]}