{"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setEmailTags"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"tags"},{"kind":"text","text":": ["},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"], "},{"text":"forEmail","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"email","kind":"internalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Dictionary of tag names and values"}],"type":"paragraph"}],"name":"tags"},{"content":[{"inlineContent":[{"type":"text","text":"The email address to associate tags with"}],"type":"paragraph"}],"name":"email"}]}],"metadata":{"title":"setEmailTags(_:forEmail:)","symbolKind":"method","navigatorTitle":[{"text":"setEmailTags:forEmail:","kind":"identifier"}],"externalID":"c:objc(cs)Pushwoosh(im)setEmailTags:forEmail:","role":"symbol","roleHeading":"Instance Method","modules":[{"name":"PushwooshFramework"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setEmailTags","kind":"identifier"},{"text":"([","kind":"text"},{"text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"text":"], ","kind":"text"},{"text":"forEmail","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}]},"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/setEmailTags(_:forEmail:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Sets tags for a specific email address."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pushwoosh\/setemailtags(_:foremail:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pushwoosh\/setemailtags(_:foremail:)"]}],"kind":"symbol","sections":[],"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"title":"PushwooshFramework","url":"\/documentation\/pushwooshframework","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","abstract":[{"text":"Push notification SDK for iOS applications.","type":"text"}],"type":"topic","role":"collection"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh":{"navigatorTitle":[{"kind":"identifier","text":"Pushwoosh"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh","type":"topic","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Main SDK interface for push notification management."}],"url":"\/documentation\/pushwooshframework\/pushwoosh","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Pushwoosh","kind":"identifier"}],"title":"Pushwoosh"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/setEmailTags(_:forEmail:)":{"title":"setEmailTags(_:forEmail:)","url":"\/documentation\/pushwooshframework\/pushwoosh\/setemailtags(_:foremail:)","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/setEmailTags(_:forEmail:)","type":"topic","abstract":[{"type":"text","text":"Sets tags for a specific email address."}],"kind":"symbol","navigatorTitle":[{"text":"setEmailTags:forEmail:","kind":"identifier"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setEmailTags","kind":"identifier"},{"text":"([","kind":"text"},{"text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"], ","kind":"text"},{"text":"forEmail","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"setEmailTags:forEmail:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"setEmailTags:forEmail:","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"setEmailTags:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSDictionary","text":"NSDictionary","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"tags","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"forEmail:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"email","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":"Pushwoosh","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh\/fragments","value":[{"kind":"identifier","text":"Pushwoosh"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1setEmailTags(_:forEmail:)\/title","value":"setEmailTags:forEmail:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setEmailTags:forEmail:"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1setEmailTags(_:forEmail:)\/fragments","op":"replace"}]}]}