{"metadata":{"roleHeading":"Instance Method","modules":[{"name":"PushwooshFramework"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setEmails","kind":"identifier"},{"text":"([","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"])"}],"externalID":"c:objc(cs)Pushwoosh(im)setEmails:","title":"setEmails(_:)","role":"symbol","symbolKind":"method","navigatorTitle":[{"text":"setEmails:","kind":"identifier"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/setEmails(_:)"},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"paths":["\/documentation\/pushwooshframework\/pushwoosh\/setemails(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pushwoosh\/setemails(_:)"]}],"seeAlsoSections":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/setEmails(_:completion:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/setEmail(_:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/setUserId(_:)"],"title":"Related Documentation"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setEmails"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"emails","kind":"internalParam"},{"kind":"text","text":": ["},{"text":"Any","kind":"keyword"},{"text":"])","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"anchor":"Overview","type":"heading","level":2,"text":"Overview"},{"inlineContent":[{"type":"text","text":"Associates multiple email addresses with the device. Use this when:"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"User has multiple email addresses (personal + work)","type":"text"}]}]},{"content":[{"inlineContent":[{"text":"Migrating from another system with multiple emails","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Supporting family\/shared accounts"}]}]}]},{"type":"paragraph","inlineContent":[{"text":"All emails receive campaigns targeted at this user.","type":"text"}]},{"text":"Example","level":2,"anchor":"Example","type":"heading"},{"inlineContent":[{"type":"text","text":"Register multiple user emails:"}],"type":"paragraph"},{"type":"codeListing","syntax":"swift","code":["func syncUserEmails(_ user: User) {","    var emails = [user.primaryEmail]","","    if let workEmail = user.workEmail {","        emails.append(workEmail)","    }","","    if let secondaryEmail = user.secondaryEmail {","        emails.append(secondaryEmail)","    }","","    Pushwoosh.configure.setEmails(emails)","}"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Import emails from account settings:"}]},{"syntax":"swift","type":"codeListing","code":["func importEmailsFromSettings() {","    let emails = accountSettings.verifiedEmails","","    guard !emails.isEmpty else { return }","","    Pushwoosh.configure.setEmails(emails)","}"]}],"kind":"content"}],"sections":[],"kind":"symbol","abstract":[{"text":"Registers a list of email addresses associated with the current user.","type":"text"}],"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/setEmails(_:)":{"url":"\/documentation\/pushwooshframework\/pushwoosh\/setemails(_:)","navigatorTitle":[{"text":"setEmails:","kind":"identifier"}],"abstract":[{"type":"text","text":"Registers a list of email addresses associated with the current user."}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/setEmails(_:)","type":"topic","title":"setEmails(_:)","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setEmails"},{"kind":"text","text":"(["},{"text":"Any","kind":"keyword"},{"kind":"text","text":"])"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/setEmails(_:completion:)":{"type":"topic","url":"\/documentation\/pushwooshframework\/pushwoosh\/setemails(_:completion:)","abstract":[{"type":"text","text":"Registers a list of email addresses with a completion handler."}],"title":"setEmails(_:completion:)","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/setEmails(_:completion:)","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setEmails","kind":"identifier"},{"text":"([","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"completion"},{"text":": (((any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":")?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")?)"}],"navigatorTitle":[{"text":"setEmails:completion:","kind":"identifier"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/setUserId(_:)":{"kind":"symbol","title":"setUserId(_:)","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/setUserId(_:)","url":"\/documentation\/pushwooshframework\/pushwoosh\/setuserid(_:)","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Associates a unique identifier with the current device."}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setUserId","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"setUserId:"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"type":"topic","role":"collection","kind":"symbol","abstract":[{"text":"Push notification SDK for iOS applications.","type":"text"}],"url":"\/documentation\/pushwooshframework","title":"PushwooshFramework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh","title":"Pushwoosh","url":"\/documentation\/pushwooshframework\/pushwoosh","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Pushwoosh","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Pushwoosh"}],"abstract":[{"text":"Main SDK interface for push notification management.","type":"text"}],"kind":"symbol"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/setEmail(_:)":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/setEmail(_:)","navigatorTitle":[{"kind":"identifier","text":"setEmail:"}],"title":"setEmail(_:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setEmail","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":")"}],"url":"\/documentation\/pushwooshframework\/pushwoosh\/setemail(_:)","role":"symbol","abstract":[{"type":"text","text":"Associates an email address with the current device."}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"setEmails:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"setEmails:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Related Documentation","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/setEmails(_:completion:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/setEmail(_:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/setUserId(_:)"]}]},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"text":"setEmails:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"emails"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1setEmails(_:)\/title","value":"setEmails:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1setEmails(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setEmails:"}]},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1setEmails(_:completion:)\/title","op":"replace","value":"setEmails:completion:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setEmails:completion:"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1setEmails(_:completion:)\/fragments"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1setUserId(_:)\/title","op":"replace","value":"setUserId:"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1setUserId(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"setUserId:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh\/title","value":"Pushwoosh"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh\/fragments","value":[{"text":"Pushwoosh","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1setEmail(_:)\/title","value":"setEmail:"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1setEmail(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"setEmail:","kind":"identifier"}]}]}]}