{"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pushwoosh\/setreverseproxy(_:)"]},{"paths":["\/documentation\/pushwooshframework\/pushwoosh\/setreverseproxy(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/setReverseProxy(_:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"deprecationSummary":[{"inlineContent":[{"type":"text","text":"Use Pushwoosh.configure.setReverseProxy(_:headers:) instead"}],"type":"paragraph"}],"sections":[],"kind":"symbol","abstract":[{"text":"Change default base url to reverse proxy url","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setReverseProxy"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"url","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"languages":["swift"]}]},{"parameters":[{"name":"url","content":[{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"reverse proxy url"}]}]}],"type":"unorderedList"}]}],"kind":"parameters"}],"metadata":{"roleHeading":"Instance Method","platforms":[],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setReverseProxy"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}],"title":"setReverseProxy(_:)","navigatorTitle":[{"kind":"identifier","text":"setReverseProxy:"}],"role":"symbol","modules":[{"name":"PushwooshFramework"}],"symbolKind":"method","externalID":"c:objc(cs)Pushwoosh(im)setReverseProxy:"},"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh":{"navigatorTitle":[{"kind":"identifier","text":"Pushwoosh"}],"abstract":[{"type":"text","text":"Main SDK interface for push notification management."}],"url":"\/documentation\/pushwooshframework\/pushwoosh","title":"Pushwoosh","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Pushwoosh","kind":"identifier"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/setReverseProxy(_:)":{"title":"setReverseProxy(_:)","kind":"symbol","url":"\/documentation\/pushwooshframework\/pushwoosh\/setreverseproxy(_:)","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/setReverseProxy(_:)","role":"symbol","navigatorTitle":[{"text":"setReverseProxy:","kind":"identifier"}],"abstract":[{"text":"Change default base url to reverse proxy url","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setReverseProxy"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"deprecated":true,"type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"type":"topic","abstract":[{"text":"Push notification SDK for iOS applications.","type":"text"}],"title":"PushwooshFramework","kind":"symbol","url":"\/documentation\/pushwooshframework","role":"collection","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"setReverseProxy:","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"setReverseProxy:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"setReverseProxy:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"url"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh\/title","value":"Pushwoosh","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"Pushwoosh"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh\/fragments"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1setReverseProxy(_:)\/title","op":"replace","value":"setReverseProxy:"},{"value":[{"text":"- ","kind":"text"},{"text":"setReverseProxy:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1setReverseProxy(_:)\/fragments"}]}]}