{"kind":"symbol","sections":[],"seeAlsoSections":[{"title":"Related Documentation","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/setTags(_:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/getTags(_:onFailure:)"]}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh"]]},"variants":[{"paths":["\/documentation\/pushwooshframework\/pushwoosh\/settags(_:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pushwooshframework\/pushwoosh\/settags(_:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"setTags(_:completion:)","externalID":"c:objc(cs)Pushwoosh(im)setTags:completion:","roleHeading":"Instance Method","modules":[{"name":"PushwooshFramework"}],"role":"symbol","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"setTags:completion:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setTags"},{"kind":"text","text":"(["},{"preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier","text":"AnyHashable"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (((any "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")?)","kind":"text"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/setTags(_:completion:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setTags","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"tags"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"], ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (((any "},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"kind":"text","text":")?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")? = nil)"}]}]},{"kind":"content","content":[{"text":"Overview","level":2,"type":"heading","anchor":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Same as "},{"type":"reference","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/setTags(_:)","isActive":true},{"text":" but provides a completion callback to confirm the tags were successfully synchronized with Pushwoosh servers.","type":"text"}]},{"inlineContent":[{"type":"text","text":"Use this variant when you need to:"}],"type":"paragraph"},{"items":[{"content":[{"inlineContent":[{"text":"Confirm tags were set before proceeding","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Handle tag synchronization errors"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Show user feedback about preference updates"}]}]}],"type":"unorderedList"},{"type":"heading","level":2,"text":"Example","anchor":"Example"},{"inlineContent":[{"type":"text","text":"Update user preferences with confirmation:"}],"type":"paragraph"},{"type":"codeListing","syntax":"swift","code":["func saveNotificationPreferences(_ preferences: NotificationPreferences) {","    let tags: [String: Any] = [","        \"notify_orders\": preferences.orderUpdates,","        \"notify_promotions\": preferences.promotionalOffers,","        \"notify_news\": preferences.newsAndUpdates","    ]","","    Pushwoosh.configure.setTags(tags) { error in","        DispatchQueue.main.async {","            if let error = error {","                self.showAlert(\"Failed to save preferences: \\(error.localizedDescription)\")","            } else {","                self.showToast(\"Preferences saved\")","            }","        }","    }","}"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Track subscription upgrade with analytics:"}]},{"syntax":"swift","type":"codeListing","code":["func handleSubscriptionUpgrade(to tier: SubscriptionTier) {","    let tags: [String: Any] = [","        \"subscription_tier\": tier.rawValue,","        \"subscription_updated\": Date(),","        \"isPremium\": tier != .free","    ]","","    Pushwoosh.configure.setTags(tags) { error in","        if error == nil {","            Analytics.log(\"subscription_synced_to_pushwoosh\", [","                \"tier\": tier.rawValue","            ])","        }","    }","}"]}]}],"abstract":[{"type":"text","text":"Sets user tags with a completion handler."}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/setTags(_:)":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/setTags(_:)","abstract":[{"type":"text","text":"Sets user tags for device segmentation."}],"navigatorTitle":[{"kind":"identifier","text":"setTags:"}],"type":"topic","kind":"symbol","title":"setTags(_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setTags"},{"text":"([","kind":"text"},{"text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"])","kind":"text"}],"url":"\/documentation\/pushwooshframework\/pushwoosh\/settags(_:)"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"title":"PushwooshFramework","kind":"symbol","abstract":[{"text":"Push notification SDK for iOS applications.","type":"text"}],"role":"collection","type":"topic","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/getTags(_:onFailure:)":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/getTags(_:onFailure:)","title":"getTags(_:onFailure:)","role":"symbol","url":"\/documentation\/pushwooshframework\/pushwoosh\/gettags(_:onfailure:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"getTags","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:PushNotificationManager.h@T@PushwooshGetTagsHandler","text":"PushwooshGetTagsHandler"},{"kind":"text","text":"?, "},{"text":"onFailure","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PushwooshErrorHandler","kind":"typeIdentifier","preciseIdentifier":"c:PushNotificationManager.h@T@PushwooshErrorHandler"},{"text":"?)","kind":"text"}],"kind":"symbol","abstract":[{"type":"text","text":"Retrieves the current device’s tags from the Pushwoosh server."}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"getTags:onFailure:"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/setTags(_:completion:)":{"title":"setTags(_:completion:)","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/setTags(_:completion:)","role":"symbol","url":"\/documentation\/pushwooshframework\/pushwoosh\/settags(_:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setTags"},{"text":"([","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"], ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (((any "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":")?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"kind":"symbol","abstract":[{"type":"text","text":"Sets user tags with a completion handler."}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"setTags:completion:"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh":{"url":"\/documentation\/pushwooshframework\/pushwoosh","abstract":[{"type":"text","text":"Main SDK interface for push notification management."}],"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Pushwoosh"}],"title":"Pushwoosh","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Pushwoosh","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"setTags:completion:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setTags:completion:"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/setTags(_:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/getTags(_:onFailure:)"],"title":"Related Documentation"}],"op":"replace","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"text":"setTags:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSDictionary","text":"NSDictionary","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"tags"},{"kind":"text","text":" "},{"text":"completion:","kind":"identifier"},{"kind":"text","text":"("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":" (^"},{"text":")(","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * "},{"text":"error","kind":"internalParam"},{"text":")) ","kind":"text"},{"text":"completion","kind":"internalParam"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1setTags(_:)\/title","value":"setTags:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setTags:"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1setTags(_:)\/fragments"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1getTags(_:onFailure:)\/title","value":"getTags:onFailure:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1getTags(_:onFailure:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"getTags:onFailure:","kind":"identifier"}]},{"value":"setTags:completion:","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1setTags(_:completion:)\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1setTags(_:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setTags:completion:"}],"op":"replace"},{"value":"Pushwoosh","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh\/title"},{"op":"replace","value":[{"text":"Pushwoosh","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh\/fragments"}]}]}