{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setTags"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"tags","kind":"internalParam"},{"text":": [","kind":"text"},{"text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"])"}],"languages":["swift"]}]},{"kind":"content","content":[{"anchor":"Overview","level":2,"text":"Overview","type":"heading"},{"inlineContent":[{"text":"Tags are key-value pairs that enable targeted push notifications based on user attributes and behavior. Use tags to:","type":"text"}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Segment users for targeted campaigns"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Personalize notification content"}]}]},{"content":[{"inlineContent":[{"text":"Track user preferences and behavior","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A\/B test notification strategies"}]}]}],"type":"unorderedList"},{"type":"heading","anchor":"Supported-Tag-Types","level":2,"text":"Supported Tag Types"},{"header":"row","type":"table","rows":[[[{"type":"paragraph","inlineContent":[{"type":"text","text":"Type"}]}],[{"type":"paragraph","inlineContent":[{"text":"Swift Type","type":"text"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"Example"}]}]],[[{"type":"paragraph","inlineContent":[{"text":"String","type":"text"}]}],[{"type":"paragraph","inlineContent":[{"code":"String","type":"codeVoice"}]}],[{"type":"paragraph","inlineContent":[{"code":"\"city\": \"New York\"","type":"codeVoice"}]}]],[[{"type":"paragraph","inlineContent":[{"type":"text","text":"Integer"}]}],[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"Int"}]}],[{"inlineContent":[{"type":"codeVoice","code":"\"age\": 25"}],"type":"paragraph"}]],[[{"type":"paragraph","inlineContent":[{"type":"text","text":"Boolean"}]}],[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"Bool"}]}],[{"type":"paragraph","inlineContent":[{"code":"\"isPremium\": true","type":"codeVoice"}]}]],[[{"inlineContent":[{"type":"text","text":"List"}],"type":"paragraph"}],[{"inlineContent":[{"code":"[String]","type":"codeVoice"}],"type":"paragraph"}],[{"inlineContent":[{"code":"\"interests\": [\"sports\", \"tech\"]","type":"codeVoice"}],"type":"paragraph"}]],[[{"type":"paragraph","inlineContent":[{"text":"Date","type":"text"}]}],[{"type":"paragraph","inlineContent":[{"code":"Date","type":"codeVoice"}]}],[{"inlineContent":[{"code":"\"lastPurchase\": Date()","type":"codeVoice"}],"type":"paragraph"}]],[[{"inlineContent":[{"type":"text","text":"Incremental"}],"type":"paragraph"}],[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"PWTagsBuilder"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"See example below"}]}]]]},{"text":"Important","type":"heading","anchor":"Important","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Tag names must be created in the Pushwoosh Control Panel before use. Sending unknown tag names will result in the tag being ignored."}]},{"level":2,"type":"heading","anchor":"Example","text":"Example"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Track user profile and preferences:"}]},{"syntax":"swift","code":["func updateUserProfile(_ profile: UserProfile) {","    let tags: [String: Any] = [","        \"username\": profile.username,","        \"age\": profile.age,","        \"city\": profile.city,","        \"isPremium\": profile.hasActiveSubscription,","        \"interests\": profile.interests,","        \"lastActive\": Date()","    ]","","    Pushwoosh.configure.setTags(tags)","}"],"type":"codeListing"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Track e-commerce behavior:"}]},{"type":"codeListing","syntax":"swift","code":["func trackPurchase(order: Order) {","    let tags: [String: Any] = [","        \"lastPurchaseDate\": Date(),","        \"lastPurchaseAmount\": order.total,","        \"purchaseCount\": PWTagsBuilder.incrementalTag(withInteger: 1),","        \"totalSpent\": PWTagsBuilder.incrementalTag(withInteger: Int(order.total)),","        \"purchasedCategories\": PWTagsBuilder.appendValues(toListTag: order.categoryNames)","    ]","","    Pushwoosh.configure.setTags(tags)","}"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Track app engagement:"}]},{"code":["func trackFeatureUsage(feature: String) {","    Pushwoosh.configure.setTags([","        \"last_used_feature\": feature,","        \"feature_\\(feature)_count\": PWTagsBuilder.incrementalTag(withInteger: 1)","    ])","}"],"type":"codeListing","syntax":"swift"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/setTags(_:)"},"metadata":{"title":"setTags(_:)","role":"symbol","externalID":"c:objc(cs)Pushwoosh(im)setTags:","navigatorTitle":[{"text":"setTags:","kind":"identifier"}],"roleHeading":"Instance Method","modules":[{"name":"PushwooshFramework"}],"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setTags","kind":"identifier"},{"text":"([","kind":"text"},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"text":"])","kind":"text"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pushwoosh\/settags(_:)"]},{"paths":["\/documentation\/pushwooshframework\/pushwoosh\/settags(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Sets user tags for device segmentation.","type":"text"}],"kind":"symbol","seeAlsoSections":[{"title":"Related Documentation","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/setTags(_:completion:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/getTags(_:onFailure:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWTagsBuilder"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/getTags(_:onFailure:)":{"abstract":[{"text":"Retrieves the current device’s tags from the Pushwoosh server.","type":"text"}],"title":"getTags(_:onFailure:)","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/getTags(_:onFailure:)","role":"symbol","url":"\/documentation\/pushwooshframework\/pushwoosh\/gettags(_:onfailure:)","navigatorTitle":[{"text":"getTags:onFailure:","kind":"identifier"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getTags"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:PushNotificationManager.h@T@PushwooshGetTagsHandler","text":"PushwooshGetTagsHandler"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"onFailure"},{"text":": ","kind":"text"},{"text":"PushwooshErrorHandler","kind":"typeIdentifier","preciseIdentifier":"c:PushNotificationManager.h@T@PushwooshErrorHandler"},{"kind":"text","text":"?)"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Pushwoosh","kind":"identifier"}],"url":"\/documentation\/pushwooshframework\/pushwoosh","type":"topic","kind":"symbol","title":"Pushwoosh","role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh","navigatorTitle":[{"text":"Pushwoosh","kind":"identifier"}],"abstract":[{"text":"Main SDK interface for push notification management.","type":"text"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/setTags(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setTags","kind":"identifier"},{"kind":"text","text":"(["},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"text":"])","kind":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/setTags(_:)","role":"symbol","type":"topic","navigatorTitle":[{"text":"setTags:","kind":"identifier"}],"title":"setTags(_:)","url":"\/documentation\/pushwooshframework\/pushwoosh\/settags(_:)","kind":"symbol","abstract":[{"text":"Sets user tags for device segmentation.","type":"text"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/setTags(_:completion:)":{"kind":"symbol","title":"setTags(_:completion:)","abstract":[{"type":"text","text":"Sets user tags with a completion handler."}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/setTags(_:completion:)","role":"symbol","url":"\/documentation\/pushwooshframework\/pushwoosh\/settags(_:completion:)","navigatorTitle":[{"text":"setTags:completion:","kind":"identifier"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setTags"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"], ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (((any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"url":"\/documentation\/pushwooshframework","type":"topic","abstract":[{"text":"Push notification SDK for iOS applications.","type":"text"}],"title":"PushwooshFramework","kind":"symbol","role":"collection","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWTagsBuilder":{"kind":"symbol","url":"\/documentation\/pushwooshframework\/pwtagsbuilder","navigatorTitle":[{"kind":"identifier","text":"PWTagsBuilder"}],"role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWTagsBuilder","abstract":[{"type":"codeVoice","code":"PWTagsBuilder"},{"type":"text","text":" class encapsulates the methods for creating tags parameters for sending them to the server."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PWTagsBuilder"}],"title":"PWTagsBuilder","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"setTags:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"setTags:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/setTags(_:completion:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/getTags(_:onFailure:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWTagsBuilder"],"title":"Related Documentation"}],"op":"replace","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"setTags:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSDictionary","text":"NSDictionary","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"tags","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1getTags(_:onFailure:)\/title","value":"getTags:onFailure:"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1getTags(_:onFailure:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"getTags:onFailure:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh\/title","value":"Pushwoosh","op":"replace"},{"value":[{"text":"Pushwoosh","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh\/fragments"},{"op":"replace","value":"setTags:","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1setTags(_:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"setTags:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1setTags(_:)\/fragments","op":"replace"},{"op":"replace","value":"setTags:completion:","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1setTags(_:completion:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setTags:completion:"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1setTags(_:completion:)\/fragments"},{"value":"PWTagsBuilder","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWTagsBuilder\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWTagsBuilder\/fragments","value":[{"kind":"identifier","text":"PWTagsBuilder"}],"op":"replace"}]}]}