{"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"role":"symbol","title":"sharedInstance()","modules":[{"name":"PushwooshFramework"}],"navigatorTitle":[{"text":"sharedInstance","kind":"identifier"}],"roleHeading":"Type Method","externalID":"c:objc(cs)Pushwoosh(cm)sharedInstance","symbolKind":"method","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"sharedInstance","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"Self","kind":"typeIdentifier"}]},"kind":"symbol","abstract":[{"text":"Returns the shared Pushwoosh SDK instance.","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"sharedInstance","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Self","kind":"typeIdentifier"}]}],"kind":"declarations"},{"content":[{"level":2,"anchor":"Overview","type":"heading","text":"Overview"},{"inlineContent":[{"type":"text","text":"Returns the singleton Pushwoosh instance. This is an alternative way to access SDK functionality."}],"type":"paragraph"},{"text":"Recommended Usage","anchor":"Recommended-Usage","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"text":"For cleaner code, prefer using ","type":"text"},{"code":"configure","type":"codeVoice"},{"text":" which provides the same functionality:","type":"text"}]},{"syntax":"swift","type":"codeListing","code":["\/\/ Recommended","Pushwoosh.configure.registerForPushNotifications()","Pushwoosh.configure.setTags([\"key\": \"value\"])","","\/\/ Alternative (same functionality)","Pushwoosh.sharedInstance().registerForPushNotifications()","Pushwoosh.sharedInstance().setTags([\"key\": \"value\"])"]},{"level":2,"type":"heading","anchor":"Prerequisites","text":"Prerequisites"},{"inlineContent":[{"type":"text","text":"The SDK must be initialized via Info.plist with key "},{"type":"codeVoice","code":"Pushwoosh_APPID"},{"type":"text","text":" before accessing."}],"type":"paragraph"},{"type":"heading","text":"Example","anchor":"Example","level":2},{"inlineContent":[{"text":"Access SDK instance:","type":"text"}],"type":"paragraph"},{"code":["let pushwoosh = Pushwoosh.sharedInstance()","let hwid = pushwoosh.getHWID()","let token = pushwoosh.getPushToken()"],"syntax":"swift","type":"codeListing"}],"kind":"content"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/sharedInstance()"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pushwoosh\/sharedinstance()"]},{"paths":["\/documentation\/pushwooshframework\/pushwoosh\/sharedinstance()"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh"]]},"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/sharedInstance()":{"type":"topic","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"sharedInstance","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Self","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"sharedInstance","kind":"identifier"}],"abstract":[{"text":"Returns the shared Pushwoosh SDK instance.","type":"text"}],"title":"sharedInstance()","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/sharedInstance()","url":"\/documentation\/pushwooshframework\/pushwoosh\/sharedinstance()"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"title":"PushwooshFramework","kind":"symbol","abstract":[{"text":"Push notification SDK for iOS applications.","type":"text"}],"role":"collection","type":"topic","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh":{"url":"\/documentation\/pushwooshframework\/pushwoosh","abstract":[{"type":"text","text":"Main SDK interface for push notification management."}],"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Pushwoosh"}],"title":"Pushwoosh","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Pushwoosh","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"sharedInstance"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"text":"sharedInstance","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"sharedInstance"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1sharedInstance()\/title","value":"sharedInstance","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1sharedInstance()\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"sharedInstance"}]},{"value":"Pushwoosh","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh\/fragments","value":[{"text":"Pushwoosh","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}