{"abstract":[{"text":"Controls whether push notification alerts are shown when the app is running in the foreground.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh"]]},"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/showPushnotificationAlert","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/pushwooshframework\/pushwoosh\/showpushnotificationalert"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pushwooshframework\/pushwoosh\/showpushnotificationalert"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"showPushnotificationAlert","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]},{"content":[{"level":2,"type":"heading","anchor":"Discussion","text":"Discussion"},{"inlineContent":[{"type":"text","text":"When set to "},{"type":"codeVoice","code":"true"},{"type":"text","text":" (default), push notifications received while the app is in the foreground will display an alert to the user. When set to "},{"code":"false","type":"codeVoice"},{"text":", notifications are delivered silently to your delegate methods without showing an alert.","type":"text"}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"text":"Set this property to ","type":"text"},{"code":"false","type":"codeVoice"},{"text":" if you want to handle foreground notifications with custom UI instead of the system alert.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"Default value is ","type":"text"},{"type":"codeVoice","code":"true"},{"text":".","type":"text"}]}],"kind":"content"}],"metadata":{"roleHeading":"Instance Property","modules":[{"name":"PushwooshFramework"}],"symbolKind":"property","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"showPushnotificationAlert","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"showPushnotificationAlert","kind":"identifier"}],"title":"showPushnotificationAlert","externalID":"c:objc(cs)Pushwoosh(py)showPushnotificationAlert"},"sections":[],"kind":"symbol","references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh","type":"topic","kind":"symbol","url":"\/documentation\/pushwooshframework\/pushwoosh","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Pushwoosh"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Pushwoosh"}],"title":"Pushwoosh","abstract":[{"type":"text","text":"Main SDK interface for push notification management."}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/showPushnotificationAlert":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"showPushnotificationAlert","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/showPushnotificationAlert","navigatorTitle":[{"text":"showPushnotificationAlert","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Controls whether push notification alerts are shown when the app is running in the foreground."}],"url":"\/documentation\/pushwooshframework\/pushwoosh\/showpushnotificationalert","type":"topic","title":"showPushnotificationAlert","kind":"symbol"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"abstract":[],"url":"\/documentation\/pushwooshframework","role":"collection","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","title":"PushwooshFramework","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"showPushnotificationAlert","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"showPushnotificationAlert"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"assign","kind":"keyword"},{"text":") ","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"showPushnotificationAlert"},{"text":";","kind":"text"}]}]},"op":"replace"},{"value":"Pushwoosh","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh\/fragments","value":[{"text":"Pushwoosh","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1showPushnotificationAlert\/title","value":"showPushnotificationAlert"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1showPushnotificationAlert\/fragments","value":[{"text":"showPushnotificationAlert","kind":"identifier"}],"op":"replace"}]}]}