{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"startLiveActivity","kind":"identifier"},{"kind":"text","text":"("},{"text":"withToken","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"token"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"activityId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": (((any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")? = nil)","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"content","content":[{"anchor":"Discussion","text":"Discussion","level":2,"type":"heading"},{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"text":"Deprecated since 6.8.0","type":"text"}]},{"type":"text","text":": Use "},{"code":"Pushwoosh.LiveActivities.startLiveActivity(token:activityId:completion:)","type":"codeVoice"},{"text":" instead.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"Similar to ","type":"text"},{"type":"codeVoice","code":"startLiveActivityWithToken:activityId:"},{"type":"text","text":" but provides a callback when the operation completes."}]},{"type":"heading","text":"Parameters","anchor":"Parameters","level":2},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"token: The live activity token"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"activityId: Activity ID for updating Live Activities by segments (optional)"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"completion: Block called when the operation completes. Receives nil on success or an NSError on failure."}],"type":"paragraph"}]}],"type":"unorderedList"}]}],"variants":[{"paths":["\/documentation\/pushwooshframework\/pushwoosh\/startliveactivity(withtoken:activityid:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pushwooshframework\/pushwoosh\/startliveactivity(withtoken:activityid:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh"]]},"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"Sends live activity token to the server with a completion handler."}],"metadata":{"externalID":"c:objc(cs)Pushwoosh(im)startLiveActivityWithToken:activityId:completion:","role":"symbol","modules":[{"name":"PushwooshFramework"}],"platforms":[],"title":"startLiveActivity(withToken:activityId:completion:)","navigatorTitle":[{"text":"startLiveActivityWithToken:activityId:completion:","kind":"identifier"}],"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startLiveActivity","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withToken","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"activityId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (((any "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")?)","kind":"text"}],"symbolKind":"method"},"deprecationSummary":[{"inlineContent":[{"type":"text","text":"Since 6.8.0: This method is deprecated and will be removed in a future release. Use startLiveActivity(token: , activityId: , completion: ) instead."}],"type":"paragraph"}],"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/startLiveActivity(withToken:activityId:completion:)","interfaceLanguage":"swift"},"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/startLiveActivity(withToken:activityId:completion:)":{"kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/startLiveActivity(withToken:activityId:completion:)","abstract":[{"type":"text","text":"Sends live activity token to the server with a completion handler."}],"type":"topic","url":"\/documentation\/pushwooshframework\/pushwoosh\/startliveactivity(withtoken:activityid:completion:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"startLiveActivity"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withToken"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"activityId"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (((any "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"startLiveActivityWithToken:activityId:completion:"}],"title":"startLiveActivity(withToken:activityId:completion:)","role":"symbol","deprecated":true},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh":{"title":"Pushwoosh","kind":"symbol","url":"\/documentation\/pushwooshframework\/pushwoosh","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Pushwoosh"}],"abstract":[{"text":"Main SDK interface for push notification management.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"Pushwoosh"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","title":"PushwooshFramework","url":"\/documentation\/pushwooshframework","kind":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"startLiveActivityWithToken:activityId:completion:","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startLiveActivityWithToken:activityId:completion:"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"startLiveActivityWithToken:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"token"},{"kind":"text","text":" "},{"text":"activityId:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"activityId"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":" (^"},{"text":")(","kind":"text"},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * "},{"kind":"internalParam","text":"error"},{"text":")) ","kind":"text"},{"kind":"internalParam","text":"completion"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1startLiveActivity(withToken:activityId:completion:)\/title","op":"replace","value":"startLiveActivityWithToken:activityId:completion:"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1startLiveActivity(withToken:activityId:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"startLiveActivityWithToken:activityId:completion:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh\/title","value":"Pushwoosh"},{"value":[{"kind":"identifier","text":"Pushwoosh"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}