{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/startServerCommunication()"},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh"]]},"abstract":[{"text":"Starts communication with Pushwoosh server.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pushwoosh\/startservercommunication()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pushwoosh\/startservercommunication()"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"startServerCommunication","kind":"identifier"},{"text":"()","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"content":[{"anchor":"Overview","level":2,"type":"heading","text":"Overview"},{"inlineContent":[{"type":"text","text":"Enables network communication with Pushwoosh servers. Use this method to resume SDK operations after calling "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/stopServerCommunication()"},{"type":"text","text":"."}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"text":"When communication is enabled, the SDK will:","type":"text"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Send pending device registration"}]}]},{"content":[{"inlineContent":[{"text":"Sync queued tags","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"Report pending analytics events","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Resume all server interactions"}],"type":"paragraph"}]}]},{"anchor":"Default-State","text":"Default State","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"Server communication is "},{"inlineContent":[{"type":"text","text":"enabled by default"}],"type":"strong"},{"text":". You only need to call this method after explicitly stopping communication.","type":"text"}],"type":"paragraph"},{"text":"Example","type":"heading","anchor":"Example","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Resume communication after user accepts privacy policy:"}]},{"syntax":"swift","code":["func handlePrivacyPolicyAccepted() {","    userDefaults.set(true, forKey: \"privacyAccepted\")","","    Pushwoosh.configure.startServerCommunication()","    Pushwoosh.configure.registerForPushNotifications()","}"],"type":"codeListing"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Toggle communication based on user preference:"}]},{"code":["func updateDataSharingPreference(enabled: Bool) {","    if enabled {","        Pushwoosh.configure.startServerCommunication()","    } else {","        Pushwoosh.configure.stopServerCommunication()","    }","","    userDefaults.set(enabled, forKey: \"dataSharing\")","}"],"type":"codeListing","syntax":"swift"}],"kind":"content"}],"metadata":{"externalID":"c:objc(cs)Pushwoosh(im)startServerCommunication","role":"symbol","symbolKind":"method","title":"startServerCommunication()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"startServerCommunication"},{"text":"()","kind":"text"}],"roleHeading":"Instance Method","modules":[{"name":"PushwooshFramework"}],"navigatorTitle":[{"kind":"identifier","text":"startServerCommunication"}]},"seeAlsoSections":[{"title":"Related Documentation","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/stopServerCommunication()"]}],"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/stopServerCommunication()":{"kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/stopServerCommunication()","type":"topic","url":"\/documentation\/pushwooshframework\/pushwoosh\/stopservercommunication()","title":"stopServerCommunication()","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopServerCommunication"},{"kind":"text","text":"()"}],"navigatorTitle":[{"text":"stopServerCommunication","kind":"identifier"}],"abstract":[{"text":"Stops communication with Pushwoosh server.","type":"text"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/startServerCommunication()":{"kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/startServerCommunication()","type":"topic","url":"\/documentation\/pushwooshframework\/pushwoosh\/startservercommunication()","title":"startServerCommunication()","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"startServerCommunication"},{"kind":"text","text":"()"}],"navigatorTitle":[{"kind":"identifier","text":"startServerCommunication"}],"abstract":[{"type":"text","text":"Starts communication with Pushwoosh server."}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"title":"PushwooshFramework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","url":"\/documentation\/pushwooshframework","type":"topic","abstract":[{"text":"Push notification SDK for iOS applications.","type":"text"}],"role":"collection","kind":"symbol"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh":{"role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh","kind":"symbol","url":"\/documentation\/pushwooshframework\/pushwoosh","title":"Pushwoosh","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Pushwoosh","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Pushwoosh"}],"abstract":[{"type":"text","text":"Main SDK interface for push notification management."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"startServerCommunication","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startServerCommunication"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/stopServerCommunication()"],"title":"Related Documentation"}],"op":"replace"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"startServerCommunication"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"stopServerCommunication","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1stopServerCommunication()\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"stopServerCommunication"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1stopServerCommunication()\/fragments","op":"replace"},{"value":"startServerCommunication","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1startServerCommunication()\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"startServerCommunication","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1startServerCommunication()\/fragments"},{"op":"replace","value":"Pushwoosh","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh\/title"},{"value":[{"text":"Pushwoosh","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh\/fragments","op":"replace"}]}]}