{"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/stopLiveActivity()","interfaceLanguage":"swift"},"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"stopLiveActivity","kind":"identifier"},{"text":"()","kind":"text"}],"role":"symbol","symbolKind":"method","title":"stopLiveActivity()","roleHeading":"Instance Method","modules":[{"name":"PushwooshFramework"}],"externalID":"c:objc(cs)Pushwoosh(im)stopLiveActivity","navigatorTitle":[{"text":"stopLiveActivity","kind":"identifier"}],"platforms":[]},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopLiveActivity"},{"kind":"text","text":"()"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Overview","level":2,"anchor":"Overview","type":"heading"},{"name":"Deprecated","type":"aside","style":"note","content":[{"inlineContent":[{"type":"text","text":"Use "},{"code":"Pushwoosh\/LiveActivities","type":"codeVoice"},{"type":"text","text":" API instead:"}],"type":"paragraph"},{"type":"codeListing","syntax":"swift","code":["Pushwoosh.LiveActivities.stopLiveActivity()"]}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Notifies Pushwoosh servers that a Live Activity has ended."}]},{"anchor":"Example","level":2,"type":"heading","text":"Example"},{"type":"paragraph","inlineContent":[{"text":"End delivery tracking:","type":"text"}]},{"type":"codeListing","syntax":"swift","code":["func completeDelivery() async {","    await activity.end(dismissalPolicy: .immediate)","","    try? await Pushwoosh.LiveActivities.stopLiveActivity()","}"]}]}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pushwoosh\/stopliveactivity()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pushwoosh\/stopliveactivity()"]}],"abstract":[{"type":"text","text":"Stops the current live activity."}],"deprecationSummary":[{"type":"paragraph","inlineContent":[{"text":"Since 6.8.0: This method is deprecated and will be removed within 6 months. Use Pushwoosh.LiveActivities.stopLiveActivity() instead.","type":"text"}]}],"sections":[],"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"abstract":[{"type":"text","text":"Push notification SDK for iOS applications."}],"role":"collection","kind":"symbol","url":"\/documentation\/pushwooshframework","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","title":"PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh","type":"topic","url":"\/documentation\/pushwooshframework\/pushwoosh","title":"Pushwoosh","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Pushwoosh","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"Pushwoosh","kind":"identifier"}],"abstract":[{"type":"text","text":"Main SDK interface for push notification management."}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/stopLiveActivity()":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/stopLiveActivity()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"stopLiveActivity","kind":"identifier"},{"text":"()","kind":"text"}],"role":"symbol","title":"stopLiveActivity()","abstract":[{"type":"text","text":"Stops the current live activity."}],"type":"topic","url":"\/documentation\/pushwooshframework\/pushwoosh\/stopliveactivity()","kind":"symbol","navigatorTitle":[{"text":"stopLiveActivity","kind":"identifier"}],"deprecated":true}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"stopLiveActivity"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"stopLiveActivity","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"stopLiveActivity"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh\/title","value":"Pushwoosh"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh\/fragments","op":"replace","value":[{"text":"Pushwoosh","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1stopLiveActivity()\/title","op":"replace","value":"stopLiveActivity"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1stopLiveActivity()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"stopLiveActivity"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}