{"metadata":{"externalID":"c:objc(cs)Pushwoosh(im)stopServerCommunication","navigatorTitle":[{"text":"stopServerCommunication","kind":"identifier"}],"roleHeading":"Instance Method","title":"stopServerCommunication()","modules":[{"name":"PushwooshFramework"}],"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stopServerCommunication","kind":"identifier"},{"kind":"text","text":"()"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh"]]},"abstract":[{"text":"Stops communication with Pushwoosh server.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"stopServerCommunication","kind":"identifier"},{"kind":"text","text":"()"}],"languages":["swift"]}]},{"kind":"content","content":[{"type":"heading","text":"Overview","level":2,"anchor":"Overview"},{"inlineContent":[{"type":"text","text":"Temporarily disables all network communication with Pushwoosh servers. Use this for:"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"text":"GDPR compliance (user opts out of data collection)","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"Privacy-first onboarding (wait for user consent)","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Offline mode support"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Debugging network issues","type":"text"}]}]}]},{"type":"heading","text":"Behavior When Stopped","anchor":"Behavior-When-Stopped","level":2},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"No data is sent to Pushwoosh servers","type":"text"}]}]},{"content":[{"inlineContent":[{"text":"Tags and events are queued locally","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Push notifications can still be received (via APNs)"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Queued data is sent when communication resumes"}]}]}]},{"type":"heading","level":2,"text":"Example","anchor":"Example"},{"inlineContent":[{"type":"text","text":"Implement GDPR-compliant data collection opt-out:"}],"type":"paragraph"},{"code":["func handleGDPROptOut() {","    Pushwoosh.configure.stopServerCommunication()","","    userDefaults.set(false, forKey: \"analyticsEnabled\")","","    showConfirmation(\"Data collection disabled\")","}","","func handleGDPROptIn() {","    Pushwoosh.configure.startServerCommunication()","","    userDefaults.set(true, forKey: \"analyticsEnabled\")","}"],"syntax":"swift","type":"codeListing"},{"inlineContent":[{"text":"Wait for privacy consent before enabling SDK:","type":"text"}],"type":"paragraph"},{"syntax":"swift","type":"codeListing","code":["func application(_ application: UIApplication,","                didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {","","    if !userDefaults.bool(forKey: \"privacyConsentGiven\") {","        Pushwoosh.configure.stopServerCommunication()","    }","","    return true","}","","func privacyConsentViewController(_ controller: PrivacyConsentViewController,","                                   didFinishWithConsent consent: Bool) {","    userDefaults.set(consent, forKey: \"privacyConsentGiven\")","","    if consent {","        Pushwoosh.configure.startServerCommunication()","        Pushwoosh.configure.registerForPushNotifications()","    }","}"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pushwoosh\/stopservercommunication()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pushwoosh\/stopservercommunication()"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/stopServerCommunication()"},"kind":"symbol","seeAlsoSections":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/startServerCommunication()"],"title":"Related Documentation"}],"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/stopServerCommunication()":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/stopServerCommunication()","url":"\/documentation\/pushwooshframework\/pushwoosh\/stopservercommunication()","navigatorTitle":[{"kind":"identifier","text":"stopServerCommunication"}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stopServerCommunication","kind":"identifier"},{"text":"()","kind":"text"}],"abstract":[{"text":"Stops communication with Pushwoosh server.","type":"text"}],"type":"topic","title":"stopServerCommunication()","role":"symbol"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","title":"PushwooshFramework","role":"collection","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Push notification SDK for iOS applications."}],"url":"\/documentation\/pushwooshframework"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/startServerCommunication()":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/startServerCommunication()","url":"\/documentation\/pushwooshframework\/pushwoosh\/startservercommunication()","navigatorTitle":[{"kind":"identifier","text":"startServerCommunication"}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startServerCommunication","kind":"identifier"},{"text":"()","kind":"text"}],"abstract":[{"text":"Starts communication with Pushwoosh server.","type":"text"}],"type":"topic","title":"startServerCommunication()","role":"symbol"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh":{"url":"\/documentation\/pushwooshframework\/pushwoosh","navigatorTitle":[{"kind":"identifier","text":"Pushwoosh"}],"role":"symbol","abstract":[{"text":"Main SDK interface for push notification management.","type":"text"}],"title":"Pushwoosh","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Pushwoosh","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"stopServerCommunication","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"stopServerCommunication","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"replace","value":[{"title":"Related Documentation","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/startServerCommunication()"]}],"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"text":"stopServerCommunication","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1stopServerCommunication()\/title","value":"stopServerCommunication"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1stopServerCommunication()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"stopServerCommunication","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1startServerCommunication()\/title","value":"startServerCommunication"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1startServerCommunication()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startServerCommunication"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh\/title","op":"replace","value":"Pushwoosh"},{"op":"replace","value":[{"text":"Pushwoosh","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh\/fragments"}]}]}