{"abstract":[{"type":"text","text":"Stops the current live activity with a completion handler."}],"deprecationSummary":[{"inlineContent":[{"type":"text","text":"Since 6.8.0: This method is deprecated and will be removed in a future release. Use Pushwoosh.LiveActivities.stopLiveActivity(completion: ) instead."}],"type":"paragraph"}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pushwoosh\/stopliveactivity(completion:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pushwoosh\/stopliveactivity(completion:)"]}],"metadata":{"role":"symbol","platforms":[],"modules":[{"name":"PushwooshFramework"}],"title":"stopLiveActivity(completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"stopLiveActivity","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (((any "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":")?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"symbolKind":"method","navigatorTitle":[{"text":"stopLiveActivityWithCompletion:","kind":"identifier"}],"roleHeading":"Instance Method","externalID":"c:objc(cs)Pushwoosh(im)stopLiveActivityWithCompletion:"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/stopLiveActivity(completion:)"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"stopLiveActivity","kind":"identifier"},{"kind":"text","text":"("},{"text":"completion","kind":"externalParam"},{"text":": (((any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")? = nil)","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"anchor":"Overview","type":"heading","text":"Overview","level":2},{"style":"note","name":"Deprecated","content":[{"inlineContent":[{"type":"text","text":"Use "},{"type":"codeVoice","code":"Pushwoosh\/LiveActivities"},{"type":"text","text":" API instead."}],"type":"paragraph"}],"type":"aside"},{"type":"paragraph","inlineContent":[{"text":"Similar to ","type":"text"},{"type":"codeVoice","code":"stopLiveActivity()"},{"text":" but provides a callback when the operation completes.","type":"text"}]},{"level":2,"anchor":"Example","text":"Example","type":"heading"},{"inlineContent":[{"type":"text","text":"Use the new LiveActivities API:"}],"type":"paragraph"},{"type":"codeListing","code":["@available(iOS 16.1, *)","func completeDelivery(orderId: String) {","    Pushwoosh.LiveActivities.stopLiveActivity { error in","        if let error = error {","            self.logger.error(\"Failed to stop live activity: \\(error)\")","        } else {","            self.logger.info(\"Live activity stopped for order: \\(orderId)\")","        }","    }","","    Task {","        for activity in Activity<DeliveryAttributes>.activities {","            await activity.end(nil, dismissalPolicy: .immediate)","        }","    }","}"],"syntax":"swift"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/stopLiveActivity(completion:)":{"role":"symbol","url":"\/documentation\/pushwooshframework\/pushwoosh\/stopliveactivity(completion:)","abstract":[{"type":"text","text":"Stops the current live activity with a completion handler."}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/stopLiveActivity(completion:)","title":"stopLiveActivity(completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"stopLiveActivity"},{"kind":"text","text":"("},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (((any "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")?)","kind":"text"}],"deprecated":true,"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"stopLiveActivityWithCompletion:"}],"type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh":{"url":"\/documentation\/pushwooshframework\/pushwoosh","kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Pushwoosh"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Pushwoosh","kind":"identifier"}],"title":"Pushwoosh","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh","abstract":[{"type":"text","text":"Main SDK interface for push notification management."}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","title":"PushwooshFramework","type":"topic","kind":"symbol","abstract":[{"text":"Push notification SDK for iOS applications.","type":"text"}],"url":"\/documentation\/pushwooshframework","role":"collection"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"stopLiveActivityWithCompletion:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"stopLiveActivityWithCompletion:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"stopLiveActivityWithCompletion:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":" (^","kind":"text"},{"text":")(","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * "},{"kind":"internalParam","text":"error"},{"kind":"text","text":")) "},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1stopLiveActivity(completion:)\/title","value":"stopLiveActivityWithCompletion:"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1stopLiveActivity(completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"stopLiveActivityWithCompletion:","kind":"identifier"}]},{"value":"Pushwoosh","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh\/title"},{"value":[{"text":"Pushwoosh","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}