{"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/stopLiveActivity(with:)"},"abstract":[{"type":"text","text":"Stops a specific live activity by ID."}],"metadata":{"externalID":"c:objc(cs)Pushwoosh(im)stopLiveActivityWith:","role":"symbol","title":"stopLiveActivity(with:)","platforms":[],"modules":[{"name":"PushwooshFramework"}],"navigatorTitle":[{"text":"stopLiveActivityWith:","kind":"identifier"}],"symbolKind":"method","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"stopLiveActivity","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"with"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?)"}]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"stopLiveActivity"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"text":"activityId","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"languages":["swift"]}]},{"content":[{"type":"heading","anchor":"Discussion","text":"Discussion","level":2},{"inlineContent":[{"inlineContent":[{"type":"text","text":"Deprecated since 6.8.0"}],"type":"strong"},{"type":"text","text":": Use "},{"code":"Pushwoosh.LiveActivities.stopLiveActivity(activityId:)","type":"codeVoice"},{"type":"text","text":" instead."}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Stops a live activity identified by its activity ID. Use this when managing multiple live activities and you need to stop a specific one."}]},{"text":"Parameters","anchor":"Parameters","type":"heading","level":2},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"activityId: The ID of the live activity to stop"}],"type":"paragraph"}]}]}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pushwoosh\/stopliveactivity(with:)"]},{"paths":["\/documentation\/pushwooshframework\/pushwoosh\/stopliveactivity(with:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","deprecationSummary":[{"inlineContent":[{"text":"Since 6.8.0: This method is deprecated and will be removed in a future release. Use Pushwoosh.LiveActivities.stopLiveActivity(activityId: ) instead.","type":"text"}],"type":"paragraph"}],"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"kind":"symbol","abstract":[],"url":"\/documentation\/pushwooshframework","role":"collection","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","title":"PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/stopLiveActivity(with:)":{"type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"stopLiveActivity","kind":"identifier"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"text":"stopLiveActivityWith:","kind":"identifier"}],"deprecated":true,"url":"\/documentation\/pushwooshframework\/pushwoosh\/stopliveactivity(with:)","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/stopLiveActivity(with:)","kind":"symbol","title":"stopLiveActivity(with:)","abstract":[{"type":"text","text":"Stops a specific live activity by ID."}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"Pushwoosh"}],"abstract":[{"type":"text","text":"Main SDK interface for push notification management."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Pushwoosh"}],"title":"Pushwoosh","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh","kind":"symbol","url":"\/documentation\/pushwooshframework\/pushwoosh","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","value":"stopLiveActivityWith:","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"stopLiveActivityWith:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"stopLiveActivityWith:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"activityId"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1stopLiveActivity(with:)\/title","value":"stopLiveActivityWith:"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1stopLiveActivity(with:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"stopLiveActivityWith:","kind":"identifier"}],"op":"replace"},{"value":"Pushwoosh","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh\/fragments","value":[{"text":"Pushwoosh","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}