{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unregisterForPushNotifications","kind":"identifier"},{"text":"()","kind":"text"}],"languages":["swift"]}]},{"kind":"content","content":[{"text":"Overview","type":"heading","anchor":"Overview","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"This method:"}]},{"type":"orderedList","items":[{"content":[{"inlineContent":[{"text":"Notifies Pushwoosh servers to stop sending push notifications to this device","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Removes the device token from Pushwoosh"}]}]}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"The device will no longer receive push notifications through Pushwoosh until "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/registerForPushNotifications()"},{"type":"text","text":" is called again."}]},{"type":"heading","anchor":"Use-Cases","text":"Use Cases","level":2},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"text":"User logs out of the app","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"User disables notifications in app settings","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"GDPR\/privacy compliance requests"}]}]}]},{"text":"Important","type":"heading","level":2,"anchor":"Important"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This method only unregisters from Pushwoosh. The device may still receive push notifications from other providers if registered separately."}]},{"text":"Example","type":"heading","level":2,"anchor":"Example"},{"inlineContent":[{"type":"text","text":"Unregister when user logs out:"}],"type":"paragraph"},{"type":"codeListing","syntax":"swift","code":["func handleLogout() {","    Pushwoosh.configure.setUserId(\"\")","    Pushwoosh.configure.unregisterForPushNotifications()","","    clearLocalUserData()","    navigateToLogin()","}"]}]}],"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/unregisterForPushNotifications()","interfaceLanguage":"swift"},"abstract":[{"text":"Unregisters the device from push notifications.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"roleHeading":"Instance Method","navigatorTitle":[{"text":"unregisterForPushNotifications","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"unregisterForPushNotifications","kind":"identifier"},{"text":"()","kind":"text"}],"role":"symbol","externalID":"c:objc(cs)Pushwoosh(im)unregisterForPushNotifications","symbolKind":"method","modules":[{"name":"PushwooshFramework"}],"title":"unregisterForPushNotifications()"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pushwoosh\/unregisterforpushnotifications()"]},{"paths":["\/documentation\/pushwooshframework\/pushwoosh\/unregisterforpushnotifications()"],"traits":[{"interfaceLanguage":"occ"}]}],"seeAlsoSections":[{"title":"Related Documentation","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/unregisterForPushNotifications(completion:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/registerForPushNotifications()"]}],"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/unregisterForPushNotifications()":{"url":"\/documentation\/pushwooshframework\/pushwoosh\/unregisterforpushnotifications()","kind":"symbol","abstract":[{"type":"text","text":"Unregisters the device from push notifications."}],"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/unregisterForPushNotifications()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unregisterForPushNotifications"},{"kind":"text","text":"()"}],"title":"unregisterForPushNotifications()","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"unregisterForPushNotifications"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"kind":"symbol","role":"collection","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","title":"PushwooshFramework","abstract":[{"text":"Push notification SDK for iOS applications.","type":"text"}],"url":"\/documentation\/pushwooshframework","type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/registerForPushNotifications()":{"url":"\/documentation\/pushwooshframework\/pushwoosh\/registerforpushnotifications()","kind":"symbol","abstract":[{"type":"text","text":"Registers the device for push notifications."}],"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/registerForPushNotifications()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"registerForPushNotifications","kind":"identifier"},{"text":"()","kind":"text"}],"title":"registerForPushNotifications()","role":"symbol","navigatorTitle":[{"text":"registerForPushNotifications","kind":"identifier"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/unregisterForPushNotifications(completion:)":{"url":"\/documentation\/pushwooshframework\/pushwoosh\/unregisterforpushnotifications(completion:)","kind":"symbol","abstract":[{"text":"Unregisters the device from push notifications with a completion handler.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/unregisterForPushNotifications(completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unregisterForPushNotifications","kind":"identifier"},{"kind":"text","text":"("},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (((any "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"title":"unregisterForPushNotifications(completion:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"unregisterForPushNotificationsWithCompletion:"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh":{"role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh","title":"Pushwoosh","abstract":[{"type":"text","text":"Main SDK interface for push notification management."}],"type":"topic","navigatorTitle":[{"text":"Pushwoosh","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/pushwooshframework\/pushwoosh","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Pushwoosh"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"unregisterForPushNotifications"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"unregisterForPushNotifications","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/unregisterForPushNotifications(completion:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/registerForPushNotifications()"],"title":"Related Documentation"}],"path":"\/seeAlsoSections","op":"replace"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"unregisterForPushNotifications","kind":"identifier"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1unregisterForPushNotifications()\/title","op":"replace","value":"unregisterForPushNotifications"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1unregisterForPushNotifications()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"unregisterForPushNotifications"}]},{"value":"registerForPushNotifications","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1registerForPushNotifications()\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1registerForPushNotifications()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"registerForPushNotifications"}]},{"value":"unregisterForPushNotificationsWithCompletion:","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1unregisterForPushNotifications(completion:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1unregisterForPushNotifications(completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"unregisterForPushNotificationsWithCompletion:"}],"op":"replace"},{"value":"Pushwoosh","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh\/fragments","value":[{"kind":"identifier","text":"Pushwoosh"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}