{"seeAlsoSections":[{"title":"Related Documentation","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/unregisterForPushNotifications()","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/registerForPushNotifications(completion:)"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pushwoosh\/unregisterforpushnotifications(completion:)"]},{"paths":["\/documentation\/pushwooshframework\/pushwoosh\/unregisterforpushnotifications(completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"unregisterForPushNotifications","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (((any ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":")?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")? = nil)"}]}]},{"kind":"content","content":[{"anchor":"Overview","type":"heading","level":2,"text":"Overview"},{"inlineContent":[{"text":"Same as ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/unregisterForPushNotifications()"},{"type":"text","text":" but provides a completion callback to confirm the operation finished."}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Use this variant when you need to:"}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"Confirm unregistration before proceeding"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"Show user feedback about the operation","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Handle errors during unregistration"}]}]}]},{"text":"Example","type":"heading","level":2,"anchor":"Example"},{"inlineContent":[{"text":"Unregister on logout with confirmation:","type":"text"}],"type":"paragraph"},{"type":"codeListing","syntax":"swift","code":["func handleLogout(completion: @escaping (Bool) -> Void) {","    Pushwoosh.configure.setUserId(\"\")","","    Pushwoosh.configure.unregisterForPushNotifications { error in","        if let error = error {","            Analytics.log(\"unregister_failed\", error: error)","            completion(false)","        } else {","            self.clearLocalUserData()","            completion(true)","        }","    }","}"]},{"inlineContent":[{"text":"Toggle push notifications in settings:","type":"text"}],"type":"paragraph"},{"code":["func togglePushNotifications(enabled: Bool, completion: @escaping (Bool) -> Void) {","    if enabled {","        Pushwoosh.configure.registerForPushNotifications { _, error in","            completion(error == nil)","        }","    } else {","        Pushwoosh.configure.unregisterForPushNotifications { error in","            completion(error == nil)","        }","    }","}"],"type":"codeListing","syntax":"swift"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/unregisterForPushNotifications(completion:)"},"sections":[],"kind":"symbol","metadata":{"modules":[{"name":"PushwooshFramework"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"unregisterForPushNotifications","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": (((any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"navigatorTitle":[{"kind":"identifier","text":"unregisterForPushNotificationsWithCompletion:"}],"roleHeading":"Instance Method","role":"symbol","title":"unregisterForPushNotifications(completion:)","externalID":"c:objc(cs)Pushwoosh(im)unregisterForPushNotificationsWithCompletion:","symbolKind":"method"},"abstract":[{"text":"Unregisters the device from push notifications with a completion handler.","type":"text"}],"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/unregisterForPushNotifications()":{"url":"\/documentation\/pushwooshframework\/pushwoosh\/unregisterforpushnotifications()","abstract":[{"type":"text","text":"Unregisters the device from push notifications."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unregisterForPushNotifications","kind":"identifier"},{"kind":"text","text":"()"}],"title":"unregisterForPushNotifications()","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/unregisterForPushNotifications()","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"unregisterForPushNotifications"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/registerForPushNotifications(completion:)":{"type":"topic","title":"registerForPushNotifications(completion:)","abstract":[{"text":"Registers the device for push notifications with a completion handler.","type":"text"}],"url":"\/documentation\/pushwooshframework\/pushwoosh\/registerforpushnotifications(completion:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"registerForPushNotifications","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:PWTypes.h@T@PushwooshRegistrationHandler","text":"PushwooshRegistrationHandler"},{"text":"?)","kind":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/registerForPushNotifications(completion:)","navigatorTitle":[{"kind":"identifier","text":"registerForPushNotificationsWithCompletion:"}],"kind":"symbol"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"abstract":[{"text":"Push notification SDK for iOS applications.","type":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","title":"PushwooshFramework","kind":"symbol","role":"collection","url":"\/documentation\/pushwooshframework","type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/unregisterForPushNotifications(completion:)":{"kind":"symbol","title":"unregisterForPushNotifications(completion:)","url":"\/documentation\/pushwooshframework\/pushwoosh\/unregisterforpushnotifications(completion:)","abstract":[{"type":"text","text":"Unregisters the device from push notifications with a completion handler."}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"unregisterForPushNotifications"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (((any ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"kind":"text","text":")?) -> "},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"kind":"text","text":")?)"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/unregisterForPushNotifications(completion:)","navigatorTitle":[{"text":"unregisterForPushNotificationsWithCompletion:","kind":"identifier"}],"type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh","type":"topic","url":"\/documentation\/pushwooshframework\/pushwoosh","abstract":[{"type":"text","text":"Main SDK interface for push notification management."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Pushwoosh","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Pushwoosh"}],"title":"Pushwoosh","role":"symbol","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"unregisterForPushNotificationsWithCompletion:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"unregisterForPushNotificationsWithCompletion:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"replace","value":[{"title":"Related Documentation","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/unregisterForPushNotifications()","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/registerForPushNotifications(completion:)"]}],"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"unregisterForPushNotificationsWithCompletion:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":" (^","kind":"text"},{"text":")(","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":" * ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":")) ","kind":"text"},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"unregisterForPushNotifications","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1unregisterForPushNotifications()\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1unregisterForPushNotifications()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"unregisterForPushNotifications"}],"op":"replace"},{"value":"registerForPushNotificationsWithCompletion:","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1registerForPushNotifications(completion:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1registerForPushNotifications(completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"registerForPushNotificationsWithCompletion:","kind":"identifier"}]},{"value":"unregisterForPushNotificationsWithCompletion:","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1unregisterForPushNotifications(completion:)\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1unregisterForPushNotifications(completion:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"unregisterForPushNotificationsWithCompletion:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh\/title","op":"replace","value":"Pushwoosh"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh\/fragments","value":[{"kind":"identifier","text":"Pushwoosh"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}