{"metadata":{"roleHeading":"Type Method","platforms":[{"deprecated":false,"introducedAt":"16.1","name":"iOS","unavailable":false,"beta":false}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultSetup"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"defaultSetup","kind":"identifier"}],"externalID":"c:@M@PushwooshLiveActivities@objc(cs)PushwooshLiveActivitiesImplementationSetup(cm)defaultSetup","symbolKind":"method","title":"defaultSetup()","role":"symbol","modules":[{"name":"PushwooshLiveActivities"}]},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshliveactivities\/pushwooshliveactivitiesimplementationsetup\/defaultsetup()-8niha"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshliveactivities\/pushwooshliveactivitiesimplementationsetup\/defaultsetup()-8niha"]}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities","doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/PushwooshLiveActivitiesImplementationSetup"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"defaultSetup","kind":"identifier"},{"text":"()","kind":"text"}]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Discussion","level":2,"type":"heading","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"text":"This method sets up automatic lifecycle management using ","type":"text"},{"identifier":"doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/DefaultLiveActivityAttributes","isActive":true,"type":"reference"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Use this when you want the SDK to handle all activity management without defining custom types."}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/PushwooshLiveActivitiesImplementationSetup\/defaultSetup()-8niha"},"abstract":[{"type":"text","text":"Configures Live Activities with default attributes managed by Pushwoosh."}],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://com.pushwoosh.PushwooshLiveActivities/documentation/PushwooshLiveActivities":{"kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities","title":"PushwooshLiveActivities","role":"collection","abstract":[{"type":"text","text":"Real-time iOS Live Activities powered by push notifications."}],"type":"topic","url":"\/documentation\/pushwooshliveactivities"},"doc://com.pushwoosh.PushwooshLiveActivities/documentation/PushwooshLiveActivities/PushwooshLiveActivitiesImplementationSetup/defaultSetup()-8niha":{"title":"defaultSetup()","identifier":"doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/PushwooshLiveActivitiesImplementationSetup\/defaultSetup()-8niha","role":"symbol","kind":"symbol","url":"\/documentation\/pushwooshliveactivities\/pushwooshliveactivitiesimplementationsetup\/defaultsetup()-8niha","navigatorTitle":[{"kind":"identifier","text":"defaultSetup"}],"abstract":[{"type":"text","text":"Configures Live Activities with default attributes managed by Pushwoosh."}],"type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"defaultSetup"},{"text":"()","kind":"text"}]},"doc://com.pushwoosh.PushwooshLiveActivities/documentation/PushwooshLiveActivities/PushwooshLiveActivitiesImplementationSetup":{"title":"PushwooshLiveActivitiesImplementationSetup","abstract":[{"text":"Orchestrates iOS Live Activities integration with Pushwoosh push notifications.","type":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/PushwooshLiveActivitiesImplementationSetup","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PushwooshLiveActivitiesImplementationSetup","kind":"identifier"}],"navigatorTitle":[{"text":"PushwooshLiveActivitiesImplementationSetup","kind":"identifier"}],"role":"symbol","kind":"symbol","url":"\/documentation\/pushwooshliveactivities\/pushwooshliveactivitiesimplementationsetup"},"doc://com.pushwoosh.PushwooshLiveActivities/documentation/PushwooshLiveActivities/DefaultLiveActivityAttributes":{"navigatorTitle":[{"text":"DefaultLiveActivityAttributes","kind":"identifier"}],"title":"DefaultLiveActivityAttributes","type":"topic","url":"\/documentation\/pushwooshliveactivities\/defaultliveactivityattributes","abstract":[{"type":"text","text":"A flexible structure for defining Live Activity content dynamically."}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DefaultLiveActivityAttributes"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/DefaultLiveActivityAttributes","kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":[{"deprecated":false,"introducedAt":"16.1","name":"iOS","unavailable":false,"beta":false}],"path":"\/metadata\/platforms"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"defaultSetup"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"text":"defaultSetup","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"defaultSetup","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshLiveActivities~1documentation~1PushwooshLiveActivities~1PushwooshLiveActivitiesImplementationSetup~1defaultSetup()-8niha\/title","value":"defaultSetup"},{"value":[{"kind":"text","text":"+ "},{"text":"defaultSetup","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshLiveActivities~1documentation~1PushwooshLiveActivities~1PushwooshLiveActivitiesImplementationSetup~1defaultSetup()-8niha\/fragments"},{"value":"PushwooshLiveActivitiesImplementationSetup","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshLiveActivities~1documentation~1PushwooshLiveActivities~1PushwooshLiveActivitiesImplementationSetup\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshLiveActivities~1documentation~1PushwooshLiveActivities~1PushwooshLiveActivitiesImplementationSetup\/fragments","op":"replace","value":[{"text":"PushwooshLiveActivitiesImplementationSetup","kind":"identifier"}]}]}]}