{"sections":[],"metadata":{"roleHeading":"Instance Method","modules":[{"name":"PushwooshNotificationUI"}],"symbolKind":"method","role":"symbol","title":"didReceive(_:)","externalID":"c:@M@PushwooshNotificationUI@objc(cs)PushwooshStoriesViewController(im)didReceiveNotification:","navigatorTitle":[{"text":"didReceiveNotification:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didReceive"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UNNotification","text":"UNNotification"},{"kind":"text","text":")"}]},"abstract":[{"type":"text","text":"Inherited from "},{"code":"UNNotificationContentExtension.didReceive(_:)","type":"codeVoice"},{"text":".","type":"text"}],"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshNotificationUI\/documentation\/PushwooshNotificationUI\/PushwooshStoriesViewController\/didReceive(_:)","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshnotificationui\/pushwooshstoriesviewcontroller\/didreceive(_:)"]},{"paths":["\/documentation\/pushwooshnotificationui\/pushwooshstoriesviewcontroller\/didreceive(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didReceive"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"notification","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UNNotification","preciseIdentifier":"c:objc(cs)UNNotification","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshNotificationUI\/documentation\/PushwooshNotificationUI","doc:\/\/com.pushwoosh.PushwooshNotificationUI\/documentation\/PushwooshNotificationUI\/PushwooshStoriesViewController"]]},"references":{"doc://com.pushwoosh.PushwooshNotificationUI/documentation/PushwooshNotificationUI/PushwooshStoriesViewController/didReceive(_:)":{"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"didReceive","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UNNotification","text":"UNNotification","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","title":"didReceive(_:)","navigatorTitle":[{"kind":"identifier","text":"didReceiveNotification:"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshNotificationUI\/documentation\/PushwooshNotificationUI\/PushwooshStoriesViewController\/didReceive(_:)","kind":"symbol","url":"\/documentation\/pushwooshnotificationui\/pushwooshstoriesviewcontroller\/didreceive(_:)","abstract":[]},"doc://com.pushwoosh.PushwooshNotificationUI/documentation/PushwooshNotificationUI":{"type":"topic","abstract":[{"text":"A ready-made full-screen “stories” UI for an expanded push notification.","type":"text"}],"title":"PushwooshNotificationUI","role":"collection","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshNotificationUI\/documentation\/PushwooshNotificationUI","url":"\/documentation\/pushwooshnotificationui"},"doc://com.pushwoosh.PushwooshNotificationUI/documentation/PushwooshNotificationUI/PushwooshStoriesViewController":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PushwooshStoriesViewController","kind":"identifier"}],"url":"\/documentation\/pushwooshnotificationui\/pushwooshstoriesviewcontroller","title":"PushwooshStoriesViewController","abstract":[{"type":"text","text":"A drop-in "},{"type":"codeVoice","code":"UNNotificationContentExtension"},{"text":" view controller that renders a full-screen,","type":"text"},{"text":" ","type":"text"},{"text":"Instagram-style “stories” experience for an expanded push notification: full-bleed images,","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"top progress bars, an auto-advance timer, tap-zone navigation, and an optional deep-link button."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PushwooshStoriesViewController"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshNotificationUI\/documentation\/PushwooshNotificationUI\/PushwooshStoriesViewController","role":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"didReceiveNotification:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"didReceiveNotification:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"didReceiveNotification:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UNNotification","kind":"typeIdentifier","text":"UNNotification"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"notification"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"op":"replace","value":"didReceiveNotification:","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshNotificationUI~1documentation~1PushwooshNotificationUI~1PushwooshStoriesViewController~1didReceive(_:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"didReceiveNotification:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshNotificationUI~1documentation~1PushwooshNotificationUI~1PushwooshStoriesViewController~1didReceive(_:)\/fragments"},{"op":"replace","value":"PushwooshStoriesViewController","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshNotificationUI~1documentation~1PushwooshNotificationUI~1PushwooshStoriesViewController\/title"},{"value":[{"text":"PushwooshStoriesViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshNotificationUI~1documentation~1PushwooshNotificationUI~1PushwooshStoriesViewController\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}