{"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshNotificationUI\/documentation\/PushwooshNotificationUI\/PushwooshStoriesViewController\/viewWillDisappear(_:)","interfaceLanguage":"swift"},"metadata":{"title":"viewWillDisappear(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"viewWillDisappear","kind":"identifier"},{"kind":"text","text":"("},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"symbolKind":"method","roleHeading":"Instance Method","modules":[{"name":"PushwooshNotificationUI"}],"navigatorTitle":[{"text":"viewWillDisappear:","kind":"identifier"}],"role":"symbol","externalID":"c:@M@PushwooshNotificationUI@objc(cs)PushwooshStoriesViewController(im)viewWillDisappear:"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"viewWillDisappear","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"animated"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshNotificationUI\/documentation\/PushwooshNotificationUI","doc:\/\/com.pushwoosh.PushwooshNotificationUI\/documentation\/PushwooshNotificationUI\/PushwooshStoriesViewController"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshnotificationui\/pushwooshstoriesviewcontroller\/viewwilldisappear(_:)"]},{"paths":["\/documentation\/pushwooshnotificationui\/pushwooshstoriesviewcontroller\/viewwilldisappear(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://com.pushwoosh.PushwooshNotificationUI/documentation/PushwooshNotificationUI/PushwooshStoriesViewController/viewWillDisappear(_:)":{"title":"viewWillDisappear(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"viewWillDisappear","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":")","kind":"text"}],"url":"\/documentation\/pushwooshnotificationui\/pushwooshstoriesviewcontroller\/viewwilldisappear(_:)","abstract":[],"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshNotificationUI\/documentation\/PushwooshNotificationUI\/PushwooshStoriesViewController\/viewWillDisappear(_:)","navigatorTitle":[{"kind":"identifier","text":"viewWillDisappear:"}],"kind":"symbol","role":"symbol"},"doc://com.pushwoosh.PushwooshNotificationUI/documentation/PushwooshNotificationUI/PushwooshStoriesViewController":{"title":"PushwooshStoriesViewController","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PushwooshStoriesViewController","kind":"identifier"}],"url":"\/documentation\/pushwooshnotificationui\/pushwooshstoriesviewcontroller","abstract":[{"text":"A drop-in ","type":"text"},{"type":"codeVoice","code":"UNNotificationContentExtension"},{"type":"text","text":" view controller that renders a full-screen,"},{"text":" ","type":"text"},{"type":"text","text":"Instagram-style “stories” experience for an expanded push notification: full-bleed images,"},{"text":" ","type":"text"},{"text":"top progress bars, an auto-advance timer, tap-zone navigation, and an optional deep-link button.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshNotificationUI\/documentation\/PushwooshNotificationUI\/PushwooshStoriesViewController","navigatorTitle":[{"kind":"identifier","text":"PushwooshStoriesViewController"}],"kind":"symbol","role":"symbol"},"doc://com.pushwoosh.PushwooshNotificationUI/documentation/PushwooshNotificationUI":{"title":"PushwooshNotificationUI","url":"\/documentation\/pushwooshnotificationui","abstract":[{"text":"A ready-made full-screen “stories” UI for an expanded push notification.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshNotificationUI\/documentation\/PushwooshNotificationUI","kind":"symbol","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"viewWillDisappear:","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"viewWillDisappear:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"text":"viewWillDisappear:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"animated","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshNotificationUI~1documentation~1PushwooshNotificationUI~1PushwooshStoriesViewController~1viewWillDisappear(_:)\/title","value":"viewWillDisappear:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"viewWillDisappear:"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshNotificationUI~1documentation~1PushwooshNotificationUI~1PushwooshStoriesViewController~1viewWillDisappear(_:)\/fragments"},{"value":"PushwooshStoriesViewController","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshNotificationUI~1documentation~1PushwooshNotificationUI~1PushwooshStoriesViewController\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshNotificationUI~1documentation~1PushwooshNotificationUI~1PushwooshStoriesViewController\/fragments","value":[{"kind":"identifier","text":"PushwooshStoriesViewController"}],"op":"replace"}]}]}