{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"override"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"viewDidLoad"},{"text":"()","kind":"text"}]}]}],"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshNotificationUI\/documentation\/PushwooshNotificationUI\/PushwooshStoriesViewController\/viewDidLoad()","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"metadata":{"role":"symbol","externalID":"c:@M@PushwooshNotificationUI@objc(cs)PushwooshStoriesViewController(im)viewDidLoad","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"viewDidLoad","kind":"identifier"},{"text":"()","kind":"text"}],"symbolKind":"method","navigatorTitle":[{"text":"viewDidLoad","kind":"identifier"}],"title":"viewDidLoad()","modules":[{"name":"PushwooshNotificationUI"}]},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshNotificationUI\/documentation\/PushwooshNotificationUI","doc:\/\/com.pushwoosh.PushwooshNotificationUI\/documentation\/PushwooshNotificationUI\/PushwooshStoriesViewController"]]},"variants":[{"paths":["\/documentation\/pushwooshnotificationui\/pushwooshstoriesviewcontroller\/viewdidload()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pushwooshnotificationui\/pushwooshstoriesviewcontroller\/viewdidload()"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.pushwoosh.PushwooshNotificationUI/documentation/PushwooshNotificationUI/PushwooshStoriesViewController/viewDidLoad()":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshNotificationUI\/documentation\/PushwooshNotificationUI\/PushwooshStoriesViewController\/viewDidLoad()","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"viewDidLoad","kind":"identifier"},{"text":"()","kind":"text"}],"type":"topic","url":"\/documentation\/pushwooshnotificationui\/pushwooshstoriesviewcontroller\/viewdidload()","title":"viewDidLoad()","navigatorTitle":[{"text":"viewDidLoad","kind":"identifier"}]},"doc://com.pushwoosh.PushwooshNotificationUI/documentation/PushwooshNotificationUI":{"url":"\/documentation\/pushwooshnotificationui","identifier":"doc:\/\/com.pushwoosh.PushwooshNotificationUI\/documentation\/PushwooshNotificationUI","title":"PushwooshNotificationUI","abstract":[{"text":"A ready-made full-screen “stories” UI for an expanded push notification.","type":"text"}],"role":"collection","type":"topic","kind":"symbol"},"doc://com.pushwoosh.PushwooshNotificationUI/documentation/PushwooshNotificationUI/PushwooshStoriesViewController":{"title":"PushwooshStoriesViewController","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PushwooshStoriesViewController","kind":"identifier"}],"url":"\/documentation\/pushwooshnotificationui\/pushwooshstoriesviewcontroller","abstract":[{"text":"A drop-in ","type":"text"},{"type":"codeVoice","code":"UNNotificationContentExtension"},{"type":"text","text":" view controller that renders a full-screen,"},{"text":" ","type":"text"},{"type":"text","text":"Instagram-style “stories” experience for an expanded push notification: full-bleed images,"},{"text":" ","type":"text"},{"text":"top progress bars, an auto-advance timer, tap-zone navigation, and an optional deep-link button.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshNotificationUI\/documentation\/PushwooshNotificationUI\/PushwooshStoriesViewController","navigatorTitle":[{"kind":"identifier","text":"PushwooshStoriesViewController"}],"kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"viewDidLoad"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"viewDidLoad","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"viewDidLoad"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"value":"viewDidLoad","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshNotificationUI~1documentation~1PushwooshNotificationUI~1PushwooshStoriesViewController~1viewDidLoad()\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshNotificationUI~1documentation~1PushwooshNotificationUI~1PushwooshStoriesViewController~1viewDidLoad()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"viewDidLoad"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshNotificationUI~1documentation~1PushwooshNotificationUI~1PushwooshStoriesViewController\/title","value":"PushwooshStoriesViewController"},{"value":[{"text":"PushwooshStoriesViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshNotificationUI~1documentation~1PushwooshNotificationUI~1PushwooshStoriesViewController\/fragments","op":"replace"}]}]}