#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 5.10 (swiftlang-5.10.0.13 clang-1500.3.9.4)
#ifndef PUSHWOOSHTVOS_SWIFT_H
#define PUSHWOOSHTVOS_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
@import PushwooshBridge;
@import UIKit;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="PushwooshTVOS",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

/// Manager for displaying Rich Media content on tvOS.
/// This class handles the parsing, rendering, and display of HTML-based Rich Media
/// content with full support for tvOS Focus Engine and Apple TV remote navigation.
/// <h2>Overview</h2>
/// The Rich Media manager automatically:
/// <ul>
///   <li>
///     Parses HTML content with inline styles
///   </li>
///   <li>
///     Renders native UIKit components
///   </li>
///   <li>
///     Configures focus navigation for tvOS remote
///   </li>
///   <li>
///     Handles button actions (events, tags, close)
///   </li>
///   <li>
///     Manages presentation and dismissal animations
///   </li>
/// </ul>
/// <h2>Usage</h2>
/// Configure Rich Media behavior during app initialization:
/// \code
/// Pushwoosh.TVoS.configureRichMediaWith(
///     position: .center,
///     presentAnimation: .fromBottom,
///     dismissAnimation: .toBottom
/// )
///
/// \endcode
SWIFT_CLASS_NAMED("PWTVOSRichMediaManager") SWIFT_AVAILABILITY(tvos,introduced=11.0)
@interface PWTVOSRichMediaManager : NSObject
/// The screen position where Rich Media will be displayed.
@property (nonatomic) enum PWTVOSRichMediaPosition position;
/// The animation type used when presenting Rich Media.
@property (nonatomic) enum PWTVOSRichMediaPresentAnimation animationType;
/// The animation type used when dismissing Rich Media.
@property (nonatomic) enum PWTVOSRichMediaDismissAnimation dismissAnimationType;
/// Configures Rich Media presentation settings.
/// \param position Screen position for Rich Media display. Defaults to <code>.center</code>.
///
/// \param presentAnimation Animation when Rich Media appears.
///
/// \param dismissAnimation Animation when Rich Media disappears. Defaults to <code>.none</code>.
///
- (void)configureRichMediaWithPosition:(enum PWTVOSRichMediaPosition)position presentAnimation:(enum PWTVOSRichMediaPresentAnimation)presentAnimation dismissAnimation:(enum PWTVOSRichMediaDismissAnimation)dismissAnimation;
/// Controls visibility of the Close button on Rich Media.
/// \param show <code>true</code> to show Close button, <code>false</code> to hide it.
///
- (void)configureCloseButton:(BOOL)show;
/// Sets a handler for getTags button actions in Rich Media.
/// \param handler Closure called when getTags button is clicked, receiving tags dictionary.
///
- (void)setGetTagsHandler:(void (^ _Nonnull)(NSDictionary * _Nonnull))handler;
/// Handles in-app resource for Rich Media display.
/// \param resource Resource object containing pageUrl and code.
///
///
/// returns:
/// <code>true</code> if resource was handled successfully.
- (BOOL)handleInAppResource:(id _Nonnull)resource SWIFT_WARN_UNUSED_RESULT;
/// Dismisses currently displayed Rich Media.
/// \param animated Whether to animate the dismissal.
///
- (void)dismissWithAnimated:(BOOL)animated;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSString;
@class NSData;

/// Main implementation class for tvOS push notifications and Rich Media.
/// This class provides the core functionality for integrating Pushwoosh push notifications
/// and Rich Media content into tvOS applications. It handles device registration, push
/// notification processing, and Rich Media display with tvOS-specific optimizations.
/// <h2>Usage</h2>
/// Initialize and configure during app launch:
/// \code
/// Pushwoosh.TVoS.setAppCode("YOUR-APP-CODE")
/// Pushwoosh.TVoS.registerForTvPushNotifications()
///
/// \endcode<h2>Topics</h2>
/// <h3>Configuration</h3>
/// <ul>
///   <li>
///     <code>setAppCode(_:)</code>
///   </li>
///   <li>
///     <code>registerForTvPushNotifications()</code>
///   </li>
///   <li>
///     <code>registerForPushNotifications(withToken:completion:)</code>
///   </li>
/// </ul>
/// <h3>Push Handling</h3>
/// <ul>
///   <li>
///     <code>handleTvPushToken(_:)</code>
///   </li>
///   <li>
///     <code>handleTvPushRegistrationFailure(_:)</code>
///   </li>
///   <li>
///     <code>handleTvPushReceived(userInfo:completionHandler:)</code>
///   </li>
///   <li>
///     <code>handleTVOSPush(userInfo:)</code>
///   </li>
/// </ul>
/// <h3>Rich Media</h3>
/// <ul>
///   <li>
///     <code>richMediaManager</code>
///   </li>
///   <li>
///     <code>configureRichMediaWith(position:presentAnimation:dismissAnimation:)</code>
///   </li>
///   <li>
///     <code>configureCloseButton(_:)</code>
///   </li>
///   <li>
///     <code>setRichMediaGetTagsHandler(_:)</code>
///   </li>
/// </ul>
SWIFT_CLASS_NAMED("PushwooshTVOSImplementation") SWIFT_AVAILABILITY(tvos,introduced=11.0)
@interface PushwooshTVOSImplementation : NSObject
/// Shared singleton instance of the tvOS implementation.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) PushwooshTVOSImplementation * _Nonnull shared;)
+ (PushwooshTVOSImplementation * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
/// Rich Media manager instance for displaying HTML content.
/// Provides access to the Rich Media manager for advanced configuration
/// and programmatic control of Rich Media display.
@property (nonatomic, readonly, strong) PWTVOSRichMediaManager * _Nonnull richMediaManager;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// Sets the Pushwoosh application code for tvOS.
/// This method must be called before registering for push notifications.
/// The app code can be found in your Pushwoosh Control Panel.
/// <h2>Example</h2>
/// \code
/// Pushwoosh.TVoS.setAppCode("12345-67890")
///
/// \endcode\param appCode The Pushwoosh application identifier (format: XXXXX-XXXXX).
///
+ (void)setAppCode:(NSString * _Nonnull)appCode;
/// Registers the tvOS device for push notifications with the Pushwoosh server.
/// Call this method after receiving a device token from Apple Push Notification service.
/// This method sends the device token to Pushwoosh servers to enable push notifications.
/// <h2>Example</h2>
/// \code
/// func application(_ application: UIApplication,
///                  didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
///     Pushwoosh.TVoS.registerForPushNotifications(withToken: deviceToken) { error in
///         if let error = error {
///             print("Failed to register: \(error)")
///         } else {
///             print("Successfully registered")
///         }
///     }
/// }
///
/// \endcode\param token The device token received from APNs in <code>application(_:didRegisterForRemoteNotificationsWithDeviceToken:)</code>.
///
/// \param completion Optional completion handler called when registration completes. The handler receives an error parameter if registration fails, or nil on success.
///
- (void)registerForPushNotificationsWithToken:(NSData * _Nonnull)token completion:(void (^ _Nullable)(NSError * _Nullable))completion;
/// Registers for tvOS push notifications.
/// This method requests push notification authorization and registers the device
/// for remote notifications on tvOS. Call this during app initialization.
/// <h2>Example</h2>
/// \code
/// func application(_ application: UIApplication,
///                  didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
///     Pushwoosh.TVoS.setAppCode("XXXXX-XXXXX")
///     Pushwoosh.TVoS.registerForTvPushNotifications()
///     return true
/// }
///
/// \endcode
+ (void)registerForTvPushNotifications;
/// Unregisters the tvOS device from receiving push notifications.
/// This method removes the device registration from Pushwoosh servers.
/// The device will no longer receive push notifications until it registers again.
/// <h2>Example</h2>
/// \code
/// Pushwoosh.TVoS.unregisterForTvPushNotifications { error in
///     if let error = error {
///         print("Failed to unregister: \(error)")
///     } else {
///         print("Successfully unregistered")
///     }
/// }
///
/// \endcode\param completion Optional completion handler called when unregistration completes. The handler receives an error parameter if unregistration fails, or nil on success.
///
- (void)unregisterForPushNotificationsWithCompletion:(void (^ _Nullable)(NSError * _Nullable))completion;
/// Unregisters the tvOS device from receiving push notifications.
/// This is a convenience method that calls the instance method on the shared instance.
/// \param completion Optional completion handler called when unregistration completes.
///
+ (void)unregisterForTvPushNotificationsWithCompletion:(void (^ _Nullable)(NSError * _Nullable))completion;
/// Handles the device token received from tvOS push registration.
/// Call this method from <code>application(_:didRegisterForRemoteNotificationsWithDeviceToken:)</code>
/// to process the device token and register it with Pushwoosh.
/// <h2>Example</h2>
/// \code
/// func application(_ application: UIApplication,
///                  didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
///     Pushwoosh.TVoS.handleTvPushToken(deviceToken)
/// }
///
/// \endcode\param deviceToken The device token data received from APNs.
///
+ (void)handleTvPushToken:(NSData * _Nonnull)deviceToken;
/// Handles push registration failure on tvOS.
/// Call this method from <code>application(_:didFailToRegisterForRemoteNotificationsWithError:)</code>
/// to log and handle registration errors.
/// <h2>Example</h2>
/// \code
/// func application(_ application: UIApplication,
///                  didFailToRegisterForRemoteNotificationsWithError error: Error) {
///     Pushwoosh.TVoS.handleTvPushRegistrationFailure(error)
/// }
///
/// \endcode\param error The error that occurred during registration.
///
+ (void)handleTvPushRegistrationFailure:(NSError * _Nonnull)error;
/// Handles incoming push notification on tvOS.
/// Call this method from <code>application(_:didReceiveRemoteNotification:fetchCompletionHandler:)</code>
/// to process incoming push notifications. The method automatically detects and displays
/// Rich Media if present in the notification payload.
/// <h2>Example</h2>
/// \code
/// func application(_ application: UIApplication,
///                  didReceiveRemoteNotification userInfo: [AnyHashable: Any],
///                  fetchCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult) -> Void) {
///     Pushwoosh.TVoS.handleTvPushReceived(userInfo: userInfo, completionHandler: completionHandler)
/// }
///
/// \endcode\param userInfo Dictionary containing push payload data.
///
/// \param completionHandler Completion handler to call when processing is complete.
///
+ (void)handleTvPushReceivedWithUserInfo:(NSDictionary * _Nonnull)userInfo completionHandler:(void (^ _Nonnull)(UIBackgroundFetchResult))completionHandler;
/// Handles incoming push notifications with rich media content for tvOS.
/// Call this method to process push notifications that may contain rich media content.
/// If the notification contains rich media, it will be displayed automatically.
/// <h2>Example</h2>
/// \code
/// func application(_ application: UIApplication,
///                  didReceiveRemoteNotification userInfo: [AnyHashable: Any],
///                  fetchCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult) -> Void) {
///     if Pushwoosh.TVoS.handleTVOSPush(userInfo: userInfo) {
///         completionHandler(.newData)
///     } else {
///         completionHandler(.noData)
///     }
/// }
///
/// \endcode\param userInfo The push notification payload received from APNs.
///
///
/// returns:
/// <code>true</code> if the notification contains rich media and was handled, <code>false</code> otherwise.
+ (BOOL)handleTVOSPushWithUserInfo:(NSDictionary * _Nonnull)userInfo SWIFT_WARN_UNUSED_RESULT;
/// Configures rich media presentation, positioning, and dismissal animations for tvOS.
/// This method allows you to customize how rich media content appears, where it’s positioned,
/// and how it disappears on screen. You can choose from different animation directions,
/// screen positions, or disable animation entirely.
/// <h2>Example</h2>
/// \code
/// // Configure rich media to appear on the left, slide in from bottom and slide out to left
/// Pushwoosh.TVoS.configureRichMediaWith(
///     position: .left,
///     presentAnimation: .fromBottom,
///     dismissAnimation: .toLeft
/// )
///
/// \endcodenote:
/// This configuration applies to all subsequent rich media presentations until changed.
/// \param position The screen position where rich media content will be displayed. See <code>PWTVOSRichMediaPosition</code> for available options.
///
/// \param presentAnimation The animation type to use when presenting rich media. See <code>PWTVOSRichMediaPresentAnimation</code> for available options.
///
/// \param dismissAnimation The animation type to use when dismissing rich media. Defaults to <code>.none</code>. See <code>PWTVOSRichMediaDismissAnimation</code> for available options.
///
+ (void)configureRichMediaWithPosition:(enum PWTVOSRichMediaPosition)position presentAnimation:(enum PWTVOSRichMediaPresentAnimation)presentAnimation dismissAnimation:(enum PWTVOSRichMediaDismissAnimation)dismissAnimation;
/// Controls whether the Close button is displayed on rich media content.
/// By default, a Close button is shown at the bottom of rich media presentations,
/// allowing users to dismiss the content. You can hide this button if you want
/// rich media to only be dismissible through button actions within the content itself.
/// <h2>Example</h2>
/// \code
/// // Hide the system Close button
/// Pushwoosh.TVoS.configureCloseButton(false)
///
/// \endcodenote:
/// If you hide the Close button, ensure your rich media content includes a button with the <code>closeInApp()</code> action to allow users to dismiss it.
/// \param show <code>true</code> to show the Close button (default), <code>false</code> to hide it.
///
+ (void)configureCloseButton:(BOOL)show;
/// Sets a handler to receive tags when requested from rich media content.
/// When a user interacts with a getTags button in rich media HTML content,
/// this handler will be called with the tags retrieved from Pushwoosh.
/// This allows you to handle tag data in your application as needed.
/// <h2>Example</h2>
/// \code
/// Pushwoosh.TVoS.setRichMediaGetTagsHandler { tags in
///     print("Received tags from rich media: \(tags)")
///     // Handle tags in your application
/// }
///
/// \endcode\param handler A closure that receives tags as a dictionary when getTags is triggered. The dictionary contains tag keys and their values.
///
+ (void)setRichMediaGetTagsHandler:(void (^ _Nonnull)(NSDictionary * _Nonnull))handler;
+ (Class _Nonnull)tvos SWIFT_WARN_UNUSED_RESULT;
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
