{"abstract":[{"type":"text","text":"Called when the application receives a push notification."}],"seeAlsoSections":[{"title":"Related Documentation","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWMessagingDelegate\/pushwoosh(_:onMessageOpened:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/showPushnotificationAlert"]},{"generated":true,"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWMessagingDelegate\/pushwoosh(_:onMessageOpened:)"],"title":"Handling Notifications"}],"variants":[{"paths":["\/documentation\/pushwooshframework\/pwmessagingdelegate\/pushwoosh(_:onmessagereceived:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pwmessagingdelegate\/pushwoosh(_:onmessagereceived:)"]}],"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWMessagingDelegate\/pushwoosh(_:onMessageReceived:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWMessagingDelegate"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pushwoosh","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"pushwoosh","kind":"internalParam"},{"kind":"text","text":": "},{"text":"Pushwoosh","preciseIdentifier":"c:objc(cs)Pushwoosh","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"onMessageReceived"},{"text":" ","kind":"text"},{"text":"message","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"PWMessage","preciseIdentifier":"c:objc(cs)PWMessage","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"anchor":"Overview","type":"heading","level":2,"text":"Overview"},{"inlineContent":[{"type":"text","text":"This method is invoked when a push notification arrives, regardless of app state:"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"inlineContent":[{"text":"Foreground","type":"text"}],"type":"strong"},{"text":": Called immediately when notification arrives","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"text":"Background","type":"text"}]},{"type":"text","text":": Called when system wakes your app to process the notification"}]}]}]},{"type":"paragraph","inlineContent":[{"text":"Use this method to:","type":"text"}]},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Log notification receipt for analytics","type":"text"}]}]},{"content":[{"inlineContent":[{"text":"Update local data based on notification content","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Refresh UI if app is in foreground"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Trigger background data sync"}]}]}],"type":"unorderedList"},{"level":2,"type":"heading","anchor":"Foreground-Behavior","text":"Foreground Behavior"},{"inlineContent":[{"type":"text","text":"When the app is in foreground, notifications are received but not displayed by default. Use "},{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/showPushnotificationAlert","isActive":true,"type":"reference"},{"type":"text","text":" to control this behavior."}],"type":"paragraph"},{"text":"Example","level":2,"anchor":"Example","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Track notification receipt and update local data:"}]},{"syntax":"swift","type":"codeListing","code":["func pushwoosh(_ pushwoosh: Pushwoosh, onMessageReceived message: PWMessage) {","    Analytics.log(\"push_received\", [","        \"campaign_id\": message.customData?[\"campaign_id\"] ?? \"\",","        \"app_state\": UIApplication.shared.applicationState.rawValue","    ])","","    if let action = message.customData?[\"action\"] as? String {","        switch action {","        case \"refresh_orders\":","            OrderManager.shared.refreshOrders()","        case \"update_cart\":","            CartManager.shared.syncWithServer()","        default:","            break","        }","    }","}"]},{"type":"paragraph","inlineContent":[{"text":"Show in-app notification banner when app is in foreground:","type":"text"}]},{"type":"codeListing","syntax":"swift","code":["func pushwoosh(_ pushwoosh: Pushwoosh, onMessageReceived message: PWMessage) {","    guard UIApplication.shared.applicationState == .active else { return }","","    let banner = InAppNotificationBanner(","        title: message.title ?? \"New Notification\",","        message: message.message ?? \"\"","    )","    banner.show()","}"]}]}],"metadata":{"modules":[{"name":"PushwooshFramework"}],"symbolKind":"method","externalID":"c:objc(pl)PWMessagingDelegate(im)pushwoosh:onMessageReceived:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pushwoosh","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Pushwoosh","preciseIdentifier":"c:objc(cs)Pushwoosh"},{"text":", ","kind":"text"},{"text":"onMessageReceived","kind":"externalParam"},{"kind":"text","text":": "},{"text":"PWMessage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PWMessage"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"pushwoosh:onMessageReceived:"}],"role":"symbol","title":"pushwoosh(_:onMessageReceived:)","roleHeading":"Instance Method"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh":{"kind":"symbol","url":"\/documentation\/pushwooshframework\/pushwoosh","title":"Pushwoosh","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Pushwoosh","kind":"identifier"}],"navigatorTitle":[{"text":"Pushwoosh","kind":"identifier"}],"abstract":[{"text":"Main SDK interface for push notification management.","type":"text"}],"type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"abstract":[{"text":"Push notification SDK for iOS applications.","type":"text"}],"url":"\/documentation\/pushwooshframework","title":"PushwooshFramework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","role":"collection","type":"topic","kind":"symbol"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/showPushnotificationAlert":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/showPushnotificationAlert","url":"\/documentation\/pushwooshframework\/pushwoosh\/showpushnotificationalert","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"showPushnotificationAlert"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"abstract":[{"text":"Controls whether push notification alerts are shown when the app is in foreground.","type":"text"}],"navigatorTitle":[{"text":"showPushnotificationAlert","kind":"identifier"}],"title":"showPushnotificationAlert","type":"topic","role":"symbol"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWMessagingDelegate/pushwoosh(_:onMessageOpened:)":{"abstract":[{"type":"text","text":"Called when the user taps on a push notification."}],"type":"topic","title":"pushwoosh(_:onMessageOpened:)","url":"\/documentation\/pushwooshframework\/pwmessagingdelegate\/pushwoosh(_:onmessageopened:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pushwoosh"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)Pushwoosh","kind":"typeIdentifier","text":"Pushwoosh"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onMessageOpened"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)PWMessage","kind":"typeIdentifier","text":"PWMessage"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"pushwoosh:onMessageOpened:","kind":"identifier"}],"kind":"symbol","required":true,"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWMessagingDelegate\/pushwoosh(_:onMessageOpened:)"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWMessagingDelegate":{"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PWMessagingDelegate"}],"url":"\/documentation\/pushwooshframework\/pwmessagingdelegate","navigatorTitle":[{"text":"PWMessagingDelegate","kind":"identifier"}],"type":"topic","role":"symbol","title":"PWMessagingDelegate","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWMessagingDelegate","abstract":[{"type":"text","text":"Delegate protocol for handling push notification events."}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWMessagingDelegate/pushwoosh(_:onMessageReceived:)":{"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Called when the application receives a push notification."}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWMessagingDelegate\/pushwoosh(_:onMessageReceived:)","title":"pushwoosh(_:onMessageReceived:)","url":"\/documentation\/pushwooshframework\/pwmessagingdelegate\/pushwoosh(_:onmessagereceived:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pushwoosh"},{"text":"(","kind":"text"},{"text":"Pushwoosh","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)Pushwoosh"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onMessageReceived"},{"text":": ","kind":"text"},{"text":"PWMessage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PWMessage"},{"kind":"text","text":")"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"pushwoosh:onMessageReceived:"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"pushwoosh:onMessageReceived:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"pushwoosh:onMessageReceived:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"replace","path":"\/seeAlsoSections","value":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWMessagingDelegate\/pushwoosh(_:onMessageOpened:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/showPushnotificationAlert"],"title":"Related Documentation"},{"generated":true,"title":"Handling Notifications","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWMessagingDelegate\/pushwoosh(_:onMessageOpened:)"]}]},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"pushwoosh:"},{"kind":"text","text":"("},{"text":"Pushwoosh","preciseIdentifier":"c:objc(cs)Pushwoosh","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"pushwoosh","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"onMessageReceived:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PWMessage","preciseIdentifier":"c:objc(cs)PWMessage"},{"text":" *) ","kind":"text"},{"text":"message","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"Pushwoosh","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh\/title","op":"replace"},{"value":[{"text":"Pushwoosh","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh\/fragments","op":"replace"},{"value":"showPushnotificationAlert","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1showPushnotificationAlert\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1showPushnotificationAlert\/fragments","value":[{"kind":"identifier","text":"showPushnotificationAlert"}]},{"op":"replace","value":"pushwoosh:onMessageOpened:","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWMessagingDelegate~1pushwoosh(_:onMessageOpened:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWMessagingDelegate~1pushwoosh(_:onMessageOpened:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"pushwoosh:onMessageOpened:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWMessagingDelegate\/title","value":"PWMessagingDelegate"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWMessagingDelegate\/fragments","value":[{"text":"PWMessagingDelegate","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWMessagingDelegate~1pushwoosh(_:onMessageReceived:)\/title","value":"pushwoosh:onMessageReceived:"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWMessagingDelegate~1pushwoosh(_:onMessageReceived:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"pushwoosh:onMessageReceived:","kind":"identifier"}]}]}]}