{"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWMessagingDelegate"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pwmessagingdelegate\/pushwoosh(_:onmessageopened:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pwmessagingdelegate\/pushwoosh(_:onmessageopened:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pushwoosh"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"pushwoosh"},{"text":": ","kind":"text"},{"text":"Pushwoosh","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)Pushwoosh"},{"text":", ","kind":"text"},{"text":"onMessageOpened","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"message","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"PWMessage","preciseIdentifier":"c:objc(cs)PWMessage","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"Overview","type":"heading","level":2,"text":"Overview"},{"type":"paragraph","inlineContent":[{"text":"This method is invoked when a user explicitly taps on a notification banner or notification in the Notification Center. Use this method to:","type":"text"}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"text":"Navigate to relevant content","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Open deep links","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Track user engagement with notifications"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Perform actions based on notification type"}]}]}]},{"level":2,"type":"heading","anchor":"Timing","text":"Timing"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This method is called:"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"When user taps notification while app is in background","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"When user taps notification while app is terminated (app is launched first)"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"NOT called for silent\/background notifications"}],"type":"paragraph"}]}]},{"type":"heading","anchor":"Example","level":2,"text":"Example"},{"type":"paragraph","inlineContent":[{"text":"Handle deep links from notification:","type":"text"}]},{"type":"codeListing","syntax":"swift","code":["func pushwoosh(_ pushwoosh: Pushwoosh, onMessageOpened message: PWMessage) {","    Analytics.log(\"push_opened\", [","        \"campaign_id\": message.customData?[\"campaign_id\"] ?? \"\"","    ])","","    guard let customData = message.customData else { return }","","    if let deepLink = customData[\"deep_link\"] as? String,","       let url = URL(string: deepLink) {","        DeepLinkRouter.shared.handle(url)","        return","    }","","    if let screen = customData[\"screen\"] as? String {","        navigateToScreen(screen, params: customData)","    }","}","","private func navigateToScreen(_ screen: String, params: [AnyHashable: Any]) {","    switch screen {","    case \"order_details\":","        if let orderId = params[\"order_id\"] as? String {","            router.push(OrderDetailsViewController(orderId: orderId))","        }","    case \"product\":","        if let productId = params[\"product_id\"] as? String {","            router.push(ProductViewController(productId: productId))","        }","    case \"promo\":","        if let promoCode = params[\"promo_code\"] as? String {","            router.push(PromoViewController(code: promoCode))","        }","    default:","        break","    }","}"]},{"inlineContent":[{"text":"Open specific tab when notification is tapped:","type":"text"}],"type":"paragraph"},{"type":"codeListing","syntax":"swift","code":["func pushwoosh(_ pushwoosh: Pushwoosh, onMessageOpened message: PWMessage) {","    guard let tabIndex = message.customData?[\"tab\"] as? Int else { return }","","    if let tabBarController = window?.rootViewController as? UITabBarController {","        tabBarController.selectedIndex = tabIndex","    }","}"]}]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWMessagingDelegate\/pushwoosh(_:onMessageOpened:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Called when the user taps on a push notification."}],"seeAlsoSections":[{"title":"Related Documentation","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWMessagingDelegate\/pushwoosh(_:onMessageReceived:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/delegate"]},{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWMessagingDelegate\/pushwoosh(_:onMessageReceived:)"],"title":"Handling Notifications","generated":true}],"metadata":{"externalID":"c:objc(pl)PWMessagingDelegate(im)pushwoosh:onMessageOpened:","title":"pushwoosh(_:onMessageOpened:)","modules":[{"name":"PushwooshFramework"}],"role":"symbol","roleHeading":"Instance Method","navigatorTitle":[{"text":"pushwoosh:onMessageOpened:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pushwoosh"},{"text":"(","kind":"text"},{"text":"Pushwoosh","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)Pushwoosh"},{"text":", ","kind":"text"},{"text":"onMessageOpened","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)PWMessage","text":"PWMessage","kind":"typeIdentifier"},{"kind":"text","text":")"}],"symbolKind":"method"},"sections":[],"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh":{"navigatorTitle":[{"kind":"identifier","text":"Pushwoosh"}],"abstract":[{"type":"text","text":"Main SDK interface for push notification management."}],"url":"\/documentation\/pushwooshframework\/pushwoosh","title":"Pushwoosh","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Pushwoosh","kind":"identifier"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/delegate":{"role":"symbol","url":"\/documentation\/pushwooshframework\/pushwoosh\/delegate","abstract":[{"text":"Delegate that receives push notification events.","type":"text"}],"title":"delegate","navigatorTitle":[{"kind":"identifier","text":"delegate"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/delegate","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":": (any ","kind":"text"},{"kind":"typeIdentifier","text":"PWMessagingDelegate","preciseIdentifier":"c:objc(pl)PWMessagingDelegate"},{"text":")?","kind":"text"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWMessagingDelegate":{"role":"symbol","url":"\/documentation\/pushwooshframework\/pwmessagingdelegate","abstract":[{"type":"text","text":"Delegate protocol for handling push notification events."}],"title":"PWMessagingDelegate","navigatorTitle":[{"text":"PWMessagingDelegate","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWMessagingDelegate","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"PWMessagingDelegate","kind":"identifier"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"type":"topic","abstract":[{"text":"Push notification SDK for iOS applications.","type":"text"}],"title":"PushwooshFramework","kind":"symbol","url":"\/documentation\/pushwooshframework","role":"collection","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWMessagingDelegate/pushwoosh(_:onMessageOpened:)":{"navigatorTitle":[{"kind":"identifier","text":"pushwoosh:onMessageOpened:"}],"role":"symbol","title":"pushwoosh(_:onMessageOpened:)","abstract":[{"text":"Called when the user taps on a push notification.","type":"text"}],"type":"topic","url":"\/documentation\/pushwooshframework\/pwmessagingdelegate\/pushwoosh(_:onmessageopened:)","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWMessagingDelegate\/pushwoosh(_:onMessageOpened:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"pushwoosh"},{"text":"(","kind":"text"},{"text":"Pushwoosh","preciseIdentifier":"c:objc(cs)Pushwoosh","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"onMessageOpened","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)PWMessage","text":"PWMessage","kind":"typeIdentifier"},{"kind":"text","text":")"}],"kind":"symbol"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWMessagingDelegate/pushwoosh(_:onMessageReceived:)":{"role":"symbol","url":"\/documentation\/pushwooshframework\/pwmessagingdelegate\/pushwoosh(_:onmessagereceived:)","abstract":[{"type":"text","text":"Called when the application receives a push notification."}],"title":"pushwoosh(_:onMessageReceived:)","navigatorTitle":[{"text":"pushwoosh:onMessageReceived:","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWMessagingDelegate\/pushwoosh(_:onMessageReceived:)","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pushwoosh"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"Pushwoosh","preciseIdentifier":"c:objc(cs)Pushwoosh"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"onMessageReceived"},{"kind":"text","text":": "},{"text":"PWMessage","preciseIdentifier":"c:objc(cs)PWMessage","kind":"typeIdentifier"},{"text":")","kind":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"pushwoosh:onMessageOpened:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"pushwoosh:onMessageOpened:"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":[{"title":"Related Documentation","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWMessagingDelegate\/pushwoosh(_:onMessageReceived:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/delegate"]},{"generated":true,"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWMessagingDelegate\/pushwoosh(_:onMessageReceived:)"],"title":"Handling Notifications"}],"op":"replace","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"text":"pushwoosh:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh","text":"Pushwoosh","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)Pushwoosh"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"pushwoosh"},{"kind":"text","text":" "},{"kind":"identifier","text":"onMessageOpened:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PWMessage","text":"PWMessage"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"message"},{"text":";","kind":"text"}]}]}},{"value":"Pushwoosh","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh\/title","op":"replace"},{"op":"replace","value":[{"text":"Pushwoosh","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh\/fragments"},{"value":"delegate","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1delegate\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1delegate\/fragments","value":[{"text":"delegate","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWMessagingDelegate\/title","value":"PWMessagingDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWMessagingDelegate\/fragments","value":[{"kind":"identifier","text":"PWMessagingDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWMessagingDelegate~1pushwoosh(_:onMessageOpened:)\/title","value":"pushwoosh:onMessageOpened:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"pushwoosh:onMessageOpened:"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWMessagingDelegate~1pushwoosh(_:onMessageOpened:)\/fragments"},{"op":"replace","value":"pushwoosh:onMessageReceived:","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWMessagingDelegate~1pushwoosh(_:onMessageReceived:)\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWMessagingDelegate~1pushwoosh(_:onMessageReceived:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"pushwoosh:onMessageReceived:"}]}]}]}