{"abstract":[{"type":"text","text":"The caller’s display name or identifier."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"callerName"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","text":"Discussion","level":2,"anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This string is displayed in the CallKit incoming call UI to identify who is calling."},{"text":" ","type":"text"},{"type":"text","text":"The format should match the "},{"type":"codeVoice","code":"handleType"},{"text":" (e.g., phone number, email, or username).","type":"text"}]},{"style":"note","name":"Note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"This value is shown prominently in the CallKit UI, so ensure it’s user-friendly and recognizable."}]}],"type":"aside"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPMessage\/callerName","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPMessage"]]},"metadata":{"modules":[{"name":"PushwooshVoIP"}],"roleHeading":"Instance Property","title":"callerName","navigatorTitle":[{"kind":"identifier","text":"callerName"}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"callerName","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"symbolKind":"property","role":"symbol","externalID":"c:@M@PushwooshVoIP@objc(cs)PWVoIPMessage(py)callerName"},"variants":[{"paths":["\/documentation\/pushwooshvoip\/pwvoipmessage\/callername"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pushwooshvoip\/pwvoipmessage\/callername"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPMessage":{"abstract":[{"type":"text","text":"An encapsulation of VoIP push notification payload data."}],"url":"\/documentation\/pushwooshvoip\/pwvoipmessage","navigatorTitle":[{"kind":"identifier","text":"PWVoIPMessage"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPMessage","title":"PWVoIPMessage","role":"symbol","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PWVoIPMessage","kind":"identifier"}]},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPMessage/callerName":{"title":"callerName","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"callerName"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"callerName","kind":"identifier"}],"abstract":[{"type":"text","text":"The caller’s display name or identifier."}],"identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPMessage\/callerName","kind":"symbol","url":"\/documentation\/pushwooshvoip\/pwvoipmessage\/callername","type":"topic"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP":{"abstract":[{"type":"text","text":"VoIP push notifications with native call UI for iOS applications."}],"url":"\/documentation\/pushwooshvoip","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP","title":"PushwooshVoIP","role":"collection","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"callerName"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","value":[{"text":"callerName","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" * ","kind":"text"},{"text":"callerName","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPMessage\/title","value":"PWVoIPMessage"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPMessage\/fragments","op":"replace","value":[{"text":"PWVoIPMessage","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPMessage~1callerName\/title","op":"replace","value":"callerName"},{"value":[{"kind":"identifier","text":"callerName"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPMessage~1callerName\/fragments","op":"replace"}]}]}