{"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPMessage\/cancelCall","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshvoip\/pwvoipmessage\/cancelcall"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshvoip\/pwvoipmessage\/cancelcall"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cancelCall"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]}],"kind":"declarations"},{"content":[{"anchor":"discussion","text":"Discussion","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"When "},{"type":"codeVoice","code":"true"},{"type":"text","text":", this VoIP push represents a cancellation of a previously sent incoming call."},{"text":" ","type":"text"},{"text":"The SDK uses the ","type":"text"},{"code":"callId","type":"codeVoice"},{"text":" field to match this cancellation with the active call and automatically","type":"text"},{"type":"text","text":" "},{"type":"text","text":"dismisses the CallKit UI with "},{"code":"CXCallEndedReason.remoteEnded","type":"codeVoice"},{"type":"text","text":"."}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"For regular incoming calls, this value is ","type":"text"},{"type":"codeVoice","code":"false"},{"text":". Only cancellation pushes should set this to ","type":"text"},{"code":"true","type":"codeVoice"},{"type":"text","text":"."}]}],"name":"Note","type":"aside","style":"note"}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPMessage"]]},"abstract":[{"type":"text","text":"Indicates whether this push is a call cancellation request."}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"cancelCall"}],"symbolKind":"property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cancelCall","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"modules":[{"name":"PushwooshVoIP"}],"roleHeading":"Instance Property","externalID":"c:@M@PushwooshVoIP@objc(cs)PWVoIPMessage(py)cancelCall","title":"cancelCall","role":"symbol"},"references":{"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP":{"title":"PushwooshVoIP","url":"\/documentation\/pushwooshvoip","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP","role":"collection","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"VoIP push notifications with native call UI for iOS applications."}]},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPMessage":{"navigatorTitle":[{"text":"PWVoIPMessage","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPMessage","role":"symbol","abstract":[{"text":"An encapsulation of VoIP push notification payload data.","type":"text"}],"kind":"symbol","title":"PWVoIPMessage","url":"\/documentation\/pushwooshvoip\/pwvoipmessage","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PWVoIPMessage","kind":"identifier"}]},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPMessage/cancelCall":{"title":"cancelCall","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPMessage\/cancelCall","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cancelCall"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"cancelCall","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"text":"Indicates whether this push is a call cancellation request.","type":"text"}],"url":"\/documentation\/pushwooshvoip\/pwvoipmessage\/cancelcall","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"cancelCall","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"cancelCall"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"cancelCall","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"op":"replace","value":"PWVoIPMessage","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPMessage\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPMessage\/fragments","value":[{"text":"PWVoIPMessage","kind":"identifier"}],"op":"replace"},{"value":"cancelCall","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPMessage~1cancelCall\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPMessage~1cancelCall\/fragments","op":"replace","value":[{"kind":"identifier","text":"cancelCall"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}