{"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPMessage\/handleType","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPMessage"]]},"kind":"symbol","metadata":{"title":"handleType","roleHeading":"Instance Property","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"handleType"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@PushwooshVoIP@E@PWVoIPHandleType","text":"PWVoIPHandleType","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"handleType"}],"modules":[{"name":"PushwooshVoIP"}],"externalID":"c:@M@PushwooshVoIP@objc(cs)PWVoIPMessage(py)handleType","symbolKind":"property"},"abstract":[{"text":"The display format for caller information.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"handleType","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@PushwooshVoIP@E@PWVoIPHandleType","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPHandleType","kind":"typeIdentifier","text":"PWVoIPHandleType"}]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","anchor":"discussion","text":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Determines how the caller’s identifier is displayed in CallKit UI. Choose the appropriate format"},{"type":"text","text":" "},{"text":"based on your caller information type.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Available values:"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":".generic"},{"text":" - Generic identifier like username or custom ID (default if not specified)","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":".phoneNumber"},{"type":"text","text":" - Phone number with automatic system formatting"}]}]},{"content":[{"inlineContent":[{"type":"codeVoice","code":".email"},{"type":"text","text":" - Email address format"}],"type":"paragraph"}]}]},{"type":"aside","style":"note","name":"Note","content":[{"inlineContent":[{"type":"text","text":"The format affects how CallKit displays the caller information in the system UI."}],"type":"paragraph"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshvoip\/pwvoipmessage\/handletype"]},{"paths":["\/documentation\/pushwooshvoip\/pwvoipmessage\/handletype"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP":{"abstract":[{"text":"VoIP push notifications with native call UI for iOS applications.","type":"text"}],"title":"PushwooshVoIP","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP","kind":"symbol","role":"collection","url":"\/documentation\/pushwooshvoip"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPMessage":{"role":"symbol","abstract":[{"text":"An encapsulation of VoIP push notification payload data.","type":"text"}],"kind":"symbol","url":"\/documentation\/pushwooshvoip\/pwvoipmessage","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PWVoIPMessage"}],"title":"PWVoIPMessage","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPMessage","navigatorTitle":[{"text":"PWVoIPMessage","kind":"identifier"}],"type":"topic"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPMessage/handleType":{"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"handleType"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@PushwooshVoIP@E@PWVoIPHandleType","text":"PWVoIPHandleType","kind":"typeIdentifier"}],"kind":"symbol","role":"symbol","abstract":[{"text":"The display format for caller information.","type":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPMessage\/handleType","url":"\/documentation\/pushwooshvoip\/pwvoipmessage\/handletype","title":"handleType","type":"topic","navigatorTitle":[{"text":"handleType","kind":"identifier"}]},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPHandleType":{"role":"symbol","abstract":[{"type":"text","text":"Display format for caller information in CallKit UI."}],"url":"\/documentation\/pushwooshvoip\/pwvoiphandletype","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PWVoIPHandleType"}],"title":"PWVoIPHandleType","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPHandleType","navigatorTitle":[{"text":"PWVoIPHandleType","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","value":"handleType","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"handleType"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PWVoIPHandleType","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPHandleType","kind":"typeIdentifier","preciseIdentifier":"c:@M@PushwooshVoIP@E@PWVoIPHandleType"},{"kind":"text","text":" "},{"text":"handleType","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"PWVoIPMessage","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPMessage\/title"},{"op":"replace","value":[{"text":"PWVoIPMessage","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPMessage\/fragments"},{"op":"replace","value":"handleType","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPMessage~1handleType\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPMessage~1handleType\/fragments","op":"replace","value":[{"text":"handleType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPHandleType\/title","value":"PWVoIPHandleType"},{"value":[{"kind":"identifier","text":"PWVoIPHandleType"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPHandleType\/fragments","op":"replace"}]}]}