{"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPMessage\/hasVideo"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPMessage"]]},"abstract":[{"text":"A Boolean value that indicates whether the call supports video.","type":"text"}],"sections":[],"metadata":{"externalID":"c:@M@PushwooshVoIP@objc(cs)PWVoIPMessage(py)hasVideo","roleHeading":"Instance Property","modules":[{"name":"PushwooshVoIP"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hasVideo"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"kind":"identifier","text":"hasVideo"}],"title":"hasVideo","symbolKind":"property","role":"symbol"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"hasVideo","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"text":"Discussion","anchor":"discussion","type":"heading","level":2},{"inlineContent":[{"text":"When ","type":"text"},{"type":"codeVoice","code":"true"},{"type":"text","text":", the call is presented as a video call in CallKit UI with appropriate video call icons."},{"text":" ","type":"text"},{"type":"text","text":"When "},{"type":"codeVoice","code":"false"},{"type":"text","text":", the call is presented as an audio-only call."}],"type":"paragraph"},{"style":"note","type":"aside","name":"Note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"This property is mutable to allow updating video capability during call setup if needed."}]}]}],"kind":"content"}],"variants":[{"paths":["\/documentation\/pushwooshvoip\/pwvoipmessage\/hasvideo"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pushwooshvoip\/pwvoipmessage\/hasvideo"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPMessage/hasVideo":{"identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPMessage\/hasVideo","abstract":[{"type":"text","text":"A Boolean value that indicates whether the call supports video."}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"hasVideo"}],"title":"hasVideo","url":"\/documentation\/pushwooshvoip\/pwvoipmessage\/hasvideo","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"hasVideo","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP":{"type":"topic","abstract":[{"type":"text","text":"VoIP push notifications with native call UI for iOS applications."}],"title":"PushwooshVoIP","role":"collection","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP","kind":"symbol","url":"\/documentation\/pushwooshvoip"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPMessage":{"identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPMessage","abstract":[{"text":"An encapsulation of VoIP push notification payload data.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"PWVoIPMessage","kind":"identifier"}],"title":"PWVoIPMessage","url":"\/documentation\/pushwooshvoip\/pwvoipmessage","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PWVoIPMessage"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","value":"hasVideo","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"hasVideo","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"hasVideo","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"value":"hasVideo","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPMessage~1hasVideo\/title","op":"replace"},{"value":[{"kind":"identifier","text":"hasVideo"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPMessage~1hasVideo\/fragments","op":"replace"},{"op":"replace","value":"PWVoIPMessage","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPMessage\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPMessage\/fragments","value":[{"kind":"identifier","text":"PWVoIPMessage"}]}]}]}