{"metadata":{"externalID":"c:@M@PushwooshVoIP@objc(cs)PWVoIPMessage(py)rawPayload","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rawPayload"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"text":"]","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"rawPayload","kind":"identifier"}],"modules":[{"name":"PushwooshVoIP"}],"title":"rawPayload","symbolKind":"property","roleHeading":"Instance Property"},"abstract":[{"type":"text","text":"The raw push notification payload."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshvoip\/pwvoipmessage\/rawpayload"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshvoip\/pwvoipmessage\/rawpayload"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"rawPayload","kind":"identifier"},{"kind":"text","text":": ["},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"level":2,"type":"heading","text":"Discussion","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Contains the complete original payload received from the VoIP push notification, with "},{"code":"NSNull","type":"codeVoice"},{"text":" values","type":"text"},{"type":"text","text":" "},{"type":"text","text":"removed. Use this to access any custom fields you included in your VoIP push that are not part of"},{"type":"text","text":" "},{"text":"the standard PWVoIPMessage properties.","type":"text"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"All standard properties (callerName, hasVideo, etc.) are parsed from this payload during initialization."}]}],"type":"aside","style":"note","name":"Note"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPMessage"]]},"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPMessage\/rawPayload","interfaceLanguage":"swift"},"references":{"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPMessage":{"identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPMessage","title":"PWVoIPMessage","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PWVoIPMessage"}],"role":"symbol","abstract":[{"type":"text","text":"An encapsulation of VoIP push notification payload data."}],"url":"\/documentation\/pushwooshvoip\/pwvoipmessage","navigatorTitle":[{"text":"PWVoIPMessage","kind":"identifier"}],"type":"topic"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPMessage/rawPayload":{"url":"\/documentation\/pushwooshvoip\/pwvoipmessage\/rawpayload","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPMessage\/rawPayload","title":"rawPayload","abstract":[{"type":"text","text":"The raw push notification payload."}],"role":"symbol","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rawPayload"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier","text":"AnyHashable"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"]","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"rawPayload"}]},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP":{"kind":"symbol","url":"\/documentation\/pushwooshvoip","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP","abstract":[{"type":"text","text":"VoIP push notifications with native call UI for iOS applications."}],"role":"collection","title":"PushwooshVoIP"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"rawPayload","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"rawPayload","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSDictionary","kind":"typeIdentifier","text":"NSDictionary"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"rawPayload"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPMessage\/title","value":"PWVoIPMessage","op":"replace"},{"value":[{"text":"PWVoIPMessage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPMessage\/fragments"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPMessage~1rawPayload\/title","op":"replace","value":"rawPayload"},{"value":[{"text":"rawPayload","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPMessage~1rawPayload\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}