{"kind":"symbol","metadata":{"modules":[{"name":"PushwooshVoIP"}],"symbolKind":"property","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"uuid"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"role":"symbol","externalID":"c:@M@PushwooshVoIP@objc(cs)PWVoIPMessage(py)uuid","navigatorTitle":[{"text":"uuid","kind":"identifier"}],"title":"uuid"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"uuid","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This UUID is used by CallKit to track the call throughout its lifecycle. The SDK automatically generates"},{"text":" ","type":"text"},{"type":"text","text":"this identifier when a VoIP push is received, or uses the value from the payload if provided."}]},{"content":[{"inlineContent":[{"type":"text","text":"This property is mutable to allow updating the UUID if needed during call setup."}],"type":"paragraph"}],"style":"note","name":"Note","type":"aside"}]}],"variants":[{"paths":["\/documentation\/pushwooshvoip\/pwvoipmessage\/uuid"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshvoip\/pwvoipmessage\/uuid"]}],"abstract":[{"text":"The unique identifier for the call.","type":"text"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPMessage"]]},"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPMessage\/uuid","interfaceLanguage":"swift"},"references":{"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPMessage":{"kind":"symbol","navigatorTitle":[{"text":"PWVoIPMessage","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPMessage","abstract":[{"type":"text","text":"An encapsulation of VoIP push notification payload data."}],"title":"PWVoIPMessage","role":"symbol","url":"\/documentation\/pushwooshvoip\/pwvoipmessage","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PWVoIPMessage","kind":"identifier"}],"type":"topic"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP":{"kind":"symbol","title":"PushwooshVoIP","type":"topic","abstract":[{"text":"VoIP push notifications with native call UI for iOS applications.","type":"text"}],"url":"\/documentation\/pushwooshvoip","role":"collection","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPMessage/uuid":{"url":"\/documentation\/pushwooshvoip\/pwvoipmessage\/uuid","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"uuid"}],"title":"uuid","abstract":[{"text":"The unique identifier for the call.","type":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPMessage\/uuid","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"uuid","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"uuid"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","value":[{"text":"uuid","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"uuid"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPMessage\/title","op":"replace","value":"PWVoIPMessage"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPMessage\/fragments","value":[{"kind":"identifier","text":"PWVoIPMessage"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPMessage~1uuid\/title","value":"uuid"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPMessage~1uuid\/fragments","value":[{"kind":"identifier","text":"uuid"}]}]}]}