{"sections":[],"seeAlsoSections":[{"generated":true,"title":"Getting Started","identifiers":["doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/GettingStarted"]}],"variants":[{"paths":["\/documentation\/pushwooshliveactivities\/examples"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshliveactivities\/examples"]}],"primaryContentSections":[{"content":[{"anchor":"Overview","text":"Overview","level":2,"type":"heading"},{"inlineContent":[{"text":"This guide provides working code examples for typical use cases with PushwooshLiveActivities.","type":"text"}],"type":"paragraph"},{"level":2,"type":"heading","text":"Delivery Tracking","anchor":"Delivery-Tracking"},{"level":3,"anchor":"Activity-Attributes","type":"heading","text":"Activity Attributes"},{"code":["import ActivityKit","import PushwooshLiveActivities","","struct DeliveryActivityAttributes: PushwooshLiveActivityAttributes {","    var pushwoosh: PushwooshLiveActivityAttributeData","","    var orderNumber: String","    var driverName: String","    var deliveryAddress: String","","    struct ContentState: PushwooshLiveActivityContentState {","        var pushwoosh: PushwooshLiveActivityContentStateData?","","        enum DeliveryStatus: String, Codable {","            case preparing","            case enRoute","            case nearBy","            case delivered","        }","","        var status: DeliveryStatus","        var estimatedArrival: Date","        var currentLocation: String","    }","}"],"type":"codeListing","syntax":"swift"},{"text":"Starting Delivery Tracking","anchor":"Starting-Delivery-Tracking","level":3,"type":"heading"},{"syntax":"swift","code":["import ActivityKit","import PushwooshLiveActivities","","func startDeliveryTracking(orderNumber: String, driverName: String, address: String) {","    guard #available(iOS 16.1, *) else { return }","","    let attributes = DeliveryActivityAttributes(","        pushwoosh: .create(activityId: \"delivery-\\(orderNumber)\"),","        orderNumber: orderNumber,","        driverName: driverName,","        deliveryAddress: address","    )","","    let contentState = DeliveryActivityAttributes.ContentState(","        pushwoosh: nil,","        status: .preparing,","        estimatedArrival: Date().addingTimeInterval(2700),","        currentLocation: \"Restaurant\"","    )","","    do {","        let activity = try Activity<DeliveryActivityAttributes>.request(","            attributes: attributes,","            contentState: contentState,","            pushType: .token","        )","","        print(\"Delivery tracking started: \\(activity.id)\")","    } catch {","        print(\"Failed to start delivery tracking: \\(error)\")","    }","}"],"type":"codeListing"},{"text":"Ending Delivery Tracking","anchor":"Ending-Delivery-Tracking","type":"heading","level":3},{"code":["import ActivityKit","import PushwooshLiveActivities","","func endDeliveryTracking() async {","    guard #available(iOS 16.1, *) else { return }","","    for activity in Activity<DeliveryActivityAttributes>.activities {","        await activity.end(nil, dismissalPolicy: .immediate)","    }","","    Pushwoosh.LiveActivities.stopLiveActivity()","}"],"type":"codeListing","syntax":"swift"},{"type":"heading","level":3,"text":"Push Payload for Delivery Updates","anchor":"Push-Payload-for-Delivery-Updates"},{"syntax":"json","code":["{","  \"aps\": {","    \"alert\": \"Your order is on the way!\"","  },","  \"live_activity\": {","    \"event\": \"update\",","    \"content-state\": {","      \"status\": \"enRoute\",","      \"estimatedArrival\": \"2024-11-06T15:45:00Z\",","      \"currentLocation\": \"Main Street\"","    },","    \"attributes-type\": \"DeliveryActivityAttributes\"","  }","}"],"type":"codeListing"},{"type":"heading","level":2,"anchor":"Sports-Score-Tracking","text":"Sports Score Tracking"},{"type":"heading","anchor":"Activity-Attributes","level":3,"text":"Activity Attributes"},{"code":["import ActivityKit","import PushwooshLiveActivities","","struct GameActivityAttributes: PushwooshLiveActivityAttributes {","    var pushwoosh: PushwooshLiveActivityAttributeData","","    var homeTeam: String","    var awayTeam: String","    var league: String","","    struct ContentState: PushwooshLiveActivityContentState {","        var pushwoosh: PushwooshLiveActivityContentStateData?","","        var homeScore: Int","        var awayScore: Int","        var period: String","        var timeRemaining: String","    }","}"],"type":"codeListing","syntax":"swift"},{"type":"heading","text":"Starting Game Tracking","anchor":"Starting-Game-Tracking","level":3},{"syntax":"swift","code":["import ActivityKit","import PushwooshLiveActivities","","func startGameTracking(gameId: String, homeTeam: String, awayTeam: String) {","    guard #available(iOS 16.1, *) else { return }","","    let attributes = GameActivityAttributes(","        pushwoosh: .create(activityId: \"game-\\(gameId)\"),","        homeTeam: homeTeam,","        awayTeam: awayTeam,","        league: \"NBA\"","    )","","    let contentState = GameActivityAttributes.ContentState(","        pushwoosh: nil,","        homeScore: 0,","        awayScore: 0,","        period: \"1st Quarter\",","        timeRemaining: \"12:00\"","    )","","    do {","        _ = try Activity<GameActivityAttributes>.request(","            attributes: attributes,","            contentState: contentState,","            pushType: .token","        )","    } catch {","        print(\"Failed to start game tracking: \\(error)\")","    }","}"],"type":"codeListing"},{"text":"Push Payload for Score Updates","anchor":"Push-Payload-for-Score-Updates","level":3,"type":"heading"},{"code":["{","  \"aps\": {","    \"alert\": \"Lakers scored!\"","  },","  \"live_activity\": {","    \"event\": \"update\",","    \"content-state\": {","      \"homeScore\": 24,","      \"awayScore\": 18,","      \"period\": \"2nd Quarter\",","      \"timeRemaining\": \"8:45\"","    },","    \"attributes-type\": \"GameActivityAttributes\"","  }","}"],"type":"codeListing","syntax":"json"},{"level":2,"anchor":"Ride-Sharing","text":"Ride Sharing","type":"heading"},{"text":"Activity Attributes","level":3,"anchor":"Activity-Attributes","type":"heading"},{"code":["import ActivityKit","import PushwooshLiveActivities","","struct RideActivityAttributes: PushwooshLiveActivityAttributes {","    var pushwoosh: PushwooshLiveActivityAttributeData","","    var driverName: String","    var vehicleModel: String","    var licensePlate: String","    var destination: String","","    struct ContentState: PushwooshLiveActivityContentState {","        var pushwoosh: PushwooshLiveActivityContentStateData?","","        enum RideStatus: String, Codable {","            case driverEnRoute","            case arrived","            case riding","            case completed","        }","","        var status: RideStatus","        var estimatedArrival: Date","        var distanceRemaining: String","    }","}"],"type":"codeListing","syntax":"swift"},{"type":"heading","text":"Starting Ride Tracking","anchor":"Starting-Ride-Tracking","level":3},{"type":"codeListing","syntax":"swift","code":["import ActivityKit","import PushwooshLiveActivities","","func startRideTracking(rideId: String, driver: String, vehicle: String, plate: String, destination: String) {","    guard #available(iOS 16.1, *) else { return }","","    let attributes = RideActivityAttributes(","        pushwoosh: .create(activityId: \"ride-\\(rideId)\"),","        driverName: driver,","        vehicleModel: vehicle,","        licensePlate: plate,","        destination: destination","    )","","    let contentState = RideActivityAttributes.ContentState(","        pushwoosh: nil,","        status: .driverEnRoute,","        estimatedArrival: Date().addingTimeInterval(300),","        distanceRemaining: \"0.8 mi\"","    )","","    do {","        _ = try Activity<RideActivityAttributes>.request(","            attributes: attributes,","            contentState: contentState,","            pushType: .token","        )","    } catch {","        print(\"Failed to start ride tracking: \\(error)\")","    }","}"]},{"anchor":"Push-to-Start-iOS-172+","type":"heading","text":"Push-to-Start (iOS 17.2+)","level":2},{"level":3,"anchor":"Setup","type":"heading","text":"Setup"},{"type":"codeListing","code":["import UIKit","import PushwooshFramework","import PushwooshLiveActivities","","@main","class AppDelegate: UIResponder, UIApplicationDelegate {","","    func application(","        _ application: UIApplication,","        didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?","    ) -> Bool {","","        if #available(iOS 17.2, *) {","            Pushwoosh.LiveActivities.setup(DeliveryActivityAttributes.self)","        }","","        return true","    }","}"],"syntax":"swift"},{"type":"heading","level":3,"text":"Push-to-Start Payload","anchor":"Push-to-Start-Payload"},{"code":["{","  \"aps\": {","    \"alert\": \"Your order is ready!\",","    \"content-state\": {","      \"status\": \"preparing\",","      \"estimatedArrival\": \"2024-11-06T15:30:00Z\",","      \"currentLocation\": \"Restaurant\"","    },","    \"attributes\": {","      \"orderNumber\": \"12345\",","      \"driverName\": \"John\",","      \"deliveryAddress\": \"123 Main St\"","    },","    \"attributes-type\": \"DeliveryActivityAttributes\",","    \"event\": \"start\"","  }","}"],"syntax":"json","type":"codeListing"},{"text":"Default Mode Examples","level":2,"anchor":"Default-Mode-Examples","type":"heading"},{"level":3,"type":"heading","text":"Simple Notification Counter","anchor":"Simple-Notification-Counter"},{"code":["import PushwooshLiveActivities","","func startNotificationCounter() {","    guard #available(iOS 16.1, *) else { return }","","    let attributes = [\"type\": \"notifications\"]","    let content = [","        \"title\": \"Notifications\",","        \"count\": 1","    ]","","    Pushwoosh.LiveActivities.defaultStart(","        \"notification-counter\",","        attributes: attributes,","        content: content","    )","}"],"syntax":"swift","type":"codeListing"},{"level":3,"type":"heading","text":"Push Payload","anchor":"Push-Payload"},{"code":["{","  \"aps\": {","    \"alert\": \"New notification\"","  },","  \"live_activity\": {","    \"event\": \"update\",","    \"content-state\": {","      \"data\": {","        \"title\": \"Notifications\",","        \"count\": 5","      }","    },","    \"attributes-type\": \"DefaultLiveActivityAttributes\"","  }","}"],"type":"codeListing","syntax":"json"},{"type":"heading","anchor":"Timer-with-Progress","level":3,"text":"Timer with Progress"},{"code":["import PushwooshLiveActivities","","func startTimer(duration: Int) {","    guard #available(iOS 16.1, *) else { return }","","    let endTime = Date().addingTimeInterval(TimeInterval(duration))","","    let attributes = [\"timerType\": \"workout\"]","    let content = [","        \"title\": \"Workout Timer\",","        \"endTime\": ISO8601DateFormatter().string(from: endTime),","        \"progress\": 0.0","    ] as [String : Any]","","    Pushwoosh.LiveActivities.defaultStart(","        \"workout-timer\",","        attributes: attributes,","        content: content","    )","}"],"type":"codeListing","syntax":"swift"},{"anchor":"Handling-Multiple-Activities","level":2,"text":"Handling Multiple Activities","type":"heading"},{"level":3,"type":"heading","anchor":"Managing-Multiple-Live-Activities","text":"Managing Multiple Live Activities"},{"syntax":"swift","code":["import ActivityKit","import PushwooshLiveActivities","","func listActiveDeliveries() {","    guard #available(iOS 16.1, *) else { return }","","    for activity in Activity<DeliveryActivityAttributes>.activities {","        print(\"Order: \\(activity.attributes.orderNumber)\")","        print(\"Status: \\(activity.contentState.status)\")","        print(\"Activity ID: \\(activity.attributes.pushwoosh.activityId)\")","    }","}","","func endSpecificDelivery(activityId: String) async {","    guard #available(iOS 16.1, *) else { return }","","    for activity in Activity<DeliveryActivityAttributes>.activities {","        if activity.attributes.pushwoosh.activityId == activityId {","            await activity.end(nil, dismissalPolicy: .immediate)","            Pushwoosh.LiveActivities.stopLiveActivity(activityId: activityId)","            break","        }","    }","}"],"type":"codeListing"},{"anchor":"Error-Handling","text":"Error Handling","level":2,"type":"heading"},{"text":"Handling Activity Request Errors","anchor":"Handling-Activity-Request-Errors","type":"heading","level":3},{"code":["import ActivityKit","import PushwooshLiveActivities","","func startActivityWithErrorHandling() {","    guard #available(iOS 16.1, *) else {","        print(\"Live Activities require iOS 16.1+\")","        return","    }","","    let attributes = DeliveryActivityAttributes(","        pushwoosh: .create(activityId: \"delivery-123\"),","        orderNumber: \"123\",","        driverName: \"John\",","        deliveryAddress: \"123 Main St\"","    )","","    let contentState = DeliveryActivityAttributes.ContentState(","        pushwoosh: nil,","        status: .preparing,","        estimatedArrival: Date().addingTimeInterval(1800),","        currentLocation: \"Restaurant\"","    )","","    do {","        let activity = try Activity<DeliveryActivityAttributes>.request(","            attributes: attributes,","            contentState: contentState,","            pushType: .token","        )","        print(\"Activity started: \\(activity.id)\")","    } catch let error as ActivityAuthorizationError {","        print(\"Authorization error: \\(error.localizedDescription)\")","    } catch {","        print(\"Failed to start activity: \\(error.localizedDescription)\")","    }","}"],"syntax":"swift","type":"codeListing"},{"anchor":"Next-Steps","text":"Next Steps","type":"heading","level":2},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"identifier":"doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/GettingStarted","type":"reference"},{"type":"text","text":" - Setup guide"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/PushwooshLiveActivityAttributes"},{"text":" - Custom attributes protocol","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/DefaultLiveActivityAttributes"},{"type":"text","text":" - Default mode attributes"}]}]}],"type":"unorderedList"}],"kind":"content"}],"kind":"article","hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"modules":[{"name":"PushwooshLiveActivities"}],"roleHeading":"Article","title":"Code Examples","role":"article"},"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/Examples","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Practical examples for common Live Activities integration scenarios."}],"references":{"doc://com.pushwoosh.PushwooshLiveActivities/documentation/PushwooshLiveActivities/GettingStarted":{"identifier":"doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/GettingStarted","abstract":[{"type":"text","text":"Set up iOS Live Activities with push notification updates."}],"role":"article","kind":"article","title":"Getting Started","url":"\/documentation\/pushwooshliveactivities\/gettingstarted","type":"topic"},"doc://com.pushwoosh.PushwooshLiveActivities/documentation/PushwooshLiveActivities":{"url":"\/documentation\/pushwooshliveactivities","identifier":"doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities","kind":"symbol","role":"collection","abstract":[{"text":"Real-time iOS Live Activities powered by push notifications.","type":"text"}],"type":"topic","title":"PushwooshLiveActivities"},"doc://com.pushwoosh.PushwooshLiveActivities/documentation/PushwooshLiveActivities/PushwooshLiveActivityAttributes":{"kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/PushwooshLiveActivityAttributes","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PushwooshLiveActivityAttributes"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"PushwooshLiveActivityAttributes","kind":"identifier"}],"url":"\/documentation\/pushwooshliveactivities\/pushwooshliveactivityattributes","title":"PushwooshLiveActivityAttributes","abstract":[{"type":"text","text":"Protocol for defining custom Live Activity attributes."}]},"doc://com.pushwoosh.PushwooshLiveActivities/documentation/PushwooshLiveActivities/DefaultLiveActivityAttributes":{"abstract":[{"type":"text","text":"A flexible structure for defining Live Activity content dynamically."}],"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"DefaultLiveActivityAttributes","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"DefaultLiveActivityAttributes","kind":"identifier"}],"url":"\/documentation\/pushwooshliveactivities\/defaultliveactivityattributes","title":"DefaultLiveActivityAttributes","identifier":"doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/DefaultLiveActivityAttributes"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":null,"op":"add","path":"\/topicSections"},{"value":[{"generated":true,"identifiers":["doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/GettingStarted"],"title":"Getting Started"}],"path":"\/seeAlsoSections","op":"replace"}]}]}