{"metadata":{"roleHeading":"Article","modules":[{"name":"PushwooshLiveActivities"}],"role":"article","title":"Getting Started"},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/GettingStarted"},"kind":"article","schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities"]]},"primaryContentSections":[{"kind":"content","content":[{"level":2,"type":"heading","text":"Installation","anchor":"Installation"},{"type":"tabNavigator","tabs":[{"title":"Swift Package Manager","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"In Xcode, use the following URL to add the Pushwoosh dependency:"}]},{"syntax":null,"code":["https:\/\/github.com\/Pushwoosh\/Pushwoosh-XCFramework"],"type":"codeListing"},{"style":"note","name":"Note","type":"aside","content":[{"inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Important"}]},{"type":"text","text":": The modules PushwooshFramework, PushwooshCore, PushwooshBridge, and PushwooshLiveActivities are required."}],"type":"paragraph"}]}]},{"title":"CocoaPods","content":[{"inlineContent":[{"type":"text","text":"Add to your Podfile:"}],"type":"paragraph"},{"type":"codeListing","code":["pod 'PushwooshXCFramework'"],"syntax":"ruby"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Then run:"}]},{"syntax":"bash","type":"codeListing","code":["pod install"]}]}]},{"anchor":"Prerequisites","type":"heading","text":"Prerequisites","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Before you begin, ensure you have:"}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"text":"A Pushwoosh account","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"A Pushwoosh project set up in your account","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"An iOS platform configured in your Pushwoosh project with Token-Based Authentication","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Your Pushwoosh Application Code from the Control Panel","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"iOS 16.1+ deployment target (iOS 17.2+ for push-to-start feature)"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"PushwooshFramework, PushwooshCore, and PushwooshBridge frameworks integrated in your project"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A Widget Extension target in your Xcode project"}]}]}]},{"name":"Note","style":"note","content":[{"inlineContent":[{"type":"strong","inlineContent":[{"text":"Important","type":"text"}]},{"text":": Live Activities require iOS 16.1+. Push-to-start functionality requires iOS 17.2+. Only token-based configuration is supported (certificate-based is not supported).","type":"text"}],"type":"paragraph"}],"type":"aside"},{"level":2,"anchor":"Step-1-Add-Required-Capabilities","text":"Step 1: Add Required Capabilities","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"In Xcode:","type":"text"}]},{"items":[{"content":[{"inlineContent":[{"text":"Select your ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"app target"}]},{"type":"text","text":" (not widget extension)"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"Go to ","type":"text"},{"type":"strong","inlineContent":[{"text":"Signing & Capabilities","type":"text"}]}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Click "},{"type":"strong","inlineContent":[{"type":"text","text":"+ Capability"}]},{"type":"text","text":" and add "},{"type":"strong","inlineContent":[{"type":"text","text":"Push Notifications"}]}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Click ","type":"text"},{"type":"strong","inlineContent":[{"text":"+ Capability","type":"text"}]},{"type":"text","text":" and add "},{"type":"strong","inlineContent":[{"type":"text","text":"Background Modes"}]}]}]},{"content":[{"inlineContent":[{"type":"text","text":"In Background Modes, enable "},{"type":"strong","inlineContent":[{"text":"Remote notifications","type":"text"}]},{"text":" checkbox","type":"text"}],"type":"paragraph"}]}],"type":"orderedList"},{"anchor":"Step-2-Configure-Infoplist","text":"Step 2: Configure Info.plist","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"Add Live Activities support to your app’s Info.plist:"}],"type":"paragraph"},{"syntax":"xml","type":"codeListing","code":["<key>NSSupportsLiveActivities<\/key>","<true\/>"]},{"anchor":"Step-3-Create-Widget-Extension","level":2,"text":"Step 3: Create Widget Extension","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"If you don’t have a Widget Extension:","type":"text"}]},{"type":"orderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"In Xcode: "},{"type":"strong","inlineContent":[{"type":"text","text":"File → New → Target"}]}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Select ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"Widget Extension"}]}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Enable "},{"inlineContent":[{"type":"text","text":"Include Live Activity"}],"type":"strong"},{"type":"text","text":" checkbox"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Name it (e.g., “MyAppWidgets”)"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Add PushwooshLiveActivities to your Widget Extension target dependencies","type":"text"}]}]}]},{"type":"heading","level":2,"anchor":"Step-4-Define-Activity-Attributes","text":"Step 4: Define Activity Attributes"},{"type":"paragraph","inlineContent":[{"text":"Create a struct conforming to ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/PushwooshLiveActivityAttributes"},{"type":"text","text":":"}]},{"syntax":"swift","code":["import WidgetKit","import SwiftUI","import ActivityKit","import PushwooshFramework","import PushwooshLiveActivities","","struct FoodDeliveryAttributes: PushwooshLiveActivityAttributes {","    public struct ContentState: PushwooshLiveActivityContentState {","        var status: String","        var estimatedTime: String","        var emoji: String","        var pushwoosh: PushwooshLiveActivityContentStateData?","    }","","    var orderNumber: String","    var pushwoosh: PushwooshLiveActivityAttributeData","}"],"type":"codeListing"},{"level":2,"type":"heading","anchor":"Step-5-Create-Widget","text":"Step 5: Create Widget"},{"inlineContent":[{"text":"In your Widget Extension:","type":"text"}],"type":"paragraph"},{"type":"codeListing","syntax":"swift","code":["import WidgetKit","import SwiftUI","import ActivityKit","","@main","struct FoodDeliveryWidget: Widget {","    var body: some WidgetConfiguration {","        ActivityConfiguration(for: FoodDeliveryAttributes.self) { context in","            VStack(alignment: .leading, spacing: 8) {","                HStack {","                    Text(\"Order #\\(context.attributes.orderNumber)\")","                        .font(.headline)","                    Spacer()","                    Text(context.state.emoji)","                        .font(.title)","                }","","                Text(context.state.status)","                    .font(.subheadline)","","                HStack {","                    Image(systemName: \"clock\")","                    Text(context.state.estimatedTime)","                }","                .font(.caption)","            }","            .padding()","        } dynamicIsland: { context in","            DynamicIsland {","                DynamicIslandExpandedRegion(.leading) {","                    Text(context.state.emoji)","                        .font(.title)","                }","                DynamicIslandExpandedRegion(.trailing) {","                    Text(context.state.estimatedTime)","                        .font(.caption)","                }","                DynamicIslandExpandedRegion(.center) {","                    Text(context.state.status)","                        .font(.caption)","                }","            } compactLeading: {","                Text(context.state.emoji)","            } compactTrailing: {","                Text(context.state.estimatedTime)","                    .font(.caption2)","            } minimal: {","                Text(context.state.emoji)","            }","        }","    }","}"]},{"level":2,"text":"Step 6: Initialize in AppDelegate","type":"heading","anchor":"Step-6-Initialize-in-AppDelegate"},{"code":["import UIKit","import PushwooshFramework","import PushwooshLiveActivities","","@main","class AppDelegate: UIResponder, UIApplicationDelegate {","","    func application(","        _ application: UIApplication,","        didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?","    ) -> Bool {","","        if #available(iOS 16.1, *) {","            Pushwoosh.LiveActivities.setup(FoodDeliveryAttributes.self)","        }","","        return true","    }","}"],"syntax":"swift","type":"codeListing"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"codeVoice","code":"setup()"},{"text":" method handles the entire lifecycle of Live Activities:","type":"text"}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"text":"Automatically listens for push-to-start token updates (iOS 17.2+)","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Automatically listens for activity token updates"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Registers tokens with Pushwoosh server","type":"text"}]}]}]},{"type":"heading","level":2,"anchor":"Step-7-Create-Live-Activity-Manager","text":"Step 7: Create Live Activity Manager"},{"code":["import Foundation","import ActivityKit","import UIKit","import PushwooshFramework","import PushwooshLiveActivities","","class LiveActivityManager: NSObject, ObservableObject {","    public static let shared = LiveActivityManager()","    private var currentActivity: Activity<FoodDeliveryAttributes>?","","    func startActivity() {","        guard ActivityAuthorizationInfo().areActivitiesEnabled else {","            print(\"Live Activities are not enabled\")","            return","        }","","        do {","            let pushwooshData = PushwooshLiveActivityAttributeData(","                activityId: \"order_123\"","            )","","            let attribute = FoodDeliveryAttributes(","                orderNumber: \"1234567\",","                pushwoosh: pushwooshData","            )","","            let initialState = FoodDeliveryAttributes.ContentState(","                status: \"Preparing your meal\",","                estimatedTime: \"25 min\",","                emoji: \"👨‍🍳\",","                pushwoosh: nil","            )","","            let activity = try Activity<FoodDeliveryAttributes>.request(","                attributes: attribute,","                content: .init(state: initialState, staleDate: nil),","                pushType: .token","            )","","            self.currentActivity = activity","","            Task {","                for await pushToken in activity.pushTokenUpdates {","                    let pushTokenString = pushToken.reduce(\"\") {","                        $0 + String(format: \"%02x\", $1)","                    }","","                    print(\"Activity push token: \\(pushTokenString)\")","","                    Pushwoosh.LiveActivities.startLiveActivity(","                        token: pushTokenString,","                        activityId: \"order_123\"","                    )","                }","            }","        } catch {","            print(\"Start Activity Error: \\(error.localizedDescription)\")","        }","    }","","    func endActivity() async {","        guard let activity = currentActivity else { return }","","        await activity.end(nil, dismissalPolicy: .immediate)","","        Pushwoosh.LiveActivities.stopLiveActivity(activityId: \"order_123\")","    }","}"],"type":"codeListing","syntax":"swift"},{"text":"Step 8: Start Activity from UI","level":2,"anchor":"Step-8-Start-Activity-from-UI","type":"heading"},{"type":"codeListing","syntax":"swift","code":["import SwiftUI","","struct ContentView: View {","    var body: some View {","        VStack(spacing: 20) {","            Button(action: {","                LiveActivityManager.shared.startActivity()","            }) {","                Text(\"Start Live Activity\")","                    .foregroundColor(.white)","                    .padding()","                    .background(Color.blue)","                    .cornerRadius(10)","            }","","            Button(action: {","                Task {","                    await LiveActivityManager.shared.endActivity()","                }","            }) {","                Text(\"End Live Activity\")","                    .foregroundColor(.white)","                    .padding()","                    .background(Color.red)","                    .cornerRadius(10)","            }","        }","        .padding()","    }","}"]},{"level":2,"type":"heading","text":"Step 9: Send Push Notifications via Pushwoosh API","anchor":"Step-9-Send-Push-Notifications-via-Pushwoosh-API"},{"inlineContent":[{"type":"text","text":"Use Pushwoosh REST API to send Live Activity updates from your server."}],"type":"paragraph"},{"text":"Start Live Activity (Push-to-Start for iOS 17.2+)","type":"heading","level":3,"anchor":"Start-Live-Activity-Push-to-Start-for-iOS-172+"},{"inlineContent":[{"code":"POST https:\/\/api.pushwoosh.com\/json\/1.3\/startLiveActivity","type":"codeVoice"}],"type":"paragraph"},{"type":"codeListing","code":["{","  \"request\": {","    \"application\": \"YOUR-APP-CODE\",","    \"auth\": \"YOUR-API-TOKEN\",","    \"notifications\": [","      {","        \"content\": \"Your order is being prepared!\",","        \"live_activity\": {","          \"event\": \"start\",","          \"content-state\": {","            \"status\": \"Preparing your meal\",","            \"estimatedTime\": \"25 min\",","            \"emoji\": \"👨‍🍳\"","          },","          \"attributes-type\": \"FoodDeliveryAttributes\",","          \"attributes\": {","            \"orderNumber\": \"1234567\"","          }","        },","        \"live_activity_id\": \"order_123\",","        \"filter_code\": \"user_segment_code\"","      }","    ]","  }","}"],"syntax":"json"},{"inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Targeting Options:"}]}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"code":"filter_code","type":"codeVoice"},{"type":"text","text":": Target specific user segment"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"devices"},{"text":": Array of push tokens or HWIDs (max 1000)","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"code":"users","type":"codeVoice"},{"text":": Array of User IDs (max 1000)","type":"text"}]}]}]},{"anchor":"Update-Live-Activity","text":"Update Live Activity","type":"heading","level":3},{"inlineContent":[{"type":"codeVoice","code":"POST https:\/\/api.pushwoosh.com\/json\/1.3\/updateLiveActivity"}],"type":"paragraph"},{"code":["{","  \"request\": {","    \"application\": \"YOUR-APP-CODE\",","    \"auth\": \"YOUR-API-TOKEN\",","    \"notifications\": [","      {","        \"live_activity\": {","          \"event\": \"update\",","          \"content-state\": {","            \"status\": \"On the way\",","            \"estimatedTime\": \"10 min\",","            \"emoji\": \"🚚\"","          },","          \"stale-date\": 1234567890","        },","        \"live_activity_id\": \"order_123\"","      }","    ]","  }","}"],"syntax":"json","type":"codeListing"},{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Optional Parameters:"}]}]},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"stale-date"},{"text":": Unix timestamp when content becomes stale","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"code":"dismissal-date","type":"codeVoice"},{"text":": Unix timestamp when to dismiss (use with “end” event)","type":"text"}]}]}],"type":"unorderedList"},{"level":3,"type":"heading","text":"End Live Activity","anchor":"End-Live-Activity"},{"inlineContent":[{"code":"POST https:\/\/api.pushwoosh.com\/json\/1.3\/updateLiveActivity","type":"codeVoice"}],"type":"paragraph"},{"syntax":"json","type":"codeListing","code":["{","  \"request\": {","    \"application\": \"YOUR-APP-CODE\",","    \"auth\": \"YOUR-API-TOKEN\",","    \"notifications\": [","      {","        \"live_activity\": {","          \"event\": \"end\",","          \"dismissal-date\": 1234567890","        },","        \"live_activity_id\": \"order_123\"","      }","    ]","  }","}"]},{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"text":"Note:","type":"text"}]},{"type":"text","text":" For push-to-start functionality (iOS 17.2+), the "},{"type":"codeVoice","code":"setup()"},{"type":"text","text":" method automatically handles token registration. No additional code is needed in the app."}]},{"level":2,"type":"heading","anchor":"Available-SDK-Methods","text":"Available SDK Methods"},{"type":"paragraph","inlineContent":[{"text":"The PushwooshLiveActivities module provides the following methods:","type":"text"}]},{"text":"Setup Methods","level":3,"anchor":"Setup-Methods","type":"heading"},{"type":"codeListing","syntax":"swift","code":["\/\/ Setup with custom attributes (iOS 16.1+)","static func setup<Attributes: PushwooshLiveActivityAttributes>(","    _ activityType: Attributes.Type",")","","\/\/ Setup with default attributes (iOS 16.1+)","static func defaultSetup()"]},{"level":3,"anchor":"Token-Management","type":"heading","text":"Token Management"},{"content":[{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"text":"Important","type":"text"}]},{"text":": These methods are only needed if you are ","type":"text"},{"inlineContent":[{"type":"text","text":"NOT"}],"type":"strong"},{"type":"text","text":" using "},{"code":"setup()","type":"codeVoice"},{"type":"text","text":" or "},{"code":"defaultSetup()","type":"codeVoice"},{"text":". The setup methods automatically manage all token registration and lifecycle. Use these methods only for manual token management scenarios.","type":"text"}]}],"type":"aside","style":"note","name":"Note"},{"code":["\/\/ Send push-to-start token (iOS 17.2+)","static func sendPushToStartLiveActivity(token: String)","static func sendPushToStartLiveActivity(","    token: String,","    completion: @escaping (Error?) -> Void",")","","\/\/ Register activity token","static func startLiveActivity(token: String, activityId: String)","static func startLiveActivity(","    token: String,","    activityId: String,","    completion: @escaping (Error?) -> Void",")"],"type":"codeListing","syntax":"swift"},{"type":"heading","text":"Activity Lifecycle","level":3,"anchor":"Activity-Lifecycle"},{"syntax":"swift","type":"codeListing","code":["\/\/ Stop all activities","static func stopLiveActivity()","static func stopLiveActivity(completion: @escaping (Error?) -> Void)","","\/\/ Stop specific activity","static func stopLiveActivity(activityId: String)","static func stopLiveActivity(","    activityId: String,","    completion: @escaping (Error?) -> Void",")"]},{"level":3,"anchor":"Default-Mode-Methods","text":"Default Mode Methods","type":"heading"},{"type":"aside","content":[{"inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Important"}]},{"text":": Use ","type":"text"},{"type":"codeVoice","code":"defaultStart()"},{"type":"text","text":" only when you have called "},{"code":"defaultSetup()","type":"codeVoice"},{"text":" during app initialization. This method creates a Live Activity using ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/DefaultLiveActivityAttributes","isActive":true},{"type":"text","text":" structure."}],"type":"paragraph"}],"style":"note","name":"Note"},{"syntax":"swift","code":["\/\/ Start activity with default attributes (iOS 16.1+)","\/\/ Requires defaultSetup() to be called first","static func defaultStart(","    _ activityId: String,","    attributes: [String: Any],","    content: [String: Any]",")"],"type":"codeListing"},{"inlineContent":[{"inlineContent":[{"text":"Example:","type":"text"}],"type":"strong"}],"type":"paragraph"},{"syntax":"swift","code":["\/\/ In AppDelegate","if #available(iOS 16.1, *) {","    Pushwoosh.LiveActivities.defaultSetup()","}","","\/\/ Later in your code","Pushwoosh.LiveActivities.defaultStart(","    \"order_123\",","    attributes: [\"restaurantName\": \"Burger House\"],","    content: [\"status\": \"Preparing\", \"estimatedTime\": \"25 min\"]",")"],"type":"codeListing"},{"type":"heading","text":"REST API Integration","anchor":"REST-API-Integration","level":2},{"inlineContent":[{"type":"text","text":"Pushwoosh provides REST API endpoints for remote Live Activities management:"}],"type":"paragraph"},{"type":"heading","anchor":"Start-Live-Activity","text":"Start Live Activity","level":3},{"type":"paragraph","inlineContent":[{"code":"POST https:\/\/api.pushwoosh.com\/json\/1.3\/startLiveActivity","type":"codeVoice"}]},{"type":"paragraph","inlineContent":[{"text":"Required parameters:","type":"text"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"application"},{"type":"text","text":": Pushwoosh application code"}]}]},{"content":[{"inlineContent":[{"code":"auth","type":"codeVoice"},{"text":": API access token","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"codeVoice","code":"notifications"},{"type":"text","text":": Array containing Live Activity data"}],"type":"paragraph"}]}]},{"text":"Update Live Activity","type":"heading","level":3,"anchor":"Update-Live-Activity"},{"inlineContent":[{"type":"codeVoice","code":"POST https:\/\/api.pushwoosh.com\/json\/1.3\/updateLiveActivity"}],"type":"paragraph"},{"inlineContent":[{"text":"Required parameters:","type":"text"}],"type":"paragraph"},{"items":[{"content":[{"inlineContent":[{"code":"application","type":"codeVoice"},{"text":": Pushwoosh application code","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"auth"},{"type":"text","text":": API access token"}]}]},{"content":[{"inlineContent":[{"type":"codeVoice","code":"notifications"},{"type":"text","text":": Array with "},{"type":"codeVoice","code":"event"},{"text":" (“update” or “end”) and ","type":"text"},{"code":"content-state","type":"codeVoice"}],"type":"paragraph"}]}],"type":"unorderedList"},{"type":"paragraph","inlineContent":[{"text":"For complete REST API documentation, see ","type":"text"},{"isActive":true,"type":"reference","identifier":"https:\/\/docs.pushwoosh.com\/developer\/api-reference\/ios-live-activities-api\/"},{"text":".","type":"text"}]},{"level":2,"text":"Important Notes","anchor":"Important-Notes","type":"heading"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Activity ID"}]},{"type":"text","text":": Must be unique per user segment for proper targeting"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Token-based only"}]},{"text":": Certificate-based push configuration is not supported","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Physical device"}]},{"text":": Live Activities work on physical devices (Simulator support available iOS 16.4+)","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Permissions"}]},{"text":": User must have notifications enabled","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"API vs SDK"}]},{"type":"text","text":": Use SDK methods for app-side management, REST API for server-side control"}],"type":"paragraph"}]}]},{"anchor":"Testing","type":"heading","level":2,"text":"Testing"},{"type":"orderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"Build and run your app on a physical device running iOS 16.1+"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Tap “Start Live Activity” button","type":"text"}]}]},{"content":[{"inlineContent":[{"text":"Check console for activity token","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Send test push from Pushwoosh Control Panel"}]}]},{"content":[{"inlineContent":[{"text":"Observe Live Activity update on Lock Screen and Dynamic Island","type":"text"}],"type":"paragraph"}]}]},{"type":"heading","anchor":"Next-Steps","level":2,"text":"Next Steps"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"identifier":"doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/Examples","isActive":true,"type":"reference"},{"text":" - Code examples for common use cases","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"identifier":"doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/PushwooshLiveActivityAttributes","isActive":true,"type":"reference"},{"type":"text","text":" - Custom attributes protocol reference"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/DefaultLiveActivityAttributes","isActive":true,"type":"reference"},{"type":"text","text":" - Default mode attributes reference"}]}]}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshliveactivities\/gettingstarted"]},{"paths":["\/documentation\/pushwooshliveactivities\/gettingstarted"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Set up iOS Live Activities with push notification updates.","type":"text"}],"seeAlsoSections":[{"title":"Getting Started","generated":true,"identifiers":["doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/Examples"]}],"references":{"doc://com.pushwoosh.PushwooshLiveActivities/documentation/PushwooshLiveActivities/DefaultLiveActivityAttributes":{"url":"\/documentation\/pushwooshliveactivities\/defaultliveactivityattributes","title":"DefaultLiveActivityAttributes","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DefaultLiveActivityAttributes"}],"abstract":[{"type":"text","text":"A flexible structure for defining Live Activity content dynamically."}],"identifier":"doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/DefaultLiveActivityAttributes","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DefaultLiveActivityAttributes"}],"type":"topic"},"doc://com.pushwoosh.PushwooshLiveActivities/documentation/PushwooshLiveActivities/Examples":{"kind":"article","url":"\/documentation\/pushwooshliveactivities\/examples","role":"article","title":"Code Examples","abstract":[{"text":"Practical examples for common Live Activities integration scenarios.","type":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/Examples","type":"topic"},"doc://com.pushwoosh.PushwooshLiveActivities/documentation/PushwooshLiveActivities":{"url":"\/documentation\/pushwooshliveactivities","title":"PushwooshLiveActivities","kind":"symbol","abstract":[{"type":"text","text":"Real-time iOS Live Activities powered by push notifications."}],"identifier":"doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities","role":"collection","type":"topic"},"doc://com.pushwoosh.PushwooshLiveActivities/documentation/PushwooshLiveActivities/PushwooshLiveActivityAttributes":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PushwooshLiveActivityAttributes"}],"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PushwooshLiveActivityAttributes","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/PushwooshLiveActivityAttributes","url":"\/documentation\/pushwooshliveactivities\/pushwooshliveactivityattributes","title":"PushwooshLiveActivityAttributes","role":"symbol","abstract":[{"text":"Protocol for defining custom Live Activity attributes.","type":"text"}]},"https://docs.pushwoosh.com/developer/api-reference/ios-live-activities-api/":{"titleInlineContent":[{"text":"iOS Live Activities API Reference","type":"text"}],"title":"iOS Live Activities API Reference","type":"link","identifier":"https:\/\/docs.pushwoosh.com\/developer\/api-reference\/ios-live-activities-api\/","url":"https:\/\/docs.pushwoosh.com\/developer\/api-reference\/ios-live-activities-api\/"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","value":null,"path":"\/topicSections"},{"value":[{"generated":true,"title":"Getting Started","identifiers":["doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/Examples"]}],"path":"\/seeAlsoSections","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}