{"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"title":"PushwooshLiveActivitiesImplementationSetup","symbolKind":"class","role":"symbol","modules":[{"name":"PushwooshLiveActivities"}],"roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PushwooshLiveActivitiesImplementationSetup","kind":"identifier"}],"externalID":"c:@M@PushwooshLiveActivities@objc(cs)PushwooshLiveActivitiesImplementationSetup","navigatorTitle":[{"text":"PushwooshLiveActivitiesImplementationSetup","kind":"identifier"}]},"topicSections":[{"title":"Type Methods","identifiers":["doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/PushwooshLiveActivitiesImplementationSetup\/configureLiveActivity(_:)","doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/PushwooshLiveActivitiesImplementationSetup\/defaultSetup()-8niha","doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/PushwooshLiveActivitiesImplementationSetup\/defaultStart(_:attributes:content:)-1jgk3","doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/PushwooshLiveActivitiesImplementationSetup\/liveActivities()","doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/PushwooshLiveActivitiesImplementationSetup\/sendPushToStartLiveActivity(token:)-1pumn","doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/PushwooshLiveActivitiesImplementationSetup\/sendPushToStartLiveActivity(token:completion:)-3mmnt","doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/PushwooshLiveActivitiesImplementationSetup\/setPushToStartToken(_:withToken:)","doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/PushwooshLiveActivitiesImplementationSetup\/startLiveActivity(token:activityId:)-9fkj","doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/PushwooshLiveActivitiesImplementationSetup\/startLiveActivity(token:activityId:completion:)-lzr3","doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/PushwooshLiveActivitiesImplementationSetup\/stopLiveActivity()-7riam","doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/PushwooshLiveActivitiesImplementationSetup\/stopLiveActivity(activityId:)-96xj3","doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/PushwooshLiveActivitiesImplementationSetup\/stopLiveActivity(activityId:completion:)-85he3","doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/PushwooshLiveActivitiesImplementationSetup\/stopLiveActivity(completion:)-83ur3"]},{"generated":true,"title":"Default Implementations","identifiers":["doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/PushwooshLiveActivitiesImplementationSetup\/PWLiveActivities-Implementations"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(PushwooshLiveActivitiesImplementationSetup) "},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PushwooshLiveActivitiesImplementationSetup"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshliveactivities\/pushwooshliveactivitiesimplementationsetup"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshliveactivities\/pushwooshliveactivitiesimplementationsetup"]}],"kind":"symbol","sections":[],"abstract":[{"text":"Orchestrates iOS Live Activities integration with Pushwoosh push notifications.","type":"text"}],"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/com.pushwoosh.PushwooshLiveActivities\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"},{"title":"Conforms To","kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/com.pushwoosh.PushwooshLiveActivities\/objc(pl)NSObject","doc:\/\/com.pushwoosh.PushwooshLiveActivities\/@M@PushwooshBridge@objc(pl)PWLiveActivities","doc:\/\/com.pushwoosh.PushwooshLiveActivities\/s7CVarArgP","doc:\/\/com.pushwoosh.PushwooshLiveActivities\/s28CustomDebugStringConvertibleP","doc:\/\/com.pushwoosh.PushwooshLiveActivities\/s23CustomStringConvertibleP","doc:\/\/com.pushwoosh.PushwooshLiveActivities\/SQ","doc:\/\/com.pushwoosh.PushwooshLiveActivities\/SH"]}],"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/PushwooshLiveActivitiesImplementationSetup","interfaceLanguage":"swift"},"references":{"doc://com.pushwoosh.PushwooshLiveActivities/documentation/PushwooshLiveActivities/PushwooshLiveActivitiesImplementationSetup/stopLiveActivity()-7riam":{"identifier":"doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/PushwooshLiveActivitiesImplementationSetup\/stopLiveActivity()-7riam","title":"stopLiveActivity()","navigatorTitle":[{"text":"stopLiveActivity","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","abstract":[{"text":"Notifies the server that all Live Activities have ended.","type":"text"}],"url":"\/documentation\/pushwooshliveactivities\/pushwooshliveactivitiesimplementationsetup\/stopliveactivity()-7riam","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stopLiveActivity","kind":"identifier"},{"text":"()","kind":"text"}]},"doc://com.pushwoosh.PushwooshLiveActivities/documentation/PushwooshLiveActivities/PushwooshLiveActivitiesImplementationSetup/setPushToStartToken(_:withToken:)":{"identifier":"doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/PushwooshLiveActivitiesImplementationSetup\/setPushToStartToken(_:withToken:)","title":"setPushToStartToken(_:withToken:)","type":"topic","kind":"symbol","role":"symbol","abstract":[],"url":"\/documentation\/pushwooshliveactivities\/pushwooshliveactivitiesimplementationsetup\/setpushtostarttoken(_:withtoken:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setPushToStartToken","kind":"identifier"},{"text":"<","kind":"text"},{"text":"Attributes","kind":"genericParameter"},{"text":">(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:23PushwooshLiveActivities0abC19ImplementationSetupC19setPushToStartToken_04withJ0yxm_SSt11ActivityKit0L10AttributesRzlFZ0N0L_xmfp","text":"Attributes"},{"text":".Type, ","kind":"text"},{"text":"withToken","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}]},"doc://com.pushwoosh.PushwooshLiveActivities/@M@PushwooshBridge@objc(pl)PWLiveActivities":{"type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshLiveActivities\/@M@PushwooshBridge@objc(pl)PWLiveActivities","title":"PWLiveActivities"},"doc://com.pushwoosh.PushwooshLiveActivities/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshLiveActivities\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.pushwoosh.PushwooshLiveActivities/documentation/PushwooshLiveActivities/PushwooshLiveActivitiesImplementationSetup/defaultStart(_:attributes:content:)-1jgk3":{"identifier":"doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/PushwooshLiveActivitiesImplementationSetup\/defaultStart(_:attributes:content:)-1jgk3","title":"defaultStart(_:attributes:content:)","navigatorTitle":[{"text":"defaultStart:attributes:content:","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Starts a Live Activity using default attributes."}],"url":"\/documentation\/pushwooshliveactivities\/pushwooshliveactivitiesimplementationsetup\/defaultstart(_:attributes:content:)-1jgk3","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"defaultStart"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"attributes","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"], "},{"text":"content","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"])","kind":"text"}]},"doc://com.pushwoosh.PushwooshLiveActivities/documentation/PushwooshLiveActivities/PushwooshLiveActivitiesImplementationSetup/liveActivities()":{"identifier":"doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/PushwooshLiveActivitiesImplementationSetup\/liveActivities()","title":"liveActivities()","navigatorTitle":[{"text":"liveActivities","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","abstract":[],"url":"\/documentation\/pushwooshliveactivities\/pushwooshliveactivitiesimplementationsetup\/liveactivities()","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"liveActivities","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:s8AnyClassa","kind":"typeIdentifier","text":"AnyClass"}]},"doc://com.pushwoosh.PushwooshLiveActivities/documentation/PushwooshLiveActivities/PushwooshLiveActivitiesImplementationSetup/startLiveActivity(token:activityId:)-9fkj":{"url":"\/documentation\/pushwooshliveactivities\/pushwooshliveactivitiesimplementationsetup\/startliveactivity(token:activityid:)-9fkj","identifier":"doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/PushwooshLiveActivitiesImplementationSetup\/startLiveActivity(token:activityId:)-9fkj","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startLiveActivityWithToken:activityId:"}],"abstract":[{"type":"text","text":"Registers an active Live Activity with the server."}],"title":"startLiveActivity(token:activityId:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startLiveActivity","kind":"identifier"},{"text":"(","kind":"text"},{"text":"token","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"activityId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"role":"symbol"},"doc://com.pushwoosh.PushwooshLiveActivities/documentation/PushwooshLiveActivities":{"kind":"symbol","abstract":[{"text":"Real-time iOS Live Activities powered by push notifications.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities","title":"PushwooshLiveActivities","url":"\/documentation\/pushwooshliveactivities","role":"collection"},"doc://com.pushwoosh.PushwooshLiveActivities/documentation/PushwooshLiveActivities/PushwooshLiveActivitiesImplementationSetup/defaultSetup()-8niha":{"url":"\/documentation\/pushwooshliveactivities\/pushwooshliveactivitiesimplementationsetup\/defaultsetup()-8niha","identifier":"doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/PushwooshLiveActivitiesImplementationSetup\/defaultSetup()-8niha","kind":"symbol","type":"topic","navigatorTitle":[{"text":"defaultSetup","kind":"identifier"}],"abstract":[{"text":"Configures Live Activities with default attributes managed by Pushwoosh.","type":"text"}],"title":"defaultSetup()","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"defaultSetup","kind":"identifier"},{"text":"()","kind":"text"}],"role":"symbol"},"doc://com.pushwoosh.PushwooshLiveActivities/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshLiveActivities\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.pushwoosh.PushwooshLiveActivities/documentation/PushwooshLiveActivities/PushwooshLiveActivitiesImplementationSetup":{"url":"\/documentation\/pushwooshliveactivities\/pushwooshliveactivitiesimplementationsetup","identifier":"doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/PushwooshLiveActivitiesImplementationSetup","kind":"symbol","type":"topic","navigatorTitle":[{"text":"PushwooshLiveActivitiesImplementationSetup","kind":"identifier"}],"abstract":[{"type":"text","text":"Orchestrates iOS Live Activities integration with Pushwoosh push notifications."}],"title":"PushwooshLiveActivitiesImplementationSetup","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PushwooshLiveActivitiesImplementationSetup","kind":"identifier"}],"role":"symbol"},"doc://com.pushwoosh.PushwooshLiveActivities/documentation/PushwooshLiveActivities/PushwooshLiveActivitiesImplementationSetup/sendPushToStartLiveActivity(token:)-1pumn":{"url":"\/documentation\/pushwooshliveactivities\/pushwooshliveactivitiesimplementationsetup\/sendpushtostartliveactivity(token:)-1pumn","identifier":"doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/PushwooshLiveActivitiesImplementationSetup\/sendPushToStartLiveActivity(token:)-1pumn","kind":"symbol","type":"topic","navigatorTitle":[{"text":"sendPushToStartLiveActivityWithToken:","kind":"identifier"}],"abstract":[{"text":"Sends push-to-start token to enable remote activity initiation.","type":"text"}],"title":"sendPushToStartLiveActivity(token:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sendPushToStartLiveActivity","kind":"identifier"},{"text":"(","kind":"text"},{"text":"token","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol"},"doc://com.pushwoosh.PushwooshLiveActivities/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshLiveActivities\/objc(cs)NSObject","title":"NSObject"},"doc://com.pushwoosh.PushwooshLiveActivities/documentation/PushwooshLiveActivities/PushwooshLiveActivitiesImplementationSetup/stopLiveActivity(activityId:completion:)-85he3":{"url":"\/documentation\/pushwooshliveactivities\/pushwooshliveactivitiesimplementationsetup\/stopliveactivity(activityid:completion:)-85he3","identifier":"doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/PushwooshLiveActivitiesImplementationSetup\/stopLiveActivity(activityId:completion:)-85he3","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"stopLiveActivityWithActivityId:completion:"}],"abstract":[{"text":"Notifies the server that a specific Live Activity has ended with completion handler.","type":"text"}],"title":"stopLiveActivity(activityId:completion:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stopLiveActivity","kind":"identifier"},{"text":"(","kind":"text"},{"text":"activityId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"any","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":")?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"role":"symbol"},"doc://com.pushwoosh.PushwooshLiveActivities/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshLiveActivities\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.pushwoosh.PushwooshLiveActivities/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshLiveActivities\/SQ","title":"Swift.Equatable"},"doc://com.pushwoosh.PushwooshLiveActivities/documentation/PushwooshLiveActivities/PushwooshLiveActivitiesImplementationSetup/sendPushToStartLiveActivity(token:completion:)-3mmnt":{"type":"topic","title":"sendPushToStartLiveActivity(token:completion:)","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"sendPushToStartLiveActivity","kind":"identifier"},{"text":"(","kind":"text"},{"text":"token","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (((","kind":"text"},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":"))","kind":"text"}],"role":"symbol","abstract":[{"type":"text","text":"Sends push-to-start token to enable remote activity initiation with completion handler."}],"url":"\/documentation\/pushwooshliveactivities\/pushwooshliveactivitiesimplementationsetup\/sendpushtostartliveactivity(token:completion:)-3mmnt","navigatorTitle":[{"kind":"identifier","text":"sendPushToStartLiveActivityWithToken:completion:"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/PushwooshLiveActivitiesImplementationSetup\/sendPushToStartLiveActivity(token:completion:)-3mmnt"},"doc://com.pushwoosh.PushwooshLiveActivities/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshLiveActivities\/objc(pl)NSObject"},"doc://com.pushwoosh.PushwooshLiveActivities/documentation/PushwooshLiveActivities/PushwooshLiveActivitiesImplementationSetup/configureLiveActivity(_:)":{"type":"topic","title":"configureLiveActivity(_:)","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"configureLiveActivity","kind":"identifier"},{"text":"<","kind":"text"},{"text":"Attributes","kind":"genericParameter"},{"text":">(","kind":"text"},{"text":"Attributes","kind":"typeIdentifier","preciseIdentifier":"s:23PushwooshLiveActivities0abC19ImplementationSetupC09configureB8ActivityyyxmAA0abG10AttributesRzlFZ0H0L_xmfp"},{"text":".Type)","kind":"text"}],"role":"symbol","abstract":[{"type":"text","text":"Configures Live Activities with custom attributes."}],"url":"\/documentation\/pushwooshliveactivities\/pushwooshliveactivitiesimplementationsetup\/configureliveactivity(_:)","identifier":"doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/PushwooshLiveActivitiesImplementationSetup\/configureLiveActivity(_:)"},"doc://com.pushwoosh.PushwooshLiveActivities/documentation/PushwooshLiveActivities/PushwooshLiveActivitiesImplementationSetup/stopLiveActivity(completion:)-83ur3":{"title":"stopLiveActivity(completion:)","type":"topic","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stopLiveActivity","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":")?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","url":"\/documentation\/pushwooshliveactivities\/pushwooshliveactivitiesimplementationsetup\/stopliveactivity(completion:)-83ur3","abstract":[{"type":"text","text":"Notifies the server that all Live Activities have ended with completion handler."}],"navigatorTitle":[{"text":"stopLiveActivityWithCompletion:","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/PushwooshLiveActivitiesImplementationSetup\/stopLiveActivity(completion:)-83ur3"},"doc://com.pushwoosh.PushwooshLiveActivities/documentation/PushwooshLiveActivities/PushwooshLiveActivitiesImplementationSetup/startLiveActivity(token:activityId:completion:)-lzr3":{"type":"topic","title":"startLiveActivity(token:activityId:completion:)","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startLiveActivity","kind":"identifier"},{"text":"(","kind":"text"},{"text":"token","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"activityId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (("},{"kind":"keyword","text":"any"},{"text":" ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"role":"symbol","abstract":[{"text":"Registers an active Live Activity with the server with completion handler.","type":"text"}],"url":"\/documentation\/pushwooshliveactivities\/pushwooshliveactivitiesimplementationsetup\/startliveactivity(token:activityid:completion:)-lzr3","navigatorTitle":[{"text":"startLiveActivityWithToken:activityId:completion:","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/PushwooshLiveActivitiesImplementationSetup\/startLiveActivity(token:activityId:completion:)-lzr3"},"doc://com.pushwoosh.PushwooshLiveActivities/documentation/PushwooshLiveActivities/PushwooshLiveActivitiesImplementationSetup/stopLiveActivity(activityId:)-96xj3":{"type":"topic","title":"stopLiveActivity(activityId:)","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"stopLiveActivity","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"activityId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","url":"\/documentation\/pushwooshliveactivities\/pushwooshliveactivitiesimplementationsetup\/stopliveactivity(activityid:)-96xj3","abstract":[{"type":"text","text":"Notifies the server that a specific Live Activity has ended."}],"navigatorTitle":[{"text":"stopLiveActivityWithActivityId:","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/PushwooshLiveActivitiesImplementationSetup\/stopLiveActivity(activityId:)-96xj3"},"doc://com.pushwoosh.PushwooshLiveActivities/documentation/PushwooshLiveActivities/PushwooshLiveActivitiesImplementationSetup/PWLiveActivities-Implementations":{"type":"topic","title":"PWLiveActivities Implementations","kind":"article","role":"collectionGroup","abstract":[],"url":"\/documentation\/pushwooshliveactivities\/pushwooshliveactivitiesimplementationsetup\/pwliveactivities-implementations","identifier":"doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/PushwooshLiveActivitiesImplementationSetup\/PWLiveActivities-Implementations"},"doc://com.pushwoosh.PushwooshLiveActivities/SH":{"identifier":"doc:\/\/com.pushwoosh.PushwooshLiveActivities\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.pushwoosh.PushwooshLiveActivities/documentation/PushwooshLiveActivities/PushwooshLiveActivitiesImplementationSetup/init":{"type":"topic","title":"init","kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"role":"symbol","abstract":[],"url":"\/documentation\/pushwooshliveactivities\/pushwooshliveactivitiesimplementationsetup\/init","navigatorTitle":[{"text":"init","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/PushwooshLiveActivitiesImplementationSetup\/init"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"PushwooshLiveActivitiesImplementationSetup"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"PushwooshLiveActivitiesImplementationSetup"}]},{"value":[{"text":"PushwooshLiveActivitiesImplementationSetup","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"op":"replace","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/PushwooshLiveActivitiesImplementationSetup\/init"]},{"identifiers":["doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/PushwooshLiveActivitiesImplementationSetup\/defaultSetup()-8niha","doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/PushwooshLiveActivitiesImplementationSetup\/defaultStart(_:attributes:content:)-1jgk3","doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/PushwooshLiveActivitiesImplementationSetup\/liveActivities()","doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/PushwooshLiveActivitiesImplementationSetup\/sendPushToStartLiveActivity(token:)-1pumn","doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/PushwooshLiveActivitiesImplementationSetup\/sendPushToStartLiveActivity(token:completion:)-3mmnt","doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/PushwooshLiveActivitiesImplementationSetup\/startLiveActivity(token:activityId:)-9fkj","doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/PushwooshLiveActivitiesImplementationSetup\/startLiveActivity(token:activityId:completion:)-lzr3","doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/PushwooshLiveActivitiesImplementationSetup\/stopLiveActivity()-7riam","doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/PushwooshLiveActivitiesImplementationSetup\/stopLiveActivity(activityId:)-96xj3","doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/PushwooshLiveActivitiesImplementationSetup\/stopLiveActivity(activityId:completion:)-85he3","doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/PushwooshLiveActivitiesImplementationSetup\/stopLiveActivity(completion:)-83ur3"],"title":"Type Methods"}],"path":"\/topicSections"},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshLiveActivities\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"},{"title":"Conforms To","identifiers":["doc:\/\/com.pushwoosh.PushwooshLiveActivities\/@M@PushwooshBridge@objc(pl)PWLiveActivities"],"kind":"relationships","type":"conformsTo"}],"op":"replace"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PushwooshLiveActivitiesImplementationSetup","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshLiveActivities~1documentation~1PushwooshLiveActivities~1PushwooshLiveActivitiesImplementationSetup~1stopLiveActivity()-7riam\/title","value":"stopLiveActivity"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshLiveActivities~1documentation~1PushwooshLiveActivities~1PushwooshLiveActivitiesImplementationSetup~1stopLiveActivity()-7riam\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"stopLiveActivity","kind":"identifier"}]},{"value":"defaultStart:attributes:content:","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshLiveActivities~1documentation~1PushwooshLiveActivities~1PushwooshLiveActivitiesImplementationSetup~1defaultStart(_:attributes:content:)-1jgk3\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshLiveActivities~1documentation~1PushwooshLiveActivities~1PushwooshLiveActivitiesImplementationSetup~1defaultStart(_:attributes:content:)-1jgk3\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"defaultStart:attributes:content:"}]},{"op":"replace","value":"liveActivities","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshLiveActivities~1documentation~1PushwooshLiveActivities~1PushwooshLiveActivitiesImplementationSetup~1liveActivities()\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshLiveActivities~1documentation~1PushwooshLiveActivities~1PushwooshLiveActivitiesImplementationSetup~1liveActivities()\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"liveActivities","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshLiveActivities~1documentation~1PushwooshLiveActivities~1PushwooshLiveActivitiesImplementationSetup~1startLiveActivity(token:activityId:)-9fkj\/title","value":"startLiveActivityWithToken:activityId:"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshLiveActivities~1documentation~1PushwooshLiveActivities~1PushwooshLiveActivitiesImplementationSetup~1startLiveActivity(token:activityId:)-9fkj\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"startLiveActivityWithToken:activityId:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshLiveActivities~1documentation~1PushwooshLiveActivities~1PushwooshLiveActivitiesImplementationSetup~1defaultSetup()-8niha\/title","value":"defaultSetup"},{"value":[{"kind":"text","text":"+ "},{"text":"defaultSetup","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshLiveActivities~1documentation~1PushwooshLiveActivities~1PushwooshLiveActivitiesImplementationSetup~1defaultSetup()-8niha\/fragments"},{"value":"PushwooshLiveActivitiesImplementationSetup","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshLiveActivities~1documentation~1PushwooshLiveActivities~1PushwooshLiveActivitiesImplementationSetup\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshLiveActivities~1documentation~1PushwooshLiveActivities~1PushwooshLiveActivitiesImplementationSetup\/fragments","value":[{"text":"PushwooshLiveActivitiesImplementationSetup","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshLiveActivities~1documentation~1PushwooshLiveActivities~1PushwooshLiveActivitiesImplementationSetup~1sendPushToStartLiveActivity(token:)-1pumn\/title","value":"sendPushToStartLiveActivityWithToken:"},{"value":[{"text":"+ ","kind":"text"},{"text":"sendPushToStartLiveActivityWithToken:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshLiveActivities~1documentation~1PushwooshLiveActivities~1PushwooshLiveActivitiesImplementationSetup~1sendPushToStartLiveActivity(token:)-1pumn\/fragments"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshLiveActivities~1documentation~1PushwooshLiveActivities~1PushwooshLiveActivitiesImplementationSetup~1stopLiveActivity(activityId:completion:)-85he3\/title","value":"stopLiveActivityWithActivityId:completion:","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshLiveActivities~1documentation~1PushwooshLiveActivities~1PushwooshLiveActivitiesImplementationSetup~1stopLiveActivity(activityId:completion:)-85he3\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"stopLiveActivityWithActivityId:completion:"}],"op":"replace"},{"value":"sendPushToStartLiveActivityWithToken:completion:","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshLiveActivities~1documentation~1PushwooshLiveActivities~1PushwooshLiveActivitiesImplementationSetup~1sendPushToStartLiveActivity(token:completion:)-3mmnt\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshLiveActivities~1documentation~1PushwooshLiveActivities~1PushwooshLiveActivitiesImplementationSetup~1sendPushToStartLiveActivity(token:completion:)-3mmnt\/fragments","value":[{"kind":"text","text":"+ "},{"text":"sendPushToStartLiveActivityWithToken:completion:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshLiveActivities~1documentation~1PushwooshLiveActivities~1PushwooshLiveActivitiesImplementationSetup~1stopLiveActivity(completion:)-83ur3\/title","value":"stopLiveActivityWithCompletion:"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"stopLiveActivityWithCompletion:"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshLiveActivities~1documentation~1PushwooshLiveActivities~1PushwooshLiveActivitiesImplementationSetup~1stopLiveActivity(completion:)-83ur3\/fragments"},{"value":"startLiveActivityWithToken:activityId:completion:","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshLiveActivities~1documentation~1PushwooshLiveActivities~1PushwooshLiveActivitiesImplementationSetup~1startLiveActivity(token:activityId:completion:)-lzr3\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshLiveActivities~1documentation~1PushwooshLiveActivities~1PushwooshLiveActivitiesImplementationSetup~1startLiveActivity(token:activityId:completion:)-lzr3\/fragments","value":[{"kind":"text","text":"+ "},{"text":"startLiveActivityWithToken:activityId:completion:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshLiveActivities~1documentation~1PushwooshLiveActivities~1PushwooshLiveActivitiesImplementationSetup~1stopLiveActivity(activityId:)-96xj3\/title","value":"stopLiveActivityWithActivityId:"},{"value":[{"kind":"text","text":"+ "},{"text":"stopLiveActivityWithActivityId:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshLiveActivities~1documentation~1PushwooshLiveActivities~1PushwooshLiveActivitiesImplementationSetup~1stopLiveActivity(activityId:)-96xj3\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}