{"kind":"symbol","abstract":[{"text":"Retrieves the current device push token.","type":"text"}],"seeAlsoSections":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/getHWID()","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/registerForPushNotifications()","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/registerForPushNotifications(completion:)"],"title":"Related Documentation"}],"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/getPushToken()","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh"]]},"metadata":{"externalID":"c:objc(cs)Pushwoosh(im)getPushToken","navigatorTitle":[{"text":"getPushToken","kind":"identifier"}],"role":"symbol","roleHeading":"Instance Method","title":"getPushToken()","modules":[{"name":"PushwooshFramework"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getPushToken"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"symbolKind":"method"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getPushToken"},{"text":"() -> ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"languages":["swift"]}]},{"kind":"content","content":[{"level":2,"anchor":"Overview","type":"heading","text":"Overview"},{"inlineContent":[{"text":"The push token (also known as device token) is a unique identifier assigned by Apple Push Notification service (APNs) to this specific app installation on this device. Pushwoosh uses this token to deliver push notifications.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"Common use cases:"}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Sending the token to your own backend for server-side push delivery","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Debugging push notification issues"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Verifying successful registration","type":"text"}]}]}],"type":"unorderedList"},{"type":"heading","level":2,"anchor":"Availability","text":"Availability"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The push token becomes available only after:"}]},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"User grants notification permission","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Device successfully registers with APNs"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Token is received from APNs"}]}]}],"type":"orderedList"},{"inlineContent":[{"text":"Before registration completes, this method returns ","type":"text"},{"type":"codeVoice","code":"nil"},{"type":"text","text":"."}],"type":"paragraph"},{"type":"heading","text":"Example","anchor":"Example","level":2},{"inlineContent":[{"type":"text","text":"Send push token to your backend for custom push delivery:"}],"type":"paragraph"},{"type":"codeListing","syntax":"swift","code":["func registerDeviceWithBackend() {","    guard let pushToken = Pushwoosh.configure.getPushToken() else {","        return","    }","","    let hwid = Pushwoosh.configure.getHWID()","","    apiClient.registerDevice(","        pushToken: pushToken,","        hwid: hwid,","        platform: \"ios\"","    )","}"]},{"inlineContent":[{"type":"text","text":"Check if device is registered for push notifications:"}],"type":"paragraph"},{"code":["func isPushRegistered() -> Bool {","    return Pushwoosh.configure.getPushToken() != nil","}"],"type":"codeListing","syntax":"swift"}]}],"sections":[],"variants":[{"paths":["\/documentation\/pushwooshframework\/pushwoosh\/getpushtoken()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pushwoosh\/getpushtoken()"]}],"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/registerForPushNotifications()":{"url":"\/documentation\/pushwooshframework\/pushwoosh\/registerforpushnotifications()","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/registerForPushNotifications()","title":"registerForPushNotifications()","navigatorTitle":[{"kind":"identifier","text":"registerForPushNotifications"}],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"registerForPushNotifications"},{"kind":"text","text":"()"}],"role":"symbol","abstract":[{"type":"text","text":"Registers the device for push notifications."}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh":{"navigatorTitle":[{"kind":"identifier","text":"Pushwoosh"}],"type":"topic","url":"\/documentation\/pushwooshframework\/pushwoosh","abstract":[{"text":"Main SDK interface for push notification management.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Pushwoosh","kind":"identifier"}],"kind":"symbol","title":"Pushwoosh","role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/registerForPushNotifications(completion:)":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/registerForPushNotifications(completion:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"registerForPushNotifications"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": ","kind":"text"},{"text":"PushwooshRegistrationHandler","preciseIdentifier":"c:PWTypes.h@T@PushwooshRegistrationHandler","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"registerForPushNotificationsWithCompletion:"}],"type":"topic","kind":"symbol","abstract":[{"text":"Registers the device for push notifications with a completion handler.","type":"text"}],"url":"\/documentation\/pushwooshframework\/pushwoosh\/registerforpushnotifications(completion:)","title":"registerForPushNotifications(completion:)","role":"symbol"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/getHWID()":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/getHWID()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"getHWID","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"kind":"identifier","text":"getHWID"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Returns the Pushwoosh Hardware ID (HWID) for this device."}],"url":"\/documentation\/pushwooshframework\/pushwoosh\/gethwid()","title":"getHWID()","role":"symbol"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/getPushToken()":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"getPushToken","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"role":"symbol","type":"topic","kind":"symbol","title":"getPushToken()","navigatorTitle":[{"kind":"identifier","text":"getPushToken"}],"url":"\/documentation\/pushwooshframework\/pushwoosh\/getpushtoken()","abstract":[{"text":"Retrieves the current device push token.","type":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/getPushToken()"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"type":"topic","role":"collection","title":"PushwooshFramework","abstract":[{"type":"text","text":"Push notification SDK for iOS applications."}],"url":"\/documentation\/pushwooshframework","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"getPushToken"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"getPushToken"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/getHWID()","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/registerForPushNotifications()","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/registerForPushNotifications(completion:)"],"title":"Related Documentation"}],"op":"replace","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"getPushToken"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"registerForPushNotifications","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1registerForPushNotifications()\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1registerForPushNotifications()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"registerForPushNotifications","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh\/title","value":"Pushwoosh","op":"replace"},{"value":[{"kind":"identifier","text":"Pushwoosh"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh\/fragments","op":"replace"},{"value":"registerForPushNotificationsWithCompletion:","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1registerForPushNotifications(completion:)\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1registerForPushNotifications(completion:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"registerForPushNotificationsWithCompletion:","kind":"identifier"}],"op":"replace"},{"value":"getHWID","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1getHWID()\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"getHWID"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1getHWID()\/fragments"},{"op":"replace","value":"getPushToken","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1getPushToken()\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"getPushToken","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1getPushToken()\/fragments"}]}]}