{"variants":[{"paths":["\/documentation\/pushwooshvoip\/pwvoiphandletype\/email"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pushwooshvoip\/pwvoiphandletype\/email"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPHandleType"]]},"abstract":[{"text":"Email address format.","type":"text"}],"metadata":{"symbolKind":"case","role":"symbol","title":"PWVoIPHandleType.email","modules":[{"name":"PushwooshVoIP"}],"externalID":"c:@M@PushwooshVoIP@E@PWVoIPHandleType@PWVoIPHandleTypeEmail","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"email","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PWVoIPHandleTypeEmail"}]},"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPHandleType\/email"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"email"}],"platforms":["iOS"]}]},{"kind":"content","content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"inlineContent":[{"text":"Use this type when the caller identifier is an email address. CallKit will display the email","type":"text"},{"type":"text","text":" "},{"type":"text","text":"with appropriate email formatting in the incoming call UI."}],"type":"paragraph"},{"name":"Note","content":[{"inlineContent":[{"type":"text","text":"Ensure the email address is valid and properly formatted (e.g., user@example.com)."}],"type":"paragraph"}],"type":"aside","style":"note"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPHandleType/email":{"abstract":[{"type":"text","text":"Email address format."}],"identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPHandleType\/email","url":"\/documentation\/pushwooshvoip\/pwvoiphandletype\/email","role":"symbol","title":"PWVoIPHandleType.email","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"email"}],"navigatorTitle":[{"kind":"identifier","text":"PWVoIPHandleTypeEmail"}],"kind":"symbol","type":"topic"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP":{"abstract":[{"type":"text","text":"VoIP push notifications with native call UI for iOS applications."}],"role":"collection","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP","type":"topic","title":"PushwooshVoIP","url":"\/documentation\/pushwooshvoip"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPHandleType":{"url":"\/documentation\/pushwooshvoip\/pwvoiphandletype","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"PWVoIPHandleType","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PWVoIPHandleType"}],"title":"PWVoIPHandleType","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPHandleType","abstract":[{"text":"Display format for caller information in CallKit UI.","type":"text"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"PWVoIPHandleTypeEmail"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"PWVoIPHandleTypeEmail","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"PWVoIPHandleTypeEmail"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPHandleType~1email\/title","value":"PWVoIPHandleTypeEmail"},{"value":[{"text":"PWVoIPHandleTypeEmail","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPHandleType~1email\/fragments","op":"replace"},{"value":"PWVoIPHandleType","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPHandleType\/title","op":"replace"},{"value":[{"text":"PWVoIPHandleType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPHandleType\/fragments"}]}]}