{"abstract":[{"type":"text","text":"Convenience factory for Obj-C hosts that want a default-configured"},{"type":"text","text":" "},{"type":"text","text":"controller without touching the Swift "},{"type":"codeVoice","code":"Attributes"},{"type":"text","text":" struct."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"title":"makeViewController()","externalID":"c:@M@PushwooshInboxKit@objc(cs)PushwooshInboxKitImplementation(cm)makeViewController","symbolKind":"method","modules":[{"name":"PushwooshInboxKit"}],"navigatorTitle":[{"text":"makeViewController","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"makeViewController","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"role":"symbol","roleHeading":"Type Method"},"kind":"symbol","identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitImplementation\/makeViewController()","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitImplementation"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"makeViewController"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"}]}],"kind":"declarations"},{"content":[{"type":"heading","text":"Discussion","anchor":"discussion","level":2},{"type":"paragraph","inlineContent":[{"text":"Reserved scaffold — not currently wired into an integration path:","type":"text"},{"type":"text","text":" "},{"type":"text","text":"it is intentionally NOT declared on the "},{"code":"PWInboxKit","type":"codeVoice"},{"type":"text","text":" bridge protocol,"},{"text":" ","type":"text"},{"type":"text","text":"so it is not reachable through "},{"type":"codeVoice","code":"Pushwoosh.InboxKit"},{"type":"text","text":" today. Current"},{"type":"text","text":" "},{"type":"text","text":"integrations build the controller directly"},{"text":" ","type":"text"},{"text":"(","type":"text"},{"code":"PushwooshInboxKitViewController(attributes:)","type":"codeVoice"},{"text":", or ","type":"text"},{"type":"codeVoice","code":"[[… alloc] init]"},{"type":"text","text":" "},{"type":"text","text":"from Obj-C). Kept for a possible future Obj-C entry point: to activate"},{"text":" ","type":"text"},{"type":"text","text":"it, add "},{"type":"codeVoice","code":"static func makeViewController() -> UIViewController"},{"text":" to the","type":"text"},{"type":"text","text":" "},{"type":"codeVoice","code":"PWInboxKit"},{"type":"text","text":" protocol so "},{"type":"codeVoice","code":"[[Pushwoosh InboxKit] makeViewController]"},{"text":" ","type":"text"},{"type":"text","text":"resolves end-to-end."}]}],"kind":"content"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshinboxkit\/pushwooshinboxkitimplementation\/makeviewcontroller()"]},{"paths":["\/documentation\/pushwooshinboxkit\/pushwooshinboxkitimplementation\/makeviewcontroller()"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxKitImplementation":{"kind":"symbol","abstract":[{"type":"text","text":"Implementation entry-point discovered by the umbrella SDK via"},{"text":" ","type":"text"},{"type":"codeVoice","code":"NSClassFromString(\"PushwooshInboxKitImplementation\")"},{"text":".","type":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitImplementation","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxkitimplementation","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushwooshInboxKitImplementation"}],"title":"PushwooshInboxKitImplementation","navigatorTitle":[{"kind":"identifier","text":"PushwooshInboxKitImplementation"}],"role":"symbol","type":"topic"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxKitImplementation/makeViewController()":{"kind":"symbol","navigatorTitle":[{"text":"makeViewController","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitImplementation\/makeViewController()","abstract":[{"type":"text","text":"Convenience factory for Obj-C hosts that want a default-configured"},{"text":" ","type":"text"},{"text":"controller without touching the Swift ","type":"text"},{"type":"codeVoice","code":"Attributes"},{"type":"text","text":" struct."}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"makeViewController","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"}],"title":"makeViewController()","role":"symbol","type":"topic","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxkitimplementation\/makeviewcontroller()"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit":{"kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit","role":"collection","type":"topic","url":"\/documentation\/pushwooshinboxkit","title":"PushwooshInboxKit","abstract":[{"type":"text","text":"Modern UIKit inbox UI powered by Pushwoosh."}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"makeViewController","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"makeViewController"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"makeViewController"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxKitImplementation\/title","value":"PushwooshInboxKitImplementation"},{"op":"replace","value":[{"text":"PushwooshInboxKitImplementation","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxKitImplementation\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxKitImplementation~1makeViewController()\/title","value":"makeViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxKitImplementation~1makeViewController()\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"makeViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}