{"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC"]]},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.pushwoosh.PushwooshGRPC\/objc(cs)NSObject"],"kind":"relationships"},{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.pushwoosh.PushwooshGRPC\/objc(pl)NSObject","doc:\/\/com.pushwoosh.PushwooshGRPC\/@M@PushwooshBridge@objc(pl)PWTransport","doc:\/\/com.pushwoosh.PushwooshGRPC\/s7CVarArgP","doc:\/\/com.pushwoosh.PushwooshGRPC\/s28CustomDebugStringConvertibleP","doc:\/\/com.pushwoosh.PushwooshGRPC\/s23CustomStringConvertibleP","doc:\/\/com.pushwoosh.PushwooshGRPC\/SQ","doc:\/\/com.pushwoosh.PushwooshGRPC\/SH"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PushwooshGRPCImplementation","kind":"identifier"}]}]}],"kind":"symbol","metadata":{"role":"symbol","modules":[{"name":"PushwooshGRPC"}],"roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PushwooshGRPCImplementation","kind":"identifier"}],"title":"PushwooshGRPCImplementation","externalID":"c:@M@PushwooshGRPC@objc(cs)PushwooshGRPCImplementation","symbolKind":"class","navigatorTitle":[{"text":"PushwooshGRPCImplementation","kind":"identifier"}]},"variants":[{"paths":["\/documentation\/pushwooshgrpc\/pushwooshgrpcimplementation"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pushwooshgrpc\/pushwooshgrpcimplementation"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/PushwooshGRPCImplementation"},"topicSections":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/PushwooshGRPCImplementation\/isAvailable","doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/PushwooshGRPCImplementation\/transportName"],"title":"Type Properties"},{"title":"Type Methods","identifiers":["doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/PushwooshGRPCImplementation\/sendRequest(_:completion:)","doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/PushwooshGRPCImplementation\/supportsMethod(_:)"]}],"references":{"doc://com.pushwoosh.PushwooshGRPC/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.pushwoosh.PushwooshGRPC\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://com.pushwoosh.PushwooshGRPC/documentation/PushwooshGRPC":{"kind":"symbol","role":"collection","identifier":"doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC","title":"PushwooshGRPC","url":"\/documentation\/pushwooshgrpc","type":"topic","abstract":[]},"doc://com.pushwoosh.PushwooshGRPC/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/com.pushwoosh.PushwooshGRPC\/objc(cs)NSObject","type":"unresolvable"},"doc://com.pushwoosh.PushwooshGRPC/@M@PushwooshBridge@objc(pl)PWTransport":{"title":"PWTransport","identifier":"doc:\/\/com.pushwoosh.PushwooshGRPC\/@M@PushwooshBridge@objc(pl)PWTransport","type":"unresolvable"},"doc://com.pushwoosh.PushwooshGRPC/documentation/PushwooshGRPC/PushwooshGRPCImplementation/supportsMethod(_:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"supportsMethod","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"title":"supportsMethod(_:)","type":"topic","url":"\/documentation\/pushwooshgrpc\/pushwooshgrpcimplementation\/supportsmethod(_:)","abstract":[],"identifier":"doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/PushwooshGRPCImplementation\/supportsMethod(_:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"supportsMethod:"}]},"doc://com.pushwoosh.PushwooshGRPC/documentation/PushwooshGRPC/PushwooshGRPCImplementation/init":{"role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"title":"init","url":"\/documentation\/pushwooshgrpc\/pushwooshgrpcimplementation\/init","abstract":[],"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/PushwooshGRPCImplementation\/init","kind":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}]},"doc://com.pushwoosh.PushwooshGRPC/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.pushwoosh.PushwooshGRPC\/SQ","type":"unresolvable"},"doc://com.pushwoosh.PushwooshGRPC/documentation/PushwooshGRPC/PushwooshGRPCImplementation/isAvailable":{"identifier":"doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/PushwooshGRPCImplementation\/isAvailable","abstract":[],"navigatorTitle":[{"text":"isAvailable","kind":"identifier"}],"url":"\/documentation\/pushwooshgrpc\/pushwooshgrpcimplementation\/isavailable","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isAvailable"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"kind":"symbol","type":"topic","title":"isAvailable","role":"symbol"},"doc://com.pushwoosh.PushwooshGRPC/documentation/PushwooshGRPC/PushwooshGRPCImplementation":{"identifier":"doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/PushwooshGRPCImplementation","abstract":[],"navigatorTitle":[{"text":"PushwooshGRPCImplementation","kind":"identifier"}],"url":"\/documentation\/pushwooshgrpc\/pushwooshgrpcimplementation","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PushwooshGRPCImplementation"}],"kind":"symbol","type":"topic","title":"PushwooshGRPCImplementation","role":"symbol"},"doc://com.pushwoosh.PushwooshGRPC/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.pushwoosh.PushwooshGRPC\/SH","type":"unresolvable"},"doc://com.pushwoosh.PushwooshGRPC/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.pushwoosh.PushwooshGRPC\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://com.pushwoosh.PushwooshGRPC/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.pushwoosh.PushwooshGRPC\/objc(pl)NSObject","type":"unresolvable"},"doc://com.pushwoosh.PushwooshGRPC/documentation/PushwooshGRPC/PushwooshGRPCImplementation/sendRequest(_:completion:)":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"sendRequest","kind":"identifier"},{"text":"(","kind":"text"},{"text":"PWRequest","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PWRequest"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": ("},{"preciseIdentifier":"c:objc(cs)NSDictionary","kind":"typeIdentifier","text":"NSDictionary"},{"text":"?, ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"sendRequest:completion:"}],"abstract":[],"title":"sendRequest(_:completion:)","kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/pushwooshgrpc\/pushwooshgrpcimplementation\/sendrequest(_:completion:)","identifier":"doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/PushwooshGRPCImplementation\/sendRequest(_:completion:)"},"doc://com.pushwoosh.PushwooshGRPC/documentation/PushwooshGRPC/PushwooshGRPCImplementation/transportName":{"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"transportName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"title":"transportName","type":"topic","url":"\/documentation\/pushwooshgrpc\/pushwooshgrpcimplementation\/transportname","abstract":[],"identifier":"doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/PushwooshGRPCImplementation\/transportName","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"transportName"}]},"doc://com.pushwoosh.PushwooshGRPC/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshGRPC\/s7CVarArgP"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"PushwooshGRPCImplementation"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"value":[{"kind":"identifier","text":"PushwooshGRPCImplementation"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"PushwooshGRPCImplementation","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/PushwooshGRPCImplementation\/init"],"title":"Instance Methods"},{"title":"Type Properties","identifiers":["doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/PushwooshGRPCImplementation\/isAvailable","doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/PushwooshGRPCImplementation\/transportName"]},{"title":"Type Methods","identifiers":["doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/PushwooshGRPCImplementation\/sendRequest(_:completion:)","doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/PushwooshGRPCImplementation\/supportsMethod(_:)"]}],"op":"replace"},{"value":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshGRPC\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.pushwoosh.PushwooshGRPC\/@M@PushwooshBridge@objc(pl)PWTransport"]}],"op":"replace","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushwooshGRPCImplementation"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"supportsMethod:","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshGRPC~1documentation~1PushwooshGRPC~1PushwooshGRPCImplementation~1supportsMethod(_:)\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshGRPC~1documentation~1PushwooshGRPC~1PushwooshGRPCImplementation~1supportsMethod(_:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"supportsMethod:","kind":"identifier"}],"op":"replace"},{"value":"isAvailable","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshGRPC~1documentation~1PushwooshGRPC~1PushwooshGRPCImplementation~1isAvailable\/title"},{"value":[{"text":"isAvailable","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshGRPC~1documentation~1PushwooshGRPC~1PushwooshGRPCImplementation~1isAvailable\/fragments","op":"replace"},{"op":"replace","value":"PushwooshGRPCImplementation","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshGRPC~1documentation~1PushwooshGRPC~1PushwooshGRPCImplementation\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshGRPC~1documentation~1PushwooshGRPC~1PushwooshGRPCImplementation\/fragments","op":"replace","value":[{"text":"PushwooshGRPCImplementation","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshGRPC~1documentation~1PushwooshGRPC~1PushwooshGRPCImplementation~1sendRequest(_:completion:)\/title","op":"replace","value":"sendRequest:completion:"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshGRPC~1documentation~1PushwooshGRPC~1PushwooshGRPCImplementation~1sendRequest(_:completion:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"sendRequest:completion:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshGRPC~1documentation~1PushwooshGRPC~1PushwooshGRPCImplementation~1transportName\/title","value":"transportName","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshGRPC~1documentation~1PushwooshGRPC~1PushwooshGRPCImplementation~1transportName\/fragments","value":[{"kind":"identifier","text":"transportName"}]}]}]}