{"metadata":{"role":"symbol","symbolKind":"method","externalID":"s:17PushwooshInboxKit0aB12CarouselCellC5apply7message10attributesySo22PWInboxMessageProtocol_p_AA0abC10AttributesVtF","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"apply"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"text":"PWInboxMessageProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)PWInboxMessageProtocol"},{"kind":"text","text":", "},{"kind":"externalParam","text":"attributes"},{"text":": ","kind":"text"},{"text":"PushwooshInboxKitAttributes","kind":"typeIdentifier","preciseIdentifier":"s:17PushwooshInboxKit0abC10AttributesV"},{"text":")","kind":"text"}],"modules":[{"name":"PushwooshInboxKit"}],"title":"apply(message:attributes:)","roleHeading":"Instance Method"},"sections":[],"abstract":[{"text":"Configures the cell for the given message and attributes. Subclasses may","type":"text"},{"type":"text","text":" "},{"text":"override to render bespoke layouts; call ","type":"text"},{"code":"super.apply(...)","type":"codeVoice"},{"type":"text","text":" to inherit"},{"text":" ","type":"text"},{"type":"text","text":"dark-mode reactivity."}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCarouselCell"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshinboxkit\/pushwooshinboxcarouselcell\/apply(message:attributes:)"]}],"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCarouselCell\/apply(message:attributes:)","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"override"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"apply","kind":"identifier"},{"kind":"text","text":"("},{"text":"message","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PWInboxMessageProtocol","preciseIdentifier":"c:objc(pl)PWInboxMessageProtocol","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"attributes"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"PushwooshInboxKitAttributes","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitAttributes","preciseIdentifier":"s:17PushwooshInboxKit0abC10AttributesV"},{"kind":"text","text":")"}],"platforms":["iOS"]}]}],"references":{"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxCarouselCell/apply(message:attributes:)":{"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxcarouselcell\/apply(message:attributes:)","role":"symbol","abstract":[{"text":"Configures the cell for the given message and attributes. Subclasses may","type":"text"},{"text":" ","type":"text"},{"text":"override to render bespoke layouts; call ","type":"text"},{"code":"super.apply(...)","type":"codeVoice"},{"type":"text","text":" to inherit"},{"type":"text","text":" "},{"text":"dark-mode reactivity.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"apply","kind":"identifier"},{"text":"(","kind":"text"},{"text":"message","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PWInboxMessageProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)PWInboxMessageProtocol"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"attributes"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:17PushwooshInboxKit0abC10AttributesV","text":"PushwooshInboxKitAttributes","kind":"typeIdentifier"},{"kind":"text","text":")"}],"title":"apply(message:attributes:)","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCarouselCell\/apply(message:attributes:)","type":"topic"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit":{"kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit","title":"PushwooshInboxKit","url":"\/documentation\/pushwooshinboxkit","role":"collection","abstract":[{"text":"Modern UIKit inbox UI powered by Pushwoosh.","type":"text"}],"type":"topic"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxKitAttributes":{"type":"topic","title":"PushwooshInboxKitAttributes","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"PushwooshInboxKitAttributes","kind":"identifier"}],"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxkitattributes","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitAttributes","kind":"symbol","abstract":[{"type":"text","text":"Configuration container for "},{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitViewController","type":"reference","isActive":true},{"type":"text","text":"."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PushwooshInboxKitAttributes"}]},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxKitViewController":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PushwooshInboxKitViewController","kind":"identifier"}],"navigatorTitle":[{"text":"PushwooshInboxKitViewController","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitViewController","title":"PushwooshInboxKitViewController","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxkitviewcontroller","role":"symbol","abstract":[{"type":"text","text":"Modern UIKit inbox controller backed by "},{"type":"codeVoice","code":"PWInboxService"},{"type":"text","text":"."}],"type":"topic"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxCarouselCell":{"role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCarouselCell","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PushwooshInboxCarouselCell","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PushwooshInboxCarouselCell"}],"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxcarouselcell","abstract":[],"title":"PushwooshInboxCarouselCell","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxKitViewController\/title","value":"PushwooshInboxKitViewController"},{"value":[{"kind":"identifier","text":"PushwooshInboxKitViewController"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxKitViewController\/fragments","op":"replace"},{"value":"PushwooshInboxCarouselCell","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxCarouselCell\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxCarouselCell\/fragments","value":[{"text":"PushwooshInboxCarouselCell","kind":"identifier"}]}]}]}