{"metadata":{"modules":[{"name":"PushwooshInboxKit"}],"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"collectionView","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UICollectionView","text":"UICollectionView","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didSelectItemAt"},{"kind":"text","text":": "},{"text":"IndexPath","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":")"}],"role":"symbol","title":"collectionView(_:didSelectItemAt:)","navigatorTitle":[{"kind":"identifier","text":"collectionView:didSelectItemAtIndexPath:"}],"symbolKind":"method","externalID":"c:@CM@PushwooshInboxKit@objc(cs)PushwooshInboxCarouselCell(im)collectionView:didSelectItemAtIndexPath:"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"collectionView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"collectionView","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICollectionView","text":"UICollectionView"},{"kind":"text","text":", "},{"text":"didSelectItemAt","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"indexPath","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath","kind":"typeIdentifier"},{"kind":"text","text":")"}]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCarouselCell","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCarouselCell\/UICollectionViewDelegate-Implementations"]]},"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"UICollectionViewDelegate.collectionView(_:didSelectItemAt:)"},{"type":"text","text":"."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshinboxkit\/pushwooshinboxcarouselcell\/collectionview(_:didselectitemat:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshinboxkit\/pushwooshinboxcarouselcell\/collectionview(_:didselectitemat:)"]}],"kind":"symbol","identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCarouselCell\/collectionView(_:didSelectItemAt:)","interfaceLanguage":"swift"},"references":{"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit":{"kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit","title":"PushwooshInboxKit","url":"\/documentation\/pushwooshinboxkit","role":"collection","abstract":[{"text":"Modern UIKit inbox UI powered by Pushwoosh.","type":"text"}],"type":"topic"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxCarouselCell/collectionView(_:didSelectItemAt:)":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCarouselCell\/collectionView(_:didSelectItemAt:)","kind":"symbol","title":"collectionView(_:didSelectItemAt:)","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxcarouselcell\/collectionview(_:didselectitemat:)","type":"topic","abstract":[],"navigatorTitle":[{"text":"collectionView:didSelectItemAtIndexPath:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"collectionView"},{"text":"(","kind":"text"},{"text":"UICollectionView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICollectionView"},{"kind":"text","text":", "},{"text":"didSelectItemAt","kind":"externalParam"},{"kind":"text","text":": "},{"text":"IndexPath","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":")"}],"role":"symbol"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxCarouselCell/UICollectionViewDelegate-Implementations":{"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxcarouselcell\/uicollectionviewdelegate-implementations","role":"collectionGroup","abstract":[],"kind":"article","title":"UICollectionViewDelegate Implementations","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCarouselCell\/UICollectionViewDelegate-Implementations","type":"topic"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxCarouselCell":{"role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCarouselCell","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PushwooshInboxCarouselCell","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PushwooshInboxCarouselCell"}],"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxcarouselcell","abstract":[],"title":"PushwooshInboxCarouselCell","type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"collectionView:didSelectItemAtIndexPath:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"collectionView:didSelectItemAtIndexPath:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"collectionView:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UICollectionView","text":"UICollectionView","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"collectionView","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"didSelectItemAtIndexPath:"},{"text":"(","kind":"text"},{"text":"NSIndexPath","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSIndexPath"},{"text":" *) ","kind":"text"},{"text":"indexPath","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxCarouselCell~1collectionView(_:didSelectItemAt:)\/title","value":"collectionView:didSelectItemAtIndexPath:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"collectionView:didSelectItemAtIndexPath:"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxCarouselCell~1collectionView(_:didSelectItemAt:)\/fragments"},{"op":"replace","value":"PushwooshInboxCarouselCell","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxCarouselCell\/title"},{"value":[{"kind":"identifier","text":"PushwooshInboxCarouselCell"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxCarouselCell\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}