{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"override","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setHighlighted"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"highlighted","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"animated","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCarouselCell"]]},"sections":[],"metadata":{"externalID":"c:@M@PushwooshInboxKit@objc(cs)PushwooshInboxCarouselCell(im)setHighlighted:animated:","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setHighlighted"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"animated"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"symbolKind":"method","navigatorTitle":[{"text":"setHighlighted:animated:","kind":"identifier"}],"roleHeading":"Instance Method","title":"setHighlighted(_:animated:)","role":"symbol","modules":[{"name":"PushwooshInboxKit"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCarouselCell\/setHighlighted(_:animated:)"},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshinboxkit\/pushwooshinboxcarouselcell\/sethighlighted(_:animated:)"]},{"paths":["\/documentation\/pushwooshinboxkit\/pushwooshinboxcarouselcell\/sethighlighted(_:animated:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Subtle press feedback for taps that land on the card chrome (text block, margins)."}],"references":{"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit":{"kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit","role":"collection","type":"topic","url":"\/documentation\/pushwooshinboxkit","title":"PushwooshInboxKit","abstract":[{"type":"text","text":"Modern UIKit inbox UI powered by Pushwoosh."}]},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxCarouselCell/setHighlighted(_:animated:)":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setHighlighted","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"animated","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}],"abstract":[{"text":"Subtle press feedback for taps that land on the card chrome (text block, margins).","type":"text"}],"navigatorTitle":[{"text":"setHighlighted:animated:","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCarouselCell\/setHighlighted(_:animated:)","title":"setHighlighted(_:animated:)","type":"topic","kind":"symbol","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxcarouselcell\/sethighlighted(_:animated:)"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxCarouselCell":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"PushwooshInboxCarouselCell","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCarouselCell","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PushwooshInboxCarouselCell"}],"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxcarouselcell","type":"topic","abstract":[],"title":"PushwooshInboxCarouselCell"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"setHighlighted:animated:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"text":"setHighlighted:animated:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"setHighlighted:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"highlighted"},{"text":" ","kind":"text"},{"kind":"identifier","text":"animated:"},{"text":"(","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"animated"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxCarouselCell~1setHighlighted(_:animated:)\/title","value":"setHighlighted:animated:","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setHighlighted:animated:"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxCarouselCell~1setHighlighted(_:animated:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxCarouselCell\/title","value":"PushwooshInboxCarouselCell"},{"value":[{"kind":"identifier","text":"PushwooshInboxCarouselCell"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxCarouselCell\/fragments"}]}]}