{"kind":"article","schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"role":"collectionGroup","modules":[{"name":"PushwooshInboxKit"}],"roleHeading":"API Collection","title":"UICollectionViewDelegate Implementations"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCarouselCell\/UICollectionViewDelegate-Implementations"},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCarouselCell"]]},"sections":[],"topicSections":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCarouselCell\/collectionView(_:didSelectItemAt:)"],"title":"Instance Methods","generated":true}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshinboxkit\/pushwooshinboxcarouselcell\/uicollectionviewdelegate-implementations"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshinboxkit\/pushwooshinboxcarouselcell\/uicollectionviewdelegate-implementations"]}],"references":{"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxCarouselCell":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"PushwooshInboxCarouselCell","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCarouselCell","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PushwooshInboxCarouselCell"}],"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxcarouselcell","type":"topic","abstract":[],"title":"PushwooshInboxCarouselCell"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxCarouselCell/collectionView(_:didSelectItemAt:)":{"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"collectionView:didSelectItemAtIndexPath:"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCarouselCell\/collectionView(_:didSelectItemAt:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"collectionView"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UICollectionView","text":"UICollectionView","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didSelectItemAt"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation9IndexPathV","kind":"typeIdentifier","text":"IndexPath"},{"kind":"text","text":")"}],"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxcarouselcell\/collectionview(_:didselectitemat:)","abstract":[],"type":"topic","title":"collectionView(_:didSelectItemAt:)"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit":{"kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit","role":"collection","type":"topic","url":"\/documentation\/pushwooshinboxkit","title":"PushwooshInboxKit","abstract":[{"type":"text","text":"Modern UIKit inbox UI powered by Pushwoosh."}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":[{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCarouselCell\/collectionView(_:didSelectItemAt:)"]}],"path":"\/topicSections","op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":"PushwooshInboxCarouselCell","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxCarouselCell\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxCarouselCell\/fragments","value":[{"kind":"identifier","text":"PushwooshInboxCarouselCell"}]},{"value":"collectionView:didSelectItemAtIndexPath:","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxCarouselCell~1collectionView(_:didSelectItemAt:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxCarouselCell~1collectionView(_:didSelectItemAt:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"collectionView:didSelectItemAtIndexPath:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}