{"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWPurchaseDelegate\/onPW(inAppPurchaseHelperProducts:)","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWPurchaseDelegate"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"externalID":"c:objc(pl)PWPurchaseDelegate(im)onPWInAppPurchaseHelperProducts:","symbolKind":"method","navigatorTitle":[{"text":"onPWInAppPurchaseHelperProducts:","kind":"identifier"}],"roleHeading":"Instance Method","title":"onPW(inAppPurchaseHelperProducts:)","role":"symbol","platforms":[{"beta":false,"introducedAt":"3.0","deprecated":false,"unavailable":false,"name":"iOS"}],"modules":[{"name":"PushwooshFramework"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onPW","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"inAppPurchaseHelperProducts"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKProduct","text":"SKProduct"},{"text":"]?)","kind":"text"}]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onPW"},{"kind":"text","text":"("},{"text":"inAppPurchaseHelperProducts","kind":"externalParam"},{"kind":"text","text":" "},{"text":"products","kind":"internalParam"},{"text":": [","kind":"text"},{"text":"SKProduct","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKProduct"},{"text":"]?)","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"content":[{"inlineContent":[{"text":"Array of SKProduct instances representing available products","type":"text"}],"type":"paragraph"}],"name":"products"}],"kind":"parameters"},{"content":[{"level":2,"anchor":"discussion","type":"heading","text":"Discussion"},{"inlineContent":[{"type":"text","text":"This method is called when StoreKit returns available products for in-app purchases initiated from rich media."},{"type":"text","text":" "},{"text":"Use this to display product information or prepare the purchase flow.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"abstract":[{"text":"Tells the delegate that the application received the array of products.","type":"text"}],"variants":[{"paths":["\/documentation\/pushwooshframework\/pwpurchasedelegate\/onpw(inapppurchasehelperproducts:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pushwooshframework\/pwpurchasedelegate\/onpw(inapppurchasehelperproducts:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWPurchaseDelegate":{"title":"PWPurchaseDelegate","role":"symbol","url":"\/documentation\/pushwooshframework\/pwpurchasedelegate","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWPurchaseDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PWPurchaseDelegate"}],"navigatorTitle":[{"kind":"identifier","text":"PWPurchaseDelegate"}],"abstract":[{"type":"text","text":"Delegate protocol for handling in-app purchase events from rich media."}],"type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"abstract":[],"kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","url":"\/documentation\/pushwooshframework","type":"topic","role":"collection","title":"PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWPurchaseDelegate/onPW(inAppPurchaseHelperProducts:)":{"navigatorTitle":[{"text":"onPWInAppPurchaseHelperProducts:","kind":"identifier"}],"url":"\/documentation\/pushwooshframework\/pwpurchasedelegate\/onpw(inapppurchasehelperproducts:)","title":"onPW(inAppPurchaseHelperProducts:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onPW","kind":"identifier"},{"text":"(","kind":"text"},{"text":"inAppPurchaseHelperProducts","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKProduct","text":"SKProduct"},{"text":"]?)","kind":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWPurchaseDelegate\/onPW(inAppPurchaseHelperProducts:)","type":"topic","kind":"symbol","abstract":[{"text":"Tells the delegate that the application received the array of products.","type":"text"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"onPWInAppPurchaseHelperProducts:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"onPWInAppPurchaseHelperProducts:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"onPWInAppPurchaseHelperProducts:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<SKProduct *>","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"products","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWPurchaseDelegate\/title","op":"replace","value":"PWPurchaseDelegate"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWPurchaseDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"PWPurchaseDelegate"}]},{"op":"replace","value":"onPWInAppPurchaseHelperProducts:","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWPurchaseDelegate~1onPW(inAppPurchaseHelperProducts:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWPurchaseDelegate~1onPW(inAppPurchaseHelperProducts:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onPWInAppPurchaseHelperProducts:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}