{"sections":[],"kind":"symbol","metadata":{"title":"onPW(inAppPurchaseHelperPaymentComplete:)","externalID":"c:objc(pl)PWPurchaseDelegate(im)onPWInAppPurchaseHelperPaymentComplete:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onPW"},{"kind":"text","text":"("},{"kind":"externalParam","text":"inAppPurchaseHelperPaymentComplete"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?)","kind":"text"}],"roleHeading":"Instance Method","modules":[{"name":"PushwooshFramework"}],"role":"symbol","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"onPWInAppPurchaseHelperPaymentComplete:"}],"required":true},"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWPurchaseDelegate\/onPW(inAppPurchaseHelperPaymentComplete:)","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Tells the delegate that the transaction is in queue and the user has been charged.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pwpurchasedelegate\/onpw(inapppurchasehelperpaymentcomplete:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pwpurchasedelegate\/onpw(inapppurchasehelperpaymentcomplete:)"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onPW"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"inAppPurchaseHelperPaymentComplete"},{"kind":"text","text":" "},{"text":"identifier","kind":"internalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"Product identifier agreed upon with the store","type":"text"}],"type":"paragraph"}],"name":"identifier"}]},{"kind":"content","content":[{"level":2,"anchor":"discussion","text":"Discussion","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"This method is called when a purchase transaction completes successfully. The transaction has been added","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"to the payment queue and the user’s account has been charged."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Use this method to unlock content, update your app’s state, or provide confirmation to the user."}]}]}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWPurchaseDelegate"]]},"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWPurchaseDelegate":{"navigatorTitle":[{"kind":"identifier","text":"PWPurchaseDelegate"}],"abstract":[{"type":"text","text":"Delegate protocol for handling in-app purchase events from rich media."}],"kind":"symbol","title":"PWPurchaseDelegate","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"PWPurchaseDelegate","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWPurchaseDelegate","url":"\/documentation\/pushwooshframework\/pwpurchasedelegate"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"title":"PushwooshFramework","kind":"symbol","abstract":[{"text":"Push notification SDK for iOS applications.","type":"text"}],"role":"collection","type":"topic","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWPurchaseDelegate/onPW(inAppPurchaseHelperPaymentComplete:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onPW"},{"text":"(","kind":"text"},{"text":"inAppPurchaseHelperPaymentComplete","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?)","kind":"text"}],"required":true,"kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWPurchaseDelegate\/onPW(inAppPurchaseHelperPaymentComplete:)","abstract":[{"type":"text","text":"Tells the delegate that the transaction is in queue and the user has been charged."}],"title":"onPW(inAppPurchaseHelperPaymentComplete:)","type":"topic","role":"symbol","navigatorTitle":[{"text":"onPWInAppPurchaseHelperPaymentComplete:","kind":"identifier"}],"url":"\/documentation\/pushwooshframework\/pwpurchasedelegate\/onpw(inapppurchasehelperpaymentcomplete:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","value":"onPWInAppPurchaseHelperPaymentComplete:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onPWInAppPurchaseHelperPaymentComplete:"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"onPWInAppPurchaseHelperPaymentComplete:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWPurchaseDelegate\/title","value":"PWPurchaseDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWPurchaseDelegate\/fragments","value":[{"text":"PWPurchaseDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWPurchaseDelegate~1onPW(inAppPurchaseHelperPaymentComplete:)\/title","value":"onPWInAppPurchaseHelperPaymentComplete:"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWPurchaseDelegate~1onPW(inAppPurchaseHelperPaymentComplete:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onPWInAppPurchaseHelperPaymentComplete:"}]}]}]}