{"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWPurchaseDelegate"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pwpurchasedelegate\/onpw(inapppurchasehelperrestorecompletedtransactionsfailed:)"]},{"paths":["\/documentation\/pushwooshframework\/pwpurchasedelegate\/onpw(inapppurchasehelperrestorecompletedtransactionsfailed:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onPW","kind":"identifier"},{"kind":"text","text":"("},{"text":"inAppPurchaseHelperRestoreCompletedTransactionsFailed","kind":"externalParam"},{"kind":"text","text":" "},{"text":"error","kind":"internalParam"},{"text":": (any ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"text":")?)","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"error","content":[{"inlineContent":[{"text":"Error describing why the restore operation failed","type":"text"}],"type":"paragraph"}]}]},{"kind":"content","content":[{"anchor":"discussion","type":"heading","text":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"This method is called when the restore purchases operation fails. Use this to inform the user that"},{"type":"text","text":" "},{"type":"text","text":"their purchases could not be restored and provide appropriate error handling."}]}]}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWPurchaseDelegate\/onPW(inAppPurchaseHelperRestoreCompletedTransactionsFailed:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Tells the delegate that an error occurred while restoring transactions."}],"metadata":{"symbolKind":"method","required":true,"role":"symbol","modules":[{"name":"PushwooshFramework"}],"roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onPW"},{"kind":"text","text":"("},{"text":"inAppPurchaseHelperRestoreCompletedTransactionsFailed","kind":"externalParam"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"text":")?)","kind":"text"}],"title":"onPW(inAppPurchaseHelperRestoreCompletedTransactionsFailed:)","navigatorTitle":[{"kind":"identifier","text":"onPWInAppPurchaseHelperRestoreCompletedTransactionsFailed:"}],"externalID":"c:objc(pl)PWPurchaseDelegate(im)onPWInAppPurchaseHelperRestoreCompletedTransactionsFailed:"},"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWPurchaseDelegate":{"url":"\/documentation\/pushwooshframework\/pwpurchasedelegate","navigatorTitle":[{"kind":"identifier","text":"PWPurchaseDelegate"}],"abstract":[{"type":"text","text":"Delegate protocol for handling in-app purchase events from rich media."}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWPurchaseDelegate","kind":"symbol","title":"PWPurchaseDelegate","type":"topic","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"PWPurchaseDelegate","kind":"identifier"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","abstract":[{"text":"Push notification SDK for iOS applications.","type":"text"}],"title":"PushwooshFramework","kind":"symbol","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","url":"\/documentation\/pushwooshframework"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWPurchaseDelegate/onPW(inAppPurchaseHelperRestoreCompletedTransactionsFailed:)":{"required":true,"role":"symbol","abstract":[{"text":"Tells the delegate that an error occurred while restoring transactions.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onPW"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"inAppPurchaseHelperRestoreCompletedTransactionsFailed"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"text":")?)","kind":"text"}],"title":"onPW(inAppPurchaseHelperRestoreCompletedTransactionsFailed:)","navigatorTitle":[{"kind":"identifier","text":"onPWInAppPurchaseHelperRestoreCompletedTransactionsFailed:"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWPurchaseDelegate\/onPW(inAppPurchaseHelperRestoreCompletedTransactionsFailed:)","url":"\/documentation\/pushwooshframework\/pwpurchasedelegate\/onpw(inapppurchasehelperrestorecompletedtransactionsfailed:)"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","value":"onPWInAppPurchaseHelperRestoreCompletedTransactionsFailed:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"onPWInAppPurchaseHelperRestoreCompletedTransactionsFailed:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"onPWInAppPurchaseHelperRestoreCompletedTransactionsFailed:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier","text":"NSError"},{"kind":"text","text":" *) "},{"text":"error","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace"},{"value":"PWPurchaseDelegate","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWPurchaseDelegate\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWPurchaseDelegate\/fragments","value":[{"text":"PWPurchaseDelegate","kind":"identifier"}]},{"op":"replace","value":"onPWInAppPurchaseHelperRestoreCompletedTransactionsFailed:","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWPurchaseDelegate~1onPW(inAppPurchaseHelperRestoreCompletedTransactionsFailed:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWPurchaseDelegate~1onPW(inAppPurchaseHelperRestoreCompletedTransactionsFailed:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onPWInAppPurchaseHelperRestoreCompletedTransactionsFailed:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}