{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onPW","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"inAppPurchaseHelperCallPromotedPurchase"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?)"}],"languages":["swift"]}],"kind":"declarations"},{"content":[{"type":"heading","level":2,"anchor":"Overview","text":"Overview"},{"inlineContent":[{"type":"text","text":"This method is called when a user initiates an in-app purchase directly from the App Store (promoted IAP). Use this to handle the promoted purchase flow and start the transaction."}],"type":"paragraph"},{"inlineContent":[{"text":"Promoted purchases allow users to discover and buy in-app purchases directly from the App Store product page, before even launching your app.","type":"text"}],"type":"paragraph"},{"text":"Example","type":"heading","anchor":"Example","level":2},{"inlineContent":[{"type":"text","text":"Handle promoted purchase from App Store:"}],"type":"paragraph"},{"type":"codeListing","syntax":"swift","code":["class PurchaseManager: NSObject, PWPurchaseDelegate {","","    func onPW(inAppPurchaseHelperCallPromotedPurchase identifier: String) {","        analytics.track(\"promoted_purchase_initiated\", properties: [","            \"product_id\": identifier","        ])","","        if shouldDeferPurchase(identifier) {","            storeDeferredPurchase(identifier)","            showOnboardingFlow()","        } else {","            startPurchaseFlow(productIdentifier: identifier)","        }","    }","","    private func shouldDeferPurchase(_ identifier: String) -> Bool {","        return !userManager.isLoggedIn || !onboardingManager.isComplete","    }","}"]}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pwpurchasedelegate\/onpw(inapppurchasehelpercallpromotedpurchase:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pwpurchasedelegate\/onpw(inapppurchasehelpercallpromotedpurchase:)"]}],"kind":"symbol","abstract":[{"text":"Tells the delegate that a user initiates an IAP buy from the App Store.","type":"text"}],"metadata":{"externalID":"c:objc(pl)PWPurchaseDelegate(im)onPWInAppPurchaseHelperCallPromotedPurchase:","symbolKind":"method","roleHeading":"Instance Method","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"onPWInAppPurchaseHelperCallPromotedPurchase:"}],"title":"onPW(inAppPurchaseHelperCallPromotedPurchase:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onPW","kind":"identifier"},{"kind":"text","text":"("},{"text":"inAppPurchaseHelperCallPromotedPurchase","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"modules":[{"name":"PushwooshFramework"}],"required":true},"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWPurchaseDelegate\/onPW(inAppPurchaseHelperCallPromotedPurchase:)","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWPurchaseDelegate"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWPurchaseDelegate":{"abstract":[{"type":"text","text":"Delegate protocol for handling in-app purchase events from rich media."}],"navigatorTitle":[{"text":"PWPurchaseDelegate","kind":"identifier"}],"role":"symbol","url":"\/documentation\/pushwooshframework\/pwpurchasedelegate","type":"topic","title":"PWPurchaseDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"PWPurchaseDelegate","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWPurchaseDelegate"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWPurchaseDelegate/onPW(inAppPurchaseHelperCallPromotedPurchase:)":{"title":"onPW(inAppPurchaseHelperCallPromotedPurchase:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onPW","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"inAppPurchaseHelperCallPromotedPurchase"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?)","kind":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWPurchaseDelegate\/onPW(inAppPurchaseHelperCallPromotedPurchase:)","url":"\/documentation\/pushwooshframework\/pwpurchasedelegate\/onpw(inapppurchasehelpercallpromotedpurchase:)","abstract":[{"text":"Tells the delegate that a user initiates an IAP buy from the App Store.","type":"text"}],"required":true,"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"onPWInAppPurchaseHelperCallPromotedPurchase:"}],"role":"symbol"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"url":"\/documentation\/pushwooshframework","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","kind":"symbol","abstract":[{"text":"Push notification SDK for iOS applications.","type":"text"}],"role":"collection","title":"PushwooshFramework"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"onPWInAppPurchaseHelperCallPromotedPurchase:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onPWInAppPurchaseHelperCallPromotedPurchase:"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"text":"onPWInAppPurchaseHelperCallPromotedPurchase:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"identifier","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWPurchaseDelegate\/title","value":"PWPurchaseDelegate"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWPurchaseDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"PWPurchaseDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWPurchaseDelegate~1onPW(inAppPurchaseHelperCallPromotedPurchase:)\/title","value":"onPWInAppPurchaseHelperCallPromotedPurchase:"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWPurchaseDelegate~1onPW(inAppPurchaseHelperCallPromotedPurchase:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onPWInAppPurchaseHelperCallPromotedPurchase:","kind":"identifier"}]}]}]}