{"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWPurchaseDelegate"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"optional"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onPW","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"inAppPurchaseHelperPaymentFailedProductIdentifier"},{"text":" ","kind":"text"},{"text":"identifier","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"text":"error","kind":"externalParam"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":")?)","kind":"text"}]}],"kind":"declarations"},{"parameters":[{"name":"identifier","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The unique product identifier"}]}]},{"name":"error","content":[{"inlineContent":[{"type":"text","text":"The error that caused the transaction to fail"}],"type":"paragraph"}]}],"kind":"parameters"},{"content":[{"type":"heading","anchor":"discussion","text":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"This method is called when a purchase transaction fails or is cancelled by the user. Use this to handle errors,"},{"type":"text","text":" "},{"type":"text","text":"display appropriate messages to the user, or log the failure for analytics."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Common reasons for failure include user cancellation, invalid product IDs, or network issues."}]}],"kind":"content"}],"abstract":[{"type":"text","text":"Tells the delegate that the transaction was cancelled or failed before being added to the server queue."}],"seeAlsoSections":[{"title":"Purchase Events","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWPurchaseDelegate\/onPW(inAppPurchaseHelperPaymentComplete:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWPurchaseDelegate\/onPW(inAppPurchaseHelperCallPromotedPurchase:)"],"generated":true}],"kind":"symbol","variants":[{"paths":["\/documentation\/pushwooshframework\/pwpurchasedelegate\/onpw(inapppurchasehelperpaymentfailedproductidentifier:error:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pushwooshframework\/pwpurchasedelegate\/onpw(inapppurchasehelperpaymentfailedproductidentifier:error:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWPurchaseDelegate\/onPW(inAppPurchaseHelperPaymentFailedProductIdentifier:error:)"},"sections":[],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"onPWInAppPurchaseHelperPaymentFailedProductIdentifier:error:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onPW","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"inAppPurchaseHelperPaymentFailedProductIdentifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"text":"error","kind":"externalParam"},{"text":": (any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")?)","kind":"text"}],"modules":[{"name":"PushwooshFramework"}],"externalID":"c:objc(pl)PWPurchaseDelegate(im)onPWInAppPurchaseHelperPaymentFailedProductIdentifier:error:","title":"onPW(inAppPurchaseHelperPaymentFailedProductIdentifier:error:)","symbolKind":"method","role":"symbol","required":true,"roleHeading":"Instance Method"},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWPurchaseDelegate/onPW(inAppPurchaseHelperCallPromotedPurchase:)":{"url":"\/documentation\/pushwooshframework\/pwpurchasedelegate\/onpw(inapppurchasehelpercallpromotedpurchase:)","navigatorTitle":[{"text":"onPWInAppPurchaseHelperCallPromotedPurchase:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onPW","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"inAppPurchaseHelperCallPromotedPurchase"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?)"}],"title":"onPW(inAppPurchaseHelperCallPromotedPurchase:)","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWPurchaseDelegate\/onPW(inAppPurchaseHelperCallPromotedPurchase:)","kind":"symbol","role":"symbol","type":"topic","abstract":[{"text":"Tells the delegate that a user initiates an IAP buy from the App Store.","type":"text"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWPurchaseDelegate/onPW(inAppPurchaseHelperPaymentComplete:)":{"url":"\/documentation\/pushwooshframework\/pwpurchasedelegate\/onpw(inapppurchasehelperpaymentcomplete:)","navigatorTitle":[{"text":"onPWInAppPurchaseHelperPaymentComplete:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"onPW","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"inAppPurchaseHelperPaymentComplete"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?)","kind":"text"}],"title":"onPW(inAppPurchaseHelperPaymentComplete:)","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWPurchaseDelegate\/onPW(inAppPurchaseHelperPaymentComplete:)","role":"symbol","type":"topic","abstract":[{"text":"Tells the delegate that the transaction is in queue and the user has been charged.","type":"text"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"title":"PushwooshFramework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","kind":"symbol","type":"topic","url":"\/documentation\/pushwooshframework","role":"collection","abstract":[]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWPurchaseDelegate":{"abstract":[{"type":"text","text":"Delegate protocol for handling in-app purchase events from rich media."}],"navigatorTitle":[{"kind":"identifier","text":"PWPurchaseDelegate"}],"type":"topic","kind":"symbol","url":"\/documentation\/pushwooshframework\/pwpurchasedelegate","title":"PWPurchaseDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"PWPurchaseDelegate","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWPurchaseDelegate","role":"symbol"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWPurchaseDelegate/onPW(inAppPurchaseHelperPaymentFailedProductIdentifier:error:)":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWPurchaseDelegate\/onPW(inAppPurchaseHelperPaymentFailedProductIdentifier:error:)","role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/pushwooshframework\/pwpurchasedelegate\/onpw(inapppurchasehelperpaymentfailedproductidentifier:error:)","required":true,"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onPW","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"inAppPurchaseHelperPaymentFailedProductIdentifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"text":"error","kind":"externalParam"},{"kind":"text","text":": (any "},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"title":"onPW(inAppPurchaseHelperPaymentFailedProductIdentifier:error:)","navigatorTitle":[{"kind":"identifier","text":"onPWInAppPurchaseHelperPaymentFailedProductIdentifier:error:"}],"abstract":[{"text":"Tells the delegate that the transaction was cancelled or failed before being added to the server queue.","type":"text"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"onPWInAppPurchaseHelperPaymentFailedProductIdentifier:error:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onPWInAppPurchaseHelperPaymentFailedProductIdentifier:error:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":[{"title":"Purchase Events","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWPurchaseDelegate\/onPW(inAppPurchaseHelperPaymentComplete:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWPurchaseDelegate\/onPW(inAppPurchaseHelperCallPromotedPurchase:)"],"generated":true}],"path":"\/seeAlsoSections","op":"replace"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"onPWInAppPurchaseHelperPaymentFailedProductIdentifier:"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"identifier"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"text":"(","kind":"text"},{"text":"NSError","preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"onPWInAppPurchaseHelperCallPromotedPurchase:","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWPurchaseDelegate~1onPW(inAppPurchaseHelperCallPromotedPurchase:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWPurchaseDelegate~1onPW(inAppPurchaseHelperCallPromotedPurchase:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onPWInAppPurchaseHelperCallPromotedPurchase:","kind":"identifier"}]},{"value":"onPWInAppPurchaseHelperPaymentComplete:","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWPurchaseDelegate~1onPW(inAppPurchaseHelperPaymentComplete:)\/title","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"onPWInAppPurchaseHelperPaymentComplete:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWPurchaseDelegate~1onPW(inAppPurchaseHelperPaymentComplete:)\/fragments"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWPurchaseDelegate\/title","value":"PWPurchaseDelegate","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWPurchaseDelegate\/fragments","value":[{"text":"PWPurchaseDelegate","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWPurchaseDelegate~1onPW(inAppPurchaseHelperPaymentFailedProductIdentifier:error:)\/title","value":"onPWInAppPurchaseHelperPaymentFailedProductIdentifier:error:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onPWInAppPurchaseHelperPaymentFailedProductIdentifier:error:"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWPurchaseDelegate~1onPW(inAppPurchaseHelperPaymentFailedProductIdentifier:error:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}