{"abstract":[{"type":"text","text":"Implementation of persistent HWID storage using iOS Keychain."}],"topicSections":[{"title":"Type Properties","identifiers":["doc:\/\/com.pushwoosh.PushwooshKeychain\/documentation\/PushwooshKeychain\/PushwooshKeychainImplementation\/currentEnvironment","doc:\/\/com.pushwoosh.PushwooshKeychain\/documentation\/PushwooshKeychain\/PushwooshKeychainImplementation\/isEnabled","doc:\/\/com.pushwoosh.PushwooshKeychain\/documentation\/PushwooshKeychain\/PushwooshKeychainImplementation\/shared"]},{"identifiers":["doc:\/\/com.pushwoosh.PushwooshKeychain\/documentation\/PushwooshKeychain\/PushwooshKeychainImplementation\/clearPersistentHWID()","doc:\/\/com.pushwoosh.PushwooshKeychain\/documentation\/PushwooshKeychain\/PushwooshKeychainImplementation\/getPersistentHWID()","doc:\/\/com.pushwoosh.PushwooshKeychain\/documentation\/PushwooshKeychain\/PushwooshKeychainImplementation\/keychain()"],"title":"Type Methods"}],"metadata":{"modules":[{"name":"PushwooshKeychain"}],"title":"PushwooshKeychainImplementation","navigatorTitle":[{"text":"PushwooshKeychainImplementation","kind":"identifier"}],"externalID":"c:@M@PushwooshKeychain@objc(cs)PushwooshKeychainImplementation","roleHeading":"Class","platforms":[{"name":"iOS","unavailable":false,"introducedAt":"12.0","beta":false,"deprecated":false}],"symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PushwooshKeychainImplementation","kind":"identifier"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshKeychain\/documentation\/PushwooshKeychain"]]},"kind":"symbol","identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshKeychain\/documentation\/PushwooshKeychain\/PushwooshKeychainImplementation","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(PushwooshKeychainImplementation) ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PushwooshKeychainImplementation","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","level":2,"text":"Overview","anchor":"overview"},{"inlineContent":[{"text":"This module provides persistent device identification that survives app reinstallation.","type":"text"},{"text":" ","type":"text"},{"text":"It automatically disables itself in App Store builds.","type":"text"}],"type":"paragraph"}]}],"sections":[],"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.pushwoosh.PushwooshKeychain\/objc(cs)NSObject"]},{"identifiers":["doc:\/\/com.pushwoosh.PushwooshKeychain\/objc(pl)NSObject","doc:\/\/com.pushwoosh.PushwooshKeychain\/@M@PushwooshBridge@objc(pl)PWKeychain","doc:\/\/com.pushwoosh.PushwooshKeychain\/s7CVarArgP","doc:\/\/com.pushwoosh.PushwooshKeychain\/s28CustomDebugStringConvertibleP","doc:\/\/com.pushwoosh.PushwooshKeychain\/s23CustomStringConvertibleP","doc:\/\/com.pushwoosh.PushwooshKeychain\/SQ","doc:\/\/com.pushwoosh.PushwooshKeychain\/SH"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"variants":[{"paths":["\/documentation\/pushwooshkeychain\/pushwooshkeychainimplementation"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshkeychain\/pushwooshkeychainimplementation"]}],"references":{"doc://com.pushwoosh.PushwooshKeychain/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshKeychain\/s7CVarArgP"},"doc://com.pushwoosh.PushwooshKeychain/documentation/PushwooshKeychain/PushwooshKeychainImplementation/currentEnvironment":{"title":"currentEnvironment","navigatorTitle":[{"text":"currentEnvironment","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshKeychain\/documentation\/PushwooshKeychain\/PushwooshKeychainImplementation\/currentEnvironment","type":"topic","abstract":[{"text":"Returns the current application environment.","type":"text"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"currentEnvironment"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@PushwooshBridge@E@PWAppEnvironment","text":"PWAppEnvironment","kind":"typeIdentifier"}],"role":"symbol","kind":"symbol","url":"\/documentation\/pushwooshkeychain\/pushwooshkeychainimplementation\/currentenvironment"},"doc://com.pushwoosh.PushwooshKeychain/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.pushwoosh.PushwooshKeychain\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://com.pushwoosh.PushwooshKeychain/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.pushwoosh.PushwooshKeychain\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://com.pushwoosh.PushwooshKeychain/documentation/PushwooshKeychain/PushwooshKeychainImplementation/shared":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shared","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@PushwooshKeychain@objc(cs)PushwooshKeychainImplementation","text":"PushwooshKeychainImplementation"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshKeychain\/documentation\/PushwooshKeychain\/PushwooshKeychainImplementation\/shared","title":"shared","url":"\/documentation\/pushwooshkeychain\/pushwooshkeychainimplementation\/shared","abstract":[{"type":"text","text":"Shared singleton instance."}],"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"shared"}]},"doc://com.pushwoosh.PushwooshKeychain/documentation/PushwooshKeychain/PushwooshKeychainImplementation/clearPersistentHWID()":{"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshKeychain\/documentation\/PushwooshKeychain\/PushwooshKeychainImplementation\/clearPersistentHWID()","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"clearPersistentHWID"},{"kind":"text","text":"()"}],"title":"clearPersistentHWID()","kind":"symbol","url":"\/documentation\/pushwooshkeychain\/pushwooshkeychainimplementation\/clearpersistenthwid()","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"clearPersistentHWID"}],"abstract":[{"type":"text","text":"Clears the stored HWID from Keychain."}]},"doc://com.pushwoosh.PushwooshKeychain/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/com.pushwoosh.PushwooshKeychain\/objc(cs)NSObject","type":"unresolvable"},"doc://com.pushwoosh.PushwooshKeychain/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshKeychain\/SH"},"doc://com.pushwoosh.PushwooshKeychain/documentation/PushwooshKeychain/PushwooshKeychainImplementation/init":{"title":"init","navigatorTitle":[{"kind":"identifier","text":"init"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshKeychain\/documentation\/PushwooshKeychain\/PushwooshKeychainImplementation\/init","type":"topic","abstract":[],"fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"role":"symbol","url":"\/documentation\/pushwooshkeychain\/pushwooshkeychainimplementation\/init","kind":"symbol"},"doc://com.pushwoosh.PushwooshKeychain/documentation/PushwooshKeychain/PushwooshKeychainImplementation/isEnabled":{"title":"isEnabled","navigatorTitle":[{"text":"isEnabled","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshKeychain\/documentation\/PushwooshKeychain\/PushwooshKeychainImplementation\/isEnabled","type":"topic","abstract":[{"text":"Indicates whether persistent HWID storage is enabled.","type":"text"}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"isEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"role":"symbol","kind":"symbol","url":"\/documentation\/pushwooshkeychain\/pushwooshkeychainimplementation\/isenabled"},"doc://com.pushwoosh.PushwooshKeychain/@M@PushwooshBridge@objc(pl)PWKeychain":{"title":"PWKeychain","type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshKeychain\/@M@PushwooshBridge@objc(pl)PWKeychain"},"doc://com.pushwoosh.PushwooshKeychain/documentation/PushwooshKeychain":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshKeychain\/documentation\/PushwooshKeychain","title":"PushwooshKeychain","role":"collection","url":"\/documentation\/pushwooshkeychain","abstract":[]},"doc://com.pushwoosh.PushwooshKeychain/documentation/PushwooshKeychain/PushwooshKeychainImplementation":{"url":"\/documentation\/pushwooshkeychain\/pushwooshkeychainimplementation","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PushwooshKeychainImplementation","kind":"identifier"}],"abstract":[{"type":"text","text":"Implementation of persistent HWID storage using iOS Keychain."}],"identifier":"doc:\/\/com.pushwoosh.PushwooshKeychain\/documentation\/PushwooshKeychain\/PushwooshKeychainImplementation","navigatorTitle":[{"kind":"identifier","text":"PushwooshKeychainImplementation"}],"title":"PushwooshKeychainImplementation","kind":"symbol"},"doc://com.pushwoosh.PushwooshKeychain/documentation/PushwooshKeychain/PushwooshKeychainImplementation/keychain()":{"title":"keychain()","navigatorTitle":[{"text":"keychain","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshKeychain\/documentation\/PushwooshKeychain\/PushwooshKeychainImplementation\/keychain()","type":"topic","abstract":[{"text":"Returns the Keychain implementation class.","type":"text"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"keychain"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:s8AnyClassa","text":"AnyClass","kind":"typeIdentifier"}],"role":"symbol","kind":"symbol","url":"\/documentation\/pushwooshkeychain\/pushwooshkeychainimplementation\/keychain()"},"doc://com.pushwoosh.PushwooshKeychain/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.pushwoosh.PushwooshKeychain\/SQ","type":"unresolvable"},"doc://com.pushwoosh.PushwooshKeychain/documentation/PushwooshKeychain/PushwooshKeychainImplementation/getPersistentHWID()":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"getPersistentHWID"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"title":"getPersistentHWID()","identifier":"doc:\/\/com.pushwoosh.PushwooshKeychain\/documentation\/PushwooshKeychain\/PushwooshKeychainImplementation\/getPersistentHWID()","abstract":[{"text":"Returns the persistent HWID from Keychain, or nil if not available.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"getPersistentHWID","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/pushwooshkeychain\/pushwooshkeychainimplementation\/getpersistenthwid()"},"doc://com.pushwoosh.PushwooshKeychain/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.pushwoosh.PushwooshKeychain\/objc(pl)NSObject","type":"unresolvable"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/platforms","value":[{"name":"iOS","unavailable":false,"introducedAt":"12.0","beta":false,"deprecated":false}]},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"PushwooshKeychainImplementation"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","value":[{"text":"PushwooshKeychainImplementation","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"PushwooshKeychainImplementation","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.pushwoosh.PushwooshKeychain\/documentation\/PushwooshKeychain\/PushwooshKeychainImplementation\/init"]},{"identifiers":["doc:\/\/com.pushwoosh.PushwooshKeychain\/documentation\/PushwooshKeychain\/PushwooshKeychainImplementation\/currentEnvironment","doc:\/\/com.pushwoosh.PushwooshKeychain\/documentation\/PushwooshKeychain\/PushwooshKeychainImplementation\/isEnabled","doc:\/\/com.pushwoosh.PushwooshKeychain\/documentation\/PushwooshKeychain\/PushwooshKeychainImplementation\/shared"],"title":"Type Properties"},{"identifiers":["doc:\/\/com.pushwoosh.PushwooshKeychain\/documentation\/PushwooshKeychain\/PushwooshKeychainImplementation\/clearPersistentHWID()","doc:\/\/com.pushwoosh.PushwooshKeychain\/documentation\/PushwooshKeychain\/PushwooshKeychainImplementation\/getPersistentHWID()","doc:\/\/com.pushwoosh.PushwooshKeychain\/documentation\/PushwooshKeychain\/PushwooshKeychainImplementation\/keychain()"],"title":"Type Methods"}]},{"value":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshKeychain\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"title":"Conforms To","identifiers":["doc:\/\/com.pushwoosh.PushwooshKeychain\/@M@PushwooshBridge@objc(pl)PWKeychain"],"kind":"relationships","type":"conformsTo"}],"path":"\/relationshipsSections","op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PushwooshKeychainImplementation","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"currentEnvironment","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshKeychain~1documentation~1PushwooshKeychain~1PushwooshKeychainImplementation~1currentEnvironment\/title","op":"replace"},{"value":[{"kind":"identifier","text":"currentEnvironment"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshKeychain~1documentation~1PushwooshKeychain~1PushwooshKeychainImplementation~1currentEnvironment\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshKeychain~1documentation~1PushwooshKeychain~1PushwooshKeychainImplementation~1shared\/title","value":"shared","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshKeychain~1documentation~1PushwooshKeychain~1PushwooshKeychainImplementation~1shared\/fragments","value":[{"text":"shared","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshKeychain~1documentation~1PushwooshKeychain~1PushwooshKeychainImplementation~1clearPersistentHWID()\/title","value":"clearPersistentHWID"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshKeychain~1documentation~1PushwooshKeychain~1PushwooshKeychainImplementation~1clearPersistentHWID()\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"clearPersistentHWID"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshKeychain~1documentation~1PushwooshKeychain~1PushwooshKeychainImplementation~1isEnabled\/title","value":"isEnabled"},{"op":"replace","value":[{"kind":"identifier","text":"isEnabled"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshKeychain~1documentation~1PushwooshKeychain~1PushwooshKeychainImplementation~1isEnabled\/fragments"},{"value":"PushwooshKeychainImplementation","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshKeychain~1documentation~1PushwooshKeychain~1PushwooshKeychainImplementation\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshKeychain~1documentation~1PushwooshKeychain~1PushwooshKeychainImplementation\/fragments","value":[{"text":"PushwooshKeychainImplementation","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshKeychain~1documentation~1PushwooshKeychain~1PushwooshKeychainImplementation~1keychain()\/title","value":"keychain","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshKeychain~1documentation~1PushwooshKeychain~1PushwooshKeychainImplementation~1keychain()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"keychain"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshKeychain~1documentation~1PushwooshKeychain~1PushwooshKeychainImplementation~1getPersistentHWID()\/title","value":"getPersistentHWID"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"getPersistentHWID"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshKeychain~1documentation~1PushwooshKeychain~1PushwooshKeychainImplementation~1getPersistentHWID()\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}