{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handle"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"request","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UNNotificationRequest","text":"UNNotificationRequest"},{"text":", ","kind":"text"},{"text":"withAppGroups","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"appGroupsName"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"contentHandler","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"keyword","text":"@escaping"},{"kind":"text","text":" ("},{"preciseIdentifier":"c:objc(cs)UNNotificationContent","text":"UNNotificationContent","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")"}],"languages":["swift"]}]},{"content":[{"text":"Discussion","level":2,"type":"heading","anchor":"discussion"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"text":"(void)didReceiveNotificationRequest:(UNNotificationRequest *)request withContentHandler:(void (^)(UNNotificationContent * _Nonnull))contentHandler {","type":"text"},{"type":"text","text":" "},{"type":"text","text":"self.contentHandler = contentHandler;"},{"text":" ","type":"text"},{"text":"self.bestAttemptContent = [request.content mutableCopy];","type":"text"}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"type":"text","text":"[[PWNotificationExtensionManager sharedManager] handleNotificationRequest:request"},{"text":" ","type":"text"},{"text":"withAppGroups:@“group.com.example_domain.example_app_name”","type":"text"},{"text":" ","type":"text"},{"text":"contentHandler:contentHandler];","type":"text"},{"type":"text","text":" "},{"type":"text","text":"}"}]}]}]}],"kind":"content"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pwnotificationextensionmanager\/handle(_:withappgroups:contenthandler:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pwnotificationextensionmanager\/handle(_:withappgroups:contenthandler:)"]}],"abstract":[{"text":"Example:","type":"text"}],"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWNotificationExtensionManager\/handle(_:withAppGroups:contentHandler:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWNotificationExtensionManager"]]},"metadata":{"roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"handleNotificationRequest:withAppGroups:contentHandler:"}],"modules":[{"name":"PushwooshFramework"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"handle"},{"kind":"text","text":"("},{"text":"UNNotificationRequest","preciseIdentifier":"c:objc(cs)UNNotificationRequest","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"withAppGroups","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"contentHandler","kind":"externalParam"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","text":"UNNotificationContent","preciseIdentifier":"c:objc(cs)UNNotificationContent"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")","kind":"text"}],"title":"handle(_:withAppGroups:contentHandler:)","symbolKind":"method","externalID":"c:objc(cs)PWNotificationExtensionManager(im)handleNotificationRequest:withAppGroups:contentHandler:","role":"symbol"},"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWNotificationExtensionManager/handle(_:withAppGroups:contentHandler:)":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWNotificationExtensionManager\/handle(_:withAppGroups:contentHandler:)","navigatorTitle":[{"text":"handleNotificationRequest:withAppGroups:contentHandler:","kind":"identifier"}],"url":"\/documentation\/pushwooshframework\/pwnotificationextensionmanager\/handle(_:withappgroups:contenthandler:)","role":"symbol","title":"handle(_:withAppGroups:contentHandler:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"handle","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UNNotificationRequest","text":"UNNotificationRequest"},{"kind":"text","text":", "},{"text":"withAppGroups","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"contentHandler","kind":"externalParam"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","text":"UNNotificationContent","preciseIdentifier":"c:objc(cs)UNNotificationContent"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"type":"topic","abstract":[{"text":"Example:","type":"text"}],"kind":"symbol"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"url":"\/documentation\/pushwooshframework","kind":"symbol","type":"topic","title":"PushwooshFramework","role":"collection","abstract":[{"text":"Push notification SDK for iOS applications.","type":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWNotificationExtensionManager":{"url":"\/documentation\/pushwooshframework\/pwnotificationextensionmanager","role":"symbol","title":"PWNotificationExtensionManager","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PWNotificationExtensionManager","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"PWNotificationExtensionManager","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWNotificationExtensionManager","abstract":[],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"handleNotificationRequest:withAppGroups:contentHandler:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"kind":"text","text":"- "},{"text":"handleNotificationRequest:withAppGroups:contentHandler:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"handleNotificationRequest:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UNNotificationRequest","text":"UNNotificationRequest"},{"text":" *) ","kind":"text"},{"text":"request","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"withAppGroups:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"appGroupsName","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"contentHandler:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":" (^","kind":"text"},{"kind":"text","text":")("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UNNotificationContent","text":"UNNotificationContent"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"kind":"text","text":")) "},{"text":"contentHandler","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWNotificationExtensionManager~1handle(_:withAppGroups:contentHandler:)\/title","op":"replace","value":"handleNotificationRequest:withAppGroups:contentHandler:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"handleNotificationRequest:withAppGroups:contentHandler:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWNotificationExtensionManager~1handle(_:withAppGroups:contentHandler:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWNotificationExtensionManager\/title","value":"PWNotificationExtensionManager"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWNotificationExtensionManager\/fragments","value":[{"kind":"identifier","text":"PWNotificationExtensionManager"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}