{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"shared"},{"text":"() -> ","kind":"text"},{"text":"Self","kind":"typeIdentifier"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWNotificationExtensionManager\/shared()","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"paths":["\/documentation\/pushwooshframework\/pwnotificationextensionmanager\/shared()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pwnotificationextensionmanager\/shared()"]}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWNotificationExtensionManager"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shared","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"Self","kind":"typeIdentifier"}],"title":"shared()","symbolKind":"method","modules":[{"name":"PushwooshFramework"}],"navigatorTitle":[{"text":"sharedManager","kind":"identifier"}],"externalID":"c:objc(cs)PWNotificationExtensionManager(cm)sharedManager","roleHeading":"Type Method","role":"symbol"},"sections":[],"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","title":"PushwooshFramework","url":"\/documentation\/pushwooshframework","kind":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWNotificationExtensionManager":{"title":"PWNotificationExtensionManager","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PWNotificationExtensionManager","kind":"identifier"}],"type":"topic","abstract":[],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWNotificationExtensionManager","role":"symbol","url":"\/documentation\/pushwooshframework\/pwnotificationextensionmanager","navigatorTitle":[{"text":"PWNotificationExtensionManager","kind":"identifier"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWNotificationExtensionManager/shared()":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWNotificationExtensionManager\/shared()","navigatorTitle":[{"text":"sharedManager","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"shared"},{"kind":"text","text":"() -> "},{"text":"Self","kind":"typeIdentifier"}],"url":"\/documentation\/pushwooshframework\/pwnotificationextensionmanager\/shared()","abstract":[],"role":"symbol","type":"topic","kind":"symbol","title":"shared()"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"sharedManager"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"sharedManager"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"sharedManager","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"value":"PWNotificationExtensionManager","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWNotificationExtensionManager\/title","op":"replace"},{"value":[{"text":"PWNotificationExtensionManager","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWNotificationExtensionManager\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWNotificationExtensionManager~1shared()\/title","op":"replace","value":"sharedManager"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWNotificationExtensionManager~1shared()\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"sharedManager"}]}]}]}