{"variants":[{"paths":["\/documentation\/pushwooshinboxkit"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pushwooshinboxkit"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Framework","externalID":"PushwooshInboxKit","symbolKind":"module","role":"collection","title":"PushwooshInboxKit","modules":[{"name":"PushwooshInboxKit"}]},"primaryContentSections":[{"kind":"content","content":[{"level":2,"anchor":"Overview","type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"PushwooshInboxKit"},{"type":"text","text":" ships a "},{"code":"UIViewController","type":"codeVoice"},{"text":" you can drop into any UIKit","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"navigation flow to render your app’s message inbox. It is built on top of the"},{"type":"text","text":" "},{"text":"existing ","type":"text"},{"type":"codeVoice","code":"PWInbox"},{"type":"text","text":" data layer in "},{"code":"PushwooshCore","type":"codeVoice"},{"type":"text","text":" and adds:"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"a value-typed ","type":"text"},{"code":"Attributes","type":"codeVoice"},{"type":"text","text":" configuration container with cell registry,"},{"text":" ","type":"text"},{"text":"transform pipeline, and visual style;","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"automatic dark-mode reactivity (no per-color setup);"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"swipe-to-delete, mark-as-read on disappear, pull-to-refresh;"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"a delegate protocol with default implementations so hosts override only"},{"text":" ","type":"text"},{"text":"the callbacks they care about;","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Obj-C-friendly setters so existing Obj-C apps can integrate without","type":"text"},{"type":"text","text":" "},{"type":"text","text":"bridging headers."}]}]}]}]}],"topicSections":[{"title":"Getting Started","identifiers":["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/GettingStarted","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/Examples"]},{"title":"Public Surface","identifiers":["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitViewController","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitAttributes","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitDelegate","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCell"]},{"title":"Classes","identifiers":["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxBannerCell","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCaptionedCell","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxClassicCell","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitImplementation"]},{"title":"Structures","identifiers":["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxButton"]},{"identifiers":["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxButtonAction"],"title":"Enumerations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit"},"kind":"symbol","abstract":[{"type":"text","text":"Modern UIKit inbox UI powered by Pushwoosh."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[[]]},"sections":[],"references":{"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/GettingStarted":{"abstract":[{"text":"Drop the inbox controller into your app.","type":"text"}],"kind":"article","role":"article","title":"Getting Started","url":"\/documentation\/pushwooshinboxkit\/gettingstarted","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/GettingStarted"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxKitVersionString":{"fragments":[{"kind":"identifier","text":"PushwooshInboxKitVersionString"}],"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxkitversionstring","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitVersionString","kind":"symbol","abstract":[{"text":"Project version string for PushwooshInboxKit.","type":"text"}],"role":"symbol","title":"PushwooshInboxKitVersionString"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxKitAttributes/cells":{"role":"symbol","kind":"symbol","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxkitattributes\/cells","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cells"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:@M@PushwooshInboxKit@objc(cs)PushwooshInboxCell","text":"PushwooshInboxCell","kind":"typeIdentifier"},{"kind":"text","text":".Type]"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitAttributes\/cells","title":"cells","type":"topic","abstract":[{"text":"Mapping of cell-kind identifiers to cell classes.","type":"text"}]},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxKitAttributes":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PushwooshInboxKitAttributes","kind":"identifier"}],"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxkitattributes","type":"topic","navigatorTitle":[{"text":"PushwooshInboxKitAttributes","kind":"identifier"}],"kind":"symbol","title":"PushwooshInboxKitAttributes","role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitAttributes","abstract":[{"text":"Configuration container for ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitViewController"},{"text":".","type":"text"}]},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxKitDelegate":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushwooshInboxKitDelegate"}],"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxkitdelegate","type":"topic","kind":"symbol","abstract":[{"text":"Lifecycle and interaction callbacks for ","type":"text"},{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitViewController","type":"reference","isActive":true},{"type":"text","text":"."}],"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitDelegate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PushwooshInboxKitDelegate"}],"title":"PushwooshInboxKitDelegate"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxBannerCell":{"navigatorTitle":[{"kind":"identifier","text":"PushwooshInboxBannerCell"}],"abstract":[],"title":"PushwooshInboxBannerCell","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxbannercell","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushwooshInboxBannerCell"}],"kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxBannerCell","role":"symbol"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxButtonAction":{"title":"PushwooshInboxButtonAction","abstract":[{"type":"text","text":"The action a tapped inline CTA button should perform."}],"navigatorTitle":[{"kind":"identifier","text":"PushwooshInboxButtonAction"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"PushwooshInboxButtonAction","kind":"identifier"}],"type":"topic","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxbuttonaction","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxButtonAction"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxCaptionedCell":{"navigatorTitle":[{"kind":"identifier","text":"PushwooshInboxCaptionedCell"}],"abstract":[],"title":"PushwooshInboxCaptionedCell","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxcaptionedcell","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushwooshInboxCaptionedCell"}],"kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCaptionedCell","role":"symbol"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxButton":{"title":"PushwooshInboxButton","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxbutton","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PushwooshInboxButton","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PushwooshInboxButton"}],"abstract":[{"text":"A single inline call-to-action button rendered inside an inbox cell.","type":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxButton","type":"topic","role":"symbol","kind":"symbol"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxCell":{"role":"symbol","kind":"symbol","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxcell","navigatorTitle":[{"text":"PushwooshInboxCell","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushwooshInboxCell"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCell","title":"PushwooshInboxCell","type":"topic","abstract":[{"text":"Default inbox table-view cell. Subclass this type and register it under a","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"custom kind via "},{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitAttributes\/cells","isActive":true,"type":"reference"},{"text":" to ship bespoke","type":"text"},{"type":"text","text":" "},{"text":"layouts.","type":"text"}]},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxKitViewController":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PushwooshInboxKitViewController","kind":"identifier"}],"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxkitviewcontroller","type":"topic","navigatorTitle":[{"text":"PushwooshInboxKitViewController","kind":"identifier"}],"kind":"symbol","title":"PushwooshInboxKitViewController","role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitViewController","abstract":[{"type":"text","text":"Modern UIKit inbox controller backed by "},{"code":"PWInboxService","type":"codeVoice"},{"text":".","type":"text"}]},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxClassicCell":{"navigatorTitle":[{"kind":"identifier","text":"PushwooshInboxClassicCell"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushwooshInboxClassicCell"}],"kind":"symbol","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxclassiccell","title":"PushwooshInboxClassicCell","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxClassicCell","abstract":[],"role":"symbol","type":"topic"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit":{"role":"collection","kind":"symbol","url":"\/documentation\/pushwooshinboxkit","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit","title":"PushwooshInboxKit","type":"topic","abstract":[{"text":"Modern UIKit inbox UI powered by Pushwoosh.","type":"text"}]},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/Examples":{"abstract":[{"type":"text","text":"Recipes for the most common configurations."}],"kind":"article","role":"article","title":"Examples","url":"\/documentation\/pushwooshinboxkit\/examples","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/Examples"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxKitImplementation":{"navigatorTitle":[{"text":"PushwooshInboxKitImplementation","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PushwooshInboxKitImplementation","kind":"identifier"}],"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxkitimplementation","title":"PushwooshInboxKitImplementation","abstract":[{"type":"text","text":"Implementation entry-point discovered by the umbrella SDK via"},{"type":"text","text":" "},{"code":"NSClassFromString(\"PushwooshInboxKitImplementation\")","type":"codeVoice"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitImplementation","role":"symbol","kind":"symbol"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxKitVersionNumber":{"abstract":[{"type":"text","text":"Project version number for PushwooshInboxKit."}],"kind":"symbol","role":"symbol","title":"PushwooshInboxKitVersionNumber","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxkitversionnumber","fragments":[{"kind":"identifier","text":"PushwooshInboxKitVersionNumber"}],"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitVersionNumber"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/GettingStarted","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/Examples"],"title":"Getting Started"},{"identifiers":["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitViewController","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCell"],"title":"Public Surface"},{"title":"Classes","identifiers":["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxBannerCell","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCaptionedCell","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxClassicCell","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitImplementation"]},{"title":"Variables","identifiers":["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitVersionNumber","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitVersionString"]}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxBannerCell\/title","op":"replace","value":"PushwooshInboxBannerCell"},{"value":[{"kind":"identifier","text":"PushwooshInboxBannerCell"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxBannerCell\/fragments","op":"replace"},{"value":"PushwooshInboxCaptionedCell","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxCaptionedCell\/title"},{"value":[{"text":"PushwooshInboxCaptionedCell","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxCaptionedCell\/fragments"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxCell\/title","value":"PushwooshInboxCell","op":"replace"},{"value":[{"kind":"identifier","text":"PushwooshInboxCell"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxCell\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxKitViewController\/title","value":"PushwooshInboxKitViewController","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxKitViewController\/fragments","op":"replace","value":[{"text":"PushwooshInboxKitViewController","kind":"identifier"}]},{"value":"PushwooshInboxClassicCell","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxClassicCell\/title"},{"value":[{"kind":"identifier","text":"PushwooshInboxClassicCell"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxClassicCell\/fragments","op":"replace"},{"value":"PushwooshInboxKitImplementation","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxKitImplementation\/title"},{"value":[{"text":"PushwooshInboxKitImplementation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxKitImplementation\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}