{"metadata":{"role":"symbol","externalID":"c:@M@PushwooshVoIP@objc(pl)PWVoIPCallDelegate(im)endCall:perform:voipMessage:","navigatorTitle":[{"kind":"identifier","text":"endCall:perform:voipMessage:"}],"title":"endCall(_:perform:voipMessage:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"endCall","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CXProvider","text":"CXProvider"},{"kind":"text","text":", "},{"text":"perform","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CXEndCallAction","preciseIdentifier":"c:objc(cs)CXEndCallAction"},{"text":", ","kind":"text"},{"text":"voipMessage","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@PushwooshVoIP@objc(cs)PWVoIPMessage","text":"PWVoIPMessage","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"roleHeading":"Instance Method","symbolKind":"method","modules":[{"name":"PushwooshVoIP"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate"]]},"abstract":[{"type":"text","text":"Called when user ends a call."}],"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate\/endCall(_:perform:voipMessage:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"endCall"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"provider","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"CXProvider","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CXProvider"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"perform"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"action"},{"text":": ","kind":"text"},{"text":"CXEndCallAction","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CXEndCallAction"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"voipMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PWVoIPMessage","preciseIdentifier":"c:@M@PushwooshVoIP@objc(cs)PWVoIPMessage","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPMessage"},{"text":"?)","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/pushwooshvoip\/pwvoipcalldelegate\/endcall(_:perform:voipmessage:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pushwooshvoip\/pwvoipcalldelegate\/endcall(_:perform:voipmessage:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPMessage":{"title":"PWVoIPMessage","type":"topic","url":"\/documentation\/pushwooshvoip\/pwvoipmessage","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPMessage","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PWVoIPMessage"}],"abstract":[{"type":"text","text":"An encapsulation of VoIP push notification payload data."}],"navigatorTitle":[{"text":"PWVoIPMessage","kind":"identifier"}],"role":"symbol","kind":"symbol"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPCallDelegate":{"type":"topic","url":"\/documentation\/pushwooshvoip\/pwvoipcalldelegate","title":"PWVoIPCallDelegate","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PWVoIPCallDelegate"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate","abstract":[{"type":"text","text":"Delegate protocol for receiving VoIP call events and CallKit callbacks."}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"PWVoIPCallDelegate","kind":"identifier"}],"role":"symbol"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPCallDelegate/endCall(_:perform:voipMessage:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"endCall","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CXProvider","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CXProvider"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"perform"},{"text":": ","kind":"text"},{"text":"CXEndCallAction","preciseIdentifier":"c:objc(cs)CXEndCallAction","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"voipMessage"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"PWVoIPMessage","preciseIdentifier":"c:@M@PushwooshVoIP@objc(cs)PWVoIPMessage"},{"text":"?)","kind":"text"}],"url":"\/documentation\/pushwooshvoip\/pwvoipcalldelegate\/endcall(_:perform:voipmessage:)","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate\/endCall(_:perform:voipMessage:)","type":"topic","abstract":[{"type":"text","text":"Called when user ends a call."}],"title":"endCall(_:perform:voipMessage:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"endCall:perform:voipMessage:"}]},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP":{"kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP","role":"collection","type":"topic","url":"\/documentation\/pushwooshvoip","abstract":[{"text":"VoIP push notifications with native call UI for iOS applications.","type":"text"}],"title":"PushwooshVoIP"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"endCall:perform:voipMessage:"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"endCall:perform:voipMessage:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"text":"endCall:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)CXProvider","text":"CXProvider","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"provider","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"perform:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)CXEndCallAction","kind":"typeIdentifier","text":"CXEndCallAction"},{"text":" *) ","kind":"text"},{"text":"action","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"voipMessage:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"PWVoIPMessage","preciseIdentifier":"c:@M@PushwooshVoIP@objc(cs)PWVoIPMessage","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPMessage"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"voipMessage"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0"},{"value":"PWVoIPMessage","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPMessage\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPMessage\/fragments","value":[{"kind":"identifier","text":"PWVoIPMessage"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate\/title","value":"PWVoIPCallDelegate","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate\/fragments","value":[{"kind":"identifier","text":"PWVoIPCallDelegate"}]},{"value":"endCall:perform:voipMessage:","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate~1endCall(_:perform:voipMessage:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"endCall:perform:voipMessage:"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate~1endCall(_:perform:voipMessage:)\/fragments"}]}]}