{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshvoip\/pwvoipcalldelegate\/voipdidreportincomingcallsuccessfully(voipmessage:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshvoip\/pwvoipcalldelegate\/voipdidreportincomingcallsuccessfully(voipmessage:)"]}],"kind":"symbol","metadata":{"navigatorTitle":[{"text":"voipDidReportIncomingCallSuccessfullyWithVoipMessage:","kind":"identifier"}],"modules":[{"name":"PushwooshVoIP"}],"title":"voipDidReportIncomingCallSuccessfully(voipMessage:)","symbolKind":"method","roleHeading":"Instance Method","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"voipDidReportIncomingCallSuccessfully"},{"kind":"text","text":"("},{"text":"voipMessage","kind":"externalParam"},{"kind":"text","text":": "},{"text":"PWVoIPMessage","kind":"typeIdentifier","preciseIdentifier":"c:@M@PushwooshVoIP@objc(cs)PWVoIPMessage"},{"kind":"text","text":")"}],"externalID":"c:@M@PushwooshVoIP@objc(pl)PWVoIPCallDelegate(im)voipDidReportIncomingCallSuccessfullyWithVoipMessage:"},"sections":[],"abstract":[{"text":"Called when incoming call is successfully reported to CallKit.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"voipDidReportIncomingCallSuccessfully","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"voipMessage"},{"text":": ","kind":"text"},{"text":"PWVoIPMessage","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPMessage","preciseIdentifier":"c:@M@PushwooshVoIP@objc(cs)PWVoIPMessage","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate"]]},"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate\/voipDidReportIncomingCallSuccessfully(voipMessage:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPMessage":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PWVoIPMessage","kind":"identifier"}],"title":"PWVoIPMessage","url":"\/documentation\/pushwooshvoip\/pwvoipmessage","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPMessage","abstract":[{"type":"text","text":"An encapsulation of VoIP push notification payload data."}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"PWVoIPMessage"}]},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPCallDelegate":{"role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate","type":"topic","abstract":[{"text":"Delegate protocol for receiving VoIP call events and CallKit callbacks.","type":"text"}],"url":"\/documentation\/pushwooshvoip\/pwvoipcalldelegate","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PWVoIPCallDelegate"}],"title":"PWVoIPCallDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PWVoIPCallDelegate"}]},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP":{"role":"collection","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP","type":"topic","abstract":[{"type":"text","text":"VoIP push notifications with native call UI for iOS applications."}],"kind":"symbol","url":"\/documentation\/pushwooshvoip","title":"PushwooshVoIP"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPCallDelegate/voipDidReportIncomingCallSuccessfully(voipMessage:)":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"voipDidReportIncomingCallSuccessfullyWithVoipMessage:"}],"title":"voipDidReportIncomingCallSuccessfully(voipMessage:)","url":"\/documentation\/pushwooshvoip\/pwvoipcalldelegate\/voipdidreportincomingcallsuccessfully(voipmessage:)","kind":"symbol","abstract":[{"type":"text","text":"Called when incoming call is successfully reported to CallKit."}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"voipDidReportIncomingCallSuccessfully","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"voipMessage"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"PWVoIPMessage","preciseIdentifier":"c:@M@PushwooshVoIP@objc(cs)PWVoIPMessage"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate\/voipDidReportIncomingCallSuccessfully(voipMessage:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"voipDidReportIncomingCallSuccessfullyWithVoipMessage:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"voipDidReportIncomingCallSuccessfullyWithVoipMessage:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"voipDidReportIncomingCallSuccessfullyWithVoipMessage:"},{"text":"(","kind":"text"},{"text":"PWVoIPMessage","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPMessage","preciseIdentifier":"c:@M@PushwooshVoIP@objc(cs)PWVoIPMessage","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"voipMessage","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPMessage\/title","value":"PWVoIPMessage"},{"value":[{"kind":"identifier","text":"PWVoIPMessage"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPMessage\/fragments"},{"value":"PWVoIPCallDelegate","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate\/title","op":"replace"},{"op":"replace","value":[{"text":"PWVoIPCallDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate\/fragments"},{"value":"voipDidReportIncomingCallSuccessfullyWithVoipMessage:","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate~1voipDidReportIncomingCallSuccessfully(voipMessage:)\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate~1voipDidReportIncomingCallSuccessfully(voipMessage:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"voipDidReportIncomingCallSuccessfullyWithVoipMessage:"}],"op":"replace"}]}]}