{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","hierarchy":{"paths":[[]]},"primaryContentSections":[{"kind":"content","content":[{"anchor":"Overview","text":"Overview","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"PushwooshVoIP integrates Apple’s PushKit and CallKit frameworks to deliver VoIP push notifications and display native system call interface. VoIP pushes bypass standard notification delivery and wake your app directly, ensuring users never miss incoming calls."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"The module handles PushKit token registration, CallKit provider configuration, and call lifecycle management automatically."}],"type":"paragraph"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshvoip"]},{"paths":["\/documentation\/pushwooshvoip"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP","interfaceLanguage":"swift"},"abstract":[{"text":"VoIP push notifications with native call UI for iOS applications.","type":"text"}],"metadata":{"title":"PushwooshVoIP","externalID":"PushwooshVoIP","role":"collection","modules":[{"name":"PushwooshVoIP"}],"symbolKind":"module","roleHeading":"Framework"},"topicSections":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/GettingStarted","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/Examples"],"title":"Getting Started"},{"identifiers":["doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPMessage","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation"],"title":"Classes"},{"identifiers":["doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate"],"title":"Protocols"},{"title":"Enumerations","identifiers":["doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPHandleType"]},{"title":"Extended Modules","identifiers":["doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshBridge"]}],"references":{"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PushwooshVoIPVersionNumber":{"identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPVersionNumber","role":"symbol","abstract":[{"text":"Project version number for PushwooshVoIP.","type":"text"}],"url":"\/documentation\/pushwooshvoip\/pushwooshvoipversionnumber","title":"PushwooshVoIPVersionNumber","type":"topic","kind":"symbol","fragments":[{"text":"PushwooshVoIPVersionNumber","kind":"identifier"}]},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPCallDelegate":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PWVoIPCallDelegate"}],"kind":"symbol","title":"PWVoIPCallDelegate","abstract":[{"type":"text","text":"Delegate protocol for receiving VoIP call events and CallKit callbacks."}],"navigatorTitle":[{"text":"PWVoIPCallDelegate","kind":"identifier"}],"type":"topic","url":"\/documentation\/pushwooshvoip\/pwvoipcalldelegate","role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/GettingStarted":{"kind":"article","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/GettingStarted","url":"\/documentation\/pushwooshvoip\/gettingstarted","role":"article","abstract":[{"type":"text","text":"Set up VoIP push notifications with CallKit in your iOS app."}],"title":"Getting Started"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/Examples":{"kind":"article","title":"Code Examples","abstract":[{"type":"text","text":"Practical examples for common VoIP integration scenarios."}],"type":"topic","url":"\/documentation\/pushwooshvoip\/examples","role":"article","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/Examples"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PushwooshVoIPImplementation":{"identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PushwooshVoIPImplementation"}],"role":"symbol","abstract":[{"type":"text","text":"Orchestrates VoIP push notifications and CallKit integration for iOS applications."}],"navigatorTitle":[{"kind":"identifier","text":"PushwooshVoIPImplementation"}],"type":"topic","title":"PushwooshVoIPImplementation","url":"\/documentation\/pushwooshvoip\/pushwooshvoipimplementation"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PushwooshBridge":{"identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshBridge","abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/pushwooshvoip\/pushwooshbridge","title":"PushwooshBridge","role":"collection"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PushwooshVoIPVersionString":{"abstract":[{"text":"Project version string for PushwooshVoIP.","type":"text"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPVersionString","title":"PushwooshVoIPVersionString","type":"topic","fragments":[{"kind":"identifier","text":"PushwooshVoIPVersionString"}],"url":"\/documentation\/pushwooshvoip\/pushwooshvoipversionstring"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPHandleType":{"identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPHandleType","title":"PWVoIPHandleType","abstract":[{"text":"Display format for caller information in CallKit UI.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"PWVoIPHandleType"}],"type":"topic","role":"symbol","url":"\/documentation\/pushwooshvoip\/pwvoiphandletype","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PWVoIPHandleType","kind":"identifier"}]},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP":{"url":"\/documentation\/pushwooshvoip","title":"PushwooshVoIP","kind":"symbol","type":"topic","role":"collection","abstract":[{"text":"VoIP push notifications with native call UI for iOS applications.","type":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPMessage":{"abstract":[{"text":"An encapsulation of VoIP push notification payload data.","type":"text"}],"role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PWVoIPMessage"}],"navigatorTitle":[{"text":"PWVoIPMessage","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/pushwooshvoip\/pwvoipmessage","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPMessage","title":"PWVoIPMessage"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":[{"title":"Getting Started","identifiers":["doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/GettingStarted","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/Examples"]},{"title":"Classes","identifiers":["doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPMessage","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation"]},{"title":"Protocols","identifiers":["doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate"]},{"title":"Variables","identifiers":["doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPVersionNumber","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPVersionString"]},{"identifiers":["doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPHandleType"],"title":"Enumerations"}],"op":"replace","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":"PWVoIPCallDelegate","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate\/title"},{"value":[{"kind":"identifier","text":"PWVoIPCallDelegate"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate\/fragments"},{"op":"replace","value":"PushwooshVoIPImplementation","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation\/fragments","op":"replace","value":[{"text":"PushwooshVoIPImplementation","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPHandleType\/title","value":"PWVoIPHandleType","op":"replace"},{"op":"replace","value":[{"text":"PWVoIPHandleType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPHandleType\/fragments"},{"value":"PWVoIPMessage","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPMessage\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPMessage\/fragments","value":[{"text":"PWVoIPMessage","kind":"identifier"}]}]}]}