{"sections":[],"kind":"article","primaryContentSections":[{"content":[{"text":"Custom cell registry","type":"heading","level":2,"anchor":"Custom-cell-registry"},{"type":"codeListing","code":["final class HeroInboxCell: PushwooshInboxCell { \/* custom layout *\/ }","","var attrs = PushwooshInboxKitAttributes()","attrs.cells[\"hero\"] = HeroInboxCell.self","attrs.cellKindResolver = { message in","    (message.imageUrl?.isEmpty ?? true) ? \"default\" : \"hero\"","}","","let inbox = PushwooshInboxKitViewController(attributes: attrs)"],"syntax":"swift"},{"level":2,"text":"Filter \/ sort with `transform`","anchor":"Filter--sort-with-transform","type":"heading"},{"type":"codeListing","syntax":"swift","code":["var attrs = PushwooshInboxKitAttributes()","attrs.transform = { messages in","    messages","        .filter { !$0.isRead }","        .sorted { $0.sendDate > $1.sendDate }","}"]},{"type":"heading","level":2,"anchor":"Lifecycle-delegate","text":"Lifecycle delegate"},{"syntax":"swift","code":["extension MyHost: PushwooshInboxKitDelegate {","    func inboxKit(_ vc: PushwooshInboxKitViewController, didSelect message: PWInboxMessageProtocol) -> Bool {","        if message.type == .deeplink {","            myRouter.handle(message.actionParams)","            return false","        }","        return true","    }","}"],"type":"codeListing"},{"level":2,"text":"Force light theme","type":"heading","anchor":"Force-light-theme"},{"syntax":"swift","type":"codeListing","code":["var attrs = PushwooshInboxKitAttributes()","attrs.enableDarkTheme = false"]}],"kind":"content"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/Examples","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshinboxkit\/examples"]},{"paths":["\/documentation\/pushwooshinboxkit\/examples"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Recipes for the most common configurations.","type":"text"}],"metadata":{"role":"article","title":"Examples","modules":[{"name":"PushwooshInboxKit"}],"roleHeading":"Article"},"seeAlsoSections":[{"title":"Getting Started","identifiers":["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/GettingStarted"],"generated":true}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit"]]},"references":{"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit":{"role":"collection","abstract":[{"text":"Modern UIKit inbox UI powered by Pushwoosh.","type":"text"}],"title":"PushwooshInboxKit","type":"topic","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit","url":"\/documentation\/pushwooshinboxkit"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/GettingStarted":{"kind":"article","role":"article","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/GettingStarted","type":"topic","abstract":[{"type":"text","text":"Drop the inbox controller into your app."}],"url":"\/documentation\/pushwooshinboxkit\/gettingstarted","title":"Getting Started"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Getting Started","identifiers":["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/GettingStarted"],"generated":true}]}]}]}