{"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit"]]},"seeAlsoSections":[{"generated":true,"title":"Getting Started","identifiers":["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/Examples"]}],"kind":"article","abstract":[{"type":"text","text":"Drop the inbox controller into your app."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/GettingStarted"},"metadata":{"role":"article","modules":[{"name":"PushwooshInboxKit"}],"roleHeading":"Article","title":"Getting Started"},"sections":[],"primaryContentSections":[{"content":[{"text":"Overview","type":"heading","level":2,"anchor":"Overview"},{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"PushwooshInboxKit"},{"type":"text","text":" is shipped as an optional XCFramework alongside the main"},{"type":"text","text":" "},{"text":"SDK. After adding the ","type":"text"},{"type":"codeVoice","code":"PushwooshXCFramework\/PushwooshInboxKit"},{"text":" subspec (or the","type":"text"},{"type":"text","text":" "},{"type":"text","text":"SPM library), instantiate "},{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitViewController","isActive":true,"type":"reference"},{"type":"text","text":" and push it onto"},{"type":"text","text":" "},{"text":"your navigation stack.","type":"text"}]},{"text":"Swift","type":"heading","anchor":"Swift","level":2},{"code":["import PushwooshInboxKit","","let inbox = PushwooshInboxKitViewController(attributes: PushwooshInboxKitAttributes())","inbox.delegate = self","navigationController?.pushViewController(inbox, animated: true)"],"type":"codeListing","syntax":"swift"},{"level":2,"text":"Objective-C","type":"heading","anchor":"Objective-C"},{"code":["@import PushwooshInboxKit;","","PushwooshInboxKitViewController *inbox = [PushwooshInboxKitViewController new];","[inbox setBackgroundColor:UIColor.systemBackgroundColor];","[inbox setEmptyMessage:@\"Nothing here yet\"];","[self.navigationController pushViewController:inbox animated:YES];"],"type":"codeListing","syntax":"objc"},{"inlineContent":[{"text":"The controller refreshes itself on ","type":"text"},{"type":"codeVoice","code":"viewWillAppear"},{"type":"text","text":", on"},{"text":" ","type":"text"},{"type":"codeVoice","code":"PWInboxMessagesDidUpdateNotification"},{"type":"text","text":", and on push delivery. No additional"},{"text":" ","type":"text"},{"type":"text","text":"plumbing required."}],"type":"paragraph"}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshinboxkit\/gettingstarted"]},{"paths":["\/documentation\/pushwooshinboxkit\/gettingstarted"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit":{"kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit","title":"PushwooshInboxKit","url":"\/documentation\/pushwooshinboxkit","role":"collection","abstract":[{"text":"Modern UIKit inbox UI powered by Pushwoosh.","type":"text"}],"type":"topic"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxKitViewController":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PushwooshInboxKitViewController","kind":"identifier"}],"navigatorTitle":[{"text":"PushwooshInboxKitViewController","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitViewController","title":"PushwooshInboxKitViewController","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxkitviewcontroller","role":"symbol","abstract":[{"type":"text","text":"Modern UIKit inbox controller backed by "},{"type":"codeVoice","code":"PWInboxService"},{"type":"text","text":"."}],"type":"topic"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/Examples":{"type":"topic","kind":"article","abstract":[{"text":"Recipes for the most common configurations.","type":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/Examples","url":"\/documentation\/pushwooshinboxkit\/examples","title":"Examples","role":"article"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/Examples"],"generated":true,"title":"Getting Started"}],"op":"replace"},{"op":"replace","value":"PushwooshInboxKitViewController","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxKitViewController\/title"},{"value":[{"text":"PushwooshInboxKitViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxKitViewController\/fragments","op":"replace"}]}]}