{"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCarouselSlide","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/pushwooshinboxkit\/pushwooshinboxcarouselslide"],"traits":[{"interfaceLanguage":"swift"}]}],"seeAlsoSections":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxBannerCell","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCaptionedCell","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxClassicCell","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCarouselCell","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxVideoCell","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxWalletCell","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxVideoContent","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxWalletPass"],"generated":true,"title":"Rich Cards"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushwooshInboxCarouselSlide"}]}]},{"content":[{"anchor":"overview","text":"Overview","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"Unlike the other card kinds — which render the message’s single "},{"type":"codeVoice","code":"imageUrl"},{"text":" —","type":"text"},{"type":"text","text":" "},{"type":"text","text":"a carousel shows several images from one message. Those slides cannot live in"},{"type":"text","text":" "},{"text":"the standard message fields (there is only one ","type":"text"},{"type":"codeVoice","code":"imageUrl"},{"type":"text","text":"), so they arrive in"},{"type":"text","text":" "},{"code":"actionParams[\"carousel\"]","type":"codeVoice"},{"type":"text","text":" and are decoded by "},{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCarouselSlide\/decode(from:)","isActive":true,"type":"reference"},{"type":"text","text":", mirroring how"},{"text":" ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxButton"},{"text":" decodes its buttons.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"sections":[],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCarouselSlide\/init(imageUrl:title:url:)"]},{"identifiers":["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCarouselSlide\/imageUrl","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCarouselSlide\/title","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCarouselSlide\/url"],"title":"Instance Properties"},{"title":"Type Methods","identifiers":["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCarouselSlide\/decode(from:)"]}],"kind":"symbol","metadata":{"externalID":"s:17PushwooshInboxKit0aB13CarouselSlideV","symbolKind":"struct","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"PushwooshInboxCarouselSlide","kind":"identifier"}],"title":"PushwooshInboxCarouselSlide","navigatorTitle":[{"text":"PushwooshInboxCarouselSlide","kind":"identifier"}],"roleHeading":"Structure","modules":[{"name":"PushwooshInboxKit"}],"role":"symbol"},"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"A single slide inside a "},{"type":"reference","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCarouselCell","isActive":true},{"text":".","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit"]]},"references":{"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxWalletPass":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"PushwooshInboxWalletPass","kind":"identifier"}],"navigatorTitle":[{"text":"PushwooshInboxWalletPass","kind":"identifier"}],"abstract":[{"type":"text","text":"Apple Wallet pass descriptor for a "},{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxWalletCell","type":"reference","isActive":true},{"type":"text","text":"."}],"title":"PushwooshInboxWalletPass","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxWalletPass","kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxwalletpass"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxBannerCell":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushwooshInboxBannerCell"}],"navigatorTitle":[{"kind":"identifier","text":"PushwooshInboxBannerCell"}],"abstract":[],"title":"PushwooshInboxBannerCell","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxBannerCell","kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxbannercell"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxCarouselSlide/title":{"role":"symbol","title":"title","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"title"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCarouselSlide\/title","abstract":[{"type":"text","text":"Optional caption rendered as an overlay at the bottom of the slide."}],"kind":"symbol","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxcarouselslide\/title","type":"topic"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxCarouselSlide/imageUrl":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCarouselSlide\/imageUrl","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageUrl","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"role":"symbol","title":"imageUrl","kind":"symbol","type":"topic","abstract":[{"text":"Remote image URL string for the slide. Required — a slide without an image","type":"text"},{"type":"text","text":" "},{"type":"text","text":"is dropped during decoding."}],"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxcarouselslide\/imageurl"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxCarouselSlide/url":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCarouselSlide\/url","kind":"symbol","abstract":[{"type":"text","text":"Optional destination opened when the slide is tapped. When "},{"type":"codeVoice","code":"nil"},{"type":"text","text":", a tap"},{"type":"text","text":" "},{"type":"text","text":"falls through to the message’s default row action."}],"role":"symbol","title":"url","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxcarouselslide\/url","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"url","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"text":"?","kind":"text"}],"type":"topic"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit":{"kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit","role":"collection","type":"topic","url":"\/documentation\/pushwooshinboxkit","title":"PushwooshInboxKit","abstract":[{"type":"text","text":"Modern UIKit inbox UI powered by Pushwoosh."}]},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxCaptionedCell":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PushwooshInboxCaptionedCell","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PushwooshInboxCaptionedCell"}],"abstract":[],"title":"PushwooshInboxCaptionedCell","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCaptionedCell","kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxcaptionedcell"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxWalletCell":{"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxwalletcell","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxWalletCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PushwooshInboxWalletCell","kind":"identifier"}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PushwooshInboxWalletCell"}],"abstract":[],"role":"symbol","title":"PushwooshInboxWalletCell"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxButton":{"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxbutton","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxButton","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PushwooshInboxButton"}],"navigatorTitle":[{"text":"PushwooshInboxButton","kind":"identifier"}],"role":"symbol","abstract":[{"text":"A single inline call-to-action button rendered inside an inbox cell.","type":"text"}],"title":"PushwooshInboxButton","type":"topic","kind":"symbol"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxVideoContent":{"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PushwooshInboxVideoContent"}],"navigatorTitle":[{"kind":"identifier","text":"PushwooshInboxVideoContent"}],"abstract":[{"type":"text","text":"Video payload for a "},{"type":"reference","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxVideoCell","isActive":true},{"type":"text","text":"."}],"title":"PushwooshInboxVideoContent","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxVideoContent","kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxvideocontent"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxCarouselSlide/init(imageUrl:title:url:)":{"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxcarouselslide\/init(imageurl:title:url:)","title":"init(imageUrl:title:url:)","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCarouselSlide\/init(imageUrl:title:url:)","type":"topic","abstract":[],"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"imageUrl","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"title","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"url","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":"?)","kind":"text"}]},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxVideoCell":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PushwooshInboxVideoCell","kind":"identifier"}],"navigatorTitle":[{"text":"PushwooshInboxVideoCell","kind":"identifier"}],"abstract":[],"title":"PushwooshInboxVideoCell","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxVideoCell","kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxvideocell"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxCarouselSlide":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCarouselSlide","kind":"symbol","abstract":[{"type":"text","text":"A single slide inside a "},{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCarouselCell","type":"reference","isActive":true},{"type":"text","text":"."}],"role":"symbol","title":"PushwooshInboxCarouselSlide","navigatorTitle":[{"text":"PushwooshInboxCarouselSlide","kind":"identifier"}],"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxcarouselslide","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PushwooshInboxCarouselSlide"}],"type":"topic"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxCarouselCell":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"PushwooshInboxCarouselCell","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCarouselCell","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PushwooshInboxCarouselCell"}],"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxcarouselcell","type":"topic","abstract":[],"title":"PushwooshInboxCarouselCell"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxCarouselSlide/decode(from:)":{"title":"decode(from:)","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Decodes the slide list from a message’s "},{"code":"actionParams","type":"codeVoice"},{"text":". The expected shape","type":"text"},{"type":"text","text":" "},{"type":"text","text":"is one of:"}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"decode"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"from"},{"text":": ","kind":"text"},{"text":"PWInboxMessageProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)PWInboxMessageProtocol"},{"kind":"text","text":") -> ["},{"preciseIdentifier":"s:17PushwooshInboxKit0aB13CarouselSlideV","kind":"typeIdentifier","text":"PushwooshInboxCarouselSlide"},{"text":"]","kind":"text"}],"role":"symbol","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxcarouselslide\/decode(from:)","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCarouselSlide\/decode(from:)"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxClassicCell":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushwooshInboxClassicCell"}],"navigatorTitle":[{"kind":"identifier","text":"PushwooshInboxClassicCell"}],"abstract":[],"title":"PushwooshInboxClassicCell","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxClassicCell","kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxclassiccell"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxBannerCell\/title","value":"PushwooshInboxBannerCell"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxBannerCell\/fragments","value":[{"kind":"identifier","text":"PushwooshInboxBannerCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxCaptionedCell\/title","value":"PushwooshInboxCaptionedCell"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxCaptionedCell\/fragments","value":[{"text":"PushwooshInboxCaptionedCell","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxWalletCell\/title","value":"PushwooshInboxWalletCell"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxWalletCell\/fragments","op":"replace","value":[{"text":"PushwooshInboxWalletCell","kind":"identifier"}]},{"op":"replace","value":"PushwooshInboxVideoCell","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxVideoCell\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxVideoCell\/fragments","value":[{"text":"PushwooshInboxVideoCell","kind":"identifier"}]},{"op":"replace","value":"PushwooshInboxCarouselCell","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxCarouselCell\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxCarouselCell\/fragments","value":[{"kind":"identifier","text":"PushwooshInboxCarouselCell"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxClassicCell\/title","value":"PushwooshInboxClassicCell","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxClassicCell\/fragments","op":"replace","value":[{"kind":"identifier","text":"PushwooshInboxClassicCell"}]}]}]}