{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshinboxkit\/pushwooshinboxcaptionedcell"]},{"paths":["\/documentation\/pushwooshinboxkit\/pushwooshinboxcaptionedcell"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCaptionedCell\/init(coder:)","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCaptionedCell\/init(style:reuseIdentifier:)"],"title":"Initializers"},{"title":"Instance Methods","identifiers":["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCaptionedCell\/apply(message:attributes:)","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCaptionedCell\/prepareForReuse()"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(PushwooshInboxCaptionedCell) ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushwooshInboxCaptionedCell"}],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCaptionedCell","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit"]]},"sections":[],"kind":"symbol","metadata":{"title":"PushwooshInboxCaptionedCell","symbolKind":"class","externalID":"c:@M@PushwooshInboxKit@objc(cs)PushwooshInboxCaptionedCell","roleHeading":"Class","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PushwooshInboxCaptionedCell"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PushwooshInboxCaptionedCell","kind":"identifier"}],"modules":[{"name":"PushwooshInboxKit"}]},"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCell"],"type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)NSCoding","doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)NSObject","doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)CALayerDelegate","doc:\/\/com.pushwoosh.PushwooshInboxKit\/s7CVarArgP","doc:\/\/com.pushwoosh.PushwooshInboxKit\/s28CustomDebugStringConvertibleP","doc:\/\/com.pushwoosh.PushwooshInboxKit\/s23CustomStringConvertibleP","doc:\/\/com.pushwoosh.PushwooshInboxKit\/SQ","doc:\/\/com.pushwoosh.PushwooshInboxKit\/SH","doc:\/\/com.pushwoosh.PushwooshInboxKit\/s8SendableP","doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIAccessibilityIdentification","doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIAppearance","doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIAppearanceContainer","doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UICoordinateSpace","doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIDynamicItem","doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIFocusEnvironment","doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIFocusItem","doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIFocusItemContainer","doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIGestureRecognizerDelegate","doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UILargeContentViewerItem","doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.pushwoosh.PushwooshInboxKit\/5UIKit23UITraitChangeObservableP","doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UITraitEnvironment","doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIUserActivityRestoring"],"type":"conformsTo"}],"references":{"doc://com.pushwoosh.PushwooshInboxKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/s23CustomStringConvertibleP"},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)UILargeContentViewerItem":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UILargeContentViewerItem","type":"unresolvable","title":"UIKit.UILargeContentViewerItem"},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)NSCoding":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)NSCoding","type":"unresolvable","title":"Foundation.NSCoding"},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)UIGestureRecognizerDelegate":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIGestureRecognizerDelegate","type":"unresolvable","title":"UIKit.UIGestureRecognizerDelegate"},"doc://com.pushwoosh.PushwooshInboxKit/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)NSObject":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)UIFocusItemContainer":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIFocusItemContainer","type":"unresolvable","title":"UIKit.UIFocusItemContainer"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxCaptionedCell/init(style:reuseIdentifier:)":{"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCaptionedCell\/init(style:reuseIdentifier:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"style"},{"kind":"text","text":": "},{"text":"UITableViewCell","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableViewCell"},{"text":".","kind":"text"},{"kind":"typeIdentifier","text":"CellStyle","preciseIdentifier":"c:@E@UITableViewCellStyle"},{"kind":"text","text":", "},{"text":"reuseIdentifier","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxcaptionedcell\/init(style:reuseidentifier:)","navigatorTitle":[{"kind":"identifier","text":"initWithStyle:reuseIdentifier:"}],"abstract":[],"role":"symbol","title":"init(style:reuseIdentifier:)","kind":"symbol"},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)UIFocusItem":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIFocusItem","type":"unresolvable","title":"UIKit.UIFocusItem"},"doc://com.pushwoosh.PushwooshInboxKit/s7CVarArgP":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.pushwoosh.PushwooshInboxKit/5UIKit23UITraitChangeObservableP":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/5UIKit23UITraitChangeObservableP","type":"unresolvable","title":"UIKit.UITraitChangeObservable"},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)UIUserActivityRestoring":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIUserActivityRestoring","type":"unresolvable","title":"UIKit.UIUserActivityRestoring"},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)UIDynamicItem":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIDynamicItem","type":"unresolvable","title":"UIKit.UIDynamicItem"},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)UIPasteConfigurationSupporting":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIPasteConfigurationSupporting","type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting"},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)UIFocusEnvironment":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIFocusEnvironment","type":"unresolvable","title":"UIKit.UIFocusEnvironment"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxCaptionedCell":{"type":"topic","abstract":[],"title":"PushwooshInboxCaptionedCell","kind":"symbol","navigatorTitle":[{"text":"PushwooshInboxCaptionedCell","kind":"identifier"}],"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxcaptionedcell","role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCaptionedCell","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushwooshInboxCaptionedCell"}]},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxCaptionedCell/apply(message:attributes:)":{"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxcaptionedcell\/apply(message:attributes:)","title":"apply(message:attributes:)","abstract":[{"text":"Configures the cell for the given message and attributes. Subclasses may","type":"text"},{"text":" ","type":"text"},{"text":"override to render bespoke layouts; call ","type":"text"},{"type":"codeVoice","code":"super.apply(...)"},{"text":" to inherit","type":"text"},{"type":"text","text":" "},{"text":"dark-mode reactivity.","type":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCaptionedCell\/apply(message:attributes:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"apply"},{"text":"(","kind":"text"},{"text":"message","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(pl)PWInboxMessageProtocol","kind":"typeIdentifier","text":"PWInboxMessageProtocol"},{"kind":"text","text":", "},{"text":"attributes","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PushwooshInboxKitAttributes","preciseIdentifier":"s:17PushwooshInboxKit0abC10AttributesV","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","type":"topic"},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)UIAccessibilityIdentification":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIAccessibilityIdentification","type":"unresolvable","title":"UIKit.UIAccessibilityIdentification"},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)UIActivityItemsConfigurationProviding":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIActivityItemsConfigurationProviding","type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxCaptionedCell/prepareForReuse()":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"prepareForReuse","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"prepareForReuse","kind":"identifier"}],"type":"topic","abstract":[],"role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCaptionedCell\/prepareForReuse()","title":"prepareForReuse()","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxcaptionedcell\/prepareforreuse()","kind":"symbol"},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)UITraitEnvironment":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UITraitEnvironment","type":"unresolvable","title":"UIKit.UITraitEnvironment"},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)CALayerDelegate":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)CALayerDelegate","type":"unresolvable","title":"QuartzCore.CALayerDelegate"},"doc://com.pushwoosh.PushwooshInboxKit/SQ":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)UIAppearanceContainer":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIAppearanceContainer","type":"unresolvable","title":"UIKit.UIAppearanceContainer"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit","kind":"symbol","url":"\/documentation\/pushwooshinboxkit","title":"PushwooshInboxKit","role":"collection","abstract":[{"text":"Modern UIKit inbox UI powered by Pushwoosh.","type":"text"}],"type":"topic"},"doc://com.pushwoosh.PushwooshInboxKit/s8SendableP":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/s8SendableP","type":"unresolvable","title":"Swift.Sendable"},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)UIAppearance":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIAppearance","type":"unresolvable","title":"UIKit.UIAppearance"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxCaptionedCell/init(coder:)":{"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCaptionedCell\/init(coder:)","title":"init(coder:)","kind":"symbol","role":"symbol","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxcaptionedcell\/init(coder:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"text":"coder","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSCoder","text":"NSCoder","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}]},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)UIResponderStandardEditActions":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIResponderStandardEditActions","type":"unresolvable","title":"UIKit.UIResponderStandardEditActions"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxCell":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushwooshInboxCell"}],"title":"PushwooshInboxCell","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PushwooshInboxCell"}],"kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCell","abstract":[{"type":"text","text":"Default inbox table-view cell. Subclass this type and register it under a"},{"text":" ","type":"text"},{"type":"text","text":"custom kind via "},{"type":"reference","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitAttributes\/cells","isActive":true},{"type":"text","text":" to ship bespoke"},{"text":" ","type":"text"},{"text":"layouts.","type":"text"}],"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxcell"},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)UICoordinateSpace":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UICoordinateSpace","type":"unresolvable","title":"UIKit.UICoordinateSpace"},"doc://com.pushwoosh.PushwooshInboxKit/SH":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxKitAttributes/cells":{"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cells"},{"kind":"text","text":": ["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:@M@PushwooshInboxKit@objc(cs)PushwooshInboxCell","kind":"typeIdentifier","text":"PushwooshInboxCell"},{"text":".Type]","kind":"text"}],"title":"cells","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitAttributes\/cells","abstract":[{"type":"text","text":"Mapping of cell-kind identifiers to cell classes."}],"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxkitattributes\/cells"},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)UIPopoverPresentationControllerSourceItem":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIPopoverPresentationControllerSourceItem","type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"value":"PushwooshInboxCaptionedCell","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"value":[{"text":"PushwooshInboxCaptionedCell","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"PushwooshInboxCaptionedCell"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCaptionedCell\/init(coder:)","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCaptionedCell\/init(style:reuseIdentifier:)","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCaptionedCell\/prepareForReuse()"],"title":"Instance Methods"}]},{"value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCell"],"type":"inheritsFrom"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PushwooshInboxCaptionedCell","kind":"identifier"},{"kind":"text","text":" : "},{"text":"PushwooshInboxCell","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCell","kind":"typeIdentifier","preciseIdentifier":"c:@M@PushwooshInboxKit@objc(cs)PushwooshInboxCell"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"initWithStyle:reuseIdentifier:","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxCaptionedCell~1init(style:reuseIdentifier:)\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxCaptionedCell~1init(style:reuseIdentifier:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithStyle:reuseIdentifier:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxCaptionedCell\/title","value":"PushwooshInboxCaptionedCell"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxCaptionedCell\/fragments","value":[{"text":"PushwooshInboxCaptionedCell","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxCaptionedCell~1prepareForReuse()\/title","value":"prepareForReuse"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxCaptionedCell~1prepareForReuse()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"prepareForReuse","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxCaptionedCell~1init(coder:)\/title","value":"initWithCoder:","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxCaptionedCell~1init(coder:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithCoder:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxCell\/title","op":"replace","value":"PushwooshInboxCell"},{"op":"replace","value":[{"kind":"identifier","text":"PushwooshInboxCell"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxCell\/fragments"}]}]}