{"metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushwooshInboxKitDelegate"}],"title":"PushwooshInboxKitDelegate","roleHeading":"Protocol","symbolKind":"protocol","modules":[{"name":"PushwooshInboxKit"}],"navigatorTitle":[{"text":"PushwooshInboxKitDelegate","kind":"identifier"}],"externalID":"s:17PushwooshInboxKit0abC8DelegateP","role":"symbol"},"abstract":[{"type":"text","text":"Lifecycle and interaction callbacks for "},{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitViewController","isActive":true,"type":"reference"},{"type":"text","text":"."}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitDelegate"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PushwooshInboxKitDelegate"},{"kind":"text","text":" : AnyObject"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"level":2,"text":"Overview","type":"heading","anchor":"overview"},{"inlineContent":[{"text":"All methods carry a default implementation; conformance only requires the","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"callbacks the host actually wants to handle."}],"type":"paragraph"}]}],"kind":"symbol","variants":[{"paths":["\/documentation\/pushwooshinboxkit\/pushwooshinboxkitdelegate"],"traits":[{"interfaceLanguage":"swift"}]}],"seeAlsoSections":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitViewController","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitAttributes","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCell"],"title":"Public Surface","generated":true}],"schemaVersion":{"minor":3,"patch":0,"major":0},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitDelegate\/inboxKit(_:didAddWalletPassFor:)-hmiq","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitDelegate\/inboxKit(_:didFailToAddWalletPassFor:error:)-69muz","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitDelegate\/inboxKit(_:didRefreshWith:error:)-1vpwo","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitDelegate\/inboxKit(_:didSelect:)-2pkgo","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitDelegate\/inboxKit(_:didTapButton:onMessage:)-9e44b","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitDelegate\/inboxKit(_:shouldDelete:)-62yhf","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitDelegate\/inboxKit(_:willDisplay:at:)-6qqzf","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitDelegate\/inboxKit(didDismiss:)-6vs31"]}],"references":{"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxKitDelegate/inboxKit(_:willDisplay:at:)-6qqzf":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"inboxKit","kind":"identifier"},{"kind":"text","text":"("},{"text":"PushwooshInboxKitViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@PushwooshInboxKit@objc(cs)PushwooshInboxKitViewController"},{"text":", ","kind":"text"},{"text":"willDisplay","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PWInboxMessageProtocol","preciseIdentifier":"c:objc(pl)PWInboxMessageProtocol","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"at","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV","kind":"typeIdentifier"},{"kind":"text","text":")"}],"title":"inboxKit(_:willDisplay:at:)","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxkitdelegate\/inboxkit(_:willdisplay:at:)-6qqzf","defaultImplementations":1,"type":"topic","abstract":[{"text":"Invoked when a row is about to be displayed.","type":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitDelegate\/inboxKit(_:willDisplay:at:)-6qqzf","kind":"symbol","required":true},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxCell":{"navigatorTitle":[{"kind":"identifier","text":"PushwooshInboxCell"}],"title":"PushwooshInboxCell","abstract":[{"text":"Default inbox table-view cell. Subclass this type and register it under a","type":"text"},{"text":" ","type":"text"},{"text":"custom kind via ","type":"text"},{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitAttributes\/cells","isActive":true,"type":"reference"},{"text":" to ship bespoke","type":"text"},{"text":" ","type":"text"},{"text":"layouts.","type":"text"}],"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxcell","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCell","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PushwooshInboxCell"}],"kind":"symbol"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxKitDelegate/inboxKit(_:didSelect:)-2pkgo":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"inboxKit","kind":"identifier"},{"text":"(","kind":"text"},{"text":"PushwooshInboxKitViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@PushwooshInboxKit@objc(cs)PushwooshInboxKitViewController"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didSelect"},{"text":": ","kind":"text"},{"text":"PWInboxMessageProtocol","preciseIdentifier":"c:objc(pl)PWInboxMessageProtocol","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"title":"inboxKit(_:didSelect:)","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxkitdelegate\/inboxkit(_:didselect:)-2pkgo","defaultImplementations":1,"type":"topic","abstract":[{"type":"text","text":"Invoked on tap. Return "},{"type":"codeVoice","code":"true"},{"text":" to let the SDK perform the default action","type":"text"},{"text":" ","type":"text"},{"text":"(richmedia, URL, or deeplink). Return ","type":"text"},{"code":"false","type":"codeVoice"},{"text":" if the host has handled","type":"text"},{"text":" ","type":"text"},{"text":"the tap itself.","type":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitDelegate\/inboxKit(_:didSelect:)-2pkgo","kind":"symbol","required":true},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxKitViewController":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PushwooshInboxKitViewController","kind":"identifier"}],"navigatorTitle":[{"text":"PushwooshInboxKitViewController","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitViewController","title":"PushwooshInboxKitViewController","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxkitviewcontroller","role":"symbol","abstract":[{"type":"text","text":"Modern UIKit inbox controller backed by "},{"type":"codeVoice","code":"PWInboxService"},{"type":"text","text":"."}],"type":"topic"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxKitDelegate/inboxKit(_:didTapButton:onMessage:)-9e44b":{"type":"topic","kind":"symbol","abstract":[{"text":"Invoked when the user taps an inline CTA button rendered inside a cell.","type":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitDelegate\/inboxKit(_:didTapButton:onMessage:)-9e44b","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxkitdelegate\/inboxkit(_:didtapbutton:onmessage:)-9e44b","title":"inboxKit(_:didTapButton:onMessage:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"inboxKit","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@PushwooshInboxKit@objc(cs)PushwooshInboxKitViewController","text":"PushwooshInboxKitViewController","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"didTapButton","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"PushwooshInboxButton","preciseIdentifier":"s:17PushwooshInboxKit0aB6ButtonV"},{"kind":"text","text":", "},{"text":"onMessage","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PWInboxMessageProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)PWInboxMessageProtocol"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"defaultImplementations":1,"required":true},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxKitDelegate/inboxKit(_:shouldDelete:)-62yhf":{"required":true,"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"inboxKit","kind":"identifier"},{"kind":"text","text":"("},{"text":"PushwooshInboxKitViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@PushwooshInboxKit@objc(cs)PushwooshInboxKitViewController"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"shouldDelete"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(pl)PWInboxMessageProtocol","kind":"typeIdentifier","text":"PWInboxMessageProtocol"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"role":"symbol","title":"inboxKit(_:shouldDelete:)","kind":"symbol","defaultImplementations":1,"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxkitdelegate\/inboxkit(_:shoulddelete:)-62yhf","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitDelegate\/inboxKit(_:shouldDelete:)-62yhf","abstract":[{"type":"text","text":"Invoked before a swipe-to-delete commits. Return "},{"code":"false","type":"codeVoice"},{"text":" to cancel.","type":"text"}]},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxKitDelegate/inboxKit(_:didRefreshWith:error:)-1vpwo":{"required":true,"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"inboxKit","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PushwooshInboxKitViewController","preciseIdentifier":"c:@M@PushwooshInboxKit@objc(cs)PushwooshInboxKitViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didRefreshWith"},{"kind":"text","text":": ["},{"text":"PWInboxMessageProtocol","preciseIdentifier":"c:objc(pl)PWInboxMessageProtocol","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"error","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"role":"symbol","title":"inboxKit(_:didRefreshWith:error:)","kind":"symbol","defaultImplementations":1,"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxkitdelegate\/inboxkit(_:didrefreshwith:error:)-1vpwo","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitDelegate\/inboxKit(_:didRefreshWith:error:)-1vpwo","abstract":[{"type":"text","text":"Invoked after each refresh cycle (success or failure)."}]},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxKitAttributes":{"type":"topic","title":"PushwooshInboxKitAttributes","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"PushwooshInboxKitAttributes","kind":"identifier"}],"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxkitattributes","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitAttributes","kind":"symbol","abstract":[{"type":"text","text":"Configuration container for "},{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitViewController","type":"reference","isActive":true},{"type":"text","text":"."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PushwooshInboxKitAttributes"}]},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxKitDelegate/inboxKit(didDismiss:)-6vs31":{"required":true,"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"inboxKit","kind":"identifier"},{"kind":"text","text":"("},{"text":"didDismiss","kind":"externalParam"},{"kind":"text","text":": "},{"text":"PushwooshInboxKitViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@PushwooshInboxKit@objc(cs)PushwooshInboxKitViewController"},{"kind":"text","text":")"}],"role":"symbol","kind":"symbol","title":"inboxKit(didDismiss:)","defaultImplementations":1,"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxkitdelegate\/inboxkit(diddismiss:)-6vs31","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitDelegate\/inboxKit(didDismiss:)-6vs31","abstract":[{"text":"Invoked when the controller is being popped or dismissed.","type":"text"}]},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxKitAttributes/cells":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitAttributes\/cells","title":"cells","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxkitattributes\/cells","type":"topic","abstract":[{"type":"text","text":"Mapping of cell-kind identifiers to cell classes."}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cells","kind":"identifier"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:@M@PushwooshInboxKit@objc(cs)PushwooshInboxCell","kind":"typeIdentifier","text":"PushwooshInboxCell"},{"text":".Type]","kind":"text"}],"kind":"symbol"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxKitDelegate/inboxKit(_:didFailToAddWalletPassFor:error:)-69muz":{"abstract":[{"type":"text","text":"Invoked when adding an Apple Wallet pass failed — e.g. the "},{"type":"codeVoice","code":".pkpass"},{"text":" could not be","type":"text"},{"type":"text","text":" "},{"text":"downloaded. ","type":"text"},{"code":"error","type":"codeVoice"},{"text":" carries the underlying network error when available.","type":"text"}],"type":"topic","defaultImplementations":1,"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitDelegate\/inboxKit(_:didFailToAddWalletPassFor:error:)-69muz","kind":"symbol","title":"inboxKit(_:didFailToAddWalletPassFor:error:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"inboxKit"},{"text":"(","kind":"text"},{"text":"PushwooshInboxKitViewController","preciseIdentifier":"c:@M@PushwooshInboxKit@objc(cs)PushwooshInboxKitViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didFailToAddWalletPassFor","kind":"externalParam"},{"kind":"text","text":": "},{"text":"PWInboxMessageProtocol","preciseIdentifier":"c:objc(pl)PWInboxMessageProtocol","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?)"}],"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxkitdelegate\/inboxkit(_:didfailtoaddwalletpassfor:error:)-69muz","role":"symbol","required":true},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxKitDelegate":{"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PushwooshInboxKitDelegate","kind":"identifier"}],"title":"PushwooshInboxKitDelegate","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxkitdelegate","type":"topic","navigatorTitle":[{"text":"PushwooshInboxKitDelegate","kind":"identifier"}],"abstract":[{"text":"Lifecycle and interaction callbacks for ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitViewController","isActive":true},{"text":".","type":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitDelegate","kind":"symbol"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit":{"kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit","title":"PushwooshInboxKit","url":"\/documentation\/pushwooshinboxkit","role":"collection","abstract":[{"text":"Modern UIKit inbox UI powered by Pushwoosh.","type":"text"}],"type":"topic"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxKitDelegate/inboxKit(_:didAddWalletPassFor:)-hmiq":{"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"inboxKit","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@PushwooshInboxKit@objc(cs)PushwooshInboxKitViewController","text":"PushwooshInboxKitViewController"},{"text":", ","kind":"text"},{"text":"didAddWalletPassFor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PWInboxMessageProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)PWInboxMessageProtocol"},{"kind":"text","text":")"}],"required":true,"type":"topic","title":"inboxKit(_:didAddWalletPassFor:)","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitDelegate\/inboxKit(_:didAddWalletPassFor:)-hmiq","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxkitdelegate\/inboxkit(_:didaddwalletpassfor:)-hmiq","defaultImplementations":1,"abstract":[{"text":"Invoked when an Apple Wallet pass from a wallet card was successfully added to the user’s","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Wallet (the system add-passes sheet finished with the pass present in the library)."}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxCell\/title","value":"PushwooshInboxCell","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxCell\/fragments","op":"replace","value":[{"kind":"identifier","text":"PushwooshInboxCell"}]},{"op":"replace","value":"PushwooshInboxKitViewController","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxKitViewController\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxKitViewController\/fragments","value":[{"text":"PushwooshInboxKitViewController","kind":"identifier"}]}]}]}