{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushwooshInboxVideoContent"}]}]},{"content":[{"anchor":"overview","type":"heading","text":"Overview","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Like the carousel slides, the video descriptor cannot live in the standard message fields, so"},{"text":" ","type":"text"},{"type":"text","text":"it arrives in "},{"code":"actionParams[\"video\"]","type":"codeVoice"},{"type":"text","text":" and is decoded by "},{"type":"reference","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxVideoContent\/decode(from:)","isActive":true},{"type":"text","text":". The cell shows the"},{"text":" ","type":"text"},{"text":"poster with a play badge; tapping it opens a full-screen player.","type":"text"}]}],"kind":"content"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxVideoContent","interfaceLanguage":"swift"},"metadata":{"symbolKind":"struct","externalID":"s:17PushwooshInboxKit0aB12VideoContentV","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PushwooshInboxVideoContent"}],"roleHeading":"Structure","title":"PushwooshInboxVideoContent","navigatorTitle":[{"text":"PushwooshInboxVideoContent","kind":"identifier"}],"modules":[{"name":"PushwooshInboxKit"}]},"abstract":[{"text":"Video payload for a ","type":"text"},{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxVideoCell","isActive":true,"type":"reference"},{"type":"text","text":"."}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/pushwooshinboxkit\/pushwooshinboxvideocontent"],"traits":[{"interfaceLanguage":"swift"}]}],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxVideoContent\/init(videoURL:posterURL:)"]},{"identifiers":["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxVideoContent\/posterURL","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxVideoContent\/videoURL"],"title":"Instance Properties"},{"identifiers":["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxVideoContent\/decode(from:)"],"title":"Type Methods"}],"seeAlsoSections":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxBannerCell","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCaptionedCell","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxClassicCell","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCarouselCell","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxVideoCell","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxWalletCell","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCarouselSlide","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxWalletPass"],"title":"Rich Cards","generated":true}],"references":{"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxClassicCell":{"title":"PushwooshInboxClassicCell","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushwooshInboxClassicCell"}],"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxclassiccell","navigatorTitle":[{"text":"PushwooshInboxClassicCell","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxClassicCell","abstract":[]},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxCarouselCell":{"role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCarouselCell","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PushwooshInboxCarouselCell","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PushwooshInboxCarouselCell"}],"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxcarouselcell","abstract":[],"title":"PushwooshInboxCarouselCell","type":"topic","kind":"symbol"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxCarouselSlide":{"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxcarouselslide","navigatorTitle":[{"text":"PushwooshInboxCarouselSlide","kind":"identifier"}],"abstract":[{"text":"A single slide inside a ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCarouselCell","isActive":true},{"type":"text","text":"."}],"title":"PushwooshInboxCarouselSlide","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCarouselSlide","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushwooshInboxCarouselSlide"}]},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxVideoContent/init(videoURL:posterURL:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"videoURL","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"posterURL","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?)","kind":"text"}],"kind":"symbol","type":"topic","title":"init(videoURL:posterURL:)","role":"symbol","abstract":[],"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxvideocontent\/init(videourl:posterurl:)","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxVideoContent\/init(videoURL:posterURL:)"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxVideoContent/posterURL":{"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"posterURL"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxvideocontent\/posterurl","abstract":[{"type":"text","text":"Optional poster image shown in the cell as the preview."}],"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxVideoContent\/posterURL","title":"posterURL","kind":"symbol","type":"topic"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxCaptionedCell":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PushwooshInboxCaptionedCell"}],"role":"symbol","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCaptionedCell","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxcaptionedcell","navigatorTitle":[{"kind":"identifier","text":"PushwooshInboxCaptionedCell"}],"title":"PushwooshInboxCaptionedCell","type":"topic"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxVideoContent/decode(from:)":{"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"decode","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(pl)PWInboxMessageProtocol","kind":"typeIdentifier","text":"PWInboxMessageProtocol"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"PushwooshInboxVideoContent","preciseIdentifier":"s:17PushwooshInboxKit0aB12VideoContentV"},{"kind":"text","text":"?"}],"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxvideocontent\/decode(from:)","abstract":[{"type":"text","text":"Decodes the video descriptor from a message’s "},{"type":"codeVoice","code":"actionParams"},{"type":"text","text":". Expected shapes (mirrors"},{"type":"text","text":" "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxButton"},{"text":" \/ ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCarouselSlide"},{"text":"):","type":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxVideoContent\/decode(from:)","title":"decode(from:)","kind":"symbol","type":"topic"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit":{"kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit","title":"PushwooshInboxKit","url":"\/documentation\/pushwooshinboxkit","role":"collection","abstract":[{"text":"Modern UIKit inbox UI powered by Pushwoosh.","type":"text"}],"type":"topic"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxBannerCell":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PushwooshInboxBannerCell","kind":"identifier"}],"title":"PushwooshInboxBannerCell","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxbannercell","type":"topic","navigatorTitle":[{"text":"PushwooshInboxBannerCell","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxBannerCell","kind":"symbol"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxWalletCell":{"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxwalletcell","role":"symbol","abstract":[],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PushwooshInboxWalletCell","kind":"identifier"}],"title":"PushwooshInboxWalletCell","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxWalletCell","navigatorTitle":[{"text":"PushwooshInboxWalletCell","kind":"identifier"}],"type":"topic"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxVideoContent/videoURL":{"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"videoURL"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"}],"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxvideocontent\/videourl","abstract":[{"text":"Remote URL of the video stream \/ file played full-screen on tap. Required.","type":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxVideoContent\/videoURL","title":"videoURL","kind":"symbol","type":"topic"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxButton":{"title":"PushwooshInboxButton","type":"topic","role":"symbol","navigatorTitle":[{"text":"PushwooshInboxButton","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxButton","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxbutton","abstract":[{"type":"text","text":"A single inline call-to-action button rendered inside an inbox cell."}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PushwooshInboxButton","kind":"identifier"}],"kind":"symbol"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxVideoCell":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PushwooshInboxVideoCell","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxVideoCell","type":"topic","kind":"symbol","title":"PushwooshInboxVideoCell","role":"symbol","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxvideocell","navigatorTitle":[{"text":"PushwooshInboxVideoCell","kind":"identifier"}],"abstract":[]},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxWalletPass":{"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxwalletpass","navigatorTitle":[{"text":"PushwooshInboxWalletPass","kind":"identifier"}],"abstract":[{"text":"Apple Wallet pass descriptor for a ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxWalletCell"},{"text":".","type":"text"}],"title":"PushwooshInboxWalletPass","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxWalletPass","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"PushwooshInboxWalletPass","kind":"identifier"}]},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxVideoContent":{"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxvideocontent","navigatorTitle":[{"text":"PushwooshInboxVideoContent","kind":"identifier"}],"abstract":[{"text":"Video payload for a ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxVideoCell","isActive":true},{"type":"text","text":"."}],"title":"PushwooshInboxVideoContent","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxVideoContent","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushwooshInboxVideoContent"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxClassicCell\/title","value":"PushwooshInboxClassicCell","op":"replace"},{"value":[{"kind":"identifier","text":"PushwooshInboxClassicCell"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxClassicCell\/fragments","op":"replace"},{"value":"PushwooshInboxCarouselCell","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxCarouselCell\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxCarouselCell\/fragments","op":"replace","value":[{"kind":"identifier","text":"PushwooshInboxCarouselCell"}]},{"value":"PushwooshInboxCaptionedCell","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxCaptionedCell\/title","op":"replace"},{"op":"replace","value":[{"text":"PushwooshInboxCaptionedCell","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxCaptionedCell\/fragments"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxBannerCell\/title","value":"PushwooshInboxBannerCell","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"PushwooshInboxBannerCell"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxBannerCell\/fragments"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxWalletCell\/title","value":"PushwooshInboxWalletCell","op":"replace"},{"value":[{"text":"PushwooshInboxWalletCell","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxWalletCell\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxVideoCell\/title","value":"PushwooshInboxVideoCell"},{"value":[{"text":"PushwooshInboxVideoCell","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxVideoCell\/fragments","op":"replace"}]}]}