{"metadata":{"modules":[{"name":"PushwooshInboxKit"}],"title":"PushwooshInboxKitImplementation","symbolKind":"class","roleHeading":"Class","externalID":"c:@M@PushwooshInboxKit@objc(cs)PushwooshInboxKitImplementation","navigatorTitle":[{"text":"PushwooshInboxKitImplementation","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PushwooshInboxKitImplementation"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitImplementation\/inboxKit()","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitImplementation\/makeViewController()"],"title":"Type Methods"}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From"},{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)NSObject","doc:\/\/com.pushwoosh.PushwooshInboxKit\/@M@PushwooshBridge@objc(pl)PWInboxKit","doc:\/\/com.pushwoosh.PushwooshInboxKit\/s7CVarArgP","doc:\/\/com.pushwoosh.PushwooshInboxKit\/s28CustomDebugStringConvertibleP","doc:\/\/com.pushwoosh.PushwooshInboxKit\/s23CustomStringConvertibleP","doc:\/\/com.pushwoosh.PushwooshInboxKit\/SQ","doc:\/\/com.pushwoosh.PushwooshInboxKit\/SH"]}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit"]]},"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitImplementation","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(PushwooshInboxKitImplementation) ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PushwooshInboxKitImplementation","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"type":"heading","anchor":"overview","text":"Overview","level":2},{"inlineContent":[{"text":"Hosts instantiate the controller directly:","type":"text"}],"type":"paragraph"},{"items":[{"content":[{"inlineContent":[{"type":"text","text":"Swift: "},{"type":"codeVoice","code":"PushwooshInboxKitViewController(attributes:)"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"Obj-C: ","type":"text"},{"type":"codeVoice","code":"[[PushwooshInboxKitViewController alloc] init]"}],"type":"paragraph"}]}],"type":"unorderedList"}]}],"variants":[{"paths":["\/documentation\/pushwooshinboxkit\/pushwooshinboxkitimplementation"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshinboxkit\/pushwooshinboxkitimplementation"]}],"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"Implementation entry-point discovered by the umbrella SDK via"},{"text":" ","type":"text"},{"code":"NSClassFromString(\"PushwooshInboxKitImplementation\")","type":"codeVoice"},{"text":".","type":"text"}],"references":{"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxKitImplementation/inboxKit()":{"type":"topic","navigatorTitle":[{"text":"inboxKit","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitImplementation\/inboxKit()","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"inboxKit","kind":"identifier"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:s8AnyClassa","kind":"typeIdentifier","text":"AnyClass"}],"role":"symbol","title":"inboxKit()","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxkitimplementation\/inboxkit()","abstract":[],"kind":"symbol"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit":{"role":"collection","url":"\/documentation\/pushwooshinboxkit","title":"PushwooshInboxKit","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Modern UIKit inbox UI powered by Pushwoosh."}]},"doc://com.pushwoosh.PushwooshInboxKit/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/s23CustomStringConvertibleP"},"doc://com.pushwoosh.PushwooshInboxKit/@M@PushwooshBridge@objc(pl)PWInboxKit":{"title":"PWInboxKit","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/@M@PushwooshBridge@objc(pl)PWInboxKit","type":"unresolvable"},"doc://com.pushwoosh.PushwooshInboxKit/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(cs)NSObject"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxKitImplementation/makeViewController()":{"title":"makeViewController()","abstract":[{"text":"Convenience factory for Obj-C hosts that want a default-configured","type":"text"},{"text":" ","type":"text"},{"text":"controller without touching the Swift ","type":"text"},{"code":"Attributes","type":"codeVoice"},{"type":"text","text":" struct."}],"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitImplementation\/makeViewController()","kind":"symbol","type":"topic","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxkitimplementation\/makeviewcontroller()","navigatorTitle":[{"kind":"identifier","text":"makeViewController"}],"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"makeViewController","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"}]},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)NSObject","type":"unresolvable"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxKitImplementation":{"type":"topic","navigatorTitle":[{"text":"PushwooshInboxKitImplementation","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitImplementation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PushwooshInboxKitImplementation","kind":"identifier"}],"role":"symbol","title":"PushwooshInboxKitImplementation","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxkitimplementation","abstract":[{"text":"Implementation entry-point discovered by the umbrella SDK via","type":"text"},{"type":"text","text":" "},{"type":"codeVoice","code":"NSClassFromString(\"PushwooshInboxKitImplementation\")"},{"text":".","type":"text"}],"kind":"symbol"},"doc://com.pushwoosh.PushwooshInboxKit/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxKitImplementation/init":{"type":"topic","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitImplementation\/init","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxkitimplementation\/init","navigatorTitle":[{"kind":"identifier","text":"init"}],"title":"init","abstract":[]},"doc://com.pushwoosh.PushwooshInboxKit/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/SQ","type":"unresolvable"},"doc://com.pushwoosh.PushwooshInboxKit/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/s7CVarArgP","type":"unresolvable"},"doc://com.pushwoosh.PushwooshInboxKit/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/SH","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"PushwooshInboxKitImplementation"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"path":"\/metadata\/fragments","value":[{"text":"PushwooshInboxKitImplementation","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"PushwooshInboxKitImplementation"}],"op":"replace"},{"path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitImplementation\/init"]},{"title":"Type Methods","identifiers":["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitImplementation\/inboxKit()","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitImplementation\/makeViewController()"]}],"op":"replace"},{"path":"\/relationshipsSections","op":"replace","value":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(cs)NSObject"],"title":"Inherits From"},{"identifiers":["doc:\/\/com.pushwoosh.PushwooshInboxKit\/@M@PushwooshBridge@objc(pl)PWInboxKit"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}]},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PushwooshInboxKitImplementation"},{"kind":"text","text":" : "},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"inboxKit","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxKitImplementation~1inboxKit()\/title","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"inboxKit"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxKitImplementation~1inboxKit()\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxKitImplementation~1makeViewController()\/title","value":"makeViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxKitImplementation~1makeViewController()\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"makeViewController","kind":"identifier"}]},{"op":"replace","value":"PushwooshInboxKitImplementation","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxKitImplementation\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxKitImplementation\/fragments","value":[{"text":"PushwooshInboxKitImplementation","kind":"identifier"}],"op":"replace"}]}]}