{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshinboxkit\/pushwooshinboxwalletcell"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshinboxkit\/pushwooshinboxwalletcell"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxWalletCell\/init(coder:)","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxWalletCell\/init(style:reuseIdentifier:)"]},{"identifiers":["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxWalletCell\/onAddToWallet"],"title":"Instance Properties"},{"identifiers":["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxWalletCell\/apply(message:attributes:)","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxWalletCell\/prepareForReuse()","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxWalletCell\/setHighlighted(_:animated:)"],"title":"Instance Methods"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(PushwooshInboxWalletCell) ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PushwooshInboxWalletCell","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxWalletCell"},"relationshipsSections":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCell"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"kind":"relationships","identifiers":["doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)NSCoding","doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)NSObject","doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)CALayerDelegate","doc:\/\/com.pushwoosh.PushwooshInboxKit\/s7CVarArgP","doc:\/\/com.pushwoosh.PushwooshInboxKit\/s28CustomDebugStringConvertibleP","doc:\/\/com.pushwoosh.PushwooshInboxKit\/s23CustomStringConvertibleP","doc:\/\/com.pushwoosh.PushwooshInboxKit\/SQ","doc:\/\/com.pushwoosh.PushwooshInboxKit\/SH","doc:\/\/com.pushwoosh.PushwooshInboxKit\/s8SendableP","doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIAccessibilityIdentification","doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIAppearance","doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIAppearanceContainer","doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UICoordinateSpace","doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIDynamicItem","doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIFocusEnvironment","doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIFocusItem","doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIFocusItemContainer","doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIGestureRecognizerDelegate","doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UILargeContentViewerItem","doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.pushwoosh.PushwooshInboxKit\/5UIKit23UITraitChangeObservableP","doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UITraitEnvironment","doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIUserActivityRestoring"],"type":"conformsTo","title":"Conforms To"}],"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PushwooshInboxWalletCell","kind":"identifier"}],"role":"symbol","roleHeading":"Class","modules":[{"name":"PushwooshInboxKit"}],"symbolKind":"class","navigatorTitle":[{"kind":"identifier","text":"PushwooshInboxWalletCell"}],"title":"PushwooshInboxWalletCell","externalID":"c:@M@PushwooshInboxKit@objc(cs)PushwooshInboxWalletCell"},"sections":[],"seeAlsoSections":[{"title":"Rich Cards","identifiers":["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxBannerCell","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCaptionedCell","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxClassicCell","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCarouselCell","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxVideoCell","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCarouselSlide","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxVideoContent","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxWalletPass"],"generated":true}],"references":{"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxCaptionedCell":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PushwooshInboxCaptionedCell"}],"role":"symbol","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCaptionedCell","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxcaptionedcell","navigatorTitle":[{"kind":"identifier","text":"PushwooshInboxCaptionedCell"}],"title":"PushwooshInboxCaptionedCell","type":"topic"},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)UIAccessibilityIdentification":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIAccessibilityIdentification","title":"UIKit.UIAccessibilityIdentification","type":"unresolvable"},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)UIActivityItemsConfigurationProviding":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIActivityItemsConfigurationProviding","title":"UIKit.UIActivityItemsConfigurationProviding","type":"unresolvable"},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)UIResponderStandardEditActions":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIResponderStandardEditActions","title":"UIKit.UIResponderStandardEditActions","type":"unresolvable"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxWalletPass":{"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxwalletpass","navigatorTitle":[{"text":"PushwooshInboxWalletPass","kind":"identifier"}],"abstract":[{"text":"Apple Wallet pass descriptor for a ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxWalletCell"},{"text":".","type":"text"}],"title":"PushwooshInboxWalletPass","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxWalletPass","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"PushwooshInboxWalletPass","kind":"identifier"}]},"doc://com.pushwoosh.PushwooshInboxKit/SQ":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxCarouselSlide":{"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxcarouselslide","navigatorTitle":[{"text":"PushwooshInboxCarouselSlide","kind":"identifier"}],"abstract":[{"text":"A single slide inside a ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCarouselCell","isActive":true},{"type":"text","text":"."}],"title":"PushwooshInboxCarouselSlide","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCarouselSlide","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushwooshInboxCarouselSlide"}]},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)UIFocusEnvironment":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIFocusEnvironment","title":"UIKit.UIFocusEnvironment","type":"unresolvable"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxWalletCell/prepareForReuse()":{"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxWalletCell\/prepareForReuse()","abstract":[],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"prepareForReuse","kind":"identifier"},{"kind":"text","text":"()"}],"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxwalletcell\/prepareforreuse()","navigatorTitle":[{"text":"prepareForReuse","kind":"identifier"}],"title":"prepareForReuse()"},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)UIPasteConfigurationSupporting":{"title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIPasteConfigurationSupporting","type":"unresolvable"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxCarouselCell":{"role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCarouselCell","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PushwooshInboxCarouselCell","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PushwooshInboxCarouselCell"}],"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxcarouselcell","abstract":[],"title":"PushwooshInboxCarouselCell","type":"topic","kind":"symbol"},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)UIPopoverPresentationControllerSourceItem":{"title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIPopoverPresentationControllerSourceItem","type":"unresolvable"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxWalletCell/apply(message:attributes:)":{"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxWalletCell\/apply(message:attributes:)","abstract":[{"text":"Configures the cell for the given message and attributes. Subclasses may","type":"text"},{"type":"text","text":" "},{"text":"override to render bespoke layouts; call ","type":"text"},{"type":"codeVoice","code":"super.apply(...)"},{"type":"text","text":" to inherit"},{"type":"text","text":" "},{"text":"dark-mode reactivity.","type":"text"}],"role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"apply"},{"kind":"text","text":"("},{"text":"message","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(pl)PWInboxMessageProtocol","kind":"typeIdentifier","text":"PWInboxMessageProtocol"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"attributes"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"PushwooshInboxKitAttributes","preciseIdentifier":"s:17PushwooshInboxKit0abC10AttributesV"},{"kind":"text","text":")"}],"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxwalletcell\/apply(message:attributes:)","title":"apply(message:attributes:)"},"doc://com.pushwoosh.PushwooshInboxKit/SH":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxBannerCell":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PushwooshInboxBannerCell","kind":"identifier"}],"title":"PushwooshInboxBannerCell","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxbannercell","type":"topic","navigatorTitle":[{"text":"PushwooshInboxBannerCell","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxBannerCell","kind":"symbol"},"doc://com.pushwoosh.PushwooshInboxKit/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)UILargeContentViewerItem":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UILargeContentViewerItem","title":"UIKit.UILargeContentViewerItem","type":"unresolvable"},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)NSCoding":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)NSCoding","title":"Foundation.NSCoding","type":"unresolvable"},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)UIGestureRecognizerDelegate":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIGestureRecognizerDelegate","title":"UIKit.UIGestureRecognizerDelegate","type":"unresolvable"},"doc://com.pushwoosh.PushwooshInboxKit/s8SendableP":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/s8SendableP","title":"Swift.Sendable","type":"unresolvable"},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)UIAppearance":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIAppearance","title":"UIKit.UIAppearance","type":"unresolvable"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit":{"kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit","title":"PushwooshInboxKit","url":"\/documentation\/pushwooshinboxkit","role":"collection","abstract":[{"text":"Modern UIKit inbox UI powered by Pushwoosh.","type":"text"}],"type":"topic"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxVideoContent":{"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxvideocontent","navigatorTitle":[{"text":"PushwooshInboxVideoContent","kind":"identifier"}],"abstract":[{"text":"Video payload for a ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxVideoCell","isActive":true},{"type":"text","text":"."}],"title":"PushwooshInboxVideoContent","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxVideoContent","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushwooshInboxVideoContent"}]},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxWalletCell":{"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxwalletcell","role":"symbol","abstract":[],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PushwooshInboxWalletCell","kind":"identifier"}],"title":"PushwooshInboxWalletCell","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxWalletCell","navigatorTitle":[{"text":"PushwooshInboxWalletCell","kind":"identifier"}],"type":"topic"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxWalletCell/setHighlighted(_:animated:)":{"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setHighlighted","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"animated"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}],"role":"symbol","title":"setHighlighted(_:animated:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"setHighlighted:animated:"}],"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxwalletcell\/sethighlighted(_:animated:)","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxWalletCell\/setHighlighted(_:animated:)","abstract":[{"type":"text","text":"Subtle press feedback for taps that land on the card chrome (outside the Add button)."}]},"doc://com.pushwoosh.PushwooshInboxKit/s7CVarArgP":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxKitAttributes/cells":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitAttributes\/cells","title":"cells","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxkitattributes\/cells","type":"topic","abstract":[{"type":"text","text":"Mapping of cell-kind identifiers to cell classes."}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cells","kind":"identifier"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:@M@PushwooshInboxKit@objc(cs)PushwooshInboxCell","kind":"typeIdentifier","text":"PushwooshInboxCell"},{"text":".Type]","kind":"text"}],"kind":"symbol"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxWalletCell/init(coder:)":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxWalletCell\/init(coder:)","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxwalletcell\/init(coder:)","abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"coder"},{"text":": ","kind":"text"},{"text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder","kind":"typeIdentifier"},{"kind":"text","text":")"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}],"kind":"symbol","title":"init(coder:)"},"doc://com.pushwoosh.PushwooshInboxKit/5UIKit23UITraitChangeObservableP":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/5UIKit23UITraitChangeObservableP","title":"UIKit.UITraitChangeObservable","type":"unresolvable"},"doc://com.pushwoosh.PushwooshInboxKit/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)UIFocusItemContainer":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIFocusItemContainer","title":"UIKit.UIFocusItemContainer","type":"unresolvable"},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)UICoordinateSpace":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UICoordinateSpace","title":"UIKit.UICoordinateSpace","type":"unresolvable"},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)UIDynamicItem":{"title":"UIKit.UIDynamicItem","type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIDynamicItem"},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)UIFocusItem":{"title":"UIKit.UIFocusItem","type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIFocusItem"},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)UIUserActivityRestoring":{"title":"UIKit.UIUserActivityRestoring","type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIUserActivityRestoring"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxClassicCell":{"title":"PushwooshInboxClassicCell","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushwooshInboxClassicCell"}],"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxclassiccell","navigatorTitle":[{"text":"PushwooshInboxClassicCell","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxClassicCell","abstract":[]},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)CALayerDelegate":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)CALayerDelegate","title":"QuartzCore.CALayerDelegate","type":"unresolvable"},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)NSObject"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxVideoCell":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PushwooshInboxVideoCell","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxVideoCell","type":"topic","kind":"symbol","title":"PushwooshInboxVideoCell","role":"symbol","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxvideocell","navigatorTitle":[{"text":"PushwooshInboxVideoCell","kind":"identifier"}],"abstract":[]},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxWalletCell/init(style:reuseIdentifier:)":{"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"style","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UITableViewCell","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableViewCell"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"CellStyle","preciseIdentifier":"c:@E@UITableViewCellStyle"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"reuseIdentifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?)"}],"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxwalletcell\/init(style:reuseidentifier:)","abstract":[],"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxWalletCell\/init(style:reuseIdentifier:)","title":"init(style:reuseIdentifier:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithStyle:reuseIdentifier:"}]},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)UIAppearanceContainer":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIAppearanceContainer","title":"UIKit.UIAppearanceContainer","type":"unresolvable"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxWalletCell/onAddToWallet":{"kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onAddToWallet"},{"kind":"text","text":": (("},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?","kind":"text"}],"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxwalletcell\/onaddtowallet","type":"topic","title":"onAddToWallet","abstract":[{"text":"Invoked when the “Add to Apple Wallet” button is tapped. The controller","type":"text"},{"text":" ","type":"text"},{"text":"downloads the ","type":"text"},{"code":".pkpass","type":"codeVoice"},{"type":"text","text":" and presents the system add-passes sheet."}],"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxWalletCell\/onAddToWallet"},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)UITraitEnvironment":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UITraitEnvironment","title":"UIKit.UITraitEnvironment","type":"unresolvable"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxCell":{"navigatorTitle":[{"kind":"identifier","text":"PushwooshInboxCell"}],"title":"PushwooshInboxCell","abstract":[{"text":"Default inbox table-view cell. Subclass this type and register it under a","type":"text"},{"text":" ","type":"text"},{"text":"custom kind via ","type":"text"},{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitAttributes\/cells","isActive":true,"type":"reference"},{"text":" to ship bespoke","type":"text"},{"text":" ","type":"text"},{"text":"layouts.","type":"text"}],"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxcell","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCell","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PushwooshInboxCell"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"PushwooshInboxWalletCell"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"PushwooshInboxWalletCell"}]},{"op":"replace","value":[{"text":"PushwooshInboxWalletCell","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxWalletCell\/init(coder:)","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxWalletCell\/init(style:reuseIdentifier:)","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxWalletCell\/prepareForReuse()","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxWalletCell\/setHighlighted(_:animated:)"]}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"replace","value":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCell"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"}]},{"value":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxBannerCell","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCaptionedCell","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxClassicCell","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCarouselCell","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxVideoCell"],"title":"Rich Cards","generated":true}],"op":"replace","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"PushwooshInboxWalletCell","kind":"identifier"},{"kind":"text","text":" : "},{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCell","preciseIdentifier":"c:@M@PushwooshInboxKit@objc(cs)PushwooshInboxCell","kind":"typeIdentifier","text":"PushwooshInboxCell"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"PushwooshInboxCaptionedCell","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxCaptionedCell\/title"},{"op":"replace","value":[{"text":"PushwooshInboxCaptionedCell","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxCaptionedCell\/fragments"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxWalletCell~1prepareForReuse()\/title","op":"replace","value":"prepareForReuse"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"prepareForReuse"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxWalletCell~1prepareForReuse()\/fragments"},{"value":"PushwooshInboxCarouselCell","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxCarouselCell\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"PushwooshInboxCarouselCell"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxCarouselCell\/fragments"},{"value":"PushwooshInboxBannerCell","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxBannerCell\/title","op":"replace"},{"value":[{"text":"PushwooshInboxBannerCell","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxBannerCell\/fragments"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxWalletCell\/title","op":"replace","value":"PushwooshInboxWalletCell"},{"op":"replace","value":[{"text":"PushwooshInboxWalletCell","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxWalletCell\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxWalletCell~1setHighlighted(_:animated:)\/title","value":"setHighlighted:animated:"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxWalletCell~1setHighlighted(_:animated:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"setHighlighted:animated:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxWalletCell~1init(coder:)\/title","value":"initWithCoder:"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithCoder:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxWalletCell~1init(coder:)\/fragments"},{"value":"PushwooshInboxClassicCell","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxClassicCell\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxClassicCell\/fragments","op":"replace","value":[{"text":"PushwooshInboxClassicCell","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxVideoCell\/title","value":"PushwooshInboxVideoCell"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxVideoCell\/fragments","op":"replace","value":[{"kind":"identifier","text":"PushwooshInboxVideoCell"}]},{"value":"initWithStyle:reuseIdentifier:","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxWalletCell~1init(style:reuseIdentifier:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"initWithStyle:reuseIdentifier:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxWalletCell~1init(style:reuseIdentifier:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxCell\/title","value":"PushwooshInboxCell"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxCell\/fragments","op":"replace","value":[{"text":"PushwooshInboxCell","kind":"identifier"}]}]}]}