{"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/pushwooshinboxkit\/pushwooshinboxkitattributes"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitAttributes","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"PushwooshInboxKitAttributes","kind":"identifier"}],"platforms":["iOS"]}]},{"content":[{"type":"heading","level":2,"text":"Overview","anchor":"overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Use a value-typed "},{"type":"codeVoice","code":"Attributes"},{"type":"text","text":" to drive cell registration, transform pipeline,"},{"type":"text","text":" "},{"type":"text","text":"behavior toggles, and visual style. The default configuration ships with a"},{"text":" ","type":"text"},{"text":"single polished cell, dynamic dark-mode-aware colors, automatic mark-as-read","type":"text"},{"text":" ","type":"text"},{"text":"on disappear, and swipe-to-delete enabled.","type":"text"}]}],"kind":"content"}],"topicSections":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitAttributes\/Style-swift.struct"],"title":"Structures"},{"identifiers":["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitAttributes\/init()"],"title":"Initializers"},{"identifiers":["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitAttributes\/automaticReadOnDisappear","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitAttributes\/cellKindResolver","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitAttributes\/cells","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitAttributes\/emptyMessage","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitAttributes\/enableDarkTheme","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitAttributes\/errorMessage","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitAttributes\/forceCellKind","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitAttributes\/inlineButtonsEnabled","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitAttributes\/pinningEnabled","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitAttributes\/pullToRefreshEnabled","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitAttributes\/style-swift.property","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitAttributes\/swipeToDeleteEnabled","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitAttributes\/transform"],"title":"Instance Properties"},{"title":"Type Properties","identifiers":["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitAttributes\/defaultCellKindResolver"]},{"title":"Type Methods","identifiers":["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitAttributes\/defaultTransform(pinningEnabled:)","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitAttributes\/isPinned(_:)"]},{"title":"Enumerations","identifiers":["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitAttributes\/CellKind"]}],"kind":"symbol","seeAlsoSections":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitViewController","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitDelegate","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCell"],"generated":true,"title":"Public Surface"}],"sections":[],"metadata":{"modules":[{"name":"PushwooshInboxKit"}],"symbolKind":"struct","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushwooshInboxKitAttributes"}],"roleHeading":"Structure","title":"PushwooshInboxKitAttributes","navigatorTitle":[{"text":"PushwooshInboxKitAttributes","kind":"identifier"}],"role":"symbol","externalID":"s:17PushwooshInboxKit0abC10AttributesV"},"abstract":[{"type":"text","text":"Configuration container for "},{"type":"reference","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitViewController","isActive":true},{"type":"text","text":"."}],"references":{"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxKitAttributes/inlineButtonsEnabled":{"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxkitattributes\/inlinebuttonsenabled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"inlineButtonsEnabled"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"abstract":[{"text":"When ","type":"text"},{"type":"codeVoice","code":"true"},{"text":", cells render up to N inline CTA buttons parsed from","type":"text"},{"text":" ","type":"text"},{"type":"codeVoice","code":"actionParams[\"buttons\"]"},{"type":"text","text":". Disable to ignore the server-supplied"},{"type":"text","text":" "},{"type":"text","text":"buttons regardless of payload."}],"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitAttributes\/inlineButtonsEnabled","title":"inlineButtonsEnabled","kind":"symbol","role":"symbol"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxKitAttributes/transform":{"type":"topic","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxkitattributes\/transform","abstract":[{"type":"text","text":"Pipeline applied to the raw inbox payload before reload. Use to sort,"},{"text":" ","type":"text"},{"type":"text","text":"filter, or group messages."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"transform","kind":"identifier"},{"kind":"text","text":": (["},{"text":"PWInboxMessageProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)PWInboxMessageProtocol"},{"text":"]) -> [","kind":"text"},{"preciseIdentifier":"c:objc(pl)PWInboxMessageProtocol","text":"PWInboxMessageProtocol","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"title":"transform","role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitAttributes\/transform","kind":"symbol"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxKitAttributes/init()":{"type":"topic","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxkitattributes\/init()","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"title":"init()","role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitAttributes\/init()","kind":"symbol"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxKitAttributes/Style-swift.struct":{"abstract":[{"text":"Visual style applied to the controller chrome and the default cell.","type":"text"}],"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxkitattributes\/style-swift.struct","role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitAttributes\/Style-swift.struct","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Style"}],"title":"PushwooshInboxKitAttributes.Style","kind":"symbol","navigatorTitle":[{"text":"Style","kind":"identifier"}]},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxKitAttributes/emptyMessage":{"type":"topic","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxkitattributes\/emptymessage","abstract":[{"type":"text","text":"Empty-state message rendered when the inbox returns zero messages."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"emptyMessage","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"title":"emptyMessage","role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitAttributes\/emptyMessage","kind":"symbol"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxKitAttributes/automaticReadOnDisappear":{"type":"topic","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxkitattributes\/automaticreadondisappear","abstract":[{"text":"When ","type":"text"},{"type":"codeVoice","code":"true"},{"text":", all messages currently visible on screen are marked as read","type":"text"},{"text":" ","type":"text"},{"text":"when the controller disappears (single batch, idempotent server-side).","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"automaticReadOnDisappear","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"automaticReadOnDisappear","role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitAttributes\/automaticReadOnDisappear","kind":"symbol"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxKitViewController":{"role":"symbol","kind":"symbol","abstract":[{"text":"Modern UIKit inbox controller backed by ","type":"text"},{"type":"codeVoice","code":"PWInboxService"},{"type":"text","text":"."}],"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PushwooshInboxKitViewController","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PushwooshInboxKitViewController"}],"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxkitviewcontroller","title":"PushwooshInboxKitViewController"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxKitAttributes/style-swift.property":{"type":"topic","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxkitattributes\/style-swift.property","abstract":[{"text":"Visual styling for the controller and the default cell.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"style","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Style","kind":"typeIdentifier","preciseIdentifier":"s:17PushwooshInboxKit0abC10AttributesV5StyleV"}],"title":"style","role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitAttributes\/style-swift.property","kind":"symbol"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxKitAttributes/defaultTransform(pinningEnabled:)":{"type":"topic","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxkitattributes\/defaulttransform(pinningenabled:)","abstract":[{"text":"Default transform — pinned-first (when ","type":"text"},{"type":"codeVoice","code":"pinningEnabled"},{"type":"text","text":" is "},{"code":"true","type":"codeVoice"},{"type":"text","text":"),"},{"text":" ","type":"text"},{"text":"then unread-first, then recent-first. Override ","type":"text"},{"type":"codeVoice","code":"attributes.transform"},{"type":"text","text":" "},{"text":"to supply your own pipeline.","type":"text"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultTransform"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"pinningEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> (["},{"text":"PWInboxMessageProtocol","preciseIdentifier":"c:objc(pl)PWInboxMessageProtocol","kind":"typeIdentifier"},{"text":"]) -> [","kind":"text"},{"text":"PWInboxMessageProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)PWInboxMessageProtocol"},{"kind":"text","text":"]"}],"title":"defaultTransform(pinningEnabled:)","role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitAttributes\/defaultTransform(pinningEnabled:)","kind":"symbol"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxKitAttributes/forceCellKind":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitAttributes\/forceCellKind","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"forceCellKind","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CellKind","preciseIdentifier":"s:17PushwooshInboxKit0abC10AttributesV8CellKindO"},{"text":"?","kind":"text"}],"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxkitattributes\/forcecellkind","title":"forceCellKind","type":"topic","abstract":[{"type":"text","text":"When set, this value short-circuits the resolver — every message"},{"type":"text","text":" "},{"type":"text","text":"renders with this kind. Use it to force a uniform layout from code"},{"type":"text","text":" "},{"text":"without disabling the server-driven resolver entirely.","type":"text"}],"role":"symbol"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxCell":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCell","type":"topic","abstract":[{"type":"text","text":"Default inbox table-view cell. Subclass this type and register it under a"},{"type":"text","text":" "},{"text":"custom kind via ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitAttributes\/cells"},{"type":"text","text":" to ship bespoke"},{"text":" ","type":"text"},{"text":"layouts.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PushwooshInboxCell","kind":"identifier"}],"navigatorTitle":[{"text":"PushwooshInboxCell","kind":"identifier"}],"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxcell","title":"PushwooshInboxCell"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxKitAttributes/isPinned(_:)":{"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxkitattributes\/ispinned(_:)","abstract":[{"code":"true","type":"codeVoice"},{"type":"text","text":" if the message carries "},{"type":"codeVoice","code":"actionParams[\"pinned\"] == true"},{"type":"text","text":" at the"},{"type":"text","text":" "},{"text":"root, inside ","type":"text"},{"code":"u","type":"codeVoice"},{"type":"text","text":", or inside "},{"type":"codeVoice","code":"userdata"},{"text":". Tolerant to the same wire","type":"text"},{"type":"text","text":" "},{"text":"shapes as ","type":"text"},{"code":"readDisplayType(from:)","type":"codeVoice"},{"type":"text","text":"."}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitAttributes\/isPinned(_:)","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isPinned","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(pl)PWInboxMessageProtocol","kind":"typeIdentifier","text":"PWInboxMessageProtocol"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"title":"isPinned(_:)"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxKitAttributes/defaultCellKindResolver":{"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitAttributes\/defaultCellKindResolver","abstract":[{"text":"Default resolver — reads ","type":"text"},{"type":"codeVoice","code":"actionParams[\"displayType\"]"},{"type":"text","text":" first, falls back"},{"type":"text","text":" "},{"type":"text","text":"to imageUrl\/title heuristic. See "},{"isActive":true,"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitAttributes\/cellKindResolver","type":"reference"},{"type":"text","text":" for details."}],"kind":"symbol","title":"defaultCellKindResolver","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"defaultCellKindResolver"},{"text":": (","kind":"text"},{"text":"PWInboxMessageProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)PWInboxMessageProtocol"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxkitattributes\/defaultcellkindresolver"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxKitAttributes/cellKindResolver":{"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitAttributes\/cellKindResolver","abstract":[{"text":"Resolves a cell-kind identifier for a given message. The result must be","type":"text"},{"type":"text","text":" "},{"type":"text","text":"a key in "},{"code":"cells","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol","title":"cellKindResolver","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"cellKindResolver","kind":"identifier"},{"text":": (","kind":"text"},{"preciseIdentifier":"c:objc(pl)PWInboxMessageProtocol","kind":"typeIdentifier","text":"PWInboxMessageProtocol"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxkitattributes\/cellkindresolver"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxKitAttributes/swipeToDeleteEnabled":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitAttributes\/swipeToDeleteEnabled","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"swipeToDeleteEnabled","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxkitattributes\/swipetodeleteenabled","abstract":[{"text":"Swipe-to-delete trailing action on each row.","type":"text"}],"role":"symbol","type":"topic","title":"swipeToDeleteEnabled"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxKitAttributes":{"type":"topic","navigatorTitle":[{"text":"PushwooshInboxKitAttributes","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitAttributes","kind":"symbol","abstract":[{"text":"Configuration container for ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitViewController"},{"text":".","type":"text"}],"title":"PushwooshInboxKitAttributes","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"PushwooshInboxKitAttributes","kind":"identifier"}],"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxkitattributes"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxKitDelegate":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitDelegate","type":"topic","abstract":[{"type":"text","text":"Lifecycle and interaction callbacks for "},{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitViewController","type":"reference","isActive":true},{"text":".","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PushwooshInboxKitDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"PushwooshInboxKitDelegate","kind":"identifier"}],"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxkitdelegate","title":"PushwooshInboxKitDelegate"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxKitAttributes/CellKind":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitAttributes\/CellKind","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"CellKind","kind":"identifier"}],"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxkitattributes\/cellkind","navigatorTitle":[{"text":"CellKind","kind":"identifier"}],"title":"PushwooshInboxKitAttributes.CellKind","type":"topic","abstract":[{"type":"text","text":"Built-in cell kinds. Use these constants for type-safe code-driven"},{"type":"text","text":" "},{"text":"overrides via ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitAttributes\/forceCellKind","isActive":true},{"type":"text","text":" or directly in your "},{"type":"codeVoice","code":"cellKindResolver"},{"type":"text","text":"."}],"role":"symbol"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxKitAttributes/cells":{"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Mapping of cell-kind identifiers to cell classes."}],"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitAttributes\/cells","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cells","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"text":"PushwooshInboxCell","kind":"typeIdentifier","preciseIdentifier":"c:@M@PushwooshInboxKit@objc(cs)PushwooshInboxCell"},{"text":".Type]","kind":"text"}],"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxkitattributes\/cells","title":"cells"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxKitAttributes/pinningEnabled":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitAttributes\/pinningEnabled","kind":"symbol","type":"topic","title":"pinningEnabled","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxkitattributes\/pinningenabled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"pinningEnabled","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"role":"symbol","abstract":[{"type":"text","text":"When "},{"type":"codeVoice","code":"true"},{"type":"text","text":", messages whose "},{"code":"actionParams[\"pinned\"] == true","type":"codeVoice"},{"type":"text","text":" are"},{"type":"text","text":" "},{"type":"text","text":"floated to the top of the feed by the default transform. Disable to"},{"type":"text","text":" "},{"text":"fall back to the plain unread-first \/ recent-first ordering.","type":"text"}]},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit","title":"PushwooshInboxKit","type":"topic","url":"\/documentation\/pushwooshinboxkit","abstract":[{"text":"Modern UIKit inbox UI powered by Pushwoosh.","type":"text"}],"kind":"symbol","role":"collection"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxKitAttributes/enableDarkTheme":{"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxkitattributes\/enabledarktheme","abstract":[{"type":"text","text":"When "},{"type":"codeVoice","code":"true"},{"text":", dynamic colors resolve against the current trait collection.","type":"text"},{"type":"text","text":" "},{"text":"When ","type":"text"},{"type":"codeVoice","code":"false"},{"type":"text","text":", the controller and cells force light-mode color resolution."}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitAttributes\/enableDarkTheme","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"enableDarkTheme"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"title":"enableDarkTheme"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxKitAttributes/pullToRefreshEnabled":{"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxkitattributes\/pulltorefreshenabled","abstract":[{"text":"Pull-to-refresh control on the table view.","type":"text"}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitAttributes\/pullToRefreshEnabled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"pullToRefreshEnabled","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"title":"pullToRefreshEnabled"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxKitAttributes/errorMessage":{"role":"symbol","title":"errorMessage","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorMessage"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitAttributes\/errorMessage","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxkitattributes\/errormessage","kind":"symbol","abstract":[{"type":"text","text":"Error-state message rendered when the inbox load fails."}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxKitViewController\/title","value":"PushwooshInboxKitViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxKitViewController\/fragments","value":[{"kind":"identifier","text":"PushwooshInboxKitViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxCell\/title","value":"PushwooshInboxCell"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxCell\/fragments","op":"replace","value":[{"text":"PushwooshInboxCell","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}