{"metadata":{"modules":[{"name":"PushwooshInboxKit"}],"externalID":"c:@M@PushwooshInboxKit@objc(cs)PushwooshInboxCell","roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PushwooshInboxCell","kind":"identifier"}],"navigatorTitle":[{"text":"PushwooshInboxCell","kind":"identifier"}],"symbolKind":"class","title":"PushwooshInboxCell","role":"symbol"},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"abstract":[{"text":"Default inbox table-view cell. Subclass this type and register it under a","type":"text"},{"text":" ","type":"text"},{"text":"custom kind via ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitAttributes\/cells"},{"type":"text","text":" to ship bespoke"},{"text":" ","type":"text"},{"type":"text","text":"layouts."}],"kind":"symbol","topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCell\/init(coder:)","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCell\/init(style:reuseIdentifier:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCell\/bodyLabel","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCell\/buttonsStack","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCell\/dateLabel","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCell\/messageImageView","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCell\/onInlineButtonTap","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCell\/pinIndicatorView","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCell\/titleLabel","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCell\/unreadIndicatorView"]},{"identifiers":["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCell\/apply(message:attributes:)","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCell\/applyButtons(_:style:traits:)","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCell\/prepareForReuse()","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCell\/resetInheritedLayout()","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCell\/traitCollectionDidChange(_:)"],"title":"Instance Methods"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(PushwooshInboxCell) ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PushwooshInboxCell","kind":"identifier"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshinboxkit\/pushwooshinboxcell"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshinboxkit\/pushwooshinboxcell"]}],"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCell","interfaceLanguage":"swift"},"seeAlsoSections":[{"generated":true,"title":"Public Surface","identifiers":["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitViewController","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitAttributes","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitDelegate"]}],"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(cs)UITableViewCell"]},{"type":"inheritedBy","title":"Inherited By","identifiers":["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxBannerCell","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCaptionedCell","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxClassicCell"],"kind":"relationships"},{"identifiers":["doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)NSCoding","doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)NSObject","doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)CALayerDelegate","doc:\/\/com.pushwoosh.PushwooshInboxKit\/s7CVarArgP","doc:\/\/com.pushwoosh.PushwooshInboxKit\/s28CustomDebugStringConvertibleP","doc:\/\/com.pushwoosh.PushwooshInboxKit\/s23CustomStringConvertibleP","doc:\/\/com.pushwoosh.PushwooshInboxKit\/SQ","doc:\/\/com.pushwoosh.PushwooshInboxKit\/SH","doc:\/\/com.pushwoosh.PushwooshInboxKit\/s8SendableP","doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIAccessibilityIdentification","doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIAppearance","doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIAppearanceContainer","doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UICoordinateSpace","doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIDynamicItem","doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIFocusEnvironment","doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIFocusItem","doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIFocusItemContainer","doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIGestureRecognizerDelegate","doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UILargeContentViewerItem","doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.pushwoosh.PushwooshInboxKit\/5UIKit23UITraitChangeObservableP","doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UITraitEnvironment","doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIUserActivityRestoring"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit"]]},"references":{"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UICoordinateSpace"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxCell/pinIndicatorView":{"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"pinIndicatorView","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIImageView","kind":"typeIdentifier","text":"UIImageView"}],"type":"topic","title":"pinIndicatorView","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxcell\/pinindicatorview","abstract":[{"type":"text","text":"Small pin glyph rendered when the message carries"},{"type":"text","text":" "},{"code":"actionParams[\"pinned\"] == true","type":"codeVoice"},{"text":" and ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitAttributes\/pinningEnabled","isActive":true},{"type":"text","text":" "},{"type":"text","text":"is "},{"code":"true","type":"codeVoice"},{"type":"text","text":". Subclasses position it; the base class only owns the"},{"type":"text","text":" "},{"text":"instance.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCell\/pinIndicatorView","kind":"symbol"},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)UIFocusItemContainer":{"type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIFocusItemContainer","title":"UIKit.UIFocusItemContainer"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxCell/resetInheritedLayout()":{"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxcell\/resetinheritedlayout()","abstract":[{"type":"text","text":"Detaches every inherited subview from the contentView and removes the"},{"type":"text","text":" "},{"type":"text","text":"fixed-size self-constraints (width\/height) that were added by the"},{"text":" ","type":"text"},{"type":"text","text":"default layout in "},{"type":"codeVoice","code":"setupSubviews()"},{"type":"text","text":". Subclasses call this before"},{"type":"text","text":" "},{"type":"text","text":"installing their own chrome to avoid Auto Layout conflicts."}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCell\/resetInheritedLayout()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"resetInheritedLayout"},{"text":"()","kind":"text"}],"title":"resetInheritedLayout()","role":"symbol"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxCell":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushwooshInboxCell"}],"title":"PushwooshInboxCell","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PushwooshInboxCell"}],"kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCell","abstract":[{"type":"text","text":"Default inbox table-view cell. Subclass this type and register it under a"},{"text":" ","type":"text"},{"type":"text","text":"custom kind via "},{"type":"reference","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitAttributes\/cells","isActive":true},{"type":"text","text":" to ship bespoke"},{"text":" ","type":"text"},{"text":"layouts.","type":"text"}],"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxcell"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxKitAttributes/cells":{"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cells"},{"kind":"text","text":": ["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:@M@PushwooshInboxKit@objc(cs)PushwooshInboxCell","kind":"typeIdentifier","text":"PushwooshInboxCell"},{"text":".Type]","kind":"text"}],"title":"cells","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitAttributes\/cells","abstract":[{"type":"text","text":"Mapping of cell-kind identifiers to cell classes."}],"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxkitattributes\/cells"},"doc://com.pushwoosh.PushwooshInboxKit/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)UIActivityItemsConfigurationProviding":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIActivityItemsConfigurationProviding","type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding"},"doc://com.pushwoosh.PushwooshInboxKit/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxClassicCell":{"navigatorTitle":[{"text":"PushwooshInboxClassicCell","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxClassicCell","title":"PushwooshInboxClassicCell","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PushwooshInboxClassicCell","kind":"identifier"}],"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxclassiccell","role":"symbol"},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)UIPasteConfigurationSupporting":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIPasteConfigurationSupporting","type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting"},"doc://com.pushwoosh.PushwooshInboxKit/s8SendableP":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/s8SendableP","type":"unresolvable","title":"Swift.Sendable"},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)UILargeContentViewerItem":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UILargeContentViewerItem","type":"unresolvable","title":"UIKit.UILargeContentViewerItem"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxCell/bodyLabel":{"kind":"symbol","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxcell\/bodylabel","abstract":[],"title":"bodyLabel","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCell\/bodyLabel","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"bodyLabel","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UILabel","text":"UILabel"}]},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)UITraitEnvironment":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UITraitEnvironment","type":"unresolvable","title":"UIKit.UITraitEnvironment"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxCell/traitCollectionDidChange(_:)":{"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxcell\/traitcollectiondidchange(_:)","title":"traitCollectionDidChange(_:)","abstract":[],"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCell\/traitCollectionDidChange(_:)","navigatorTitle":[{"text":"traitCollectionDidChange:","kind":"identifier"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"traitCollectionDidChange"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITraitCollection","text":"UITraitCollection"},{"kind":"text","text":"?)"}],"kind":"symbol","type":"topic"},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)UIAppearance":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIAppearance","type":"unresolvable","title":"UIKit.UIAppearance"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxCell/apply(message:attributes:)":{"kind":"symbol","type":"topic","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxcell\/apply(message:attributes:)","abstract":[{"type":"text","text":"Configures the cell for the given message and attributes. Subclasses may"},{"type":"text","text":" "},{"text":"override to render bespoke layouts; call ","type":"text"},{"type":"codeVoice","code":"super.apply(...)"},{"type":"text","text":" to inherit"},{"type":"text","text":" "},{"type":"text","text":"dark-mode reactivity."}],"title":"apply(message:attributes:)","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCell\/apply(message:attributes:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"apply","kind":"identifier"},{"kind":"text","text":"("},{"text":"message","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PWInboxMessageProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)PWInboxMessageProtocol"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"attributes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:17PushwooshInboxKit0abC10AttributesV","text":"PushwooshInboxKitAttributes"},{"text":")","kind":"text"}]},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)UIGestureRecognizerDelegate":{"type":"unresolvable","title":"UIKit.UIGestureRecognizerDelegate","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIGestureRecognizerDelegate"},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIAppearanceContainer"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxCell/dateLabel":{"type":"topic","abstract":[],"title":"dateLabel","kind":"symbol","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxcell\/datelabel","role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCell\/dateLabel","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"dateLabel"},{"kind":"text","text":": "},{"text":"UILabel","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UILabel"}]},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIResponderStandardEditActions","title":"UIKit.UIResponderStandardEditActions"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxCell/messageImageView":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCell\/messageImageView","role":"symbol","abstract":[],"type":"topic","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"messageImageView"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIImageView","preciseIdentifier":"c:objc(cs)UIImageView"}],"title":"messageImageView","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxcell\/messageimageview"},"doc://com.pushwoosh.PushwooshInboxKit/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxBannerCell":{"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxbannercell","title":"PushwooshInboxBannerCell","abstract":[],"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxBannerCell","navigatorTitle":[{"kind":"identifier","text":"PushwooshInboxBannerCell"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PushwooshInboxBannerCell","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://com.pushwoosh.PushwooshInboxKit/objc(cs)UITableViewCell":{"type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(cs)UITableViewCell","title":"UITableViewCell"},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIUserActivityRestoring","title":"UIKit.UIUserActivityRestoring"},"doc://com.pushwoosh.PushwooshInboxKit/5UIKit23UITraitChangeObservableP":{"type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/5UIKit23UITraitChangeObservableP","title":"UIKit.UITraitChangeObservable"},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)UIFocusItem":{"type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIFocusItem","title":"UIKit.UIFocusItem"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxCell/onInlineButtonTap":{"kind":"symbol","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxcell\/oninlinebuttontap","abstract":[{"type":"text","text":"Captured tap handler for buttons rendered via "},{"type":"codeVoice","code":"applyButtons(...)"},{"type":"text","text":"."},{"type":"text","text":" "},{"text":"Subclasses call back into this when an inline CTA is tapped so the VC","type":"text"},{"text":" ","type":"text"},{"text":"can route to the delegate.","type":"text"}],"title":"onInlineButtonTap","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCell\/onInlineButtonTap","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"onInlineButtonTap","kind":"identifier"},{"kind":"text","text":": (("},{"preciseIdentifier":"s:17PushwooshInboxKit0aB6ButtonV","text":"PushwooshInboxButton","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?"}]},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIPopoverPresentationControllerSourceItem","title":"UIKit.UIPopoverPresentationControllerSourceItem"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxKitDelegate":{"kind":"symbol","abstract":[{"type":"text","text":"Lifecycle and interaction callbacks for "},{"isActive":true,"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitViewController","type":"reference"},{"type":"text","text":"."}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PushwooshInboxKitDelegate","kind":"identifier"}],"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxkitdelegate","title":"PushwooshInboxKitDelegate","navigatorTitle":[{"text":"PushwooshInboxKitDelegate","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitDelegate","type":"topic"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxCell/init(coder:)":{"kind":"symbol","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxcell\/init(coder:)","abstract":[],"title":"init(coder:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCell\/init(coder:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"text":")","kind":"text"}]},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxKitAttributes/pinningEnabled":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitAttributes\/pinningEnabled","role":"symbol","abstract":[{"type":"text","text":"When "},{"type":"codeVoice","code":"true"},{"text":", messages whose ","type":"text"},{"type":"codeVoice","code":"actionParams[\"pinned\"] == true"},{"text":" are","type":"text"},{"type":"text","text":" "},{"text":"floated to the top of the feed by the default transform. Disable to","type":"text"},{"type":"text","text":" "},{"type":"text","text":"fall back to the plain unread-first \/ recent-first ordering."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pinningEnabled"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"type":"topic","title":"pinningEnabled","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxkitattributes\/pinningenabled","kind":"symbol"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit","kind":"symbol","url":"\/documentation\/pushwooshinboxkit","title":"PushwooshInboxKit","role":"collection","abstract":[{"text":"Modern UIKit inbox UI powered by Pushwoosh.","type":"text"}],"type":"topic"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxCell/prepareForReuse()":{"kind":"symbol","type":"topic","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxcell\/prepareforreuse()","abstract":[],"title":"prepareForReuse()","navigatorTitle":[{"kind":"identifier","text":"prepareForReuse"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCell\/prepareForReuse()","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"prepareForReuse","kind":"identifier"},{"kind":"text","text":"()"}]},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxCell/titleLabel":{"type":"topic","abstract":[],"title":"titleLabel","kind":"symbol","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxcell\/titlelabel","role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCell\/titleLabel","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"titleLabel","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UILabel","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UILabel"}]},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)UIFocusEnvironment":{"type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIFocusEnvironment","title":"UIKit.UIFocusEnvironment"},"doc://com.pushwoosh.PushwooshInboxKit/SH":{"type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/SH","title":"Swift.Hashable"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxKitViewController":{"type":"topic","navigatorTitle":[{"text":"PushwooshInboxKitViewController","kind":"identifier"}],"abstract":[{"type":"text","text":"Modern UIKit inbox controller backed by "},{"code":"PWInboxService","type":"codeVoice"},{"text":".","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PushwooshInboxKitViewController","kind":"identifier"}],"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxkitviewcontroller","role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitViewController","title":"PushwooshInboxKitViewController"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxCaptionedCell":{"type":"topic","abstract":[],"title":"PushwooshInboxCaptionedCell","kind":"symbol","navigatorTitle":[{"text":"PushwooshInboxCaptionedCell","kind":"identifier"}],"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxcaptionedcell","role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCaptionedCell","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushwooshInboxCaptionedCell"}]},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxCell/init(style:reuseIdentifier:)":{"kind":"symbol","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxcell\/init(style:reuseidentifier:)","abstract":[],"title":"init(style:reuseIdentifier:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithStyle:reuseIdentifier:"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCell\/init(style:reuseIdentifier:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"style"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableViewCell","text":"UITableViewCell"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"CellStyle","preciseIdentifier":"c:@E@UITableViewCellStyle"},{"text":", ","kind":"text"},{"text":"reuseIdentifier","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}]},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)CALayerDelegate":{"title":"QuartzCore.CALayerDelegate","type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)CALayerDelegate"},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)NSObject":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxKitAttributes":{"type":"topic","navigatorTitle":[{"text":"PushwooshInboxKitAttributes","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration container for "},{"isActive":true,"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitViewController","type":"reference"},{"text":".","type":"text"}],"kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PushwooshInboxKitAttributes","kind":"identifier"}],"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxkitattributes","role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitAttributes","title":"PushwooshInboxKitAttributes"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxCell/buttonsStack":{"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxcell\/buttonsstack","title":"buttonsStack","abstract":[{"type":"text","text":"Horizontal stack that hosts inline CTA buttons ("},{"type":"codeVoice","code":"PushwooshInboxButton"},{"type":"text","text":")."},{"text":" ","type":"text"},{"text":"Subclasses are expected to add this view to their own card chrome —","type":"text"},{"type":"text","text":" "},{"type":"codeVoice","code":"applyButtons(_:style:onTap:)"},{"text":" populates it.","type":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCell\/buttonsStack","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"buttonsStack"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIStackView","text":"UIStackView","kind":"typeIdentifier"}],"kind":"symbol","type":"topic"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxCell/applyButtons(_:style:traits:)":{"kind":"symbol","type":"topic","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxcell\/applybuttons(_:style:traits:)","abstract":[{"text":"Renders an array of inline CTA buttons into ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCell\/buttonsStack"},{"text":" using the","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"supplied style. Empties the stack when "},{"type":"codeVoice","code":"buttons"},{"type":"text","text":" is empty. The cell’s"},{"type":"text","text":" "},{"code":"onInlineButtonTap","type":"codeVoice"},{"type":"text","text":" is invoked with the tapped button."}],"title":"applyButtons(_:style:traits:)","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCell\/applyButtons(_:style:traits:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"applyButtons"},{"text":"([","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:17PushwooshInboxKit0aB6ButtonV","text":"PushwooshInboxButton"},{"kind":"text","text":"], "},{"text":"style","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:17PushwooshInboxKit0abC10AttributesV","text":"PushwooshInboxKitAttributes"},{"text":".","kind":"text"},{"text":"Style","preciseIdentifier":"s:17PushwooshInboxKit0abC10AttributesV5StyleV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"traits"},{"text":": ","kind":"text"},{"text":"UITraitCollection","preciseIdentifier":"c:objc(cs)UITraitCollection","kind":"typeIdentifier"},{"text":"?)","kind":"text"}]},"doc://com.pushwoosh.PushwooshInboxKit/SQ":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)NSCoding":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)NSCoding","type":"unresolvable","title":"Foundation.NSCoding"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxCell/unreadIndicatorView":{"kind":"symbol","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxcell\/unreadindicatorview","abstract":[],"title":"unreadIndicatorView","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCell\/unreadIndicatorView","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unreadIndicatorView","kind":"identifier"},{"kind":"text","text":": "},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"}]},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)UIDynamicItem":{"title":"UIKit.UIDynamicItem","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIDynamicItem","type":"unresolvable"},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)UIAccessibilityIdentification":{"title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIAccessibilityIdentification","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"PushwooshInboxCell","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"PushwooshInboxCell","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"PushwooshInboxCell"}]},{"path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCell\/init(coder:)","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCell\/init(style:reuseIdentifier:)","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCell\/prepareForReuse()","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCell\/traitCollectionDidChange(_:)"]}],"op":"replace"},{"path":"\/relationshipsSections","op":"replace","value":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(cs)UITableViewCell"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"kind":"relationships","type":"inheritedBy","identifiers":["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxBannerCell","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCaptionedCell","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxClassicCell"],"title":"Inherited By"}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"generated":true,"title":"Public Surface","identifiers":["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitViewController"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PushwooshInboxCell"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableViewCell","text":"UITableViewCell"}]}]}},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxCell\/title","value":"PushwooshInboxCell","op":"replace"},{"value":[{"text":"PushwooshInboxCell","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxCell\/fragments"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxClassicCell\/title","value":"PushwooshInboxClassicCell","op":"replace"},{"value":[{"text":"PushwooshInboxClassicCell","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxClassicCell\/fragments"},{"op":"replace","value":"traitCollectionDidChange:","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxCell~1traitCollectionDidChange(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxCell~1traitCollectionDidChange(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"traitCollectionDidChange:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxBannerCell\/title","value":"PushwooshInboxBannerCell","op":"replace"},{"value":[{"text":"PushwooshInboxBannerCell","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxBannerCell\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxCell~1init(coder:)\/title","value":"initWithCoder:"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxCell~1init(coder:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"op":"replace"},{"op":"replace","value":"prepareForReuse","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxCell~1prepareForReuse()\/title"},{"value":[{"kind":"text","text":"- "},{"text":"prepareForReuse","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxCell~1prepareForReuse()\/fragments","op":"replace"},{"value":"PushwooshInboxKitViewController","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxKitViewController\/title"},{"value":[{"text":"PushwooshInboxKitViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxKitViewController\/fragments"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxCaptionedCell\/title","op":"replace","value":"PushwooshInboxCaptionedCell"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxCaptionedCell\/fragments","value":[{"text":"PushwooshInboxCaptionedCell","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxCell~1init(style:reuseIdentifier:)\/title","op":"replace","value":"initWithStyle:reuseIdentifier:"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxCell~1init(style:reuseIdentifier:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithStyle:reuseIdentifier:"}],"op":"replace"}]}]}