{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshinboxkit\/pushwooshinboxvideocell"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshinboxkit\/pushwooshinboxvideocell"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(PushwooshInboxVideoCell) ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PushwooshInboxVideoCell"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"title":"PushwooshInboxVideoCell","symbolKind":"class","roleHeading":"Class","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PushwooshInboxVideoCell"}],"modules":[{"name":"PushwooshInboxKit"}],"externalID":"c:@M@PushwooshInboxKit@objc(cs)PushwooshInboxVideoCell","navigatorTitle":[{"text":"PushwooshInboxVideoCell","kind":"identifier"}]},"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxVideoCell","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"topicSections":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxVideoCell\/init(coder:)","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxVideoCell\/init(style:reuseIdentifier:)"],"title":"Initializers"},{"identifiers":["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxVideoCell\/onVideoTap"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxVideoCell\/apply(message:attributes:)","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxVideoCell\/prepareForReuse()","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxVideoCell\/setHighlighted(_:animated:)"]}],"seeAlsoSections":[{"title":"Rich Cards","generated":true,"identifiers":["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxBannerCell","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCaptionedCell","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxClassicCell","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCarouselCell","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxWalletCell","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCarouselSlide","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxVideoContent","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxWalletPass"]}],"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCell"],"type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)NSCoding","doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)NSObject","doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)CALayerDelegate","doc:\/\/com.pushwoosh.PushwooshInboxKit\/s7CVarArgP","doc:\/\/com.pushwoosh.PushwooshInboxKit\/s28CustomDebugStringConvertibleP","doc:\/\/com.pushwoosh.PushwooshInboxKit\/s23CustomStringConvertibleP","doc:\/\/com.pushwoosh.PushwooshInboxKit\/SQ","doc:\/\/com.pushwoosh.PushwooshInboxKit\/SH","doc:\/\/com.pushwoosh.PushwooshInboxKit\/s8SendableP","doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIAccessibilityIdentification","doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIAppearance","doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIAppearanceContainer","doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UICoordinateSpace","doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIDynamicItem","doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIFocusEnvironment","doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIFocusItem","doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIFocusItemContainer","doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIGestureRecognizerDelegate","doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UILargeContentViewerItem","doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.pushwoosh.PushwooshInboxKit\/5UIKit23UITraitChangeObservableP","doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UITraitEnvironment","doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIUserActivityRestoring"]}],"references":{"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxVideoCell/apply(message:attributes:)":{"abstract":[{"type":"text","text":"Configures the cell for the given message and attributes. Subclasses may"},{"text":" ","type":"text"},{"text":"override to render bespoke layouts; call ","type":"text"},{"code":"super.apply(...)","type":"codeVoice"},{"type":"text","text":" to inherit"},{"text":" ","type":"text"},{"text":"dark-mode reactivity.","type":"text"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxVideoCell\/apply(message:attributes:)","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxvideocell\/apply(message:attributes:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"apply"},{"kind":"text","text":"("},{"text":"message","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PWInboxMessageProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)PWInboxMessageProtocol"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"attributes"},{"text":": ","kind":"text"},{"text":"PushwooshInboxKitAttributes","preciseIdentifier":"s:17PushwooshInboxKit0abC10AttributesV","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"apply(message:attributes:)"},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)UITraitEnvironment":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UITraitEnvironment","title":"UIKit.UITraitEnvironment","type":"unresolvable"},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)UIFocusItemContainer":{"title":"UIKit.UIFocusItemContainer","type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIFocusItemContainer"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxVideoCell/setHighlighted(_:animated:)":{"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxvideocell\/sethighlighted(_:animated:)","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxVideoCell\/setHighlighted(_:animated:)","title":"setHighlighted(_:animated:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setHighlighted"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"animated"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Subtle press feedback for taps that land on the card chrome (text block, margins)."}],"navigatorTitle":[{"kind":"identifier","text":"setHighlighted:animated:"}],"kind":"symbol","type":"topic"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit":{"kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit","title":"PushwooshInboxKit","url":"\/documentation\/pushwooshinboxkit","role":"collection","abstract":[{"text":"Modern UIKit inbox UI powered by Pushwoosh.","type":"text"}],"type":"topic"},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)UIUserActivityRestoring":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIUserActivityRestoring","title":"UIKit.UIUserActivityRestoring","type":"unresolvable"},"doc://com.pushwoosh.PushwooshInboxKit/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxCaptionedCell":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PushwooshInboxCaptionedCell"}],"role":"symbol","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCaptionedCell","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxcaptionedcell","navigatorTitle":[{"kind":"identifier","text":"PushwooshInboxCaptionedCell"}],"title":"PushwooshInboxCaptionedCell","type":"topic"},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)UIDynamicItem":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIDynamicItem","title":"UIKit.UIDynamicItem","type":"unresolvable"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxVideoContent":{"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxvideocontent","navigatorTitle":[{"text":"PushwooshInboxVideoContent","kind":"identifier"}],"abstract":[{"text":"Video payload for a ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxVideoCell","isActive":true},{"type":"text","text":"."}],"title":"PushwooshInboxVideoContent","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxVideoContent","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushwooshInboxVideoContent"}]},"doc://com.pushwoosh.PushwooshInboxKit/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)UIResponderStandardEditActions":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIResponderStandardEditActions","title":"UIKit.UIResponderStandardEditActions","type":"unresolvable"},"doc://com.pushwoosh.PushwooshInboxKit/s8SendableP":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/s8SendableP","title":"Swift.Sendable","type":"unresolvable"},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)UIActivityItemsConfigurationProviding":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIActivityItemsConfigurationProviding","title":"UIKit.UIActivityItemsConfigurationProviding","type":"unresolvable"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxWalletPass":{"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxwalletpass","navigatorTitle":[{"text":"PushwooshInboxWalletPass","kind":"identifier"}],"abstract":[{"text":"Apple Wallet pass descriptor for a ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxWalletCell"},{"text":".","type":"text"}],"title":"PushwooshInboxWalletPass","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxWalletPass","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"PushwooshInboxWalletPass","kind":"identifier"}]},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)NSCoding":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)NSCoding","title":"Foundation.NSCoding","type":"unresolvable"},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)UIAppearanceContainer":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIAppearanceContainer","title":"UIKit.UIAppearanceContainer","type":"unresolvable"},"doc://com.pushwoosh.PushwooshInboxKit/SH":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxKitAttributes/cells":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitAttributes\/cells","title":"cells","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxkitattributes\/cells","type":"topic","abstract":[{"type":"text","text":"Mapping of cell-kind identifiers to cell classes."}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cells","kind":"identifier"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:@M@PushwooshInboxKit@objc(cs)PushwooshInboxCell","kind":"typeIdentifier","text":"PushwooshInboxCell"},{"text":".Type]","kind":"text"}],"kind":"symbol"},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)UIAppearance":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIAppearance","title":"UIKit.UIAppearance","type":"unresolvable"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxClassicCell":{"title":"PushwooshInboxClassicCell","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushwooshInboxClassicCell"}],"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxclassiccell","navigatorTitle":[{"text":"PushwooshInboxClassicCell","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxClassicCell","abstract":[]},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)CALayerDelegate":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)CALayerDelegate","title":"QuartzCore.CALayerDelegate","type":"unresolvable"},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)UIFocusItem":{"title":"UIKit.UIFocusItem","type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIFocusItem"},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)UIAccessibilityIdentification":{"title":"UIKit.UIAccessibilityIdentification","type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIAccessibilityIdentification"},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)UIPasteConfigurationSupporting":{"title":"UIKit.UIPasteConfigurationSupporting","type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)UIPopoverPresentationControllerSourceItem":{"title":"UIKit.UIPopoverPresentationControllerSourceItem","type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxVideoCell/init(coder:)":{"title":"init(coder:)","type":"topic","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxvideocell\/init(coder:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"text":"coder","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSCoder","kind":"typeIdentifier","text":"NSCoder"},{"text":")","kind":"text"}],"role":"symbol","abstract":[],"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxVideoCell\/init(coder:)","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"kind":"symbol"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxCarouselCell":{"role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCarouselCell","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PushwooshInboxCarouselCell","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PushwooshInboxCarouselCell"}],"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxcarouselcell","abstract":[],"title":"PushwooshInboxCarouselCell","type":"topic","kind":"symbol"},"doc://com.pushwoosh.PushwooshInboxKit/5UIKit23UITraitChangeObservableP":{"title":"UIKit.UITraitChangeObservable","type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/5UIKit23UITraitChangeObservableP"},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)UILargeContentViewerItem":{"title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UILargeContentViewerItem","type":"unresolvable"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxBannerCell":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PushwooshInboxBannerCell","kind":"identifier"}],"title":"PushwooshInboxBannerCell","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxbannercell","type":"topic","navigatorTitle":[{"text":"PushwooshInboxBannerCell","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxBannerCell","kind":"symbol"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxVideoCell/init(style:reuseIdentifier:)":{"abstract":[],"role":"symbol","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxVideoCell\/init(style:reuseIdentifier:)","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxvideocell\/init(style:reuseidentifier:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithStyle:reuseIdentifier:"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"style"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UITableViewCell","text":"UITableViewCell","kind":"typeIdentifier"},{"kind":"text","text":"."},{"text":"CellStyle","preciseIdentifier":"c:@E@UITableViewCellStyle","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"reuseIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?)","kind":"text"}],"title":"init(style:reuseIdentifier:)"},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)UIFocusEnvironment":{"title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIFocusEnvironment","type":"unresolvable"},"doc://com.pushwoosh.PushwooshInboxKit/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/s7CVarArgP","type":"unresolvable"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxVideoCell/prepareForReuse()":{"abstract":[],"role":"symbol","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxVideoCell\/prepareForReuse()","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxvideocell\/prepareforreuse()","kind":"symbol","navigatorTitle":[{"text":"prepareForReuse","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"prepareForReuse"},{"text":"()","kind":"text"}],"title":"prepareForReuse()"},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)NSObject","type":"unresolvable"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxWalletCell":{"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxwalletcell","role":"symbol","abstract":[],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PushwooshInboxWalletCell","kind":"identifier"}],"title":"PushwooshInboxWalletCell","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxWalletCell","navigatorTitle":[{"text":"PushwooshInboxWalletCell","kind":"identifier"}],"type":"topic"},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)UICoordinateSpace":{"title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UICoordinateSpace","type":"unresolvable"},"doc://com.pushwoosh.PushwooshInboxKit/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/SQ","type":"unresolvable"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxVideoCell":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PushwooshInboxVideoCell","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxVideoCell","type":"topic","kind":"symbol","title":"PushwooshInboxVideoCell","role":"symbol","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxvideocell","navigatorTitle":[{"text":"PushwooshInboxVideoCell","kind":"identifier"}],"abstract":[]},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxVideoCell/onVideoTap":{"abstract":[{"text":"Invoked when the video preview is tapped. The controller opens a full-screen player.","type":"text"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxVideoCell\/onVideoTap","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxvideocell\/onvideotap","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"onVideoTap","kind":"identifier"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"title":"onVideoTap"},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)UIGestureRecognizerDelegate":{"title":"UIKit.UIGestureRecognizerDelegate","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIGestureRecognizerDelegate","type":"unresolvable"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxCarouselSlide":{"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxcarouselslide","navigatorTitle":[{"text":"PushwooshInboxCarouselSlide","kind":"identifier"}],"abstract":[{"text":"A single slide inside a ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCarouselCell","isActive":true},{"type":"text","text":"."}],"title":"PushwooshInboxCarouselSlide","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCarouselSlide","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushwooshInboxCarouselSlide"}]},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxCell":{"navigatorTitle":[{"kind":"identifier","text":"PushwooshInboxCell"}],"title":"PushwooshInboxCell","abstract":[{"text":"Default inbox table-view cell. Subclass this type and register it under a","type":"text"},{"text":" ","type":"text"},{"text":"custom kind via ","type":"text"},{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitAttributes\/cells","isActive":true,"type":"reference"},{"text":" to ship bespoke","type":"text"},{"text":" ","type":"text"},{"text":"layouts.","type":"text"}],"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxcell","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCell","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PushwooshInboxCell"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"PushwooshInboxVideoCell"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"PushwooshInboxVideoCell"}],"path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"PushwooshInboxVideoCell","kind":"identifier"}],"op":"replace"},{"value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxVideoCell\/init(coder:)","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxVideoCell\/init(style:reuseIdentifier:)","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxVideoCell\/prepareForReuse()","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxVideoCell\/setHighlighted(_:animated:)"]}],"op":"replace","path":"\/topicSections"},{"op":"replace","value":[{"title":"Inherits From","identifiers":["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCell"],"kind":"relationships","type":"inheritsFrom"}],"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":[{"generated":true,"title":"Rich Cards","identifiers":["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxBannerCell","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCaptionedCell","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxClassicCell","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCarouselCell","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxWalletCell"]}],"op":"replace"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PushwooshInboxVideoCell"},{"text":" : ","kind":"text"},{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCell","preciseIdentifier":"c:@M@PushwooshInboxKit@objc(cs)PushwooshInboxCell","kind":"typeIdentifier","text":"PushwooshInboxCell"}]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxVideoCell~1setHighlighted(_:animated:)\/title","value":"setHighlighted:animated:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxVideoCell~1setHighlighted(_:animated:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setHighlighted:animated:"}]},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxCaptionedCell\/title","op":"replace","value":"PushwooshInboxCaptionedCell"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxCaptionedCell\/fragments","value":[{"text":"PushwooshInboxCaptionedCell","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxClassicCell\/title","value":"PushwooshInboxClassicCell"},{"op":"replace","value":[{"text":"PushwooshInboxClassicCell","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxClassicCell\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxVideoCell~1init(coder:)\/title","value":"initWithCoder:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"initWithCoder:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxVideoCell~1init(coder:)\/fragments"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxCarouselCell\/title","op":"replace","value":"PushwooshInboxCarouselCell"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxCarouselCell\/fragments","op":"replace","value":[{"text":"PushwooshInboxCarouselCell","kind":"identifier"}]},{"value":"PushwooshInboxBannerCell","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxBannerCell\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxBannerCell\/fragments","value":[{"text":"PushwooshInboxBannerCell","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxVideoCell~1init(style:reuseIdentifier:)\/title","value":"initWithStyle:reuseIdentifier:"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxVideoCell~1init(style:reuseIdentifier:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithStyle:reuseIdentifier:"}]},{"value":"prepareForReuse","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxVideoCell~1prepareForReuse()\/title"},{"value":[{"kind":"text","text":"- "},{"text":"prepareForReuse","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxVideoCell~1prepareForReuse()\/fragments"},{"value":"PushwooshInboxWalletCell","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxWalletCell\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxWalletCell\/fragments","value":[{"text":"PushwooshInboxWalletCell","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxVideoCell\/title","value":"PushwooshInboxVideoCell","op":"replace"},{"value":[{"kind":"identifier","text":"PushwooshInboxVideoCell"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxVideoCell\/fragments"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxCell\/title","op":"replace","value":"PushwooshInboxCell"},{"op":"replace","value":[{"text":"PushwooshInboxCell","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxCell\/fragments"}]}]}