{"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCarouselCell","interfaceLanguage":"swift"},"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCell"]},{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)NSCoding","doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)NSObject","doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)CALayerDelegate","doc:\/\/com.pushwoosh.PushwooshInboxKit\/s7CVarArgP","doc:\/\/com.pushwoosh.PushwooshInboxKit\/s28CustomDebugStringConvertibleP","doc:\/\/com.pushwoosh.PushwooshInboxKit\/s23CustomStringConvertibleP","doc:\/\/com.pushwoosh.PushwooshInboxKit\/SQ","doc:\/\/com.pushwoosh.PushwooshInboxKit\/SH","doc:\/\/com.pushwoosh.PushwooshInboxKit\/s8SendableP","doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIAccessibilityIdentification","doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIAppearance","doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIAppearanceContainer","doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UICollectionViewDataSource","doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UICollectionViewDelegate","doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UICoordinateSpace","doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIDynamicItem","doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIFocusEnvironment","doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIFocusItem","doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIFocusItemContainer","doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIGestureRecognizerDelegate","doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UILargeContentViewerItem","doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIScrollViewDelegate","doc:\/\/com.pushwoosh.PushwooshInboxKit\/5UIKit23UITraitChangeObservableP","doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UITraitEnvironment","doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIUserActivityRestoring"],"kind":"relationships"}],"metadata":{"externalID":"c:@M@PushwooshInboxKit@objc(cs)PushwooshInboxCarouselCell","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushwooshInboxCarouselCell"}],"symbolKind":"class","navigatorTitle":[{"kind":"identifier","text":"PushwooshInboxCarouselCell"}],"roleHeading":"Class","title":"PushwooshInboxCarouselCell","role":"symbol","modules":[{"name":"PushwooshInboxKit"}]},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit"]]},"sections":[],"variants":[{"paths":["\/documentation\/pushwooshinboxkit\/pushwooshinboxcarouselcell"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshinboxkit\/pushwooshinboxcarouselcell"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(PushwooshInboxCarouselCell) "},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PushwooshInboxCarouselCell","kind":"identifier"}],"platforms":["iOS"]}]}],"seeAlsoSections":[{"title":"Rich Cards","generated":true,"identifiers":["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxBannerCell","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCaptionedCell","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxClassicCell","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxVideoCell","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxWalletCell","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCarouselSlide","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxVideoContent","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxWalletPass"]}],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCarouselCell\/init(coder:)","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCarouselCell\/init(style:reuseIdentifier:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCarouselCell\/onCarouselSlideTap"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCarouselCell\/apply(message:attributes:)","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCarouselCell\/prepareForReuse()","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCarouselCell\/setHighlighted(_:animated:)"]},{"identifiers":["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCarouselCell\/UICollectionViewDataSource-Implementations","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCarouselCell\/UICollectionViewDelegate-Implementations","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCarouselCell\/UIScrollViewDelegate-Implementations"],"title":"Default Implementations","generated":true}],"references":{"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxCell":{"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxcell","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCell","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PushwooshInboxCell","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PushwooshInboxCell"}],"role":"symbol","abstract":[{"type":"text","text":"Default inbox table-view cell. Subclass this type and register it under a"},{"text":" ","type":"text"},{"type":"text","text":"custom kind via "},{"type":"reference","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitAttributes\/cells","isActive":true},{"text":" to ship bespoke","type":"text"},{"type":"text","text":" "},{"text":"layouts.","type":"text"}],"kind":"symbol","title":"PushwooshInboxCell","type":"topic"},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)UIFocusItem":{"type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIFocusItem","title":"UIKit.UIFocusItem"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxWalletPass":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"PushwooshInboxWalletPass","kind":"identifier"}],"navigatorTitle":[{"text":"PushwooshInboxWalletPass","kind":"identifier"}],"abstract":[{"type":"text","text":"Apple Wallet pass descriptor for a "},{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxWalletCell","type":"reference","isActive":true},{"type":"text","text":"."}],"title":"PushwooshInboxWalletPass","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxWalletPass","kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxwalletpass"},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)UIFocusItemContainer":{"type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIFocusItemContainer","title":"UIKit.UIFocusItemContainer"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxVideoContent":{"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PushwooshInboxVideoContent"}],"navigatorTitle":[{"kind":"identifier","text":"PushwooshInboxVideoContent"}],"abstract":[{"type":"text","text":"Video payload for a "},{"type":"reference","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxVideoCell","isActive":true},{"type":"text","text":"."}],"title":"PushwooshInboxVideoContent","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxVideoContent","kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxvideocontent"},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)UICollectionViewDelegate":{"type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UICollectionViewDelegate","title":"UICollectionViewDelegate"},"doc://com.pushwoosh.PushwooshInboxKit/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxCarouselCell/onCarouselSlideTap":{"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxcarouselcell\/oncarouselslidetap","abstract":[{"text":"Invoked when a slide is tapped, carrying the slide’s optional ","type":"text"},{"type":"codeVoice","code":"url"},{"text":". The","type":"text"},{"type":"text","text":" "},{"type":"text","text":"controller opens the URL (and marks read) when present, otherwise falls through"},{"text":" ","type":"text"},{"type":"text","text":"to the message’s default row action."}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"onCarouselSlideTap","kind":"identifier"},{"text":": ((","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")?","kind":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCarouselCell\/onCarouselSlideTap","kind":"symbol","type":"topic","title":"onCarouselSlideTap"},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)UIAppearance":{"type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIAppearance","title":"UIKit.UIAppearance"},"doc://com.pushwoosh.PushwooshInboxKit/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/SQ","title":"Swift.Equatable"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxCaptionedCell":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PushwooshInboxCaptionedCell","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PushwooshInboxCaptionedCell"}],"abstract":[],"title":"PushwooshInboxCaptionedCell","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCaptionedCell","kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxcaptionedcell"},"doc://com.pushwoosh.PushwooshInboxKit/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxCarouselCell/init(coder:)":{"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxcarouselcell\/init(coder:)","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCarouselCell\/init(coder:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"abstract":[],"role":"symbol","title":"init(coder:)"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxCarouselCell/UICollectionViewDataSource-Implementations":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCarouselCell\/UICollectionViewDataSource-Implementations","role":"collectionGroup","title":"UICollectionViewDataSource Implementations","kind":"article","type":"topic","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxcarouselcell\/uicollectionviewdatasource-implementations","abstract":[]},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UILargeContentViewerItem","title":"UIKit.UILargeContentViewerItem"},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)UICoordinateSpace":{"type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UICoordinateSpace","title":"UIKit.UICoordinateSpace"},"doc://com.pushwoosh.PushwooshInboxKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxClassicCell":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushwooshInboxClassicCell"}],"navigatorTitle":[{"kind":"identifier","text":"PushwooshInboxClassicCell"}],"abstract":[],"title":"PushwooshInboxClassicCell","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxClassicCell","kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxclassiccell"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxVideoCell":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PushwooshInboxVideoCell","kind":"identifier"}],"navigatorTitle":[{"text":"PushwooshInboxVideoCell","kind":"identifier"}],"abstract":[],"title":"PushwooshInboxVideoCell","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxVideoCell","kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxvideocell"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxCarouselSlide":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCarouselSlide","kind":"symbol","abstract":[{"type":"text","text":"A single slide inside a "},{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCarouselCell","type":"reference","isActive":true},{"type":"text","text":"."}],"role":"symbol","title":"PushwooshInboxCarouselSlide","navigatorTitle":[{"text":"PushwooshInboxCarouselSlide","kind":"identifier"}],"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxcarouselslide","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PushwooshInboxCarouselSlide"}],"type":"topic"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxCarouselCell/prepareForReuse()":{"role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCarouselCell\/prepareForReuse()","title":"prepareForReuse()","navigatorTitle":[{"kind":"identifier","text":"prepareForReuse"}],"abstract":[],"type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"prepareForReuse"},{"text":"()","kind":"text"}],"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxcarouselcell\/prepareforreuse()"},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)UITraitEnvironment":{"type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UITraitEnvironment","title":"UIKit.UITraitEnvironment"},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIActivityItemsConfigurationProviding","title":"UIKit.UIActivityItemsConfigurationProviding"},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)UIGestureRecognizerDelegate":{"type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIGestureRecognizerDelegate","title":"UIKit.UIGestureRecognizerDelegate"},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIResponderStandardEditActions","title":"UIKit.UIResponderStandardEditActions"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxBannerCell":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushwooshInboxBannerCell"}],"navigatorTitle":[{"kind":"identifier","text":"PushwooshInboxBannerCell"}],"abstract":[],"title":"PushwooshInboxBannerCell","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxBannerCell","kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxbannercell"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxCarouselCell/apply(message:attributes:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"apply","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"text":": ","kind":"text"},{"text":"PWInboxMessageProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)PWInboxMessageProtocol"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"attributes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PushwooshInboxKitAttributes","preciseIdentifier":"s:17PushwooshInboxKit0abC10AttributesV"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Configures the cell for the given message and attributes. Subclasses may"},{"text":" ","type":"text"},{"type":"text","text":"override to render bespoke layouts; call "},{"type":"codeVoice","code":"super.apply(...)"},{"text":" to inherit","type":"text"},{"text":" ","type":"text"},{"text":"dark-mode reactivity.","type":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCarouselCell\/apply(message:attributes:)","title":"apply(message:attributes:)","type":"topic","kind":"symbol","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxcarouselcell\/apply(message:attributes:)"},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)UIPopoverPresentationControllerSourceItem":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIPopoverPresentationControllerSourceItem","title":"UIKit.UIPopoverPresentationControllerSourceItem","type":"unresolvable"},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)UIPasteConfigurationSupporting":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIPasteConfigurationSupporting","title":"UIKit.UIPasteConfigurationSupporting","type":"unresolvable"},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)UICollectionViewDataSource":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UICollectionViewDataSource","title":"UICollectionViewDataSource","type":"unresolvable"},"doc://com.pushwoosh.PushwooshInboxKit/5UIKit23UITraitChangeObservableP":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/5UIKit23UITraitChangeObservableP","title":"UIKit.UITraitChangeObservable","type":"unresolvable"},"doc://com.pushwoosh.PushwooshInboxKit/s8SendableP":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/s8SendableP","title":"Swift.Sendable","type":"unresolvable"},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)UIAppearanceContainer":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIAppearanceContainer","title":"UIKit.UIAppearanceContainer","type":"unresolvable"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxCarouselCell/UIScrollViewDelegate-Implementations":{"kind":"article","abstract":[],"role":"collectionGroup","title":"UIScrollViewDelegate Implementations","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCarouselCell\/UIScrollViewDelegate-Implementations","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxcarouselcell\/uiscrollviewdelegate-implementations"},"doc://com.pushwoosh.PushwooshInboxKit/SH":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxKitAttributes/cells":{"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxkitattributes\/cells","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitAttributes\/cells","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cells"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"PushwooshInboxCell","preciseIdentifier":"c:@M@PushwooshInboxKit@objc(cs)PushwooshInboxCell"},{"text":".Type]","kind":"text"}],"role":"symbol","abstract":[{"type":"text","text":"Mapping of cell-kind identifiers to cell classes."}],"title":"cells","type":"topic","kind":"symbol"},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)UIAccessibilityIdentification":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIAccessibilityIdentification","title":"UIKit.UIAccessibilityIdentification","type":"unresolvable"},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)UIDynamicItem":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIDynamicItem","title":"UIKit.UIDynamicItem","type":"unresolvable"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxCarouselCell/UICollectionViewDelegate-Implementations":{"kind":"article","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCarouselCell\/UICollectionViewDelegate-Implementations","type":"topic","role":"collectionGroup","abstract":[],"title":"UICollectionViewDelegate Implementations","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxcarouselcell\/uicollectionviewdelegate-implementations"},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)UIUserActivityRestoring":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIUserActivityRestoring","title":"UIKit.UIUserActivityRestoring","type":"unresolvable"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxCarouselCell":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"PushwooshInboxCarouselCell","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCarouselCell","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PushwooshInboxCarouselCell"}],"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxcarouselcell","type":"topic","abstract":[],"title":"PushwooshInboxCarouselCell"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxCarouselCell/setHighlighted(_:animated:)":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setHighlighted","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"animated","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}],"abstract":[{"text":"Subtle press feedback for taps that land on the card chrome (text block, margins).","type":"text"}],"navigatorTitle":[{"text":"setHighlighted:animated:","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCarouselCell\/setHighlighted(_:animated:)","title":"setHighlighted(_:animated:)","type":"topic","kind":"symbol","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxcarouselcell\/sethighlighted(_:animated:)"},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)NSCoding":{"type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)NSCoding","title":"Foundation.NSCoding"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxCarouselCell/init(style:reuseIdentifier:)":{"type":"topic","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"style","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UITableViewCell","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableViewCell"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"CellStyle","preciseIdentifier":"c:@E@UITableViewCellStyle"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"reuseIdentifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?)","kind":"text"}],"title":"init(style:reuseIdentifier:)","role":"symbol","abstract":[],"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxcarouselcell\/init(style:reuseidentifier:)","navigatorTitle":[{"kind":"identifier","text":"initWithStyle:reuseIdentifier:"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCarouselCell\/init(style:reuseIdentifier:)"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit":{"kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit","role":"collection","type":"topic","url":"\/documentation\/pushwooshinboxkit","title":"PushwooshInboxKit","abstract":[{"type":"text","text":"Modern UIKit inbox UI powered by Pushwoosh."}]},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)UIScrollViewDelegate":{"type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIScrollViewDelegate","title":"UIKit.UIScrollViewDelegate"},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)CALayerDelegate":{"type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)CALayerDelegate","title":"QuartzCore.CALayerDelegate"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxWalletCell":{"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxwalletcell","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxWalletCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PushwooshInboxWalletCell","kind":"identifier"}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PushwooshInboxWalletCell"}],"abstract":[],"role":"symbol","title":"PushwooshInboxWalletCell"},"doc://com.pushwoosh.PushwooshInboxKit/objc(pl)UIFocusEnvironment":{"type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UIFocusEnvironment","title":"UIKit.UIFocusEnvironment"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"PushwooshInboxCarouselCell","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"PushwooshInboxCarouselCell","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"PushwooshInboxCarouselCell","kind":"identifier"}]},{"path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCarouselCell\/init(coder:)","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCarouselCell\/init(style:reuseIdentifier:)","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCarouselCell\/prepareForReuse()","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCarouselCell\/setHighlighted(_:animated:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCarouselCell\/UICollectionViewDataSource-Implementations","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCarouselCell\/UICollectionViewDelegate-Implementations","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCarouselCell\/UIScrollViewDelegate-Implementations"],"generated":true}],"op":"replace"},{"value":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCell"]},{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UICollectionViewDataSource","doc:\/\/com.pushwoosh.PushwooshInboxKit\/objc(pl)UICollectionViewDelegate"]}],"op":"replace","path":"\/relationshipsSections"},{"op":"replace","value":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxBannerCell","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCaptionedCell","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxClassicCell","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxVideoCell","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxWalletCell"],"title":"Rich Cards","generated":true}],"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"PushwooshInboxCarouselCell","kind":"identifier"},{"kind":"text","text":" : "},{"text":"PushwooshInboxCell","preciseIdentifier":"c:@M@PushwooshInboxKit@objc(cs)PushwooshInboxCell","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCell","kind":"typeIdentifier"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxCell\/title","value":"PushwooshInboxCell"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxCell\/fragments","op":"replace","value":[{"text":"PushwooshInboxCell","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxCaptionedCell\/title","value":"PushwooshInboxCaptionedCell"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxCaptionedCell\/fragments","value":[{"text":"PushwooshInboxCaptionedCell","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxCarouselCell~1init(coder:)\/title","value":"initWithCoder:","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithCoder:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxCarouselCell~1init(coder:)\/fragments"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxClassicCell\/title","op":"replace","value":"PushwooshInboxClassicCell"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxClassicCell\/fragments","value":[{"text":"PushwooshInboxClassicCell","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxVideoCell\/title","value":"PushwooshInboxVideoCell"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxVideoCell\/fragments","op":"replace","value":[{"text":"PushwooshInboxVideoCell","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxCarouselCell~1prepareForReuse()\/title","value":"prepareForReuse","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxCarouselCell~1prepareForReuse()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"prepareForReuse","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxBannerCell\/title","value":"PushwooshInboxBannerCell"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxBannerCell\/fragments","value":[{"text":"PushwooshInboxBannerCell","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxCarouselCell\/title","value":"PushwooshInboxCarouselCell"},{"value":[{"text":"PushwooshInboxCarouselCell","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxCarouselCell\/fragments"},{"value":"setHighlighted:animated:","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxCarouselCell~1setHighlighted(_:animated:)\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxCarouselCell~1setHighlighted(_:animated:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"setHighlighted:animated:","kind":"identifier"}],"op":"replace"},{"value":"initWithStyle:reuseIdentifier:","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxCarouselCell~1init(style:reuseIdentifier:)\/title","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithStyle:reuseIdentifier:"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxCarouselCell~1init(style:reuseIdentifier:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxWalletCell\/title","value":"PushwooshInboxWalletCell"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxWalletCell\/fragments","value":[{"text":"PushwooshInboxWalletCell","kind":"identifier"}],"op":"replace"}]}]}