{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["tvOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"handleTvPushToken"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"deviceToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"deviceToken","content":[{"type":"paragraph","inlineContent":[{"text":"The device token data received from APNs.","type":"text"}]}]}]},{"content":[{"anchor":"discussion","text":"Discussion","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Call this method from "},{"code":"application(_:didRegisterForRemoteNotificationsWithDeviceToken:)","type":"codeVoice"},{"text":" ","type":"text"},{"text":"to process the device token and register it with Pushwoosh.","type":"text"}]},{"anchor":"Example","level":2,"text":"Example","type":"heading"},{"type":"codeListing","syntax":"swift","code":["func application(_ application: UIApplication,","                 didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {","    Pushwoosh.TVoS.handleTvPushToken(deviceToken)","}"]}],"kind":"content"}],"kind":"symbol","seeAlsoSections":[{"title":"Push Notification Handling","identifiers":["doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/handleTvPushRegistrationFailure(_:)","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/handleTvPushReceived(userInfo:completionHandler:)","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/handleTVOSPush(userInfo:)"],"generated":true}],"variants":[{"paths":["\/documentation\/pushwooshtvos\/pushwooshtvosimplementation\/handletvpushtoken(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pushwooshtvos\/pushwooshtvosimplementation\/handletvpushtoken(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/handleTvPushToken(_:)","interfaceLanguage":"swift"},"abstract":[{"text":"Handles the device token received from tvOS push registration.","type":"text"}],"metadata":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"handleTvPushToken","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"},{"kind":"text","text":")"}],"platforms":[{"unavailable":false,"introducedAt":"11.0","name":"tvOS","beta":false,"deprecated":false}],"externalID":"c:@M@PushwooshTVOS@objc(cs)PushwooshTVOSImplementation(cm)handleTvPushToken:","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"handleTvPushToken:"}],"title":"handleTvPushToken(_:)","modules":[{"name":"PushwooshTVOS"}],"symbolKind":"method","roleHeading":"Type Method"},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS"],["doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation"]]},"references":{"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PushwooshTVOSImplementation/handleTvPushToken(_:)":{"kind":"symbol","type":"topic","abstract":[{"text":"Handles the device token received from tvOS push registration.","type":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/handleTvPushToken(_:)","navigatorTitle":[{"kind":"identifier","text":"handleTvPushToken:"}],"title":"handleTvPushToken(_:)","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"handleTvPushToken","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":")","kind":"text"}],"url":"\/documentation\/pushwooshtvos\/pushwooshtvosimplementation\/handletvpushtoken(_:)","role":"symbol"},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS":{"url":"\/documentation\/pushwooshtvos","abstract":[{"text":"Push notifications and Rich Media for tvOS apps.","type":"text"}],"role":"collection","kind":"symbol","type":"topic","title":"PushwooshTVOS","identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS"},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PushwooshTVOSImplementation/handleTvPushReceived(userInfo:completionHandler:)":{"url":"\/documentation\/pushwooshtvos\/pushwooshtvosimplementation\/handletvpushreceived(userinfo:completionhandler:)","type":"topic","role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/handleTvPushReceived(userInfo:completionHandler:)","navigatorTitle":[{"text":"handleTvPushReceivedWithUserInfo:completionHandler:","kind":"identifier"}],"title":"handleTvPushReceived(userInfo:completionHandler:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"handleTvPushReceived","kind":"identifier"},{"kind":"text","text":"("},{"text":"userInfo","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"], "},{"text":"completionHandler","kind":"externalParam"},{"text":": (","kind":"text"},{"preciseIdentifier":"c:@E@UIBackgroundFetchResult","kind":"typeIdentifier","text":"UIBackgroundFetchResult"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")"}],"kind":"symbol","abstract":[{"type":"text","text":"Handles incoming push notification on tvOS."}]},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PushwooshTVOSImplementation":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation","abstract":[{"text":"Main implementation class for tvOS push notifications and Rich Media.","type":"text"}],"navigatorTitle":[{"text":"PushwooshTVOSImplementation","kind":"identifier"}],"title":"PushwooshTVOSImplementation","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PushwooshTVOSImplementation","kind":"identifier"}],"url":"\/documentation\/pushwooshtvos\/pushwooshtvosimplementation","role":"symbol"},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PushwooshTVOSImplementation/handleTvPushRegistrationFailure(_:)":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Handles push registration failure on tvOS."}],"identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/handleTvPushRegistrationFailure(_:)","navigatorTitle":[{"kind":"identifier","text":"handleTvPushRegistrationFailure:"}],"title":"handleTvPushRegistrationFailure(_:)","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"handleTvPushRegistrationFailure","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":")"}],"url":"\/documentation\/pushwooshtvos\/pushwooshtvosimplementation\/handletvpushregistrationfailure(_:)","role":"symbol"},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PushwooshTVOSImplementation/handleTVOSPush(userInfo:)":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/handleTVOSPush(userInfo:)","abstract":[{"type":"text","text":"Handles incoming push notifications with rich media content for tvOS."}],"navigatorTitle":[{"text":"handleTVOSPushWithUserInfo:","kind":"identifier"}],"title":"handleTVOSPush(userInfo:)","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"handleTVOSPush"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"userInfo"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"]) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/pushwooshtvos\/pushwooshtvosimplementation\/handletvospush(userinfo:)","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"handleTvPushToken:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"handleTvPushToken:"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/handleTvPushRegistrationFailure(_:)","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/handleTvPushReceived(userInfo:completionHandler:)","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/handleTVOSPush(userInfo:)"],"title":"Push Notification Handling","generated":true}],"op":"replace","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"handleTvPushToken:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSData","preciseIdentifier":"c:objc(cs)NSData","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"deviceToken","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["tvOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1handleTvPushToken(_:)\/title","value":"handleTvPushToken:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1handleTvPushToken(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"handleTvPushToken:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1handleTvPushReceived(userInfo:completionHandler:)\/title","value":"handleTvPushReceivedWithUserInfo:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1handleTvPushReceived(userInfo:completionHandler:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"handleTvPushReceivedWithUserInfo:completionHandler:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation\/title","value":"PushwooshTVOSImplementation"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation\/fragments","value":[{"text":"PushwooshTVOSImplementation","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"handleTvPushRegistrationFailure:","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1handleTvPushRegistrationFailure(_:)\/title"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"handleTvPushRegistrationFailure:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1handleTvPushRegistrationFailure(_:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1handleTVOSPush(userInfo:)\/title","value":"handleTVOSPushWithUserInfo:"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1handleTVOSPush(userInfo:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"handleTVOSPushWithUserInfo:","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}