{"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitAttributes"]]},"kind":"symbol","abstract":[{"type":"text","text":"Mapping of cell-kind identifiers to cell classes."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"cells","kind":"identifier"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"text":"PushwooshInboxCell","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCell","preciseIdentifier":"c:@M@PushwooshInboxKit@objc(cs)PushwooshInboxCell","kind":"typeIdentifier"},{"kind":"text","text":".Type]"}]}]},{"kind":"content","content":[{"type":"heading","anchor":"discussion","text":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"text":"The default registry ships ","type":"text"},{"inlineContent":[{"type":"text","text":"four entries"}],"type":"strong"},{"text":" matching Braze’s content-card","type":"text"},{"type":"text","text":" "},{"type":"text","text":"shapes:"}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"code":"\"banner\"","type":"codeVoice"},{"type":"text","text":" → "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxBannerCell"},{"type":"text","text":" — full-bleed image, no text."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"codeVoice","code":"\"captioned\""},{"text":" → ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCaptionedCell","isActive":true},{"type":"text","text":" — image on top, title + body below."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"code":"\"classic\"","type":"codeVoice"},{"type":"text","text":" → "},{"isActive":true,"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxClassicCell","type":"reference"},{"text":" — coloured initial avatar + title + body.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"code":"\"default\"","type":"codeVoice"},{"type":"text","text":" → "},{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxClassicCell","isActive":true,"type":"reference"},{"type":"text","text":" — fallback when the resolver returns an unknown kind."}]}]}]}]}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshinboxkit\/pushwooshinboxkitattributes\/cells"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitAttributes\/cells"},"metadata":{"roleHeading":"Instance Property","title":"cells","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"cells","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:@M@PushwooshInboxKit@objc(cs)PushwooshInboxCell","kind":"typeIdentifier","text":"PushwooshInboxCell"},{"text":".Type]","kind":"text"}],"externalID":"s:17PushwooshInboxKit0abC10AttributesV5cellsSDySSAA0aB4CellCmGvp","role":"symbol","modules":[{"name":"PushwooshInboxKit"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxCell":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushwooshInboxCell"}],"title":"PushwooshInboxCell","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PushwooshInboxCell"}],"kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCell","abstract":[{"type":"text","text":"Default inbox table-view cell. Subclass this type and register it under a"},{"text":" ","type":"text"},{"type":"text","text":"custom kind via "},{"type":"reference","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitAttributes\/cells","isActive":true},{"type":"text","text":" to ship bespoke"},{"text":" ","type":"text"},{"text":"layouts.","type":"text"}],"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxcell"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxClassicCell":{"navigatorTitle":[{"text":"PushwooshInboxClassicCell","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxClassicCell","title":"PushwooshInboxClassicCell","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PushwooshInboxClassicCell","kind":"identifier"}],"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxclassiccell","role":"symbol"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit","kind":"symbol","url":"\/documentation\/pushwooshinboxkit","title":"PushwooshInboxKit","role":"collection","abstract":[{"text":"Modern UIKit inbox UI powered by Pushwoosh.","type":"text"}],"type":"topic"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxCaptionedCell":{"type":"topic","abstract":[],"title":"PushwooshInboxCaptionedCell","kind":"symbol","navigatorTitle":[{"text":"PushwooshInboxCaptionedCell","kind":"identifier"}],"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxcaptionedcell","role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCaptionedCell","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushwooshInboxCaptionedCell"}]},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxBannerCell":{"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxbannercell","title":"PushwooshInboxBannerCell","abstract":[],"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxBannerCell","navigatorTitle":[{"kind":"identifier","text":"PushwooshInboxBannerCell"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PushwooshInboxBannerCell","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxKitAttributes/cells":{"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cells"},{"kind":"text","text":": ["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:@M@PushwooshInboxKit@objc(cs)PushwooshInboxCell","kind":"typeIdentifier","text":"PushwooshInboxCell"},{"text":".Type]","kind":"text"}],"title":"cells","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitAttributes\/cells","abstract":[{"type":"text","text":"Mapping of cell-kind identifiers to cell classes."}],"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxkitattributes\/cells"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxKitAttributes":{"type":"topic","navigatorTitle":[{"text":"PushwooshInboxKitAttributes","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration container for "},{"isActive":true,"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitViewController","type":"reference"},{"text":".","type":"text"}],"kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PushwooshInboxKitAttributes","kind":"identifier"}],"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxkitattributes","role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitAttributes","title":"PushwooshInboxKitAttributes"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxKitViewController":{"type":"topic","navigatorTitle":[{"text":"PushwooshInboxKitViewController","kind":"identifier"}],"abstract":[{"type":"text","text":"Modern UIKit inbox controller backed by "},{"code":"PWInboxService","type":"codeVoice"},{"text":".","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PushwooshInboxKitViewController","kind":"identifier"}],"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxkitviewcontroller","role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitViewController","title":"PushwooshInboxKitViewController"}},"variantOverrides":[{"patch":[{"op":"replace","value":"PushwooshInboxCell","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxCell\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxCell\/fragments","op":"replace","value":[{"kind":"identifier","text":"PushwooshInboxCell"}]},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxClassicCell\/title","value":"PushwooshInboxClassicCell","op":"replace"},{"value":[{"text":"PushwooshInboxClassicCell","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxClassicCell\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxCaptionedCell\/title","value":"PushwooshInboxCaptionedCell"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxCaptionedCell\/fragments","value":[{"text":"PushwooshInboxCaptionedCell","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxBannerCell\/title","op":"replace","value":"PushwooshInboxBannerCell"},{"value":[{"kind":"identifier","text":"PushwooshInboxBannerCell"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxBannerCell\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxKitViewController\/title","value":"PushwooshInboxKitViewController"},{"op":"replace","value":[{"kind":"identifier","text":"PushwooshInboxKitViewController"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxKitViewController\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}