{"metadata":{"symbolKind":"module","title":"PushwooshKeychain","roleHeading":"Framework","modules":[{"name":"PushwooshKeychain"}],"role":"collection","externalID":"PushwooshKeychain"},"kind":"symbol","topicSections":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshKeychain\/documentation\/PushwooshKeychain\/PushwooshKeychainImplementation"],"title":"Classes"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshKeychain\/documentation\/PushwooshKeychain"},"sections":[],"hierarchy":{"paths":[[]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshkeychain"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshkeychain"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.pushwoosh.PushwooshKeychain/documentation/PushwooshKeychain/PushwooshKeychainImplementation":{"navigatorTitle":[{"text":"PushwooshKeychainImplementation","kind":"identifier"}],"abstract":[{"type":"text","text":"Implementation of persistent HWID storage using iOS Keychain."}],"identifier":"doc:\/\/com.pushwoosh.PushwooshKeychain\/documentation\/PushwooshKeychain\/PushwooshKeychainImplementation","url":"\/documentation\/pushwooshkeychain\/pushwooshkeychainimplementation","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PushwooshKeychainImplementation","kind":"identifier"}],"role":"symbol","title":"PushwooshKeychainImplementation"},"doc://com.pushwoosh.PushwooshKeychain/documentation/PushwooshKeychain/PushwooshKeychainVersionString":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshKeychain\/documentation\/PushwooshKeychain\/PushwooshKeychainVersionString","title":"PushwooshKeychainVersionString","abstract":[{"type":"text","text":"Project version string for PushwooshKeychain."}],"url":"\/documentation\/pushwooshkeychain\/pushwooshkeychainversionstring","type":"topic","fragments":[{"kind":"identifier","text":"PushwooshKeychainVersionString"}]},"doc://com.pushwoosh.PushwooshKeychain/documentation/PushwooshKeychain/PushwooshKeychainVersionNumber":{"type":"topic","url":"\/documentation\/pushwooshkeychain\/pushwooshkeychainversionnumber","kind":"symbol","title":"PushwooshKeychainVersionNumber","identifier":"doc:\/\/com.pushwoosh.PushwooshKeychain\/documentation\/PushwooshKeychain\/PushwooshKeychainVersionNumber","abstract":[{"type":"text","text":"Project version number for PushwooshKeychain."}],"role":"symbol","fragments":[{"text":"PushwooshKeychainVersionNumber","kind":"identifier"}]},"doc://com.pushwoosh.PushwooshKeychain/documentation/PushwooshKeychain":{"type":"topic","url":"\/documentation\/pushwooshkeychain","title":"PushwooshKeychain","identifier":"doc:\/\/com.pushwoosh.PushwooshKeychain\/documentation\/PushwooshKeychain","kind":"symbol","role":"collection","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshKeychain\/documentation\/PushwooshKeychain\/PushwooshKeychainImplementation"],"title":"Classes"},{"title":"Variables","identifiers":["doc:\/\/com.pushwoosh.PushwooshKeychain\/documentation\/PushwooshKeychain\/PushwooshKeychainVersionNumber","doc:\/\/com.pushwoosh.PushwooshKeychain\/documentation\/PushwooshKeychain\/PushwooshKeychainVersionString"]}],"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshKeychain~1documentation~1PushwooshKeychain~1PushwooshKeychainImplementation\/title","op":"replace","value":"PushwooshKeychainImplementation"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshKeychain~1documentation~1PushwooshKeychain~1PushwooshKeychainImplementation\/fragments","value":[{"kind":"identifier","text":"PushwooshKeychainImplementation"}],"op":"replace"}]}]}