{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshNotificationUI\/documentation\/PushwooshNotificationUI\/PushwooshStoriesViewController"},"topicSections":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshNotificationUI\/documentation\/PushwooshNotificationUI\/PushwooshStoriesViewController\/appGroupIdentifier","doc:\/\/com.pushwoosh.PushwooshNotificationUI\/documentation\/PushwooshNotificationUI\/PushwooshStoriesViewController\/crossfadesBetweenPages","doc:\/\/com.pushwoosh.PushwooshNotificationUI\/documentation\/PushwooshNotificationUI\/PushwooshStoriesViewController\/hapticsEnabled","doc:\/\/com.pushwoosh.PushwooshNotificationUI\/documentation\/PushwooshNotificationUI\/PushwooshStoriesViewController\/longPressToPauseEnabled","doc:\/\/com.pushwoosh.PushwooshNotificationUI\/documentation\/PushwooshNotificationUI\/PushwooshStoriesViewController\/loopsAfterLastPage","doc:\/\/com.pushwoosh.PushwooshNotificationUI\/documentation\/PushwooshNotificationUI\/PushwooshStoriesViewController\/storiesDelegate","doc:\/\/com.pushwoosh.PushwooshNotificationUI\/documentation\/PushwooshNotificationUI\/PushwooshStoriesViewController\/storyAspectRatio"],"title":"Instance Properties"},{"identifiers":["doc:\/\/com.pushwoosh.PushwooshNotificationUI\/documentation\/PushwooshNotificationUI\/PushwooshStoriesViewController\/didReceive(_:)","doc:\/\/com.pushwoosh.PushwooshNotificationUI\/documentation\/PushwooshNotificationUI\/PushwooshStoriesViewController\/showDefaultContent(for:)","doc:\/\/com.pushwoosh.PushwooshNotificationUI\/documentation\/PushwooshNotificationUI\/PushwooshStoriesViewController\/viewDidLoad()","doc:\/\/com.pushwoosh.PushwooshNotificationUI\/documentation\/PushwooshNotificationUI\/PushwooshStoriesViewController\/viewWillDisappear(_:)"],"title":"Instance Methods"}],"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/com.pushwoosh.PushwooshNotificationUI\/objc(cs)UIViewController"],"kind":"relationships","type":"inheritsFrom"},{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.pushwoosh.PushwooshNotificationUI\/objc(pl)NSCoding","doc:\/\/com.pushwoosh.PushwooshNotificationUI\/objc(pl)NSExtensionRequestHandling","doc:\/\/com.pushwoosh.PushwooshNotificationUI\/objc(pl)NSObject","doc:\/\/com.pushwoosh.PushwooshNotificationUI\/s7CVarArgP","doc:\/\/com.pushwoosh.PushwooshNotificationUI\/s28CustomDebugStringConvertibleP","doc:\/\/com.pushwoosh.PushwooshNotificationUI\/s23CustomStringConvertibleP","doc:\/\/com.pushwoosh.PushwooshNotificationUI\/SQ","doc:\/\/com.pushwoosh.PushwooshNotificationUI\/SH","doc:\/\/com.pushwoosh.PushwooshNotificationUI\/s8SendableP","doc:\/\/com.pushwoosh.PushwooshNotificationUI\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.pushwoosh.PushwooshNotificationUI\/objc(pl)UIAppearanceContainer","doc:\/\/com.pushwoosh.PushwooshNotificationUI\/objc(pl)UIContentContainer","doc:\/\/com.pushwoosh.PushwooshNotificationUI\/objc(pl)UIFocusEnvironment","doc:\/\/com.pushwoosh.PushwooshNotificationUI\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.pushwoosh.PushwooshNotificationUI\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.pushwoosh.PushwooshNotificationUI\/objc(pl)UIStateRestoring","doc:\/\/com.pushwoosh.PushwooshNotificationUI\/5UIKit23UITraitChangeObservableP","doc:\/\/com.pushwoosh.PushwooshNotificationUI\/objc(pl)UITraitEnvironment","doc:\/\/com.pushwoosh.PushwooshNotificationUI\/objc(pl)UIUserActivityRestoring","doc:\/\/com.pushwoosh.PushwooshNotificationUI\/objc(pl)UNNotificationContentExtension"],"kind":"relationships"}],"variants":[{"paths":["\/documentation\/pushwooshnotificationui\/pushwooshstoriesviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshnotificationui\/pushwooshstoriesviewcontroller"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PushwooshStoriesViewController","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","type":"heading","level":2,"text":"Overview"},{"inlineContent":[{"text":"Subclass it one line inside your Notification Content Extension:","type":"text"}],"type":"paragraph"},{"syntax":"swift","type":"codeListing","code":["import PushwooshNotificationUI","","class NotificationViewController: PushwooshStoriesViewController {}"]},{"type":"paragraph","inlineContent":[{"text":"The stories are described by a ","type":"text"},{"code":"pw_stories","type":"codeVoice"},{"type":"text","text":" block in the notification payload. A missing,"},{"type":"text","text":" "},{"type":"text","text":"empty, or malformed payload falls back to the default content (the alert body) without crashing."},{"type":"text","text":" "},{"type":"text","text":"Override "},{"identifier":"doc:\/\/com.pushwoosh.PushwooshNotificationUI\/documentation\/PushwooshNotificationUI\/PushwooshStoriesViewController\/showDefaultContent(for:)","isActive":true,"type":"reference"},{"text":" to customise that fallback.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"The module links only UIKit, UserNotifications, and UserNotificationsUI — it adds no Pushwoosh","type":"text"},{"type":"text","text":" "},{"text":"Core\/Framework weight to the memory-constrained extension process.","type":"text"}]}]}],"metadata":{"navigatorTitle":[{"text":"PushwooshStoriesViewController","kind":"identifier"}],"title":"PushwooshStoriesViewController","role":"symbol","symbolKind":"class","modules":[{"name":"PushwooshNotificationUI"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PushwooshStoriesViewController"}],"externalID":"c:@M@PushwooshNotificationUI@objc(cs)PushwooshStoriesViewController","roleHeading":"Class"},"abstract":[{"text":"A drop-in ","type":"text"},{"code":"UNNotificationContentExtension","type":"codeVoice"},{"text":" view controller that renders a full-screen,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Instagram-style “stories” experience for an expanded push notification: full-bleed images,"},{"type":"text","text":" "},{"type":"text","text":"top progress bars, an auto-advance timer, tap-zone navigation, and an optional deep-link button."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshNotificationUI\/documentation\/PushwooshNotificationUI"]]},"kind":"symbol","sections":[],"references":{"doc://com.pushwoosh.PushwooshNotificationUI/objc(pl)UIResponderStandardEditActions":{"identifier":"doc:\/\/com.pushwoosh.PushwooshNotificationUI\/objc(pl)UIResponderStandardEditActions","title":"UIKit.UIResponderStandardEditActions","type":"unresolvable"},"doc://com.pushwoosh.PushwooshNotificationUI/documentation/PushwooshNotificationUI/PushwooshStoriesViewController/crossfadesBetweenPages":{"title":"crossfadesBetweenPages","role":"symbol","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshNotificationUI\/documentation\/PushwooshNotificationUI\/PushwooshStoriesViewController\/crossfadesBetweenPages","abstract":[{"text":"Whether pages cross-dissolve into each other instead of cutting hard. Automatically falls back","type":"text"},{"text":" ","type":"text"},{"text":"to an instant change when Reduce Motion is on. Override to ","type":"text"},{"type":"codeVoice","code":"true"},{"text":" to enable. Defaults to ","type":"text"},{"type":"codeVoice","code":"false"},{"text":".","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"crossfadesBetweenPages"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/pushwooshnotificationui\/pushwooshstoriesviewcontroller\/crossfadesbetweenpages","kind":"symbol"},"doc://com.pushwoosh.PushwooshNotificationUI/documentation/PushwooshNotificationUI/PushwooshStoriesViewController/showDefaultContent(for:)":{"role":"symbol","type":"topic","title":"showDefaultContent(for:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"showDefaultContent","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UNNotification","preciseIdentifier":"c:objc(cs)UNNotification"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshNotificationUI\/documentation\/PushwooshNotificationUI\/PushwooshStoriesViewController\/showDefaultContent(for:)","url":"\/documentation\/pushwooshnotificationui\/pushwooshstoriesviewcontroller\/showdefaultcontent(for:)","abstract":[{"type":"text","text":"Subclasses may override to customise the no-stories fallback. Default: show the alert body."}],"kind":"symbol"},"doc://com.pushwoosh.PushwooshNotificationUI/documentation/PushwooshNotificationUI/PushwooshStoriesViewController/longPressToPauseEnabled":{"abstract":[{"text":"Whether press-and-hold pauses the current page (timer + progress freeze) and lifting resumes —","type":"text"},{"type":"text","text":" "},{"text":"the signature “stories” gesture. Override to ","type":"text"},{"type":"codeVoice","code":"true"},{"type":"text","text":" to enable. Defaults to "},{"code":"false","type":"codeVoice"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.pushwoosh.PushwooshNotificationUI\/documentation\/PushwooshNotificationUI\/PushwooshStoriesViewController\/longPressToPauseEnabled","url":"\/documentation\/pushwooshnotificationui\/pushwooshstoriesviewcontroller\/longpresstopauseenabled","title":"longPressToPauseEnabled","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"longPressToPauseEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"kind":"symbol"},"doc://com.pushwoosh.PushwooshNotificationUI/objc(pl)NSCoding":{"identifier":"doc:\/\/com.pushwoosh.PushwooshNotificationUI\/objc(pl)NSCoding","title":"Foundation.NSCoding","type":"unresolvable"},"doc://com.pushwoosh.PushwooshNotificationUI/documentation/PushwooshNotificationUI/PushwooshStoriesViewController/viewDidLoad()":{"navigatorTitle":[{"text":"viewDidLoad","kind":"identifier"}],"title":"viewDidLoad()","role":"symbol","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshNotificationUI\/documentation\/PushwooshNotificationUI\/PushwooshStoriesViewController\/viewDidLoad()","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"viewDidLoad"},{"text":"()","kind":"text"}],"url":"\/documentation\/pushwooshnotificationui\/pushwooshstoriesviewcontroller\/viewdidload()","kind":"symbol"},"doc://com.pushwoosh.PushwooshNotificationUI/objc(pl)NSObject":{"identifier":"doc:\/\/com.pushwoosh.PushwooshNotificationUI\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.pushwoosh.PushwooshNotificationUI/documentation/PushwooshNotificationUI/PushwooshStoriesViewController/initWithCoder:":{"navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"title":"initWithCoder:","type":"topic","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"abstract":[],"url":"\/documentation\/pushwooshnotificationui\/pushwooshstoriesviewcontroller\/initwithcoder:","role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshNotificationUI\/documentation\/PushwooshNotificationUI\/PushwooshStoriesViewController\/initWithCoder:","kind":"symbol"},"doc://com.pushwoosh.PushwooshNotificationUI/documentation/PushwooshNotificationUI/PushwooshStoriesViewController":{"type":"topic","role":"symbol","title":"PushwooshStoriesViewController","identifier":"doc:\/\/com.pushwoosh.PushwooshNotificationUI\/documentation\/PushwooshNotificationUI\/PushwooshStoriesViewController","url":"\/documentation\/pushwooshnotificationui\/pushwooshstoriesviewcontroller","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushwooshStoriesViewController"}],"abstract":[{"type":"text","text":"A drop-in "},{"code":"UNNotificationContentExtension","type":"codeVoice"},{"text":" view controller that renders a full-screen,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Instagram-style “stories” experience for an expanded push notification: full-bleed images,"},{"text":" ","type":"text"},{"text":"top progress bars, an auto-advance timer, tap-zone navigation, and an optional deep-link button.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"PushwooshStoriesViewController"}],"kind":"symbol"},"doc://com.pushwoosh.PushwooshNotificationUI/s8SendableP":{"identifier":"doc:\/\/com.pushwoosh.PushwooshNotificationUI\/s8SendableP","title":"Swift.Sendable","type":"unresolvable"},"doc://com.pushwoosh.PushwooshNotificationUI/documentation/PushwooshNotificationUI/PushwooshStoriesViewController/hapticsEnabled":{"title":"hapticsEnabled","role":"symbol","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshNotificationUI\/documentation\/PushwooshNotificationUI\/PushwooshStoriesViewController\/hapticsEnabled","abstract":[{"text":"Whether a light tactile tap accompanies tap-zone navigation between pages. Override to ","type":"text"},{"code":"true","type":"codeVoice"},{"text":" ","type":"text"},{"type":"text","text":"to enable. Defaults to "},{"code":"false","type":"codeVoice"},{"type":"text","text":"."}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"hapticsEnabled","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/pushwooshnotificationui\/pushwooshstoriesviewcontroller\/hapticsenabled","kind":"symbol"},"doc://com.pushwoosh.PushwooshNotificationUI/documentation/PushwooshNotificationUI/PushwooshStoriesViewController/initWithNibName:bundle:":{"navigatorTitle":[{"kind":"identifier","text":"initWithNibName:bundle:"}],"title":"initWithNibName:bundle:","role":"symbol","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshNotificationUI\/documentation\/PushwooshNotificationUI\/PushwooshStoriesViewController\/initWithNibName:bundle:","abstract":[],"fragments":[{"text":"- ","kind":"text"},{"text":"initWithNibName:bundle:","kind":"identifier"}],"url":"\/documentation\/pushwooshnotificationui\/pushwooshstoriesviewcontroller\/initwithnibname:bundle:","kind":"symbol"},"doc://com.pushwoosh.PushwooshNotificationUI/objc(pl)UNNotificationContentExtension":{"identifier":"doc:\/\/com.pushwoosh.PushwooshNotificationUI\/objc(pl)UNNotificationContentExtension","title":"UNNotificationContentExtension","type":"unresolvable"},"doc://com.pushwoosh.PushwooshNotificationUI/s7CVarArgP":{"identifier":"doc:\/\/com.pushwoosh.PushwooshNotificationUI\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.pushwoosh.PushwooshNotificationUI/documentation/PushwooshNotificationUI":{"title":"PushwooshNotificationUI","identifier":"doc:\/\/com.pushwoosh.PushwooshNotificationUI\/documentation\/PushwooshNotificationUI","url":"\/documentation\/pushwooshnotificationui","abstract":[{"type":"text","text":"A ready-made full-screen “stories” UI for an expanded push notification."}],"role":"collection","kind":"symbol","type":"topic"},"doc://com.pushwoosh.PushwooshNotificationUI/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.pushwoosh.PushwooshNotificationUI\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.pushwoosh.PushwooshNotificationUI/objc(cs)UIViewController":{"identifier":"doc:\/\/com.pushwoosh.PushwooshNotificationUI\/objc(cs)UIViewController","title":"UIViewController","type":"unresolvable"},"doc://com.pushwoosh.PushwooshNotificationUI/objc(pl)UIFocusEnvironment":{"identifier":"doc:\/\/com.pushwoosh.PushwooshNotificationUI\/objc(pl)UIFocusEnvironment","title":"UIKit.UIFocusEnvironment","type":"unresolvable"},"doc://com.pushwoosh.PushwooshNotificationUI/objc(pl)UIContentContainer":{"identifier":"doc:\/\/com.pushwoosh.PushwooshNotificationUI\/objc(pl)UIContentContainer","title":"UIKit.UIContentContainer","type":"unresolvable"},"doc://com.pushwoosh.PushwooshNotificationUI/objc(pl)UITraitEnvironment":{"identifier":"doc:\/\/com.pushwoosh.PushwooshNotificationUI\/objc(pl)UITraitEnvironment","title":"UIKit.UITraitEnvironment","type":"unresolvable"},"doc://com.pushwoosh.PushwooshNotificationUI/objc(pl)NSExtensionRequestHandling":{"identifier":"doc:\/\/com.pushwoosh.PushwooshNotificationUI\/objc(pl)NSExtensionRequestHandling","title":"Foundation.NSExtensionRequestHandling","type":"unresolvable"},"doc://com.pushwoosh.PushwooshNotificationUI/objc(pl)UIStateRestoring":{"identifier":"doc:\/\/com.pushwoosh.PushwooshNotificationUI\/objc(pl)UIStateRestoring","title":"UIKit.UIStateRestoring","type":"unresolvable"},"doc://com.pushwoosh.PushwooshNotificationUI/objc(pl)UIActivityItemsConfigurationProviding":{"title":"UIKit.UIActivityItemsConfigurationProviding","type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshNotificationUI\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.pushwoosh.PushwooshNotificationUI/objc(pl)UIAppearanceContainer":{"identifier":"doc:\/\/com.pushwoosh.PushwooshNotificationUI\/objc(pl)UIAppearanceContainer","title":"UIKit.UIAppearanceContainer","type":"unresolvable"},"doc://com.pushwoosh.PushwooshNotificationUI/documentation/PushwooshNotificationUI/PushwooshStoriesViewController/loopsAfterLastPage":{"role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"loopsAfterLastPage"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"kind":"symbol","abstract":[{"text":"Whether playback restarts from the first page after the last one finishes, instead of stopping.","type":"text"},{"text":" ","type":"text"},{"text":"Override to ","type":"text"},{"code":"true","type":"codeVoice"},{"type":"text","text":" for an endlessly looping reel. Defaults to "},{"type":"codeVoice","code":"false"},{"type":"text","text":"."}],"title":"loopsAfterLastPage","identifier":"doc:\/\/com.pushwoosh.PushwooshNotificationUI\/documentation\/PushwooshNotificationUI\/PushwooshStoriesViewController\/loopsAfterLastPage","url":"\/documentation\/pushwooshnotificationui\/pushwooshstoriesviewcontroller\/loopsafterlastpage"},"doc://com.pushwoosh.PushwooshNotificationUI/documentation/PushwooshNotificationUI/PushwooshStoriesViewController/viewWillDisappear(_:)":{"navigatorTitle":[{"text":"viewWillDisappear:","kind":"identifier"}],"title":"viewWillDisappear(_:)","role":"symbol","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshNotificationUI\/documentation\/PushwooshNotificationUI\/PushwooshStoriesViewController\/viewWillDisappear(_:)","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"viewWillDisappear"},{"text":"(","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"url":"\/documentation\/pushwooshnotificationui\/pushwooshstoriesviewcontroller\/viewwilldisappear(_:)","kind":"symbol"},"doc://com.pushwoosh.PushwooshNotificationUI/5UIKit23UITraitChangeObservableP":{"identifier":"doc:\/\/com.pushwoosh.PushwooshNotificationUI\/5UIKit23UITraitChangeObservableP","title":"UIKit.UITraitChangeObservable","type":"unresolvable"},"doc://com.pushwoosh.PushwooshNotificationUI/SQ":{"identifier":"doc:\/\/com.pushwoosh.PushwooshNotificationUI\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.pushwoosh.PushwooshNotificationUI/documentation/PushwooshNotificationUI/PushwooshStoriesViewController/appGroupIdentifier":{"role":"symbol","type":"topic","title":"appGroupIdentifier","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"appGroupIdentifier","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshNotificationUI\/documentation\/PushwooshNotificationUI\/PushwooshStoriesViewController\/appGroupIdentifier","abstract":[{"type":"text","text":"App Group identifier shared with your Notification Service Extension. When set (and the"},{"type":"text","text":" "},{"text":"capability is enabled on both targets), the first frame is read from the shared container","type":"text"},{"type":"text","text":" "},{"type":"text","text":"that the Service Extension pre-warmed — instant and offline. Defaults to "},{"type":"codeVoice","code":"nil"},{"text":" (uses ","type":"text"},{"type":"codeVoice","code":"tmp"},{"text":").","type":"text"}],"kind":"symbol","url":"\/documentation\/pushwooshnotificationui\/pushwooshstoriesviewcontroller\/appgroupidentifier"},"doc://com.pushwoosh.PushwooshNotificationUI/documentation/PushwooshNotificationUI/PushwooshStoriesViewController/storiesDelegate":{"abstract":[{"type":"text","text":"Optional observer for story lifecycle \/ analytics events. Every method is optional —"},{"type":"text","text":" "},{"type":"text","text":"implement only the callbacks you need (impressions, clicks, completion, fallback)."}],"title":"storiesDelegate","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"storiesDelegate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PushwooshStoriesDelegate","kind":"typeIdentifier","preciseIdentifier":"s:23PushwooshNotificationUI0A15StoriesDelegateP"},{"text":"?","kind":"text"}],"kind":"symbol","url":"\/documentation\/pushwooshnotificationui\/pushwooshstoriesviewcontroller\/storiesdelegate","identifier":"doc:\/\/com.pushwoosh.PushwooshNotificationUI\/documentation\/PushwooshNotificationUI\/PushwooshStoriesViewController\/storiesDelegate","type":"topic","role":"symbol"},"doc://com.pushwoosh.PushwooshNotificationUI/documentation/PushwooshNotificationUI/PushwooshStoriesViewController/storyAspectRatio":{"role":"symbol","type":"topic","title":"storyAspectRatio","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"storyAspectRatio","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshNotificationUI\/documentation\/PushwooshNotificationUI\/PushwooshStoriesViewController\/storyAspectRatio","url":"\/documentation\/pushwooshnotificationui\/pushwooshstoriesviewcontroller\/storyaspectratio","abstract":[{"type":"text","text":"Aspect ratio (height ÷ width) of the stories area. Keep this in sync with the extension’s"},{"type":"text","text":" "},{"code":"UNNotificationExtensionInitialContentSizeRatio","type":"codeVoice"},{"type":"text","text":" so the notification doesn’t resize after the"},{"type":"text","text":" "},{"type":"text","text":"image loads. Override in a subclass to change the story proportions."}],"kind":"symbol"},"doc://com.pushwoosh.PushwooshNotificationUI/objc(pl)UIUserActivityRestoring":{"identifier":"doc:\/\/com.pushwoosh.PushwooshNotificationUI\/objc(pl)UIUserActivityRestoring","title":"UIKit.UIUserActivityRestoring","type":"unresolvable"},"doc://com.pushwoosh.PushwooshNotificationUI/objc(pl)UIPasteConfigurationSupporting":{"identifier":"doc:\/\/com.pushwoosh.PushwooshNotificationUI\/objc(pl)UIPasteConfigurationSupporting","title":"UIKit.UIPasteConfigurationSupporting","type":"unresolvable"},"doc://com.pushwoosh.PushwooshNotificationUI/SH":{"identifier":"doc:\/\/com.pushwoosh.PushwooshNotificationUI\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.pushwoosh.PushwooshNotificationUI/documentation/PushwooshNotificationUI/PushwooshStoriesViewController/didReceive(_:)":{"navigatorTitle":[{"text":"didReceiveNotification:","kind":"identifier"}],"title":"didReceive(_:)","role":"symbol","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshNotificationUI\/documentation\/PushwooshNotificationUI\/PushwooshStoriesViewController\/didReceive(_:)","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didReceive"},{"text":"(","kind":"text"},{"text":"UNNotification","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UNNotification"},{"kind":"text","text":")"}],"url":"\/documentation\/pushwooshnotificationui\/pushwooshstoriesviewcontroller\/didreceive(_:)","kind":"symbol"},"doc://com.pushwoosh.PushwooshNotificationUI/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.pushwoosh.PushwooshNotificationUI\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"PushwooshStoriesViewController"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"PushwooshStoriesViewController"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"PushwooshStoriesViewController"}],"op":"replace"},{"value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.pushwoosh.PushwooshNotificationUI\/documentation\/PushwooshNotificationUI\/PushwooshStoriesViewController\/didReceive(_:)","doc:\/\/com.pushwoosh.PushwooshNotificationUI\/documentation\/PushwooshNotificationUI\/PushwooshStoriesViewController\/initWithCoder:","doc:\/\/com.pushwoosh.PushwooshNotificationUI\/documentation\/PushwooshNotificationUI\/PushwooshStoriesViewController\/initWithNibName:bundle:","doc:\/\/com.pushwoosh.PushwooshNotificationUI\/documentation\/PushwooshNotificationUI\/PushwooshStoriesViewController\/viewDidLoad()","doc:\/\/com.pushwoosh.PushwooshNotificationUI\/documentation\/PushwooshNotificationUI\/PushwooshStoriesViewController\/viewWillDisappear(_:)"]}],"path":"\/topicSections","op":"replace"},{"op":"replace","value":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshNotificationUI\/objc(cs)UIViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"title":"Conforms To","kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/com.pushwoosh.PushwooshNotificationUI\/objc(pl)UNNotificationContentExtension"]}],"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushwooshStoriesViewController"},{"text":" : ","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshNotificationUI~1documentation~1PushwooshNotificationUI~1PushwooshStoriesViewController~1viewDidLoad()\/title","value":"viewDidLoad"},{"value":[{"text":"- ","kind":"text"},{"text":"viewDidLoad","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshNotificationUI~1documentation~1PushwooshNotificationUI~1PushwooshStoriesViewController~1viewDidLoad()\/fragments"},{"value":"PushwooshStoriesViewController","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshNotificationUI~1documentation~1PushwooshNotificationUI~1PushwooshStoriesViewController\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshNotificationUI~1documentation~1PushwooshNotificationUI~1PushwooshStoriesViewController\/fragments","value":[{"kind":"identifier","text":"PushwooshStoriesViewController"}],"op":"replace"},{"value":"viewWillDisappear:","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshNotificationUI~1documentation~1PushwooshNotificationUI~1PushwooshStoriesViewController~1viewWillDisappear(_:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"viewWillDisappear:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshNotificationUI~1documentation~1PushwooshNotificationUI~1PushwooshStoriesViewController~1viewWillDisappear(_:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshNotificationUI~1documentation~1PushwooshNotificationUI~1PushwooshStoriesViewController~1didReceive(_:)\/title","value":"didReceiveNotification:"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshNotificationUI~1documentation~1PushwooshNotificationUI~1PushwooshStoriesViewController~1didReceive(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"didReceiveNotification:"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}