{"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshForegroundPush\/documentation\/PushwooshForegroundPush"]]},"kind":"article","variants":[{"paths":["\/documentation\/pushwooshforegroundpush\/examples"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshforegroundpush\/examples"]}],"sections":[],"seeAlsoSections":[{"generated":true,"identifiers":["doc:\/\/com.pushwoosh.PushwooshForegroundPush\/documentation\/PushwooshForegroundPush\/GettingStarted"],"title":"Getting Started"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshForegroundPush\/documentation\/PushwooshForegroundPush\/Examples"},"primaryContentSections":[{"content":[{"text":"Overview","level":2,"anchor":"Overview","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"This guide provides working code examples for customizing PushwooshForegroundPush appearance, animations, and user interactions.","type":"text"}]},{"text":"Basic Setup","level":2,"type":"heading","anchor":"Basic-Setup"},{"type":"heading","level":3,"text":"Minimal Configuration","anchor":"Minimal-Configuration"},{"inlineContent":[{"text":"The simplest configuration with default appearance:","type":"text"}],"type":"paragraph"},{"code":["import UIKit","import PushwooshFramework","import PushwooshForegroundPush","","@main","class AppDelegate: UIResponder, UIApplicationDelegate, PWForegroundPushDelegate {","","    func application(","        _ application: UIApplication,","        didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?","    ) -> Bool {","","        Pushwoosh.ForegroundPush.foregroundNotificationWith(","            style: .style1,","            duration: 5,","            vibration: .notification,","            disappearedPushAnimation: .balls","        )","","        Pushwoosh.ForegroundPush.delegate = self","","        return true","    }","","    func didTapForegroundPush(_ userInfo: [AnyHashable: Any]) {","        print(\"Foreground custom push: \\(userInfo)\")","    }","}"],"type":"codeListing","syntax":"swift"},{"type":"heading","text":"Appearance Customization","level":2,"anchor":"Appearance-Customization"},{"text":"Custom Gradient Background","type":"heading","level":3,"anchor":"Custom-Gradient-Background"},{"inlineContent":[{"type":"text","text":"Create a vibrant gradient background with custom text colors:"}],"type":"paragraph"},{"code":["Pushwoosh.ForegroundPush.gradientColors = [.red, .orange, .yellow]","Pushwoosh.ForegroundPush.titlePushColor = .white","Pushwoosh.ForegroundPush.messagePushColor = .white"],"type":"codeListing","syntax":"swift"},{"type":"paragraph","inlineContent":[{"identifier":"ios-foreground-custom-3.gif","type":"image"}]},{"level":3,"text":"Solid Background Color","type":"heading","anchor":"Solid-Background-Color"},{"inlineContent":[{"type":"text","text":"Use a solid color instead of gradient:"}],"type":"paragraph"},{"type":"codeListing","code":["Pushwoosh.ForegroundPush.backgroundColor = UIColor(red: 0.1, green: 0.1, blue: 0.1, alpha: 0.95)","Pushwoosh.ForegroundPush.gradientColors = nil"],"syntax":"swift"},{"level":3,"anchor":"Custom-Fonts","type":"heading","text":"Custom Fonts"},{"type":"paragraph","inlineContent":[{"text":"Use custom fonts for title and message:","type":"text"}]},{"type":"codeListing","syntax":"swift","code":["Pushwoosh.ForegroundPush.backgroundColor = .systemPurple","Pushwoosh.ForegroundPush.titlePushFont = UIFont(name: \"YourCustomFont-Bold\", size: 18)","Pushwoosh.ForegroundPush.messagePushFont = UIFont(name: \"YourCustomFont-Regular\", size: 15)","Pushwoosh.ForegroundPush.titlePushColor = .white","Pushwoosh.ForegroundPush.messagePushColor = .white"]},{"inlineContent":[{"type":"image","identifier":"ios-foreground-custom-4.gif"}],"type":"paragraph"},{"anchor":"Rich-Media-Support","type":"heading","level":2,"text":"Rich Media Support"},{"anchor":"Push-with-Image-Attachment","type":"heading","level":3,"text":"Push with Image Attachment"},{"inlineContent":[{"text":"Foreground push notifications support image attachments:","type":"text"}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"identifier":"ios-foreground-custom-2.gif","type":"image"}]},{"level":3,"anchor":"Push-with-GIF-Attachment","text":"Push with GIF Attachment","type":"heading"},{"inlineContent":[{"type":"text","text":"Animated GIF images are supported:"}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"identifier":"ios-foreground-custom-1.gif","type":"image"}]},{"inlineContent":[{"text":"The attachment URL is specified in the push notification payload. The SDK automatically downloads and displays the media content.","type":"text"}],"type":"paragraph"},{"type":"heading","text":"Animation Customization","level":2,"anchor":"Animation-Customization"},{"level":3,"anchor":"Disable-Entry-Animation","type":"heading","text":"Disable Entry Animation"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Show push instantly without slide animation:"}]},{"code":["Pushwoosh.ForegroundPush.usePushAnimation = false"],"syntax":"swift","type":"codeListing"},{"type":"paragraph","inlineContent":[{"type":"image","identifier":"ios-foreground-custom-4.gif"}]},{"type":"heading","text":"Particle Explosion Effect","level":3,"anchor":"Particle-Explosion-Effect"},{"type":"paragraph","inlineContent":[{"text":"Use particle explosion when push disappears:","type":"text"}]},{"type":"codeListing","syntax":"swift","code":["Pushwoosh.ForegroundPush.foregroundNotificationWith(","    style: .style1,","    duration: 5,","    vibration: .notification,","    disappearedPushAnimation: .balls",")"]},{"type":"heading","anchor":"Regular-Push-Animation","text":"Regular Push Animation","level":3},{"type":"paragraph","inlineContent":[{"type":"text","text":"Use standard upward slide animation:"}]},{"syntax":"swift","code":["Pushwoosh.ForegroundPush.foregroundNotificationWith(","    style: .style1,","    duration: 5,","    vibration: .notification,","    disappearedPushAnimation: .regularPush",")"],"type":"codeListing"},{"anchor":"Liquid-Glass-Effect-iOS-26+","type":"heading","text":"Liquid Glass Effect (iOS 26+)","level":3},{"type":"paragraph","inlineContent":[{"type":"text","text":"Enable modern Liquid Glass visual effect:"}]},{"type":"codeListing","syntax":"swift","code":["Pushwoosh.ForegroundPush.useLiquidView = true"]},{"type":"paragraph","inlineContent":[{"type":"image","identifier":"ios-foreground-custom-5.gif"}]},{"type":"aside","style":"note","name":"Note","content":[{"type":"paragraph","inlineContent":[{"inlineContent":[{"text":"Important","type":"text"}],"type":"strong"},{"type":"text","text":": Liquid Glass requires iOS 26+ and Swift 5.13+. On earlier iOS versions, standard UIView-based notifications are displayed. Swift versions below 5.13 use blurred UIVisualEffectView."}]}]},{"anchor":"Haptic-Feedback-Options","text":"Haptic Feedback Options","type":"heading","level":2},{"text":"No Vibration","level":3,"anchor":"No-Vibration","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"For silent notifications:"}]},{"syntax":"swift","type":"codeListing","code":["Pushwoosh.ForegroundPush.foregroundNotificationWith(","    style: .style1,","    duration: 5,","    vibration: .none,","    disappearedPushAnimation: .balls",")"]},{"text":"Strong Haptic","type":"heading","level":3,"anchor":"Strong-Haptic"},{"type":"paragraph","inlineContent":[{"text":"For important notifications:","type":"text"}]},{"type":"codeListing","syntax":"swift","code":["Pushwoosh.ForegroundPush.foregroundNotificationWith(","    style: .style1,","    duration: 7,","    vibration: .heavy,","    disappearedPushAnimation: .balls",")"]},{"level":3,"anchor":"System-Notification-Haptic","type":"heading","text":"System Notification Haptic"},{"inlineContent":[{"type":"text","text":"Use system notification-style haptic:"}],"type":"paragraph"},{"type":"codeListing","syntax":"swift","code":["Pushwoosh.ForegroundPush.foregroundNotificationWith(","    style: .style1,","    duration: 5,","    vibration: .notification,","    disappearedPushAnimation: .balls",")"]},{"level":2,"anchor":"Handling-User-Interactions","type":"heading","text":"Handling User Interactions"},{"anchor":"Implementing-Delegate","level":3,"type":"heading","text":"Implementing Delegate"},{"inlineContent":[{"type":"text","text":"Handle user taps through the delegate method:"}],"type":"paragraph"},{"syntax":"swift","code":["class AppDelegate: UIResponder, UIApplicationDelegate, PWForegroundPushDelegate {","","    func application(","        _ application: UIApplication,","        didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?","    ) -> Bool {","        Pushwoosh.ForegroundPush.delegate = self","        return true","    }","","    func didTapForegroundPush(_ userInfo: [AnyHashable: Any]) {","        print(\"Foreground custom push tapped: \\(userInfo)\")","","        if let customData = userInfo[\"custom\"] as? [String: Any],","           let screenId = customData[\"screen_id\"] as? String {","            navigateToScreen(screenId)","        }","    }","}"],"type":"codeListing"},{"level":3,"anchor":"Deep-Link-Handling","text":"Deep Link Handling","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Handle deep links from push notifications:"}]},{"type":"codeListing","code":["func didTapForegroundPush(_ userInfo: [AnyHashable: Any]) {","    if let deepLink = userInfo[\"deep_link\"] as? String,","       let url = URL(string: deepLink) {","        UIApplication.shared.open(url, options: [:]) { success in","            print(\"Deep link opened: \\(success)\")","        }","    }","}"],"syntax":"swift"},{"text":"Complete Custom Setup","type":"heading","level":2,"anchor":"Complete-Custom-Setup"},{"text":"Branded Notification","type":"heading","level":3,"anchor":"Branded-Notification"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Full customization with brand identity:"}]},{"type":"codeListing","syntax":"swift","code":["func configureBrandedForegroundPush() {","    Pushwoosh.ForegroundPush.gradientColors = [","        UIColor(red: 0.18, green: 0.31, blue: 0.64, alpha: 1.0),","        UIColor(red: 0.44, green: 0.26, blue: 0.63, alpha: 1.0)","    ]","","    Pushwoosh.ForegroundPush.titlePushColor = .white","    Pushwoosh.ForegroundPush.messagePushColor = UIColor(white: 0.95, alpha: 1.0)","","    Pushwoosh.ForegroundPush.titlePushFont = UIFont(name: \"Helvetica-Bold\", size: 18)","    Pushwoosh.ForegroundPush.messagePushFont = UIFont(name: \"Helvetica\", size: 15)","","    Pushwoosh.ForegroundPush.usePushAnimation = true","    Pushwoosh.ForegroundPush.useLiquidView = true","","    Pushwoosh.ForegroundPush.foregroundNotificationWith(","        style: .style1,","        duration: 6,","        vibration: .notification,","        disappearedPushAnimation: .balls","    )","","    Pushwoosh.ForegroundPush.delegate = self","}"]},{"anchor":"Dark-Mode-Support","text":"Dark Mode Support","level":2,"type":"heading"},{"text":"Adaptive Colors","level":3,"type":"heading","anchor":"Adaptive-Colors"},{"inlineContent":[{"text":"Adjust colors based on user interface style:","type":"text"}],"type":"paragraph"},{"type":"codeListing","syntax":"swift","code":["func configureForegroundPushColors() {","    if #available(iOS 13.0, *) {","        let isDarkMode = UITraitCollection.current.userInterfaceStyle == .dark","","        if isDarkMode {","            Pushwoosh.ForegroundPush.gradientColors = [","                UIColor(red: 0.15, green: 0.15, blue: 0.15, alpha: 1.0),","                UIColor(red: 0.25, green: 0.25, blue: 0.25, alpha: 1.0)","            ]","            Pushwoosh.ForegroundPush.titlePushColor = .white","            Pushwoosh.ForegroundPush.messagePushColor = UIColor(white: 0.85, alpha: 1.0)","        } else {","            Pushwoosh.ForegroundPush.gradientColors = [","                UIColor(red: 0.95, green: 0.95, blue: 0.95, alpha: 1.0),","                UIColor(red: 0.85, green: 0.85, blue: 0.85, alpha: 1.0)","            ]","            Pushwoosh.ForegroundPush.titlePushColor = .black","            Pushwoosh.ForegroundPush.messagePushColor = UIColor(white: 0.15, alpha: 1.0)","        }","    }","}"]},{"type":"heading","level":2,"anchor":"Next-Steps","text":"Next Steps"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/com.pushwoosh.PushwooshForegroundPush\/documentation\/PushwooshForegroundPush\/GettingStarted"},{"type":"text","text":" - Quick start guide"}]}]},{"content":[{"inlineContent":[{"type":"reference","identifier":"doc:\/\/com.pushwoosh.PushwooshForegroundPush\/documentation\/PushwooshForegroundPush\/PushwooshForegroundPushImplementation","isActive":true},{"text":" - Full API reference","type":"text"}],"type":"paragraph"}]}]}],"kind":"content"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"modules":[{"name":"PushwooshForegroundPush"}],"roleHeading":"Article","title":"Code Examples","role":"article"},"abstract":[{"text":"Practical examples for common foreground push notification scenarios.","type":"text"}],"references":{"doc://com.pushwoosh.PushwooshForegroundPush/documentation/PushwooshForegroundPush/PushwooshForegroundPushImplementation":{"type":"topic","abstract":[{"type":"text","text":"Main implementation class that manages foreground push notifications display and configuration."}],"navigatorTitle":[{"text":"PushwooshForegroundPushImplementation","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PushwooshForegroundPushImplementation"}],"title":"PushwooshForegroundPushImplementation","url":"\/documentation\/pushwooshforegroundpush\/pushwooshforegroundpushimplementation","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshForegroundPush\/documentation\/PushwooshForegroundPush\/PushwooshForegroundPushImplementation"},"ios-foreground-custom-2.gif":{"type":"image","identifier":"ios-foreground-custom-2.gif","alt":"Foreground push with card image attachment","variants":[{"traits":["1x","light"],"url":"\/images\/ios-foreground-custom-2.gif"}]},"doc://com.pushwoosh.PushwooshForegroundPush/documentation/PushwooshForegroundPush/GettingStarted":{"role":"article","title":"Getting Started","abstract":[{"text":"Customize foreground push notifications when native iOS system alerts are disabled.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshForegroundPush\/documentation\/PushwooshForegroundPush\/GettingStarted","url":"\/documentation\/pushwooshforegroundpush\/gettingstarted","kind":"article"},"ios-foreground-custom-4.gif":{"alt":"Foreground push with no animation","identifier":"ios-foreground-custom-4.gif","type":"image","variants":[{"url":"\/images\/ios-foreground-custom-4.gif","traits":["1x","light"]}]},"ios-foreground-custom-3.gif":{"alt":"Foreground push with custom gradient and text colors","identifier":"ios-foreground-custom-3.gif","type":"image","variants":[{"url":"\/images\/ios-foreground-custom-3.gif","traits":["1x","light"]}]},"doc://com.pushwoosh.PushwooshForegroundPush/documentation/PushwooshForegroundPush":{"url":"\/documentation\/pushwooshforegroundpush","type":"topic","abstract":[{"text":"Customizable foreground push notifications for iOS applications.","type":"text"}],"title":"PushwooshForegroundPush","identifier":"doc:\/\/com.pushwoosh.PushwooshForegroundPush\/documentation\/PushwooshForegroundPush","kind":"symbol","role":"collection"},"ios-foreground-custom-5.gif":{"type":"image","identifier":"ios-foreground-custom-5.gif","alt":"Foreground push with Liquid Glass effect","variants":[{"url":"\/images\/ios-foreground-custom-5.gif","traits":["1x","light"]}]},"ios-foreground-custom-1.gif":{"alt":"Foreground push with animated GIF","type":"image","identifier":"ios-foreground-custom-1.gif","variants":[{"traits":["1x","light"],"url":"\/images\/ios-foreground-custom-1.gif"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"add","path":"\/topicSections","value":null},{"value":[{"generated":true,"identifiers":["doc:\/\/com.pushwoosh.PushwooshForegroundPush\/documentation\/PushwooshForegroundPush\/GettingStarted"],"title":"Getting Started"}],"path":"\/seeAlsoSections","op":"replace"}]}]}