{"variants":[{"paths":["\/documentation\/pushwooshforegroundpush\/gettingstarted"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pushwooshforegroundpush\/gettingstarted"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"article","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshForegroundPush\/documentation\/PushwooshForegroundPush\/GettingStarted"},"seeAlsoSections":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshForegroundPush\/documentation\/PushwooshForegroundPush\/Examples"],"generated":true,"title":"Getting Started"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"modules":[{"name":"PushwooshForegroundPush"}],"role":"article","title":"Getting Started","roleHeading":"Article"},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshForegroundPush\/documentation\/PushwooshForegroundPush"]]},"abstract":[{"text":"Customize foreground push notifications when native iOS system alerts are disabled.","type":"text"}],"primaryContentSections":[{"content":[{"text":"Prerequisites","anchor":"Prerequisites","type":"heading","level":2},{"inlineContent":[{"text":"Before you begin, ensure you have:","type":"text"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"A Pushwoosh account"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A Pushwoosh project set up in your account"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"An iOS platform configured in your Pushwoosh project. We recommend using the Token-Based Authentication configuration as the simplest approach"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Your Pushwoosh Application Code from the Control Panel","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"iOS 14.0+ deployment target"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Pushwoosh SDK version 6.10.0 or higher"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"PushwooshFramework, PushwooshCore, and PushwooshBridge frameworks integrated in your project","type":"text"}],"type":"paragraph"}]}]},{"type":"aside","name":"Note","style":"note","content":[{"inlineContent":[{"type":"strong","inlineContent":[{"text":"Important","type":"text"}]},{"type":"text","text":": PushwooshForegroundPush requires the main Pushwoosh SDK to be properly configured for push notifications."}],"type":"paragraph"}]},{"level":2,"type":"heading","anchor":"Step-1-Disable-Native-Alerts","text":"Step 1: Disable Native Alerts"},{"inlineContent":[{"text":"Add the following key to your ","type":"text"},{"type":"codeVoice","code":"Info.plist"},{"text":" file to disable native iOS system alerts:","type":"text"}],"type":"paragraph"},{"syntax":"xml","code":["<key>Pushwoosh_SHOW_ALERT<\/key>","<false\/>"],"type":"codeListing"},{"inlineContent":[{"text":"This allows PushwooshForegroundPush to display custom foreground notifications instead of system alerts.","type":"text"}],"type":"paragraph"},{"level":2,"anchor":"Step-2-Install-Module","text":"Step 2: Install Module","type":"heading"},{"type":"tabNavigator","tabs":[{"title":"Swift Package Manager","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"In Xcode, use the following URL to add the Pushwoosh dependency:"}]},{"code":["https:\/\/github.com\/Pushwoosh\/Pushwoosh-XCFramework"],"syntax":null,"type":"codeListing"},{"type":"paragraph","inlineContent":[{"text":"Select the required modules in your target:","type":"text"}]},{"inlineContent":[],"type":"paragraph"},{"style":"note","name":"Note","content":[{"inlineContent":[{"type":"strong","inlineContent":[{"text":"Important","type":"text"}]},{"type":"text","text":": The modules PushwooshFramework, PushwooshCore, PushwooshBridge, PushwooshForegroundPush, and PushwooshLiveActivities are required."}],"type":"paragraph"}],"type":"aside"}]},{"title":"CocoaPods","content":[{"inlineContent":[{"type":"text","text":"Add to your Podfile:"}],"type":"paragraph"},{"code":["pod 'PushwooshXCFramework'","pod 'PushwooshFramework\/PushwooshForegroundPush'"],"type":"codeListing","syntax":"ruby"},{"type":"paragraph","inlineContent":[{"text":"Then run:","type":"text"}]},{"code":["pod install"],"syntax":"bash","type":"codeListing"}]}]},{"level":2,"type":"heading","anchor":"Step-3-Add-Required-Capabilities","text":"Step 3: Add Required Capabilities"},{"inlineContent":[{"type":"text","text":"In Xcode:"}],"type":"paragraph"},{"type":"orderedList","items":[{"content":[{"inlineContent":[{"text":"Select your target","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Go to ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"Signing & Capabilities"}]}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Click "},{"inlineContent":[{"text":"+ Capability","type":"text"}],"type":"strong"},{"type":"text","text":" and add "},{"type":"strong","inlineContent":[{"text":"Push Notifications","type":"text"}]}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Click "},{"inlineContent":[{"text":"+ Capability","type":"text"}],"type":"strong"},{"type":"text","text":" and add "},{"type":"strong","inlineContent":[{"type":"text","text":"Background Modes"}]}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"In Background Modes, enable ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"Remote notifications"}]},{"text":" checkbox","type":"text"}]}]}]},{"type":"paragraph","inlineContent":[]},{"level":2,"type":"heading","text":"Step 4: Configure Foreground Push","anchor":"Step-4-Configure-Foreground-Push"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Configure foreground push and set delegate in "},{"type":"codeVoice","code":"application(_:didFinishLaunchingWithOptions:)"},{"type":"text","text":":"}]},{"syntax":"swift","code":["import UIKit","import PushwooshFramework","import PushwooshForegroundPush","","@main","class AppDelegate: UIResponder, UIApplicationDelegate, PWForegroundPushDelegate {","","    func application(","        _ application: UIApplication,","        didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?","    ) -> Bool {","","        Pushwoosh.ForegroundPush.foregroundNotificationWith(","            style: .style1,","            duration: 5,","            vibration: .notification,","            disappearedPushAnimation: .balls","        )","","        Pushwoosh.ForegroundPush.delegate = self","","        return true","    }","","    \/\/ MARK: - Push Notification Registration","","    func application(","        _ application: UIApplication,","        didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data","    ) {","        Pushwoosh.configure.handlePushRegistration(deviceToken)","    }","","    func application(","        _ application: UIApplication,","        didFailToRegisterForRemoteNotificationsWithError error: Error","    ) {","        print(\"Failed to register for remote notifications: \\(error)\")","    }","","    \/\/ MARK: - PWForegroundPushDelegate","","    func didTapForegroundPush(_ userInfo: [AnyHashable: Any]) {","        print(\"Foreground custom push tapped: \\(userInfo)\")","    }","}"],"type":"codeListing"},{"type":"heading","level":3,"anchor":"Configuration-Parameters","text":"Configuration Parameters"},{"header":"row","rows":[[[{"type":"paragraph","inlineContent":[{"text":"Parameter","type":"text"}]}],[{"type":"paragraph","inlineContent":[{"text":"Type","type":"text"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"Description"}]}]],[[{"type":"paragraph","inlineContent":[{"code":"style","type":"codeVoice"}]}],[{"type":"paragraph","inlineContent":[{"code":"PWForegroundPushStyle","type":"codeVoice"}]}],[{"type":"paragraph","inlineContent":[{"text":"Visual template for the notification. Currently only ","type":"text"},{"type":"codeVoice","code":".style1"},{"text":" is available","type":"text"}]}]],[[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"duration"}]}],[{"inlineContent":[{"code":"Int","type":"codeVoice"}],"type":"paragraph"}],[{"inlineContent":[{"text":"Display time in seconds","type":"text"}],"type":"paragraph"}]],[[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"vibration"}]}],[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"PWForegroundPushHapticFeedback"}]}],[{"type":"paragraph","inlineContent":[{"text":"Haptic feedback type:","type":"text"},{"type":"text","text":"• "},{"code":".none","type":"codeVoice"},{"type":"text","text":" – No vibration"},{"text":"• ","type":"text"},{"code":".light","type":"codeVoice"},{"type":"text","text":" – Subtle feedback"},{"text":"• ","type":"text"},{"type":"codeVoice","code":".medium"},{"type":"text","text":" – Standard feedback"},{"text":"• ","type":"text"},{"type":"codeVoice","code":".heavy"},{"type":"text","text":" – Strong feedback"},{"text":"• ","type":"text"},{"code":".soft","type":"codeVoice"},{"type":"text","text":" – Gentle feedback"},{"type":"text","text":"• "},{"type":"codeVoice","code":".rigid"},{"text":" – Sharp feedback","type":"text"},{"text":"• ","type":"text"},{"type":"codeVoice","code":".notification"},{"text":" – System notification feedback","type":"text"}]}]],[[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"disappearedPushAnimation"}]}],[{"inlineContent":[{"type":"codeVoice","code":"PWForegroundPushDisappearedAnimation"}],"type":"paragraph"}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"Exit animation:"},{"text":"• ","type":"text"},{"code":".balls","type":"codeVoice"},{"text":" – Explodes into particles","type":"text"},{"type":"text","text":"• "},{"type":"codeVoice","code":".regularPush"},{"type":"text","text":" – Slides up and fades"}]}]]],"type":"table"},{"level":3,"type":"heading","text":"Delegate Methods","anchor":"Delegate-Methods"},{"inlineContent":[{"type":"text","text":"The "},{"identifier":"doc:\/\/com.pushwoosh.PushwooshForegroundPush\/documentation\/PushwooshForegroundPush\/PWForegroundPushDelegate","isActive":true,"type":"reference"},{"text":" protocol provides callbacks for foreground push events:","type":"text"}],"type":"paragraph"},{"rows":[[[{"inlineContent":[{"type":"text","text":"Method"}],"type":"paragraph"}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"Description"}]}]],[[{"inlineContent":[{"type":"codeVoice","code":"didTapForegroundPush(_:)"}],"type":"paragraph"}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"Called when user taps on the foreground push notification"}]}]]],"type":"table","header":"row"},{"type":"heading","level":2,"anchor":"Customization","text":"Customization"},{"inlineContent":[{"text":"Configure appearance globally using static properties:","type":"text"}],"type":"paragraph"},{"syntax":"swift","type":"codeListing","code":["Pushwoosh.ForegroundPush.useLiquidView = true","Pushwoosh.ForegroundPush.gradientColors = [.red, .orange, .yellow]","Pushwoosh.ForegroundPush.titlePushColor = .red","Pushwoosh.ForegroundPush.messagePushColor = .white","Pushwoosh.ForegroundPush.usePushAnimation = false"]},{"type":"heading","level":3,"anchor":"Available-Properties","text":"Available Properties"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"useLiquidView"},{"text":" - Enable Liquid Glass effect (requires iOS 26+ and Swift 5.13+)","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"gradientColors"},{"text":" - Custom gradient background colors","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"codeVoice","code":"backgroundColor"},{"text":" - Solid background color","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"code":"titlePushColor","type":"codeVoice"},{"type":"text","text":" - Text color for notification title"}]}]},{"content":[{"inlineContent":[{"type":"codeVoice","code":"messagePushColor"},{"type":"text","text":" - Text color for notification message"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"titlePushFont"},{"type":"text","text":" - Custom font for title"}]}]},{"content":[{"inlineContent":[{"type":"codeVoice","code":"messagePushFont"},{"type":"text","text":" - Custom font for message"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"code":"usePushAnimation","type":"codeVoice"},{"text":" - Enable or disable show animation","type":"text"}],"type":"paragraph"}]}]},{"text":"Platform Support","anchor":"Platform-Support","level":2,"type":"heading"},{"items":[{"content":[{"inlineContent":[{"type":"strong","inlineContent":[{"text":"Liquid Glass effect","type":"text"}]},{"text":": Requires iOS 26+ and Swift 5.13+","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"text":"Earlier iOS versions","type":"text"}]},{"type":"text","text":": Display standard UIView-based notifications"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Swift versions below 5.13"}]},{"type":"text","text":": Use blurred UIVisualEffectView instead of Liquid Glass"}]}]}],"type":"unorderedList"},{"type":"heading","text":"Testing","level":2,"anchor":"Testing"},{"inlineContent":[{"text":"To test your foreground push integration:","type":"text"}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Verify ","type":"text"},{"type":"codeVoice","code":"Pushwoosh_SHOW_ALERT"},{"text":" is set to ","type":"text"},{"type":"codeVoice","code":"false"},{"text":" in Info.plist","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Build and run your app on a physical device (push notifications don’t work in Simulator)"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Ensure the app has registered for push notifications successfully"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Send a test push notification from Pushwoosh Control Panel"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Keep your app in the foreground when the notification arrives","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Verify the custom foreground push banner appears with the configured animation and haptic feedback"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Tap the notification to verify the delegate method is called"}],"type":"paragraph"}]}],"type":"orderedList"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"text":"Important","type":"text"}]},{"text":": If ","type":"text"},{"code":"Pushwoosh_SHOW_ALERT","type":"codeVoice"},{"type":"text","text":" is not set to "},{"code":"false","type":"codeVoice"},{"text":", native iOS alerts will be shown instead of custom foreground push notifications.","type":"text"}]}],"type":"aside","name":"Note"},{"level":2,"text":"Next Steps","anchor":"Next-Steps","type":"heading"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.pushwoosh.PushwooshForegroundPush\/documentation\/PushwooshForegroundPush\/Examples"},{"type":"text","text":" - Advanced customization with colors, fonts, and animations"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/com.pushwoosh.PushwooshForegroundPush\/documentation\/PushwooshForegroundPush\/PushwooshForegroundPushImplementation","isActive":true,"type":"reference"},{"type":"text","text":" - Full API reference"}]}]},{"content":[{"inlineContent":[{"identifier":"doc:\/\/com.pushwoosh.PushwooshForegroundPush\/documentation\/PushwooshForegroundPush\/PWForegroundPushDelegate","type":"reference","isActive":true},{"type":"text","text":" - Delegate protocol reference"}],"type":"paragraph"}]}]}],"kind":"content"}],"sections":[],"references":{"doc://com.pushwoosh.PushwooshForegroundPush/documentation/PushwooshForegroundPush/PWForegroundPushDelegate":{"title":"PWForegroundPushDelegate","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshForegroundPush\/documentation\/PushwooshForegroundPush\/PWForegroundPushDelegate","navigatorTitle":[{"kind":"identifier","text":"PWForegroundPushDelegate"}],"type":"topic","url":"\/documentation\/pushwooshforegroundpush\/pwforegroundpushdelegate","role":"symbol","abstract":[{"type":"text","text":"Delegate protocol for receiving foreground push events."}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PWForegroundPushDelegate"}]},"doc://com.pushwoosh.PushwooshForegroundPush/documentation/PushwooshForegroundPush":{"role":"collection","abstract":[{"type":"text","text":"Customizable foreground push notifications for iOS applications."}],"title":"PushwooshForegroundPush","identifier":"doc:\/\/com.pushwoosh.PushwooshForegroundPush\/documentation\/PushwooshForegroundPush","type":"topic","kind":"symbol","url":"\/documentation\/pushwooshforegroundpush"},"doc://com.pushwoosh.PushwooshForegroundPush/documentation/PushwooshForegroundPush/Examples":{"title":"Code Examples","kind":"article","identifier":"doc:\/\/com.pushwoosh.PushwooshForegroundPush\/documentation\/PushwooshForegroundPush\/Examples","type":"topic","url":"\/documentation\/pushwooshforegroundpush\/examples","role":"article","abstract":[{"text":"Practical examples for common foreground push notification scenarios.","type":"text"}]},"doc://com.pushwoosh.PushwooshForegroundPush/documentation/PushwooshForegroundPush/PushwooshForegroundPushImplementation":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushwooshForegroundPushImplementation"}],"abstract":[{"text":"Main implementation class that manages foreground push notifications display and configuration.","type":"text"}],"title":"PushwooshForegroundPushImplementation","navigatorTitle":[{"kind":"identifier","text":"PushwooshForegroundPushImplementation"}],"kind":"symbol","url":"\/documentation\/pushwooshforegroundpush\/pushwooshforegroundpushimplementation","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshForegroundPush\/documentation\/PushwooshForegroundPush\/PushwooshForegroundPushImplementation"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/seeAlsoSections","op":"replace","value":[{"generated":true,"identifiers":["doc:\/\/com.pushwoosh.PushwooshForegroundPush\/documentation\/PushwooshForegroundPush\/Examples"],"title":"Getting Started"}]}]}]}