{"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PWTVOSRichMediaManager\/animationType"},"abstract":[{"type":"text","text":"The animation type used when presenting Rich Media."}],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["tvOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"animationType","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@PushwooshBridge@E@PWTVOSRichMediaPresentAnimation","kind":"typeIdentifier","text":"PWTVOSRichMediaPresentAnimation"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/pushwooshtvos\/pwtvosrichmediamanager\/animationtype"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshtvos\/pwtvosrichmediamanager\/animationtype"]}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PWTVOSRichMediaManager"]]},"metadata":{"platforms":[{"unavailable":false,"beta":false,"introducedAt":"11.0","name":"tvOS","deprecated":false}],"title":"animationType","role":"symbol","roleHeading":"Instance Property","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"animationType","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@PushwooshBridge@E@PWTVOSRichMediaPresentAnimation","text":"PWTVOSRichMediaPresentAnimation"}],"navigatorTitle":[{"text":"animationType","kind":"identifier"}],"modules":[{"name":"PushwooshTVOS"}],"externalID":"c:@M@PushwooshTVOS@objc(cs)PWTVOSRichMediaManager(py)animationType"},"sections":[],"references":{"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PWTVOSRichMediaManager":{"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PWTVOSRichMediaManager","url":"\/documentation\/pushwooshtvos\/pwtvosrichmediamanager","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PWTVOSRichMediaManager","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PWTVOSRichMediaManager"}],"title":"PWTVOSRichMediaManager","abstract":[{"text":"Manager for displaying Rich Media content on tvOS.","type":"text"}]},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PWTVOSRichMediaManager/animationType":{"title":"animationType","identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PWTVOSRichMediaManager\/animationType","url":"\/documentation\/pushwooshtvos\/pwtvosrichmediamanager\/animationtype","kind":"symbol","abstract":[{"type":"text","text":"The animation type used when presenting Rich Media."}],"navigatorTitle":[{"text":"animationType","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"animationType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PWTVOSRichMediaPresentAnimation","preciseIdentifier":"c:@M@PushwooshBridge@E@PWTVOSRichMediaPresentAnimation","kind":"typeIdentifier"}],"type":"topic","role":"symbol"},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS":{"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS","kind":"symbol","url":"\/documentation\/pushwooshtvos","role":"collection","title":"PushwooshTVOS","abstract":[{"text":"Push notifications and Rich Media for tvOS apps.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"animationType","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"animationType","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@PushwooshBridge@E@PWTVOSRichMediaPresentAnimation","kind":"typeIdentifier","text":"PWTVOSRichMediaPresentAnimation"},{"kind":"text","text":" "},{"kind":"identifier","text":"animationType"},{"text":";","kind":"text"}],"platforms":["tvOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PWTVOSRichMediaManager\/title","value":"PWTVOSRichMediaManager","op":"replace"},{"op":"replace","value":[{"text":"PWTVOSRichMediaManager","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PWTVOSRichMediaManager\/fragments"},{"value":"animationType","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PWTVOSRichMediaManager~1animationType\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PWTVOSRichMediaManager~1animationType\/fragments","value":[{"kind":"identifier","text":"animationType"}]}]}]}