{"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PWTVOSRichMediaManager\/configureRichMediaWith(position:presentAnimation:dismissAnimation:)","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"configureRichMediaWith","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"position"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"PWTVOSRichMediaPosition","preciseIdentifier":"c:@M@PushwooshBridge@E@PWTVOSRichMediaPosition"},{"text":" = .center, ","kind":"text"},{"text":"presentAnimation","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@PushwooshBridge@E@PWTVOSRichMediaPresentAnimation","text":"PWTVOSRichMediaPresentAnimation"},{"kind":"text","text":", "},{"text":"dismissAnimation","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PWTVOSRichMediaDismissAnimation","preciseIdentifier":"c:@M@PushwooshBridge@E@PWTVOSRichMediaDismissAnimation","kind":"typeIdentifier"},{"text":" = .none)","kind":"text"}],"languages":["swift"],"platforms":["tvOS"]}]},{"kind":"parameters","parameters":[{"name":"position","content":[{"type":"paragraph","inlineContent":[{"text":"Screen position for Rich Media display. Defaults to ","type":"text"},{"code":".center","type":"codeVoice"},{"type":"text","text":"."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Animation when Rich Media appears."}]}],"name":"presentAnimation"},{"name":"dismissAnimation","content":[{"inlineContent":[{"type":"text","text":"Animation when Rich Media disappears. Defaults to "},{"type":"codeVoice","code":".none"},{"type":"text","text":"."}],"type":"paragraph"}]}]}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"externalID":"c:@M@PushwooshTVOS@objc(cs)PWTVOSRichMediaManager(im)configureRichMediaWithPosition:presentAnimation:dismissAnimation:","platforms":[{"unavailable":false,"beta":false,"name":"tvOS","deprecated":false,"introducedAt":"11.0"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"configureRichMediaWith","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"position"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@PushwooshBridge@E@PWTVOSRichMediaPosition","kind":"typeIdentifier","text":"PWTVOSRichMediaPosition"},{"text":", ","kind":"text"},{"text":"presentAnimation","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PWTVOSRichMediaPresentAnimation","preciseIdentifier":"c:@M@PushwooshBridge@E@PWTVOSRichMediaPresentAnimation","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"dismissAnimation"},{"kind":"text","text":": "},{"text":"PWTVOSRichMediaDismissAnimation","kind":"typeIdentifier","preciseIdentifier":"c:@M@PushwooshBridge@E@PWTVOSRichMediaDismissAnimation"},{"text":")","kind":"text"}],"title":"configureRichMediaWith(position:presentAnimation:dismissAnimation:)","roleHeading":"Instance Method","role":"symbol","modules":[{"name":"PushwooshTVOS"}],"symbolKind":"method","navigatorTitle":[{"text":"configureRichMediaWithPosition:presentAnimation:dismissAnimation:","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PWTVOSRichMediaManager"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshtvos\/pwtvosrichmediamanager\/configurerichmediawith(position:presentanimation:dismissanimation:)"]},{"paths":["\/documentation\/pushwooshtvos\/pwtvosrichmediamanager\/configurerichmediawith(position:presentanimation:dismissanimation:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Configures Rich Media presentation settings.","type":"text"}],"references":{"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS":{"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"Push notifications and Rich Media for tvOS apps."}],"url":"\/documentation\/pushwooshtvos","title":"PushwooshTVOS"},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PWTVOSRichMediaManager":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PWTVOSRichMediaManager","role":"symbol","abstract":[{"text":"Manager for displaying Rich Media content on tvOS.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PWTVOSRichMediaManager","kind":"identifier"}],"url":"\/documentation\/pushwooshtvos\/pwtvosrichmediamanager","navigatorTitle":[{"kind":"identifier","text":"PWTVOSRichMediaManager"}],"title":"PWTVOSRichMediaManager"},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PWTVOSRichMediaManager/configureRichMediaWith(position:presentAnimation:dismissAnimation:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"configureRichMediaWith"},{"text":"(","kind":"text"},{"text":"position","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@PushwooshBridge@E@PWTVOSRichMediaPosition","kind":"typeIdentifier","text":"PWTVOSRichMediaPosition"},{"kind":"text","text":", "},{"kind":"externalParam","text":"presentAnimation"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@PushwooshBridge@E@PWTVOSRichMediaPresentAnimation","text":"PWTVOSRichMediaPresentAnimation"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"dismissAnimation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PWTVOSRichMediaDismissAnimation","preciseIdentifier":"c:@M@PushwooshBridge@E@PWTVOSRichMediaDismissAnimation"},{"text":")","kind":"text"}],"abstract":[{"text":"Configures Rich Media presentation settings.","type":"text"}],"title":"configureRichMediaWith(position:presentAnimation:dismissAnimation:)","identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PWTVOSRichMediaManager\/configureRichMediaWith(position:presentAnimation:dismissAnimation:)","url":"\/documentation\/pushwooshtvos\/pwtvosrichmediamanager\/configurerichmediawith(position:presentanimation:dismissanimation:)","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"configureRichMediaWithPosition:presentAnimation:dismissAnimation:"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"configureRichMediaWithPosition:presentAnimation:dismissAnimation:","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"configureRichMediaWithPosition:presentAnimation:dismissAnimation:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"configureRichMediaWithPosition:","kind":"identifier"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@PushwooshBridge@E@PWTVOSRichMediaPosition","text":"PWTVOSRichMediaPosition"},{"kind":"text","text":") "},{"text":"position","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"presentAnimation:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@PushwooshBridge@E@PWTVOSRichMediaPresentAnimation","text":"PWTVOSRichMediaPresentAnimation","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"presentAnimation"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dismissAnimation:"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@PushwooshBridge@E@PWTVOSRichMediaDismissAnimation","text":"PWTVOSRichMediaDismissAnimation","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"dismissAnimation","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["tvOS"]}]},"op":"replace"},{"value":"PWTVOSRichMediaManager","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PWTVOSRichMediaManager\/title"},{"op":"replace","value":[{"text":"PWTVOSRichMediaManager","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PWTVOSRichMediaManager\/fragments"},{"value":"configureRichMediaWithPosition:presentAnimation:dismissAnimation:","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PWTVOSRichMediaManager~1configureRichMediaWith(position:presentAnimation:dismissAnimation:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"configureRichMediaWithPosition:presentAnimation:dismissAnimation:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PWTVOSRichMediaManager~1configureRichMediaWith(position:presentAnimation:dismissAnimation:)\/fragments"}]}]}