{"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PWTVOSRichMediaManager"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshtvos\/pwtvosrichmediamanager\/configureclosebutton(_:)"]},{"paths":["\/documentation\/pushwooshtvos\/pwtvosrichmediamanager\/configureclosebutton(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"title":"configureCloseButton(_:)","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"configureCloseButton","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":")","kind":"text"}],"externalID":"c:@M@PushwooshTVOS@objc(cs)PWTVOSRichMediaManager(im)configureCloseButton:","platforms":[{"introducedAt":"11.0","beta":false,"deprecated":false,"name":"tvOS","unavailable":false}],"navigatorTitle":[{"text":"configureCloseButton:","kind":"identifier"}],"modules":[{"name":"PushwooshTVOS"}],"role":"symbol","roleHeading":"Instance Method"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["tvOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"configureCloseButton","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"show","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"languages":["swift"]}]},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":""},{"code":"true","type":"codeVoice"},{"text":" to show Close button, ","type":"text"},{"code":"false","type":"codeVoice"},{"text":" to hide it.","type":"text"}],"type":"paragraph"}],"name":"show"}],"kind":"parameters"}],"abstract":[{"text":"Controls visibility of the Close button on Rich Media.","type":"text"}],"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PWTVOSRichMediaManager\/configureCloseButton(_:)","interfaceLanguage":"swift"},"references":{"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PWTVOSRichMediaManager/configureCloseButton(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"configureCloseButton"},{"text":"(","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"url":"\/documentation\/pushwooshtvos\/pwtvosrichmediamanager\/configureclosebutton(_:)","title":"configureCloseButton(_:)","type":"topic","abstract":[{"text":"Controls visibility of the Close button on Rich Media.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"configureCloseButton:"}],"kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PWTVOSRichMediaManager\/configureCloseButton(_:)"},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PWTVOSRichMediaManager":{"kind":"symbol","title":"PWTVOSRichMediaManager","abstract":[{"text":"Manager for displaying Rich Media content on tvOS.","type":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PWTVOSRichMediaManager","navigatorTitle":[{"kind":"identifier","text":"PWTVOSRichMediaManager"}],"url":"\/documentation\/pushwooshtvos\/pwtvosrichmediamanager","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PWTVOSRichMediaManager"}],"role":"symbol"},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS":{"kind":"symbol","title":"PushwooshTVOS","identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS","abstract":[{"type":"text","text":"Push notifications and Rich Media for tvOS apps."}],"url":"\/documentation\/pushwooshtvos","type":"topic","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"configureCloseButton:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"configureCloseButton:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"configureCloseButton:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"show"},{"text":";","kind":"text"}],"platforms":["tvOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PWTVOSRichMediaManager~1configureCloseButton(_:)\/title","value":"configureCloseButton:"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PWTVOSRichMediaManager~1configureCloseButton(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"configureCloseButton:","kind":"identifier"}]},{"value":"PWTVOSRichMediaManager","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PWTVOSRichMediaManager\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PWTVOSRichMediaManager\/fragments","value":[{"kind":"identifier","text":"PWTVOSRichMediaManager"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}