{"sections":[],"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PWTVOSRichMediaManager\/dismissAnimationType","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PWTVOSRichMediaManager"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["tvOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"dismissAnimationType","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"PWTVOSRichMediaDismissAnimation","preciseIdentifier":"c:@M@PushwooshBridge@E@PWTVOSRichMediaDismissAnimation"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshtvos\/pwtvosrichmediamanager\/dismissanimationtype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshtvos\/pwtvosrichmediamanager\/dismissanimationtype"]}],"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"dismissAnimationType","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@PushwooshBridge@E@PWTVOSRichMediaDismissAnimation","text":"PWTVOSRichMediaDismissAnimation","kind":"typeIdentifier"}],"externalID":"c:@M@PushwooshTVOS@objc(cs)PWTVOSRichMediaManager(py)dismissAnimationType","modules":[{"name":"PushwooshTVOS"}],"title":"dismissAnimationType","roleHeading":"Instance Property","platforms":[{"deprecated":false,"unavailable":false,"name":"tvOS","introducedAt":"11.0","beta":false}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"dismissAnimationType"}],"symbolKind":"property"},"abstract":[{"text":"The animation type used when dismissing Rich Media.","type":"text"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PWTVOSRichMediaManager/dismissAnimationType":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"dismissAnimationType","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@PushwooshBridge@E@PWTVOSRichMediaDismissAnimation","text":"PWTVOSRichMediaDismissAnimation","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"The animation type used when dismissing Rich Media."}],"type":"topic","title":"dismissAnimationType","identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PWTVOSRichMediaManager\/dismissAnimationType","role":"symbol","url":"\/documentation\/pushwooshtvos\/pwtvosrichmediamanager\/dismissanimationtype","navigatorTitle":[{"kind":"identifier","text":"dismissAnimationType"}]},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PWTVOSRichMediaManager":{"identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PWTVOSRichMediaManager","type":"topic","abstract":[{"text":"Manager for displaying Rich Media content on tvOS.","type":"text"}],"kind":"symbol","url":"\/documentation\/pushwooshtvos\/pwtvosrichmediamanager","title":"PWTVOSRichMediaManager","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PWTVOSRichMediaManager"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PWTVOSRichMediaManager","kind":"identifier"}]},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS":{"identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS","abstract":[{"text":"Push notifications and Rich Media for tvOS apps.","type":"text"}],"type":"topic","kind":"symbol","title":"PushwooshTVOS","url":"\/documentation\/pushwooshtvos","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"dismissAnimationType"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"dismissAnimationType"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["tvOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@PushwooshBridge@E@PWTVOSRichMediaDismissAnimation","text":"PWTVOSRichMediaDismissAnimation","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"dismissAnimationType","kind":"identifier"},{"kind":"text","text":";"}]}]}},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PWTVOSRichMediaManager~1dismissAnimationType\/title","value":"dismissAnimationType","op":"replace"},{"op":"replace","value":[{"text":"dismissAnimationType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PWTVOSRichMediaManager~1dismissAnimationType\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PWTVOSRichMediaManager\/title","value":"PWTVOSRichMediaManager"},{"op":"replace","value":[{"kind":"identifier","text":"PWTVOSRichMediaManager"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PWTVOSRichMediaManager\/fragments"}]}]}