{"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Dismisses currently displayed Rich Media.","type":"text"}],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"dismiss"},{"kind":"text","text":"("},{"text":"animated","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}],"modules":[{"name":"PushwooshTVOS"}],"externalID":"c:@M@PushwooshTVOS@objc(cs)PWTVOSRichMediaManager(im)dismissWithAnimated:","title":"dismiss(animated:)","platforms":[{"deprecated":false,"introducedAt":"11.0","unavailable":false,"beta":false,"name":"tvOS"}],"role":"symbol","navigatorTitle":[{"text":"dismissWithAnimated:","kind":"identifier"}],"symbolKind":"method","roleHeading":"Instance Method"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PWTVOSRichMediaManager"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["tvOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dismiss"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"animated"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":")"}],"languages":["swift"]}]},{"parameters":[{"name":"animated","content":[{"inlineContent":[{"text":"Whether to animate the dismissal.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"}],"variants":[{"paths":["\/documentation\/pushwooshtvos\/pwtvosrichmediamanager\/dismiss(animated:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshtvos\/pwtvosrichmediamanager\/dismiss(animated:)"]}],"sections":[],"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PWTVOSRichMediaManager\/dismiss(animated:)","interfaceLanguage":"swift"},"references":{"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PWTVOSRichMediaManager/dismiss(animated:)":{"navigatorTitle":[{"text":"dismissWithAnimated:","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dismiss"},{"text":"(","kind":"text"},{"text":"animated","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PWTVOSRichMediaManager\/dismiss(animated:)","abstract":[{"text":"Dismisses currently displayed Rich Media.","type":"text"}],"title":"dismiss(animated:)","type":"topic","url":"\/documentation\/pushwooshtvos\/pwtvosrichmediamanager\/dismiss(animated:)","kind":"symbol"},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PWTVOSRichMediaManager":{"navigatorTitle":[{"text":"PWTVOSRichMediaManager","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PWTVOSRichMediaManager","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PWTVOSRichMediaManager","title":"PWTVOSRichMediaManager","abstract":[{"text":"Manager for displaying Rich Media content on tvOS.","type":"text"}],"type":"topic","url":"\/documentation\/pushwooshtvos\/pwtvosrichmediamanager","kind":"symbol"},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS":{"abstract":[{"type":"text","text":"Push notifications and Rich Media for tvOS apps."}],"identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/pushwooshtvos","title":"PushwooshTVOS"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"dismissWithAnimated:","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"dismissWithAnimated:"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["tvOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"dismissWithAnimated:","kind":"identifier"},{"kind":"text","text":"("},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"animated"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PWTVOSRichMediaManager~1dismiss(animated:)\/title","value":"dismissWithAnimated:"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PWTVOSRichMediaManager~1dismiss(animated:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"dismissWithAnimated:","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"PWTVOSRichMediaManager","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PWTVOSRichMediaManager\/title"},{"value":[{"kind":"identifier","text":"PWTVOSRichMediaManager"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PWTVOSRichMediaManager\/fragments"}]}]}