{"variants":[{"paths":["\/documentation\/pushwooshtvos\/pwtvosrichmediamanager\/position"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pushwooshtvos\/pwtvosrichmediamanager\/position"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PWTVOSRichMediaManager\/position","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The screen position where Rich Media will be displayed."}],"metadata":{"role":"symbol","roleHeading":"Instance Property","symbolKind":"property","modules":[{"name":"PushwooshTVOS"}],"navigatorTitle":[{"kind":"identifier","text":"position"}],"platforms":[{"unavailable":false,"deprecated":false,"beta":false,"name":"tvOS","introducedAt":"11.0"}],"externalID":"c:@M@PushwooshTVOS@objc(cs)PWTVOSRichMediaManager(py)position","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"position"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@PushwooshBridge@E@PWTVOSRichMediaPosition","text":"PWTVOSRichMediaPosition","kind":"typeIdentifier"}],"title":"position"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["tvOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"position"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"PWTVOSRichMediaPosition","preciseIdentifier":"c:@M@PushwooshBridge@E@PWTVOSRichMediaPosition"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PWTVOSRichMediaManager"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","sections":[],"references":{"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PWTVOSRichMediaManager":{"navigatorTitle":[{"kind":"identifier","text":"PWTVOSRichMediaManager"}],"title":"PWTVOSRichMediaManager","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PWTVOSRichMediaManager","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PWTVOSRichMediaManager","role":"symbol","abstract":[{"text":"Manager for displaying Rich Media content on tvOS.","type":"text"}],"url":"\/documentation\/pushwooshtvos\/pwtvosrichmediamanager"},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PWTVOSRichMediaManager/position":{"url":"\/documentation\/pushwooshtvos\/pwtvosrichmediamanager\/position","type":"topic","title":"position","identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PWTVOSRichMediaManager\/position","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"position","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PWTVOSRichMediaPosition","preciseIdentifier":"c:@M@PushwooshBridge@E@PWTVOSRichMediaPosition","kind":"typeIdentifier"}],"kind":"symbol","role":"symbol","abstract":[{"text":"The screen position where Rich Media will be displayed.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"position"}]},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS":{"identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS","abstract":[{"text":"Push notifications and Rich Media for tvOS apps.","type":"text"}],"type":"topic","kind":"symbol","role":"collection","title":"PushwooshTVOS","url":"\/documentation\/pushwooshtvos"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"position"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"position"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["tvOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":") ","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"PWTVOSRichMediaPosition","preciseIdentifier":"c:@M@PushwooshBridge@E@PWTVOSRichMediaPosition","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"position","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PWTVOSRichMediaManager\/title","value":"PWTVOSRichMediaManager","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"PWTVOSRichMediaManager"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PWTVOSRichMediaManager\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PWTVOSRichMediaManager~1position\/title","value":"position"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PWTVOSRichMediaManager~1position\/fragments","value":[{"kind":"identifier","text":"position"}]}]}]}