{"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/AdvancedIntegration","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"kind":"content","content":[{"level":2,"text":"Overview","type":"heading","anchor":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This guide covers advanced configuration options including background modes, foreground notifications, logging, custom delegates, lazy initialization, and Info.plist properties."}]},{"level":2,"text":"Background Modes","type":"heading","anchor":"Background-Modes"},{"inlineContent":[{"type":"text","text":"By default, iOS does not allow apps to process push notifications when they are in the background. To enable silent push notifications and background processing, you must enable Background Modes."}],"type":"paragraph"},{"type":"heading","text":"Enable Background Modes in Xcode","level":3,"anchor":"Enable-Background-Modes-in-Xcode"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Open your Xcode project"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Select your app target"}]}]},{"content":[{"inlineContent":[{"text":"Navigate to ","type":"text"},{"type":"strong","inlineContent":[{"text":"Signing & Capabilities","type":"text"}]},{"text":" tab","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Click "},{"inlineContent":[{"text":"+ Capability","type":"text"}],"type":"strong"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Select ","type":"text"},{"type":"strong","inlineContent":[{"text":"Background Modes","type":"text"}]}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Enable "},{"type":"strong","inlineContent":[{"type":"text","text":"Remote notifications"}]},{"text":" checkbox","type":"text"}],"type":"paragraph"}]}],"type":"orderedList"},{"type":"paragraph","inlineContent":[{"text":"This allows your app to:","type":"text"}]},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Process silent push notifications in the background","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Update content when push notifications arrive"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Wake up the app to perform tasks"}],"type":"paragraph"}]}],"type":"unorderedList"},{"level":2,"type":"heading","text":"Foreground Notifications","anchor":"Foreground-Notifications"},{"inlineContent":[{"text":"By default, the SDK displays notification banners while the app is running in the foreground. You can control this behavior programmatically.","type":"text"}],"type":"paragraph"},{"level":3,"anchor":"Control-Foreground-Alert-Display","text":"Control Foreground Alert Display","type":"heading"},{"type":"tabNavigator","tabs":[{"content":[{"type":"codeListing","syntax":"swift","code":["\/\/ Enable foreground notifications","Pushwoosh.sharedInstance().showPushnotificationAlert = true","","\/\/ Disable foreground notifications","Pushwoosh.sharedInstance().showPushnotificationAlert = false"]}],"title":"Swift"},{"content":[{"syntax":"objc","code":["\/\/ Enable foreground notifications","[[Pushwoosh sharedInstance] setShowPushnotificationAlert:1];","","\/\/ Disable foreground notifications","[[Pushwoosh sharedInstance] setShowPushnotificationAlert:0];"],"type":"codeListing"}],"title":"Objective-C"}]},{"type":"heading","level":2,"text":"Logging","anchor":"Logging"},{"inlineContent":[{"type":"text","text":"The SDK provides multiple logging levels to help debug integration issues and monitor SDK behavior."}],"type":"paragraph"},{"level":3,"anchor":"Available-Log-Levels","type":"heading","text":"Available Log Levels"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"NONE"}]},{"type":"text","text":" - No logging"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"ERROR"}]},{"text":" - Only errors","type":"text"}]}]},{"content":[{"inlineContent":[{"inlineContent":[{"type":"text","text":"WARNING"}],"type":"strong"},{"text":" - Errors and warnings","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"strong","inlineContent":[{"text":"INFO","type":"text"}]},{"type":"text","text":" - Default level, informational messages"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"inlineContent":[{"text":"DEBUG","type":"text"}],"type":"strong"},{"type":"text","text":" - Detailed debug information"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"inlineContent":[{"type":"text","text":"VERBOSE"}],"type":"strong"},{"type":"text","text":" - All possible logging"}],"type":"paragraph"}]}]},{"type":"heading","anchor":"Configure-Logging-via-Infoplist","level":3,"text":"Configure Logging via Info.plist"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Add the following key to your "},{"type":"codeVoice","code":"Info.plist"},{"text":":","type":"text"}]},{"code":["<key>Pushwoosh_LOG_LEVEL<\/key>","<string>DEBUG<\/string>"],"syntax":"xml","type":"codeListing"},{"text":"Configure Logging Programmatically","level":3,"anchor":"Configure-Logging-Programmatically","type":"heading"},{"tabs":[{"content":[{"type":"codeListing","syntax":"swift","code":["Pushwoosh.debug.setLogLevel(.PW_LL_DEBUG)"]},{"inlineContent":[{"type":"text","text":"Available log levels:"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"codeVoice","code":".PW_LL_NONE"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"code":".PW_LL_ERROR","type":"codeVoice"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":".PW_LL_WARNING"}]}]},{"content":[{"inlineContent":[{"type":"codeVoice","code":".PW_LL_INFO"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":".PW_LL_DEBUG"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"code":".PW_LL_VERBOSE","type":"codeVoice"}]}]}]}],"title":"Swift"},{"content":[{"syntax":"objc","type":"codeListing","code":["[Pushwoosh.debug setLogLevel:PW_LL_DEBUG];"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Available log levels:"}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"code":"PW_LL_NONE","type":"codeVoice"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"PW_LL_ERROR"}]}]},{"content":[{"inlineContent":[{"type":"codeVoice","code":"PW_LL_WARNING"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"code":"PW_LL_INFO","type":"codeVoice"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"PW_LL_DEBUG"}]}]},{"content":[{"inlineContent":[{"type":"codeVoice","code":"PW_LL_VERBOSE"}],"type":"paragraph"}]}]}],"title":"Objective-C"}],"type":"tabNavigator"},{"level":2,"text":"Custom UNNotificationCenterDelegate","type":"heading","anchor":"Custom-UNNotificationCenterDelegate"},{"inlineContent":[{"type":"text","text":"If you need to implement custom notification handling alongside Pushwoosh, you can register additional delegates through the notification center delegate proxy."}],"type":"paragraph"},{"type":"heading","text":"Register Custom Delegate","anchor":"Register-Custom-Delegate","level":3},{"type":"tabNavigator","tabs":[{"title":"Swift","content":[{"type":"codeListing","syntax":"swift","code":["Pushwoosh.sharedInstance()?.notificationCenterDelegateProxy.add(myDelegate)"]}]},{"title":"Objective-C","content":[{"type":"codeListing","syntax":"objc","code":["[Pushwoosh.sharedInstance.notificationCenterDelegateProxy","    addNotificationCenterDelegate:myDelegate];"]}]}]},{"type":"heading","level":3,"anchor":"Implement-Delegate-Methods","text":"Implement Delegate Methods"},{"inlineContent":[{"type":"text","text":"Use "},{"type":"codeVoice","code":"PWMessage.isPushwooshMessage()"},{"text":" to check if the notification is from Pushwoosh and handle only non-Pushwoosh notifications in your custom delegate.","type":"text"}],"type":"paragraph"},{"tabs":[{"content":[{"code":["func userNotificationCenter(","    _ center: UNUserNotificationCenter,","    willPresent notification: UNNotification,","    withCompletionHandler completionHandler: @escaping (UNNotificationPresentationOptions) -> Void",") {","    \/\/ Only handle non-Pushwoosh notifications","    if !PWMessage.isPushwooshMessage(notification.request.content.userInfo) {","        completionHandler([.alert, .sound])","    }","}","","func userNotificationCenter(","    _ center: UNUserNotificationCenter,","    didReceive response: UNNotificationResponse,","    withCompletionHandler completionHandler: @escaping () -> Void",") {","    \/\/ Only handle non-Pushwoosh notifications","    if !PWMessage.isPushwooshMessage(response.notification.request.content.userInfo) {","        \/\/ Handle your custom notification","        completionHandler()","    }","}"],"type":"codeListing","syntax":"swift"}],"title":"Swift"},{"content":[{"code":["- (void)userNotificationCenter:(UNUserNotificationCenter *)center","        willPresentNotification:(UNNotification *)notification","        withCompletionHandler:(void (^)(UNNotificationPresentationOptions))completionHandler {","    \/\/ Only handle non-Pushwoosh notifications","    if (![PWMessage isPushwooshMessage:notification.request.content.userInfo]) {","        completionHandler(UNNotificationPresentationOptionAlert | UNNotificationPresentationOptionSound);","    }","}","","- (void)userNotificationCenter:(UNUserNotificationCenter *)center","        didReceiveNotificationResponse:(UNNotificationResponse *)response","        withCompletionHandler:(void (^)(void))completionHandler {","    \/\/ Only handle non-Pushwoosh notifications","    if (![PWMessage isPushwooshMessage:response.notification.request.content.userInfo]) {","        \/\/ Handle your custom notification","        completionHandler();","    }","}"],"syntax":"objc","type":"codeListing"}],"title":"Objective-C"}],"type":"tabNavigator"},{"anchor":"Lazy-Initialization","level":2,"text":"Lazy Initialization","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"By default, the Pushwoosh SDK initializes automatically when the app launches. Lazy initialization allows you to delay SDK startup until explicitly called.","type":"text"}]},{"inlineContent":[{"type":"text","text":"This is useful when:"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"You need to obtain user consent before initializing the SDK"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"You want conditional initialization based on user preferences"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"You need to configure settings before SDK starts"}],"type":"paragraph"}]}]},{"anchor":"Enable-Lazy-Initialization","type":"heading","level":3,"text":"Enable Lazy Initialization"},{"type":"paragraph","inlineContent":[{"text":"Add the following key to your ","type":"text"},{"code":"Info.plist","type":"codeVoice"},{"type":"text","text":":"}]},{"code":["<key>Pushwoosh_LAZY_INITIALIZATION<\/key>","<true\/>"],"type":"codeListing","syntax":"xml"},{"type":"paragraph","inlineContent":[{"type":"text","text":"With this flag enabled, the SDK will not start automatically. Services will only activate when you explicitly call Pushwoosh SDK methods, such as:"}]},{"type":"tabNavigator","tabs":[{"content":[{"syntax":"swift","code":["Pushwoosh.sharedInstance().registerForPushNotifications()"],"type":"codeListing"}],"title":"Swift"},{"content":[{"type":"codeListing","syntax":"objc","code":["[[Pushwoosh sharedInstance] registerForPushNotifications];"]}],"title":"Objective-C"}]},{"type":"heading","level":2,"anchor":"Infoplist-Configuration-Properties","text":"Info.plist Configuration Properties"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The SDK supports multiple configuration options through "},{"type":"codeVoice","code":"Info.plist"},{"type":"text","text":" keys."}]},{"type":"heading","level":3,"text":"Application Configuration","anchor":"Application-Configuration"},{"rows":[[[{"type":"paragraph","inlineContent":[{"text":"Key","type":"text"}]}],[{"inlineContent":[{"type":"text","text":"Type"}],"type":"paragraph"}],[{"inlineContent":[{"text":"Description","type":"text"}],"type":"paragraph"}],[{"inlineContent":[{"type":"text","text":"Default"}],"type":"paragraph"}]],[[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"Pushwoosh_APPID"}]}],[{"inlineContent":[{"type":"text","text":"String"}],"type":"paragraph"}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"Production app ID from Pushwoosh Control Panel"}]}],[{"type":"paragraph","inlineContent":[{"text":"Required","type":"text"}]}]],[[{"inlineContent":[{"code":"Pushwoosh_APPID_Dev","type":"codeVoice"}],"type":"paragraph"}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"String"}]}],[{"inlineContent":[{"text":"Development app ID for testing","type":"text"}],"type":"paragraph"}],[{"type":"paragraph","inlineContent":[{"text":"Optional","type":"text"}]}]]],"header":"row","type":"table"},{"level":3,"type":"heading","text":"Notification Settings","anchor":"Notification-Settings"},{"type":"table","header":"row","rows":[[[{"type":"paragraph","inlineContent":[{"text":"Key","type":"text"}]}],[{"inlineContent":[{"type":"text","text":"Type"}],"type":"paragraph"}],[{"inlineContent":[{"text":"Description","type":"text"}],"type":"paragraph"}],[{"inlineContent":[{"text":"Default","type":"text"}],"type":"paragraph"}]],[[{"inlineContent":[{"type":"codeVoice","code":"Pushwoosh_SHOW_ALERT"}],"type":"paragraph"}],[{"inlineContent":[{"text":"Boolean","type":"text"}],"type":"paragraph"}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"Shows notification foreground alert"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"YES"}]}]],[[{"inlineContent":[{"code":"Pushwoosh_ALERT_TYPE","type":"codeVoice"}],"type":"paragraph"}],[{"inlineContent":[{"type":"text","text":"String"}],"type":"paragraph"}],[{"type":"paragraph","inlineContent":[{"text":"Sets notification alert style: BANNER, ALERT, or NONE","type":"text"}]}],[{"inlineContent":[{"type":"text","text":"BANNER"}],"type":"paragraph"}]],[[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"Pushwoosh_AUTO_ACCEPT_DEEP_LINK_FOR_SILENT_PUSH"}]}],[{"inlineContent":[{"text":"Boolean","type":"text"}],"type":"paragraph"}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"Deep links in silent pushes process automatically"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"YES"}]}]]]},{"level":3,"text":"Network Configuration","type":"heading","anchor":"Network-Configuration"},{"rows":[[[{"type":"paragraph","inlineContent":[{"text":"Key","type":"text"}]}],[{"type":"paragraph","inlineContent":[{"text":"Type","type":"text"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"Description"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"Default"}]}]],[[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"Pushwoosh_BASEURL"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"String"}]}],[{"type":"paragraph","inlineContent":[{"text":"Overrides the Pushwoosh server base URL","type":"text"}]}],[{"type":"paragraph","inlineContent":[{"text":"https:\/\/cp.pushwoosh.com\/json\/1.3\/","type":"text"}]}]],[[{"inlineContent":[{"type":"codeVoice","code":"Pushwoosh_ALLOW_SERVER_COMMUNICATION"}],"type":"paragraph"}],[{"inlineContent":[{"type":"text","text":"Boolean"}],"type":"paragraph"}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"Allows SDK to send network requests to Pushwoosh"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"YES"}]}]]],"header":"row","type":"table"},{"text":"Data Collection Settings","level":3,"type":"heading","anchor":"Data-Collection-Settings"},{"rows":[[[{"inlineContent":[{"text":"Key","type":"text"}],"type":"paragraph"}],[{"type":"paragraph","inlineContent":[{"text":"Type","type":"text"}]}],[{"inlineContent":[{"type":"text","text":"Description"}],"type":"paragraph"}],[{"inlineContent":[{"type":"text","text":"Default"}],"type":"paragraph"}]],[[{"inlineContent":[{"type":"codeVoice","code":"Pushwoosh_ALLOW_COLLECTING_DEVICE_DATA"}],"type":"paragraph"}],[{"inlineContent":[{"text":"Boolean","type":"text"}],"type":"paragraph"}],[{"type":"paragraph","inlineContent":[{"text":"Allows SDK to collect and send device data","type":"text"}]}],[{"inlineContent":[{"type":"text","text":"YES"}],"type":"paragraph"}]],[[{"type":"paragraph","inlineContent":[{"code":"Pushwoosh_ALLOW_COLLECTING_DEVICE_OS_VERSION","type":"codeVoice"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"Boolean"}]}],[{"inlineContent":[{"text":"Device OS version collection permission","type":"text"}],"type":"paragraph"}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"YES"}]}]],[[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"Pushwoosh_ALLOW_COLLECTING_DEVICE_LOCALE"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"Boolean"}]}],[{"inlineContent":[{"text":"Device locale collection permission","type":"text"}],"type":"paragraph"}],[{"inlineContent":[{"type":"text","text":"YES"}],"type":"paragraph"}]],[[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"Pushwoosh_ALLOW_COLLECTING_DEVICE_MODEL"}]}],[{"inlineContent":[{"type":"text","text":"Boolean"}],"type":"paragraph"}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"Device model collection permission"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"YES"}]}]]],"type":"table","header":"row"},{"text":"Feature Toggles","level":3,"anchor":"Feature-Toggles","type":"heading"},{"header":"row","type":"table","rows":[[[{"inlineContent":[{"type":"text","text":"Key"}],"type":"paragraph"}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"Type"}]}],[{"inlineContent":[{"text":"Description","type":"text"}],"type":"paragraph"}],[{"inlineContent":[{"text":"Default","type":"text"}],"type":"paragraph"}]],[[{"type":"paragraph","inlineContent":[{"code":"Pushwoosh_LOG_LEVEL","type":"codeVoice"}]}],[{"inlineContent":[{"type":"text","text":"String"}],"type":"paragraph"}],[{"inlineContent":[{"text":"SDK logging level: NONE, ERROR, WARNING, INFO, DEBUG, VERBOSE","type":"text"}],"type":"paragraph"}],[{"inlineContent":[{"text":"INFO","type":"text"}],"type":"paragraph"}]],[[{"type":"paragraph","inlineContent":[{"code":"Pushwoosh_PURCHASE_TRACKING_ENABLED","type":"codeVoice"}]}],[{"type":"paragraph","inlineContent":[{"text":"Boolean","type":"text"}]}],[{"type":"paragraph","inlineContent":[{"text":"In-app purchase tracking for customer journeys","type":"text"}]}],[{"inlineContent":[{"text":"NO","type":"text"}],"type":"paragraph"}]],[[{"inlineContent":[{"type":"codeVoice","code":"Pushwoosh_LAZY_INITIALIZATION"}],"type":"paragraph"}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"Boolean"}]}],[{"inlineContent":[{"text":"Delays SDK startup until explicitly called","type":"text"}],"type":"paragraph"}],[{"type":"paragraph","inlineContent":[{"text":"NO","type":"text"}]}]]]},{"level":3,"type":"heading","anchor":"Example-Infoplist-Configuration","text":"Example Info.plist Configuration"},{"code":["<?xml version=\"1.0\" encoding=\"UTF-8\"?>","<!DOCTYPE plist PUBLIC \"-\/\/Apple\/\/DTD PLIST 1.0\/\/EN\" \"http:\/\/www.apple.com\/DTDs\/PropertyList-1.0.dtd\">","<plist version=\"1.0\">","<dict>","    <!-- Required: Your Pushwoosh Application ID -->","    <key>Pushwoosh_APPID<\/key>","    <string>XXXXX-XXXXX<\/string>","","    <!-- Optional: Development Application ID -->","    <key>Pushwoosh_APPID_Dev<\/key>","    <string>YYYYY-YYYYY<\/string>","","    <!-- Show notifications in foreground -->","    <key>Pushwoosh_SHOW_ALERT<\/key>","    <true\/>","","    <!-- Set logging level -->","    <key>Pushwoosh_LOG_LEVEL<\/key>","    <string>DEBUG<\/string>","","    <!-- Enable lazy initialization -->","    <key>Pushwoosh_LAZY_INITIALIZATION<\/key>","    <true\/>","","    <!-- Enable purchase tracking -->","    <key>Pushwoosh_PURCHASE_TRACKING_ENABLED<\/key>","    <true\/>","<\/dict>","<\/plist>"],"type":"codeListing","syntax":"xml"},{"anchor":"Best-Practices","text":"Best Practices","type":"heading","level":2},{"text":"1. Use Appropriate Log Levels","anchor":"1-Use-Appropriate-Log-Levels","type":"heading","level":3},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Production"}]},{"type":"text","text":": Use "},{"code":"INFO","type":"codeVoice"},{"text":" or ","type":"text"},{"code":"WARNING","type":"codeVoice"},{"text":" level","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"inlineContent":[{"type":"text","text":"Development"}],"type":"strong"},{"type":"text","text":": Use "},{"type":"codeVoice","code":"DEBUG"},{"type":"text","text":" or "},{"type":"codeVoice","code":"VERBOSE"},{"text":" level","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Release"}]},{"type":"text","text":": Consider using "},{"code":"ERROR","type":"codeVoice"},{"text":" or ","type":"text"},{"type":"codeVoice","code":"NONE"},{"type":"text","text":" to minimize log output"}]}]}],"type":"unorderedList"},{"anchor":"2-Background-Modes","level":3,"type":"heading","text":"2. Background Modes"},{"inlineContent":[{"type":"text","text":"Always enable Background Modes if you plan to:"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"Send silent push notifications"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Update app content in the background"}]}]},{"content":[{"inlineContent":[{"text":"Track notification delivery rates accurately","type":"text"}],"type":"paragraph"}]}]},{"text":"3. Custom Delegates","anchor":"3-Custom-Delegates","type":"heading","level":3},{"inlineContent":[{"text":"When implementing custom ","type":"text"},{"code":"UNNotificationCenterDelegate","type":"codeVoice"},{"type":"text","text":":"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"text":"Always check ","type":"text"},{"type":"codeVoice","code":"PWMessage.isPushwooshMessage()"},{"type":"text","text":" first"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Handle only non-Pushwoosh notifications in your custom code"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Let Pushwoosh SDK handle its own notifications automatically","type":"text"}]}]}]},{"text":"4. Lazy Initialization","level":3,"anchor":"4-Lazy-Initialization","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"Use lazy initialization when:","type":"text"}]},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"You need to comply with privacy regulations (GDPR, CCPA)","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"User consent is required before collecting data"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"You want to delay SDK initialization for performance reasons"}]}]}],"type":"unorderedList"},{"type":"heading","level":3,"text":"5. Data Collection","anchor":"5-Data-Collection"},{"inlineContent":[{"type":"text","text":"Configure data collection settings based on your privacy policy:"}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Disable unnecessary data collection","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Document what data you collect in your privacy policy"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Provide users with opt-out options if required","type":"text"}]}]}],"type":"unorderedList"},{"text":"Troubleshooting","anchor":"Troubleshooting","level":2,"type":"heading"},{"text":"Background Notifications Not Working","type":"heading","anchor":"Background-Notifications-Not-Working","level":3},{"type":"paragraph","inlineContent":[{"text":"Check:","type":"text"}]},{"type":"orderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Background Modes capability is enabled","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Remote notifications checkbox is checked"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Silent push notification flag is set in the notification payload"}]}]},{"content":[{"inlineContent":[{"text":"App is not force-quit by the user","type":"text"}],"type":"paragraph"}]}]},{"type":"heading","text":"Foreground Notifications Not Appearing","anchor":"Foreground-Notifications-Not-Appearing","level":3},{"type":"paragraph","inlineContent":[{"text":"Verify:","type":"text"}]},{"items":[{"content":[{"inlineContent":[{"code":"showPushnotificationAlert","type":"codeVoice"},{"type":"text","text":" is set to "},{"type":"codeVoice","code":"true"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"codeVoice","code":"Pushwoosh_SHOW_ALERT"},{"text":" is ","type":"text"},{"type":"codeVoice","code":"YES"},{"text":" in Info.plist","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Notification permissions are granted"}],"type":"paragraph"}]}],"type":"orderedList"},{"anchor":"Custom-Delegate-Not-Called","text":"Custom Delegate Not Called","level":3,"type":"heading"},{"type":"paragraph","inlineContent":[{"text":"Ensure:","type":"text"}]},{"items":[{"content":[{"inlineContent":[{"type":"text","text":"Delegate is registered via "},{"type":"codeVoice","code":"notificationCenterDelegateProxy"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"You’re checking ","type":"text"},{"type":"codeVoice","code":"isPushwooshMessage()"},{"type":"text","text":" correctly"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Delegate is not deallocated (use strong reference)"}]}]}],"type":"orderedList"},{"level":2,"anchor":"Next-Steps","type":"heading","text":"Next Steps"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"Configure user segmentation with tags"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Set up rich media notifications"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Implement deep linking"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Enable in-app messaging"}]}]}]}]}],"abstract":[{"type":"text","text":"Advanced configuration options for Pushwoosh iOS SDK integration."}],"kind":"article","metadata":{"roleHeading":"Article","role":"article","title":"Advanced Integration Guide","modules":[{"name":"PushwooshFramework"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"seeAlsoSections":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/QuickStart","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/GettingStarted"],"generated":true,"title":"Getting Started"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/advancedintegration"]},{"paths":["\/documentation\/pushwooshframework\/advancedintegration"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh"]]},"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/GettingStarted":{"role":"article","type":"topic","url":"\/documentation\/pushwooshframework\/gettingstarted","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/GettingStarted","title":"Getting Started","abstract":[{"text":"Set up push notifications in your iOS application with Pushwoosh SDK.","type":"text"}],"kind":"article"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/QuickStart":{"role":"article","type":"topic","url":"\/documentation\/pushwooshframework\/quickstart","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/QuickStart","title":"Quick Start","abstract":[{"text":"Get your first push notification running in minutes.","type":"text"}],"kind":"article"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Pushwoosh","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh","abstract":[{"type":"text","text":"Main SDK interface for push notification management."}],"navigatorTitle":[{"text":"Pushwoosh","kind":"identifier"}],"url":"\/documentation\/pushwooshframework\/pushwoosh","title":"Pushwoosh","type":"topic","role":"symbol"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","type":"topic","kind":"symbol","abstract":[],"title":"PushwooshFramework","url":"\/documentation\/pushwooshframework"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"generated":true,"title":"Getting Started","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/QuickStart","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/GettingStarted"]}]},{"value":"Pushwoosh","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh\/title"},{"value":[{"kind":"identifier","text":"Pushwoosh"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}