{"kind":"article","seeAlsoSections":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/QuickStart","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/AdvancedIntegration"],"generated":true,"title":"Getting Started"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/gettingstarted"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/gettingstarted"]}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"metadata":{"modules":[{"name":"PushwooshFramework"}],"role":"article","title":"Getting Started","roleHeading":"Article"},"abstract":[{"text":"Set up push notifications in your iOS application with Pushwoosh SDK.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/GettingStarted"},"primaryContentSections":[{"content":[{"type":"heading","text":"Overview","anchor":"Overview","level":2},{"inlineContent":[{"type":"text","text":"This guide walks through the steps to integrate Pushwoosh SDK into your iOS application and send your first push notification."}],"type":"paragraph"},{"text":"Prerequisites","level":2,"anchor":"Prerequisites","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"Before you begin, make sure you have:","type":"text"}]},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"A Pushwoosh account and application created","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Apple Developer account with push notification certificate configured","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Xcode 14.0 or later"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"iOS deployment target 11.0 or later"}]}]}],"type":"unorderedList"},{"type":"heading","level":2,"text":"Installation","anchor":"Installation"},{"tabs":[{"title":"CocoaPods","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Add Pushwoosh to your "},{"code":"Podfile","type":"codeVoice"},{"type":"text","text":":"}]},{"syntax":"ruby","type":"codeListing","code":["pod 'PushwooshXCFramework'"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Then run:"}]},{"code":["pod install"],"type":"codeListing","syntax":"bash"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"In Xcode, use the following URL to add the Pushwoosh dependency:","type":"text"}]},{"type":"codeListing","syntax":null,"code":["https:\/\/github.com\/Pushwoosh\/Pushwoosh-XCFramework"]}],"title":"Swift Package Manager"}],"type":"tabNavigator"},{"text":"Configuration","type":"heading","level":2,"anchor":"Configuration"},{"type":"heading","text":"1. Import the SDK","level":3,"anchor":"1-Import-the-SDK"},{"tabs":[{"title":"Swift","content":[{"type":"codeListing","code":["import PushwooshFramework"],"syntax":"swift"}]},{"title":"Objective-C","content":[{"syntax":"objc","code":["#import <PushwooshFramework\/PushwooshFramework.h>"],"type":"codeListing"}]}],"type":"tabNavigator"},{"level":3,"type":"heading","anchor":"2-Initialize-in-AppDelegate","text":"2. Initialize in AppDelegate"},{"code":["func application(_ application: UIApplication,","                didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {","","    Pushwoosh.configure.registerForPushNotifications()","","    return true","}"],"syntax":"swift","type":"codeListing"},{"level":3,"anchor":"3-Handle-Push-Notifications","text":"3. Handle Push Notifications","type":"heading"},{"inlineContent":[{"text":"Implement ","type":"text"},{"code":"PWMessagingDelegate","type":"codeVoice"},{"text":" to receive push notification events:","type":"text"}],"type":"paragraph"},{"syntax":"swift","type":"codeListing","code":["class AppDelegate: UIResponder, UIApplicationDelegate, PWMessagingDelegate {","","    func application(_ application: UIApplication,","                    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {","","        Pushwoosh.configure.delegate = self","        Pushwoosh.configure.registerForPushNotifications()","","        return true","    }","","    func pushwoosh(_ pushwoosh: Pushwoosh, onMessageReceived message: PWMessage) {","        print(\"Push notification received: \\(message.payload)\")","    }","","    func pushwoosh(_ pushwoosh: Pushwoosh, onMessageOpened message: PWMessage) {","        print(\"Push notification opened: \\(message.payload)\")","    }","}"]},{"text":"4. Add Push Notification Capability","anchor":"4-Add-Push-Notification-Capability","level":3,"type":"heading"},{"inlineContent":[{"type":"text","text":"In Xcode:"}],"type":"paragraph"},{"type":"orderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Select your target"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Go to “Signing & Capabilities”"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Click “+ Capability”"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Add “Push Notifications”"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Click “+ Capability” again","type":"text"}]}]},{"content":[{"inlineContent":[{"text":"Add “Background Modes”","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Check “Remote notifications” in Background Modes"}],"type":"paragraph"}]}]},{"level":2,"type":"heading","text":"Send Your First Push","anchor":"Send-Your-First-Push"},{"type":"orderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"Go to Pushwoosh Control Panel"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"Navigate to your application","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Click “Create Message”"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Enter your notification content"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Click “Send”"}],"type":"paragraph"}]}]},{"inlineContent":[{"text":"Your device should receive the push notification!","type":"text"}],"type":"paragraph"},{"type":"heading","level":2,"text":"Next Steps","anchor":"Next-Steps"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/AdvancedIntegration","isActive":true},{"type":"text","text":" - Learn about advanced integration options"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Configure user segmentation with tags"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Set up rich media notifications"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Enable inbox functionality","type":"text"}]}]}]},{"text":"Troubleshooting","level":2,"anchor":"Troubleshooting","type":"heading"},{"level":3,"text":"Device Not Registered","type":"heading","anchor":"Device-Not-Registered"},{"type":"paragraph","inlineContent":[{"text":"Make sure:","type":"text"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Push notification capability is enabled","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"APNs certificate is correctly configured"}]}]},{"content":[{"inlineContent":[{"text":"App has permission to receive notifications","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Device token is successfully sent to Pushwoosh","type":"text"}]}]}]},{"text":"Notifications Not Received","anchor":"Notifications-Not-Received","level":3,"type":"heading"},{"inlineContent":[{"type":"text","text":"Check:"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"text":"Device is registered in Pushwoosh Control Panel","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Notification is sent to correct audience segment","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"App is not in Do Not Disturb mode","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Enable SDK logging with "},{"code":"Pushwoosh.debug.setLogLevel(.PW_LL_VERBOSE)","type":"codeVoice"}]}]}]}],"kind":"content"}],"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","title":"PushwooshFramework","abstract":[{"text":"Push notification SDK for iOS applications.","type":"text"}],"role":"collection","url":"\/documentation\/pushwooshframework"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/QuickStart":{"role":"article","kind":"article","abstract":[{"type":"text","text":"Get your first push notification running in minutes."}],"url":"\/documentation\/pushwooshframework\/quickstart","title":"Quick Start","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/QuickStart","type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/AdvancedIntegration":{"title":"Advanced Integration Guide","role":"article","url":"\/documentation\/pushwooshframework\/advancedintegration","abstract":[{"text":"Advanced configuration options for Pushwoosh iOS SDK integration.","type":"text"}],"type":"topic","kind":"article","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/AdvancedIntegration"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/seeAlsoSections","value":[{"title":"Getting Started","generated":true,"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/QuickStart","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/AdvancedIntegration"]}],"op":"replace"}]}]}