{"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Completion handler called when an operation fails.","type":"text"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PushwooshErrorHandler","kind":"identifier"},{"text":" = ((any ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")?) -> "},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"}]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Discussion","level":2,"anchor":"Discussion","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This closure is called when a Pushwoosh operation fails, providing an error object describing what went wrong."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"The handler receives an optional "},{"type":"codeVoice","code":"NSError"},{"text":" parameter. If the error is ","type":"text"},{"type":"codeVoice","code":"nil"},{"type":"text","text":", the operation succeeded (though typically success handlers use different callback types)."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Use this handler to respond to failures appropriately, such as displaying error messages to users, logging errors, or retrying operations."}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pushwoosherrorhandler"]},{"paths":["\/documentation\/pushwooshframework\/pushwoosherrorhandler"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushwooshErrorHandler","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"PushwooshFramework"}],"title":"PushwooshErrorHandler","symbolKind":"typealias","navigatorTitle":[{"text":"PushwooshErrorHandler","kind":"identifier"}],"roleHeading":"Type Alias","role":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushwooshErrorHandler"}],"externalID":"c:PushNotificationManager.h@T@PushwooshErrorHandler"},"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushwooshErrorHandler":{"title":"PushwooshErrorHandler","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushwooshErrorHandler","kind":"symbol","abstract":[{"text":"Completion handler called when an operation fails.","type":"text"}],"url":"\/documentation\/pushwooshframework\/pushwoosherrorhandler","navigatorTitle":[{"text":"PushwooshErrorHandler","kind":"identifier"}],"role":"symbol","type":"topic","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushwooshErrorHandler"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","title":"PushwooshFramework","url":"\/documentation\/pushwooshframework","kind":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Alias"},{"op":"replace","path":"\/metadata\/title","value":"PushwooshErrorHandler"},{"value":"typealias","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"PushwooshErrorHandler"}],"path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"PushwooshErrorHandler","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"typedef","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","text":"void (^)(NSError *)","preciseIdentifier":"c:BFv(#*$objc(cs)NSError)"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PushwooshErrorHandler"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"PushwooshErrorHandler","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushwooshErrorHandler\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushwooshErrorHandler\/fragments","value":[{"text":"PushwooshErrorHandler","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}