{"kind":"symbol","metadata":{"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PushwooshGetTagsHandler"}],"navigatorTitle":[{"text":"PushwooshGetTagsHandler","kind":"identifier"}],"title":"PushwooshGetTagsHandler","modules":[{"name":"PushwooshFramework"}],"role":"symbol","symbolKind":"typealias","roleHeading":"Type Alias","externalID":"c:PushNotificationManager.h@T@PushwooshGetTagsHandler"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushwooshGetTagsHandler"},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"]]},"sections":[],"abstract":[{"type":"text","text":"Completion handler called when tags are successfully retrieved from the server."}],"variants":[{"paths":["\/documentation\/pushwooshframework\/pushwooshgettagshandler"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pushwooshgettagshandler"]}],"seeAlsoSections":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushwooshErrorHandler","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/getTags(_:onFailure:)"],"title":"Related Documentation"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PushwooshGetTagsHandler"},{"text":" = ([","kind":"text"},{"text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"text":"]?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"}],"platforms":["iOS"]}]},{"kind":"content","content":[{"type":"heading","text":"Overview","level":2,"anchor":"Overview"},{"type":"paragraph","inlineContent":[{"text":"This closure is called when the ","type":"text"},{"code":"getTags:onFailure:","type":"codeVoice"},{"text":" method successfully retrieves device tags from Pushwoosh servers.","type":"text"}]},{"inlineContent":[{"text":"The handler receives a dictionary where keys are tag names and values are the corresponding tag values. The dictionary can contain various types including strings, numbers, booleans, dates, and arrays.","type":"text"}],"type":"paragraph"},{"type":"heading","level":2,"text":"Example","anchor":"Example"},{"inlineContent":[{"type":"text","text":"Sync user preferences from Pushwoosh tags:"}],"type":"paragraph"},{"code":["func loadUserPreferences() {","    let successHandler: PushwooshGetTagsHandler = { tags in","        guard let tags = tags else { return }","","        if let subscriptionTier = tags[\"subscription_tier\"] as? String {","            self.userSettings.subscriptionTier = subscriptionTier","        }","","        if let favoriteCategories = tags[\"favorite_categories\"] as? [String] {","            self.userSettings.favoriteCategories = favoriteCategories","        }","","        if let notificationsEnabled = tags[\"notifications_enabled\"] as? Bool {","            self.userSettings.notificationsEnabled = notificationsEnabled","        }","","        self.refreshUI()","    }","","    let errorHandler: PushwooshErrorHandler = { error in","        self.logger.error(\"Failed to load preferences: \\(error?.localizedDescription ?? \"Unknown error\")\")","    }","","    Pushwoosh.configure.getTags(successHandler, onFailure: errorHandler)","}"],"type":"codeListing","syntax":"swift"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushwooshErrorHandler":{"navigatorTitle":[{"kind":"identifier","text":"PushwooshErrorHandler"}],"type":"topic","title":"PushwooshErrorHandler","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushwooshErrorHandler","url":"\/documentation\/pushwooshframework\/pushwoosherrorhandler","kind":"symbol","abstract":[{"text":"Completion handler called when an operation fails.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushwooshErrorHandler"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"kind":"symbol","type":"topic","abstract":[{"text":"Push notification SDK for iOS applications.","type":"text"}],"url":"\/documentation\/pushwooshframework","title":"PushwooshFramework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","role":"collection"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Pushwoosh/getTags(_:onFailure:)":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/getTags(_:onFailure:)","kind":"symbol","role":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"getTags"},{"kind":"text","text":"("},{"text":"PushwooshGetTagsHandler","kind":"typeIdentifier","preciseIdentifier":"c:PushNotificationManager.h@T@PushwooshGetTagsHandler"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"onFailure"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"PushwooshErrorHandler","preciseIdentifier":"c:PushNotificationManager.h@T@PushwooshErrorHandler"},{"kind":"text","text":"?)"}],"title":"getTags(_:onFailure:)","abstract":[{"text":"Retrieves the current device’s tags from the Pushwoosh server.","type":"text"}],"navigatorTitle":[{"text":"getTags:onFailure:","kind":"identifier"}],"url":"\/documentation\/pushwooshframework\/pushwoosh\/gettags(_:onfailure:)"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushwooshGetTagsHandler":{"navigatorTitle":[{"kind":"identifier","text":"PushwooshGetTagsHandler"}],"title":"PushwooshGetTagsHandler","type":"topic","url":"\/documentation\/pushwooshframework\/pushwooshgettagshandler","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushwooshGetTagsHandler","kind":"symbol","abstract":[{"type":"text","text":"Completion handler called when tags are successfully retrieved from the server."}],"role":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"PushwooshGetTagsHandler","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Type Alias","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"PushwooshGetTagsHandler"},{"path":"\/metadata\/symbolKind","op":"replace","value":"typealias"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"PushwooshGetTagsHandler","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","value":[{"text":"PushwooshGetTagsHandler","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushwooshErrorHandler","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Pushwoosh\/getTags(_:onFailure:)"],"title":"Related Documentation"}],"path":"\/seeAlsoSections","op":"replace"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"typedef","kind":"keyword"},{"text":" ","kind":"text"},{"text":"void (^)(NSDictionary *)","kind":"typeIdentifier","preciseIdentifier":"c:BFv(#*$objc(cs)NSDictionary)"},{"kind":"text","text":" "},{"text":"PushwooshGetTagsHandler","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushwooshErrorHandler\/title","value":"PushwooshErrorHandler","op":"replace"},{"value":[{"text":"PushwooshErrorHandler","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushwooshErrorHandler\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1getTags(_:onFailure:)\/title","value":"getTags:onFailure:"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Pushwoosh~1getTags(_:onFailure:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"getTags:onFailure:","kind":"identifier"}]},{"value":"PushwooshGetTagsHandler","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushwooshGetTagsHandler\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushwooshGetTagsHandler\/fragments","value":[{"kind":"identifier","text":"PushwooshGetTagsHandler"}],"op":"replace"}]}]}