{"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"]]},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/objc(cs)UNNotificationServiceExtension"],"kind":"relationships","title":"Inherits From"},{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)NSObject","doc:\/\/com.pushwoosh.PushwooshiOS\/s7CVarArgP","doc:\/\/com.pushwoosh.PushwooshiOS\/s28CustomDebugStringConvertibleP","doc:\/\/com.pushwoosh.PushwooshiOS\/s23CustomStringConvertibleP","doc:\/\/com.pushwoosh.PushwooshiOS\/SQ","doc:\/\/com.pushwoosh.PushwooshiOS\/SH"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"metadata":{"title":"PushwooshNotificationServiceExtension","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PushwooshNotificationServiceExtension","kind":"identifier"}],"externalID":"c:objc(cs)PushwooshNotificationServiceExtension","navigatorTitle":[{"kind":"identifier","text":"PushwooshNotificationServiceExtension"}],"role":"symbol","symbolKind":"class","platforms":[{"beta":false,"unavailable":false,"name":"iOS","deprecated":false,"introducedAt":"10.0"}],"modules":[{"name":"PushwooshFramework"}],"roleHeading":"Class"},"abstract":[{"text":"Drop-in base class for a Notification Service Extension. Subclass it (or set it directly as","type":"text"},{"type":"text","text":" "},{"type":"text","text":"the extension’s "},{"code":"NSExtensionPrincipalClass","type":"codeVoice"},{"text":") and Pushwoosh handles everything required for a","type":"text"},{"text":" ","type":"text"},{"text":"push: sending the message delivery event, badge counting, downloading the media attachment,","type":"text"},{"type":"text","text":" "},{"text":"and the mandatory ","type":"text"},{"type":"codeVoice","code":"serviceExtensionTimeWillExpire"},{"type":"text","text":" fallback."}],"topicSections":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushwooshNotificationServiceExtension\/pushwooshAppGroupsName()","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushwooshNotificationServiceExtension\/pushwooshPrepare(for:completion:)"],"title":"Instance Methods"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PushwooshNotificationServiceExtension","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]},{"content":[{"type":"heading","anchor":"overview","text":"Overview","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Minimal integration — no code required beyond the subclass:"}]},{"type":"codeListing","code":["import PushwooshFramework","","class NotificationService: PushwooshNotificationServiceExtension {}"],"syntax":"swift"},{"inlineContent":[{"text":"Or point the extension’s Info.plist ","type":"text"},{"code":"NSExtensionPrincipalClass","type":"codeVoice"},{"text":" at","type":"text"},{"type":"text","text":" "},{"type":"codeVoice","code":"PushwooshNotificationServiceExtension"},{"type":"text","text":" directly and write no Swift\/Obj-C at all."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"Requirements:"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"code":"Pushwoosh_APPID","type":"codeVoice"},{"text":" in the main app Info.plist. You do not need to duplicate it in the extension","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Info.plist — when missing there, Pushwoosh inherits it (and other "},{"type":"codeVoice","code":"Pushwoosh_*"},{"type":"text","text":" keys) from the"},{"text":" ","type":"text"},{"type":"text","text":"host app. Set it explicitly in the extension Info.plist only to override the host."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"mutable-content: 1"},{"text":" in the push payload (so the extension is invoked).","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"App Group shared between the app and the extension for badge \/ reverse-proxy sync"},{"type":"text","text":" "},{"text":"(set ","type":"text"},{"code":"PW_APP_GROUPS_NAME","type":"codeVoice"},{"text":" in Info.plist or override ","type":"text"},{"code":"pushwooshAppGroupsName","type":"codeVoice"},{"type":"text","text":")."},{"text":" ","type":"text"},{"type":"text","text":"Note: if the host app uses a reverse proxy ("},{"code":"Pushwoosh_ALLOW_REVERSE_PROXY","type":"codeVoice"},{"text":"), the extension","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"needs this App Group to read the proxy URL the app stored there — otherwise the delivery event"},{"text":" ","type":"text"},{"type":"text","text":"is held back (it will not bypass the proxy). Add the App Group capability to the extension target."}]}]}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Customization, from least to most control:"}]},{"items":[{"content":[{"inlineContent":[{"type":"text","text":"Override "},{"code":"pushwooshAppGroupsName","type":"codeVoice"},{"type":"text","text":" to set the App Group programmatically."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Override "},{"type":"codeVoice","code":"pushwooshPrepareForRequest:completion:"},{"text":" to run async preparation before processing","type":"text"},{"type":"text","text":" "},{"text":"(e.g. Push Stories media prefetch) without touching the standard ","type":"text"},{"type":"codeVoice","code":"didReceive"},{"type":"text","text":"."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"Override the standard ","type":"text"},{"code":"didReceiveNotificationRequest:withContentHandler:","type":"codeVoice"},{"type":"text","text":" to customize the"},{"text":" ","type":"text"},{"text":"content before it is shown: call ","type":"text"},{"type":"codeVoice","code":"super"},{"type":"text","text":" with your own content handler, mutate the content"},{"text":" ","type":"text"},{"type":"text","text":"inside it, then forward to the original handler. Pushwoosh still runs the delivery event,"},{"text":" ","type":"text"},{"text":"badge, attachment and timeout fallback.","type":"text"}],"type":"paragraph"},{"type":"codeListing","syntax":"swift","code":["override func didReceive(_ request: UNNotificationRequest,","                         withContentHandler contentHandler: @escaping (UNNotificationContent) -> Void) {","    super.didReceive(request) { content in","        let mutable = (content.mutableCopy() as? UNMutableNotificationContent) ?? content","        \/\/ customize `mutable` here","        contentHandler(mutable)","    }","}"]},{"type":"paragraph","inlineContent":[{"text":"For full control, skip ","type":"text"},{"type":"codeVoice","code":"super"},{"text":" and drive everything yourself (in that case send the delivery","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"event via "},{"type":"codeVoice","code":"PWNotificationExtensionManager"},{"type":"text","text":")."}]}]}],"type":"unorderedList"}],"kind":"content"}],"variants":[{"paths":["\/documentation\/pushwooshframework\/pushwooshnotificationserviceextension"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pushwooshnotificationserviceextension"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushwooshNotificationServiceExtension"},"references":{"doc://com.pushwoosh.PushwooshiOS/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.pushwoosh.PushwooshiOS/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.pushwoosh.PushwooshiOS/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/SQ"},"doc://com.pushwoosh.PushwooshiOS/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/s7CVarArgP"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushwooshNotificationServiceExtension/pushwooshPrepare(for:completion:)":{"role":"symbol","abstract":[{"type":"text","text":"Called before Pushwoosh processes the push. Override to run asynchronous preparation — for"},{"text":" ","type":"text"},{"text":"example, prefetching Push Stories media into a shared App Group container — without overriding","type":"text"},{"type":"text","text":" "},{"text":"the standard ","type":"text"},{"type":"codeVoice","code":"didReceive"},{"text":". Processing (delivery event, badge, attachment) continues only after","type":"text"},{"text":" ","type":"text"},{"type":"codeVoice","code":"completion"},{"type":"text","text":" fires, so always call it exactly once, on the main thread."}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushwooshNotificationServiceExtension\/pushwooshPrepare(for:completion:)","type":"topic","url":"\/documentation\/pushwooshframework\/pushwooshnotificationserviceextension\/pushwooshprepare(for:completion:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pushwooshPrepare"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UNNotificationRequest","text":"UNNotificationRequest"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": () -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")","kind":"text"}],"title":"pushwooshPrepare(for:completion:)","navigatorTitle":[{"kind":"identifier","text":"pushwooshPrepareForRequest:completion:"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushwooshNotificationServiceExtension/pushwooshAppGroupsName()":{"type":"topic","abstract":[{"type":"text","text":"The App Group used to sync badge count and reverse-proxy settings with the host app."}],"role":"symbol","url":"\/documentation\/pushwooshframework\/pushwooshnotificationserviceextension\/pushwooshappgroupsname()","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushwooshNotificationServiceExtension\/pushwooshAppGroupsName()","title":"pushwooshAppGroupsName()","navigatorTitle":[{"kind":"identifier","text":"pushwooshAppGroupsName"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"pushwooshAppGroupsName","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol"},"doc://com.pushwoosh.PushwooshiOS/objc(cs)UNNotificationServiceExtension":{"type":"unresolvable","title":"UNNotificationServiceExtension","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/objc(cs)UNNotificationServiceExtension"},"doc://com.pushwoosh.PushwooshiOS/SH":{"type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/SH","title":"Swift.Hashable"},"doc://com.pushwoosh.PushwooshiOS/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushwooshNotificationServiceExtension":{"type":"topic","abstract":[{"type":"text","text":"Drop-in base class for a Notification Service Extension. Subclass it (or set it directly as"},{"text":" ","type":"text"},{"text":"the extension’s ","type":"text"},{"code":"NSExtensionPrincipalClass","type":"codeVoice"},{"type":"text","text":") and Pushwoosh handles everything required for a"},{"type":"text","text":" "},{"text":"push: sending the message delivery event, badge counting, downloading the media attachment,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"and the mandatory "},{"code":"serviceExtensionTimeWillExpire","type":"codeVoice"},{"text":" fallback.","type":"text"}],"role":"symbol","url":"\/documentation\/pushwooshframework\/pushwooshnotificationserviceextension","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushwooshNotificationServiceExtension","title":"PushwooshNotificationServiceExtension","navigatorTitle":[{"text":"PushwooshNotificationServiceExtension","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PushwooshNotificationServiceExtension","kind":"identifier"}],"kind":"symbol"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","type":"topic","role":"collection","abstract":[{"text":"Push notification SDK for iOS applications.","type":"text"}],"title":"PushwooshFramework","url":"\/documentation\/pushwooshframework"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[{"unavailable":false,"introducedAt":"10.0","beta":false,"deprecated":false,"name":"iOS"}]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"path":"\/metadata\/title","value":"PushwooshNotificationServiceExtension","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"PushwooshNotificationServiceExtension","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"PushwooshNotificationServiceExtension"}]},{"value":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushwooshNotificationServiceExtension\/pushwooshAppGroupsName()","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushwooshNotificationServiceExtension\/pushwooshPrepare(for:completion:)"],"title":"Instance Methods"}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"replace","value":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/objc(cs)UNNotificationServiceExtension"],"kind":"relationships","title":"Inherits From"}]},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PushwooshNotificationServiceExtension","kind":"identifier"},{"kind":"text","text":" : "},{"text":"UNNotificationServiceExtension","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UNNotificationServiceExtension"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushwooshNotificationServiceExtension~1pushwooshPrepare(for:completion:)\/title","value":"pushwooshPrepareForRequest:completion:"},{"value":[{"text":"- ","kind":"text"},{"text":"pushwooshPrepareForRequest:completion:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushwooshNotificationServiceExtension~1pushwooshPrepare(for:completion:)\/fragments","op":"replace"},{"value":"pushwooshAppGroupsName","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushwooshNotificationServiceExtension~1pushwooshAppGroupsName()\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"pushwooshAppGroupsName","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushwooshNotificationServiceExtension~1pushwooshAppGroupsName()\/fragments"},{"value":"PushwooshNotificationServiceExtension","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushwooshNotificationServiceExtension\/title","op":"replace"},{"value":[{"kind":"identifier","text":"PushwooshNotificationServiceExtension"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushwooshNotificationServiceExtension\/fragments"}]}]}