{"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PushNotificationDelegate"}],"externalID":"c:objc(pl)PushNotificationDelegate","title":"PushNotificationDelegate","modules":[{"name":"PushwooshFramework"}],"symbolKind":"protocol","roleHeading":"Protocol","navigatorTitle":[{"text":"PushNotificationDelegate","kind":"identifier"}]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushNotificationDelegate"}],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"type":"heading","anchor":"overview","level":2,"text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Deprecated. Use PWMessagingDelegate instead."}]}],"kind":"content"}],"kind":"symbol","sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationDelegate\/on(inAppClosed:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationDelegate\/on(inAppDisplayed:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationDelegate\/onActionIdentifierReceived(_:withNotification:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationDelegate\/onDidFailToRegisterForRemoteNotificationsWithError(_:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationDelegate\/onDidRegisterForRemoteNotifications(withDeviceToken:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationDelegate\/onPushAccepted(_:withNotification:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationDelegate\/onPushAccepted(_:withNotification:onStart:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationDelegate\/onPushReceived(_:withNotification:onStart:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationDelegate\/onTagsFailed(toReceive:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationDelegate\/onTagsReceived(_:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationDelegate\/push(_:openSettingsFor:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationDelegate"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pushnotificationdelegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pushnotificationdelegate"]}],"abstract":[{"type":"codeVoice","code":"PushNotificationDelegate"},{"text":" protocol defines the methods that can be implemented in the delegate of the ","type":"text"},{"type":"codeVoice","code":"PushNotificationManager"},{"type":"text","text":" class’ singleton object."},{"type":"text","text":" "},{"text":"These methods provide information about the key events for push notification manager such as registering with APS services, receiving push notifications or working with the received notification.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"These methods implementation allows to react on these events properly."}],"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationDelegate/onPushAccepted(_:withNotification:)":{"role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationDelegate\/onPushAccepted(_:withNotification:)","abstract":[{"type":"text","text":"Tells the delegate that the user has pressed OK on the push notification."},{"type":"text","text":" "},{"text":"IMPORTANT: This method is used for backwards compatibility and is deprecated. Please use the ","type":"text"},{"type":"codeVoice","code":"onPushAccepted:withNotification:onStart:"},{"type":"text","text":" method instead"}],"title":"onPushAccepted(_:withNotification:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onPushAccepted","kind":"identifier"},{"text":"(","kind":"text"},{"text":"PushNotificationManager","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PushNotificationManager"},{"kind":"text","text":"!, "},{"text":"withNotification","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!)"}],"type":"topic","url":"\/documentation\/pushwooshframework\/pushnotificationdelegate\/onpushaccepted(_:withnotification:)","deprecated":true,"navigatorTitle":[{"text":"onPushAccepted:withNotification:","kind":"identifier"}],"required":true},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationDelegate/onPushAccepted(_:withNotification:onStart:)":{"navigatorTitle":[{"kind":"identifier","text":"onPushAccepted:withNotification:onStart:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"onPushAccepted","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PushNotificationManager","preciseIdentifier":"c:objc(cs)PushNotificationManager"},{"text":"!, ","kind":"text"},{"text":"withNotification","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"]!, ","kind":"text"},{"text":"onStart","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Tells the delegate that the user has pressed on the push notification banner."}],"type":"topic","kind":"symbol","url":"\/documentation\/pushwooshframework\/pushnotificationdelegate\/onpushaccepted(_:withnotification:onstart:)","title":"onPushAccepted(_:withNotification:onStart:)","role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationDelegate\/onPushAccepted(_:withNotification:onStart:)"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationDelegate/on(inAppDisplayed:)":{"title":"on(inAppDisplayed:)","role":"symbol","type":"topic","navigatorTitle":[{"text":"onInAppDisplayed:","kind":"identifier"}],"required":true,"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationDelegate\/on(inAppDisplayed:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"on","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"inAppDisplayed"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"!)","kind":"text"}],"abstract":[{"type":"text","text":"Tells the delegate that In-App with specified code has been displayed"}],"url":"\/documentation\/pushwooshframework\/pushnotificationdelegate\/on(inappdisplayed:)","kind":"symbol","deprecated":true},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationDelegate/on(inAppClosed:)":{"deprecated":true,"type":"topic","url":"\/documentation\/pushwooshframework\/pushnotificationdelegate\/on(inappclosed:)","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationDelegate\/on(inAppClosed:)","role":"symbol","abstract":[{"type":"text","text":"Tells the delegate that In-App with specified code has been closed"}],"title":"on(inAppClosed:)","navigatorTitle":[{"text":"onInAppClosed:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"on"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"inAppClosed"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"!)","kind":"text"}],"kind":"symbol"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationDelegate/onPushReceived(_:withNotification:onStart:)":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationDelegate\/onPushReceived(_:withNotification:onStart:)","url":"\/documentation\/pushwooshframework\/pushnotificationdelegate\/onpushreceived(_:withnotification:onstart:)","abstract":[{"type":"text","text":"Tells the delegate that the push manager has received a remote notification."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"onPushReceived:withNotification:onStart:"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onPushReceived","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)PushNotificationManager","text":"PushNotificationManager","kind":"typeIdentifier"},{"text":"!, ","kind":"text"},{"text":"withNotification","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]!, ","kind":"text"},{"kind":"externalParam","text":"onStart"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"title":"onPushReceived(_:withNotification:onStart:)","required":true,"type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationDelegate":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"PushNotificationDelegate","kind":"identifier"}],"type":"topic","abstract":[{"type":"codeVoice","code":"PushNotificationDelegate"},{"type":"text","text":" protocol defines the methods that can be implemented in the delegate of the "},{"code":"PushNotificationManager","type":"codeVoice"},{"text":" class’ singleton object.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"These methods provide information about the key events for push notification manager such as registering with APS services, receiving push notifications or working with the received notification."},{"type":"text","text":" "},{"text":"These methods implementation allows to react on these events properly.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationDelegate","role":"symbol","url":"\/documentation\/pushwooshframework\/pushnotificationdelegate","navigatorTitle":[{"text":"PushNotificationDelegate","kind":"identifier"}],"title":"PushNotificationDelegate"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationDelegate/onDidFailToRegisterForRemoteNotificationsWithError(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onDidFailToRegisterForRemoteNotificationsWithError"},{"kind":"text","text":"((any "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":")!)","kind":"text"}],"type":"topic","abstract":[{"type":"text","text":"Sent to the delegate when Apple Push Service (APS) could not complete the registration process successfully."}],"kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationDelegate\/onDidFailToRegisterForRemoteNotificationsWithError(_:)","role":"symbol","url":"\/documentation\/pushwooshframework\/pushnotificationdelegate\/ondidfailtoregisterforremotenotificationswitherror(_:)","navigatorTitle":[{"text":"onDidFailToRegisterForRemoteNotificationsWithError:","kind":"identifier"}],"title":"onDidFailToRegisterForRemoteNotificationsWithError(_:)"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationDelegate/onDidRegisterForRemoteNotifications(withDeviceToken:)":{"url":"\/documentation\/pushwooshframework\/pushnotificationdelegate\/ondidregisterforremotenotifications(withdevicetoken:)","required":true,"role":"symbol","title":"onDidRegisterForRemoteNotifications(withDeviceToken:)","abstract":[{"type":"text","text":"Tells the delegate that the application has registered with Apple Push Service (APS) successfully."}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationDelegate\/onDidRegisterForRemoteNotifications(withDeviceToken:)","kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onDidRegisterForRemoteNotifications"},{"text":"(","kind":"text"},{"text":"withDeviceToken","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"!)"}],"navigatorTitle":[{"text":"onDidRegisterForRemoteNotificationsWithDeviceToken:","kind":"identifier"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationDelegate/onActionIdentifierReceived(_:withNotification:)":{"type":"topic","role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationDelegate\/onActionIdentifierReceived(_:withNotification:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onActionIdentifierReceived"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"!, ","kind":"text"},{"text":"withNotification","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]!)"}],"title":"onActionIdentifierReceived(_:withNotification:)","required":true,"abstract":[{"text":"Tells the delegate that a custom action was triggered when opening a notification.","type":"text"}],"kind":"symbol","url":"\/documentation\/pushwooshframework\/pushnotificationdelegate\/onactionidentifierreceived(_:withnotification:)","navigatorTitle":[{"text":"onActionIdentifierReceived:withNotification:","kind":"identifier"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationDelegate/push(_:openSettingsFor:)":{"role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationDelegate\/push(_:openSettingsFor:)","abstract":[{"text":"The method will be called on the delegate when the application is launched in response to the user’s request to view in-app notification settings.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Add UNAuthorizationOptionProvidesAppNotificationSettings as an option in [PushNotificationManager pushManager].additionalAuthorizationOptions to add a button to inline notification settings view and the notification settings view in Settings."},{"type":"text","text":" "},{"text":"The notification will be nil when opened from Settings.","type":"text"}],"title":"push(_:openSettingsFor:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"push"},{"text":"(","kind":"text"},{"text":"PushNotificationManager","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PushNotificationManager"},{"text":"!, ","kind":"text"},{"text":"openSettingsFor","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UNNotification","text":"UNNotification"},{"kind":"text","text":"!)"}],"type":"topic","url":"\/documentation\/pushwooshframework\/pushnotificationdelegate\/push(_:opensettingsfor:)","navigatorTitle":[{"text":"pushManager:openSettingsForNotification:","kind":"identifier"}],"required":true},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationDelegate/onTagsReceived(_:)":{"required":true,"abstract":[{"text":"Tells the delegate that the push manager has received tags from the server.","type":"text"}],"url":"\/documentation\/pushwooshframework\/pushnotificationdelegate\/ontagsreceived(_:)","kind":"symbol","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationDelegate\/onTagsReceived(_:)","title":"onTagsReceived(_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onTagsReceived","kind":"identifier"},{"text":"([","kind":"text"},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"text":"]!)","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"onTagsReceived:"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"type":"topic","abstract":[{"type":"text","text":"Push notification SDK for iOS applications."}],"title":"PushwooshFramework","kind":"symbol","url":"\/documentation\/pushwooshframework","role":"collection","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationDelegate/onTagsFailed(toReceive:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"onTagsFailed","kind":"identifier"},{"kind":"text","text":"("},{"text":"toReceive","kind":"externalParam"},{"text":": (any ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")!)"}],"type":"topic","navigatorTitle":[{"text":"onTagsFailedToReceive:","kind":"identifier"}],"required":true,"url":"\/documentation\/pushwooshframework\/pushnotificationdelegate\/ontagsfailed(toreceive:)","kind":"symbol","title":"onTagsFailed(toReceive:)","abstract":[{"type":"text","text":"Sent to the delegate when push manager could not complete the tags receiving process successfully."}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationDelegate\/onTagsFailed(toReceive:)","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"value":"PushNotificationDelegate","op":"replace","path":"\/metadata\/title"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"PushNotificationDelegate","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"PushNotificationDelegate","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationDelegate\/on(inAppClosed:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationDelegate\/on(inAppDisplayed:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationDelegate\/onActionIdentifierReceived(_:withNotification:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationDelegate\/onDidFailToRegisterForRemoteNotificationsWithError(_:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationDelegate\/onDidRegisterForRemoteNotifications(withDeviceToken:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationDelegate\/onPushAccepted(_:withNotification:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationDelegate\/onPushAccepted(_:withNotification:onStart:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationDelegate\/onPushReceived(_:withNotification:onStart:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationDelegate\/onTagsFailed(toReceive:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationDelegate\/onTagsReceived(_:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationDelegate\/push(_:openSettingsFor:)"],"title":"Instance Methods"}]},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"text":"PushNotificationDelegate","kind":"identifier"}]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationDelegate~1onPushAccepted(_:withNotification:)\/title","op":"replace","value":"onPushAccepted:withNotification:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"onPushAccepted:withNotification:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationDelegate~1onPushAccepted(_:withNotification:)\/fragments"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationDelegate~1onPushAccepted(_:withNotification:onStart:)\/title","op":"replace","value":"onPushAccepted:withNotification:onStart:"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationDelegate~1onPushAccepted(_:withNotification:onStart:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onPushAccepted:withNotification:onStart:"}]},{"value":"onInAppDisplayed:","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationDelegate~1on(inAppDisplayed:)\/title","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onInAppDisplayed:"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationDelegate~1on(inAppDisplayed:)\/fragments"},{"value":"onInAppClosed:","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationDelegate~1on(inAppClosed:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationDelegate~1on(inAppClosed:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onInAppClosed:"}]},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationDelegate~1onPushReceived(_:withNotification:onStart:)\/title","value":"onPushReceived:withNotification:onStart:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"onPushReceived:withNotification:onStart:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationDelegate~1onPushReceived(_:withNotification:onStart:)\/fragments"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationDelegate\/title","value":"PushNotificationDelegate","op":"replace"},{"value":[{"kind":"identifier","text":"PushNotificationDelegate"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationDelegate\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationDelegate~1onDidFailToRegisterForRemoteNotificationsWithError(_:)\/title","value":"onDidFailToRegisterForRemoteNotificationsWithError:"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationDelegate~1onDidFailToRegisterForRemoteNotificationsWithError(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"onDidFailToRegisterForRemoteNotificationsWithError:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationDelegate~1onDidRegisterForRemoteNotifications(withDeviceToken:)\/title","value":"onDidRegisterForRemoteNotificationsWithDeviceToken:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationDelegate~1onDidRegisterForRemoteNotifications(withDeviceToken:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onDidRegisterForRemoteNotificationsWithDeviceToken:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationDelegate~1onActionIdentifierReceived(_:withNotification:)\/title","value":"onActionIdentifierReceived:withNotification:"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationDelegate~1onActionIdentifierReceived(_:withNotification:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onActionIdentifierReceived:withNotification:","kind":"identifier"}]},{"value":"pushManager:openSettingsForNotification:","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationDelegate~1push(_:openSettingsFor:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationDelegate~1push(_:openSettingsFor:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"pushManager:openSettingsForNotification:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationDelegate~1onTagsReceived(_:)\/title","op":"replace","value":"onTagsReceived:"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationDelegate~1onTagsReceived(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"onTagsReceived:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationDelegate~1onTagsFailed(toReceive:)\/title","op":"replace","value":"onTagsFailedToReceive:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"onTagsFailedToReceive:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationDelegate~1onTagsFailed(toReceive:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}