{"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"The current version of the Pushwoosh SDK."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"PUSHWOOSH_VERSION"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}]}],"kind":"declarations"},{"content":[{"level":2,"type":"heading","anchor":"Discussion","text":"Discussion"},{"inlineContent":[{"type":"text","text":"This constant contains the version string of the Pushwoosh SDK currently in use. The version follows semantic versioning format (e.g., “6.12.1”)."}],"type":"paragraph"},{"inlineContent":[{"text":"Use this for debugging, logging, or displaying SDK version information in your app.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pushwoosh_version"]},{"paths":["\/documentation\/pushwooshframework\/pushwoosh_version"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"PUSHWOOSH_VERSION","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"role":"symbol","symbolKind":"var","title":"PUSHWOOSH_VERSION","modules":[{"name":"PushwooshFramework"}],"externalID":"c:PushwooshFramework.h@490@macro@PUSHWOOSH_VERSION","roleHeading":"Global Variable","navigatorTitle":[{"text":"PUSHWOOSH_VERSION","kind":"identifier"}]},"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PUSHWOOSH_VERSION","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"]]},"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PUSHWOOSH_VERSION":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PUSHWOOSH_VERSION"}],"type":"topic","abstract":[{"type":"text","text":"The current version of the Pushwoosh SDK."}],"role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PUSHWOOSH_VERSION","url":"\/documentation\/pushwooshframework\/pushwoosh_version","title":"PUSHWOOSH_VERSION","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PUSHWOOSH_VERSION"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"kind":"symbol","abstract":[],"url":"\/documentation\/pushwooshframework","role":"collection","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","title":"PushwooshFramework"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Macro","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"PUSHWOOSH_VERSION","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"macro"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"PUSHWOOSH_VERSION","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"#define","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PUSHWOOSH_VERSION","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PUSHWOOSH_VERSION\/title","value":"PUSHWOOSH_VERSION","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PUSHWOOSH_VERSION\/fragments","value":[{"text":"PUSHWOOSH_VERSION","kind":"identifier"}]}]}]}