{"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"]]},"abstract":[{"type":"codeVoice","code":"PushNotificationManager"},{"type":"text","text":" class offers access to the singleton-instance of the push manager responsible for registering the device with the APS servers, receiving and processing push notifications."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PushNotificationManager","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"type":"heading","level":2,"anchor":"overview","text":"Overview"},{"type":"paragraph","inlineContent":[{"text":"Deprecated. Use Pushwoosh class instead.","type":"text"}]}]}],"sections":[],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/init(applicationCode:appName:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/init(applicationCode:navController:appName:)"]},{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/additionalAuthorizationOptions","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/appCode","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/appName","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/delegate","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/language","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/launchNotification","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/notificationCenterDelegate","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/showPushnotificationAlert"],"title":"Instance Properties"},{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/getApnPayload(_:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/getCustomPushData(_:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/getCustomPushData(asNSDict:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/getHWID()","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/getPushToken()","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/handlePushAccepted(_:onStart:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/handlePushReceived(_:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/handlePushRegistration(_:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/handlePushRegistrationFailure(_:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/handlePushRegistrationString(_:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/loadTags()","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/loadTags(_:error:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/mergeUserId(_:to:doMerge:completion:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/postEvent(_:withAttributes:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/postEvent(_:withAttributes:completion:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/registerForPushNotifications()","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/sendAppOpen()","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/sendPurchase(_:withPrice:currencyCode:andDate:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/sendSKPaymentTransactions(_:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/setTags(_:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/setTags(_:withCompletion:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/setUserId(_:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/startLocationTracking()","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/stopLocationTracking()","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/unregisterForPushNotifications()","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/unregisterForPushNotifications(completion:)"],"title":"Instance Methods"},{"title":"Type Methods","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/clearNotificationCenter()","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/getRemoteNotificationStatus()","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/initialize(withAppCode:appName:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/isPushwooshMessage(_:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/push()","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/pushwooshVersion()"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager"},"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PushNotificationManager","kind":"identifier"}],"title":"PushNotificationManager","roleHeading":"Class","externalID":"c:objc(cs)PushNotificationManager","role":"symbol","symbolKind":"class","navigatorTitle":[{"text":"PushNotificationManager","kind":"identifier"}],"modules":[{"name":"PushwooshFramework"}]},"relationshipsSections":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"},{"kind":"relationships","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)NSObject","doc:\/\/com.pushwoosh.PushwooshiOS\/s7CVarArgP","doc:\/\/com.pushwoosh.PushwooshiOS\/s28CustomDebugStringConvertibleP","doc:\/\/com.pushwoosh.PushwooshiOS\/s23CustomStringConvertibleP","doc:\/\/com.pushwoosh.PushwooshiOS\/SQ","doc:\/\/com.pushwoosh.PushwooshiOS\/SH"],"type":"conformsTo","title":"Conforms To"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pushnotificationmanager"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pushnotificationmanager"]}],"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationManager/appCode":{"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"appCode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"!","kind":"text"}],"title":"appCode","abstract":[{"text":"Pushwoosh Application ID. Usually retrieved automatically from Info.plist parameter ","type":"text"},{"code":"Pushwoosh_APPID","type":"codeVoice"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/appCode","role":"symbol","url":"\/documentation\/pushwooshframework\/pushnotificationmanager\/appcode","navigatorTitle":[{"text":"appCode","kind":"identifier"}],"type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationManager/postEvent(_:withAttributes:)":{"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"postEvent","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"withAttributes"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]!)"}],"deprecated":true,"title":"postEvent(_:withAttributes:)","abstract":[{"text":"See ","type":"text"},{"code":"postEvent:withAttributes:completion:","type":"codeVoice"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/postEvent(_:withAttributes:)","role":"symbol","url":"\/documentation\/pushwooshframework\/pushnotificationmanager\/postevent(_:withattributes:)","navigatorTitle":[{"text":"postEvent:withAttributes:","kind":"identifier"}],"type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationManager/appName":{"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"appName"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"!"}],"title":"appName","abstract":[{"text":"Application name. Usually retrieved automatically from Info.plist bundle name (CFBundleDisplayName). Could be used to override bundle name. In addition could be set in Info.plist as ","type":"text"},{"code":"Pushwoosh_APPNAME","type":"codeVoice"},{"text":" parameter.","type":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/appName","role":"symbol","url":"\/documentation\/pushwooshframework\/pushnotificationmanager\/appname","navigatorTitle":[{"kind":"identifier","text":"appName"}],"type":"topic"},"doc://com.pushwoosh.PushwooshiOS/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/s23CustomStringConvertibleP"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationManager/clearNotificationCenter()":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"clearNotificationCenter"},{"text":"()","kind":"text"}],"title":"clearNotificationCenter()","abstract":[{"text":"Clears the notifications from the notification center.","type":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/clearNotificationCenter()","role":"symbol","url":"\/documentation\/pushwooshframework\/pushnotificationmanager\/clearnotificationcenter()","navigatorTitle":[{"kind":"identifier","text":"clearNotificationCenter"}],"type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationManager/sendPurchase(_:withPrice:currencyCode:andDate:)":{"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"sendPurchase","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"!, ","kind":"text"},{"kind":"externalParam","text":"withPrice"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSDecimalNumber","text":"NSDecimalNumber","kind":"typeIdentifier"},{"text":"!, ","kind":"text"},{"text":"currencyCode","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"!, ","kind":"text"},{"kind":"externalParam","text":"andDate"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"},{"kind":"text","text":"!)"}],"title":"sendPurchase(_:withPrice:currencyCode:andDate:)","abstract":[{"text":"Tracks individual in-app purchase. See recommended ","type":"text"},{"code":"sendSKPaymentTransactions:","type":"codeVoice"},{"type":"text","text":" method."}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/sendPurchase(_:withPrice:currencyCode:andDate:)","role":"symbol","url":"\/documentation\/pushwooshframework\/pushnotificationmanager\/sendpurchase(_:withprice:currencycode:anddate:)","navigatorTitle":[{"text":"sendPurchase:withPrice:currencyCode:andDate:","kind":"identifier"}],"type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationManager/initialize(withAppCode:appName:)":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"initialize","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withAppCode","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"!, ","kind":"text"},{"text":"appName","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"!)"}],"title":"initialize(withAppCode:appName:)","abstract":[{"type":"text","text":"Initializes PushNotificationManager. Usually called by Pushwoosh Runtime internally."}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/initialize(withAppCode:appName:)","role":"symbol","url":"\/documentation\/pushwooshframework\/pushnotificationmanager\/initialize(withappcode:appname:)","navigatorTitle":[{"kind":"identifier","text":"initializeWithAppCode:appName:"}],"type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationManager/loadTags(_:error:)":{"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"loadTags","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:PushNotificationManager.h@T@PushwooshGetTagsHandler","text":"PushwooshGetTagsHandler","kind":"typeIdentifier"},{"text":"!, ","kind":"text"},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PushwooshErrorHandler","kind":"typeIdentifier","preciseIdentifier":"c:PushNotificationManager.h@T@PushwooshErrorHandler"},{"text":"!)","kind":"text"}],"title":"loadTags(_:error:)","abstract":[{"type":"text","text":"Get tags from server. Calls delegate method if exists and handler (block)."}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/loadTags(_:error:)","role":"symbol","url":"\/documentation\/pushwooshframework\/pushnotificationmanager\/loadtags(_:error:)","navigatorTitle":[{"text":"loadTags:error:","kind":"identifier"}],"type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationManager/notificationCenterDelegate":{"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"notificationCenterDelegate","kind":"identifier"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)UNUserNotificationCenterDelegate","text":"UNUserNotificationCenterDelegate","kind":"typeIdentifier"},{"text":")!","kind":"text"}],"title":"notificationCenterDelegate","abstract":[{"text":"Returns UNUserNotificationCenterDelegate that handles foreground push notifications on iOS10","type":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/notificationCenterDelegate","role":"symbol","url":"\/documentation\/pushwooshframework\/pushnotificationmanager\/notificationcenterdelegate","navigatorTitle":[{"text":"notificationCenterDelegate","kind":"identifier"}],"type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationManager/launchNotification":{"role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"launchNotification","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]!"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/launchNotification","navigatorTitle":[{"kind":"identifier","text":"launchNotification"}],"type":"topic","abstract":[{"type":"text","text":"Returns push notification payload if the app was started in response to push notification or null otherwise"}],"url":"\/documentation\/pushwooshframework\/pushnotificationmanager\/launchnotification","title":"launchNotification"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"abstract":[{"text":"Push notification SDK for iOS applications.","type":"text"}],"url":"\/documentation\/pushwooshframework","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","title":"PushwooshFramework","type":"topic","role":"collection"},"doc://com.pushwoosh.PushwooshiOS/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/objc(cs)NSObject","title":"NSObject"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationManager/sendLocation:":{"kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"sendLocation:","kind":"identifier"}],"title":"sendLocation:","abstract":[{"type":"text","text":"Explicitly sends geolocation to the server for GeoFencing push technology. Also called internally, please use "},{"type":"codeVoice","code":"startLocationTracking"},{"text":" and ","type":"text"},{"code":"stopLocationTracking","type":"codeVoice"},{"text":" functions.","type":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/sendLocation:","role":"symbol","url":"\/documentation\/pushwooshframework\/pushnotificationmanager\/sendlocation:","navigatorTitle":[{"kind":"identifier","text":"sendLocation:"}],"type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationManager/isPushwooshMessage(_:)":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isPushwooshMessage","kind":"identifier"},{"text":"([","kind":"text"},{"text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"]!) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"title":"isPushwooshMessage(_:)","abstract":[],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/isPushwooshMessage(_:)","role":"symbol","url":"\/documentation\/pushwooshframework\/pushnotificationmanager\/ispushwooshmessage(_:)","navigatorTitle":[{"text":"isPushwooshMessage:","kind":"identifier"}],"type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationManager/stopLocationTracking()":{"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"stopLocationTracking"},{"text":"()","kind":"text"}],"deprecated":true,"title":"stopLocationTracking()","abstract":[{"type":"text","text":"Stops location tracking"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/stopLocationTracking()","role":"symbol","url":"\/documentation\/pushwooshframework\/pushnotificationmanager\/stoplocationtracking()","navigatorTitle":[{"text":"stopLocationTracking","kind":"identifier"}],"type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationManager/language":{"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"language","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"title":"language","abstract":[{"text":"Set custom application language. Must be a lowercase two-letter code according to ISO-639-1 standard (“en”, “de”, “fr”, etc.).","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Device language used by default."},{"type":"text","text":" "},{"text":"Set to nil if you want to use device language again.","type":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/language","role":"symbol","url":"\/documentation\/pushwooshframework\/pushnotificationmanager\/language","navigatorTitle":[{"kind":"identifier","text":"language"}],"type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationManager/push()":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"push","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)PushNotificationManager","text":"PushNotificationManager","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"title":"push()","abstract":[{"type":"text","text":"Returns an object representing the current push manager."}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/push()","role":"symbol","url":"\/documentation\/pushwooshframework\/pushnotificationmanager\/push()","navigatorTitle":[{"text":"pushManager","kind":"identifier"}],"type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationManager/loadTags()":{"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loadTags","kind":"identifier"},{"kind":"text","text":"()"}],"title":"loadTags()","abstract":[{"text":"Get tags from the server. Calls delegate method ","type":"text"},{"type":"codeVoice","code":"onTagsReceived:"},{"text":" or ","type":"text"},{"code":"onTagsFailedToReceive:","type":"codeVoice"},{"text":" depending on the results.","type":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/loadTags()","role":"symbol","url":"\/documentation\/pushwooshframework\/pushnotificationmanager\/loadtags()","navigatorTitle":[{"text":"loadTags","kind":"identifier"}],"type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationManager/showPushnotificationAlert":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"showPushnotificationAlert"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"title":"showPushnotificationAlert","abstract":[{"text":"Show push notifications alert when push notification is received while the app is running, default is ","type":"text"},{"type":"codeVoice","code":"YES"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/showPushnotificationAlert","role":"symbol","url":"\/documentation\/pushwooshframework\/pushnotificationmanager\/showpushnotificationalert","navigatorTitle":[{"text":"showPushnotificationAlert","kind":"identifier"}],"type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationManager/getRemoteNotificationStatus()":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getRemoteNotificationStatus"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSMutableDictionary","text":"NSMutableDictionary","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"title":"getRemoteNotificationStatus()","abstract":[{"type":"text","text":"Returns dictionary with enabled remove notificaton types."}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/getRemoteNotificationStatus()","role":"symbol","url":"\/documentation\/pushwooshframework\/pushnotificationmanager\/getremotenotificationstatus()","navigatorTitle":[{"text":"getRemoteNotificationStatus","kind":"identifier"}],"type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationManager/getHWID()":{"title":"getHWID()","type":"topic","abstract":[{"text":"Gets HWID. Unique device identifier that used in all API calls with Pushwoosh.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"This is identifierForVendor for iOS >= 7."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getHWID"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"!","kind":"text"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/getHWID()","navigatorTitle":[{"text":"getHWID","kind":"identifier"}],"url":"\/documentation\/pushwooshframework\/pushnotificationmanager\/gethwid()"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationManager/unregisterForPushNotifications(completion:)":{"title":"unregisterForPushNotifications(completion:)","url":"\/documentation\/pushwooshframework\/pushnotificationmanager\/unregisterforpushnotifications(completion:)","abstract":[{"text":"Unregisters from push notifications.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"unregisterForPushNotifications","kind":"identifier"},{"kind":"text","text":"("},{"text":"completion","kind":"externalParam"},{"text":": (((any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")!)","kind":"text"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/unregisterForPushNotifications(completion:)","navigatorTitle":[{"kind":"identifier","text":"unregisterForPushNotificationsWithCompletion:"}],"type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationManager/getCustomPushData(_:)":{"title":"getCustomPushData(_:)","type":"topic","abstract":[{"type":"text","text":"Gets custom JSON string data from push notifications dictionary as specified in Pushwoosh Control Panel."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getCustomPushData","kind":"identifier"},{"text":"([","kind":"text"},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"]!) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"!","kind":"text"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/getCustomPushData(_:)","navigatorTitle":[{"text":"getCustomPushData:","kind":"identifier"}],"url":"\/documentation\/pushwooshframework\/pushnotificationmanager\/getcustompushdata(_:)"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationManager/postEvent(_:withAttributes:completion:)":{"title":"postEvent(_:withAttributes:completion:)","url":"\/documentation\/pushwooshframework\/pushnotificationmanager\/postevent(_:withattributes:completion:)","abstract":[{"text":"Post events for In-App Messages. This can trigger In-App message display as specified in Pushwoosh Control Panel.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"postEvent","kind":"identifier"},{"kind":"text","text":"("},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"!, ","kind":"text"},{"text":"withAttributes","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (((any "},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":")?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")!)","kind":"text"}],"deprecated":true,"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/postEvent(_:withAttributes:completion:)","navigatorTitle":[{"kind":"identifier","text":"postEvent:withAttributes:completion:"}],"type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationManager/getApnPayload(_:)":{"title":"getApnPayload(_:)","type":"topic","abstract":[{"type":"text","text":"Gets APN payload from push notifications dictionary."}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"getApnPayload","kind":"identifier"},{"text":"([","kind":"text"},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!) -> ["},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]!","kind":"text"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/getApnPayload(_:)","navigatorTitle":[{"text":"getApnPayload:","kind":"identifier"}],"url":"\/documentation\/pushwooshframework\/pushnotificationmanager\/getapnpayload(_:)"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationManager/handlePushReceived(_:)":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"handlePushReceived:"}],"abstract":[],"type":"topic","url":"\/documentation\/pushwooshframework\/pushnotificationmanager\/handlepushreceived(_:)","role":"symbol","title":"handlePushReceived(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"handlePushReceived"},{"kind":"text","text":"(["},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"]!) -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/handlePushReceived(_:)"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationManager/sendAppOpen()":{"title":"sendAppOpen()","url":"\/documentation\/pushwooshframework\/pushnotificationmanager\/sendappopen()","abstract":[{"type":"text","text":"Informs the Pushwoosh about the app being launched. Usually called internally by SDK Runtime."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sendAppOpen","kind":"identifier"},{"text":"()","kind":"text"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/sendAppOpen()","navigatorTitle":[{"kind":"identifier","text":"sendAppOpen"}],"type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationManager/pushwooshVersion()":{"title":"pushwooshVersion()","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pushwooshVersion","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/pushwooshVersion()","navigatorTitle":[{"kind":"identifier","text":"pushwooshVersion"}],"url":"\/documentation\/pushwooshframework\/pushnotificationmanager\/pushwooshversion()"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationManager/mergeUserId(_:to:doMerge:completion:)":{"abstract":[{"type":"text","text":"Move all events from oldUserId to newUserId if doMerge is true. If doMerge is false all events for oldUserId are removed."}],"kind":"symbol","url":"\/documentation\/pushwooshframework\/pushnotificationmanager\/mergeuserid(_:to:domerge:completion:)","type":"topic","title":"mergeUserId(_:to:doMerge:completion:)","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/mergeUserId(_:to:doMerge:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mergeUserId"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"!, ","kind":"text"},{"kind":"externalParam","text":"to"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"text":"doMerge","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"text":": (((any ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")!)","kind":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"mergeUserId:to:doMerge:completion:"}],"deprecated":true},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationManager/sendSKPaymentTransactions(_:)":{"title":"sendSKPaymentTransactions(_:)","url":"\/documentation\/pushwooshframework\/pushnotificationmanager\/sendskpaymenttransactions(_:)","abstract":[{"type":"text","text":"Sends in-app purchases to Pushwoosh. Use in paymentQueue:updatedTransactions: payment queue method (see example)."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"sendSKPaymentTransactions","kind":"identifier"},{"text":"([","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]!)","kind":"text"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/sendSKPaymentTransactions(_:)","navigatorTitle":[{"text":"sendSKPaymentTransactions:","kind":"identifier"}],"type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationManager/startLocationTracking()":{"title":"startLocationTracking()","type":"topic","abstract":[{"type":"text","text":"Start location tracking."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startLocationTracking","kind":"identifier"},{"text":"()","kind":"text"}],"deprecated":true,"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/startLocationTracking()","navigatorTitle":[{"kind":"identifier","text":"startLocationTracking"}],"url":"\/documentation\/pushwooshframework\/pushnotificationmanager\/startlocationtracking()"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationManager/setTags(_:)":{"title":"setTags(_:)","url":"\/documentation\/pushwooshframework\/pushnotificationmanager\/settags(_:)","abstract":[{"text":"Send tags to server. Tag names have to be created in the Pushwoosh Control Panel. Possible tag types: Integer, String, Incremental (integer only), List tags (array of values).","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setTags","kind":"identifier"},{"text":"([","kind":"text"},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!)"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/setTags(_:)","navigatorTitle":[{"text":"setTags:","kind":"identifier"}],"type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationManager":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager","navigatorTitle":[{"text":"PushNotificationManager","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PushNotificationManager","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"PushNotificationManager","abstract":[{"type":"codeVoice","code":"PushNotificationManager"},{"text":" class offers access to the singleton-instance of the push manager responsible for registering the device with the APS servers, receiving and processing push notifications.","type":"text"}],"url":"\/documentation\/pushwooshframework\/pushnotificationmanager"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationManager/delegate":{"title":"delegate","type":"topic","abstract":[{"type":"codeVoice","code":"PushNotificationDelegate"},{"type":"text","text":" protocol delegate that would receive the information about events for push notification manager such as registering with APS services, receiving push notifications or working with the received notification."},{"type":"text","text":" "},{"type":"text","text":"Pushwoosh Runtime sets it to ApplicationDelegate by default"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)NSObject","text":"NSObjectProtocol","kind":"typeIdentifier"},{"kind":"text","text":" & "},{"preciseIdentifier":"c:objc(pl)PushNotificationDelegate","text":"PushNotificationDelegate","kind":"typeIdentifier"},{"kind":"text","text":")!"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/delegate","navigatorTitle":[{"text":"delegate","kind":"identifier"}],"url":"\/documentation\/pushwooshframework\/pushnotificationmanager\/delegate"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationManager/unregisterForPushNotifications()":{"title":"unregisterForPushNotifications()","url":"\/documentation\/pushwooshframework\/pushnotificationmanager\/unregisterforpushnotifications()","abstract":[{"type":"text","text":"Deprecated. Use unregisterForPushNotificationsWithCompletion: method instead"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unregisterForPushNotifications"},{"text":"()","kind":"text"}],"deprecated":true,"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/unregisterForPushNotifications()","navigatorTitle":[{"text":"unregisterForPushNotifications","kind":"identifier"}],"type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationManager/handlePushRegistrationString(_:)":{"title":"handlePushRegistrationString(_:)","type":"topic","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"handlePushRegistrationString"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"!)","kind":"text"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/handlePushRegistrationString(_:)","navigatorTitle":[{"text":"handlePushRegistrationString:","kind":"identifier"}],"url":"\/documentation\/pushwooshframework\/pushnotificationmanager\/handlepushregistrationstring(_:)"},"doc://com.pushwoosh.PushwooshiOS/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationManager/registerForPushNotifications()":{"title":"registerForPushNotifications()","type":"topic","abstract":[{"type":"text","text":"Registers for push notifications. By default registeres for “UIRemoteNotificationTypeBadge | UIRemoteNotificationTypeSound | UIRemoteNotificationTypeAlert” flags."},{"type":"text","text":" "},{"text":"Automatically detects if you have “newsstand-content” in “UIBackgroundModes” and adds “UIRemoteNotificationTypeNewsstandContentAvailability” flag.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"registerForPushNotifications","kind":"identifier"},{"text":"()","kind":"text"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/registerForPushNotifications()","navigatorTitle":[{"text":"registerForPushNotifications","kind":"identifier"}],"url":"\/documentation\/pushwooshframework\/pushnotificationmanager\/registerforpushnotifications()"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationManager/handlePushRegistrationFailure(_:)":{"title":"handlePushRegistrationFailure(_:)","url":"\/documentation\/pushwooshframework\/pushnotificationmanager\/handlepushregistrationfailure(_:)","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"handlePushRegistrationFailure","kind":"identifier"},{"kind":"text","text":"((any "},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"kind":"text","text":")!)"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/handlePushRegistrationFailure(_:)","navigatorTitle":[{"text":"handlePushRegistrationFailure:","kind":"identifier"}],"type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationManager/setTags(_:withCompletion:)":{"title":"setTags(_:withCompletion:)","type":"topic","abstract":[{"type":"text","text":"Send tags to server with completion block. If setTags succeeds competion is called with nil argument. If setTags fails completion is called with error."}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setTags"},{"text":"([","kind":"text"},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]!, ","kind":"text"},{"kind":"externalParam","text":"withCompletion"},{"kind":"text","text":": (((any "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":")?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")!)","kind":"text"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/setTags(_:withCompletion:)","navigatorTitle":[{"kind":"identifier","text":"setTags:withCompletion:"}],"url":"\/documentation\/pushwooshframework\/pushnotificationmanager\/settags(_:withcompletion:)"},"doc://com.pushwoosh.PushwooshiOS/SH":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationManager/getPushToken()":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"getPushToken","kind":"identifier"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/getPushToken()","navigatorTitle":[{"kind":"identifier","text":"getPushToken"}],"kind":"symbol","url":"\/documentation\/pushwooshframework\/pushnotificationmanager\/getpushtoken()","abstract":[{"type":"text","text":"Gets current push token."}],"role":"symbol","title":"getPushToken()","type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationManager/getCustomPushData(asNSDict:)":{"title":"getCustomPushData(asNSDict:)","type":"topic","abstract":[{"type":"text","text":"The same as getCustomPushData but returns NSDictionary rather than JSON string (converts JSON string into NSDictionary)."}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"getCustomPushData","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"asNSDict"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]!) -> [","kind":"text"},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]!"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/getCustomPushData(asNSDict:)","navigatorTitle":[{"text":"getCustomPushDataAsNSDict:","kind":"identifier"}],"url":"\/documentation\/pushwooshframework\/pushnotificationmanager\/getcustompushdata(asnsdict:)"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationManager/setUserId(_:)":{"title":"setUserId(_:)","url":"\/documentation\/pushwooshframework\/pushnotificationmanager\/setuserid(_:)","abstract":[{"type":"text","text":"Set User indentifier. This could be Facebook ID, username or email, or any other user ID."},{"text":" ","type":"text"},{"type":"text","text":"This allows data and events to be matched across multiple user devices."}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setUserId","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"!)","kind":"text"}],"deprecated":true,"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/setUserId(_:)","navigatorTitle":[{"kind":"identifier","text":"setUserId:"}],"type":"topic"},"doc://com.pushwoosh.PushwooshiOS/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/s7CVarArgP"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationManager/init(applicationCode:navController:appName:)":{"title":"init(applicationCode:navController:appName:)","url":"\/documentation\/pushwooshframework\/pushnotificationmanager\/init(applicationcode:navcontroller:appname:)","abstract":[{"type":"text","text":"Deprecated. Use initializeWithAppCode:appName: method instead"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"!(","kind":"text"},{"text":"applicationCode","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"!, "},{"text":"navController","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"appName"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"!)","kind":"text"}],"deprecated":true,"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/init(applicationCode:navController:appName:)","navigatorTitle":[{"kind":"identifier","text":"initWithApplicationCode:navController:appName:"}],"type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationManager/handlePushRegistration(_:)":{"title":"handlePushRegistration(_:)","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"handlePushRegistration"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"kind":"text","text":"!)"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/handlePushRegistration(_:)","navigatorTitle":[{"text":"handlePushRegistration:","kind":"identifier"}],"url":"\/documentation\/pushwooshframework\/pushnotificationmanager\/handlepushregistration(_:)"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationManager/init(applicationCode:appName:)":{"title":"init(applicationCode:appName:)","url":"\/documentation\/pushwooshframework\/pushnotificationmanager\/init(applicationcode:appname:)","abstract":[{"type":"text","text":"Deprecated. Use initializeWithAppCode:appName: method instead"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"!("},{"text":"applicationCode","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"appName"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"!)","kind":"text"}],"deprecated":true,"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/init(applicationCode:appName:)","navigatorTitle":[{"text":"initWithApplicationCode:appName:","kind":"identifier"}],"type":"topic"},"doc://com.pushwoosh.PushwooshiOS/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.pushwoosh.PushwooshiOS/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/SQ","title":"Swift.Equatable"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationManager/handlePushAccepted(_:onStart:)":{"title":"handlePushAccepted(_:onStart:)","type":"topic","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"handlePushAccepted"},{"text":"([","kind":"text"},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]!, "},{"text":"onStart","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/handlePushAccepted(_:onStart:)","navigatorTitle":[{"text":"handlePushAccepted:onStart:","kind":"identifier"}],"url":"\/documentation\/pushwooshframework\/pushnotificationmanager\/handlepushaccepted(_:onstart:)"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationManager/additionalAuthorizationOptions":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/additionalAuthorizationOptions","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"additionalAuthorizationOptions","kind":"identifier"},{"kind":"text","text":": "},{"text":"UNAuthorizationOptions","preciseIdentifier":"c:@E@UNAuthorizationOptions","kind":"typeIdentifier"}],"kind":"symbol","title":"additionalAuthorizationOptions","navigatorTitle":[{"text":"additionalAuthorizationOptions","kind":"identifier"}],"url":"\/documentation\/pushwooshframework\/pushnotificationmanager\/additionalauthorizationoptions","role":"symbol","type":"topic","abstract":[{"text":"Authorization options in addition to UNAuthorizationOptionBadge | UNAuthorizationOptionSound | UNAuthorizationOptionAlert | UNAuthorizationOptionCarPlay.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"op":"replace","value":"PushNotificationManager","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"PushNotificationManager"}],"op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"PushNotificationManager"}]},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/additionalAuthorizationOptions","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/appCode","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/appName","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/delegate","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/language","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/launchNotification","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/notificationCenterDelegate","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/showPushnotificationAlert"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/getApnPayload(_:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/getCustomPushData(_:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/getCustomPushData(asNSDict:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/getHWID()","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/getPushToken()","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/handlePushAccepted(_:onStart:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/handlePushReceived(_:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/handlePushRegistration(_:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/handlePushRegistrationFailure(_:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/handlePushRegistrationString(_:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/init(applicationCode:appName:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/init(applicationCode:navController:appName:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/loadTags()","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/loadTags(_:error:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/mergeUserId(_:to:doMerge:completion:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/postEvent(_:withAttributes:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/postEvent(_:withAttributes:completion:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/registerForPushNotifications()","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/sendAppOpen()","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/sendLocation:","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/sendPurchase(_:withPrice:currencyCode:andDate:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/sendSKPaymentTransactions(_:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/setTags(_:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/setTags(_:withCompletion:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/setUserId(_:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/startLocationTracking()","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/stopLocationTracking()","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/unregisterForPushNotifications()","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/unregisterForPushNotifications(completion:)"]},{"title":"Type Methods","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/clearNotificationCenter()","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/getRemoteNotificationStatus()","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/initialize(withAppCode:appName:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/isPushwooshMessage(_:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/push()","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/pushwooshVersion()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"}]},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PushNotificationManager"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1appCode\/title","value":"appCode","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1appCode\/fragments","op":"replace","value":[{"text":"appCode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1postEvent(_:withAttributes:)\/title","op":"replace","value":"postEvent:withAttributes:"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1postEvent(_:withAttributes:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"postEvent:withAttributes:"}],"op":"replace"},{"value":"appName","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1appName\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1appName\/fragments","value":[{"text":"appName","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1clearNotificationCenter()\/title","value":"clearNotificationCenter"},{"value":[{"text":"+ ","kind":"text"},{"text":"clearNotificationCenter","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1clearNotificationCenter()\/fragments"},{"op":"replace","value":"sendPurchase:withPrice:currencyCode:andDate:","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1sendPurchase(_:withPrice:currencyCode:andDate:)\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1sendPurchase(_:withPrice:currencyCode:andDate:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"sendPurchase:withPrice:currencyCode:andDate:","kind":"identifier"}]},{"value":"initializeWithAppCode:appName:","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1initialize(withAppCode:appName:)\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1initialize(withAppCode:appName:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"initializeWithAppCode:appName:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1loadTags(_:error:)\/title","value":"loadTags:error:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"loadTags:error:"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1loadTags(_:error:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1notificationCenterDelegate\/title","value":"notificationCenterDelegate"},{"value":[{"kind":"identifier","text":"notificationCenterDelegate"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1notificationCenterDelegate\/fragments","op":"replace"},{"value":"launchNotification","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1launchNotification\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1launchNotification\/fragments","value":[{"text":"launchNotification","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1isPushwooshMessage(_:)\/title","value":"isPushwooshMessage:","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"text":"isPushwooshMessage:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1isPushwooshMessage(_:)\/fragments"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1stopLocationTracking()\/title","value":"stopLocationTracking","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1stopLocationTracking()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"stopLocationTracking"}]},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1language\/title","op":"replace","value":"language"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1language\/fragments","op":"replace","value":[{"text":"language","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1push()\/title","value":"pushManager"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"pushManager","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1push()\/fragments"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1loadTags()\/title","value":"loadTags","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"loadTags"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1loadTags()\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1showPushnotificationAlert\/title","value":"showPushnotificationAlert"},{"value":[{"text":"showPushnotificationAlert","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1showPushnotificationAlert\/fragments"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1getRemoteNotificationStatus()\/title","op":"replace","value":"getRemoteNotificationStatus"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"getRemoteNotificationStatus"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1getRemoteNotificationStatus()\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1getHWID()\/title","value":"getHWID"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getHWID"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1getHWID()\/fragments"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1unregisterForPushNotifications(completion:)\/title","value":"unregisterForPushNotificationsWithCompletion:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"unregisterForPushNotificationsWithCompletion:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1unregisterForPushNotifications(completion:)\/fragments"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1getCustomPushData(_:)\/title","value":"getCustomPushData:","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1getCustomPushData(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"getCustomPushData:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1postEvent(_:withAttributes:completion:)\/title","value":"postEvent:withAttributes:completion:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"postEvent:withAttributes:completion:"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1postEvent(_:withAttributes:completion:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1getApnPayload(_:)\/title","value":"getApnPayload:"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1getApnPayload(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"getApnPayload:","kind":"identifier"}],"op":"replace"},{"value":"handlePushReceived:","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1handlePushReceived(_:)\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1handlePushReceived(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"handlePushReceived:"}],"op":"replace"},{"op":"replace","value":"sendAppOpen","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1sendAppOpen()\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"sendAppOpen","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1sendAppOpen()\/fragments"},{"value":"pushwooshVersion","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1pushwooshVersion()\/title","op":"replace"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"pushwooshVersion","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1pushwooshVersion()\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1mergeUserId(_:to:doMerge:completion:)\/title","value":"mergeUserId:to:doMerge:completion:"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1mergeUserId(_:to:doMerge:completion:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"mergeUserId:to:doMerge:completion:","kind":"identifier"}]},{"value":"sendSKPaymentTransactions:","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1sendSKPaymentTransactions(_:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"sendSKPaymentTransactions:"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1sendSKPaymentTransactions(_:)\/fragments"},{"value":"startLocationTracking","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1startLocationTracking()\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1startLocationTracking()\/fragments","value":[{"kind":"text","text":"- "},{"text":"startLocationTracking","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1setTags(_:)\/title","value":"setTags:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1setTags(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setTags:"}]},{"value":"PushNotificationManager","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager\/title","op":"replace"},{"value":[{"text":"PushNotificationManager","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager\/fragments","op":"replace"},{"op":"replace","value":"delegate","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1delegate\/title"},{"value":[{"kind":"identifier","text":"delegate"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1delegate\/fragments","op":"replace"},{"value":"unregisterForPushNotifications","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1unregisterForPushNotifications()\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1unregisterForPushNotifications()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"unregisterForPushNotifications","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1handlePushRegistrationString(_:)\/title","value":"handlePushRegistrationString:"},{"value":[{"kind":"text","text":"- "},{"text":"handlePushRegistrationString:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1handlePushRegistrationString(_:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1registerForPushNotifications()\/title","op":"replace","value":"registerForPushNotifications"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1registerForPushNotifications()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"registerForPushNotifications","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1handlePushRegistrationFailure(_:)\/title","value":"handlePushRegistrationFailure:"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1handlePushRegistrationFailure(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"handlePushRegistrationFailure:","kind":"identifier"}]},{"value":"setTags:withCompletion:","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1setTags(_:withCompletion:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1setTags(_:withCompletion:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setTags:withCompletion:"}]},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1getPushToken()\/title","value":"getPushToken","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"getPushToken","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1getPushToken()\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1getCustomPushData(asNSDict:)\/title","value":"getCustomPushDataAsNSDict:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"getCustomPushDataAsNSDict:"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1getCustomPushData(asNSDict:)\/fragments"},{"op":"replace","value":"setUserId:","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1setUserId(_:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"setUserId:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1setUserId(_:)\/fragments"},{"value":"initWithApplicationCode:navController:appName:","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1init(applicationCode:navController:appName:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1init(applicationCode:navController:appName:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithApplicationCode:navController:appName:"}]},{"value":"handlePushRegistration:","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1handlePushRegistration(_:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"handlePushRegistration:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1handlePushRegistration(_:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1init(applicationCode:appName:)\/title","value":"initWithApplicationCode:appName:","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1init(applicationCode:appName:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithApplicationCode:appName:","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"handlePushAccepted:onStart:","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1handlePushAccepted(_:onStart:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"handlePushAccepted:onStart:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1handlePushAccepted(_:onStart:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1additionalAuthorizationOptions\/title","value":"additionalAuthorizationOptions"},{"value":[{"text":"additionalAuthorizationOptions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1additionalAuthorizationOptions\/fragments"}]}]}