{"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PWInbox","kind":"identifier"}],"title":"PWInbox","externalID":"c:objc(cs)PWInbox","modules":[{"name":"PushwooshFramework"}],"symbolKind":"class","roleHeading":"Class","navigatorTitle":[{"text":"PWInbox","kind":"identifier"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"topicSections":[{"title":"Type Methods","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox\/addObserver(forUpdateMessagesCompletion:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox\/addObserverForDidReceive(inPushNotificationCompletion:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox\/addObserverForNoActionPerformedMessagesCount(_:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox\/addObserverForUnreadMessagesCount(_:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox\/deleteAllReadMessages()","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox\/deleteMessages(withCodes:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox\/loadMessages()","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox\/loadMessages(completion:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox\/markAllMessagesAsRead()","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox\/message(forCode:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox\/messagesCount()","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox\/messagesCount(completion:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox\/messagesWithNoActionPerformedCount()","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox\/messagesWithNoActionPerformedCount(completion:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox\/performActionForMessage(withCode:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox\/readMessages(withCodes:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox\/removeObserver(_:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox\/resyncInboxForNewUserId()","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox\/unreadMessagesCount()","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox\/unreadMessagesCount(completion:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox\/updateInbox(forNewUserId:)"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PWInbox","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/pushwooshframework\/pwinbox"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pushwooshframework\/pwinbox"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/objc(cs)NSObject"]},{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)NSObject","doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)PWInboxBridge","doc:\/\/com.pushwoosh.PushwooshiOS\/s7CVarArgP","doc:\/\/com.pushwoosh.PushwooshiOS\/s28CustomDebugStringConvertibleP","doc:\/\/com.pushwoosh.PushwooshiOS\/s23CustomStringConvertibleP","doc:\/\/com.pushwoosh.PushwooshiOS\/SQ","doc:\/\/com.pushwoosh.PushwooshiOS\/SH"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"Conforms to "},{"type":"codeVoice","code":"PWInboxBridge"},{"text":" so optional Swift modules","type":"text"},{"type":"text","text":" "},{"type":"text","text":"(e.g. "},{"type":"codeVoice","code":"PushwooshInboxKit"},{"text":") can reach the storage-backed inbox API","type":"text"},{"type":"text","text":" "},{"type":"text","text":"through "},{"code":"PWManagerBridge.shared.inboxBridge as? PWInboxBridge.Type","type":"codeVoice"},{"text":".","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Without the formal conformance the Swift cast returns "},{"code":"nil","type":"codeVoice"},{"type":"text","text":" at runtime"},{"text":" ","type":"text"},{"text":"and every bridge call silently no-ops — mutations never reach disk.","type":"text"}],"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"]]},"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInbox/message(forCode:)":{"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"messageForCode:","kind":"identifier"}],"title":"message(forCode:)","url":"\/documentation\/pushwooshframework\/pwinbox\/message(forcode:)","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox\/message(forCode:)","abstract":[{"type":"text","text":"Returns a single inbox message identified by its code without loading the"},{"text":" ","type":"text"},{"text":"entire feed. Reads from the local ","type":"text"},{"type":"codeVoice","code":"PWInboxStorage"},{"type":"text","text":" cache. Returns "},{"type":"codeVoice","code":"nil"},{"text":" if","type":"text"},{"text":" ","type":"text"},{"text":"the message has not been seen yet, has been deleted, or has expired.","type":"text"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"message","kind":"identifier"},{"kind":"text","text":"("},{"text":"forCode","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"!) -> (any ","kind":"text"},{"text":"PWInboxMessageProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)PWInboxMessageProtocol"},{"kind":"text","text":")?"}]},"doc://com.pushwoosh.PushwooshiOS/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/s23CustomStringConvertibleP"},"doc://com.pushwoosh.PushwooshiOS/SH":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.pushwoosh.PushwooshiOS/objc(pl)NSObject":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.pushwoosh.PushwooshiOS/SQ":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInbox/deleteAllReadMessages()":{"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"deleteAllReadMessages","kind":"identifier"}],"title":"deleteAllReadMessages()","url":"\/documentation\/pushwooshframework\/pwinbox\/deleteallreadmessages()","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox\/deleteAllReadMessages()","type":"topic","abstract":[{"text":"Deletes every read inbox message in one call. Useful for “Clear read”","type":"text"},{"type":"text","text":" "},{"text":"affordances. Unread and pinned-but-unread messages are preserved.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"deleteAllReadMessages","kind":"identifier"},{"kind":"text","text":"()"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInbox/addObserverForDidReceive(inPushNotificationCompletion:)":{"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"addObserverForDidReceiveInPushNotificationCompletion:"}],"title":"addObserverForDidReceive(inPushNotificationCompletion:)","url":"\/documentation\/pushwooshframework\/pwinbox\/addobserverfordidreceive(inpushnotificationcompletion:)","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox\/addObserverForDidReceive(inPushNotificationCompletion:)","abstract":[{"type":"text","text":"Subscribe for messages arriving with push notifications. @warning You need to unsubscribe by calling the removeObserver method, if you don’t want to receive notifications"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"addObserverForDidReceive"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"inPushNotificationCompletion"},{"text":": (([any ","kind":"text"},{"text":"PWInboxMessageProtocol","preciseIdentifier":"c:objc(pl)PWInboxMessageProtocol","kind":"typeIdentifier"},{"kind":"text","text":"]?) -> "},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")!) -> (any ","kind":"text"},{"text":"NSObjectProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"},{"text":")!","kind":"text"}]},"doc://com.pushwoosh.PushwooshiOS/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/s28CustomDebugStringConvertibleP"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInbox/addObserverForNoActionPerformedMessagesCount(_:)":{"role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox\/addObserverForNoActionPerformedMessagesCount(_:)","abstract":[{"text":"Subscribe for messages with no action performed count changes. @warning You need to unsubscribe by calling the removeObserver method, if you don’t want to receive notifications","type":"text"}],"kind":"symbol","title":"addObserverForNoActionPerformedMessagesCount(_:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"addObserverForNoActionPerformedMessagesCount"},{"text":"(((","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"},{"kind":"text","text":") -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")!) -> (any "},{"text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier"},{"text":")!","kind":"text"}],"type":"topic","url":"\/documentation\/pushwooshframework\/pwinbox\/addobserverfornoactionperformedmessagescount(_:)","navigatorTitle":[{"kind":"identifier","text":"addObserverForNoActionPerformedMessagesCountUsingBlock:"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInbox/addObserverForUnreadMessagesCount(_:)":{"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"addObserverForUnreadMessagesCountUsingBlock:","kind":"identifier"}],"title":"addObserverForUnreadMessagesCount(_:)","url":"\/documentation\/pushwooshframework\/pwinbox\/addobserverforunreadmessagescount(_:)","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox\/addObserverForUnreadMessagesCount(_:)","abstract":[{"text":"Subscribe for unread messages count changes. @warning You need to unsubscribe by calling the removeObserver method, if you don’t want to receive notifications","type":"text"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"addObserverForUnreadMessagesCount","kind":"identifier"},{"text":"(((","kind":"text"},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")!) -> (any "},{"text":"NSObjectProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"},{"kind":"text","text":")!"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"type":"topic","abstract":[{"type":"text","text":"Push notification SDK for iOS applications."}],"title":"PushwooshFramework","kind":"symbol","url":"\/documentation\/pushwooshframework","role":"collection","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInbox/markAllMessagesAsRead()":{"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"markAllMessagesAsRead"}],"title":"markAllMessagesAsRead()","url":"\/documentation\/pushwooshframework\/pwinbox\/markallmessagesasread()","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox\/markAllMessagesAsRead()","abstract":[{"type":"text","text":"Marks every currently-stored unread inbox message as read in a single call."},{"text":" ","type":"text"},{"type":"text","text":"Convenience over filtering the result of "},{"type":"codeVoice","code":"loadMessagesWithCompletion:"},{"text":" and","type":"text"},{"type":"text","text":" "},{"text":"calling ","type":"text"},{"type":"codeVoice","code":"readMessagesWithCodes:"},{"type":"text","text":" yourself."}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"markAllMessagesAsRead","kind":"identifier"},{"kind":"text","text":"()"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInbox/addObserver(forUpdateMessagesCompletion:)":{"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"addObserverForUpdateInboxMessagesCompletion:","kind":"identifier"}],"title":"addObserver(forUpdateMessagesCompletion:)","url":"\/documentation\/pushwooshframework\/pwinbox\/addobserver(forupdatemessagescompletion:)","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox\/addObserver(forUpdateMessagesCompletion:)","type":"topic","abstract":[{"type":"text","text":"Subscribe for messages arriving when a message is deleted, added, or updated. @warning You need to unsubscribe by calling the removeObserver method, if you don’t want to receive notifications"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addObserver","kind":"identifier"},{"kind":"text","text":"("},{"text":"forUpdateMessagesCompletion","kind":"externalParam"},{"text":": (([any ","kind":"text"},{"kind":"typeIdentifier","text":"PWInboxMessageProtocol","preciseIdentifier":"c:objc(pl)PWInboxMessageProtocol"},{"text":"]?, [any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)PWInboxMessageProtocol","kind":"typeIdentifier","text":"PWInboxMessageProtocol"},{"kind":"text","text":"]?, [any "},{"text":"PWInboxMessageProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)PWInboxMessageProtocol"},{"kind":"text","text":"]?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")!) -> (any "},{"text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier"},{"text":")!","kind":"text"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInbox/deleteMessages(withCodes:)":{"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"deleteMessagesWithCodes:","kind":"identifier"}],"title":"deleteMessages(withCodes:)","url":"\/documentation\/pushwooshframework\/pwinbox\/deletemessages(withcodes:)","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox\/deleteMessages(withCodes:)","type":"topic","abstract":[{"text":"Call this method, when the user deletes the list of InboxMessageProtocol manually","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"deleteMessages","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withCodes"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"]!)","kind":"text"}]},"doc://com.pushwoosh.PushwooshiOS/objc(cs)NSObject":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInbox/loadMessages(completion:)":{"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"loadMessagesWithCompletion:","kind":"identifier"}],"title":"loadMessages(completion:)","url":"\/documentation\/pushwooshframework\/pwinbox\/loadmessages(completion:)","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox\/loadMessages(completion:)","abstract":[{"text":"Get the collection of the PWInboxMessageProtocol that the user received","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"loadMessages","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (([any "},{"text":"PWInboxMessageProtocol","preciseIdentifier":"c:objc(pl)PWInboxMessageProtocol","kind":"typeIdentifier"},{"text":"]?, (any ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"kind":"text","text":")?) -> "},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")!)","kind":"text"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInbox/unreadMessagesCount()":{"role":"symbol","kind":"symbol","title":"unreadMessagesCount()","url":"\/documentation\/pushwooshframework\/pwinbox\/unreadmessagescount()","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox\/unreadMessagesCount()","type":"topic","abstract":[{"text":"Returns the count of unread messages. Async wrapper around","type":"text"},{"type":"text","text":" "},{"type":"codeVoice","code":"unreadMessagesCountWithCompletion(_:)"},{"text":".","type":"text"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unreadMessagesCount"},{"text":"() ","kind":"text"},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"text":"throws","kind":"keyword"},{"kind":"text","text":" -> "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInbox/messagesWithNoActionPerformedCount()":{"role":"symbol","kind":"symbol","title":"messagesWithNoActionPerformedCount()","url":"\/documentation\/pushwooshframework\/pwinbox\/messageswithnoactionperformedcount()","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox\/messagesWithNoActionPerformedCount()","abstract":[{"text":"Returns the count of messages whose action has not yet been performed.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"messagesWithNoActionPerformedCount","kind":"identifier"},{"kind":"text","text":"() "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInbox/performActionForMessage(withCode:)":{"kind":"symbol","navigatorTitle":[{"text":"performActionForMessageWithCode:","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Call this method, when the user clicks on the InboxMessageProtocol and the message’s action is performed","type":"text"}],"url":"\/documentation\/pushwooshframework\/pwinbox\/performactionformessage(withcode:)","title":"performActionForMessage(withCode:)","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox\/performActionForMessage(withCode:)","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"performActionForMessage"},{"text":"(","kind":"text"},{"text":"withCode","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"!)","kind":"text"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInbox/messagesCount(completion:)":{"type":"topic","url":"\/documentation\/pushwooshframework\/pwinbox\/messagescount(completion:)","title":"messagesCount(completion:)","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"messagesCount"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"text":": ((","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"text":", (any ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"text":")?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")!)","kind":"text"}],"abstract":[{"type":"text","text":"Get the total number of the PWInboxMessageProtocol"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox\/messagesCount(completion:)","navigatorTitle":[{"text":"messagesCountWithCompletion:","kind":"identifier"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInbox/unreadMessagesCount(completion:)":{"type":"topic","url":"\/documentation\/pushwooshframework\/pwinbox\/unreadmessagescount(completion:)","navigatorTitle":[{"text":"unreadMessagesCountWithCompletion:","kind":"identifier"}],"kind":"symbol","role":"symbol","abstract":[{"text":"Get the number of the unread PWInboxMessageProtocol","type":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox\/unreadMessagesCount(completion:)","title":"unreadMessagesCount(completion:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"unreadMessagesCount"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": ((","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", (any ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"kind":"text","text":")?) -> "},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")!)","kind":"text"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInbox/readMessages(withCodes:)":{"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"readMessagesWithCodes:","kind":"identifier"}],"title":"readMessages(withCodes:)","url":"\/documentation\/pushwooshframework\/pwinbox\/readmessages(withcodes:)","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox\/readMessages(withCodes:)","type":"topic","abstract":[{"text":"Call this method to mark the list of InboxMessageProtocol as read","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"readMessages"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withCodes"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"]!)"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInbox":{"title":"PWInbox","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PWInbox","kind":"identifier"}],"url":"\/documentation\/pushwooshframework\/pwinbox","navigatorTitle":[{"kind":"identifier","text":"PWInbox"}],"abstract":[{"type":"text","text":"Conforms to "},{"code":"PWInboxBridge","type":"codeVoice"},{"text":" so optional Swift modules","type":"text"},{"text":" ","type":"text"},{"text":"(e.g. ","type":"text"},{"code":"PushwooshInboxKit","type":"codeVoice"},{"type":"text","text":") can reach the storage-backed inbox API"},{"text":" ","type":"text"},{"type":"text","text":"through "},{"code":"PWManagerBridge.shared.inboxBridge as? PWInboxBridge.Type","type":"codeVoice"},{"text":".","type":"text"},{"type":"text","text":" "},{"text":"Without the formal conformance the Swift cast returns ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":" at runtime","type":"text"},{"type":"text","text":" "},{"type":"text","text":"and every bridge call silently no-ops — mutations never reach disk."}],"type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInbox/loadMessages()":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loadMessages","kind":"identifier"},{"text":"() ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"kind":"text","text":" -> ["},{"preciseIdentifier":"c:objc(pl)PWInboxMessageProtocol","text":"PWInboxMessageProtocol","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"url":"\/documentation\/pushwooshframework\/pwinbox\/loadmessages()","kind":"symbol","title":"loadMessages()","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox\/loadMessages()","role":"symbol","abstract":[{"text":"Loads every inbox message currently visible to the user (cached +","type":"text"},{"text":" ","type":"text"},{"text":"freshly merged from the server). Maps the completion-based","type":"text"},{"text":" ","type":"text"},{"code":"loadMessagesWithCompletion(_:)","type":"codeVoice"},{"type":"text","text":" into an async throwing call."}],"type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInbox/removeObserver(_:)":{"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"removeObserver:","kind":"identifier"}],"title":"removeObserver(_:)","url":"\/documentation\/pushwooshframework\/pwinbox\/removeobserver(_:)","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox\/removeObserver(_:)","abstract":[{"type":"text","text":"Unsubscribes from notifications"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"removeObserver"},{"kind":"text","text":"((any "},{"preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier","text":"NSObjectProtocol"},{"text":")!)","kind":"text"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInbox/updateInbox(forNewUserId:)":{"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"updateInboxForNewUserId:","kind":"identifier"}],"title":"updateInbox(forNewUserId:)","url":"\/documentation\/pushwooshframework\/pwinbox\/updateinbox(fornewuserid:)","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox\/updateInbox(forNewUserId:)","type":"topic","abstract":[{"type":"text","text":"updates observers"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"updateInbox"},{"kind":"text","text":"("},{"text":"forNewUserId","kind":"externalParam"},{"kind":"text","text":": (("},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")!)"}]},"doc://com.pushwoosh.PushwooshiOS/objc(pl)PWInboxBridge":{"type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)PWInboxBridge","title":"PWInboxBridge"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInbox/messagesCount()":{"title":"messagesCount()","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"messagesCount","kind":"identifier"},{"kind":"text","text":"() "},{"kind":"keyword","text":"async"},{"text":" ","kind":"text"},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"type":"topic","abstract":[{"type":"text","text":"Returns the total number of stored messages."}],"url":"\/documentation\/pushwooshframework\/pwinbox\/messagescount()","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox\/messagesCount()"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInbox/messagesWithNoActionPerformedCount(completion:)":{"title":"messagesWithNoActionPerformedCount(completion:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"messagesWithNoActionPerformedCount"},{"kind":"text","text":"("},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (("},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", (any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")!)","kind":"text"}],"type":"topic","navigatorTitle":[{"text":"messagesWithNoActionPerformedCountWithCompletion:","kind":"identifier"}],"abstract":[{"type":"text","text":"Get the number of the PWInboxMessageProtocol with no action performed"}],"kind":"symbol","url":"\/documentation\/pushwooshframework\/pwinbox\/messageswithnoactionperformedcount(completion:)","role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox\/messagesWithNoActionPerformedCount(completion:)"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInbox/resyncInboxForNewUserId()":{"title":"resyncInboxForNewUserId()","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"resyncInboxForNewUserId","kind":"identifier"},{"kind":"text","text":"() "},{"kind":"keyword","text":"async"},{"text":" -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"}],"type":"topic","abstract":[{"type":"text","text":"Re-syncs the inbox after the user identity changes. Returns the new"},{"text":" ","type":"text"},{"text":"message count once the sync completes. No throwing variant — the","type":"text"},{"type":"text","text":" "},{"type":"text","text":"underlying API does not surface errors."}],"url":"\/documentation\/pushwooshframework\/pwinbox\/resyncinboxfornewuserid()","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox\/resyncInboxForNewUserId()"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"path":"\/metadata\/title","value":"PWInbox","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"PWInbox"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"PWInbox"}]},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox\/addObserver(forUpdateMessagesCompletion:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox\/addObserverForDidReceive(inPushNotificationCompletion:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox\/addObserverForNoActionPerformedMessagesCount(_:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox\/addObserverForUnreadMessagesCount(_:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox\/deleteAllReadMessages()","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox\/deleteMessages(withCodes:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox\/loadMessages(completion:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox\/markAllMessagesAsRead()","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox\/message(forCode:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox\/messagesCount(completion:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox\/messagesWithNoActionPerformedCount(completion:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox\/performActionForMessage(withCode:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox\/readMessages(withCodes:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox\/removeObserver(_:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox\/unreadMessagesCount(completion:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox\/updateInbox(forNewUserId:)"],"title":"Type Methods"}],"op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/objc(cs)NSObject"]},{"type":"conformsTo","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)PWInboxBridge"],"title":"Conforms To","kind":"relationships"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PWInbox"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInbox~1message(forCode:)\/title","value":"messageForCode:"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInbox~1message(forCode:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"messageForCode:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInbox~1deleteAllReadMessages()\/title","value":"deleteAllReadMessages"},{"value":[{"text":"+ ","kind":"text"},{"text":"deleteAllReadMessages","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInbox~1deleteAllReadMessages()\/fragments","op":"replace"},{"value":"addObserverForDidReceiveInPushNotificationCompletion:","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInbox~1addObserverForDidReceive(inPushNotificationCompletion:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInbox~1addObserverForDidReceive(inPushNotificationCompletion:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"addObserverForDidReceiveInPushNotificationCompletion:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInbox~1addObserverForNoActionPerformedMessagesCount(_:)\/title","value":"addObserverForNoActionPerformedMessagesCountUsingBlock:"},{"value":[{"text":"+ ","kind":"text"},{"text":"addObserverForNoActionPerformedMessagesCountUsingBlock:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInbox~1addObserverForNoActionPerformedMessagesCount(_:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInbox~1addObserverForUnreadMessagesCount(_:)\/title","value":"addObserverForUnreadMessagesCountUsingBlock:"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInbox~1addObserverForUnreadMessagesCount(_:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"addObserverForUnreadMessagesCountUsingBlock:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInbox~1markAllMessagesAsRead()\/title","value":"markAllMessagesAsRead"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInbox~1markAllMessagesAsRead()\/fragments","value":[{"kind":"text","text":"+ "},{"text":"markAllMessagesAsRead","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInbox~1addObserver(forUpdateMessagesCompletion:)\/title","value":"addObserverForUpdateInboxMessagesCompletion:"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInbox~1addObserver(forUpdateMessagesCompletion:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"addObserverForUpdateInboxMessagesCompletion:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInbox~1deleteMessages(withCodes:)\/title","value":"deleteMessagesWithCodes:","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"deleteMessagesWithCodes:"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInbox~1deleteMessages(withCodes:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInbox~1loadMessages(completion:)\/title","value":"loadMessagesWithCompletion:"},{"value":[{"kind":"text","text":"+ "},{"text":"loadMessagesWithCompletion:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInbox~1loadMessages(completion:)\/fragments"},{"value":"performActionForMessageWithCode:","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInbox~1performActionForMessage(withCode:)\/title","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"performActionForMessageWithCode:"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInbox~1performActionForMessage(withCode:)\/fragments"},{"value":"messagesCountWithCompletion:","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInbox~1messagesCount(completion:)\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInbox~1messagesCount(completion:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"messagesCountWithCompletion:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInbox~1unreadMessagesCount(completion:)\/title","value":"unreadMessagesCountWithCompletion:","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"text":"unreadMessagesCountWithCompletion:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInbox~1unreadMessagesCount(completion:)\/fragments"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInbox~1readMessages(withCodes:)\/title","value":"readMessagesWithCodes:","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"readMessagesWithCodes:"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInbox~1readMessages(withCodes:)\/fragments"},{"value":"PWInbox","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInbox\/title"},{"value":[{"text":"PWInbox","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInbox\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInbox~1removeObserver(_:)\/title","value":"removeObserver:"},{"value":[{"text":"+ ","kind":"text"},{"text":"removeObserver:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInbox~1removeObserver(_:)\/fragments","op":"replace"},{"value":"updateInboxForNewUserId:","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInbox~1updateInbox(forNewUserId:)\/title"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"updateInboxForNewUserId:"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInbox~1updateInbox(forNewUserId:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInbox~1messagesWithNoActionPerformedCount(completion:)\/title","value":"messagesWithNoActionPerformedCountWithCompletion:"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInbox~1messagesWithNoActionPerformedCount(completion:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"messagesWithNoActionPerformedCountWithCompletion:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}