{"sections":[],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"PWMessagingDelegate","kind":"identifier"}],"symbolKind":"protocol","modules":[{"name":"PushwooshFramework"}],"externalID":"c:objc(pl)PWMessagingDelegate","role":"symbol","title":"PWMessagingDelegate","roleHeading":"Protocol","navigatorTitle":[{"text":"PWMessagingDelegate","kind":"identifier"}]},"topicSections":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWMessagingDelegate\/pushwoosh(_:onMessageReceived:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWMessagingDelegate\/pushwoosh(_:onMessageOpened:)"],"title":"Handling Notifications"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWMessagingDelegate"},"abstract":[{"type":"text","text":"Delegate protocol for handling push notification events."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PWMessagingDelegate"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier","text":"NSObjectProtocol"}]}]},{"content":[{"text":"Discussion","level":2,"anchor":"Discussion","type":"heading"},{"inlineContent":[{"text":"The ","type":"text"},{"code":"PWMessagingDelegate","type":"codeVoice"},{"type":"text","text":" protocol defines methods that notify your app about push notification lifecycle events. Implement these methods to respond to notifications being received and opened by users."}],"type":"paragraph"},{"level":2,"type":"heading","text":"Overview","anchor":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This protocol provides two key notification events:"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"When a push notification arrives (received)"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"When a user taps on a push notification (opened)"}]}]}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Both methods are called with a "},{"type":"codeVoice","code":"PWMessage"},{"type":"text","text":" object containing the notification payload and metadata."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Set your delegate on the shared Pushwoosh instance:"}]},{"syntax":"swift","type":"codeListing","code":["Pushwoosh.sharedInstance().delegate = self"]},{"type":"paragraph","inlineContent":[{"text":"Both methods are optional. Implement only the events you need to handle.","type":"text"}]}],"kind":"content"}],"variants":[{"paths":["\/documentation\/pushwooshframework\/pwmessagingdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pushwooshframework\/pwmessagingdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)NSObject"],"type":"inheritsFrom","title":"Inherits From"}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"]]},"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWMessagingDelegate":{"abstract":[{"type":"text","text":"Delegate protocol for handling push notification events."}],"type":"topic","title":"PWMessagingDelegate","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWMessagingDelegate","role":"symbol","url":"\/documentation\/pushwooshframework\/pwmessagingdelegate","kind":"symbol","navigatorTitle":[{"text":"PWMessagingDelegate","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"PWMessagingDelegate","kind":"identifier"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWMessagingDelegate/pushwoosh(_:onMessageReceived:)":{"url":"\/documentation\/pushwooshframework\/pwmessagingdelegate\/pushwoosh(_:onmessagereceived:)","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWMessagingDelegate\/pushwoosh(_:onMessageReceived:)","role":"symbol","title":"pushwoosh(_:onMessageReceived:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"pushwoosh","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)Pushwoosh","text":"Pushwoosh","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"onMessageReceived"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)PWMessage","text":"PWMessage","kind":"typeIdentifier"},{"kind":"text","text":")"}],"abstract":[{"text":"Called when the application receives a push notification.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"pushwoosh:onMessageReceived:"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWMessagingDelegate/pushwoosh(_:onMessageOpened:)":{"url":"\/documentation\/pushwooshframework\/pwmessagingdelegate\/pushwoosh(_:onmessageopened:)","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWMessagingDelegate\/pushwoosh(_:onMessageOpened:)","role":"symbol","title":"pushwoosh(_:onMessageOpened:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"pushwoosh","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"Pushwoosh","preciseIdentifier":"c:objc(cs)Pushwoosh"},{"text":", ","kind":"text"},{"text":"onMessageOpened","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)PWMessage","text":"PWMessage","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"text":"Called when the user taps on a push notification.","type":"text"}],"navigatorTitle":[{"text":"pushwoosh:onMessageOpened:","kind":"identifier"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"kind":"symbol","abstract":[],"url":"\/documentation\/pushwooshframework","role":"collection","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","title":"PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)NSObject"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Protocol","path":"\/metadata\/roleHeading"},{"value":"PWMessagingDelegate","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"protocol","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"PWMessagingDelegate","kind":"identifier"}]},{"value":[{"text":"PWMessagingDelegate","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWMessagingDelegate\/pushwoosh(_:onMessageReceived:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWMessagingDelegate\/pushwoosh(_:onMessageOpened:)"],"title":"Handling Notifications"}],"op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)NSObject"],"title":"Inherits From","type":"inheritsFrom"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PWMessagingDelegate"},{"text":" <","kind":"text"},{"preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier","text":"NSObject"},{"text":">","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWMessagingDelegate\/title","value":"PWMessagingDelegate"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWMessagingDelegate\/fragments","value":[{"kind":"identifier","text":"PWMessagingDelegate"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWMessagingDelegate~1pushwoosh(_:onMessageReceived:)\/title","value":"pushwoosh:onMessageReceived:"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWMessagingDelegate~1pushwoosh(_:onMessageReceived:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"pushwoosh:onMessageReceived:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWMessagingDelegate~1pushwoosh(_:onMessageOpened:)\/title","value":"pushwoosh:onMessageOpened:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"pushwoosh:onMessageOpened:"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWMessagingDelegate~1pushwoosh(_:onMessageOpened:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}