{"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pwnotificationcenterdelegateproxy"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pwnotificationcenterdelegateproxy"]}],"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWNotificationCenterDelegateProxy\/defaultNotificationCenterDelegate"]},{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWNotificationCenterDelegateProxy\/add(_:)"],"title":"Instance Methods"}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"]]},"kind":"symbol","relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/objc(cs)NSObject"],"title":"Inherits From"},{"kind":"relationships","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)NSObject","doc:\/\/com.pushwoosh.PushwooshiOS\/s7CVarArgP","doc:\/\/com.pushwoosh.PushwooshiOS\/s28CustomDebugStringConvertibleP","doc:\/\/com.pushwoosh.PushwooshiOS\/s23CustomStringConvertibleP","doc:\/\/com.pushwoosh.PushwooshiOS\/SQ","doc:\/\/com.pushwoosh.PushwooshiOS\/SH","doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)UNUserNotificationCenterDelegate"],"title":"Conforms To","type":"conformsTo"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PWNotificationCenterDelegateProxy"}],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWNotificationCenterDelegateProxy","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Class","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PWNotificationCenterDelegateProxy"}],"symbolKind":"class","externalID":"c:objc(cs)PWNotificationCenterDelegateProxy","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PWNotificationCenterDelegateProxy","kind":"identifier"}],"modules":[{"name":"PushwooshFramework"}],"title":"PWNotificationCenterDelegateProxy"},"sections":[],"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWNotificationCenterDelegateProxy":{"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PWNotificationCenterDelegateProxy"}],"url":"\/documentation\/pushwooshframework\/pwnotificationcenterdelegateproxy","type":"topic","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PWNotificationCenterDelegateProxy"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWNotificationCenterDelegateProxy","title":"PWNotificationCenterDelegateProxy"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWNotificationCenterDelegateProxy/defaultNotificationCenterDelegate":{"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"defaultNotificationCenterDelegate"}],"url":"\/documentation\/pushwooshframework\/pwnotificationcenterdelegateproxy\/defaultnotificationcenterdelegate","type":"topic","abstract":[{"type":"text","text":"Returns UNUserNotificationCenterDelegate that handles foreground push notifications on iOS10"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"defaultNotificationCenterDelegate"},{"kind":"text","text":": any "},{"text":"UNUserNotificationCenterDelegate","preciseIdentifier":"c:objc(pl)UNUserNotificationCenterDelegate","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWNotificationCenterDelegateProxy\/defaultNotificationCenterDelegate","title":"defaultNotificationCenterDelegate"},"doc://com.pushwoosh.PushwooshiOS/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"abstract":[{"text":"Push notification SDK for iOS applications.","type":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","type":"topic","title":"PushwooshFramework","url":"\/documentation\/pushwooshframework","kind":"symbol","role":"collection"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWNotificationCenterDelegateProxy/add(_:)":{"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"addNotificationCenterDelegate:"}],"url":"\/documentation\/pushwooshframework\/pwnotificationcenterdelegateproxy\/add(_:)","type":"topic","abstract":[{"type":"text","text":"Adds extra UNUserNotificationCenterDelegate that handles foreground push notifications on iOS10."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"add","kind":"identifier"},{"kind":"text","text":"(any "},{"kind":"typeIdentifier","text":"UNUserNotificationCenterDelegate","preciseIdentifier":"c:objc(pl)UNUserNotificationCenterDelegate"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWNotificationCenterDelegateProxy\/add(_:)","title":"add(_:)"},"doc://com.pushwoosh.PushwooshiOS/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/objc(cs)NSObject","title":"NSObject"},"doc://com.pushwoosh.PushwooshiOS/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/SQ","title":"Swift.Equatable"},"doc://com.pushwoosh.PushwooshiOS/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.pushwoosh.PushwooshiOS/SH":{"type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/SH","title":"Swift.Hashable"},"doc://com.pushwoosh.PushwooshiOS/objc(pl)UNUserNotificationCenterDelegate":{"type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)UNUserNotificationCenterDelegate","title":"UNUserNotificationCenterDelegate"},"doc://com.pushwoosh.PushwooshiOS/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.pushwoosh.PushwooshiOS/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"PWNotificationCenterDelegateProxy"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","value":[{"kind":"identifier","text":"PWNotificationCenterDelegateProxy"}],"path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"PWNotificationCenterDelegateProxy"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWNotificationCenterDelegateProxy\/defaultNotificationCenterDelegate"],"title":"Instance Properties"},{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWNotificationCenterDelegateProxy\/add(_:)"],"title":"Instance Methods"}],"op":"replace","path":"\/topicSections"},{"op":"replace","value":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/objc(cs)NSObject"]},{"type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)UNUserNotificationCenterDelegate"],"title":"Conforms To"}],"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"PWNotificationCenterDelegateProxy","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"PWNotificationCenterDelegateProxy","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWNotificationCenterDelegateProxy\/title"},{"value":[{"kind":"identifier","text":"PWNotificationCenterDelegateProxy"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWNotificationCenterDelegateProxy\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWNotificationCenterDelegateProxy~1defaultNotificationCenterDelegate\/title","value":"defaultNotificationCenterDelegate"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWNotificationCenterDelegateProxy~1defaultNotificationCenterDelegate\/fragments","value":[{"kind":"identifier","text":"defaultNotificationCenterDelegate"}],"op":"replace"},{"op":"replace","value":"addNotificationCenterDelegate:","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWNotificationCenterDelegateProxy~1add(_:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"addNotificationCenterDelegate:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWNotificationCenterDelegateProxy~1add(_:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}