{"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/objc(cs)NSObject"]},{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)NSObject","doc:\/\/com.pushwoosh.PushwooshiOS\/s7CVarArgP","doc:\/\/com.pushwoosh.PushwooshiOS\/s28CustomDebugStringConvertibleP","doc:\/\/com.pushwoosh.PushwooshiOS\/s23CustomStringConvertibleP","doc:\/\/com.pushwoosh.PushwooshiOS\/SQ","doc:\/\/com.pushwoosh.PushwooshiOS\/SH"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWNotificationExtensionManager"},"metadata":{"symbolKind":"class","title":"PWNotificationExtensionManager","modules":[{"name":"PushwooshFramework"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PWNotificationExtensionManager","kind":"identifier"}],"navigatorTitle":[{"text":"PWNotificationExtensionManager","kind":"identifier"}],"externalID":"c:objc(cs)PWNotificationExtensionManager","roleHeading":"Class"},"sections":[],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWNotificationExtensionManager\/handle(_:contentHandler:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWNotificationExtensionManager\/handle(_:withAppGroups:contentHandler:)"]},{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWNotificationExtensionManager\/shared()"],"title":"Type Methods"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PWNotificationExtensionManager","kind":"identifier"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/pushwooshframework\/pwnotificationextensionmanager"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pushwooshframework\/pwnotificationextensionmanager"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.pushwoosh.PushwooshiOS/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/objc(cs)NSObject"},"doc://com.pushwoosh.PushwooshiOS/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/s28CustomDebugStringConvertibleP"},"doc://com.pushwoosh.PushwooshiOS/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/SH"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWNotificationExtensionManager":{"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PWNotificationExtensionManager"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWNotificationExtensionManager","navigatorTitle":[{"text":"PWNotificationExtensionManager","kind":"identifier"}],"type":"topic","title":"PWNotificationExtensionManager","url":"\/documentation\/pushwooshframework\/pwnotificationextensionmanager","abstract":[]},"doc://com.pushwoosh.PushwooshiOS/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)NSObject"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWNotificationExtensionManager/handle(_:contentHandler:)":{"navigatorTitle":[{"text":"handleNotificationRequest:contentHandler:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"handle","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UNNotificationRequest","text":"UNNotificationRequest"},{"kind":"text","text":", "},{"text":"contentHandler","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"UNNotificationContent","preciseIdentifier":"c:objc(cs)UNNotificationContent","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/pushwooshframework\/pwnotificationextensionmanager\/handle(_:contenthandler:)","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWNotificationExtensionManager\/handle(_:contentHandler:)","title":"handle(_:contentHandler:)","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Sends message delivery event to Pushwoosh and downloads media attachment. Call it from UNNotificationServiceExtension. Don’t forget to set Pushwoosh_APPID in extension Info.plist."}],"type":"topic"},"doc://com.pushwoosh.PushwooshiOS/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/s7CVarArgP"},"doc://com.pushwoosh.PushwooshiOS/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/SQ"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWNotificationExtensionManager/shared()":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"shared"},{"text":"() -> ","kind":"text"},{"text":"Self","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"sharedManager"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWNotificationExtensionManager\/shared()","title":"shared()","abstract":[],"url":"\/documentation\/pushwooshframework\/pwnotificationextensionmanager\/shared()","kind":"symbol","role":"symbol"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWNotificationExtensionManager/handle(_:withAppGroups:contentHandler:)":{"kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWNotificationExtensionManager\/handle(_:withAppGroups:contentHandler:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"handle"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UNNotificationRequest","text":"UNNotificationRequest"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"withAppGroups"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"contentHandler","kind":"externalParam"},{"kind":"text","text":": ("},{"text":"UNNotificationContent","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UNNotificationContent"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")"}],"abstract":[{"text":"Example:","type":"text"}],"navigatorTitle":[{"text":"handleNotificationRequest:withAppGroups:contentHandler:","kind":"identifier"}],"url":"\/documentation\/pushwooshframework\/pwnotificationextensionmanager\/handle(_:withappgroups:contenthandler:)","type":"topic","title":"handle(_:withAppGroups:contentHandler:)","role":"symbol"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"abstract":[{"text":"Push notification SDK for iOS applications.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","title":"PushwooshFramework","role":"collection","url":"\/documentation\/pushwooshframework","kind":"symbol"},"doc://com.pushwoosh.PushwooshiOS/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"value":"PWNotificationExtensionManager","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"PWNotificationExtensionManager","kind":"identifier"}]},{"op":"replace","value":[{"text":"PWNotificationExtensionManager","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWNotificationExtensionManager\/handle(_:contentHandler:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWNotificationExtensionManager\/handle(_:withAppGroups:contentHandler:)"]},{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWNotificationExtensionManager\/shared()"],"title":"Type Methods"}],"op":"replace","path":"\/topicSections"},{"value":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/objc(cs)NSObject"]}],"op":"replace","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"PWNotificationExtensionManager","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWNotificationExtensionManager\/title","op":"replace","value":"PWNotificationExtensionManager"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWNotificationExtensionManager\/fragments","value":[{"kind":"identifier","text":"PWNotificationExtensionManager"}]},{"value":"handleNotificationRequest:contentHandler:","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWNotificationExtensionManager~1handle(_:contentHandler:)\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWNotificationExtensionManager~1handle(_:contentHandler:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"handleNotificationRequest:contentHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWNotificationExtensionManager~1shared()\/title","value":"sharedManager"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"sharedManager"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWNotificationExtensionManager~1shared()\/fragments","op":"replace"},{"op":"replace","value":"handleNotificationRequest:withAppGroups:contentHandler:","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWNotificationExtensionManager~1handle(_:withAppGroups:contentHandler:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWNotificationExtensionManager~1handle(_:withAppGroups:contentHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"handleNotificationRequest:withAppGroups:contentHandler:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}