{"topicSections":[{"title":"Product Information","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWPurchaseDelegate\/onPW(inAppPurchaseHelperProducts:)"]},{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWPurchaseDelegate\/onPW(inAppPurchaseHelperPaymentComplete:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWPurchaseDelegate\/onPW(inAppPurchaseHelperPaymentFailedProductIdentifier:error:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWPurchaseDelegate\/onPW(inAppPurchaseHelperCallPromotedPurchase:)"],"title":"Purchase Events"},{"title":"Restore Transactions","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWPurchaseDelegate\/onPW(inAppPurchaseHelperRestoreCompletedTransactionsFailed:)"]}],"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWPurchaseDelegate","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"relationshipsSections":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"}],"metadata":{"roleHeading":"Protocol","navigatorTitle":[{"kind":"identifier","text":"PWPurchaseDelegate"}],"externalID":"c:objc(pl)PWPurchaseDelegate","symbolKind":"protocol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"PWPurchaseDelegate","kind":"identifier"}],"title":"PWPurchaseDelegate","modules":[{"name":"PushwooshFramework"}],"role":"symbol"},"abstract":[{"type":"text","text":"Delegate protocol for handling in-app purchase events from rich media."}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"]]},"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"PWPurchaseDelegate","kind":"identifier"},{"kind":"text","text":" : "},{"text":"NSObjectProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"}]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","anchor":"Discussion","level":2,"text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"PWPurchaseDelegate"},{"text":" protocol defines methods for responding to in-app purchase events initiated from Pushwoosh rich media notifications. These methods provide callbacks for successful purchases, failed payments, and other purchase-related events.","type":"text"}]},{"inlineContent":[{"text":"Implement these methods to handle purchase flow and update your app’s state accordingly.","type":"text"}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"text":"Set your purchase delegate on the shared Pushwoosh instance:","type":"text"}]},{"syntax":"swift","code":["Pushwoosh.sharedInstance().purchaseDelegate = self"],"type":"codeListing"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pwpurchasedelegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pwpurchasedelegate"]}],"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWPurchaseDelegate/onPW(inAppPurchaseHelperPaymentComplete:)":{"navigatorTitle":[{"text":"onPWInAppPurchaseHelperPaymentComplete:","kind":"identifier"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onPW"},{"text":"(","kind":"text"},{"text":"inAppPurchaseHelperPaymentComplete","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWPurchaseDelegate\/onPW(inAppPurchaseHelperPaymentComplete:)","abstract":[{"type":"text","text":"Tells the delegate that the transaction is in queue and the user has been charged."}],"kind":"symbol","url":"\/documentation\/pushwooshframework\/pwpurchasedelegate\/onpw(inapppurchasehelperpaymentcomplete:)","title":"onPW(inAppPurchaseHelperPaymentComplete:)","role":"symbol"},"doc://com.pushwoosh.PushwooshiOS/objc(pl)NSObject":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWPurchaseDelegate/onPW(inAppPurchaseHelperPaymentFailedProductIdentifier:error:)":{"navigatorTitle":[{"kind":"identifier","text":"onPWInAppPurchaseHelperPaymentFailedProductIdentifier:error:"}],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onPW","kind":"identifier"},{"text":"(","kind":"text"},{"text":"inAppPurchaseHelperPaymentFailedProductIdentifier","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?, ","kind":"text"},{"text":"error","kind":"externalParam"},{"kind":"text","text":": (any "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")?)","kind":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWPurchaseDelegate\/onPW(inAppPurchaseHelperPaymentFailedProductIdentifier:error:)","abstract":[{"type":"text","text":"Tells the delegate that the transaction was cancelled or failed before being added to the server queue."}],"kind":"symbol","url":"\/documentation\/pushwooshframework\/pwpurchasedelegate\/onpw(inapppurchasehelperpaymentfailedproductidentifier:error:)","title":"onPW(inAppPurchaseHelperPaymentFailedProductIdentifier:error:)","role":"symbol"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWPurchaseDelegate/onPW(inAppPurchaseHelperProducts:)":{"navigatorTitle":[{"text":"onPWInAppPurchaseHelperProducts:","kind":"identifier"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onPW"},{"text":"(","kind":"text"},{"text":"inAppPurchaseHelperProducts","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKProduct","text":"SKProduct"},{"text":"]?)","kind":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWPurchaseDelegate\/onPW(inAppPurchaseHelperProducts:)","abstract":[{"type":"text","text":"Tells the delegate that the application received the array of products."}],"kind":"symbol","title":"onPW(inAppPurchaseHelperProducts:)","url":"\/documentation\/pushwooshframework\/pwpurchasedelegate\/onpw(inapppurchasehelperproducts:)","role":"symbol"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWPurchaseDelegate":{"abstract":[{"type":"text","text":"Delegate protocol for handling in-app purchase events from rich media."}],"url":"\/documentation\/pushwooshframework\/pwpurchasedelegate","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"PWPurchaseDelegate","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWPurchaseDelegate","title":"PWPurchaseDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PWPurchaseDelegate"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWPurchaseDelegate/onPW(inAppPurchaseHelperCallPromotedPurchase:)":{"navigatorTitle":[{"text":"onPWInAppPurchaseHelperCallPromotedPurchase:","kind":"identifier"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onPW"},{"text":"(","kind":"text"},{"text":"inAppPurchaseHelperCallPromotedPurchase","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?)","kind":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWPurchaseDelegate\/onPW(inAppPurchaseHelperCallPromotedPurchase:)","abstract":[{"type":"text","text":"Tells the delegate that a user initiates an IAP buy from the App Store."}],"kind":"symbol","url":"\/documentation\/pushwooshframework\/pwpurchasedelegate\/onpw(inapppurchasehelpercallpromotedpurchase:)","title":"onPW(inAppPurchaseHelperCallPromotedPurchase:)","required":true,"role":"symbol"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWPurchaseDelegate/onPW(inAppPurchaseHelperRestoreCompletedTransactionsFailed:)":{"navigatorTitle":[{"text":"onPWInAppPurchaseHelperRestoreCompletedTransactionsFailed:","kind":"identifier"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onPW"},{"text":"(","kind":"text"},{"text":"inAppPurchaseHelperRestoreCompletedTransactionsFailed","kind":"externalParam"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":")?)","kind":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWPurchaseDelegate\/onPW(inAppPurchaseHelperRestoreCompletedTransactionsFailed:)","abstract":[{"type":"text","text":"Tells the delegate that an error occurred while restoring transactions."}],"kind":"symbol","title":"onPW(inAppPurchaseHelperRestoreCompletedTransactionsFailed:)","url":"\/documentation\/pushwooshframework\/pwpurchasedelegate\/onpw(inapppurchasehelperrestorecompletedtransactionsfailed:)","required":true,"role":"symbol"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"abstract":[],"url":"\/documentation\/pushwooshframework","role":"collection","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","title":"PushwooshFramework","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"PWPurchaseDelegate"},{"op":"replace","value":"protocol","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"PWPurchaseDelegate","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"PWPurchaseDelegate","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWPurchaseDelegate\/onPW(inAppPurchaseHelperProducts:)"],"title":"Product Information"},{"title":"Purchase Events","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWPurchaseDelegate\/onPW(inAppPurchaseHelperPaymentComplete:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWPurchaseDelegate\/onPW(inAppPurchaseHelperPaymentFailedProductIdentifier:error:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWPurchaseDelegate\/onPW(inAppPurchaseHelperCallPromotedPurchase:)"]},{"title":"Restore Transactions","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWPurchaseDelegate\/onPW(inAppPurchaseHelperRestoreCompletedTransactionsFailed:)"]}]},{"path":"\/relationshipsSections","op":"replace","value":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PWPurchaseDelegate"},{"text":" <","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"},{"kind":"text","text":">"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWPurchaseDelegate~1onPW(inAppPurchaseHelperPaymentComplete:)\/title","value":"onPWInAppPurchaseHelperPaymentComplete:"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWPurchaseDelegate~1onPW(inAppPurchaseHelperPaymentComplete:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"onPWInAppPurchaseHelperPaymentComplete:","kind":"identifier"}]},{"value":"onPWInAppPurchaseHelperPaymentFailedProductIdentifier:error:","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWPurchaseDelegate~1onPW(inAppPurchaseHelperPaymentFailedProductIdentifier:error:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onPWInAppPurchaseHelperPaymentFailedProductIdentifier:error:"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWPurchaseDelegate~1onPW(inAppPurchaseHelperPaymentFailedProductIdentifier:error:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWPurchaseDelegate~1onPW(inAppPurchaseHelperProducts:)\/title","value":"onPWInAppPurchaseHelperProducts:"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWPurchaseDelegate~1onPW(inAppPurchaseHelperProducts:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"onPWInAppPurchaseHelperProducts:","kind":"identifier"}]},{"value":"PWPurchaseDelegate","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWPurchaseDelegate\/title"},{"value":[{"kind":"identifier","text":"PWPurchaseDelegate"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWPurchaseDelegate\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWPurchaseDelegate~1onPW(inAppPurchaseHelperCallPromotedPurchase:)\/title","value":"onPWInAppPurchaseHelperCallPromotedPurchase:"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWPurchaseDelegate~1onPW(inAppPurchaseHelperCallPromotedPurchase:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"onPWInAppPurchaseHelperCallPromotedPurchase:","kind":"identifier"}]},{"value":"onPWInAppPurchaseHelperRestoreCompletedTransactionsFailed:","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWPurchaseDelegate~1onPW(inAppPurchaseHelperRestoreCompletedTransactionsFailed:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"onPWInAppPurchaseHelperRestoreCompletedTransactionsFailed:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWPurchaseDelegate~1onPW(inAppPurchaseHelperRestoreCompletedTransactionsFailed:)\/fragments"}]}]}