{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWTags"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PWTags"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/pushwooshframework\/pwtags"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pwtags"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"codeVoice","code":"PWTags"},{"type":"text","text":" class encapsulates the methods for creating tags parameters for sending them to the server."}],"kind":"symbol","sections":[],"topicSections":[{"title":"Type Methods","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWTags\/appendValues(toListTag:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWTags\/incrementalTag(with:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWTags\/removeValues(fromListTag:)"]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"PWTags"}],"symbolKind":"class","title":"PWTags","roleHeading":"Class","modules":[{"name":"PushwooshFramework"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PWTags","kind":"identifier"}],"externalID":"c:objc(cs)PWTags","role":"symbol"},"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/objc(cs)NSObject"]},{"kind":"relationships","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)NSObject","doc:\/\/com.pushwoosh.PushwooshiOS\/s7CVarArgP","doc:\/\/com.pushwoosh.PushwooshiOS\/s28CustomDebugStringConvertibleP","doc:\/\/com.pushwoosh.PushwooshiOS\/s23CustomStringConvertibleP","doc:\/\/com.pushwoosh.PushwooshiOS\/SQ","doc:\/\/com.pushwoosh.PushwooshiOS\/SH"],"title":"Conforms To","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"]]},"references":{"doc://com.pushwoosh.PushwooshiOS/SH":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.pushwoosh.PushwooshiOS/s7CVarArgP":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"url":"\/documentation\/pushwooshframework","kind":"symbol","abstract":[{"text":"Push notification SDK for iOS applications.","type":"text"}],"type":"topic","role":"collection","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","title":"PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/SQ":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWTags/appendValues(toListTag:)":{"kind":"symbol","url":"\/documentation\/pushwooshframework\/pwtags\/appendvalues(tolisttag:)","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWTags\/appendValues(toListTag:)","type":"topic","abstract":[{"text":"Creates a dictionary for extending Tag’s values list with additional values","type":"text"}],"title":"appendValues(toListTag:)","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"appendValues"},{"text":"(","kind":"text"},{"text":"toListTag","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"]!) -> ["},{"preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier","text":"AnyHashable"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!"}],"navigatorTitle":[{"kind":"identifier","text":"appendValuesToListTag:"}],"role":"symbol"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWTags/incrementalTag(with:)":{"kind":"symbol","title":"incrementalTag(with:)","url":"\/documentation\/pushwooshframework\/pwtags\/incrementaltag(with:)","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWTags\/incrementalTag(with:)","navigatorTitle":[{"kind":"identifier","text":"incrementalTagWithInteger:"}],"type":"topic","role":"symbol","abstract":[{"text":"Creates a dictionary for incrementing\/decrementing a numeric tag on the server.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"incrementalTag","kind":"identifier"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> ["},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"text":"]!","kind":"text"}]},"doc://com.pushwoosh.PushwooshiOS/objc(pl)NSObject":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.pushwoosh.PushwooshiOS/objc(cs)NSObject":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWTags":{"kind":"symbol","title":"PWTags","url":"\/documentation\/pushwooshframework\/pwtags","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWTags","navigatorTitle":[{"kind":"identifier","text":"PWTags"}],"type":"topic","role":"symbol","abstract":[{"code":"PWTags","type":"codeVoice"},{"text":" class encapsulates the methods for creating tags parameters for sending them to the server.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PWTags"}]},"doc://com.pushwoosh.PushwooshiOS/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.pushwoosh.PushwooshiOS/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWTags/removeValues(fromListTag:)":{"url":"\/documentation\/pushwooshframework\/pwtags\/removevalues(fromlisttag:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"removeValues","kind":"identifier"},{"text":"(","kind":"text"},{"text":"fromListTag","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"]!) -> ["},{"kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"text":"]!","kind":"text"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWTags\/removeValues(fromListTag:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"removeValuesFromListTag:"}],"title":"removeValues(fromListTag:)","abstract":[{"type":"text","text":"Creates a dictionary for removing Tag’s values from existing values list"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"PWTags"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"value":[{"kind":"identifier","text":"PWTags"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"PWTags"}],"op":"replace"},{"value":[{"title":"Type Methods","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWTags\/appendValues(toListTag:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWTags\/incrementalTag(with:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWTags\/removeValues(fromListTag:)"]}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","value":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/objc(cs)NSObject"],"kind":"relationships"}],"op":"replace"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"PWTags","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"appendValuesToListTag:","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWTags~1appendValues(toListTag:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWTags~1appendValues(toListTag:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"appendValuesToListTag:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWTags~1incrementalTag(with:)\/title","op":"replace","value":"incrementalTagWithInteger:"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWTags~1incrementalTag(with:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"incrementalTagWithInteger:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWTags\/title","value":"PWTags","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWTags\/fragments","op":"replace","value":[{"kind":"identifier","text":"PWTags"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWTags~1removeValues(fromListTag:)\/title","value":"removeValuesFromListTag:"},{"value":[{"kind":"text","text":"+ "},{"text":"removeValuesFromListTag:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWTags~1removeValues(fromListTag:)\/fragments"}]}]}