{"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWTagsBuilder","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PWTagsBuilder","kind":"identifier"}],"platforms":["iOS"]}]}],"metadata":{"externalID":"c:objc(cs)PWTagsBuilder","role":"symbol","symbolKind":"class","modules":[{"name":"PushwooshFramework"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PWTagsBuilder"}],"navigatorTitle":[{"kind":"identifier","text":"PWTagsBuilder"}],"title":"PWTagsBuilder","roleHeading":"Class"},"abstract":[{"type":"codeVoice","code":"PWTagsBuilder"},{"text":" class encapsulates the methods for creating tags parameters for sending them to the server.","type":"text"}],"kind":"symbol","topicSections":[{"title":"Type Methods","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWTagsBuilder\/appendValues(toListTag:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWTagsBuilder\/incrementalTag(with:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWTagsBuilder\/removeValues(fromListTag:)"]}],"variants":[{"paths":["\/documentation\/pushwooshframework\/pwtagsbuilder"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pwtagsbuilder"]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"kind":"relationships","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)NSObject","doc:\/\/com.pushwoosh.PushwooshiOS\/s7CVarArgP","doc:\/\/com.pushwoosh.PushwooshiOS\/s28CustomDebugStringConvertibleP","doc:\/\/com.pushwoosh.PushwooshiOS\/s23CustomStringConvertibleP","doc:\/\/com.pushwoosh.PushwooshiOS\/SQ","doc:\/\/com.pushwoosh.PushwooshiOS\/SH"],"title":"Conforms To","type":"conformsTo"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"]]},"references":{"doc://com.pushwoosh.PushwooshiOS/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/s28CustomDebugStringConvertibleP"},"doc://com.pushwoosh.PushwooshiOS/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/SH"},"doc://com.pushwoosh.PushwooshiOS/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/objc(cs)NSObject"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWTagsBuilder/incrementalTag(with:)":{"role":"symbol","url":"\/documentation\/pushwooshframework\/pwtagsbuilder\/incrementaltag(with:)","navigatorTitle":[{"text":"incrementalTagWithInteger:","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWTagsBuilder\/incrementalTag(with:)","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"incrementalTag","kind":"identifier"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> ["},{"preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier","text":"AnyHashable"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]?"}],"title":"incrementalTag(with:)","abstract":[{"type":"text","text":"Creates a dictionary for incrementing\/decrementing a numeric tag on the server."}],"kind":"symbol"},"doc://com.pushwoosh.PushwooshiOS/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/s23CustomStringConvertibleP"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"kind":"symbol","abstract":[{"type":"text","text":"Push notification SDK for iOS applications."}],"type":"topic","role":"collection","url":"\/documentation\/pushwooshframework","title":"PushwooshFramework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/SQ"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWTagsBuilder/appendValues(toListTag:)":{"url":"\/documentation\/pushwooshframework\/pwtagsbuilder\/appendvalues(tolisttag:)","kind":"symbol","title":"appendValues(toListTag:)","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWTagsBuilder\/appendValues(toListTag:)","role":"symbol","abstract":[{"type":"text","text":"Creates a dictionary for extending Tag’s values list with additional values"}],"navigatorTitle":[{"text":"appendValuesToListTag:","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"appendValues"},{"kind":"text","text":"("},{"kind":"externalParam","text":"toListTag"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"]) -> ["},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]?"}]},"doc://com.pushwoosh.PushwooshiOS/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/s7CVarArgP"},"doc://com.pushwoosh.PushwooshiOS/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/objc(pl)NSObject"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWTagsBuilder/removeValues(fromListTag:)":{"url":"\/documentation\/pushwooshframework\/pwtagsbuilder\/removevalues(fromlisttag:)","abstract":[{"text":"Creates a dictionary for removing Tag’s values from existing values list","type":"text"}],"kind":"symbol","role":"symbol","title":"removeValues(fromListTag:)","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWTagsBuilder\/removeValues(fromListTag:)","navigatorTitle":[{"kind":"identifier","text":"removeValuesFromListTag:"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"removeValues","kind":"identifier"},{"text":"(","kind":"text"},{"text":"fromListTag","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"]) -> [","kind":"text"},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWTagsBuilder":{"role":"symbol","url":"\/documentation\/pushwooshframework\/pwtagsbuilder","navigatorTitle":[{"kind":"identifier","text":"PWTagsBuilder"}],"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWTagsBuilder","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PWTagsBuilder"}],"title":"PWTagsBuilder","abstract":[{"type":"codeVoice","code":"PWTagsBuilder"},{"type":"text","text":" class encapsulates the methods for creating tags parameters for sending them to the server."}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"PWTagsBuilder"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"PWTagsBuilder"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"PWTagsBuilder"}],"op":"replace"},{"value":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWTagsBuilder\/appendValues(toListTag:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWTagsBuilder\/incrementalTag(with:)","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWTagsBuilder\/removeValues(fromListTag:)"],"title":"Type Methods"}],"path":"\/topicSections","op":"replace"},{"value":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From"}],"path":"\/relationshipsSections","op":"replace"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PWTagsBuilder"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"languages":["occ"]}]},"op":"replace"},{"op":"replace","value":"incrementalTagWithInteger:","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWTagsBuilder~1incrementalTag(with:)\/title"},{"value":[{"kind":"text","text":"+ "},{"text":"incrementalTagWithInteger:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWTagsBuilder~1incrementalTag(with:)\/fragments"},{"op":"replace","value":"appendValuesToListTag:","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWTagsBuilder~1appendValues(toListTag:)\/title"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"appendValuesToListTag:"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWTagsBuilder~1appendValues(toListTag:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWTagsBuilder~1removeValues(fromListTag:)\/title","value":"removeValuesFromListTag:"},{"value":[{"text":"+ ","kind":"text"},{"text":"removeValuesFromListTag:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWTagsBuilder~1removeValues(fromListTag:)\/fragments"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWTagsBuilder\/title","op":"replace","value":"PWTagsBuilder"},{"value":[{"text":"PWTagsBuilder","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWTagsBuilder\/fragments","op":"replace"}]}]}