{"seeAlsoSections":[{"title":"Getting Started","generated":true,"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/GettingStarted","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/AdvancedIntegration"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"]]},"kind":"article","identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/QuickStart","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Get your first push notification running in minutes."}],"primaryContentSections":[{"kind":"content","content":[{"level":2,"anchor":"Overview","text":"Overview","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This quick start guide helps you set up Pushwoosh SDK and send your first push notification as quickly as possible. For comprehensive integration steps, see "},{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/GettingStarted","isActive":true,"type":"reference"},{"text":".","type":"text"}]},{"type":"heading","level":2,"anchor":"Prerequisites","text":"Prerequisites"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"text":"Active Pushwoosh account with a configured project","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"iOS platform set to Token-Based Authentication (recommended)"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Gateway set to "},{"code":"Sandbox","type":"codeVoice"},{"type":"text","text":" for simulator testing"}]}]},{"content":[{"inlineContent":[{"text":"Your Application Code and Device API Token from Pushwoosh Control Panel","type":"text"}],"type":"paragraph"}]}]},{"text":"Installation","level":2,"type":"heading","anchor":"Installation"},{"tabs":[{"title":"Swift Package Manager","content":[{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"In Xcode, select File → Add Package Dependencies","type":"text"}]}]},{"content":[{"inlineContent":[{"text":"Enter the repository URL:","type":"text"}],"type":"paragraph"}]}],"type":"orderedList"},{"syntax":null,"type":"codeListing","code":["https:\/\/github.com\/Pushwoosh\/Pushwoosh-XCFramework"]},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Select the following frameworks:","type":"text"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"PushwooshFramework","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"PushwooshCore"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"PushwooshBridge"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"PushwooshLiveActivities"}]}]}]}]}],"start":3,"type":"orderedList"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Add to your "},{"type":"codeVoice","code":"Podfile"},{"type":"text","text":":"}]},{"type":"codeListing","syntax":"ruby","code":["pod 'PushwooshXCFramework'"]},{"inlineContent":[{"type":"text","text":"Then run:"}],"type":"paragraph"},{"code":["pod install"],"type":"codeListing","syntax":"bash"}],"title":"CocoaPods"}],"type":"tabNavigator"},{"anchor":"Configuration","text":"Configuration","level":2,"type":"heading"},{"text":"1. Add Required Info.plist Keys","type":"heading","anchor":"1-Add-Required-Infoplist-Keys","level":3},{"inlineContent":[{"text":"Add these two keys to your ","type":"text"},{"code":"Info.plist","type":"codeVoice"},{"text":":","type":"text"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"codeVoice","code":"Pushwoosh_APPID"},{"type":"text","text":" → Your Application Code"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"Pushwoosh_API_TOKEN"},{"text":" → Your Device API Token","type":"text"}]}]}]},{"type":"codeListing","syntax":"xml","code":["<key>Pushwoosh_APPID<\/key>","<string>YOUR-APPLICATION-CODE<\/string>","<key>Pushwoosh_API_TOKEN<\/key>","<string>YOUR-DEVICE-API-TOKEN<\/string>"]},{"text":"2. Enable Push Notifications Capability","level":3,"type":"heading","anchor":"2-Enable-Push-Notifications-Capability"},{"type":"orderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Select your app target in Xcode"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Go to Signing & Capabilities"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Click + Capability","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Add “Push Notifications”"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Add “Background Modes” and check “Remote notifications”"}]}]}]},{"text":"3. Initialize SDK","anchor":"3-Initialize-SDK","type":"heading","level":3},{"inlineContent":[{"text":"In your AppDelegate or App struct:","type":"text"}],"type":"paragraph"},{"type":"tabNavigator","tabs":[{"title":"Swift","content":[{"code":["import PushwooshFramework","","class AppDelegate: NSObject, UIApplicationDelegate {","    func application(_ application: UIApplication,","                    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {","","        Pushwoosh.configure.registerForPushNotifications()","","        return true","    }","","    func application(_ application: UIApplication,","                    didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {","        Pushwoosh.configure.handlePushRegistration(deviceToken)","    }","}"],"type":"codeListing","syntax":"swift"}]},{"title":"Objective-C","content":[{"code":["#import <PushwooshFramework\/PushwooshFramework.h>","","@interface AppDelegate : NSObject <UIApplicationDelegate>","@end","","@implementation AppDelegate","","- (BOOL)application:(UIApplication *)application","        didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {","","    [Pushwoosh.configure registerForPushNotifications];","","    return YES;","}","","- (void)application:(UIApplication *)application","        didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken {","    [Pushwoosh.configure handlePushRegistration:deviceToken];","}","","@end"],"type":"codeListing","syntax":"objc"}]}]},{"anchor":"4-Register-for-Push-Notifications","text":"4. Register for Push Notifications","level":3,"type":"heading"},{"type":"paragraph","inlineContent":[{"text":"Run your app and grant push notification permissions when prompted. Check the console for a successful registration log containing your HWID and push token.","type":"text"}]},{"type":"heading","text":"Send Your First Push","anchor":"Send-Your-First-Push","level":2},{"items":[{"content":[{"inlineContent":[{"type":"text","text":"Open Pushwoosh Control Panel"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Navigate to your application","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Click “Create Message”"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Enter notification content"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Click “Send”"}],"type":"paragraph"}]}],"type":"orderedList"},{"inlineContent":[{"text":"Your device should receive the push notification!","type":"text"}],"type":"paragraph"},{"level":2,"text":"Troubleshooting","type":"heading","anchor":"Troubleshooting"},{"text":"Device Not Registered","level":3,"anchor":"Device-Not-Registered","type":"heading"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"text":"Verify push notification capability is enabled","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Check APNs certificate configuration in Pushwoosh","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Confirm app has notification permissions","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Look for registration logs in Xcode console"}],"type":"paragraph"}]}]},{"type":"heading","text":"Notifications Not Received","level":3,"anchor":"Notifications-Not-Received"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Confirm device is registered in Pushwoosh Control Panel under Audience → Devices"}]}]},{"content":[{"inlineContent":[{"text":"Verify Gateway is set to ","type":"text"},{"type":"codeVoice","code":"Sandbox"},{"text":" for simulator testing","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Check notification is sent to correct audience"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Enable debug logging:"}],"type":"paragraph"}]}],"type":"unorderedList"},{"type":"tabNavigator","tabs":[{"content":[{"syntax":"swift","code":["Pushwoosh.debug.setLogLevel(.PW_LL_VERBOSE)"],"type":"codeListing"}],"title":"Swift"},{"title":"Objective-C","content":[{"code":["[Pushwoosh.debug setLogLevel:PW_LL_VERBOSE];"],"syntax":"objc","type":"codeListing"}]}]},{"text":"Next Steps","type":"heading","level":2,"anchor":"Next-Steps"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/GettingStarted"},{"type":"text","text":" - Complete integration guide"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/AdvancedIntegration","isActive":true},{"text":" - Advanced features and configuration","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Add Notification Service Extension for rich media","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Implement PWMessagingDelegate for custom handling","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Configure user tags for segmentation"}]}]}],"type":"unorderedList"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/quickstart"]},{"paths":["\/documentation\/pushwooshframework\/quickstart"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"roleHeading":"Article","modules":[{"name":"PushwooshFramework"}],"title":"Quick Start","role":"article"},"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"url":"\/documentation\/pushwooshframework","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","kind":"symbol","abstract":[{"text":"Push notification SDK for iOS applications.","type":"text"}],"role":"collection","title":"PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/GettingStarted":{"kind":"article","url":"\/documentation\/pushwooshframework\/gettingstarted","title":"Getting Started","type":"topic","abstract":[{"text":"Set up push notifications in your iOS application with Pushwoosh SDK.","type":"text"}],"role":"article","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/GettingStarted"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/AdvancedIntegration":{"kind":"article","url":"\/documentation\/pushwooshframework\/advancedintegration","title":"Advanced Integration Guide","type":"topic","abstract":[{"text":"Advanced configuration options for Pushwoosh iOS SDK integration.","type":"text"}],"role":"article","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/AdvancedIntegration"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","value":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/GettingStarted","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/AdvancedIntegration"],"generated":true,"title":"Getting Started"}],"path":"\/seeAlsoSections"}]}]}