{"variants":[{"paths":["\/documentation\/pushwooshliveactivities"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshliveactivities"]}],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities","interfaceLanguage":"swift"},"sections":[],"abstract":[{"text":"Real-time iOS Live Activities powered by push notifications.","type":"text"}],"topicSections":[{"title":"Getting Started","identifiers":["doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/GettingStarted","doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/Examples"]},{"title":"Classes","identifiers":["doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/PushwooshLiveActivitiesImplementationSetup"]},{"title":"Protocols","identifiers":["doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/PushwooshLiveActivityAttributes","doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/PushwooshLiveActivityContentState"]},{"identifiers":["doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/AnyCodable","doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/DefaultLiveActivityAttributes","doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/PushwooshLiveActivityAttributeData","doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/PushwooshLiveActivityContentStateData"],"title":"Structures"},{"identifiers":["doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/PushwooshBridge"],"title":"Extended Modules"}],"primaryContentSections":[{"kind":"content","content":[{"level":2,"type":"heading","text":"Overview","anchor":"Overview"},{"inlineContent":[{"type":"text","text":"PushwooshLiveActivities integrates Apple’s ActivityKit framework to deliver real-time updates to Live Activities on the Lock Screen and Dynamic Island. Live Activities provide persistent, glanceable information that users can track without opening your app."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"The module handles token registration, activity lifecycle management, and push notification delivery automatically. It supports both custom activity attributes and a default configuration for cross-platform scenarios."}],"type":"paragraph"}]}],"metadata":{"modules":[{"name":"PushwooshLiveActivities"}],"roleHeading":"Framework","role":"collection","externalID":"PushwooshLiveActivities","title":"PushwooshLiveActivities","symbolKind":"module"},"hierarchy":{"paths":[[]]},"references":{"doc://com.pushwoosh.PushwooshLiveActivities/documentation/PushwooshLiveActivities/PushwooshLiveActivityAttributeData":{"role":"symbol","abstract":[{"type":"text","text":"Pushwoosh-specific metadata required for Live Activity tracking."}],"identifier":"doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/PushwooshLiveActivityAttributeData","type":"topic","url":"\/documentation\/pushwooshliveactivities\/pushwooshliveactivityattributedata","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PushwooshLiveActivityAttributeData","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PushwooshLiveActivityAttributeData"}],"kind":"symbol","title":"PushwooshLiveActivityAttributeData"},"doc://com.pushwoosh.PushwooshLiveActivities/documentation/PushwooshLiveActivities/PushwooshLiveActivityContentState":{"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PushwooshLiveActivityContentState"}],"abstract":[{"type":"text","text":"Protocol for defining Live Activity content state."}],"type":"topic","title":"PushwooshLiveActivityContentState","role":"symbol","url":"\/documentation\/pushwooshliveactivities\/pushwooshliveactivitycontentstate","navigatorTitle":[{"text":"PushwooshLiveActivityContentState","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/PushwooshLiveActivityContentState"},"doc://com.pushwoosh.PushwooshLiveActivities/documentation/PushwooshLiveActivities":{"type":"topic","role":"collection","url":"\/documentation\/pushwooshliveactivities","title":"PushwooshLiveActivities","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities","abstract":[{"text":"Real-time iOS Live Activities powered by push notifications.","type":"text"}]},"doc://com.pushwoosh.PushwooshLiveActivities/documentation/PushwooshLiveActivities/PushwooshBridge":{"url":"\/documentation\/pushwooshliveactivities\/pushwooshbridge","role":"collection","type":"topic","abstract":[],"title":"PushwooshBridge","identifier":"doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/PushwooshBridge","kind":"symbol"},"doc://com.pushwoosh.PushwooshLiveActivities/documentation/PushwooshLiveActivities/PushwooshLiveActivityContentStateData":{"identifier":"doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/PushwooshLiveActivityContentStateData","kind":"symbol","title":"PushwooshLiveActivityContentStateData","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"PushwooshLiveActivityContentStateData","kind":"identifier"}],"url":"\/documentation\/pushwooshliveactivities\/pushwooshliveactivitycontentstatedata","navigatorTitle":[{"text":"PushwooshLiveActivityContentStateData","kind":"identifier"}],"type":"topic","abstract":[{"text":"Pushwoosh-specific metadata for Live Activity content state updates.","type":"text"}]},"doc://com.pushwoosh.PushwooshLiveActivities/documentation/PushwooshLiveActivities/DefaultLiveActivityAttributes":{"identifier":"doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/DefaultLiveActivityAttributes","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DefaultLiveActivityAttributes"}],"navigatorTitle":[{"text":"DefaultLiveActivityAttributes","kind":"identifier"}],"title":"DefaultLiveActivityAttributes","url":"\/documentation\/pushwooshliveactivities\/defaultliveactivityattributes","role":"symbol","abstract":[{"type":"text","text":"A flexible structure for defining Live Activity content dynamically."}],"kind":"symbol"},"doc://com.pushwoosh.PushwooshLiveActivities/documentation/PushwooshLiveActivities/PushwooshLiveActivitiesVersionString":{"url":"\/documentation\/pushwooshliveactivities\/pushwooshliveactivitiesversionstring","role":"symbol","fragments":[{"text":"PushwooshLiveActivitiesVersionString","kind":"identifier"}],"type":"topic","abstract":[{"text":"Project version string for PushwooshLiveActivities.","type":"text"}],"title":"PushwooshLiveActivitiesVersionString","identifier":"doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/PushwooshLiveActivitiesVersionString","kind":"symbol"},"doc://com.pushwoosh.PushwooshLiveActivities/documentation/PushwooshLiveActivities/AnyCodable":{"navigatorTitle":[{"text":"AnyCodable","kind":"identifier"}],"title":"AnyCodable","identifier":"doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/AnyCodable","type":"topic","abstract":[],"kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AnyCodable"}],"url":"\/documentation\/pushwooshliveactivities\/anycodable","role":"symbol"},"doc://com.pushwoosh.PushwooshLiveActivities/documentation/PushwooshLiveActivities/Examples":{"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/Examples","kind":"article","abstract":[{"text":"Practical examples for common Live Activities integration scenarios.","type":"text"}],"role":"article","title":"Code Examples","url":"\/documentation\/pushwooshliveactivities\/examples"},"doc://com.pushwoosh.PushwooshLiveActivities/documentation/PushwooshLiveActivities/PushwooshLiveActivitiesVersionNumber":{"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Project version number for PushwooshLiveActivities."}],"title":"PushwooshLiveActivitiesVersionNumber","identifier":"doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/PushwooshLiveActivitiesVersionNumber","type":"topic","fragments":[{"text":"PushwooshLiveActivitiesVersionNumber","kind":"identifier"}],"url":"\/documentation\/pushwooshliveactivities\/pushwooshliveactivitiesversionnumber"},"doc://com.pushwoosh.PushwooshLiveActivities/documentation/PushwooshLiveActivities/PushwooshLiveActivitiesImplementationSetup":{"abstract":[{"text":"Orchestrates iOS Live Activities integration with Pushwoosh push notifications.","type":"text"}],"role":"symbol","url":"\/documentation\/pushwooshliveactivities\/pushwooshliveactivitiesimplementationsetup","navigatorTitle":[{"kind":"identifier","text":"PushwooshLiveActivitiesImplementationSetup"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PushwooshLiveActivitiesImplementationSetup","kind":"identifier"}],"title":"PushwooshLiveActivitiesImplementationSetup","identifier":"doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/PushwooshLiveActivitiesImplementationSetup","kind":"symbol","type":"topic"},"doc://com.pushwoosh.PushwooshLiveActivities/documentation/PushwooshLiveActivities/PushwooshLiveActivityAttributes":{"navigatorTitle":[{"kind":"identifier","text":"PushwooshLiveActivityAttributes"}],"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/PushwooshLiveActivityAttributes","kind":"symbol","abstract":[{"type":"text","text":"Protocol for defining custom Live Activity attributes."}],"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"PushwooshLiveActivityAttributes","kind":"identifier"}],"title":"PushwooshLiveActivityAttributes","url":"\/documentation\/pushwooshliveactivities\/pushwooshliveactivityattributes"},"doc://com.pushwoosh.PushwooshLiveActivities/documentation/PushwooshLiveActivities/GettingStarted":{"kind":"article","role":"article","type":"topic","abstract":[{"text":"Set up iOS Live Activities with push notification updates.","type":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/GettingStarted","title":"Getting Started","url":"\/documentation\/pushwooshliveactivities\/gettingstarted"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"title":"Getting Started","identifiers":["doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/GettingStarted","doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/Examples"]},{"title":"Classes","identifiers":["doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/PushwooshLiveActivitiesImplementationSetup"]},{"title":"Variables","identifiers":["doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/PushwooshLiveActivitiesVersionNumber","doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/PushwooshLiveActivitiesVersionString"]}]},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshLiveActivities~1documentation~1PushwooshLiveActivities~1PushwooshLiveActivitiesImplementationSetup\/title","value":"PushwooshLiveActivitiesImplementationSetup","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshLiveActivities~1documentation~1PushwooshLiveActivities~1PushwooshLiveActivitiesImplementationSetup\/fragments","value":[{"kind":"identifier","text":"PushwooshLiveActivitiesImplementationSetup"}]}]}]}