{"variants":[{"paths":["\/documentation\/pushwooshframework\/pwnotificationextensionmanager\/handle(_:contenthandler:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pwnotificationextensionmanager\/handle(_:contenthandler:)"]}],"metadata":{"modules":[{"name":"PushwooshFramework"}],"title":"handle(_:contentHandler:)","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"handleNotificationRequest:contentHandler:"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"handle"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UNNotificationRequest","kind":"typeIdentifier","text":"UNNotificationRequest"},{"text":", ","kind":"text"},{"text":"contentHandler","kind":"externalParam"},{"kind":"text","text":": ("},{"preciseIdentifier":"c:objc(cs)UNNotificationContent","text":"UNNotificationContent","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")"}],"role":"symbol","roleHeading":"Instance Method","externalID":"c:objc(cs)PWNotificationExtensionManager(im)handleNotificationRequest:contentHandler:"},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWNotificationExtensionManager"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"handle"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"request","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UNNotificationRequest","text":"UNNotificationRequest","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"contentHandler"},{"kind":"text","text":": "},{"kind":"keyword","text":"@escaping"},{"kind":"text","text":" ("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UNNotificationContent","text":"UNNotificationContent"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"level":2,"text":"Discussion","anchor":"discussion","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Example:"}]},{"items":[{"content":[{"inlineContent":[{"text":"(void)didReceiveNotificationRequest:(UNNotificationRequest *)request withContentHandler:(void (^)(UNNotificationContent * _Nonnull))contentHandler {","type":"text"},{"type":"text","text":" "},{"type":"text","text":"self.contentHandler = contentHandler;"},{"text":" ","type":"text"},{"text":"self.bestAttemptContent = [request.content mutableCopy];","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"[[PWNotificationExtensionManager sharedManager] handleNotificationRequest:request contentHandler:contentHandler];"},{"type":"text","text":" "},{"text":"}","type":"text"}],"type":"paragraph"}]}],"type":"unorderedList"}],"kind":"content"}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Sends message delivery event to Pushwoosh and downloads media attachment. Call it from UNNotificationServiceExtension. Don’t forget to set Pushwoosh_APPID in extension Info.plist."}],"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWNotificationExtensionManager\/handle(_:contentHandler:)","interfaceLanguage":"swift"},"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWNotificationExtensionManager":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PWNotificationExtensionManager","kind":"identifier"}],"url":"\/documentation\/pushwooshframework\/pwnotificationextensionmanager","title":"PWNotificationExtensionManager","abstract":[],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWNotificationExtensionManager","type":"topic","navigatorTitle":[{"text":"PWNotificationExtensionManager","kind":"identifier"}],"role":"symbol","kind":"symbol"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"title":"PushwooshFramework","abstract":[{"text":"Push notification SDK for iOS applications.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","url":"\/documentation\/pushwooshframework","type":"topic","role":"collection"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWNotificationExtensionManager/handle(_:contentHandler:)":{"abstract":[{"type":"text","text":"Sends message delivery event to Pushwoosh and downloads media attachment. Call it from UNNotificationServiceExtension. Don’t forget to set Pushwoosh_APPID in extension Info.plist."}],"role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWNotificationExtensionManager\/handle(_:contentHandler:)","title":"handle(_:contentHandler:)","navigatorTitle":[{"text":"handleNotificationRequest:contentHandler:","kind":"identifier"}],"url":"\/documentation\/pushwooshframework\/pwnotificationextensionmanager\/handle(_:contenthandler:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"handle"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UNNotificationRequest","text":"UNNotificationRequest","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"contentHandler","kind":"externalParam"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"UNNotificationContent","preciseIdentifier":"c:objc(cs)UNNotificationContent"},{"kind":"text","text":") -> "},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"handleNotificationRequest:contentHandler:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"handleNotificationRequest:contentHandler:"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"handleNotificationRequest:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UNNotificationRequest","text":"UNNotificationRequest","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"request","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"contentHandler:"},{"kind":"text","text":"("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":" (^"},{"text":")(","kind":"text"},{"text":"UNNotificationContent","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UNNotificationContent"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"kind":"internalParam","text":"contentHandler"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWNotificationExtensionManager\/title","value":"PWNotificationExtensionManager"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWNotificationExtensionManager\/fragments","value":[{"text":"PWNotificationExtensionManager","kind":"identifier"}],"op":"replace"},{"value":"handleNotificationRequest:contentHandler:","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWNotificationExtensionManager~1handle(_:contentHandler:)\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWNotificationExtensionManager~1handle(_:contentHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"handleNotificationRequest:contentHandler:","kind":"identifier"}],"op":"replace"}]}]}