{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxBannerCell\/prepareForReuse()"},"metadata":{"externalID":"c:@M@PushwooshInboxKit@objc(cs)PushwooshInboxBannerCell(im)prepareForReuse","modules":[{"name":"PushwooshInboxKit"}],"role":"symbol","title":"prepareForReuse()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"prepareForReuse","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"prepareForReuse","kind":"identifier"}],"symbolKind":"method","roleHeading":"Instance Method"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxBannerCell"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"override","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"prepareForReuse","kind":"identifier"},{"text":"()","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/pushwooshinboxkit\/pushwooshinboxbannercell\/prepareforreuse()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshinboxkit\/pushwooshinboxbannercell\/prepareforreuse()"]}],"references":{"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxBannerCell":{"role":"symbol","abstract":[],"navigatorTitle":[{"text":"PushwooshInboxBannerCell","kind":"identifier"}],"title":"PushwooshInboxBannerCell","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PushwooshInboxBannerCell","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxbannercell","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxBannerCell","type":"topic"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxBannerCell/prepareForReuse()":{"navigatorTitle":[{"kind":"identifier","text":"prepareForReuse"}],"role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxBannerCell\/prepareForReuse()","title":"prepareForReuse()","kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"prepareForReuse","kind":"identifier"},{"text":"()","kind":"text"}],"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxbannercell\/prepareforreuse()","type":"topic"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit","title":"PushwooshInboxKit","type":"topic","url":"\/documentation\/pushwooshinboxkit","abstract":[{"text":"Modern UIKit inbox UI powered by Pushwoosh.","type":"text"}],"kind":"symbol","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"prepareForReuse","op":"replace","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"prepareForReuse","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"prepareForReuse","kind":"identifier"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxBannerCell\/title","op":"replace","value":"PushwooshInboxBannerCell"},{"op":"replace","value":[{"text":"PushwooshInboxBannerCell","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxBannerCell\/fragments"},{"value":"prepareForReuse","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxBannerCell~1prepareForReuse()\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxBannerCell~1prepareForReuse()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"prepareForReuse","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}