{"topicSections":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/GettingStarted","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/Examples","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/HTMLGuide"],"title":"Getting Started"},{"identifiers":["doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/setAppCode(_:)","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/registerForTvPushNotifications()","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/unregisterForTvPushNotifications(completion:)"],"title":"Configuration"},{"title":"Push Notification Handling","identifiers":["doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/handleTvPushToken(_:)","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/handleTvPushRegistrationFailure(_:)","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/handleTvPushReceived(userInfo:completionHandler:)","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/handleTVOSPush(userInfo:)"]},{"identifiers":["doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/configureRichMediaWith(position:presentAnimation:dismissAnimation:)","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/configureCloseButton(_:)"],"title":"Rich Media Configuration"},{"title":"Rich Media Manager","identifiers":["doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PWTVOSRichMediaManager"]},{"identifiers":["doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation"],"title":"Classes"},{"title":"Extended Modules","identifiers":["doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshBridge"]}],"primaryContentSections":[{"kind":"content","content":[{"level":2,"text":"Overview","type":"heading","anchor":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"PushwooshTVOS is an optional module that extends the Pushwoosh SDK with tvOS-specific functionality. It provides seamless integration of push notifications and interactive Rich Media content optimized for Apple TV."}]},{"type":"heading","text":"Key Features","level":3,"anchor":"Key-Features"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Push Notifications"}]},{"type":"text","text":": Full support for tvOS push notifications with automatic device registration"}]}]},{"content":[{"inlineContent":[{"inlineContent":[{"text":"Rich Media","type":"text"}],"type":"strong"},{"type":"text","text":": Display interactive HTML content with Focus Engine support for Apple TV remote navigation"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"text":"Customizable Animations","type":"text"}]},{"type":"text","text":": Configure presentation and dismissal animations for Rich Media"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"inlineContent":[{"text":"Flexible Positioning","type":"text"}],"type":"strong"},{"text":": Position Rich Media content anywhere on screen (center, left, right, top, bottom)","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Button Actions"}]},{"type":"text","text":": Support for event tracking, tag management, and custom actions"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"inlineContent":[{"text":"Focus Management","type":"text"}],"type":"strong"},{"type":"text","text":": Automatic focus handling for tvOS remote navigation"}],"type":"paragraph"}]}]},{"text":"tvOS Requirements","level":3,"type":"heading","anchor":"tvOS-Requirements"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"tvOS 11.0 or later","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Pushwoosh App Code configured for tvOS"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Push Notification capability enabled in Xcode","type":"text"}]}]}],"type":"unorderedList"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","hierarchy":{"paths":[[]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshtvos"]},{"paths":["\/documentation\/pushwooshtvos"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"module","modules":[{"name":"PushwooshTVOS"}],"title":"PushwooshTVOS","externalID":"PushwooshTVOS","role":"collection","roleHeading":"Framework"},"sections":[],"abstract":[{"type":"text","text":"Push notifications and Rich Media for tvOS apps."}],"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS","interfaceLanguage":"swift"},"references":{"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PushwooshTVOSImplementation/handleTvPushReceived(userInfo:completionHandler:)":{"abstract":[{"type":"text","text":"Handles incoming push notification on tvOS."}],"identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/handleTvPushReceived(userInfo:completionHandler:)","navigatorTitle":[{"kind":"identifier","text":"handleTvPushReceivedWithUserInfo:completionHandler:"}],"url":"\/documentation\/pushwooshtvos\/pushwooshtvosimplementation\/handletvpushreceived(userinfo:completionhandler:)","title":"handleTvPushReceived(userInfo:completionHandler:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"handleTvPushReceived","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"userInfo"},{"text":": [","kind":"text"},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"], ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"kind":"text","text":": ("},{"text":"UIBackgroundFetchResult","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIBackgroundFetchResult"},{"kind":"text","text":") -> "},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PushwooshTVOSImplementation/configureRichMediaWith(position:presentAnimation:dismissAnimation:)":{"abstract":[{"type":"text","text":"Configures rich media presentation, positioning, and dismissal animations for tvOS."}],"kind":"symbol","url":"\/documentation\/pushwooshtvos\/pushwooshtvosimplementation\/configurerichmediawith(position:presentanimation:dismissanimation:)","identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/configureRichMediaWith(position:presentAnimation:dismissAnimation:)","title":"configureRichMediaWith(position:presentAnimation:dismissAnimation:)","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"configureRichMediaWith","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"position"},{"kind":"text","text":": "},{"text":"PWTVOSRichMediaPosition","preciseIdentifier":"c:@M@PushwooshBridge@E@PWTVOSRichMediaPosition","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"presentAnimation","kind":"externalParam"},{"kind":"text","text":": "},{"text":"PWTVOSRichMediaPresentAnimation","kind":"typeIdentifier","preciseIdentifier":"c:@M@PushwooshBridge@E@PWTVOSRichMediaPresentAnimation"},{"kind":"text","text":", "},{"text":"dismissAnimation","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"PWTVOSRichMediaDismissAnimation","preciseIdentifier":"c:@M@PushwooshBridge@E@PWTVOSRichMediaDismissAnimation"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"configureRichMediaWithPosition:presentAnimation:dismissAnimation:","kind":"identifier"}]},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PushwooshTVOSVersionNumber":{"fragments":[{"text":"PushwooshTVOSVersionNumber","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"PushwooshTVOSVersionNumber","type":"topic","abstract":[{"text":"Project version number for PushwooshTVOS.","type":"text"}],"url":"\/documentation\/pushwooshtvos\/pushwooshtvosversionnumber","identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSVersionNumber"},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PushwooshTVOSImplementation/configureCloseButton(_:)":{"identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/configureCloseButton(_:)","abstract":[{"type":"text","text":"Controls whether the Close button is displayed on rich media content."}],"url":"\/documentation\/pushwooshtvos\/pushwooshtvosimplementation\/configureclosebutton(_:)","kind":"symbol","title":"configureCloseButton(_:)","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"configureCloseButton","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"configureCloseButton:"}]},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PushwooshTVOSImplementation/unregisterForTvPushNotifications(completion:)":{"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"unregisterForTvPushNotifications"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": ((","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"kind":"text","text":")?)"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"unregisterForTvPushNotificationsWithCompletion:","kind":"identifier"}],"title":"unregisterForTvPushNotifications(completion:)","type":"topic","url":"\/documentation\/pushwooshtvos\/pushwooshtvosimplementation\/unregisterfortvpushnotifications(completion:)","abstract":[{"text":"Unregisters the tvOS device from receiving push notifications.","type":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/unregisterForTvPushNotifications(completion:)"},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PWTVOSRichMediaManager":{"kind":"symbol","title":"PWTVOSRichMediaManager","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PWTVOSRichMediaManager","abstract":[{"text":"Manager for displaying Rich Media content on tvOS.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PWTVOSRichMediaManager","kind":"identifier"}],"navigatorTitle":[{"text":"PWTVOSRichMediaManager","kind":"identifier"}],"url":"\/documentation\/pushwooshtvos\/pwtvosrichmediamanager","role":"symbol"},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PushwooshTVOSImplementation":{"abstract":[{"text":"Main implementation class for tvOS push notifications and Rich Media.","type":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation","navigatorTitle":[{"kind":"identifier","text":"PushwooshTVOSImplementation"}],"url":"\/documentation\/pushwooshtvos\/pushwooshtvosimplementation","title":"PushwooshTVOSImplementation","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PushwooshTVOSImplementation","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PushwooshTVOSImplementation/handleTVOSPush(userInfo:)":{"abstract":[{"text":"Handles incoming push notifications with rich media content for tvOS.","type":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/handleTVOSPush(userInfo:)","navigatorTitle":[{"text":"handleTVOSPushWithUserInfo:","kind":"identifier"}],"url":"\/documentation\/pushwooshtvos\/pushwooshtvosimplementation\/handletvospush(userinfo:)","title":"handleTVOSPush(userInfo:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"handleTVOSPush","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"userInfo"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PushwooshTVOSImplementation/handleTvPushToken(_:)":{"abstract":[{"text":"Handles the device token received from tvOS push registration.","type":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/handleTvPushToken(_:)","navigatorTitle":[{"text":"handleTvPushToken:","kind":"identifier"}],"url":"\/documentation\/pushwooshtvos\/pushwooshtvosimplementation\/handletvpushtoken(_:)","title":"handleTvPushToken(_:)","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"handleTvPushToken","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":")","kind":"text"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PushwooshTVOSVersionString":{"fragments":[{"text":"PushwooshTVOSVersionString","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"PushwooshTVOSVersionString","type":"topic","abstract":[{"text":"Project version string for PushwooshTVOS.","type":"text"}],"url":"\/documentation\/pushwooshtvos\/pushwooshtvosversionstring","identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSVersionString"},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/Examples":{"kind":"article","role":"article","title":"Examples","type":"topic","url":"\/documentation\/pushwooshtvos\/examples","abstract":[{"text":"Code samples demonstrating common tvOS integration scenarios.","type":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/Examples"},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/GettingStarted":{"kind":"article","type":"topic","url":"\/documentation\/pushwooshtvos\/gettingstarted","title":"Getting Started","role":"article","identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/GettingStarted","abstract":[{"text":"Integrate Modal Rich Media for your tvOS app.","type":"text"}]},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS":{"identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS","url":"\/documentation\/pushwooshtvos","role":"collection","kind":"symbol","abstract":[{"text":"Push notifications and Rich Media for tvOS apps.","type":"text"}],"title":"PushwooshTVOS","type":"topic"},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/HTMLGuide":{"kind":"article","type":"topic","url":"\/documentation\/pushwooshtvos\/htmlguide","title":"HTML Guide for tvOS Rich Media","role":"article","identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/HTMLGuide","abstract":[{"text":"Create Rich Media content using Unlayer HTML format for tvOS.","type":"text"}]},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PushwooshBridge":{"kind":"symbol","title":"PushwooshBridge","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshBridge","abstract":[],"role":"collection","url":"\/documentation\/pushwooshtvos\/pushwooshbridge"},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PushwooshTVOSImplementation/registerForTvPushNotifications()":{"kind":"symbol","type":"topic","url":"\/documentation\/pushwooshtvos\/pushwooshtvosimplementation\/registerfortvpushnotifications()","title":"registerForTvPushNotifications()","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"registerForTvPushNotifications","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"registerForTvPushNotifications"}],"role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/registerForTvPushNotifications()","abstract":[{"text":"Registers for tvOS push notifications.","type":"text"}]},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PushwooshTVOSImplementation/handleTvPushRegistrationFailure(_:)":{"abstract":[{"text":"Handles push registration failure on tvOS.","type":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/handleTvPushRegistrationFailure(_:)","navigatorTitle":[{"text":"handleTvPushRegistrationFailure:","kind":"identifier"}],"url":"\/documentation\/pushwooshtvos\/pushwooshtvosimplementation\/handletvpushregistrationfailure(_:)","title":"handleTvPushRegistrationFailure(_:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"handleTvPushRegistrationFailure","kind":"identifier"},{"kind":"text","text":"("},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PushwooshTVOSImplementation/setAppCode(_:)":{"role":"symbol","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/setAppCode(_:)","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setAppCode"},{"text":"(","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"setAppCode:","kind":"identifier"}],"url":"\/documentation\/pushwooshtvos\/pushwooshtvosimplementation\/setappcode(_:)","title":"setAppCode(_:)","abstract":[{"text":"Sets the Pushwoosh application code for tvOS.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":[{"title":"Getting Started","identifiers":["doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/GettingStarted","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/Examples","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/HTMLGuide"]},{"title":"Configuration","identifiers":["doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/setAppCode(_:)","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/registerForTvPushNotifications()","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/unregisterForTvPushNotifications(completion:)"]},{"identifiers":["doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/handleTvPushToken(_:)","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/handleTvPushRegistrationFailure(_:)","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/handleTvPushReceived(userInfo:completionHandler:)","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/handleTVOSPush(userInfo:)"],"title":"Push Notification Handling"},{"title":"Rich Media Configuration","identifiers":["doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/configureRichMediaWith(position:presentAnimation:dismissAnimation:)","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/configureCloseButton(_:)"]},{"title":"Rich Media Manager","identifiers":["doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PWTVOSRichMediaManager"]},{"title":"Classes","identifiers":["doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation"]},{"title":"Variables","identifiers":["doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSVersionNumber","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSVersionString"]}],"op":"replace","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1handleTvPushReceived(userInfo:completionHandler:)\/title","op":"replace","value":"handleTvPushReceivedWithUserInfo:completionHandler:"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"handleTvPushReceivedWithUserInfo:completionHandler:"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1handleTvPushReceived(userInfo:completionHandler:)\/fragments"},{"value":"configureRichMediaWithPosition:presentAnimation:dismissAnimation:","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1configureRichMediaWith(position:presentAnimation:dismissAnimation:)\/title"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"configureRichMediaWithPosition:presentAnimation:dismissAnimation:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1configureRichMediaWith(position:presentAnimation:dismissAnimation:)\/fragments"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1configureCloseButton(_:)\/title","value":"configureCloseButton:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1configureCloseButton(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"configureCloseButton:"}]},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1unregisterForTvPushNotifications(completion:)\/title","op":"replace","value":"unregisterForTvPushNotificationsWithCompletion:"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1unregisterForTvPushNotifications(completion:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"unregisterForTvPushNotificationsWithCompletion:"}]},{"value":"PWTVOSRichMediaManager","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PWTVOSRichMediaManager\/title"},{"op":"replace","value":[{"kind":"identifier","text":"PWTVOSRichMediaManager"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PWTVOSRichMediaManager\/fragments"},{"value":"PushwooshTVOSImplementation","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation\/fragments","value":[{"text":"PushwooshTVOSImplementation","kind":"identifier"}],"op":"replace"},{"value":"handleTVOSPushWithUserInfo:","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1handleTVOSPush(userInfo:)\/title"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"handleTVOSPushWithUserInfo:"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1handleTVOSPush(userInfo:)\/fragments"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1handleTvPushToken(_:)\/title","value":"handleTvPushToken:","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"text":"handleTvPushToken:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1handleTvPushToken(_:)\/fragments"},{"value":"registerForTvPushNotifications","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1registerForTvPushNotifications()\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1registerForTvPushNotifications()\/fragments","value":[{"kind":"text","text":"+ "},{"text":"registerForTvPushNotifications","kind":"identifier"}],"op":"replace"},{"value":"handleTvPushRegistrationFailure:","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1handleTvPushRegistrationFailure(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1handleTvPushRegistrationFailure(_:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"handleTvPushRegistrationFailure:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1setAppCode(_:)\/title","value":"setAppCode:"},{"value":[{"text":"+ ","kind":"text"},{"text":"setAppCode:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1setAppCode(_:)\/fragments"}]}]}