{"metadata":{"platforms":[{"unavailable":false,"name":"iOS","introducedAt":"12.0","beta":false,"deprecated":false}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"backchannelProvider","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@PushwooshBridge@objc(pl)PWKeychainPersistentHWIDProvider","text":"PWKeychainPersistentHWIDProvider"}],"symbolKind":"property","externalID":"c:@M@PushwooshKeychain@objc(cs)PushwooshKeychainImplementation(cpy)backchannelProvider","roleHeading":"Type Property","role":"symbol","title":"backchannelProvider","modules":[{"name":"PushwooshKeychain"}],"navigatorTitle":[{"kind":"identifier","text":"backchannelProvider"}]},"kind":"symbol","sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshKeychain\/documentation\/PushwooshKeychain\/PushwooshKeychainImplementation\/backchannelProvider"},"abstract":[{"type":"text","text":"Singleton back-channel adapter used by "},{"code":"PWPreferences","type":"codeVoice"},{"type":"text","text":" to retrieve the"},{"type":"text","text":" "},{"type":"text","text":"persistent HWID without reflection. Registered with"},{"text":" ","type":"text"},{"type":"codeVoice","code":"PushwooshModuleRegistry"},{"text":" by ","type":"text"},{"type":"codeVoice","code":"PushwooshKeychainLoader"},{"text":".","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshKeychain\/documentation\/PushwooshKeychain","doc:\/\/com.pushwoosh.PushwooshKeychain\/documentation\/PushwooshKeychain\/PushwooshKeychainImplementation"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"backchannelProvider"},{"kind":"text","text":": "},{"text":"PWKeychainPersistentHWIDProvider","kind":"typeIdentifier","preciseIdentifier":"c:@M@PushwooshBridge@objc(pl)PWKeychainPersistentHWIDProvider"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/pushwooshkeychain\/pushwooshkeychainimplementation\/backchannelprovider"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshkeychain\/pushwooshkeychainimplementation\/backchannelprovider"]}],"references":{"doc://com.pushwoosh.PushwooshKeychain/documentation/PushwooshKeychain":{"identifier":"doc:\/\/com.pushwoosh.PushwooshKeychain\/documentation\/PushwooshKeychain","kind":"symbol","url":"\/documentation\/pushwooshkeychain","title":"PushwooshKeychain","role":"collection","type":"topic","abstract":[]},"doc://com.pushwoosh.PushwooshKeychain/documentation/PushwooshKeychain/PushwooshKeychainImplementation/backchannelProvider":{"url":"\/documentation\/pushwooshkeychain\/pushwooshkeychainimplementation\/backchannelprovider","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"backchannelProvider","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@PushwooshBridge@objc(pl)PWKeychainPersistentHWIDProvider","text":"PWKeychainPersistentHWIDProvider"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshKeychain\/documentation\/PushwooshKeychain\/PushwooshKeychainImplementation\/backchannelProvider","navigatorTitle":[{"kind":"identifier","text":"backchannelProvider"}],"title":"backchannelProvider","role":"symbol","abstract":[{"type":"text","text":"Singleton back-channel adapter used by "},{"type":"codeVoice","code":"PWPreferences"},{"type":"text","text":" to retrieve the"},{"type":"text","text":" "},{"type":"text","text":"persistent HWID without reflection. Registered with"},{"type":"text","text":" "},{"type":"codeVoice","code":"PushwooshModuleRegistry"},{"type":"text","text":" by "},{"code":"PushwooshKeychainLoader","type":"codeVoice"},{"type":"text","text":"."}],"type":"topic","kind":"symbol"},"doc://com.pushwoosh.PushwooshKeychain/documentation/PushwooshKeychain/PushwooshKeychainImplementation":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PushwooshKeychainImplementation","kind":"identifier"}],"abstract":[{"type":"text","text":"Implementation of persistent HWID storage using iOS Keychain."}],"kind":"symbol","navigatorTitle":[{"text":"PushwooshKeychainImplementation","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshKeychain\/documentation\/PushwooshKeychain\/PushwooshKeychainImplementation","url":"\/documentation\/pushwooshkeychain\/pushwooshkeychainimplementation","title":"PushwooshKeychainImplementation","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Type Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"backchannelProvider","op":"replace","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"backchannelProvider"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@PushwooshBridge@objc(pl)PWKeychainPersistentHWIDProvider","text":"id<PWKeychainPersistentHWIDProvider>"},{"text":" ","kind":"text"},{"text":"backchannelProvider","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshKeychain~1documentation~1PushwooshKeychain~1PushwooshKeychainImplementation~1backchannelProvider\/title","value":"backchannelProvider","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshKeychain~1documentation~1PushwooshKeychain~1PushwooshKeychainImplementation~1backchannelProvider\/fragments","value":[{"text":"backchannelProvider","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshKeychain~1documentation~1PushwooshKeychain~1PushwooshKeychainImplementation\/title","op":"replace","value":"PushwooshKeychainImplementation"},{"value":[{"text":"PushwooshKeychainImplementation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshKeychain~1documentation~1PushwooshKeychain~1PushwooshKeychainImplementation\/fragments"}]}]}