{"abstract":[{"text":"Clears the stored HWID from Keychain.","type":"text"}],"sections":[],"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshKeychain\/documentation\/PushwooshKeychain\/PushwooshKeychainImplementation\/clearPersistentHWID()","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"clearPersistentHWID","kind":"identifier"},{"kind":"text","text":"()"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshKeychain\/documentation\/PushwooshKeychain","doc:\/\/com.pushwoosh.PushwooshKeychain\/documentation\/PushwooshKeychain\/PushwooshKeychainImplementation"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshkeychain\/pushwooshkeychainimplementation\/clearpersistenthwid()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshkeychain\/pushwooshkeychainimplementation\/clearpersistenthwid()"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"externalID":"c:@M@PushwooshKeychain@objc(cs)PushwooshKeychainImplementation(cm)clearPersistentHWID","role":"symbol","title":"clearPersistentHWID()","navigatorTitle":[{"text":"clearPersistentHWID","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"clearPersistentHWID"},{"kind":"text","text":"()"}],"roleHeading":"Type Method","modules":[{"name":"PushwooshKeychain"}],"symbolKind":"method","platforms":[{"unavailable":false,"beta":false,"name":"iOS","introducedAt":"12.0","deprecated":false}]},"references":{"doc://com.pushwoosh.PushwooshKeychain/documentation/PushwooshKeychain/PushwooshKeychainImplementation/clearPersistentHWID()":{"abstract":[{"text":"Clears the stored HWID from Keychain.","type":"text"}],"url":"\/documentation\/pushwooshkeychain\/pushwooshkeychainimplementation\/clearpersistenthwid()","type":"topic","navigatorTitle":[{"text":"clearPersistentHWID","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshKeychain\/documentation\/PushwooshKeychain\/PushwooshKeychainImplementation\/clearPersistentHWID()","title":"clearPersistentHWID()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"clearPersistentHWID","kind":"identifier"},{"text":"()","kind":"text"}],"role":"symbol","kind":"symbol"},"doc://com.pushwoosh.PushwooshKeychain/documentation/PushwooshKeychain":{"identifier":"doc:\/\/com.pushwoosh.PushwooshKeychain\/documentation\/PushwooshKeychain","url":"\/documentation\/pushwooshkeychain","role":"collection","type":"topic","kind":"symbol","abstract":[],"title":"PushwooshKeychain"},"doc://com.pushwoosh.PushwooshKeychain/documentation/PushwooshKeychain/PushwooshKeychainImplementation":{"identifier":"doc:\/\/com.pushwoosh.PushwooshKeychain\/documentation\/PushwooshKeychain\/PushwooshKeychainImplementation","role":"symbol","abstract":[{"type":"text","text":"Implementation of persistent HWID storage using iOS Keychain."}],"title":"PushwooshKeychainImplementation","kind":"symbol","url":"\/documentation\/pushwooshkeychain\/pushwooshkeychainimplementation","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PushwooshKeychainImplementation"}],"navigatorTitle":[{"text":"PushwooshKeychainImplementation","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","value":"clearPersistentHWID","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"clearPersistentHWID","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"text":"clearPersistentHWID","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"clearPersistentHWID","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshKeychain~1documentation~1PushwooshKeychain~1PushwooshKeychainImplementation~1clearPersistentHWID()\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshKeychain~1documentation~1PushwooshKeychain~1PushwooshKeychainImplementation~1clearPersistentHWID()\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"clearPersistentHWID"}]},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshKeychain~1documentation~1PushwooshKeychain~1PushwooshKeychainImplementation\/title","op":"replace","value":"PushwooshKeychainImplementation"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshKeychain~1documentation~1PushwooshKeychain~1PushwooshKeychainImplementation\/fragments","value":[{"text":"PushwooshKeychainImplementation","kind":"identifier"}]}]}]}