{"sections":[],"abstract":[{"type":"text","text":"Returns the current application environment."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"currentEnvironment","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PWAppEnvironment","kind":"typeIdentifier","preciseIdentifier":"c:@M@PushwooshBridge@E@PWAppEnvironment"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshkeychain\/pushwooshkeychainimplementation\/currentenvironment"]},{"paths":["\/documentation\/pushwooshkeychain\/pushwooshkeychainimplementation\/currentenvironment"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshKeychain\/documentation\/PushwooshKeychain","doc:\/\/com.pushwoosh.PushwooshKeychain\/documentation\/PushwooshKeychain\/PushwooshKeychainImplementation"]]},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"externalID":"c:@M@PushwooshKeychain@objc(cs)PushwooshKeychainImplementation(cpy)currentEnvironment","platforms":[{"introducedAt":"12.0","beta":false,"unavailable":false,"deprecated":false,"name":"iOS"}],"symbolKind":"property","navigatorTitle":[{"text":"currentEnvironment","kind":"identifier"}],"roleHeading":"Type Property","title":"currentEnvironment","role":"symbol","modules":[{"name":"PushwooshKeychain"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"currentEnvironment","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@PushwooshBridge@E@PWAppEnvironment","text":"PWAppEnvironment","kind":"typeIdentifier"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshKeychain\/documentation\/PushwooshKeychain\/PushwooshKeychainImplementation\/currentEnvironment"},"references":{"doc://com.pushwoosh.PushwooshKeychain/documentation/PushwooshKeychain/PushwooshKeychainImplementation/currentEnvironment":{"abstract":[{"text":"Returns the current application environment.","type":"text"}],"navigatorTitle":[{"text":"currentEnvironment","kind":"identifier"}],"title":"currentEnvironment","url":"\/documentation\/pushwooshkeychain\/pushwooshkeychainimplementation\/currentenvironment","type":"topic","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshKeychain\/documentation\/PushwooshKeychain\/PushwooshKeychainImplementation\/currentEnvironment","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"currentEnvironment","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@PushwooshBridge@E@PWAppEnvironment","kind":"typeIdentifier","text":"PWAppEnvironment"}]},"doc://com.pushwoosh.PushwooshKeychain/documentation/PushwooshKeychain":{"role":"collection","kind":"symbol","url":"\/documentation\/pushwooshkeychain","identifier":"doc:\/\/com.pushwoosh.PushwooshKeychain\/documentation\/PushwooshKeychain","type":"topic","abstract":[],"title":"PushwooshKeychain"},"doc://com.pushwoosh.PushwooshKeychain/documentation/PushwooshKeychain/PushwooshKeychainImplementation":{"title":"PushwooshKeychainImplementation","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PushwooshKeychainImplementation","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"text":"Implementation of persistent HWID storage using iOS Keychain.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshKeychain\/documentation\/PushwooshKeychain\/PushwooshKeychainImplementation","url":"\/documentation\/pushwooshkeychain\/pushwooshkeychainimplementation","navigatorTitle":[{"text":"PushwooshKeychainImplementation","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Type Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"currentEnvironment","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"currentEnvironment"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PWAppEnvironment","preciseIdentifier":"c:@M@PushwooshBridge@E@PWAppEnvironment","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"currentEnvironment","kind":"identifier"},{"kind":"text","text":";"}]}]},"op":"replace"},{"op":"replace","value":"currentEnvironment","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshKeychain~1documentation~1PushwooshKeychain~1PushwooshKeychainImplementation~1currentEnvironment\/title"},{"value":[{"kind":"identifier","text":"currentEnvironment"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshKeychain~1documentation~1PushwooshKeychain~1PushwooshKeychainImplementation~1currentEnvironment\/fragments"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshKeychain~1documentation~1PushwooshKeychain~1PushwooshKeychainImplementation\/title","op":"replace","value":"PushwooshKeychainImplementation"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshKeychain~1documentation~1PushwooshKeychain~1PushwooshKeychainImplementation\/fragments","value":[{"text":"PushwooshKeychainImplementation","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}