{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getPersistentHWID"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"languages":["swift"]}]},{"kind":"content","content":[{"text":"Discussion","anchor":"discussion","level":2,"type":"heading"},{"inlineContent":[{"text":"This method:","type":"text"}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Returns "},{"code":"nil","type":"codeVoice"},{"type":"text","text":" in App Store builds (module disabled)"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Returns existing HWID from Keychain if found","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Creates and stores new HWID in Keychain if not found (first launch)"}],"type":"paragraph"}]}],"type":"unorderedList"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Returns the persistent HWID from Keychain, or nil if not available."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshkeychain\/pushwooshkeychainimplementation\/getpersistenthwid()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshkeychain\/pushwooshkeychainimplementation\/getpersistenthwid()"]}],"kind":"symbol","metadata":{"modules":[{"name":"PushwooshKeychain"}],"role":"symbol","externalID":"c:@M@PushwooshKeychain@objc(cs)PushwooshKeychainImplementation(cm)getPersistentHWID","navigatorTitle":[{"kind":"identifier","text":"getPersistentHWID"}],"platforms":[{"deprecated":false,"introducedAt":"12.0","beta":false,"name":"iOS","unavailable":false}],"title":"getPersistentHWID()","symbolKind":"method","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getPersistentHWID","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"roleHeading":"Type Method"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshKeychain\/documentation\/PushwooshKeychain","doc:\/\/com.pushwoosh.PushwooshKeychain\/documentation\/PushwooshKeychain\/PushwooshKeychainImplementation"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshKeychain\/documentation\/PushwooshKeychain\/PushwooshKeychainImplementation\/getPersistentHWID()"},"references":{"doc://com.pushwoosh.PushwooshKeychain/documentation/PushwooshKeychain/PushwooshKeychainImplementation/getPersistentHWID()":{"kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"text":"getPersistentHWID","kind":"identifier"}],"title":"getPersistentHWID()","identifier":"doc:\/\/com.pushwoosh.PushwooshKeychain\/documentation\/PushwooshKeychain\/PushwooshKeychainImplementation\/getPersistentHWID()","abstract":[{"text":"Returns the persistent HWID from Keychain, or nil if not available.","type":"text"}],"url":"\/documentation\/pushwooshkeychain\/pushwooshkeychainimplementation\/getpersistenthwid()","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getPersistentHWID"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}]},"doc://com.pushwoosh.PushwooshKeychain/documentation/PushwooshKeychain/PushwooshKeychainImplementation":{"type":"topic","kind":"symbol","abstract":[{"text":"Implementation of persistent HWID storage using iOS Keychain.","type":"text"}],"title":"PushwooshKeychainImplementation","role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshKeychain\/documentation\/PushwooshKeychain\/PushwooshKeychainImplementation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushwooshKeychainImplementation"}],"navigatorTitle":[{"kind":"identifier","text":"PushwooshKeychainImplementation"}],"url":"\/documentation\/pushwooshkeychain\/pushwooshkeychainimplementation"},"doc://com.pushwoosh.PushwooshKeychain/documentation/PushwooshKeychain":{"kind":"symbol","title":"PushwooshKeychain","url":"\/documentation\/pushwooshkeychain","identifier":"doc:\/\/com.pushwoosh.PushwooshKeychain\/documentation\/PushwooshKeychain","abstract":[],"type":"topic","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"getPersistentHWID","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"text":"getPersistentHWID","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"getPersistentHWID"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshKeychain~1documentation~1PushwooshKeychain~1PushwooshKeychainImplementation~1getPersistentHWID()\/title","op":"replace","value":"getPersistentHWID"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshKeychain~1documentation~1PushwooshKeychain~1PushwooshKeychainImplementation~1getPersistentHWID()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getPersistentHWID"}]},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshKeychain~1documentation~1PushwooshKeychain~1PushwooshKeychainImplementation\/title","value":"PushwooshKeychainImplementation","op":"replace"},{"value":[{"kind":"identifier","text":"PushwooshKeychainImplementation"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshKeychain~1documentation~1PushwooshKeychain~1PushwooshKeychainImplementation\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}