{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshKeychain\/documentation\/PushwooshKeychain\/PushwooshKeychainImplementation\/isEnabled"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshkeychain\/pushwooshkeychainimplementation\/isenabled"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshkeychain\/pushwooshkeychainimplementation\/isenabled"]}],"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEnabled"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}]}],"kind":"declarations"},{"kind":"content","content":[{"level":2,"type":"heading","anchor":"discussion","text":"Discussion"},{"inlineContent":[{"type":"text","text":"Returns "},{"type":"codeVoice","code":"true"},{"text":" for Simulator, Debug, and TestFlight builds.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Returns "},{"type":"codeVoice","code":"false"},{"text":" for App Store builds.","type":"text"}],"type":"paragraph"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Indicates whether persistent HWID storage is enabled."}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshKeychain\/documentation\/PushwooshKeychain","doc:\/\/com.pushwoosh.PushwooshKeychain\/documentation\/PushwooshKeychain\/PushwooshKeychainImplementation"]]},"metadata":{"externalID":"c:@M@PushwooshKeychain@objc(cs)PushwooshKeychainImplementation(cpy)isEnabled","modules":[{"name":"PushwooshKeychain"}],"title":"isEnabled","roleHeading":"Type Property","role":"symbol","navigatorTitle":[{"text":"isEnabled","kind":"identifier"}],"symbolKind":"property","platforms":[{"unavailable":false,"introducedAt":"12.0","beta":false,"deprecated":false,"name":"iOS"}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEnabled","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}]},"kind":"symbol","references":{"doc://com.pushwoosh.PushwooshKeychain/documentation/PushwooshKeychain/PushwooshKeychainImplementation":{"identifier":"doc:\/\/com.pushwoosh.PushwooshKeychain\/documentation\/PushwooshKeychain\/PushwooshKeychainImplementation","role":"symbol","abstract":[{"type":"text","text":"Implementation of persistent HWID storage using iOS Keychain."}],"title":"PushwooshKeychainImplementation","kind":"symbol","url":"\/documentation\/pushwooshkeychain\/pushwooshkeychainimplementation","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PushwooshKeychainImplementation"}],"navigatorTitle":[{"text":"PushwooshKeychainImplementation","kind":"identifier"}]},"doc://com.pushwoosh.PushwooshKeychain/documentation/PushwooshKeychain":{"identifier":"doc:\/\/com.pushwoosh.PushwooshKeychain\/documentation\/PushwooshKeychain","url":"\/documentation\/pushwooshkeychain","role":"collection","type":"topic","kind":"symbol","abstract":[],"title":"PushwooshKeychain"},"doc://com.pushwoosh.PushwooshKeychain/documentation/PushwooshKeychain/PushwooshKeychainImplementation/isEnabled":{"abstract":[{"type":"text","text":"Indicates whether persistent HWID storage is enabled."}],"url":"\/documentation\/pushwooshkeychain\/pushwooshkeychainimplementation\/isenabled","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isEnabled"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshKeychain\/documentation\/PushwooshKeychain\/PushwooshKeychainImplementation\/isEnabled","title":"isEnabled","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEnabled"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"role":"symbol","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"op":"replace","path":"\/metadata\/title","value":"isEnabled"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"isEnabled"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"class","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"isEnabled","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshKeychain~1documentation~1PushwooshKeychain~1PushwooshKeychainImplementation\/title","op":"replace","value":"PushwooshKeychainImplementation"},{"op":"replace","value":[{"kind":"identifier","text":"PushwooshKeychainImplementation"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshKeychain~1documentation~1PushwooshKeychain~1PushwooshKeychainImplementation\/fragments"},{"value":"isEnabled","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshKeychain~1documentation~1PushwooshKeychain~1PushwooshKeychainImplementation~1isEnabled\/title","op":"replace"},{"value":[{"text":"isEnabled","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshKeychain~1documentation~1PushwooshKeychain~1PushwooshKeychainImplementation~1isEnabled\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}