{"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshKeychain\/documentation\/PushwooshKeychain","doc:\/\/com.pushwoosh.PushwooshKeychain\/documentation\/PushwooshKeychain\/PushwooshKeychainImplementation"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"Returns the Keychain implementation class."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshKeychain\/documentation\/PushwooshKeychain\/PushwooshKeychainImplementation\/keychain()"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"keychain"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"AnyClass","preciseIdentifier":"s:s8AnyClassa"}],"languages":["swift"],"platforms":["iOS"]}]}],"metadata":{"roleHeading":"Type Method","navigatorTitle":[{"text":"keychain","kind":"identifier"}],"platforms":[{"unavailable":false,"introducedAt":"12.0","deprecated":false,"beta":false,"name":"iOS"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"keychain","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"AnyClass","preciseIdentifier":"s:s8AnyClassa","kind":"typeIdentifier"}],"role":"symbol","externalID":"c:@M@PushwooshKeychain@objc(cs)PushwooshKeychainImplementation(cm)keychain","symbolKind":"method","title":"keychain()","modules":[{"name":"PushwooshKeychain"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshkeychain\/pushwooshkeychainimplementation\/keychain()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshkeychain\/pushwooshkeychainimplementation\/keychain()"]}],"sections":[],"references":{"doc://com.pushwoosh.PushwooshKeychain/documentation/PushwooshKeychain":{"type":"topic","url":"\/documentation\/pushwooshkeychain","title":"PushwooshKeychain","identifier":"doc:\/\/com.pushwoosh.PushwooshKeychain\/documentation\/PushwooshKeychain","kind":"symbol","role":"collection","abstract":[]},"doc://com.pushwoosh.PushwooshKeychain/documentation/PushwooshKeychain/PushwooshKeychainImplementation":{"navigatorTitle":[{"text":"PushwooshKeychainImplementation","kind":"identifier"}],"abstract":[{"type":"text","text":"Implementation of persistent HWID storage using iOS Keychain."}],"identifier":"doc:\/\/com.pushwoosh.PushwooshKeychain\/documentation\/PushwooshKeychain\/PushwooshKeychainImplementation","url":"\/documentation\/pushwooshkeychain\/pushwooshkeychainimplementation","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PushwooshKeychainImplementation","kind":"identifier"}],"role":"symbol","title":"PushwooshKeychainImplementation"},"doc://com.pushwoosh.PushwooshKeychain/documentation/PushwooshKeychain/PushwooshKeychainImplementation/keychain()":{"url":"\/documentation\/pushwooshkeychain\/pushwooshkeychainimplementation\/keychain()","navigatorTitle":[{"kind":"identifier","text":"keychain"}],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"keychain","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"AnyClass","kind":"typeIdentifier","preciseIdentifier":"s:s8AnyClassa"}],"title":"keychain()","abstract":[{"type":"text","text":"Returns the Keychain implementation class."}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshKeychain\/documentation\/PushwooshKeychain\/PushwooshKeychainImplementation\/keychain()"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"path":"\/metadata\/title","value":"keychain","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"keychain"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","text":"Class","preciseIdentifier":"c:*QO"},{"kind":"text","text":") "},{"kind":"identifier","text":"keychain"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshKeychain~1documentation~1PushwooshKeychain~1PushwooshKeychainImplementation\/title","value":"PushwooshKeychainImplementation","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshKeychain~1documentation~1PushwooshKeychain~1PushwooshKeychainImplementation\/fragments","value":[{"kind":"identifier","text":"PushwooshKeychainImplementation"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshKeychain~1documentation~1PushwooshKeychain~1PushwooshKeychainImplementation~1keychain()\/title","value":"keychain"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshKeychain~1documentation~1PushwooshKeychain~1PushwooshKeychainImplementation~1keychain()\/fragments","value":[{"kind":"text","text":"+ "},{"text":"keychain","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}