{"metadata":{"externalID":"c:@M@PushwooshKeychain@objc(cs)PushwooshKeychainImplementation(cpy)shared","role":"symbol","symbolKind":"property","title":"shared","platforms":[{"name":"iOS","deprecated":false,"unavailable":false,"beta":false,"introducedAt":"12.0"}],"navigatorTitle":[{"kind":"identifier","text":"shared"}],"roleHeading":"Type Property","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"shared"},{"kind":"text","text":": "},{"text":"PushwooshKeychainImplementation","kind":"typeIdentifier","preciseIdentifier":"c:@M@PushwooshKeychain@objc(cs)PushwooshKeychainImplementation"}],"modules":[{"name":"PushwooshKeychain"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(shared) ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"shared"},{"text":": ","kind":"text"},{"text":"PushwooshKeychainImplementation","preciseIdentifier":"c:@M@PushwooshKeychain@objc(cs)PushwooshKeychainImplementation","kind":"typeIdentifier","identifier":"doc:\/\/com.pushwoosh.PushwooshKeychain\/documentation\/PushwooshKeychain\/PushwooshKeychainImplementation"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshKeychain\/documentation\/PushwooshKeychain\/PushwooshKeychainImplementation\/shared","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshKeychain\/documentation\/PushwooshKeychain","doc:\/\/com.pushwoosh.PushwooshKeychain\/documentation\/PushwooshKeychain\/PushwooshKeychainImplementation"]]},"abstract":[{"type":"text","text":"Shared singleton instance."}],"kind":"symbol","variants":[{"paths":["\/documentation\/pushwooshkeychain\/pushwooshkeychainimplementation\/shared"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pushwooshkeychain\/pushwooshkeychainimplementation\/shared"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.pushwoosh.PushwooshKeychain/documentation/PushwooshKeychain":{"type":"topic","role":"collection","abstract":[],"identifier":"doc:\/\/com.pushwoosh.PushwooshKeychain\/documentation\/PushwooshKeychain","title":"PushwooshKeychain","kind":"symbol","url":"\/documentation\/pushwooshkeychain"},"doc://com.pushwoosh.PushwooshKeychain/documentation/PushwooshKeychain/PushwooshKeychainImplementation":{"url":"\/documentation\/pushwooshkeychain\/pushwooshkeychainimplementation","kind":"symbol","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshKeychain\/documentation\/PushwooshKeychain\/PushwooshKeychainImplementation","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushwooshKeychainImplementation"}],"title":"PushwooshKeychainImplementation","abstract":[{"type":"text","text":"Implementation of persistent HWID storage using iOS Keychain."}],"role":"symbol","navigatorTitle":[{"text":"PushwooshKeychainImplementation","kind":"identifier"}]},"doc://com.pushwoosh.PushwooshKeychain/documentation/PushwooshKeychain/PushwooshKeychainImplementation/shared":{"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshKeychain\/documentation\/PushwooshKeychain\/PushwooshKeychainImplementation\/shared","url":"\/documentation\/pushwooshkeychain\/pushwooshkeychainimplementation\/shared","title":"shared","abstract":[{"type":"text","text":"Shared singleton instance."}],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"shared","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@PushwooshKeychain@objc(cs)PushwooshKeychainImplementation","text":"PushwooshKeychainImplementation","kind":"typeIdentifier"}],"kind":"symbol","navigatorTitle":[{"text":"shared","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Type Property","path":"\/metadata\/roleHeading"},{"value":"shared","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"shared"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/com.pushwoosh.PushwooshKeychain\/documentation\/PushwooshKeychain\/PushwooshKeychainImplementation","text":"PushwooshKeychainImplementation","preciseIdentifier":"c:@M@PushwooshKeychain@objc(cs)PushwooshKeychainImplementation","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"shared","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshKeychain~1documentation~1PushwooshKeychain~1PushwooshKeychainImplementation\/title","op":"replace","value":"PushwooshKeychainImplementation"},{"value":[{"text":"PushwooshKeychainImplementation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshKeychain~1documentation~1PushwooshKeychain~1PushwooshKeychainImplementation\/fragments"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshKeychain~1documentation~1PushwooshKeychain~1PushwooshKeychainImplementation~1shared\/title","value":"shared","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshKeychain~1documentation~1PushwooshKeychain~1PushwooshKeychainImplementation~1shared\/fragments","value":[{"kind":"identifier","text":"shared"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}