{"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/pushwooshnotificationui"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pushwooshnotificationui"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"A ready-made full-screen “stories” UI for an expanded push notification."}],"metadata":{"roleHeading":"Framework","modules":[{"name":"PushwooshNotificationUI"}],"role":"collection","title":"PushwooshNotificationUI","symbolKind":"module","externalID":"PushwooshNotificationUI"},"topicSections":[{"title":"Stories UI","identifiers":["doc:\/\/com.pushwoosh.PushwooshNotificationUI\/documentation\/PushwooshNotificationUI\/PushwooshStoriesViewController"]},{"identifiers":["doc:\/\/com.pushwoosh.PushwooshNotificationUI\/documentation\/PushwooshNotificationUI\/StoryPage"],"title":"Payload model"},{"title":"Analytics","identifiers":["doc:\/\/com.pushwoosh.PushwooshNotificationUI\/documentation\/PushwooshNotificationUI\/PushwooshStoriesDelegate"]},{"title":"Media pre-cache","identifiers":["doc:\/\/com.pushwoosh.PushwooshNotificationUI\/documentation\/PushwooshNotificationUI\/PushwooshStoriesMediaPrefetcher"]}],"primaryContentSections":[{"content":[{"anchor":"Overview","text":"Overview","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"PushwooshNotificationUI provides "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.pushwoosh.PushwooshNotificationUI\/documentation\/PushwooshNotificationUI\/PushwooshStoriesViewController"},{"text":" — a drop-in","type":"text"},{"type":"text","text":" "},{"type":"codeVoice","code":"UNNotificationContentExtension"},{"type":"text","text":" view controller that renders an Instagram-style"},{"type":"text","text":" "},{"text":"stories experience: full-bleed images, top progress bars, auto-advance, tap-zone","type":"text"},{"type":"text","text":" "},{"type":"text","text":"navigation, per-frame title\/subtitle, and an optional deep-link button."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"The module links only UIKit, UserNotifications, and UserNotificationsUI (plus"},{"text":" ","type":"text"},{"type":"text","text":"CryptoKit for a stable cache key), so it adds no Pushwoosh Core\/Framework weight"},{"type":"text","text":" "},{"text":"to your memory-constrained extension process.","type":"text"}]},{"text":"Usage","level":2,"anchor":"Usage","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"In your Notification Content Extension:"}]},{"syntax":"swift","type":"codeListing","code":["import PushwooshNotificationUI","","class NotificationViewController: PushwooshStoriesViewController {}"]},{"inlineContent":[{"type":"text","text":"Then set these keys in the extension’s Info.plist:"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"code":"UNNotificationExtensionCategory","type":"codeVoice"},{"type":"text","text":" = "},{"type":"codeVoice","code":"PW_STORIES"},{"type":"text","text":" (must match "},{"type":"codeVoice","code":"aps.category"},{"text":")","type":"text"}]}]},{"content":[{"inlineContent":[{"code":"UNNotificationExtensionUserInteractionEnabled","type":"codeVoice"},{"type":"text","text":" = "},{"type":"codeVoice","code":"YES"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"codeVoice","code":"UNNotificationExtensionDefaultContentHidden"},{"text":" = ","type":"text"},{"code":"YES","type":"codeVoice"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"code":"UNNotificationExtensionInitialContentSizeRatio","type":"codeVoice"},{"type":"text","text":" = e.g. "},{"type":"codeVoice","code":"1.5"},{"type":"text","text":" (keep in sync with "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.pushwoosh.PushwooshNotificationUI\/documentation\/PushwooshNotificationUI\/PushwooshStoriesViewController\/storyAspectRatio"},{"type":"text","text":")"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"NSExtensionPrincipalClass"},{"text":" = ","type":"text"},{"code":"$(PRODUCT_MODULE_NAME).NotificationViewController","type":"codeVoice"},{"type":"text","text":" (code-only, no storyboard)"}]}]}]},{"anchor":"Payload","level":2,"type":"heading","text":"Payload"},{"inlineContent":[{"type":"text","text":"The stories are described by a "},{"code":"pw_stories","type":"codeVoice"},{"text":" block, alongside an ","type":"text"},{"type":"codeVoice","code":"aps.category"},{"text":" ","type":"text"},{"text":"matching ","type":"text"},{"code":"UNNotificationExtensionCategory","type":"codeVoice"},{"type":"text","text":". The parser accepts the block either at"},{"type":"text","text":" "},{"type":"text","text":"the "},{"type":"strong","inlineContent":[{"text":"payload root","type":"text"}]},{"type":"text","text":" (e.g. via the Pushwoosh API "},{"type":"codeVoice","code":"ios_root_params"},{"type":"text","text":") or inside the"},{"type":"text","text":" "},{"text":"custom-data container ","type":"text"},{"type":"codeVoice","code":"u"},{"text":" \/ ","type":"text"},{"code":"userdata","type":"codeVoice"},{"text":" (the Pushwoosh API ","type":"text"},{"type":"codeVoice","code":"data"},{"text":" field — delivered as","type":"text"},{"type":"text","text":" "},{"text":"a dictionary or a JSON-encoded string). The root form on the device looks like this:","type":"text"}],"type":"paragraph"},{"code":["{","  \"aps\": { \"category\": \"PW_STORIES\" },","  \"pw_stories\": { \"pages\": [","    { \"image\": \"https:\/\/...\/1.jpg\", \"duration\": 5.0,","      \"link\": \"myapp:\/\/sale\", \"button_title\": \"Buy\",","      \"title\": \"Summer Sale\", \"subtitle\": \"Up to 70% off\" },","    { \"image\": \"https:\/\/...\/2.jpg\" }","  ]}","}"],"type":"codeListing","syntax":"json"},{"type":"paragraph","inlineContent":[{"text":"Sent through the ","type":"text"},{"code":"data","type":"codeVoice"},{"text":" API field instead (recommended, since it does not depend on","type":"text"},{"type":"text","text":" "},{"code":"ios_root_params","type":"codeVoice"},{"type":"text","text":"), the same block arrives nested under "},{"code":"u","type":"codeVoice"},{"type":"text","text":" — while "},{"type":"codeVoice","code":"aps.category"},{"type":"text","text":" "},{"text":"(and ","type":"text"},{"type":"codeVoice","code":"mutable-content"},{"type":"text","text":" for the pre-cache path) still go through "},{"type":"codeVoice","code":"ios_root_params.aps"},{"type":"text","text":","},{"text":" ","type":"text"},{"text":"as there is no dedicated request field for them. The relevant createMessage fields:","type":"text"}]},{"code":["{","  \"ios_root_params\": { \"aps\": { \"category\": \"PW_STORIES\", \"mutable-content\": 1 } },","  \"data\": { \"pw_stories\": { \"pages\": [ { \"image\": \"https:\/\/...\/1.jpg\" } ] } }","}"],"syntax":"json","type":"codeListing"},{"inlineContent":[{"type":"text","text":"The parser tries the root first, then "},{"type":"codeVoice","code":"u"},{"type":"text","text":" \/ "},{"type":"codeVoice","code":"userdata"},{"type":"text","text":", so both delivery styles work"},{"text":" ","type":"text"},{"text":"and old pushes keep rendering.","type":"text"}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Every field except "},{"type":"codeVoice","code":"image"},{"type":"text","text":" is optional. "},{"code":"link","type":"codeVoice"},{"text":" (like ","type":"text"},{"code":"image","type":"codeVoice"},{"text":") must include a URL","type":"text"},{"type":"text","text":" "},{"type":"text","text":"scheme. A missing, empty, or malformed payload falls back to the default content"},{"text":" ","type":"text"},{"type":"text","text":"(the alert body) without crashing — override "},{"type":"reference","identifier":"doc:\/\/com.pushwoosh.PushwooshNotificationUI\/documentation\/PushwooshNotificationUI\/PushwooshStoriesViewController\/showDefaultContent(for:)","isActive":true},{"text":".","type":"text"}]},{"level":2,"anchor":"Analytics","text":"Analytics","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"Set ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.pushwoosh.PushwooshNotificationUI\/documentation\/PushwooshNotificationUI\/PushwooshStoriesViewController\/storiesDelegate","type":"reference"},{"type":"text","text":" to observe lifecycle and"},{"type":"text","text":" "},{"text":"engagement and forward it to your analytics (the module itself sends nothing):","type":"text"}]},{"type":"codeListing","syntax":"swift","code":["class NotificationViewController: PushwooshStoriesViewController, PushwooshStoriesDelegate {","    override func viewDidLoad() {","        super.viewDidLoad()","        storiesDelegate = self","    }","    func storiesViewController(_ c: PushwooshStoriesViewController, didTapActionFor page: StoryPage, at index: Int) {","        \/\/ forward the per-page click to your backend","    }","}"]},{"type":"heading","text":"Instant \/ offline first frame (App Group pre-cache)","level":2,"anchor":"Instant--offline-first-frame-App-Group-pre-cache"},{"type":"paragraph","inlineContent":[{"type":"text","text":"To make the first frame appear instantly (and offline), pre-download the media in"},{"type":"text","text":" "},{"text":"a Notification ","type":"text"},{"inlineContent":[{"type":"text","text":"Service"}],"type":"strong"},{"type":"text","text":" Extension into a shared App Group container that the"},{"type":"text","text":" "},{"type":"text","text":"Content Extension reads from:"}]},{"items":[{"content":[{"inlineContent":[{"text":"Enable the ","type":"text"},{"inlineContent":[{"text":"App Groups","type":"text"}],"type":"strong"},{"text":" capability (same id) on both the Service and Content","type":"text"},{"type":"text","text":" "},{"type":"text","text":"extensions, and override "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.pushwoosh.PushwooshNotificationUI\/documentation\/PushwooshNotificationUI\/PushwooshStoriesViewController\/appGroupIdentifier"},{"type":"text","text":"."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"From the Service Extension’s "},{"code":"didReceive(_:withContentHandler:)","type":"codeVoice"},{"type":"text","text":", call"},{"type":"text","text":" "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.pushwoosh.PushwooshNotificationUI\/documentation\/PushwooshNotificationUI\/PushwooshStoriesMediaPrefetcher\/prefetch(userInfo:appGroupIdentifier:completion:)"},{"type":"text","text":"."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Send the push with "},{"code":"mutable-content: 1","type":"codeVoice"},{"type":"text","text":" so the Service Extension runs."}]}]}],"type":"orderedList"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Without this, the module still works — images download on display instead."}]}],"kind":"content"}],"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshNotificationUI\/documentation\/PushwooshNotificationUI"},"hierarchy":{"paths":[[]]},"references":{"doc://com.pushwoosh.PushwooshNotificationUI/documentation/PushwooshNotificationUI/PushwooshStoriesMediaPrefetcher/prefetch(userInfo:appGroupIdentifier:completion:)":{"url":"\/documentation\/pushwooshnotificationui\/pushwooshstoriesmediaprefetcher\/prefetch(userinfo:appgroupidentifier:completion:)","kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"prefetch","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"userInfo"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"], "},{"text":"appGroupIdentifier","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": () -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")"}],"title":"prefetch(userInfo:appGroupIdentifier:completion:)","abstract":[],"identifier":"doc:\/\/com.pushwoosh.PushwooshNotificationUI\/documentation\/PushwooshNotificationUI\/PushwooshStoriesMediaPrefetcher\/prefetch(userInfo:appGroupIdentifier:completion:)"},"doc://com.pushwoosh.PushwooshNotificationUI/documentation/PushwooshNotificationUI/StoryPage":{"navigatorTitle":[{"kind":"identifier","text":"StoryPage"}],"abstract":[],"type":"topic","url":"\/documentation\/pushwooshnotificationui\/storypage","title":"StoryPage","identifier":"doc:\/\/com.pushwoosh.PushwooshNotificationUI\/documentation\/PushwooshNotificationUI\/StoryPage","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"StoryPage","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://com.pushwoosh.PushwooshNotificationUI/documentation/PushwooshNotificationUI/PushwooshStoriesViewController/appGroupIdentifier":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"appGroupIdentifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"text":"App Group identifier shared with your Notification Service Extension. When set (and the","type":"text"},{"type":"text","text":" "},{"text":"capability is enabled on both targets), the first frame is read from the shared container","type":"text"},{"type":"text","text":" "},{"text":"that the Service Extension pre-warmed — instant and offline. Defaults to ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" (uses ","type":"text"},{"code":"tmp","type":"codeVoice"},{"type":"text","text":")."}],"type":"topic","kind":"symbol","url":"\/documentation\/pushwooshnotificationui\/pushwooshstoriesviewcontroller\/appgroupidentifier","identifier":"doc:\/\/com.pushwoosh.PushwooshNotificationUI\/documentation\/PushwooshNotificationUI\/PushwooshStoriesViewController\/appGroupIdentifier","title":"appGroupIdentifier"},"doc://com.pushwoosh.PushwooshNotificationUI/documentation/PushwooshNotificationUI/PushwooshStoriesViewController":{"navigatorTitle":[{"text":"PushwooshStoriesViewController","kind":"identifier"}],"abstract":[{"type":"text","text":"A drop-in "},{"type":"codeVoice","code":"UNNotificationContentExtension"},{"type":"text","text":" view controller that renders a full-screen,"},{"type":"text","text":" "},{"text":"Instagram-style “stories” experience for an expanded push notification: full-bleed images,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"top progress bars, an auto-advance timer, tap-zone navigation, and an optional deep-link button."}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshNotificationUI\/documentation\/PushwooshNotificationUI\/PushwooshStoriesViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PushwooshStoriesViewController","kind":"identifier"}],"url":"\/documentation\/pushwooshnotificationui\/pushwooshstoriesviewcontroller","kind":"symbol","title":"PushwooshStoriesViewController"},"doc://com.pushwoosh.PushwooshNotificationUI/documentation/PushwooshNotificationUI/PushwooshNotificationUIVersionString":{"role":"symbol","fragments":[{"text":"PushwooshNotificationUIVersionString","kind":"identifier"}],"type":"topic","abstract":[{"text":"Project version string for PushwooshNotificationUI.","type":"text"}],"kind":"symbol","url":"\/documentation\/pushwooshnotificationui\/pushwooshnotificationuiversionstring","identifier":"doc:\/\/com.pushwoosh.PushwooshNotificationUI\/documentation\/PushwooshNotificationUI\/PushwooshNotificationUIVersionString","title":"PushwooshNotificationUIVersionString"},"doc://com.pushwoosh.PushwooshNotificationUI/documentation/PushwooshNotificationUI/PushwooshStoriesDelegate":{"navigatorTitle":[{"text":"PushwooshStoriesDelegate","kind":"identifier"}],"abstract":[{"text":"Optional analytics \/ lifecycle hooks for ","type":"text"},{"identifier":"doc:\/\/com.pushwoosh.PushwooshNotificationUI\/documentation\/PushwooshNotificationUI\/PushwooshStoriesViewController","type":"reference","isActive":true},{"text":".","type":"text"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshNotificationUI\/documentation\/PushwooshNotificationUI\/PushwooshStoriesDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"PushwooshStoriesDelegate","kind":"identifier"}],"url":"\/documentation\/pushwooshnotificationui\/pushwooshstoriesdelegate","kind":"symbol","title":"PushwooshStoriesDelegate"},"doc://com.pushwoosh.PushwooshNotificationUI/documentation/PushwooshNotificationUI":{"abstract":[{"type":"text","text":"A ready-made full-screen “stories” UI for an expanded push notification."}],"kind":"symbol","url":"\/documentation\/pushwooshnotificationui","title":"PushwooshNotificationUI","identifier":"doc:\/\/com.pushwoosh.PushwooshNotificationUI\/documentation\/PushwooshNotificationUI","type":"topic","role":"collection"},"doc://com.pushwoosh.PushwooshNotificationUI/documentation/PushwooshNotificationUI/PushwooshNotificationUIVersionNumber":{"url":"\/documentation\/pushwooshnotificationui\/pushwooshnotificationuiversionnumber","fragments":[{"text":"PushwooshNotificationUIVersionNumber","kind":"identifier"}],"abstract":[{"type":"text","text":"Project version number for PushwooshNotificationUI."}],"role":"symbol","type":"topic","kind":"symbol","title":"PushwooshNotificationUIVersionNumber","identifier":"doc:\/\/com.pushwoosh.PushwooshNotificationUI\/documentation\/PushwooshNotificationUI\/PushwooshNotificationUIVersionNumber"},"doc://com.pushwoosh.PushwooshNotificationUI/documentation/PushwooshNotificationUI/PushwooshStoriesMediaPrefetcher":{"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PushwooshStoriesMediaPrefetcher"}],"navigatorTitle":[{"text":"PushwooshStoriesMediaPrefetcher","kind":"identifier"}],"abstract":[{"text":"Entry point for a Notification ","type":"text"},{"inlineContent":[{"type":"text","text":"Service"}],"type":"strong"},{"type":"text","text":" Extension: pre-downloads the story media referenced"},{"text":" ","type":"text"},{"text":"by a ","type":"text"},{"code":"pw_stories","type":"codeVoice"},{"text":" payload into the shared App Group container, so the Content Extension can","type":"text"},{"type":"text","text":" "},{"text":"render the first frame instantly and offline. Call from ","type":"text"},{"type":"codeVoice","code":"didReceive(_:withContentHandler:)"},{"text":".","type":"text"}],"type":"topic","kind":"symbol","url":"\/documentation\/pushwooshnotificationui\/pushwooshstoriesmediaprefetcher","identifier":"doc:\/\/com.pushwoosh.PushwooshNotificationUI\/documentation\/PushwooshNotificationUI\/PushwooshStoriesMediaPrefetcher","title":"PushwooshStoriesMediaPrefetcher"},"doc://com.pushwoosh.PushwooshNotificationUI/documentation/PushwooshNotificationUI/PushwooshStoriesViewController/storyAspectRatio":{"kind":"symbol","role":"symbol","url":"\/documentation\/pushwooshnotificationui\/pushwooshstoriesviewcontroller\/storyaspectratio","abstract":[{"text":"Aspect ratio (height ÷ width) of the stories area. Keep this in sync with the extension’s","type":"text"},{"type":"text","text":" "},{"code":"UNNotificationExtensionInitialContentSizeRatio","type":"codeVoice"},{"type":"text","text":" so the notification doesn’t resize after the"},{"type":"text","text":" "},{"type":"text","text":"image loads. Override in a subclass to change the story proportions."}],"identifier":"doc:\/\/com.pushwoosh.PushwooshNotificationUI\/documentation\/PushwooshNotificationUI\/PushwooshStoriesViewController\/storyAspectRatio","title":"storyAspectRatio","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"storyAspectRatio"},{"kind":"text","text":": "},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}]},"doc://com.pushwoosh.PushwooshNotificationUI/documentation/PushwooshNotificationUI/PushwooshStoriesViewController/storiesDelegate":{"kind":"symbol","title":"storiesDelegate","identifier":"doc:\/\/com.pushwoosh.PushwooshNotificationUI\/documentation\/PushwooshNotificationUI\/PushwooshStoriesViewController\/storiesDelegate","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"storiesDelegate"},{"kind":"text","text":": "},{"preciseIdentifier":"s:23PushwooshNotificationUI0A15StoriesDelegateP","text":"PushwooshStoriesDelegate","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"url":"\/documentation\/pushwooshnotificationui\/pushwooshstoriesviewcontroller\/storiesdelegate","abstract":[{"type":"text","text":"Optional observer for story lifecycle \/ analytics events. Every method is optional —"},{"text":" ","type":"text"},{"type":"text","text":"implement only the callbacks you need (impressions, clicks, completion, fallback)."}]},"doc://com.pushwoosh.PushwooshNotificationUI/documentation/PushwooshNotificationUI/PushwooshStoriesViewController/showDefaultContent(for:)":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"showDefaultContent"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"text":"UNNotification","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UNNotification"},{"text":")","kind":"text"}],"type":"topic","abstract":[{"text":"Subclasses may override to customise the no-stories fallback. Default: show the alert body.","type":"text"}],"kind":"symbol","url":"\/documentation\/pushwooshnotificationui\/pushwooshstoriesviewcontroller\/showdefaultcontent(for:)","identifier":"doc:\/\/com.pushwoosh.PushwooshNotificationUI\/documentation\/PushwooshNotificationUI\/PushwooshStoriesViewController\/showDefaultContent(for:)","title":"showDefaultContent(for:)"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":[{"title":"Stories UI","identifiers":["doc:\/\/com.pushwoosh.PushwooshNotificationUI\/documentation\/PushwooshNotificationUI\/PushwooshStoriesViewController"]},{"title":"Variables","identifiers":["doc:\/\/com.pushwoosh.PushwooshNotificationUI\/documentation\/PushwooshNotificationUI\/PushwooshNotificationUIVersionNumber","doc:\/\/com.pushwoosh.PushwooshNotificationUI\/documentation\/PushwooshNotificationUI\/PushwooshNotificationUIVersionString"]}],"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshNotificationUI~1documentation~1PushwooshNotificationUI~1PushwooshStoriesViewController\/title","value":"PushwooshStoriesViewController","op":"replace"},{"op":"replace","value":[{"text":"PushwooshStoriesViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshNotificationUI~1documentation~1PushwooshNotificationUI~1PushwooshStoriesViewController\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}