{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"provider","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"provider"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)CXProvider","kind":"typeIdentifier","text":"CXProvider"},{"kind":"text","text":", "},{"text":"perform","kind":"externalParam"},{"kind":"text","text":" "},{"text":"action","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)CXSetMutedCallAction","text":"CXSetMutedCallAction","kind":"typeIdentifier"},{"kind":"text","text":")"}],"languages":["swift"]}]}],"metadata":{"modules":[{"name":"PushwooshVoIP"}],"platforms":[{"deprecated":false,"introducedAt":"14.0","name":"iOS","beta":false,"unavailable":false}],"role":"symbol","title":"provider(_:perform:)","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"provider","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CXProvider","text":"CXProvider"},{"text":", ","kind":"text"},{"text":"perform","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CXSetMutedCallAction","text":"CXSetMutedCallAction"},{"text":")","kind":"text"}],"externalID":"c:@M@PushwooshVoIP@objc(cs)PushwooshVoIPImplementation(im)provider:performSetMutedCallAction:","navigatorTitle":[{"text":"provider:performSetMutedCallAction:","kind":"identifier"}],"symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation"]]},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"CXProviderDelegate.provider(_:perform:)"},{"type":"text","text":"."}],"kind":"symbol","variants":[{"paths":["\/documentation\/pushwooshvoip\/pushwooshvoipimplementation\/provider(_:perform:)-79gr4"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshvoip\/pushwooshvoipimplementation\/provider(_:perform:)-79gr4"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation\/provider(_:perform:)-79gr4"},"references":{"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PushwooshVoIPImplementation":{"type":"topic","navigatorTitle":[{"text":"PushwooshVoIPImplementation","kind":"identifier"}],"abstract":[{"type":"text","text":"Orchestrates VoIP push notifications and CallKit integration for iOS applications."}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PushwooshVoIPImplementation","kind":"identifier"}],"title":"PushwooshVoIPImplementation","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation","url":"\/documentation\/pushwooshvoip\/pushwooshvoipimplementation","role":"symbol"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP":{"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP","kind":"symbol","abstract":[{"type":"text","text":"VoIP push notifications with native call UI for iOS applications."}],"title":"PushwooshVoIP","role":"collection","url":"\/documentation\/pushwooshvoip"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PushwooshVoIPImplementation/provider(_:perform:)-79gr4":{"url":"\/documentation\/pushwooshvoip\/pushwooshvoipimplementation\/provider(_:perform:)-79gr4","kind":"symbol","role":"symbol","type":"topic","title":"provider(_:perform:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"provider"},{"text":"(","kind":"text"},{"text":"CXProvider","preciseIdentifier":"c:objc(cs)CXProvider","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"perform","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CXSetMutedCallAction","text":"CXSetMutedCallAction"},{"kind":"text","text":")"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"provider:performSetMutedCallAction:"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation\/provider(_:perform:)-79gr4"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"provider:performSetMutedCallAction:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"provider:performSetMutedCallAction:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"provider:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CXProvider","text":"CXProvider"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"provider"},{"kind":"text","text":" "},{"kind":"identifier","text":"performSetMutedCallAction:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)CXSetMutedCallAction","text":"CXSetMutedCallAction","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"action","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation\/title","value":"PushwooshVoIPImplementation"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation\/fragments","value":[{"text":"PushwooshVoIPImplementation","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation~1provider(_:perform:)-79gr4\/title","value":"provider:performSetMutedCallAction:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation~1provider(_:perform:)-79gr4\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"provider:performSetMutedCallAction:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}