{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshvoip\/pushwooshvoipimplementation\/configurebackchannel"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshvoip\/pushwooshvoipimplementation\/configurebackchannel"]}],"metadata":{"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"configureBackchannel"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@PushwooshBridge@objc(pl)PWVoIPConfigureHandler","text":"PWVoIPConfigureHandler","kind":"typeIdentifier"}],"role":"symbol","roleHeading":"Type Property","navigatorTitle":[{"text":"configureBackchannel","kind":"identifier"}],"platforms":[{"beta":false,"deprecated":false,"name":"iOS","unavailable":false,"introducedAt":"14.0"}],"modules":[{"name":"PushwooshVoIP"}],"externalID":"c:@CM@PushwooshVoIP@objc(cs)PushwooshVoIPImplementation(cpy)configureBackchannel","symbolKind":"property","title":"configureBackchannel"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation\/configureBackchannel"},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"configureBackchannel"},{"text":": ","kind":"text"},{"text":"PWVoIPConfigureHandler","kind":"typeIdentifier","preciseIdentifier":"c:@M@PushwooshBridge@objc(pl)PWVoIPConfigureHandler"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation"]]},"sections":[],"abstract":[{"type":"text","text":"Singleton back-channel adapter used by "},{"code":"PWPushRuntime","type":"codeVoice"},{"text":" to trigger","type":"text"},{"type":"text","text":" "},{"text":"VoIP configuration without reflection.","type":"text"}],"kind":"symbol","references":{"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PushwooshVoIPImplementation":{"url":"\/documentation\/pushwooshvoip\/pushwooshvoipimplementation","abstract":[{"text":"Orchestrates VoIP push notifications and CallKit integration for iOS applications.","type":"text"}],"navigatorTitle":[{"text":"PushwooshVoIPImplementation","kind":"identifier"}],"title":"PushwooshVoIPImplementation","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PushwooshVoIPImplementation","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation","kind":"symbol"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PushwooshVoIPImplementation/configureBackchannel":{"identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation\/configureBackchannel","abstract":[{"text":"Singleton back-channel adapter used by ","type":"text"},{"code":"PWPushRuntime","type":"codeVoice"},{"type":"text","text":" to trigger"},{"text":" ","type":"text"},{"type":"text","text":"VoIP configuration without reflection."}],"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"configureBackchannel","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PWVoIPConfigureHandler","kind":"typeIdentifier","preciseIdentifier":"c:@M@PushwooshBridge@objc(pl)PWVoIPConfigureHandler"}],"kind":"symbol","title":"configureBackchannel","navigatorTitle":[{"kind":"identifier","text":"configureBackchannel"}],"url":"\/documentation\/pushwooshvoip\/pushwooshvoipimplementation\/configurebackchannel","type":"topic"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP":{"identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP","kind":"symbol","title":"PushwooshVoIP","abstract":[{"type":"text","text":"VoIP push notifications with native call UI for iOS applications."}],"type":"topic","url":"\/documentation\/pushwooshvoip","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"op":"replace","path":"\/metadata\/title","value":"configureBackchannel"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"configureBackchannel","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":", "},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Qo@M@PushwooshBridge@objc(pl)PWVoIPConfigureHandler","text":"id<PWVoIPConfigureHandler>","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"configureBackchannel","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation\/title","value":"PushwooshVoIPImplementation","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation\/fragments","value":[{"kind":"identifier","text":"PushwooshVoIPImplementation"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation~1configureBackchannel\/title","op":"replace","value":"configureBackchannel"},{"value":[{"text":"configureBackchannel","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation~1configureBackchannel\/fragments"}]}]}