{"variants":[{"paths":["\/documentation\/pushwooshvoip\/pushwooshvoipimplementation\/configurevoip()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshvoip\/pushwooshvoipimplementation\/configurevoip()"]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation"]]},"metadata":{"role":"symbol","symbolKind":"method","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"configureVoIP","kind":"identifier"},{"text":"()","kind":"text"}],"title":"configureVoIP()","modules":[{"name":"PushwooshVoIP"}],"externalID":"c:@M@PushwooshVoIP@objc(cs)PushwooshVoIPImplementation(cm)configureVoIP","platforms":[{"unavailable":false,"beta":false,"name":"iOS","deprecated":false,"introducedAt":"14.0"}],"navigatorTitle":[{"text":"configureVoIP","kind":"identifier"}],"roleHeading":"Type Method"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"configureVoIP","kind":"identifier"},{"kind":"text","text":"()"}],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation\/configureVoIP()","interfaceLanguage":"swift"},"references":{"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PushwooshVoIPImplementation":{"navigatorTitle":[{"kind":"identifier","text":"PushwooshVoIPImplementation"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation","abstract":[{"text":"Orchestrates VoIP push notifications and CallKit integration for iOS applications.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PushwooshVoIPImplementation","kind":"identifier"}],"role":"symbol","title":"PushwooshVoIPImplementation","kind":"symbol","type":"topic","url":"\/documentation\/pushwooshvoip\/pushwooshvoipimplementation"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PushwooshVoIPImplementation/configureVoIP()":{"abstract":[],"url":"\/documentation\/pushwooshvoip\/pushwooshvoipimplementation\/configurevoip()","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"configureVoIP","kind":"identifier"},{"text":"()","kind":"text"}],"title":"configureVoIP()","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation\/configureVoIP()","kind":"symbol","navigatorTitle":[{"text":"configureVoIP","kind":"identifier"}],"type":"topic"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP":{"url":"\/documentation\/pushwooshvoip","type":"topic","title":"PushwooshVoIP","role":"collection","abstract":[{"type":"text","text":"VoIP push notifications with native call UI for iOS applications."}],"identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"configureVoIP","op":"replace","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"text":"configureVoIP","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"configureVoIP","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"PushwooshVoIPImplementation","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation\/title"},{"value":[{"kind":"identifier","text":"PushwooshVoIPImplementation"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation\/fragments"},{"value":"configureVoIP","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation~1configureVoIP()\/title"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"configureVoIP","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation~1configureVoIP()\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}