{"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation\/provider(_:didDeactivate:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/pushwooshvoip\/pushwooshvoipimplementation\/provider(_:diddeactivate:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pushwooshvoip\/pushwooshvoipimplementation\/provider(_:diddeactivate:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"externalID":"c:@M@PushwooshVoIP@objc(cs)PushwooshVoIPImplementation(im)provider:didDeactivateAudioSession:","title":"provider(_:didDeactivate:)","platforms":[{"introducedAt":"14.0","beta":false,"unavailable":false,"name":"iOS","deprecated":false}],"modules":[{"name":"PushwooshVoIP"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"provider","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CXProvider","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CXProvider"},{"kind":"text","text":", "},{"text":"didDeactivate","kind":"externalParam"},{"kind":"text","text":": "},{"text":"AVAudioSession","preciseIdentifier":"c:objc(cs)AVAudioSession","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"provider:didDeactivateAudioSession:"}],"role":"symbol","symbolKind":"method","roleHeading":"Instance Method"},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"provider","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"provider"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CXProvider","preciseIdentifier":"c:objc(cs)CXProvider"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didDeactivate"},{"kind":"text","text":" "},{"kind":"internalParam","text":"audioSession"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)AVAudioSession","text":"AVAudioSession","kind":"typeIdentifier"},{"kind":"text","text":")"}],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"abstract":[{"type":"text","text":"Inherited from "},{"code":"CXProviderDelegate.provider(_:didDeactivate:)","type":"codeVoice"},{"text":".","type":"text"}],"kind":"symbol","references":{"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PushwooshVoIPImplementation":{"abstract":[{"text":"Orchestrates VoIP push notifications and CallKit integration for iOS applications.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushwooshVoIPImplementation"}],"navigatorTitle":[{"text":"PushwooshVoIPImplementation","kind":"identifier"}],"title":"PushwooshVoIPImplementation","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation","kind":"symbol","type":"topic","url":"\/documentation\/pushwooshvoip\/pushwooshvoipimplementation"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PushwooshVoIPImplementation/provider(_:didDeactivate:)":{"abstract":[],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"provider"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)CXProvider","text":"CXProvider","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didDeactivate"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)AVAudioSession","kind":"typeIdentifier","text":"AVAudioSession"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"provider:didDeactivateAudioSession:"}],"title":"provider(_:didDeactivate:)","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation\/provider(_:didDeactivate:)","kind":"symbol","type":"topic","url":"\/documentation\/pushwooshvoip\/pushwooshvoipimplementation\/provider(_:diddeactivate:)"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP":{"abstract":[{"text":"VoIP push notifications with native call UI for iOS applications.","type":"text"}],"title":"PushwooshVoIP","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP","kind":"symbol","role":"collection","url":"\/documentation\/pushwooshvoip"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"provider:didDeactivateAudioSession:","op":"replace","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"provider:didDeactivateAudioSession:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"text":"provider:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)CXProvider","kind":"typeIdentifier","text":"CXProvider"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"provider"},{"text":" ","kind":"text"},{"text":"didDeactivateAudioSession:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AVAudioSession","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVAudioSession"},{"kind":"text","text":" *) "},{"text":"audioSession","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation\/title","value":"PushwooshVoIPImplementation"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation\/fragments","value":[{"kind":"identifier","text":"PushwooshVoIPImplementation"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation~1provider(_:didDeactivate:)\/title","value":"provider:didDeactivateAudioSession:"},{"value":[{"kind":"text","text":"- "},{"text":"provider:didDeactivateAudioSession:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation~1provider(_:didDeactivate:)\/fragments"}]}]}