{"abstract":[{"type":"text","text":"Inherited from "},{"code":"CXProviderDelegate.provider(_:perform:)","type":"codeVoice"},{"type":"text","text":"."}],"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation\/provider(_:perform:)-6b5ut","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation"]]},"metadata":{"title":"provider(_:perform:)","modules":[{"name":"PushwooshVoIP"}],"externalID":"c:@M@PushwooshVoIP@objc(cs)PushwooshVoIPImplementation(im)provider:performEndCallAction:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"provider"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)CXProvider","kind":"typeIdentifier","text":"CXProvider"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"perform"},{"kind":"text","text":": "},{"text":"CXEndCallAction","preciseIdentifier":"c:objc(cs)CXEndCallAction","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":[{"name":"iOS","introducedAt":"14.0","deprecated":false,"unavailable":false,"beta":false}],"roleHeading":"Instance Method","symbolKind":"method","navigatorTitle":[{"text":"provider:performEndCallAction:","kind":"identifier"}],"role":"symbol"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"provider","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"provider"},{"kind":"text","text":": "},{"text":"CXProvider","preciseIdentifier":"c:objc(cs)CXProvider","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"perform","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"action"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CXEndCallAction","text":"CXEndCallAction"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshvoip\/pushwooshvoipimplementation\/provider(_:perform:)-6b5ut"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshvoip\/pushwooshvoipimplementation\/provider(_:perform:)-6b5ut"]}],"references":{"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PushwooshVoIPImplementation/provider(_:perform:)-6b5ut":{"role":"symbol","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"provider"},{"text":"(","kind":"text"},{"text":"CXProvider","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CXProvider"},{"kind":"text","text":", "},{"text":"perform","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)CXEndCallAction","text":"CXEndCallAction","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation\/provider(_:perform:)-6b5ut","url":"\/documentation\/pushwooshvoip\/pushwooshvoipimplementation\/provider(_:perform:)-6b5ut","navigatorTitle":[{"text":"provider:performEndCallAction:","kind":"identifier"}],"title":"provider(_:perform:)"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP":{"url":"\/documentation\/pushwooshvoip","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP","role":"collection","type":"topic","title":"PushwooshVoIP","abstract":[{"text":"VoIP push notifications with native call UI for iOS applications.","type":"text"}],"kind":"symbol"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PushwooshVoIPImplementation":{"type":"topic","title":"PushwooshVoIPImplementation","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation","navigatorTitle":[{"kind":"identifier","text":"PushwooshVoIPImplementation"}],"url":"\/documentation\/pushwooshvoip\/pushwooshvoipimplementation","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PushwooshVoIPImplementation","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Orchestrates VoIP push notifications and CallKit integration for iOS applications.","type":"text"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"provider:performEndCallAction:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"provider:performEndCallAction:","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"provider:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CXProvider","preciseIdentifier":"c:objc(cs)CXProvider"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"provider"},{"kind":"text","text":" "},{"text":"performEndCallAction:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CXEndCallAction","preciseIdentifier":"c:objc(cs)CXEndCallAction","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"action"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation~1provider(_:perform:)-6b5ut\/title","value":"provider:performEndCallAction:","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"provider:performEndCallAction:"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation~1provider(_:perform:)-6b5ut\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation\/title","value":"PushwooshVoIPImplementation"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation\/fragments","op":"replace","value":[{"kind":"identifier","text":"PushwooshVoIPImplementation"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}