{"sections":[],"kind":"symbol","metadata":{"symbolKind":"method","title":"provider(_:perform:)","modules":[{"name":"PushwooshVoIP"}],"role":"symbol","externalID":"c:@M@PushwooshVoIP@objc(cs)PushwooshVoIPImplementation(im)provider:performSetHeldCallAction:","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"provider"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CXProvider","text":"CXProvider"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"perform"},{"text":": ","kind":"text"},{"text":"CXSetHeldCallAction","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CXSetHeldCallAction"},{"kind":"text","text":")"}],"platforms":[{"introducedAt":"14.0","name":"iOS","beta":false,"unavailable":false,"deprecated":false}],"navigatorTitle":[{"kind":"identifier","text":"provider:performSetHeldCallAction:"}]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"provider"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"provider"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CXProvider","preciseIdentifier":"c:objc(cs)CXProvider"},{"text":", ","kind":"text"},{"text":"perform","kind":"externalParam"},{"kind":"text","text":" "},{"text":"action","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CXSetHeldCallAction","text":"CXSetHeldCallAction"},{"kind":"text","text":")"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation\/provider(_:perform:)-8zhob"},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshvoip\/pushwooshvoipimplementation\/provider(_:perform:)-8zhob"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshvoip\/pushwooshvoipimplementation\/provider(_:perform:)-8zhob"]}],"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"CXProviderDelegate.provider(_:perform:)"},{"type":"text","text":"."}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation"]]},"references":{"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PushwooshVoIPImplementation/provider(_:perform:)-8zhob":{"navigatorTitle":[{"kind":"identifier","text":"provider:performSetHeldCallAction:"}],"title":"provider(_:perform:)","abstract":[],"role":"symbol","kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"provider","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)CXProvider","text":"CXProvider","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"perform"},{"kind":"text","text":": "},{"text":"CXSetHeldCallAction","preciseIdentifier":"c:objc(cs)CXSetHeldCallAction","kind":"typeIdentifier"},{"kind":"text","text":")"}],"url":"\/documentation\/pushwooshvoip\/pushwooshvoipimplementation\/provider(_:perform:)-8zhob","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation\/provider(_:perform:)-8zhob"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PushwooshVoIPImplementation":{"title":"PushwooshVoIPImplementation","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushwooshVoIPImplementation"}],"url":"\/documentation\/pushwooshvoip\/pushwooshvoipimplementation","role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation","navigatorTitle":[{"text":"PushwooshVoIPImplementation","kind":"identifier"}],"abstract":[{"text":"Orchestrates VoIP push notifications and CallKit integration for iOS applications.","type":"text"}],"type":"topic"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP":{"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP","url":"\/documentation\/pushwooshvoip","title":"PushwooshVoIP","abstract":[{"type":"text","text":"VoIP push notifications with native call UI for iOS applications."}],"kind":"symbol","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"provider:performSetHeldCallAction:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"provider:performSetHeldCallAction:","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"provider:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"CXProvider","preciseIdentifier":"c:objc(cs)CXProvider"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"provider"},{"kind":"text","text":" "},{"kind":"identifier","text":"performSetHeldCallAction:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)CXSetHeldCallAction","kind":"typeIdentifier","text":"CXSetHeldCallAction"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"action"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation~1provider(_:perform:)-8zhob\/title","value":"provider:performSetHeldCallAction:"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation~1provider(_:perform:)-8zhob\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"provider:performSetHeldCallAction:"}]},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation\/title","value":"PushwooshVoIPImplementation","op":"replace"},{"value":[{"kind":"identifier","text":"PushwooshVoIPImplementation"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}