{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation\/pushRegistry(_:didUpdate:for:)"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation"]]},"variants":[{"paths":["\/documentation\/pushwooshvoip\/pushwooshvoipimplementation\/pushregistry(_:didupdate:for:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pushwooshvoip\/pushwooshvoipimplementation\/pushregistry(_:didupdate:for:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"abstract":[{"type":"text","text":"Inherited from "},{"code":"PKPushRegistryDelegate.pushRegistry(_:didUpdate:for:)","type":"codeVoice"},{"type":"text","text":"."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pushRegistry","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"registry"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PKPushRegistry","text":"PKPushRegistry"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didUpdate"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"pushCredentials"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)PKPushCredentials","text":"PKPushCredentials","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"for","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"type","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"PKPushType","preciseIdentifier":"c:@T@PKPushType","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"modules":[{"name":"PushwooshVoIP"}],"navigatorTitle":[{"kind":"identifier","text":"pushRegistry:didUpdatePushCredentials:forType:"}],"roleHeading":"Instance Method","platforms":[{"deprecated":false,"name":"iOS","introducedAt":"14.0","beta":false,"unavailable":false}],"externalID":"c:@M@PushwooshVoIP@objc(cs)PushwooshVoIPImplementation(im)pushRegistry:didUpdatePushCredentials:forType:","symbolKind":"method","title":"pushRegistry(_:didUpdate:for:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pushRegistry"},{"text":"(","kind":"text"},{"text":"PKPushRegistry","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PKPushRegistry"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didUpdate"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)PKPushCredentials","text":"PKPushCredentials","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"text":"PKPushType","kind":"typeIdentifier","preciseIdentifier":"c:@T@PKPushType"},{"text":")","kind":"text"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PushwooshVoIPImplementation":{"identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PushwooshVoIPImplementation","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PushwooshVoIPImplementation"}],"abstract":[{"type":"text","text":"Orchestrates VoIP push notifications and CallKit integration for iOS applications."}],"role":"symbol","url":"\/documentation\/pushwooshvoip\/pushwooshvoipimplementation","title":"PushwooshVoIPImplementation"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PushwooshVoIPImplementation/pushRegistry(_:didUpdate:for:)":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"pushRegistry:didUpdatePushCredentials:forType:"}],"title":"pushRegistry(_:didUpdate:for:)","abstract":[],"identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation\/pushRegistry(_:didUpdate:for:)","url":"\/documentation\/pushwooshvoip\/pushwooshvoipimplementation\/pushregistry(_:didupdate:for:)","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"pushRegistry","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PKPushRegistry","preciseIdentifier":"c:objc(cs)PKPushRegistry"},{"text":", ","kind":"text"},{"text":"didUpdate","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"PKPushCredentials","preciseIdentifier":"c:objc(cs)PKPushCredentials"},{"text":", ","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@PKPushType","text":"PKPushType"},{"text":")","kind":"text"}]},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP":{"identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"VoIP push notifications with native call UI for iOS applications."}],"role":"collection","url":"\/documentation\/pushwooshvoip","title":"PushwooshVoIP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"pushRegistry:didUpdatePushCredentials:forType:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"pushRegistry:didUpdatePushCredentials:forType:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"pushRegistry:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PKPushRegistry","preciseIdentifier":"c:objc(cs)PKPushRegistry"},{"text":" *) ","kind":"text"},{"text":"registry","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"didUpdatePushCredentials:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"PKPushCredentials","preciseIdentifier":"c:objc(cs)PKPushCredentials","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"pushCredentials"},{"text":" ","kind":"text"},{"text":"forType:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"type"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"PushwooshVoIPImplementation","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation\/title","op":"replace"},{"value":[{"text":"PushwooshVoIPImplementation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation\/fragments"},{"value":"pushRegistry:didUpdatePushCredentials:forType:","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation~1pushRegistry(_:didUpdate:for:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation~1pushRegistry(_:didUpdate:for:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"pushRegistry:didUpdatePushCredentials:forType:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}