{"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"pushRegistry","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"PKPushRegistry","preciseIdentifier":"c:objc(cs)PKPushRegistry"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didInvalidatePushTokenFor"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@PKPushType","text":"PKPushType","kind":"typeIdentifier"},{"kind":"text","text":")"}],"platforms":[{"deprecated":false,"name":"iOS","introducedAt":"14.0","beta":false,"unavailable":false}],"symbolKind":"method","modules":[{"name":"PushwooshVoIP"}],"title":"pushRegistry(_:didInvalidatePushTokenFor:)","navigatorTitle":[{"kind":"identifier","text":"pushRegistry:didInvalidatePushTokenForType:"}],"roleHeading":"Instance Method","externalID":"c:@M@PushwooshVoIP@objc(cs)PushwooshVoIPImplementation(im)pushRegistry:didInvalidatePushTokenForType:"},"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation\/pushRegistry(_:didInvalidatePushTokenFor:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshvoip\/pushwooshvoipimplementation\/pushregistry(_:didinvalidatepushtokenfor:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshvoip\/pushwooshvoipimplementation\/pushregistry(_:didinvalidatepushtokenfor:)"]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pushRegistry"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"registry","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PKPushRegistry","text":"PKPushRegistry"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didInvalidatePushTokenFor"},{"text":" ","kind":"text"},{"text":"type","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"PKPushType","kind":"typeIdentifier","preciseIdentifier":"c:@T@PKPushType"},{"text":")","kind":"text"}]}]}],"kind":"symbol","abstract":[{"text":"Inherited from ","type":"text"},{"code":"PKPushRegistryDelegate.pushRegistry(_:didInvalidatePushTokenFor:)","type":"codeVoice"},{"type":"text","text":"."}],"references":{"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP":{"abstract":[{"text":"VoIP push notifications with native call UI for iOS applications.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP","role":"collection","type":"topic","title":"PushwooshVoIP","url":"\/documentation\/pushwooshvoip"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PushwooshVoIPImplementation":{"identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation","abstract":[{"text":"Orchestrates VoIP push notifications and CallKit integration for iOS applications.","type":"text"}],"title":"PushwooshVoIPImplementation","navigatorTitle":[{"kind":"identifier","text":"PushwooshVoIPImplementation"}],"type":"topic","kind":"symbol","url":"\/documentation\/pushwooshvoip\/pushwooshvoipimplementation","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PushwooshVoIPImplementation","kind":"identifier"}]},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PushwooshVoIPImplementation/pushRegistry(_:didInvalidatePushTokenFor:)":{"identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation\/pushRegistry(_:didInvalidatePushTokenFor:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"pushRegistry:didInvalidatePushTokenForType:"}],"type":"topic","url":"\/documentation\/pushwooshvoip\/pushwooshvoipimplementation\/pushregistry(_:didinvalidatepushtokenfor:)","title":"pushRegistry(_:didInvalidatePushTokenFor:)","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"pushRegistry","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PKPushRegistry","text":"PKPushRegistry"},{"text":", ","kind":"text"},{"text":"didInvalidatePushTokenFor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PKPushType","kind":"typeIdentifier","preciseIdentifier":"c:@T@PKPushType"},{"text":")","kind":"text"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"pushRegistry:didInvalidatePushTokenForType:"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"pushRegistry:didInvalidatePushTokenForType:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"text":"pushRegistry:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"PKPushRegistry","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PKPushRegistry"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"registry"},{"text":" ","kind":"text"},{"text":"didInvalidatePushTokenForType:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"type"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"PushwooshVoIPImplementation","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation\/fragments","value":[{"kind":"identifier","text":"PushwooshVoIPImplementation"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation~1pushRegistry(_:didInvalidatePushTokenFor:)\/title","value":"pushRegistry:didInvalidatePushTokenForType:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"pushRegistry:didInvalidatePushTokenForType:"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation~1pushRegistry(_:didInvalidatePushTokenFor:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}