{"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"pushRegistry","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)PKPushRegistry","kind":"typeIdentifier","text":"PKPushRegistry"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceiveIncomingPushWith"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PKPushPayload","text":"PKPushPayload"},{"text":", ","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@PKPushType","text":"PKPushType","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": () -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")"}],"title":"pushRegistry(_:didReceiveIncomingPushWith:for:completion:)","platforms":[{"deprecated":false,"unavailable":false,"name":"iOS","introducedAt":"14.0","beta":false}],"navigatorTitle":[{"text":"pushRegistry:didReceiveIncomingPushWithPayload:forType:withCompletionHandler:","kind":"identifier"}],"externalID":"c:@M@PushwooshVoIP@objc(cs)PushwooshVoIPImplementation(im)pushRegistry:didReceiveIncomingPushWithPayload:forType:withCompletionHandler:","modules":[{"name":"PushwooshVoIP"}],"role":"symbol","roleHeading":"Instance Method","symbolKind":"method"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pushRegistry"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"registry","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)PKPushRegistry","text":"PKPushRegistry","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"didReceiveIncomingPushWith","kind":"externalParam"},{"kind":"text","text":" "},{"text":"payload","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PKPushPayload","text":"PKPushPayload"},{"text":", ","kind":"text"},{"text":"for","kind":"externalParam"},{"kind":"text","text":" "},{"text":"type","kind":"internalParam"},{"kind":"text","text":": "},{"text":"PKPushType","kind":"typeIdentifier","preciseIdentifier":"c:@T@PKPushType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" () -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation\/pushRegistry(_:didReceiveIncomingPushWith:for:completion:)"},"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"PKPushRegistryDelegate.pushRegistry(_:didReceiveIncomingPushWith:for:completion:)"},{"text":".","type":"text"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshvoip\/pushwooshvoipimplementation\/pushregistry(_:didreceiveincomingpushwith:for:completion:)"]},{"paths":["\/documentation\/pushwooshvoip\/pushwooshvoipimplementation\/pushregistry(_:didreceiveincomingpushwith:for:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP":{"abstract":[{"type":"text","text":"VoIP push notifications with native call UI for iOS applications."}],"title":"PushwooshVoIP","url":"\/documentation\/pushwooshvoip","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP","role":"collection","type":"topic","kind":"symbol"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PushwooshVoIPImplementation":{"title":"PushwooshVoIPImplementation","abstract":[{"text":"Orchestrates VoIP push notifications and CallKit integration for iOS applications.","type":"text"}],"url":"\/documentation\/pushwooshvoip\/pushwooshvoipimplementation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushwooshVoIPImplementation"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PushwooshVoIPImplementation"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PushwooshVoIPImplementation/pushRegistry(_:didReceiveIncomingPushWith:for:completion:)":{"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pushRegistry"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)PKPushRegistry","text":"PKPushRegistry","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didReceiveIncomingPushWith"},{"kind":"text","text":": "},{"text":"PKPushPayload","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PKPushPayload"},{"kind":"text","text":", "},{"text":"for","kind":"externalParam"},{"kind":"text","text":": "},{"text":"PKPushType","kind":"typeIdentifier","preciseIdentifier":"c:@T@PKPushType"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": () -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"pushRegistry:didReceiveIncomingPushWithPayload:forType:withCompletionHandler:","kind":"identifier"}],"abstract":[],"kind":"symbol","title":"pushRegistry(_:didReceiveIncomingPushWith:for:completion:)","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation\/pushRegistry(_:didReceiveIncomingPushWith:for:completion:)","role":"symbol","url":"\/documentation\/pushwooshvoip\/pushwooshvoipimplementation\/pushregistry(_:didreceiveincomingpushwith:for:completion:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"pushRegistry:didReceiveIncomingPushWithPayload:forType:withCompletionHandler:","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"pushRegistry:didReceiveIncomingPushWithPayload:forType:withCompletionHandler:","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"pushRegistry:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PKPushRegistry","text":"PKPushRegistry"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"registry"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didReceiveIncomingPushWithPayload:"},{"text":"(","kind":"text"},{"text":"PKPushPayload","preciseIdentifier":"c:objc(cs)PKPushPayload","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"payload","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"forType:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"type","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"withCompletionHandler:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":" (^"},{"text":")()) ","kind":"text"},{"kind":"internalParam","text":"completion"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation\/title","value":"PushwooshVoIPImplementation","op":"replace"},{"op":"replace","value":[{"text":"PushwooshVoIPImplementation","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation\/fragments"},{"value":"pushRegistry:didReceiveIncomingPushWithPayload:forType:withCompletionHandler:","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation~1pushRegistry(_:didReceiveIncomingPushWith:for:completion:)\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation~1pushRegistry(_:didReceiveIncomingPushWith:for:completion:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"pushRegistry:didReceiveIncomingPushWithPayload:forType:withCompletionHandler:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}