{"abstract":[{"text":"Sets the Pushwoosh VoIP Application Code.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation\/setPushwooshVoIPAppId(_:)-1ebdx"},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setPushwooshVoIPAppId"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"voipAppId","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}]}]}],"metadata":{"symbolKind":"method","externalID":"c:@M@PushwooshVoIP@objc(cs)PushwooshVoIPImplementation(cm)setPushwooshVoIPAppId:","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setPushwooshVoIPAppId","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"role":"symbol","navigatorTitle":[{"text":"setPushwooshVoIPAppId:","kind":"identifier"}],"roleHeading":"Type Method","modules":[{"name":"PushwooshVoIP"}],"title":"setPushwooshVoIPAppId(_:)","platforms":[{"deprecated":false,"beta":false,"name":"iOS","unavailable":false,"introducedAt":"14.0"}]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshvoip\/pushwooshvoipimplementation\/setpushwooshvoipappid(_:)-1ebdx"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshvoip\/pushwooshvoipimplementation\/setpushwooshvoipappid(_:)-1ebdx"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","references":{"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP":{"title":"PushwooshVoIP","type":"topic","role":"collection","url":"\/documentation\/pushwooshvoip","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP","kind":"symbol","abstract":[{"text":"VoIP push notifications with native call UI for iOS applications.","type":"text"}]},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PushwooshVoIPImplementation/setPushwooshVoIPAppId(_:)-1ebdx":{"identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation\/setPushwooshVoIPAppId(_:)-1ebdx","role":"symbol","abstract":[{"text":"Sets the Pushwoosh VoIP Application Code.","type":"text"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"setPushwooshVoIPAppId","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"kind":"symbol","title":"setPushwooshVoIPAppId(_:)","type":"topic","navigatorTitle":[{"text":"setPushwooshVoIPAppId:","kind":"identifier"}],"url":"\/documentation\/pushwooshvoip\/pushwooshvoipimplementation\/setpushwooshvoipappid(_:)-1ebdx"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PushwooshVoIPImplementation":{"title":"PushwooshVoIPImplementation","type":"topic","role":"symbol","url":"\/documentation\/pushwooshvoip\/pushwooshvoipimplementation","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushwooshVoIPImplementation"}],"navigatorTitle":[{"kind":"identifier","text":"PushwooshVoIPImplementation"}],"abstract":[{"text":"Orchestrates VoIP push notifications and CallKit integration for iOS applications.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Type Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"setPushwooshVoIPAppId:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"text":"setPushwooshVoIPAppId:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"setPushwooshVoIPAppId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"voipAppId","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"setPushwooshVoIPAppId:","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation~1setPushwooshVoIPAppId(_:)-1ebdx\/title","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"setPushwooshVoIPAppId:"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation~1setPushwooshVoIPAppId(_:)-1ebdx\/fragments","op":"replace"},{"op":"replace","value":"PushwooshVoIPImplementation","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation\/title"},{"op":"replace","value":[{"text":"PushwooshVoIPImplementation","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation\/fragments"}]}]}