{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setRingtone","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"ringtoneSound"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"platforms":["iOS"]}]}],"kind":"symbol","metadata":{"title":"setRingtone(_:)","navigatorTitle":[{"kind":"identifier","text":"setRingtone:"}],"platforms":[{"beta":false,"introducedAt":"14.0","deprecated":false,"name":"iOS","unavailable":false}],"symbolKind":"method","role":"symbol","externalID":"c:@M@PushwooshVoIP@objc(cs)PushwooshVoIPImplementation(cm)setRingtone:","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setRingtone"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?)"}],"modules":[{"name":"PushwooshVoIP"}],"roleHeading":"Type Method"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation\/setRingtone(_:)-6s7ow"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshvoip\/pushwooshvoipimplementation\/setringtone(_:)-6s7ow"]},{"paths":["\/documentation\/pushwooshvoip\/pushwooshvoipimplementation\/setringtone(_:)-6s7ow"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"Sets custom ringtone for incoming VoIP calls. Persisted across app launches."},{"type":"text","text":" "},{"type":"text","text":"Pass nil or empty string to reset to system default ringtone."}],"references":{"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PushwooshVoIPImplementation/setRingtone(_:)-6s7ow":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setRingtone"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?)"}],"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation\/setRingtone(_:)-6s7ow","url":"\/documentation\/pushwooshvoip\/pushwooshvoipimplementation\/setringtone(_:)-6s7ow","abstract":[{"type":"text","text":"Sets custom ringtone for incoming VoIP calls. Persisted across app launches."},{"text":" ","type":"text"},{"text":"Pass nil or empty string to reset to system default ringtone.","type":"text"}],"title":"setRingtone(_:)","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"setRingtone:","kind":"identifier"}]},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PushwooshVoIPImplementation":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PushwooshVoIPImplementation","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation","url":"\/documentation\/pushwooshvoip\/pushwooshvoipimplementation","abstract":[{"text":"Orchestrates VoIP push notifications and CallKit integration for iOS applications.","type":"text"}],"title":"PushwooshVoIPImplementation","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"PushwooshVoIPImplementation","kind":"identifier"}]},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP":{"role":"collection","type":"topic","title":"PushwooshVoIP","abstract":[{"text":"VoIP push notifications with native call UI for iOS applications.","type":"text"}],"kind":"symbol","url":"\/documentation\/pushwooshvoip","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"setRingtone:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"setRingtone:"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"setRingtone:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"ringtoneSound","kind":"internalParam"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation~1setRingtone(_:)-6s7ow\/title","op":"replace","value":"setRingtone:"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation~1setRingtone(_:)-6s7ow\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"setRingtone:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation\/title","value":"PushwooshVoIPImplementation"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation\/fragments","value":[{"kind":"identifier","text":"PushwooshVoIPImplementation"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}