{"abstract":[{"type":"text","text":"Sets the VoIP push token manually."}],"variants":[{"paths":["\/documentation\/pushwooshvoip\/pushwooshvoipimplementation\/setvoiptoken(_:)-3hp5q"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pushwooshvoip\/pushwooshvoipimplementation\/setvoiptoken(_:)-3hp5q"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation\/setVoIPToken(_:)-3hp5q","interfaceLanguage":"swift"},"metadata":{"platforms":[{"unavailable":false,"beta":false,"name":"iOS","introducedAt":"14.0","deprecated":false}],"role":"symbol","title":"setVoIPToken(_:)","symbolKind":"method","roleHeading":"Type Method","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"setVoIPToken","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"setVoIPToken:"}],"externalID":"c:@M@PushwooshVoIP@objc(cs)PushwooshVoIPImplementation(cm)setVoIPToken:","modules":[{"name":"PushwooshVoIP"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setVoIPToken"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"token","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation"]]},"references":{"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PushwooshVoIPImplementation":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation","title":"PushwooshVoIPImplementation","abstract":[{"type":"text","text":"Orchestrates VoIP push notifications and CallKit integration for iOS applications."}],"navigatorTitle":[{"text":"PushwooshVoIPImplementation","kind":"identifier"}],"url":"\/documentation\/pushwooshvoip\/pushwooshvoipimplementation","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PushwooshVoIPImplementation","kind":"identifier"}]},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PushwooshVoIPImplementation/setVoIPToken(_:)-3hp5q":{"kind":"symbol","role":"symbol","title":"setVoIPToken(_:)","navigatorTitle":[{"text":"setVoIPToken:","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setVoIPToken"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Sets the VoIP push token manually."}],"type":"topic","url":"\/documentation\/pushwooshvoip\/pushwooshvoipimplementation\/setvoiptoken(_:)-3hp5q","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation\/setVoIPToken(_:)-3hp5q"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP":{"abstract":[{"type":"text","text":"VoIP push notifications with native call UI for iOS applications."}],"url":"\/documentation\/pushwooshvoip","title":"PushwooshVoIP","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP","kind":"symbol","role":"collection","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"path":"\/metadata\/title","value":"setVoIPToken:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"setVoIPToken:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"setVoIPToken:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSData","text":"NSData"},{"text":" *) ","kind":"text"},{"text":"token","kind":"internalParam"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation\/title","value":"PushwooshVoIPImplementation","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"PushwooshVoIPImplementation"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation\/fragments"},{"op":"replace","value":"setVoIPToken:","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation~1setVoIPToken(_:)-3hp5q\/title"},{"value":[{"text":"+ ","kind":"text"},{"text":"setVoIPToken:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation~1setVoIPToken(_:)-3hp5q\/fragments","op":"replace"}]}]}