{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"applyCardSurface","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"card","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"style"},{"kind":"text","text":": "},{"text":"PushwooshInboxKitAttributes","preciseIdentifier":"s:17PushwooshInboxKit0abC10AttributesV","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitAttributes","kind":"typeIdentifier"},{"kind":"text","text":"."},{"preciseIdentifier":"s:17PushwooshInboxKit0abC10AttributesV5StyleV","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitAttributes\/Style-swift.struct","text":"Style","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"cornerRadius"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCell"]]},"sections":[],"metadata":{"externalID":"s:17PushwooshInboxKit0aB4CellC16applyCardSurface_5style12cornerRadiusySo6UIViewC_AA0abC10AttributesV5StyleV14CoreFoundation7CGFloatVtF","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"applyCardSurface","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"style"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:17PushwooshInboxKit0abC10AttributesV","text":"PushwooshInboxKitAttributes"},{"text":".","kind":"text"},{"kind":"typeIdentifier","text":"Style","preciseIdentifier":"s:17PushwooshInboxKit0abC10AttributesV5StyleV"},{"kind":"text","text":", "},{"text":"cornerRadius","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":")"}],"symbolKind":"method","roleHeading":"Instance Method","title":"applyCardSurface(_:style:cornerRadius:)","role":"symbol","modules":[{"name":"PushwooshInboxKit"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCell\/applyCardSurface(_:style:cornerRadius:)"},"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshinboxkit\/pushwooshinboxcell\/applycardsurface(_:style:cornerradius:)"]}],"abstract":[{"text":"Applies the card’s background surface honoring ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitAttributes\/Style-swift.struct\/isLiquidGlass","isActive":true},{"type":"text","text":":"},{"type":"text","text":" "},{"type":"text","text":"an Apple Liquid Glass effect on iOS 26+, with the solid "},{"type":"codeVoice","code":"backgroundColor"},{"type":"text","text":" as the fallback."},{"type":"text","text":" "},{"text":"Card subclasses call this from ","type":"text"},{"code":"apply(...)","type":"codeVoice"},{"type":"text","text":" instead of setting "},{"type":"codeVoice","code":"card.backgroundColor"},{"type":"text","text":" directly."},{"text":" ","type":"text"},{"text":"A neutral opaque backdrop is inserted behind the glass so it refracts a known colour","type":"text"},{"type":"text","text":" "},{"type":"text","text":"("},{"code":"backgroundColor","type":"codeVoice"},{"text":") instead of tinting from whatever image\/content the card holds; the glass","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"sits above it, behind the card’s content, and both are clipped by the card’s rounded corners."}],"references":{"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxKitAttributes":{"abstract":[{"text":"Configuration container for ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitViewController"},{"type":"text","text":"."}],"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxkitattributes","title":"PushwooshInboxKitAttributes","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"PushwooshInboxKitAttributes","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitAttributes","kind":"symbol","navigatorTitle":[{"text":"PushwooshInboxKitAttributes","kind":"identifier"}],"role":"symbol"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxKitAttributes/Style-swift.struct/isLiquidGlass":{"abstract":[{"type":"text","text":"When "},{"type":"codeVoice","code":"true"},{"type":"text","text":", cards render with an Apple Liquid Glass background on iOS 26+ (falling back"},{"type":"text","text":" "},{"text":"to the solid ","type":"text"},{"code":"backgroundColor","type":"codeVoice"},{"text":" on earlier OSes). Opt-in — defaults to ","type":"text"},{"type":"codeVoice","code":"false"},{"type":"text","text":" so existing"},{"text":" ","type":"text"},{"text":"apps keep their current card surfaces unchanged.","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitAttributes\/Style-swift.struct\/isLiquidGlass","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxkitattributes\/style-swift.struct\/isliquidglass","title":"isLiquidGlass","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isLiquidGlass"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxKitViewController":{"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxkitviewcontroller","navigatorTitle":[{"text":"PushwooshInboxKitViewController","kind":"identifier"}],"abstract":[{"text":"Modern UIKit inbox controller backed by ","type":"text"},{"type":"codeVoice","code":"PWInboxService"},{"text":".","type":"text"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitViewController","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PushwooshInboxKitViewController"}],"type":"topic","title":"PushwooshInboxKitViewController"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit":{"kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit","role":"collection","type":"topic","url":"\/documentation\/pushwooshinboxkit","title":"PushwooshInboxKit","abstract":[{"type":"text","text":"Modern UIKit inbox UI powered by Pushwoosh."}]},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxKitAttributes/Style-swift.struct":{"abstract":[{"type":"text","text":"Visual style applied to the controller chrome and the default cell."}],"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxkitattributes\/style-swift.struct","title":"PushwooshInboxKitAttributes.Style","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"Style","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitAttributes\/Style-swift.struct","kind":"symbol","navigatorTitle":[{"text":"Style","kind":"identifier"}],"role":"symbol"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxKitAttributes/cells":{"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxkitattributes\/cells","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitAttributes\/cells","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cells"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"PushwooshInboxCell","preciseIdentifier":"c:@M@PushwooshInboxKit@objc(cs)PushwooshInboxCell"},{"text":".Type]","kind":"text"}],"role":"symbol","abstract":[{"type":"text","text":"Mapping of cell-kind identifiers to cell classes."}],"title":"cells","type":"topic","kind":"symbol"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxCell":{"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxcell","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCell","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PushwooshInboxCell","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PushwooshInboxCell"}],"role":"symbol","abstract":[{"type":"text","text":"Default inbox table-view cell. Subclass this type and register it under a"},{"text":" ","type":"text"},{"type":"text","text":"custom kind via "},{"type":"reference","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitAttributes\/cells","isActive":true},{"text":" to ship bespoke","type":"text"},{"type":"text","text":" "},{"text":"layouts.","type":"text"}],"kind":"symbol","title":"PushwooshInboxCell","type":"topic"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxCell/applyCardSurface(_:style:cornerRadius:)":{"kind":"symbol","abstract":[{"text":"Applies the card’s background surface honoring ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitAttributes\/Style-swift.struct\/isLiquidGlass","type":"reference"},{"type":"text","text":":"},{"type":"text","text":" "},{"text":"an Apple Liquid Glass effect on iOS 26+, with the solid ","type":"text"},{"code":"backgroundColor","type":"codeVoice"},{"text":" as the fallback.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Card subclasses call this from "},{"type":"codeVoice","code":"apply(...)"},{"type":"text","text":" instead of setting "},{"code":"card.backgroundColor","type":"codeVoice"},{"text":" directly.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"A neutral opaque backdrop is inserted behind the glass so it refracts a known colour"},{"type":"text","text":" "},{"type":"text","text":"("},{"type":"codeVoice","code":"backgroundColor"},{"type":"text","text":") instead of tinting from whatever image\/content the card holds; the glass"},{"type":"text","text":" "},{"text":"sits above it, behind the card’s content, and both are clipped by the card’s rounded corners.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCell\/applyCardSurface(_:style:cornerRadius:)","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxcell\/applycardsurface(_:style:cornerradius:)","title":"applyCardSurface(_:style:cornerRadius:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"applyCardSurface"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"style"},{"kind":"text","text":": "},{"preciseIdentifier":"s:17PushwooshInboxKit0abC10AttributesV","text":"PushwooshInboxKitAttributes","kind":"typeIdentifier"},{"kind":"text","text":"."},{"text":"Style","preciseIdentifier":"s:17PushwooshInboxKit0abC10AttributesV5StyleV","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cornerRadius"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"text":")","kind":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"PushwooshInboxKitViewController","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxKitViewController\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxKitViewController\/fragments","value":[{"kind":"identifier","text":"PushwooshInboxKitViewController"}],"op":"replace"},{"value":"PushwooshInboxCell","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxCell\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxCell\/fragments","value":[{"text":"PushwooshInboxCell","kind":"identifier"}],"op":"replace"}]}]}