{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshinboxkit\/pushwooshinboxcell\/applybuttons(_:style:traits:)"]}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCell"]]},"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCell\/applyButtons(_:style:traits:)","interfaceLanguage":"swift"},"metadata":{"title":"applyButtons(_:style:traits:)","symbolKind":"method","role":"symbol","modules":[{"name":"PushwooshInboxKit"}],"roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"applyButtons","kind":"identifier"},{"text":"([","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:17PushwooshInboxKit0aB6ButtonV","text":"PushwooshInboxButton"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"style"},{"text":": ","kind":"text"},{"text":"PushwooshInboxKitAttributes","kind":"typeIdentifier","preciseIdentifier":"s:17PushwooshInboxKit0abC10AttributesV"},{"text":".","kind":"text"},{"text":"Style","kind":"typeIdentifier","preciseIdentifier":"s:17PushwooshInboxKit0abC10AttributesV5StyleV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"traits"},{"text":": ","kind":"text"},{"text":"UITraitCollection","preciseIdentifier":"c:objc(cs)UITraitCollection","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"externalID":"s:17PushwooshInboxKit0aB4CellC12applyButtons_5style6traitsySayAA0aB6ButtonVG_AA0abC10AttributesV5StyleVSo17UITraitCollectionCSgtF"},"abstract":[{"type":"text","text":"Renders an array of inline CTA buttons into "},{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCell\/buttonsStack","type":"reference","isActive":true},{"text":" using the","type":"text"},{"type":"text","text":" "},{"text":"supplied style. Empties the stack when ","type":"text"},{"code":"buttons","type":"codeVoice"},{"text":" is empty. The cell’s","type":"text"},{"type":"text","text":" "},{"code":"onInlineButtonTap","type":"codeVoice"},{"type":"text","text":" is invoked with the tapped button."}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"applyButtons","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"buttons","kind":"internalParam"},{"kind":"text","text":": ["},{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxButton","kind":"typeIdentifier","preciseIdentifier":"s:17PushwooshInboxKit0aB6ButtonV","text":"PushwooshInboxButton"},{"kind":"text","text":"], "},{"text":"style","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PushwooshInboxKitAttributes","kind":"typeIdentifier","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitAttributes","preciseIdentifier":"s:17PushwooshInboxKit0abC10AttributesV"},{"text":".","kind":"text"},{"text":"Style","kind":"typeIdentifier","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitAttributes\/Style-swift.struct","preciseIdentifier":"s:17PushwooshInboxKit0abC10AttributesV5StyleV"},{"kind":"text","text":", "},{"text":"traits","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITraitCollection","text":"UITraitCollection"},{"text":"? = nil)","kind":"text"}]}]},{"content":[{"level":2,"type":"heading","text":"Discussion","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Each button is sized to a fixed 34pt height (Apple Mail \/ Wallet"},{"type":"text","text":" "},{"text":"convention) and the stack itself is constrained to that height so it","type":"text"},{"type":"text","text":" "},{"type":"text","text":"never stretches when the cell’s vertical chain has slack."}]}],"kind":"content"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxCell/buttonsStack":{"kind":"symbol","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxcell\/buttonsstack","title":"buttonsStack","type":"topic","role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCell\/buttonsStack","abstract":[{"text":"Horizontal stack that hosts inline CTA buttons (","type":"text"},{"code":"PushwooshInboxButton","type":"codeVoice"},{"type":"text","text":")."},{"text":" ","type":"text"},{"type":"text","text":"Subclasses are expected to add this view to their own card chrome —"},{"type":"text","text":" "},{"code":"applyButtons(_:style:onTap:)","type":"codeVoice"},{"type":"text","text":" populates it."}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"buttonsStack"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIStackView","text":"UIStackView"}]},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxKitAttributes/Style-swift.struct":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Style"}],"title":"PushwooshInboxKitAttributes.Style","type":"topic","abstract":[{"type":"text","text":"Visual style applied to the controller chrome and the default cell."}],"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitAttributes\/Style-swift.struct","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxkitattributes\/style-swift.struct","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Style"}]},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxKitViewController":{"type":"topic","abstract":[{"type":"text","text":"Modern UIKit inbox controller backed by "},{"type":"codeVoice","code":"PWInboxService"},{"type":"text","text":"."}],"kind":"symbol","role":"symbol","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxkitviewcontroller","navigatorTitle":[{"kind":"identifier","text":"PushwooshInboxKitViewController"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushwooshInboxKitViewController"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitViewController","title":"PushwooshInboxKitViewController"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxCell":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCell","title":"PushwooshInboxCell","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PushwooshInboxCell","kind":"identifier"}],"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxcell","navigatorTitle":[{"text":"PushwooshInboxCell","kind":"identifier"}],"abstract":[{"type":"text","text":"Default inbox table-view cell. Subclass this type and register it under a"},{"type":"text","text":" "},{"text":"custom kind via ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitAttributes\/cells"},{"type":"text","text":" to ship bespoke"},{"type":"text","text":" "},{"type":"text","text":"layouts."}],"kind":"symbol","type":"topic"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit":{"title":"PushwooshInboxKit","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit","type":"topic","abstract":[{"type":"text","text":"Modern UIKit inbox UI powered by Pushwoosh."}],"kind":"symbol","role":"collection","url":"\/documentation\/pushwooshinboxkit"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxKitAttributes/cells":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitAttributes\/cells","title":"cells","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"cells"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:@M@PushwooshInboxKit@objc(cs)PushwooshInboxCell","kind":"typeIdentifier","text":"PushwooshInboxCell"},{"text":".Type]","kind":"text"}],"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxkitattributes\/cells","abstract":[{"type":"text","text":"Mapping of cell-kind identifiers to cell classes."}],"kind":"symbol","type":"topic"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxKitAttributes":{"navigatorTitle":[{"kind":"identifier","text":"PushwooshInboxKitAttributes"}],"role":"symbol","title":"PushwooshInboxKitAttributes","kind":"symbol","abstract":[{"type":"text","text":"Configuration container for "},{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitViewController","type":"reference","isActive":true},{"text":".","type":"text"}],"type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"PushwooshInboxKitAttributes","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitAttributes","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxkitattributes"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxCell/applyButtons(_:style:traits:)":{"kind":"symbol","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxcell\/applybuttons(_:style:traits:)","title":"applyButtons(_:style:traits:)","type":"topic","role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCell\/applyButtons(_:style:traits:)","abstract":[{"type":"text","text":"Renders an array of inline CTA buttons into "},{"isActive":true,"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCell\/buttonsStack","type":"reference"},{"type":"text","text":" using the"},{"type":"text","text":" "},{"text":"supplied style. Empties the stack when ","type":"text"},{"type":"codeVoice","code":"buttons"},{"text":" is empty. The cell’s","type":"text"},{"type":"text","text":" "},{"type":"codeVoice","code":"onInlineButtonTap"},{"text":" is invoked with the tapped button.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"applyButtons","kind":"identifier"},{"kind":"text","text":"(["},{"preciseIdentifier":"s:17PushwooshInboxKit0aB6ButtonV","text":"PushwooshInboxButton","kind":"typeIdentifier"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"style"},{"kind":"text","text":": "},{"text":"PushwooshInboxKitAttributes","kind":"typeIdentifier","preciseIdentifier":"s:17PushwooshInboxKit0abC10AttributesV"},{"kind":"text","text":"."},{"text":"Style","kind":"typeIdentifier","preciseIdentifier":"s:17PushwooshInboxKit0abC10AttributesV5StyleV"},{"text":", ","kind":"text"},{"text":"traits","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITraitCollection","text":"UITraitCollection"},{"text":"?)","kind":"text"}]},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxButton":{"role":"symbol","navigatorTitle":[{"text":"PushwooshInboxButton","kind":"identifier"}],"title":"PushwooshInboxButton","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxbutton","abstract":[{"type":"text","text":"A single inline call-to-action button rendered inside an inbox cell."}],"kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxButton","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PushwooshInboxButton"}],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxKitViewController\/title","value":"PushwooshInboxKitViewController","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxKitViewController\/fragments","value":[{"text":"PushwooshInboxKitViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxCell\/title","value":"PushwooshInboxCell","op":"replace"},{"value":[{"text":"PushwooshInboxCell","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxCell\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}