{"variants":[{"paths":["\/documentation\/pushwooshinboxkit\/pushwooshinboxcell\/apply(message:attributes:)"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"apply"},{"text":"(","kind":"text"},{"text":"message","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)PWInboxMessageProtocol","text":"PWInboxMessageProtocol"},{"text":", ","kind":"text"},{"text":"attributes","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:17PushwooshInboxKit0abC10AttributesV","text":"PushwooshInboxKitAttributes","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitAttributes","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","abstract":[{"text":"Configures the cell for the given message and attributes. Subclasses may","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"override to render bespoke layouts; call "},{"type":"codeVoice","code":"super.apply(...)"},{"type":"text","text":" to inherit"},{"type":"text","text":" "},{"type":"text","text":"dark-mode reactivity."}],"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCell\/apply(message:attributes:)","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"apply"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"message"},{"text":": ","kind":"text"},{"text":"PWInboxMessageProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)PWInboxMessageProtocol"},{"kind":"text","text":", "},{"text":"attributes","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"PushwooshInboxKitAttributes","preciseIdentifier":"s:17PushwooshInboxKit0abC10AttributesV"},{"text":")","kind":"text"}],"role":"symbol","externalID":"s:17PushwooshInboxKit0aB4CellC5apply7message10attributesySo22PWInboxMessageProtocol_p_AA0abC10AttributesVtF","modules":[{"name":"PushwooshInboxKit"}],"title":"apply(message:attributes:)","symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCell"]]},"references":{"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxKitAttributes/cells":{"title":"cells","abstract":[{"type":"text","text":"Mapping of cell-kind identifiers to cell classes."}],"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxkitattributes\/cells","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cells","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"text":"PushwooshInboxCell","kind":"typeIdentifier","preciseIdentifier":"c:@M@PushwooshInboxKit@objc(cs)PushwooshInboxCell"},{"text":".Type]","kind":"text"}],"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitAttributes\/cells","kind":"symbol","role":"symbol"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit":{"role":"collection","abstract":[{"text":"Modern UIKit inbox UI powered by Pushwoosh.","type":"text"}],"title":"PushwooshInboxKit","type":"topic","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit","url":"\/documentation\/pushwooshinboxkit"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxCell/apply(message:attributes:)":{"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxcell\/apply(message:attributes:)","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"apply"},{"text":"(","kind":"text"},{"text":"message","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"PWInboxMessageProtocol","preciseIdentifier":"c:objc(pl)PWInboxMessageProtocol"},{"text":", ","kind":"text"},{"text":"attributes","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PushwooshInboxKitAttributes","preciseIdentifier":"s:17PushwooshInboxKit0abC10AttributesV"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCell\/apply(message:attributes:)","abstract":[{"text":"Configures the cell for the given message and attributes. Subclasses may","type":"text"},{"type":"text","text":" "},{"type":"text","text":"override to render bespoke layouts; call "},{"type":"codeVoice","code":"super.apply(...)"},{"text":" to inherit","type":"text"},{"text":" ","type":"text"},{"text":"dark-mode reactivity.","type":"text"}],"role":"symbol","title":"apply(message:attributes:)"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxKitAttributes":{"abstract":[{"text":"Configuration container for ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitViewController","type":"reference"},{"type":"text","text":"."}],"navigatorTitle":[{"text":"PushwooshInboxKitAttributes","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushwooshInboxKitAttributes"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitAttributes","role":"symbol","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxkitattributes","title":"PushwooshInboxKitAttributes","kind":"symbol","type":"topic"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxCell":{"role":"symbol","title":"PushwooshInboxCell","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PushwooshInboxCell","kind":"identifier"}],"navigatorTitle":[{"text":"PushwooshInboxCell","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Default inbox table-view cell. Subclass this type and register it under a"},{"text":" ","type":"text"},{"type":"text","text":"custom kind via "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitAttributes\/cells"},{"text":" to ship bespoke","type":"text"},{"type":"text","text":" "},{"type":"text","text":"layouts."}],"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxcell","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCell"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxKitViewController":{"navigatorTitle":[{"kind":"identifier","text":"PushwooshInboxKitViewController"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitViewController","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushwooshInboxKitViewController"}],"abstract":[{"text":"Modern UIKit inbox controller backed by ","type":"text"},{"code":"PWInboxService","type":"codeVoice"},{"text":".","type":"text"}],"role":"symbol","title":"PushwooshInboxKitViewController","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxkitviewcontroller","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxCell\/title","value":"PushwooshInboxCell"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxCell\/fragments","value":[{"kind":"identifier","text":"PushwooshInboxCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxKitViewController\/title","value":"PushwooshInboxKitViewController"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxKitViewController\/fragments","value":[{"kind":"identifier","text":"PushwooshInboxKitViewController"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}