{"sections":[],"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCell\/traitCollectionDidChange(_:)","interfaceLanguage":"swift"},"metadata":{"role":"symbol","roleHeading":"Instance Method","symbolKind":"method","title":"traitCollectionDidChange(_:)","modules":[{"name":"PushwooshInboxKit"}],"externalID":"c:@M@PushwooshInboxKit@objc(cs)PushwooshInboxCell(im)traitCollectionDidChange:","navigatorTitle":[{"kind":"identifier","text":"traitCollectionDidChange:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"traitCollectionDidChange","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UITraitCollection","kind":"typeIdentifier","text":"UITraitCollection"},{"kind":"text","text":"?)"}]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"override","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"traitCollectionDidChange","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"previousTraitCollection"},{"kind":"text","text":": "},{"text":"UITraitCollection","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITraitCollection"},{"text":"?)","kind":"text"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/pushwooshinboxkit\/pushwooshinboxcell\/traitcollectiondidchange(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshinboxkit\/pushwooshinboxcell\/traitcollectiondidchange(_:)"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCell"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxCell":{"abstract":[{"type":"text","text":"Default inbox table-view cell. Subclass this type and register it under a"},{"text":" ","type":"text"},{"text":"custom kind via ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitAttributes\/cells"},{"type":"text","text":" to ship bespoke"},{"type":"text","text":" "},{"type":"text","text":"layouts."}],"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCell","role":"symbol","navigatorTitle":[{"text":"PushwooshInboxCell","kind":"identifier"}],"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxcell","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PushwooshInboxCell","kind":"identifier"}],"kind":"symbol","title":"PushwooshInboxCell"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxCell/traitCollectionDidChange(_:)":{"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"traitCollectionDidChange","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UITraitCollection","kind":"typeIdentifier","text":"UITraitCollection"},{"text":"?)","kind":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCell\/traitCollectionDidChange(_:)","title":"traitCollectionDidChange(_:)","role":"symbol","abstract":[],"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxcell\/traitcollectiondidchange(_:)","navigatorTitle":[{"text":"traitCollectionDidChange:","kind":"identifier"}],"kind":"symbol"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit":{"url":"\/documentation\/pushwooshinboxkit","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit","abstract":[{"type":"text","text":"Modern UIKit inbox UI powered by Pushwoosh."}],"kind":"symbol","role":"collection","title":"PushwooshInboxKit"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxKitAttributes/cells":{"abstract":[{"type":"text","text":"Mapping of cell-kind identifiers to cell classes."}],"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitAttributes\/cells","role":"symbol","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxkitattributes\/cells","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"cells"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"text":"PushwooshInboxCell","preciseIdentifier":"c:@M@PushwooshInboxKit@objc(cs)PushwooshInboxCell","kind":"typeIdentifier"},{"kind":"text","text":".Type]"}],"kind":"symbol","title":"cells"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"traitCollectionDidChange:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"traitCollectionDidChange:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"traitCollectionDidChange:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UITraitCollection","text":"UITraitCollection","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"previousTraitCollection"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxCell\/title","op":"replace","value":"PushwooshInboxCell"},{"value":[{"kind":"identifier","text":"PushwooshInboxCell"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxCell\/fragments","op":"replace"},{"value":"traitCollectionDidChange:","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxCell~1traitCollectionDidChange(_:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"traitCollectionDidChange:"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxCell~1traitCollectionDidChange(_:)\/fragments"}]}]}