{"seeAlsoSections":[{"generated":true,"identifiers":["doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/configureRichMediaWith(position:presentAnimation:dismissAnimation:)"],"title":"Rich Media Configuration"}],"metadata":{"title":"configureCloseButton(_:)","roleHeading":"Type Method","modules":[{"name":"PushwooshTVOS"}],"externalID":"c:@M@PushwooshTVOS@objc(cs)PushwooshTVOSImplementation(cm)configureCloseButton:","role":"symbol","platforms":[{"name":"tvOS","unavailable":false,"beta":false,"deprecated":false,"introducedAt":"11.0"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"configureCloseButton","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"configureCloseButton:"}],"symbolKind":"method"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS"],["doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/configureCloseButton(_:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshtvos\/pushwooshtvosimplementation\/configureclosebutton(_:)"]},{"paths":["\/documentation\/pushwooshtvos\/pushwooshtvosimplementation\/configureclosebutton(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"configureCloseButton","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"show"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["tvOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"show","content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"code":"true","type":"codeVoice"},{"text":" to show the Close button (default), ","type":"text"},{"type":"codeVoice","code":"false"},{"type":"text","text":" to hide it."}]}]}]},{"content":[{"type":"heading","anchor":"discussion","text":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"text":"By default, a Close button is shown at the bottom of rich media presentations,","type":"text"},{"type":"text","text":" "},{"text":"allowing users to dismiss the content. You can hide this button if you want","type":"text"},{"type":"text","text":" "},{"text":"rich media to only be dismissible through button actions within the content itself.","type":"text"}]},{"text":"Example","level":2,"anchor":"Example","type":"heading"},{"type":"codeListing","syntax":"swift","code":["\/\/ Hide the system Close button","Pushwoosh.TVoS.configureCloseButton(false)"]},{"style":"note","type":"aside","name":"Note","content":[{"inlineContent":[{"type":"text","text":"If you hide the Close button, ensure your rich media content includes a button with the "},{"code":"closeInApp()","type":"codeVoice"},{"type":"text","text":" action to allow users to dismiss it."}],"type":"paragraph"}]}],"kind":"content"}],"abstract":[{"text":"Controls whether the Close button is displayed on rich media content.","type":"text"}],"references":{"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PushwooshTVOSImplementation/configureCloseButton(_:)":{"title":"configureCloseButton(_:)","url":"\/documentation\/pushwooshtvos\/pushwooshtvosimplementation\/configureclosebutton(_:)","kind":"symbol","abstract":[{"text":"Controls whether the Close button is displayed on rich media content.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/configureCloseButton(_:)","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"configureCloseButton"},{"kind":"text","text":"("},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"configureCloseButton:"}],"role":"symbol"},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PushwooshTVOSImplementation/configureRichMediaWith(position:presentAnimation:dismissAnimation:)":{"title":"configureRichMediaWith(position:presentAnimation:dismissAnimation:)","url":"\/documentation\/pushwooshtvos\/pushwooshtvosimplementation\/configurerichmediawith(position:presentanimation:dismissanimation:)","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/configureRichMediaWith(position:presentAnimation:dismissAnimation:)","abstract":[{"text":"Configures rich media presentation, positioning, and dismissal animations for tvOS.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"configureRichMediaWith"},{"kind":"text","text":"("},{"text":"position","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@PushwooshBridge@E@PWTVOSRichMediaPosition","kind":"typeIdentifier","text":"PWTVOSRichMediaPosition"},{"kind":"text","text":", "},{"text":"presentAnimation","kind":"externalParam"},{"kind":"text","text":": "},{"text":"PWTVOSRichMediaPresentAnimation","kind":"typeIdentifier","preciseIdentifier":"c:@M@PushwooshBridge@E@PWTVOSRichMediaPresentAnimation"},{"text":", ","kind":"text"},{"text":"dismissAnimation","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PWTVOSRichMediaDismissAnimation","kind":"typeIdentifier","preciseIdentifier":"c:@M@PushwooshBridge@E@PWTVOSRichMediaDismissAnimation"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"configureRichMediaWithPosition:presentAnimation:dismissAnimation:"}],"role":"symbol"},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS":{"kind":"symbol","title":"PushwooshTVOS","identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS","abstract":[{"type":"text","text":"Push notifications and Rich Media for tvOS apps."}],"url":"\/documentation\/pushwooshtvos","type":"topic","role":"collection"},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PushwooshTVOSImplementation":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation","title":"PushwooshTVOSImplementation","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PushwooshTVOSImplementation"}],"url":"\/documentation\/pushwooshtvos\/pushwooshtvosimplementation","navigatorTitle":[{"kind":"identifier","text":"PushwooshTVOSImplementation"}],"role":"symbol","abstract":[{"type":"text","text":"Main implementation class for tvOS push notifications and Rich Media."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Type Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"configureCloseButton:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"text":"configureCloseButton:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"replace","value":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/configureRichMediaWith(position:presentAnimation:dismissAnimation:)"],"title":"Rich Media Configuration","generated":true}],"path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["tvOS"],"tokens":[{"text":"+ (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"configureCloseButton:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"show"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1configureCloseButton(_:)\/title","value":"configureCloseButton:"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1configureCloseButton(_:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"configureCloseButton:","kind":"identifier"}]},{"value":"configureRichMediaWithPosition:presentAnimation:dismissAnimation:","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1configureRichMediaWith(position:presentAnimation:dismissAnimation:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1configureRichMediaWith(position:presentAnimation:dismissAnimation:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"configureRichMediaWithPosition:presentAnimation:dismissAnimation:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation\/title","value":"PushwooshTVOSImplementation"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation\/fragments","op":"replace","value":[{"kind":"identifier","text":"PushwooshTVOSImplementation"}]}]}]}