{"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS"],["doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshtvos\/pushwooshtvosimplementation\/configurerichmediawith(position:presentanimation:dismissanimation:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshtvos\/pushwooshtvosimplementation\/configurerichmediawith(position:presentanimation:dismissanimation:)"]}],"seeAlsoSections":[{"title":"Rich Media Configuration","identifiers":["doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/configureCloseButton(_:)"],"generated":true}],"kind":"symbol","metadata":{"title":"configureRichMediaWith(position:presentAnimation:dismissAnimation:)","modules":[{"name":"PushwooshTVOS"}],"platforms":[{"name":"tvOS","deprecated":false,"introducedAt":"11.0","beta":false,"unavailable":false}],"roleHeading":"Type Method","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"configureRichMediaWithPosition:presentAnimation:dismissAnimation:"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"configureRichMediaWith","kind":"identifier"},{"text":"(","kind":"text"},{"text":"position","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PWTVOSRichMediaPosition","kind":"typeIdentifier","preciseIdentifier":"c:@M@PushwooshBridge@E@PWTVOSRichMediaPosition"},{"text":", ","kind":"text"},{"text":"presentAnimation","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PWTVOSRichMediaPresentAnimation","kind":"typeIdentifier","preciseIdentifier":"c:@M@PushwooshBridge@E@PWTVOSRichMediaPresentAnimation"},{"kind":"text","text":", "},{"text":"dismissAnimation","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@PushwooshBridge@E@PWTVOSRichMediaDismissAnimation","text":"PWTVOSRichMediaDismissAnimation"},{"kind":"text","text":")"}],"role":"symbol","externalID":"c:@M@PushwooshTVOS@objc(cs)PushwooshTVOSImplementation(cm)configureRichMediaWithPosition:presentAnimation:dismissAnimation:"},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"Configures rich media presentation, positioning, and dismissal animations for tvOS.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"configureRichMediaWith"},{"text":"(","kind":"text"},{"text":"position","kind":"externalParam"},{"kind":"text","text":": "},{"text":"PWTVOSRichMediaPosition","preciseIdentifier":"c:@M@PushwooshBridge@E@PWTVOSRichMediaPosition","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"presentAnimation","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@PushwooshBridge@E@PWTVOSRichMediaPresentAnimation","text":"PWTVOSRichMediaPresentAnimation"},{"text":", ","kind":"text"},{"text":"dismissAnimation","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PWTVOSRichMediaDismissAnimation","preciseIdentifier":"c:@M@PushwooshBridge@E@PWTVOSRichMediaDismissAnimation","kind":"typeIdentifier"},{"kind":"text","text":" = .none)"}],"platforms":["tvOS"],"languages":["swift"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The screen position where rich media content will be displayed. See ","type":"text"},{"code":"PWTVOSRichMediaPosition","type":"codeVoice"},{"text":" for available options.","type":"text"}]}],"name":"position"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The animation type to use when presenting rich media. See "},{"code":"PWTVOSRichMediaPresentAnimation","type":"codeVoice"},{"text":" for available options.","type":"text"}]}],"name":"presentAnimation"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The animation type to use when dismissing rich media. Defaults to "},{"code":".none","type":"codeVoice"},{"type":"text","text":". See "},{"code":"PWTVOSRichMediaDismissAnimation","type":"codeVoice"},{"type":"text","text":" for available options."}]}],"name":"dismissAnimation"}],"kind":"parameters"},{"kind":"content","content":[{"level":2,"type":"heading","text":"Discussion","anchor":"discussion"},{"inlineContent":[{"text":"This method allows you to customize how rich media content appears, where it’s positioned,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"and how it disappears on screen. You can choose from different animation directions,"},{"text":" ","type":"text"},{"type":"text","text":"screen positions, or disable animation entirely."}],"type":"paragraph"},{"type":"heading","level":2,"text":"Example","anchor":"Example"},{"syntax":"swift","code":["\/\/ Configure rich media to appear on the left, slide in from bottom and slide out to left","Pushwoosh.TVoS.configureRichMediaWith(","    position: .left,","    presentAnimation: .fromBottom,","    dismissAnimation: .toLeft",")"],"type":"codeListing"},{"name":"Note","style":"note","type":"aside","content":[{"inlineContent":[{"type":"text","text":"This configuration applies to all subsequent rich media presentations until changed."}],"type":"paragraph"}]}]}],"sections":[],"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/configureRichMediaWith(position:presentAnimation:dismissAnimation:)","interfaceLanguage":"swift"},"references":{"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PushwooshTVOSImplementation":{"abstract":[{"text":"Main implementation class for tvOS push notifications and Rich Media.","type":"text"}],"type":"topic","url":"\/documentation\/pushwooshtvos\/pushwooshtvosimplementation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushwooshTVOSImplementation"}],"kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation","navigatorTitle":[{"kind":"identifier","text":"PushwooshTVOSImplementation"}],"title":"PushwooshTVOSImplementation","role":"symbol"},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS":{"type":"topic","abstract":[{"text":"Push notifications and Rich Media for tvOS apps.","type":"text"}],"role":"collection","kind":"symbol","url":"\/documentation\/pushwooshtvos","identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS","title":"PushwooshTVOS"},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PushwooshTVOSImplementation/configureRichMediaWith(position:presentAnimation:dismissAnimation:)":{"type":"topic","abstract":[{"type":"text","text":"Configures rich media presentation, positioning, and dismissal animations for tvOS."}],"navigatorTitle":[{"text":"configureRichMediaWithPosition:presentAnimation:dismissAnimation:","kind":"identifier"}],"url":"\/documentation\/pushwooshtvos\/pushwooshtvosimplementation\/configurerichmediawith(position:presentanimation:dismissanimation:)","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/configureRichMediaWith(position:presentAnimation:dismissAnimation:)","title":"configureRichMediaWith(position:presentAnimation:dismissAnimation:)","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"configureRichMediaWith","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"position"},{"text":": ","kind":"text"},{"text":"PWTVOSRichMediaPosition","kind":"typeIdentifier","preciseIdentifier":"c:@M@PushwooshBridge@E@PWTVOSRichMediaPosition"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"presentAnimation"},{"text":": ","kind":"text"},{"text":"PWTVOSRichMediaPresentAnimation","kind":"typeIdentifier","preciseIdentifier":"c:@M@PushwooshBridge@E@PWTVOSRichMediaPresentAnimation"},{"kind":"text","text":", "},{"text":"dismissAnimation","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@PushwooshBridge@E@PWTVOSRichMediaDismissAnimation","text":"PWTVOSRichMediaDismissAnimation"},{"text":")","kind":"text"}]},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PushwooshTVOSImplementation/configureCloseButton(_:)":{"type":"topic","abstract":[{"text":"Controls whether the Close button is displayed on rich media content.","type":"text"}],"navigatorTitle":[{"text":"configureCloseButton:","kind":"identifier"}],"url":"\/documentation\/pushwooshtvos\/pushwooshtvosimplementation\/configureclosebutton(_:)","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/configureCloseButton(_:)","title":"configureCloseButton(_:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"configureCloseButton"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":")"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"configureRichMediaWithPosition:presentAnimation:dismissAnimation:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"text":"configureRichMediaWithPosition:presentAnimation:dismissAnimation:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"replace","value":[{"generated":true,"title":"Rich Media Configuration","identifiers":["doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/configureCloseButton(_:)"]}]},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["tvOS"],"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"configureRichMediaWithPosition:"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"PWTVOSRichMediaPosition","kind":"typeIdentifier","preciseIdentifier":"c:@M@PushwooshBridge@E@PWTVOSRichMediaPosition"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"position"},{"text":" ","kind":"text"},{"text":"presentAnimation:","kind":"identifier"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"PWTVOSRichMediaPresentAnimation","kind":"typeIdentifier","preciseIdentifier":"c:@M@PushwooshBridge@E@PWTVOSRichMediaPresentAnimation"},{"text":") ","kind":"text"},{"text":"presentAnimation","kind":"internalParam"},{"kind":"text","text":" "},{"text":"dismissAnimation:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@PushwooshBridge@E@PWTVOSRichMediaDismissAnimation","text":"PWTVOSRichMediaDismissAnimation"},{"text":") ","kind":"text"},{"text":"dismissAnimation","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation\/title","value":"PushwooshTVOSImplementation","op":"replace"},{"value":[{"kind":"identifier","text":"PushwooshTVOSImplementation"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation\/fragments"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1configureRichMediaWith(position:presentAnimation:dismissAnimation:)\/title","value":"configureRichMediaWithPosition:presentAnimation:dismissAnimation:","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1configureRichMediaWith(position:presentAnimation:dismissAnimation:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"configureRichMediaWithPosition:presentAnimation:dismissAnimation:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1configureCloseButton(_:)\/title","op":"replace","value":"configureCloseButton:"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"configureCloseButton:"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1configureCloseButton(_:)\/fragments"}]}]}