{"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/handleTvPushReceived(userInfo:completionHandler:)","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"handleTvPushReceivedWithUserInfo:completionHandler:"}],"platforms":[{"name":"tvOS","deprecated":false,"introducedAt":"11.0","unavailable":false,"beta":false}],"title":"handleTvPushReceived(userInfo:completionHandler:)","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"handleTvPushReceived","kind":"identifier"},{"text":"(","kind":"text"},{"text":"userInfo","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"text":"], ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": (","kind":"text"},{"preciseIdentifier":"c:@E@UIBackgroundFetchResult","text":"UIBackgroundFetchResult","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"symbolKind":"method","modules":[{"name":"PushwooshTVOS"}],"roleHeading":"Type Method","externalID":"c:@M@PushwooshTVOS@objc(cs)PushwooshTVOSImplementation(cm)handleTvPushReceivedWithUserInfo:completionHandler:"},"kind":"symbol","abstract":[{"type":"text","text":"Handles incoming push notification on tvOS."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["tvOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"handleTvPushReceived","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"userInfo"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"completionHandler"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" (","kind":"text"},{"text":"UIBackgroundFetchResult","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIBackgroundFetchResult"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")","kind":"text"}]}]},{"parameters":[{"name":"userInfo","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Dictionary containing push payload data."}]}]},{"name":"completionHandler","content":[{"inlineContent":[{"type":"text","text":"Completion handler to call when processing is complete."}],"type":"paragraph"}]}],"kind":"parameters"},{"kind":"content","content":[{"type":"heading","anchor":"discussion","text":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"text":"Call this method from ","type":"text"},{"type":"codeVoice","code":"application(_:didReceiveRemoteNotification:fetchCompletionHandler:)"},{"type":"text","text":" "},{"text":"to process incoming push notifications. The method automatically detects and displays","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Rich Media if present in the notification payload."}]},{"type":"heading","text":"Example","level":2,"anchor":"Example"},{"type":"codeListing","syntax":"swift","code":["func application(_ application: UIApplication,","                 didReceiveRemoteNotification userInfo: [AnyHashable: Any],","                 fetchCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult) -> Void) {","    Pushwoosh.TVoS.handleTvPushReceived(userInfo: userInfo, completionHandler: completionHandler)","}"]}]}],"seeAlsoSections":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/handleTvPushToken(_:)","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/handleTvPushRegistrationFailure(_:)","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/handleTVOSPush(userInfo:)"],"generated":true,"title":"Push Notification Handling"}],"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS"],["doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation"]]},"variants":[{"paths":["\/documentation\/pushwooshtvos\/pushwooshtvosimplementation\/handletvpushreceived(userinfo:completionhandler:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pushwooshtvos\/pushwooshtvosimplementation\/handletvpushreceived(userinfo:completionhandler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PushwooshTVOSImplementation/handleTvPushRegistrationFailure(_:)":{"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"handleTvPushRegistrationFailure"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"kind":"text","text":")"}],"url":"\/documentation\/pushwooshtvos\/pushwooshtvosimplementation\/handletvpushregistrationfailure(_:)","role":"symbol","abstract":[{"text":"Handles push registration failure on tvOS.","type":"text"}],"title":"handleTvPushRegistrationFailure(_:)","identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/handleTvPushRegistrationFailure(_:)","navigatorTitle":[{"kind":"identifier","text":"handleTvPushRegistrationFailure:"}]},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PushwooshTVOSImplementation/handleTVOSPush(userInfo:)":{"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"handleTVOSPush","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"userInfo"},{"kind":"text","text":": ["},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"text":"]) -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"handleTVOSPushWithUserInfo:"}],"url":"\/documentation\/pushwooshtvos\/pushwooshtvosimplementation\/handletvospush(userinfo:)","identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/handleTVOSPush(userInfo:)","abstract":[{"text":"Handles incoming push notifications with rich media content for tvOS.","type":"text"}],"title":"handleTVOSPush(userInfo:)","role":"symbol"},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PushwooshTVOSImplementation/handleTvPushReceived(userInfo:completionHandler:)":{"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"handleTvPushReceived"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"userInfo"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier","text":"AnyHashable"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"], ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"kind":"text","text":": ("},{"text":"UIBackgroundFetchResult","preciseIdentifier":"c:@E@UIBackgroundFetchResult","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"handleTvPushReceivedWithUserInfo:completionHandler:"}],"title":"handleTvPushReceived(userInfo:completionHandler:)","identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/handleTvPushReceived(userInfo:completionHandler:)","abstract":[{"text":"Handles incoming push notification on tvOS.","type":"text"}],"url":"\/documentation\/pushwooshtvos\/pushwooshtvosimplementation\/handletvpushreceived(userinfo:completionhandler:)","role":"symbol"},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS":{"identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS","abstract":[{"text":"Push notifications and Rich Media for tvOS apps.","type":"text"}],"kind":"symbol","role":"collection","url":"\/documentation\/pushwooshtvos","type":"topic","title":"PushwooshTVOS"},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PushwooshTVOSImplementation":{"identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PushwooshTVOSImplementation"}],"kind":"symbol","url":"\/documentation\/pushwooshtvos\/pushwooshtvosimplementation","abstract":[{"text":"Main implementation class for tvOS push notifications and Rich Media.","type":"text"}],"title":"PushwooshTVOSImplementation","navigatorTitle":[{"kind":"identifier","text":"PushwooshTVOSImplementation"}],"type":"topic"},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PushwooshTVOSImplementation/handleTvPushToken(_:)":{"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"handleTvPushToken","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"handleTvPushToken:"}],"url":"\/documentation\/pushwooshtvos\/pushwooshtvosimplementation\/handletvpushtoken(_:)","identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/handleTvPushToken(_:)","abstract":[{"text":"Handles the device token received from tvOS push registration.","type":"text"}],"title":"handleTvPushToken(_:)","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"path":"\/metadata\/title","value":"handleTvPushReceivedWithUserInfo:completionHandler:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"handleTvPushReceivedWithUserInfo:completionHandler:"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":[{"generated":true,"title":"Push Notification Handling","identifiers":["doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/handleTvPushToken(_:)","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/handleTvPushRegistrationFailure(_:)","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/handleTVOSPush(userInfo:)"]}],"op":"replace"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"handleTvPushReceivedWithUserInfo:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSDictionary","text":"NSDictionary","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"userInfo"},{"kind":"text","text":" "},{"kind":"identifier","text":"completionHandler:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":" (^","kind":"text"},{"kind":"text","text":")("},{"text":"UIBackgroundFetchResult","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIBackgroundFetchResult"},{"text":" ","kind":"text"},{"kind":"internalParam","text":""},{"kind":"text","text":")) "},{"kind":"internalParam","text":"completionHandler"},{"text":";","kind":"text"}],"platforms":["tvOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":"handleTvPushRegistrationFailure:","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1handleTvPushRegistrationFailure(_:)\/title"},{"value":[{"kind":"text","text":"+ "},{"text":"handleTvPushRegistrationFailure:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1handleTvPushRegistrationFailure(_:)\/fragments"},{"value":"handleTVOSPushWithUserInfo:","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1handleTVOSPush(userInfo:)\/title","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"handleTVOSPushWithUserInfo:"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1handleTVOSPush(userInfo:)\/fragments","op":"replace"},{"op":"replace","value":"handleTvPushReceivedWithUserInfo:completionHandler:","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1handleTvPushReceived(userInfo:completionHandler:)\/title"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"handleTvPushReceivedWithUserInfo:completionHandler:"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1handleTvPushReceived(userInfo:completionHandler:)\/fragments"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation\/title","op":"replace","value":"PushwooshTVOSImplementation"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation\/fragments","value":[{"text":"PushwooshTVOSImplementation","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1handleTvPushToken(_:)\/title","op":"replace","value":"handleTvPushToken:"},{"value":[{"text":"+ ","kind":"text"},{"text":"handleTvPushToken:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1handleTvPushToken(_:)\/fragments","op":"replace"}]}]}