{"seeAlsoSections":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/handleTvPushToken(_:)","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/handleTvPushReceived(userInfo:completionHandler:)","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/handleTVOSPush(userInfo:)"],"generated":true,"title":"Push Notification Handling"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshtvos\/pushwooshtvosimplementation\/handletvpushregistrationfailure(_:)"]},{"paths":["\/documentation\/pushwooshtvos\/pushwooshtvosimplementation\/handletvpushregistrationfailure(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS"],["doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/handleTvPushRegistrationFailure(_:)"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"handleTvPushRegistrationFailure","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["tvOS"]}],"kind":"declarations"},{"parameters":[{"name":"error","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The error that occurred during registration."}]}]}],"kind":"parameters"},{"kind":"content","content":[{"level":2,"text":"Discussion","anchor":"discussion","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Call this method from "},{"type":"codeVoice","code":"application(_:didFailToRegisterForRemoteNotificationsWithError:)"},{"type":"text","text":" "},{"text":"to log and handle registration errors.","type":"text"}]},{"type":"heading","anchor":"Example","level":2,"text":"Example"},{"type":"codeListing","code":["func application(_ application: UIApplication,","                 didFailToRegisterForRemoteNotificationsWithError error: Error) {","    Pushwoosh.TVoS.handleTvPushRegistrationFailure(error)","}"],"syntax":"swift"}]}],"sections":[],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"text":"Handles push registration failure on tvOS.","type":"text"}],"metadata":{"symbolKind":"method","role":"symbol","title":"handleTvPushRegistrationFailure(_:)","platforms":[{"name":"tvOS","beta":false,"unavailable":false,"introducedAt":"11.0","deprecated":false}],"navigatorTitle":[{"kind":"identifier","text":"handleTvPushRegistrationFailure:"}],"roleHeading":"Type Method","externalID":"c:@M@PushwooshTVOS@objc(cs)PushwooshTVOSImplementation(cm)handleTvPushRegistrationFailure:","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handleTvPushRegistrationFailure"},{"kind":"text","text":"("},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":")","kind":"text"}],"modules":[{"name":"PushwooshTVOS"}]},"references":{"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PushwooshTVOSImplementation":{"identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PushwooshTVOSImplementation"}],"abstract":[{"text":"Main implementation class for tvOS push notifications and Rich Media.","type":"text"}],"url":"\/documentation\/pushwooshtvos\/pushwooshtvosimplementation","navigatorTitle":[{"kind":"identifier","text":"PushwooshTVOSImplementation"}],"type":"topic","title":"PushwooshTVOSImplementation"},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PushwooshTVOSImplementation/handleTvPushToken(_:)":{"identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/handleTvPushToken(_:)","url":"\/documentation\/pushwooshtvos\/pushwooshtvosimplementation\/handletvpushtoken(_:)","title":"handleTvPushToken(_:)","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Handles the device token received from tvOS push registration."}],"navigatorTitle":[{"text":"handleTvPushToken:","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"handleTvPushToken"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":")"}],"kind":"symbol"},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PushwooshTVOSImplementation/handleTVOSPush(userInfo:)":{"identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/handleTVOSPush(userInfo:)","url":"\/documentation\/pushwooshtvos\/pushwooshtvosimplementation\/handletvospush(userinfo:)","title":"handleTVOSPush(userInfo:)","role":"symbol","type":"topic","abstract":[{"text":"Handles incoming push notifications with rich media content for tvOS.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"handleTVOSPushWithUserInfo:"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"handleTVOSPush"},{"kind":"text","text":"("},{"text":"userInfo","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"]) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"kind":"symbol"},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS":{"kind":"symbol","type":"topic","title":"PushwooshTVOS","role":"collection","url":"\/documentation\/pushwooshtvos","abstract":[{"type":"text","text":"Push notifications and Rich Media for tvOS apps."}],"identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS"},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PushwooshTVOSImplementation/handleTvPushRegistrationFailure(_:)":{"identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/handleTvPushRegistrationFailure(_:)","url":"\/documentation\/pushwooshtvos\/pushwooshtvosimplementation\/handletvpushregistrationfailure(_:)","title":"handleTvPushRegistrationFailure(_:)","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Handles push registration failure on tvOS."}],"navigatorTitle":[{"text":"handleTvPushRegistrationFailure:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"handleTvPushRegistrationFailure","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":")"}],"kind":"symbol"},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PushwooshTVOSImplementation/handleTvPushReceived(userInfo:completionHandler:)":{"identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/handleTvPushReceived(userInfo:completionHandler:)","url":"\/documentation\/pushwooshtvos\/pushwooshtvosimplementation\/handletvpushreceived(userinfo:completionhandler:)","title":"handleTvPushReceived(userInfo:completionHandler:)","role":"symbol","type":"topic","abstract":[{"text":"Handles incoming push notification on tvOS.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"handleTvPushReceivedWithUserInfo:completionHandler:"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"handleTvPushReceived"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"userInfo"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"completionHandler"},{"text":": (","kind":"text"},{"preciseIdentifier":"c:@E@UIBackgroundFetchResult","text":"UIBackgroundFetchResult","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"handleTvPushRegistrationFailure:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"handleTvPushRegistrationFailure:"}],"path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"replace","value":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/handleTvPushToken(_:)","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/handleTvPushReceived(userInfo:completionHandler:)","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/handleTVOSPush(userInfo:)"],"title":"Push Notification Handling","generated":true}]},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"handleTvPushRegistrationFailure:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier","text":"NSError"},{"text":" *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["tvOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation\/title","value":"PushwooshTVOSImplementation"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation\/fragments","value":[{"text":"PushwooshTVOSImplementation","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1handleTvPushToken(_:)\/title","op":"replace","value":"handleTvPushToken:"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1handleTvPushToken(_:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"handleTvPushToken:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1handleTVOSPush(userInfo:)\/title","value":"handleTVOSPushWithUserInfo:"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"handleTVOSPushWithUserInfo:"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1handleTVOSPush(userInfo:)\/fragments"},{"value":"handleTvPushRegistrationFailure:","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1handleTvPushRegistrationFailure(_:)\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1handleTvPushRegistrationFailure(_:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"handleTvPushRegistrationFailure:"}]},{"op":"replace","value":"handleTvPushReceivedWithUserInfo:completionHandler:","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1handleTvPushReceived(userInfo:completionHandler:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1handleTvPushReceived(userInfo:completionHandler:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"handleTvPushReceivedWithUserInfo:completionHandler:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}