{"sections":[],"abstract":[{"type":"text","text":"Singleton back-channel adapter used by "},{"code":"PWInAppMessagesManager","type":"codeVoice"},{"text":" to","type":"text"},{"type":"text","text":" "},{"text":"dispatch in-app resources to the tvOS rich-media manager without","type":"text"},{"type":"text","text":" "},{"text":"reflection.","type":"text"}],"metadata":{"title":"inAppBackchannel","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"inAppBackchannel","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PWTVoSInAppHandler","kind":"typeIdentifier","preciseIdentifier":"c:@M@PushwooshBridge@objc(pl)PWTVoSInAppHandler"}],"externalID":"c:@CM@PushwooshTVOS@objc(cs)PushwooshTVOSImplementation(cpy)inAppBackchannel","symbolKind":"property","role":"symbol","modules":[{"name":"PushwooshTVOS"}],"platforms":[{"unavailable":false,"beta":false,"deprecated":false,"introducedAt":"11.0","name":"tvOS"}],"navigatorTitle":[{"kind":"identifier","text":"inAppBackchannel"}],"roleHeading":"Type Property"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"inAppBackchannel"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@PushwooshBridge@objc(pl)PWTVoSInAppHandler","text":"PWTVoSInAppHandler","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["tvOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshtvos\/pushwooshtvosimplementation\/inappbackchannel"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshtvos\/pushwooshtvosimplementation\/inappbackchannel"]}],"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/inAppBackchannel","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation"]]},"references":{"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PushwooshTVOSImplementation/inAppBackchannel":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"inAppBackchannel","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PWTVoSInAppHandler","preciseIdentifier":"c:@M@PushwooshBridge@objc(pl)PWTVoSInAppHandler","kind":"typeIdentifier"}],"title":"inAppBackchannel","navigatorTitle":[{"kind":"identifier","text":"inAppBackchannel"}],"abstract":[{"type":"text","text":"Singleton back-channel adapter used by "},{"type":"codeVoice","code":"PWInAppMessagesManager"},{"text":" to","type":"text"},{"type":"text","text":" "},{"text":"dispatch in-app resources to the tvOS rich-media manager without","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"reflection."}],"url":"\/documentation\/pushwooshtvos\/pushwooshtvosimplementation\/inappbackchannel","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/inAppBackchannel"},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PushwooshTVOSImplementation":{"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PushwooshTVOSImplementation","kind":"identifier"}],"title":"PushwooshTVOSImplementation","navigatorTitle":[{"text":"PushwooshTVOSImplementation","kind":"identifier"}],"abstract":[{"type":"text","text":"Main implementation class for tvOS push notifications and Rich Media."}],"kind":"symbol","url":"\/documentation\/pushwooshtvos\/pushwooshtvosimplementation","identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation"},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS":{"title":"PushwooshTVOS","url":"\/documentation\/pushwooshtvos","identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS","kind":"symbol","type":"topic","role":"collection","abstract":[{"type":"text","text":"Push notifications and Rich Media for tvOS apps."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Type Property","op":"replace"},{"value":"inAppBackchannel","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"inAppBackchannel","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["tvOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":", "},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:Qo@M@PushwooshBridge@objc(pl)PWTVoSInAppHandler","kind":"typeIdentifier","text":"id<PWTVoSInAppHandler>"},{"text":" ","kind":"text"},{"text":"inAppBackchannel","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"inAppBackchannel","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1inAppBackchannel\/title"},{"value":[{"kind":"identifier","text":"inAppBackchannel"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1inAppBackchannel\/fragments"},{"value":"PushwooshTVOSImplementation","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation\/fragments","value":[{"text":"PushwooshTVOSImplementation","kind":"identifier"}],"op":"replace"}]}]}