{"kind":"symbol","metadata":{"platforms":[{"unavailable":false,"beta":false,"deprecated":false,"introducedAt":"11.0","name":"tvOS"}],"title":"registerForPushNotifications(withToken:completion:)","modules":[{"name":"PushwooshTVOS"}],"externalID":"c:@M@PushwooshTVOS@objc(cs)PushwooshTVOSImplementation(im)registerForPushNotificationsWithToken:completion:","role":"symbol","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"registerForPushNotificationsWithToken:completion:"}],"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"registerForPushNotifications"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withToken"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": ((","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")?)","kind":"text"}]},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation"]]},"abstract":[{"text":"Registers the tvOS device for push notifications with the Pushwoosh server.","type":"text"}],"variants":[{"paths":["\/documentation\/pushwooshtvos\/pushwooshtvosimplementation\/registerforpushnotifications(withtoken:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pushwooshtvos\/pushwooshtvosimplementation\/registerforpushnotifications(withtoken:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/registerForPushNotifications(withToken:completion:)"},"seeAlsoSections":[{"generated":true,"title":"Configuration","identifiers":["doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/setAppCode(_:)","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/registerForTvPushNotifications()"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"registerForPushNotifications"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withToken"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"token"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")? = nil)"}],"platforms":["tvOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"token","content":[{"inlineContent":[{"type":"text","text":"The device token received from APNs in "},{"code":"application(_:didRegisterForRemoteNotificationsWithDeviceToken:)","type":"codeVoice"},{"type":"text","text":"."}],"type":"paragraph"}]},{"name":"completion","content":[{"inlineContent":[{"text":"Optional completion handler called when registration completes. The handler receives an error parameter if registration fails, or nil on success.","type":"text"}],"type":"paragraph"}]}]},{"content":[{"text":"Discussion","type":"heading","anchor":"discussion","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Call this method after receiving a device token from Apple Push Notification service."},{"text":" ","type":"text"},{"type":"text","text":"This method sends the device token to Pushwoosh servers to enable push notifications."}]},{"anchor":"Example","text":"Example","level":2,"type":"heading"},{"code":["func application(_ application: UIApplication,","                 didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {","    Pushwoosh.TVoS.registerForPushNotifications(withToken: deviceToken) { error in","        if let error = error {","            print(\"Failed to register: \\(error)\")","        } else {","            print(\"Successfully registered\")","        }","    }","}"],"type":"codeListing","syntax":"swift"}],"kind":"content"}],"references":{"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PushwooshTVOSImplementation":{"role":"symbol","abstract":[{"type":"text","text":"Main implementation class for tvOS push notifications and Rich Media."}],"title":"PushwooshTVOSImplementation","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PushwooshTVOSImplementation"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation","url":"\/documentation\/pushwooshtvos\/pushwooshtvosimplementation","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PushwooshTVOSImplementation"}]},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS":{"role":"collection","identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS","abstract":[{"type":"text","text":"Push notifications and Rich Media for tvOS apps."}],"type":"topic","kind":"symbol","url":"\/documentation\/pushwooshtvos","title":"PushwooshTVOS"},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PushwooshTVOSImplementation/registerForPushNotifications(withToken:completion:)":{"abstract":[{"text":"Registers the tvOS device for push notifications with the Pushwoosh server.","type":"text"}],"url":"\/documentation\/pushwooshtvos\/pushwooshtvosimplementation\/registerforpushnotifications(withtoken:completion:)","title":"registerForPushNotifications(withToken:completion:)","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/registerForPushNotifications(withToken:completion:)","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"registerForPushNotificationsWithToken:completion:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"registerForPushNotifications"},{"text":"(","kind":"text"},{"text":"withToken","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")?)","kind":"text"}]},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PushwooshTVOSImplementation/setAppCode(_:)":{"identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/setAppCode(_:)","url":"\/documentation\/pushwooshtvos\/pushwooshtvosimplementation\/setappcode(_:)","title":"setAppCode(_:)","abstract":[{"type":"text","text":"Sets the Pushwoosh application code for tvOS."}],"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"setAppCode:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setAppCode","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PushwooshTVOSImplementation/registerForTvPushNotifications()":{"abstract":[{"type":"text","text":"Registers for tvOS push notifications."}],"url":"\/documentation\/pushwooshtvos\/pushwooshtvosimplementation\/registerfortvpushnotifications()","title":"registerForTvPushNotifications()","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/registerForTvPushNotifications()","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"registerForTvPushNotifications"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"registerForTvPushNotifications","kind":"identifier"},{"kind":"text","text":"()"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"registerForPushNotificationsWithToken:completion:","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"registerForPushNotificationsWithToken:completion:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"replace","value":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/setAppCode(_:)","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/registerForTvPushNotifications()"],"generated":true,"title":"Configuration"}]},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["tvOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"registerForPushNotificationsWithToken:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSData","text":"NSData"},{"kind":"text","text":" *) "},{"text":"token","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"completion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":" (^"},{"text":")(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"text":" * ","kind":"text"},{"kind":"internalParam","text":""},{"text":")) ","kind":"text"},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation\/title","op":"replace","value":"PushwooshTVOSImplementation"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation\/fragments","value":[{"kind":"identifier","text":"PushwooshTVOSImplementation"}]},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1registerForPushNotifications(withToken:completion:)\/title","value":"registerForPushNotificationsWithToken:completion:","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"registerForPushNotificationsWithToken:completion:"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1registerForPushNotifications(withToken:completion:)\/fragments"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1setAppCode(_:)\/title","op":"replace","value":"setAppCode:"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1setAppCode(_:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"setAppCode:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1registerForTvPushNotifications()\/title","value":"registerForTvPushNotifications"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"registerForTvPushNotifications"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1registerForTvPushNotifications()\/fragments"}]}]}