{"abstract":[{"text":"Rich Media manager instance for displaying HTML content.","type":"text"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshtvos\/pushwooshtvosimplementation\/richmediamanager"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshtvos\/pushwooshtvosimplementation\/richmediamanager"]}],"primaryContentSections":[{"declarations":[{"platforms":["tvOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"richMediaManager","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PWTVOSRichMediaManager","preciseIdentifier":"c:@M@PushwooshTVOS@objc(cs)PWTVOSRichMediaManager","identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PWTVOSRichMediaManager"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"inlineContent":[{"type":"text","text":"Provides access to the Rich Media manager for advanced configuration"},{"text":" ","type":"text"},{"type":"text","text":"and programmatic control of Rich Media display."}],"type":"paragraph"}],"kind":"content"}],"metadata":{"externalID":"c:@M@PushwooshTVOS@objc(cs)PushwooshTVOSImplementation(py)richMediaManager","title":"richMediaManager","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"richMediaManager","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@PushwooshTVOS@objc(cs)PWTVOSRichMediaManager","kind":"typeIdentifier","text":"PWTVOSRichMediaManager"}],"navigatorTitle":[{"text":"richMediaManager","kind":"identifier"}],"role":"symbol","roleHeading":"Instance Property","symbolKind":"property","platforms":[{"unavailable":false,"beta":false,"introducedAt":"11.0","name":"tvOS","deprecated":false}],"modules":[{"name":"PushwooshTVOS"}]},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation"]]},"seeAlsoSections":[{"title":"Rich Media","generated":true,"identifiers":["doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/configureRichMediaWith(position:presentAnimation:dismissAnimation:)","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/configureCloseButton(_:)","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/setRichMediaGetTagsHandler(_:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/richMediaManager"},"references":{"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS":{"identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS","url":"\/documentation\/pushwooshtvos","role":"collection","kind":"symbol","abstract":[{"text":"Push notifications and Rich Media for tvOS apps.","type":"text"}],"title":"PushwooshTVOS","type":"topic"},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PushwooshTVOSImplementation/setRichMediaGetTagsHandler(_:)":{"type":"topic","url":"\/documentation\/pushwooshtvos\/pushwooshtvosimplementation\/setrichmediagettagshandler(_:)","title":"setRichMediaGetTagsHandler(_:)","identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/setRichMediaGetTagsHandler(_:)","abstract":[{"type":"text","text":"Sets a handler to receive tags when requested from rich media content."}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setRichMediaGetTagsHandler","kind":"identifier"},{"text":"(([","kind":"text"},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]) -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"setRichMediaGetTagsHandler:","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PushwooshTVOSImplementation":{"abstract":[{"text":"Main implementation class for tvOS push notifications and Rich Media.","type":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation","navigatorTitle":[{"kind":"identifier","text":"PushwooshTVOSImplementation"}],"url":"\/documentation\/pushwooshtvos\/pushwooshtvosimplementation","title":"PushwooshTVOSImplementation","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PushwooshTVOSImplementation","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PWTVOSRichMediaManager":{"kind":"symbol","title":"PWTVOSRichMediaManager","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PWTVOSRichMediaManager","abstract":[{"text":"Manager for displaying Rich Media content on tvOS.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PWTVOSRichMediaManager","kind":"identifier"}],"navigatorTitle":[{"text":"PWTVOSRichMediaManager","kind":"identifier"}],"url":"\/documentation\/pushwooshtvos\/pwtvosrichmediamanager","role":"symbol"},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PushwooshTVOSImplementation/configureRichMediaWith(position:presentAnimation:dismissAnimation:)":{"abstract":[{"type":"text","text":"Configures rich media presentation, positioning, and dismissal animations for tvOS."}],"kind":"symbol","url":"\/documentation\/pushwooshtvos\/pushwooshtvosimplementation\/configurerichmediawith(position:presentanimation:dismissanimation:)","identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/configureRichMediaWith(position:presentAnimation:dismissAnimation:)","title":"configureRichMediaWith(position:presentAnimation:dismissAnimation:)","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"configureRichMediaWith","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"position"},{"kind":"text","text":": "},{"text":"PWTVOSRichMediaPosition","preciseIdentifier":"c:@M@PushwooshBridge@E@PWTVOSRichMediaPosition","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"presentAnimation","kind":"externalParam"},{"kind":"text","text":": "},{"text":"PWTVOSRichMediaPresentAnimation","kind":"typeIdentifier","preciseIdentifier":"c:@M@PushwooshBridge@E@PWTVOSRichMediaPresentAnimation"},{"kind":"text","text":", "},{"text":"dismissAnimation","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"PWTVOSRichMediaDismissAnimation","preciseIdentifier":"c:@M@PushwooshBridge@E@PWTVOSRichMediaDismissAnimation"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"configureRichMediaWithPosition:presentAnimation:dismissAnimation:","kind":"identifier"}]},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PushwooshTVOSImplementation/configureCloseButton(_:)":{"identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/configureCloseButton(_:)","abstract":[{"type":"text","text":"Controls whether the Close button is displayed on rich media content."}],"url":"\/documentation\/pushwooshtvos\/pushwooshtvosimplementation\/configureclosebutton(_:)","kind":"symbol","title":"configureCloseButton(_:)","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"configureCloseButton","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"configureCloseButton:"}]},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PushwooshTVOSImplementation/richMediaManager":{"type":"topic","url":"\/documentation\/pushwooshtvos\/pushwooshtvosimplementation\/richmediamanager","identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/richMediaManager","title":"richMediaManager","abstract":[{"type":"text","text":"Rich Media manager instance for displaying HTML content."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"richMediaManager"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@PushwooshTVOS@objc(cs)PWTVOSRichMediaManager","text":"PWTVOSRichMediaManager","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"richMediaManager","kind":"identifier"}],"kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"richMediaManager","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","value":[{"text":"richMediaManager","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"replace","path":"\/seeAlsoSections","value":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/configureRichMediaWith(position:presentAnimation:dismissAnimation:)","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/configureCloseButton(_:)","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/setRichMediaGetTagsHandler(_:)"],"title":"Rich Media","generated":true}]},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PWTVOSRichMediaManager","text":"PWTVOSRichMediaManager","preciseIdentifier":"c:@M@PushwooshTVOS@objc(cs)PWTVOSRichMediaManager"},{"kind":"text","text":" * "},{"text":"richMediaManager","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["tvOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1setRichMediaGetTagsHandler(_:)\/title","value":"setRichMediaGetTagsHandler:"},{"value":[{"text":"+ ","kind":"text"},{"text":"setRichMediaGetTagsHandler:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1setRichMediaGetTagsHandler(_:)\/fragments"},{"op":"replace","value":"PushwooshTVOSImplementation","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation\/title"},{"value":[{"text":"PushwooshTVOSImplementation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation\/fragments"},{"value":"PWTVOSRichMediaManager","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PWTVOSRichMediaManager\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PWTVOSRichMediaManager\/fragments","value":[{"text":"PWTVOSRichMediaManager","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1configureRichMediaWith(position:presentAnimation:dismissAnimation:)\/title","value":"configureRichMediaWithPosition:presentAnimation:dismissAnimation:","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"text":"configureRichMediaWithPosition:presentAnimation:dismissAnimation:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1configureRichMediaWith(position:presentAnimation:dismissAnimation:)\/fragments"},{"value":"configureCloseButton:","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1configureCloseButton(_:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1configureCloseButton(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"configureCloseButton:"}]},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1richMediaManager\/title","value":"richMediaManager","op":"replace"},{"value":[{"text":"richMediaManager","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1richMediaManager\/fragments"}]}]}