{"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"seeAlsoSections":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/registerForTvPushNotifications()","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/unregisterForTvPushNotifications(completion:)"],"generated":true,"title":"Configuration"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["tvOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setAppCode"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"appCode","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":")"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The Pushwoosh application identifier (format: XXXXX-XXXXX)."}]}],"name":"appCode"}]},{"content":[{"type":"heading","level":2,"anchor":"discussion","text":"Discussion"},{"inlineContent":[{"type":"text","text":"This method must be called before registering for push notifications."},{"type":"text","text":" "},{"type":"text","text":"The app code can be found in your Pushwoosh Control Panel."}],"type":"paragraph"},{"text":"Example","type":"heading","level":2,"anchor":"Example"},{"code":["Pushwoosh.TVoS.setAppCode(\"12345-67890\")"],"type":"codeListing","syntax":"swift"}],"kind":"content"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/setAppCode(_:)"},"abstract":[{"type":"text","text":"Sets the Pushwoosh application code for tvOS."}],"kind":"symbol","variants":[{"paths":["\/documentation\/pushwooshtvos\/pushwooshtvosimplementation\/setappcode(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshtvos\/pushwooshtvosimplementation\/setappcode(_:)"]}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS"],["doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation"]]},"metadata":{"title":"setAppCode(_:)","navigatorTitle":[{"text":"setAppCode:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"setAppCode","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"roleHeading":"Type Method","symbolKind":"method","externalID":"c:@M@PushwooshTVOS@objc(cs)PushwooshTVOSImplementation(cm)setAppCode:","role":"symbol","modules":[{"name":"PushwooshTVOS"}],"platforms":[{"unavailable":false,"introducedAt":"11.0","deprecated":false,"beta":false,"name":"tvOS"}]},"references":{"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PushwooshTVOSImplementation/unregisterForTvPushNotifications(completion:)":{"title":"unregisterForTvPushNotifications(completion:)","navigatorTitle":[{"text":"unregisterForTvPushNotificationsWithCompletion:","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unregisterForTvPushNotifications"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": ((","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")?)","kind":"text"}],"abstract":[{"type":"text","text":"Unregisters the tvOS device from receiving push notifications."}],"url":"\/documentation\/pushwooshtvos\/pushwooshtvosimplementation\/unregisterfortvpushnotifications(completion:)","role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/unregisterForTvPushNotifications(completion:)","kind":"symbol","type":"topic"},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PushwooshTVOSImplementation/setAppCode(_:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setAppCode"},{"text":"(","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/setAppCode(_:)","url":"\/documentation\/pushwooshtvos\/pushwooshtvosimplementation\/setappcode(_:)","kind":"symbol","title":"setAppCode(_:)","type":"topic","navigatorTitle":[{"text":"setAppCode:","kind":"identifier"}],"abstract":[{"text":"Sets the Pushwoosh application code for tvOS.","type":"text"}]},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS","abstract":[{"text":"Push notifications and Rich Media for tvOS apps.","type":"text"}],"role":"collection","url":"\/documentation\/pushwooshtvos","title":"PushwooshTVOS"},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PushwooshTVOSImplementation":{"kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PushwooshTVOSImplementation"}],"abstract":[{"type":"text","text":"Main implementation class for tvOS push notifications and Rich Media."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PushwooshTVOSImplementation"}],"role":"symbol","url":"\/documentation\/pushwooshtvos\/pushwooshtvosimplementation","title":"PushwooshTVOSImplementation"},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PushwooshTVOSImplementation/registerForTvPushNotifications()":{"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"registerForTvPushNotifications","kind":"identifier"},{"kind":"text","text":"()"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/registerForTvPushNotifications()","url":"\/documentation\/pushwooshtvos\/pushwooshtvosimplementation\/registerfortvpushnotifications()","kind":"symbol","title":"registerForTvPushNotifications()","type":"topic","navigatorTitle":[{"kind":"identifier","text":"registerForTvPushNotifications"}],"abstract":[{"text":"Registers for tvOS push notifications.","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"op":"replace","value":"setAppCode:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"setAppCode:"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":[{"title":"Configuration","identifiers":["doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/registerForTvPushNotifications()","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/unregisterForTvPushNotifications(completion:)"],"generated":true}],"path":"\/seeAlsoSections","op":"replace"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["tvOS"],"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"setAppCode:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"appCode","kind":"internalParam"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1unregisterForTvPushNotifications(completion:)\/title","value":"unregisterForTvPushNotificationsWithCompletion:"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1unregisterForTvPushNotifications(completion:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"unregisterForTvPushNotificationsWithCompletion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1setAppCode(_:)\/title","value":"setAppCode:"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1setAppCode(_:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"setAppCode:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation\/title","value":"PushwooshTVOSImplementation"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation\/fragments","op":"replace","value":[{"kind":"identifier","text":"PushwooshTVOSImplementation"}]},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1registerForTvPushNotifications()\/title","op":"replace","value":"registerForTvPushNotifications"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1registerForTvPushNotifications()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"registerForTvPushNotifications"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}