{"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation"]]},"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/setRichMediaGetTagsHandler(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Sets a handler to receive tags when requested from rich media content."}],"metadata":{"platforms":[{"beta":false,"unavailable":false,"name":"tvOS","introducedAt":"11.0","deprecated":false}],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setRichMediaGetTagsHandler"},{"kind":"text","text":"((["},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"roleHeading":"Type Method","externalID":"c:@M@PushwooshTVOS@objc(cs)PushwooshTVOSImplementation(cm)setRichMediaGetTagsHandler:","navigatorTitle":[{"text":"setRichMediaGetTagsHandler:","kind":"identifier"}],"symbolKind":"method","modules":[{"name":"PushwooshTVOS"}],"title":"setRichMediaGetTagsHandler(_:)"},"sections":[],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"seeAlsoSections":[{"generated":true,"title":"Rich Media","identifiers":["doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/richMediaManager","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/configureRichMediaWith(position:presentAnimation:dismissAnimation:)","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/configureCloseButton(_:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setRichMediaGetTagsHandler","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"handler","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"attribute","text":"@escaping"},{"text":" ([","kind":"text"},{"text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]) -> "},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["tvOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"A closure that receives tags as a dictionary when getTags is triggered. The dictionary contains tag keys and their values.","type":"text"}],"type":"paragraph"}],"name":"handler"}]},{"kind":"content","content":[{"anchor":"discussion","type":"heading","level":2,"text":"Discussion"},{"inlineContent":[{"type":"text","text":"When a user interacts with a getTags button in rich media HTML content,"},{"text":" ","type":"text"},{"type":"text","text":"this handler will be called with the tags retrieved from Pushwoosh."},{"text":" ","type":"text"},{"type":"text","text":"This allows you to handle tag data in your application as needed."}],"type":"paragraph"},{"text":"Example","level":2,"type":"heading","anchor":"Example"},{"code":["Pushwoosh.TVoS.setRichMediaGetTagsHandler { tags in","    print(\"Received tags from rich media: \\(tags)\")","    \/\/ Handle tags in your application","}"],"type":"codeListing","syntax":"swift"}]}],"variants":[{"paths":["\/documentation\/pushwooshtvos\/pushwooshtvosimplementation\/setrichmediagettagshandler(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshtvos\/pushwooshtvosimplementation\/setrichmediagettagshandler(_:)"]}],"references":{"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PushwooshTVOSImplementation":{"abstract":[{"type":"text","text":"Main implementation class for tvOS push notifications and Rich Media."}],"role":"symbol","kind":"symbol","url":"\/documentation\/pushwooshtvos\/pushwooshtvosimplementation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PushwooshTVOSImplementation","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PushwooshTVOSImplementation"}],"type":"topic","title":"PushwooshTVOSImplementation","identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation"},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS":{"type":"topic","title":"PushwooshTVOS","role":"collection","identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS","url":"\/documentation\/pushwooshtvos","kind":"symbol","abstract":[{"type":"text","text":"Push notifications and Rich Media for tvOS apps."}]},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PushwooshTVOSImplementation/setRichMediaGetTagsHandler(_:)":{"url":"\/documentation\/pushwooshtvos\/pushwooshtvosimplementation\/setrichmediagettagshandler(_:)","abstract":[{"text":"Sets a handler to receive tags when requested from rich media content.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setRichMediaGetTagsHandler"},{"text":"(([","kind":"text"},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]) -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","navigatorTitle":[{"text":"setRichMediaGetTagsHandler:","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/setRichMediaGetTagsHandler(_:)","kind":"symbol","title":"setRichMediaGetTagsHandler(_:)"},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PushwooshTVOSImplementation/configureCloseButton(_:)":{"url":"\/documentation\/pushwooshtvos\/pushwooshtvosimplementation\/configureclosebutton(_:)","abstract":[{"type":"text","text":"Controls whether the Close button is displayed on rich media content."}],"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"configureCloseButton"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","navigatorTitle":[{"text":"configureCloseButton:","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/configureCloseButton(_:)","title":"configureCloseButton(_:)"},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PushwooshTVOSImplementation/richMediaManager":{"url":"\/documentation\/pushwooshtvos\/pushwooshtvosimplementation\/richmediamanager","abstract":[{"text":"Rich Media manager instance for displaying HTML content.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"richMediaManager"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@PushwooshTVOS@objc(cs)PWTVOSRichMediaManager","text":"PWTVOSRichMediaManager","kind":"typeIdentifier"}],"type":"topic","navigatorTitle":[{"text":"richMediaManager","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/richMediaManager","title":"richMediaManager"},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PushwooshTVOSImplementation/configureRichMediaWith(position:presentAnimation:dismissAnimation:)":{"url":"\/documentation\/pushwooshtvos\/pushwooshtvosimplementation\/configurerichmediawith(position:presentanimation:dismissanimation:)","abstract":[{"text":"Configures rich media presentation, positioning, and dismissal animations for tvOS.","type":"text"}],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"configureRichMediaWith","kind":"identifier"},{"text":"(","kind":"text"},{"text":"position","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@PushwooshBridge@E@PWTVOSRichMediaPosition","text":"PWTVOSRichMediaPosition"},{"text":", ","kind":"text"},{"text":"presentAnimation","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@PushwooshBridge@E@PWTVOSRichMediaPresentAnimation","kind":"typeIdentifier","text":"PWTVOSRichMediaPresentAnimation"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"dismissAnimation"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@PushwooshBridge@E@PWTVOSRichMediaDismissAnimation","text":"PWTVOSRichMediaDismissAnimation","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"configureRichMediaWithPosition:presentAnimation:dismissAnimation:"}],"kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/configureRichMediaWith(position:presentAnimation:dismissAnimation:)","title":"configureRichMediaWith(position:presentAnimation:dismissAnimation:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"path":"\/metadata\/title","value":"setRichMediaGetTagsHandler:","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"setRichMediaGetTagsHandler:"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Rich Media","generated":true,"identifiers":["doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/richMediaManager","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/configureRichMediaWith(position:presentAnimation:dismissAnimation:)","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/configureCloseButton(_:)"]}]},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"setRichMediaGetTagsHandler:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":" (^"},{"text":")(","kind":"text"},{"text":"NSDictionary","preciseIdentifier":"c:objc(cs)NSDictionary","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"kind":"text","text":")) "},{"text":"handler","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["tvOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation\/title","value":"PushwooshTVOSImplementation","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation\/fragments","value":[{"text":"PushwooshTVOSImplementation","kind":"identifier"}]},{"op":"replace","value":"setRichMediaGetTagsHandler:","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1setRichMediaGetTagsHandler(_:)\/title"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"setRichMediaGetTagsHandler:"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1setRichMediaGetTagsHandler(_:)\/fragments","op":"replace"},{"value":"configureCloseButton:","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1configureCloseButton(_:)\/title"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"configureCloseButton:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1configureCloseButton(_:)\/fragments"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1richMediaManager\/title","value":"richMediaManager","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1richMediaManager\/fragments","value":[{"kind":"identifier","text":"richMediaManager"}]},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1configureRichMediaWith(position:presentAnimation:dismissAnimation:)\/title","op":"replace","value":"configureRichMediaWithPosition:presentAnimation:dismissAnimation:"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1configureRichMediaWith(position:presentAnimation:dismissAnimation:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"configureRichMediaWithPosition:presentAnimation:dismissAnimation:"}]}]}]}