{"kind":"symbol","identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/shared","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["tvOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(shared) "},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"shared","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation","kind":"typeIdentifier","preciseIdentifier":"c:@M@PushwooshTVOS@objc(cs)PushwooshTVOSImplementation","text":"PushwooshTVOSImplementation"}],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/pushwooshtvos\/pushwooshtvosimplementation\/shared"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pushwooshtvos\/pushwooshtvosimplementation\/shared"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Shared singleton instance of the tvOS implementation."}],"sections":[],"metadata":{"symbolKind":"property","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"shared","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@PushwooshTVOS@objc(cs)PushwooshTVOSImplementation","text":"PushwooshTVOSImplementation","kind":"typeIdentifier"}],"externalID":"c:@M@PushwooshTVOS@objc(cs)PushwooshTVOSImplementation(cpy)shared","modules":[{"name":"PushwooshTVOS"}],"navigatorTitle":[{"kind":"identifier","text":"shared"}],"role":"symbol","title":"shared","roleHeading":"Type Property","platforms":[{"unavailable":false,"name":"tvOS","introducedAt":"11.0","beta":false,"deprecated":false}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation"]]},"references":{"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PushwooshTVOSImplementation/shared":{"identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/shared","navigatorTitle":[{"kind":"identifier","text":"shared"}],"title":"shared","abstract":[{"text":"Shared singleton instance of the tvOS implementation.","type":"text"}],"url":"\/documentation\/pushwooshtvos\/pushwooshtvosimplementation\/shared","type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"shared","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@PushwooshTVOS@objc(cs)PushwooshTVOSImplementation","text":"PushwooshTVOSImplementation","kind":"typeIdentifier"}]},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PushwooshTVOSImplementation":{"identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation","navigatorTitle":[{"kind":"identifier","text":"PushwooshTVOSImplementation"}],"title":"PushwooshTVOSImplementation","abstract":[{"type":"text","text":"Main implementation class for tvOS push notifications and Rich Media."}],"url":"\/documentation\/pushwooshtvos\/pushwooshtvosimplementation","type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PushwooshTVOSImplementation","kind":"identifier"}]},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS":{"abstract":[{"type":"text","text":"Push notifications and Rich Media for tvOS apps."}],"identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS","title":"PushwooshTVOS","url":"\/documentation\/pushwooshtvos","type":"topic","kind":"symbol","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Type Property","op":"replace"},{"value":"shared","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"shared","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"class","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"PushwooshTVOSImplementation","kind":"typeIdentifier","identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation","preciseIdentifier":"c:@M@PushwooshTVOS@objc(cs)PushwooshTVOSImplementation"},{"kind":"text","text":" * "},{"kind":"identifier","text":"shared"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["tvOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"shared","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1shared\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1shared\/fragments","value":[{"text":"shared","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation\/title","value":"PushwooshTVOSImplementation"},{"value":[{"kind":"identifier","text":"PushwooshTVOSImplementation"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}