{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/tvos()"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["tvOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tvos","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:s8AnyClassa","text":"AnyClass","kind":"typeIdentifier"}],"languages":["swift"]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","metadata":{"role":"symbol","externalID":"c:@M@PushwooshTVOS@objc(cs)PushwooshTVOSImplementation(cm)tvos","title":"tvos()","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"tvos"}],"modules":[{"name":"PushwooshTVOS"}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"tvos"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:s8AnyClassa","text":"AnyClass","kind":"typeIdentifier"}],"platforms":[{"deprecated":false,"unavailable":false,"beta":false,"name":"tvOS","introducedAt":"11.0"}],"roleHeading":"Type Method"},"variants":[{"paths":["\/documentation\/pushwooshtvos\/pushwooshtvosimplementation\/tvos()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pushwooshtvos\/pushwooshtvosimplementation\/tvos()"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation"]]},"references":{"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PushwooshTVOSImplementation":{"kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PushwooshTVOSImplementation"}],"abstract":[{"type":"text","text":"Main implementation class for tvOS push notifications and Rich Media."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PushwooshTVOSImplementation"}],"role":"symbol","url":"\/documentation\/pushwooshtvos\/pushwooshtvosimplementation","title":"PushwooshTVOSImplementation"},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PushwooshTVOSImplementation/tvos()":{"kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/tvos()","role":"symbol","abstract":[],"type":"topic","title":"tvos()","navigatorTitle":[{"kind":"identifier","text":"tvos"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"tvos"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:s8AnyClassa","kind":"typeIdentifier","text":"AnyClass"}],"url":"\/documentation\/pushwooshtvos\/pushwooshtvosimplementation\/tvos()"},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS","abstract":[{"text":"Push notifications and Rich Media for tvOS apps.","type":"text"}],"role":"collection","url":"\/documentation\/pushwooshtvos","title":"PushwooshTVOS"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"tvos","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"tvos"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:*QO","text":"Class","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"tvos","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["tvOS"]}]}},{"value":"PushwooshTVOSImplementation","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation\/title","op":"replace"},{"value":[{"kind":"identifier","text":"PushwooshTVOSImplementation"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1tvos()\/title","value":"tvos","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"text":"tvos","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1tvos()\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}