{"variants":[{"paths":["\/documentation\/pushwooshtvos\/pushwooshtvosimplementation\/unregisterforpushnotifications(completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshtvos\/pushwooshtvosimplementation\/unregisterforpushnotifications(completion:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/unregisterForPushNotifications(completion:)"},"metadata":{"title":"unregisterForPushNotifications(completion:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unregisterForPushNotifications"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"externalID":"c:@M@PushwooshTVOS@objc(cs)PushwooshTVOSImplementation(im)unregisterForPushNotificationsWithCompletion:","navigatorTitle":[{"text":"unregisterForPushNotificationsWithCompletion:","kind":"identifier"}],"platforms":[{"unavailable":false,"deprecated":false,"beta":false,"name":"tvOS","introducedAt":"11.0"}],"modules":[{"name":"PushwooshTVOS"}],"roleHeading":"Instance Method","symbolKind":"method"},"primaryContentSections":[{"declarations":[{"platforms":["tvOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"unregisterForPushNotifications","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")? = nil)","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Optional completion handler called when unregistration completes. The handler receives an error parameter if unregistration fails, or nil on success."}]}],"name":"completion"}],"kind":"parameters"},{"content":[{"type":"heading","anchor":"discussion","level":2,"text":"Discussion"},{"inlineContent":[{"type":"text","text":"This method removes the device registration from Pushwoosh servers."},{"text":" ","type":"text"},{"type":"text","text":"The device will no longer receive push notifications until it registers again."}],"type":"paragraph"},{"text":"Example","type":"heading","level":2,"anchor":"Example"},{"syntax":"swift","type":"codeListing","code":["Pushwoosh.TVoS.unregisterForTvPushNotifications { error in","    if let error = error {","        print(\"Failed to unregister: \\(error)\")","    } else {","        print(\"Successfully unregistered\")","    }","}"]}],"kind":"content"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"abstract":[{"type":"text","text":"Unregisters the tvOS device from receiving push notifications."}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation"]]},"kind":"symbol","references":{"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PushwooshTVOSImplementation/unregisterForPushNotifications(completion:)":{"title":"unregisterForPushNotifications(completion:)","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/unregisterForPushNotifications(completion:)","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"unregisterForPushNotificationsWithCompletion:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"unregisterForPushNotifications","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"abstract":[{"text":"Unregisters the tvOS device from receiving push notifications.","type":"text"}],"url":"\/documentation\/pushwooshtvos\/pushwooshtvosimplementation\/unregisterforpushnotifications(completion:)"},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PushwooshTVOSImplementation":{"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PushwooshTVOSImplementation","kind":"identifier"}],"url":"\/documentation\/pushwooshtvos\/pushwooshtvosimplementation","navigatorTitle":[{"text":"PushwooshTVOSImplementation","kind":"identifier"}],"abstract":[{"type":"text","text":"Main implementation class for tvOS push notifications and Rich Media."}],"identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation","title":"PushwooshTVOSImplementation","type":"topic"},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS":{"type":"topic","abstract":[{"type":"text","text":"Push notifications and Rich Media for tvOS apps."}],"kind":"symbol","url":"\/documentation\/pushwooshtvos","role":"collection","title":"PushwooshTVOS","identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"unregisterForPushNotificationsWithCompletion:","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"unregisterForPushNotificationsWithCompletion:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"unregisterForPushNotificationsWithCompletion:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":" (^"},{"text":")(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"kind":"text","text":" * "},{"text":"","kind":"internalParam"},{"kind":"text","text":")) "},{"text":"completion","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["tvOS"]}]}},{"value":"unregisterForPushNotificationsWithCompletion:","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1unregisterForPushNotifications(completion:)\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1unregisterForPushNotifications(completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"unregisterForPushNotificationsWithCompletion:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation\/title","value":"PushwooshTVOSImplementation","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation\/fragments","value":[{"text":"PushwooshTVOSImplementation","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}