{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/unregisterForTvPushNotifications(completion:)"},"seeAlsoSections":[{"title":"Configuration","identifiers":["doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/setAppCode(_:)","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/registerForTvPushNotifications()"],"generated":true}],"variants":[{"paths":["\/documentation\/pushwooshtvos\/pushwooshtvosimplementation\/unregisterfortvpushnotifications(completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshtvos\/pushwooshtvosimplementation\/unregisterfortvpushnotifications(completion:)"]}],"abstract":[{"text":"Unregisters the tvOS device from receiving push notifications.","type":"text"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unregisterForTvPushNotifications"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":"?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")? = nil)"}],"platforms":["tvOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"Optional completion handler called when unregistration completes.","type":"text"}],"type":"paragraph"}],"name":"completion"}]},{"kind":"content","content":[{"text":"Discussion","anchor":"discussion","level":2,"type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This is a convenience method that calls the instance method on the shared instance."}]}]}],"metadata":{"roleHeading":"Type Method","platforms":[{"deprecated":false,"beta":false,"unavailable":false,"name":"tvOS","introducedAt":"11.0"}],"symbolKind":"method","title":"unregisterForTvPushNotifications(completion:)","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unregisterForTvPushNotifications","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"unregisterForTvPushNotificationsWithCompletion:"}],"externalID":"c:@M@PushwooshTVOS@objc(cs)PushwooshTVOSImplementation(cm)unregisterForTvPushNotificationsWithCompletion:","role":"symbol","modules":[{"name":"PushwooshTVOS"}]},"kind":"symbol","references":{"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PushwooshTVOSImplementation/registerForTvPushNotifications()":{"identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/registerForTvPushNotifications()","title":"registerForTvPushNotifications()","abstract":[{"type":"text","text":"Registers for tvOS push notifications."}],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"registerForTvPushNotifications","kind":"identifier"},{"kind":"text","text":"()"}],"navigatorTitle":[{"kind":"identifier","text":"registerForTvPushNotifications"}],"url":"\/documentation\/pushwooshtvos\/pushwooshtvosimplementation\/registerfortvpushnotifications()"},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PushwooshTVOSImplementation/setAppCode(_:)":{"kind":"symbol","title":"setAppCode(_:)","type":"topic","abstract":[{"type":"text","text":"Sets the Pushwoosh application code for tvOS."}],"identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/setAppCode(_:)","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setAppCode","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"setAppCode:"}],"url":"\/documentation\/pushwooshtvos\/pushwooshtvosimplementation\/setappcode(_:)"},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PushwooshTVOSImplementation/unregisterForTvPushNotifications(completion:)":{"identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/unregisterForTvPushNotifications(completion:)","title":"unregisterForTvPushNotifications(completion:)","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unregisterForTvPushNotifications"},{"kind":"text","text":"("},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"navigatorTitle":[{"kind":"identifier","text":"unregisterForTvPushNotificationsWithCompletion:"}],"abstract":[{"type":"text","text":"Unregisters the tvOS device from receiving push notifications."}],"url":"\/documentation\/pushwooshtvos\/pushwooshtvosimplementation\/unregisterfortvpushnotifications(completion:)","kind":"symbol","role":"symbol","type":"topic"},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS":{"abstract":[{"text":"Push notifications and Rich Media for tvOS apps.","type":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/pushwooshtvos","title":"PushwooshTVOS","identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS","role":"collection"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","value":"unregisterForTvPushNotificationsWithCompletion:","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"unregisterForTvPushNotificationsWithCompletion:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Configuration","identifiers":["doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/setAppCode(_:)","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/registerForTvPushNotifications()"],"generated":true}]},{"value":{"declarations":[{"platforms":["tvOS"],"tokens":[{"kind":"text","text":"+ ("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"unregisterForTvPushNotificationsWithCompletion:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":" (^","kind":"text"},{"text":")(","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * "},{"kind":"internalParam","text":""},{"text":")) ","kind":"text"},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1registerForTvPushNotifications()\/title","value":"registerForTvPushNotifications","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1registerForTvPushNotifications()\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"registerForTvPushNotifications"}]},{"value":"setAppCode:","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1setAppCode(_:)\/title"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"setAppCode:"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1setAppCode(_:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1unregisterForTvPushNotifications(completion:)\/title","value":"unregisterForTvPushNotificationsWithCompletion:"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"unregisterForTvPushNotificationsWithCompletion:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1unregisterForTvPushNotifications(completion:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}