{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/postEvent(_:withAttributes:completion:)"},"metadata":{"roleHeading":"Instance Method","title":"postEvent(_:withAttributes:completion:)","symbolKind":"method","role":"symbol","modules":[{"name":"PushwooshFramework"}],"navigatorTitle":[{"text":"postEvent:withAttributes:completion:","kind":"identifier"}],"platforms":[],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"postEvent"},{"kind":"text","text":"("},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"!, ","kind":"text"},{"text":"withAttributes","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]!, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (((any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")!)"}],"externalID":"c:objc(cs)PushNotificationManager(im)postEvent:withAttributes:completion:"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"postEvent"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"event","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"!, ","kind":"text"},{"kind":"externalParam","text":"withAttributes"},{"text":" ","kind":"text"},{"text":"attributes","kind":"internalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"]! = [:], ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (((any "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":")?) -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")!)","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"event","content":[{"inlineContent":[{"type":"text","text":"name of the event"}],"type":"paragraph"}]},{"name":"attributes","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"NSDictionary of event attributes"}]}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"text":"function to call after posting event","type":"text"}]}]}]},{"kind":"content","content":[{"anchor":"discussion","text":"Discussion","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Example:"}]},{"inlineContent":[{"type":"text","text":"[[PushNotificationManager pushManager] setUserId:@“96da2f590cd7246bbde0051047b0d6f7”];"},{"type":"text","text":" "},{"type":"text","text":"[[PushNotificationManager pushManager] postEvent:@“buttonPressed” withAttributes:@{ @“buttonNumber” : @“4”, @“buttonLabel” : @“Banner” } completion:nil];"}],"type":"paragraph"},{"inlineContent":[{"text":"Deprecated. Use PWInAppManager postEvent method instead","type":"text"}],"type":"paragraph"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pushnotificationmanager\/postevent(_:withattributes:completion:)"]},{"paths":["\/documentation\/pushwooshframework\/pushnotificationmanager\/postevent(_:withattributes:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Post events for In-App Messages. This can trigger In-App message display as specified in Pushwoosh Control Panel."}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"type":"topic","role":"collection","title":"PushwooshFramework","abstract":[{"type":"text","text":"Push notification SDK for iOS applications."}],"url":"\/documentation\/pushwooshframework","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationManager/postEvent(_:withAttributes:completion:)":{"deprecated":true,"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/postEvent(_:withAttributes:completion:)","type":"topic","url":"\/documentation\/pushwooshframework\/pushnotificationmanager\/postevent(_:withattributes:completion:)","abstract":[{"type":"text","text":"Post events for In-App Messages. This can trigger In-App message display as specified in Pushwoosh Control Panel."}],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"postEvent"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"!, "},{"text":"withAttributes","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]!, "},{"text":"completion","kind":"externalParam"},{"text":": (((any ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":")?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")!)"}],"navigatorTitle":[{"text":"postEvent:withAttributes:completion:","kind":"identifier"}],"title":"postEvent(_:withAttributes:completion:)"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationManager":{"abstract":[{"type":"codeVoice","code":"PushNotificationManager"},{"text":" class offers access to the singleton-instance of the push manager responsible for registering the device with the APS servers, receiving and processing push notifications.","type":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager","kind":"symbol","title":"PushNotificationManager","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PushNotificationManager","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/pushwooshframework\/pushnotificationmanager","navigatorTitle":[{"text":"PushNotificationManager","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","value":"postEvent:withAttributes:completion:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"postEvent:withAttributes:completion:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"postEvent:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"event"},{"text":" ","kind":"text"},{"kind":"identifier","text":"withAttributes:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDictionary","text":"NSDictionary"},{"text":" *) ","kind":"text"},{"text":"attributes","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"completion:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":" (^"},{"text":")(","kind":"text"},{"text":"NSError","preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"error","kind":"internalParam"},{"kind":"text","text":")) "},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"postEvent:withAttributes:completion:","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1postEvent(_:withAttributes:completion:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1postEvent(_:withAttributes:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"postEvent:withAttributes:completion:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager\/title","value":"PushNotificationManager","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager\/fragments","value":[{"kind":"identifier","text":"PushNotificationManager"}]}]}]}