{"sections":[],"hierarchy":{"paths":[[]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshForegroundPush\/documentation\/PushwooshForegroundPush","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Customizable foreground push notifications for iOS applications."}],"topicSections":[{"title":"Getting Started","identifiers":["doc:\/\/com.pushwoosh.PushwooshForegroundPush\/documentation\/PushwooshForegroundPush\/GettingStarted","doc:\/\/com.pushwoosh.PushwooshForegroundPush\/documentation\/PushwooshForegroundPush\/Examples"]},{"title":"Classes","identifiers":["doc:\/\/com.pushwoosh.PushwooshForegroundPush\/documentation\/PushwooshForegroundPush\/ForegroundPushConfiguration","doc:\/\/com.pushwoosh.PushwooshForegroundPush\/documentation\/PushwooshForegroundPush\/PushwooshForegroundPushImplementation"]},{"identifiers":["doc:\/\/com.pushwoosh.PushwooshForegroundPush\/documentation\/PushwooshForegroundPush\/PWForegroundPushDelegate"],"title":"Protocols"},{"identifiers":["doc:\/\/com.pushwoosh.PushwooshForegroundPush\/documentation\/PushwooshForegroundPush\/PushwooshBridge"],"title":"Extended Modules"}],"primaryContentSections":[{"content":[{"level":2,"text":"Overview","type":"heading","anchor":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Starting from version 6.10.0, PushwooshForegroundPush enables customization of foreground push notifications when native iOS system alerts are disabled. This module creates animated push banners that appear at the top of your app with rich visual effects, haptic feedback, and interactive capabilities."}]},{"type":"paragraph","inlineContent":[{"text":"The module offers extensive customization options including gradient backgrounds, custom colors and fonts, multiple animation styles, and modern iOS 26+ Liquid Glass effects.","type":"text"}]}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshforegroundpush"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshforegroundpush"]}],"kind":"symbol","metadata":{"roleHeading":"Framework","modules":[{"name":"PushwooshForegroundPush"}],"role":"collection","externalID":"PushwooshForegroundPush","title":"PushwooshForegroundPush","symbolKind":"module"},"references":{"doc://com.pushwoosh.PushwooshForegroundPush/documentation/PushwooshForegroundPush/PushwooshForegroundPushImplementation":{"kind":"symbol","role":"symbol","title":"PushwooshForegroundPushImplementation","url":"\/documentation\/pushwooshforegroundpush\/pushwooshforegroundpushimplementation","identifier":"doc:\/\/com.pushwoosh.PushwooshForegroundPush\/documentation\/PushwooshForegroundPush\/PushwooshForegroundPushImplementation","type":"topic","abstract":[{"text":"Main implementation class that manages foreground push notifications display and configuration.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PushwooshForegroundPushImplementation"}],"navigatorTitle":[{"text":"PushwooshForegroundPushImplementation","kind":"identifier"}]},"doc://com.pushwoosh.PushwooshForegroundPush/documentation/PushwooshForegroundPush/GettingStarted":{"kind":"article","role":"article","type":"topic","title":"Getting Started","abstract":[{"text":"Customize foreground push notifications when native iOS system alerts are disabled.","type":"text"}],"url":"\/documentation\/pushwooshforegroundpush\/gettingstarted","identifier":"doc:\/\/com.pushwoosh.PushwooshForegroundPush\/documentation\/PushwooshForegroundPush\/GettingStarted"},"doc://com.pushwoosh.PushwooshForegroundPush/documentation/PushwooshForegroundPush":{"title":"PushwooshForegroundPush","kind":"symbol","role":"collection","identifier":"doc:\/\/com.pushwoosh.PushwooshForegroundPush\/documentation\/PushwooshForegroundPush","url":"\/documentation\/pushwooshforegroundpush","type":"topic","abstract":[{"text":"Customizable foreground push notifications for iOS applications.","type":"text"}]},"doc://com.pushwoosh.PushwooshForegroundPush/documentation/PushwooshForegroundPush/PushwooshForegroundPushVersionString":{"kind":"symbol","role":"symbol","type":"topic","title":"PushwooshForegroundPushVersionString","abstract":[{"text":"Project version string for PushwooshForegroundPush.","type":"text"}],"url":"\/documentation\/pushwooshforegroundpush\/pushwooshforegroundpushversionstring","identifier":"doc:\/\/com.pushwoosh.PushwooshForegroundPush\/documentation\/PushwooshForegroundPush\/PushwooshForegroundPushVersionString","fragments":[{"text":"PushwooshForegroundPushVersionString","kind":"identifier"}]},"doc://com.pushwoosh.PushwooshForegroundPush/documentation/PushwooshForegroundPush/PushwooshForegroundPushVersionNumber":{"kind":"symbol","role":"symbol","type":"topic","title":"PushwooshForegroundPushVersionNumber","abstract":[{"type":"text","text":"Project version number for PushwooshForegroundPush."}],"url":"\/documentation\/pushwooshforegroundpush\/pushwooshforegroundpushversionnumber","identifier":"doc:\/\/com.pushwoosh.PushwooshForegroundPush\/documentation\/PushwooshForegroundPush\/PushwooshForegroundPushVersionNumber","fragments":[{"text":"PushwooshForegroundPushVersionNumber","kind":"identifier"}]},"doc://com.pushwoosh.PushwooshForegroundPush/documentation/PushwooshForegroundPush/Examples":{"title":"Code Examples","role":"article","kind":"article","url":"\/documentation\/pushwooshforegroundpush\/examples","abstract":[{"text":"Practical examples for common foreground push notification scenarios.","type":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshForegroundPush\/documentation\/PushwooshForegroundPush\/Examples","type":"topic"},"doc://com.pushwoosh.PushwooshForegroundPush/documentation/PushwooshForegroundPush/PWForegroundPushDelegate":{"navigatorTitle":[{"text":"PWForegroundPushDelegate","kind":"identifier"}],"title":"PWForegroundPushDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"PWForegroundPushDelegate","kind":"identifier"}],"role":"symbol","kind":"symbol","url":"\/documentation\/pushwooshforegroundpush\/pwforegroundpushdelegate","abstract":[{"text":"Delegate protocol for receiving foreground push events.","type":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshForegroundPush\/documentation\/PushwooshForegroundPush\/PWForegroundPushDelegate","type":"topic"},"doc://com.pushwoosh.PushwooshForegroundPush/documentation/PushwooshForegroundPush/PushwooshBridge":{"identifier":"doc:\/\/com.pushwoosh.PushwooshForegroundPush\/documentation\/PushwooshForegroundPush\/PushwooshBridge","role":"collection","abstract":[],"type":"topic","url":"\/documentation\/pushwooshforegroundpush\/pushwooshbridge","kind":"symbol","title":"PushwooshBridge"},"doc://com.pushwoosh.PushwooshForegroundPush/documentation/PushwooshForegroundPush/ForegroundPushConfiguration":{"kind":"symbol","role":"symbol","type":"topic","title":"ForegroundPushConfiguration","navigatorTitle":[{"text":"ForegroundPushConfiguration","kind":"identifier"}],"abstract":[{"text":"Configuration object containing all visual and behavioral settings for foreground pushes.","type":"text"}],"url":"\/documentation\/pushwooshforegroundpush\/foregroundpushconfiguration","identifier":"doc:\/\/com.pushwoosh.PushwooshForegroundPush\/documentation\/PushwooshForegroundPush\/ForegroundPushConfiguration","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ForegroundPushConfiguration"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":[{"title":"Getting Started","identifiers":["doc:\/\/com.pushwoosh.PushwooshForegroundPush\/documentation\/PushwooshForegroundPush\/GettingStarted","doc:\/\/com.pushwoosh.PushwooshForegroundPush\/documentation\/PushwooshForegroundPush\/Examples"]},{"title":"Variables","identifiers":["doc:\/\/com.pushwoosh.PushwooshForegroundPush\/documentation\/PushwooshForegroundPush\/PushwooshForegroundPushVersionNumber","doc:\/\/com.pushwoosh.PushwooshForegroundPush\/documentation\/PushwooshForegroundPush\/PushwooshForegroundPushVersionString"]}],"op":"replace","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"}],"traits":[{"interfaceLanguage":"occ"}]}]}