{"kind":"symbol","abstract":[{"text":"Sends push-to-start token to enable remote activity initiation with completion handler.","type":"text"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities","doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/PushwooshLiveActivitiesImplementationSetup"]]},"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/PushwooshLiveActivitiesImplementationSetup\/sendPushToStartLiveActivity(token:completion:)-3mmnt","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"sendPushToStartLiveActivity","kind":"identifier"},{"text":"(","kind":"text"},{"text":"token","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"attribute","text":"@escaping"},{"text":" (((","kind":"text"},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":")?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"token","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The push-to-start token from ActivityKit."}]}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Completion handler called when the request finishes."}]}]}]}],"metadata":{"symbolKind":"method","title":"sendPushToStartLiveActivity(token:completion:)","externalID":"c:@M@PushwooshLiveActivities@objc(cs)PushwooshLiveActivitiesImplementationSetup(cm)sendPushToStartLiveActivityWithToken:completion:","roleHeading":"Type Method","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendPushToStartLiveActivity"},{"kind":"text","text":"("},{"kind":"externalParam","text":"token"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": (((","kind":"text"},{"kind":"keyword","text":"any"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"text":")?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":"))","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"sendPushToStartLiveActivityWithToken:completion:"}],"modules":[{"name":"PushwooshLiveActivities"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshliveactivities\/pushwooshliveactivitiesimplementationsetup\/sendpushtostartliveactivity(token:completion:)-3mmnt"]},{"paths":["\/documentation\/pushwooshliveactivities\/pushwooshliveactivitiesimplementationsetup\/sendpushtostartliveactivity(token:completion:)-3mmnt"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.pushwoosh.PushwooshLiveActivities/documentation/PushwooshLiveActivities/PushwooshLiveActivitiesImplementationSetup/sendPushToStartLiveActivity(token:completion:)-3mmnt":{"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/PushwooshLiveActivitiesImplementationSetup\/sendPushToStartLiveActivity(token:completion:)-3mmnt","role":"symbol","url":"\/documentation\/pushwooshliveactivities\/pushwooshliveactivitiesimplementationsetup\/sendpushtostartliveactivity(token:completion:)-3mmnt","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sendPushToStartLiveActivity","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"token"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ((("},{"text":"any","kind":"keyword"},{"kind":"text","text":" "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"text":")?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":"))"}],"title":"sendPushToStartLiveActivity(token:completion:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"sendPushToStartLiveActivityWithToken:completion:"}],"abstract":[{"text":"Sends push-to-start token to enable remote activity initiation with completion handler.","type":"text"}]},"doc://com.pushwoosh.PushwooshLiveActivities/documentation/PushwooshLiveActivities":{"role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/pushwooshliveactivities","abstract":[{"type":"text","text":"Real-time iOS Live Activities powered by push notifications."}],"title":"PushwooshLiveActivities","identifier":"doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities"},"doc://com.pushwoosh.PushwooshLiveActivities/documentation/PushwooshLiveActivities/PushwooshLiveActivitiesImplementationSetup":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushwooshLiveActivitiesImplementationSetup"}],"title":"PushwooshLiveActivitiesImplementationSetup","role":"symbol","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/PushwooshLiveActivitiesImplementationSetup","kind":"symbol","url":"\/documentation\/pushwooshliveactivities\/pushwooshliveactivitiesimplementationsetup","navigatorTitle":[{"text":"PushwooshLiveActivitiesImplementationSetup","kind":"identifier"}],"abstract":[{"type":"text","text":"Orchestrates iOS Live Activities integration with Pushwoosh push notifications."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"value":"sendPushToStartLiveActivityWithToken:completion:","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"sendPushToStartLiveActivityWithToken:completion:"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"sendPushToStartLiveActivityWithToken:"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"token"},{"text":" ","kind":"text"},{"text":"completion:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":" (^","kind":"text"},{"kind":"text","text":")("},{"text":"NSError","preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"kind":"text","text":")) "},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"sendPushToStartLiveActivityWithToken:completion:","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshLiveActivities~1documentation~1PushwooshLiveActivities~1PushwooshLiveActivitiesImplementationSetup~1sendPushToStartLiveActivity(token:completion:)-3mmnt\/title"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"sendPushToStartLiveActivityWithToken:completion:"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshLiveActivities~1documentation~1PushwooshLiveActivities~1PushwooshLiveActivitiesImplementationSetup~1sendPushToStartLiveActivity(token:completion:)-3mmnt\/fragments"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshLiveActivities~1documentation~1PushwooshLiveActivities~1PushwooshLiveActivitiesImplementationSetup\/title","value":"PushwooshLiveActivitiesImplementationSetup","op":"replace"},{"value":[{"text":"PushwooshLiveActivitiesImplementationSetup","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshLiveActivities~1documentation~1PushwooshLiveActivities~1PushwooshLiveActivitiesImplementationSetup\/fragments","op":"replace"}]}]}