{"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/PushwooshLiveActivitiesImplementationSetup\/sendPushToStartLiveActivity(token:)-1pumn","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities","doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/PushwooshLiveActivitiesImplementationSetup"]]},"metadata":{"modules":[{"name":"PushwooshLiveActivities"}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"sendPushToStartLiveActivity","kind":"identifier"},{"kind":"text","text":"("},{"text":"token","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"externalID":"c:@M@PushwooshLiveActivities@objc(cs)PushwooshLiveActivitiesImplementationSetup(cm)sendPushToStartLiveActivityWithToken:","title":"sendPushToStartLiveActivity(token:)","navigatorTitle":[{"kind":"identifier","text":"sendPushToStartLiveActivityWithToken:"}],"symbolKind":"method","roleHeading":"Type Method","role":"symbol"},"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"Sends push-to-start token to enable remote activity initiation."}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"sendPushToStartLiveActivity","kind":"identifier"},{"text":"(","kind":"text"},{"text":"token","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"token","content":[{"type":"paragraph","inlineContent":[{"text":"The push-to-start token from ActivityKit.","type":"text"}]}]}]}],"variants":[{"paths":["\/documentation\/pushwooshliveactivities\/pushwooshliveactivitiesimplementationsetup\/sendpushtostartliveactivity(token:)-1pumn"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pushwooshliveactivities\/pushwooshliveactivitiesimplementationsetup\/sendpushtostartliveactivity(token:)-1pumn"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.pushwoosh.PushwooshLiveActivities/documentation/PushwooshLiveActivities/PushwooshLiveActivitiesImplementationSetup":{"navigatorTitle":[{"kind":"identifier","text":"PushwooshLiveActivitiesImplementationSetup"}],"abstract":[{"text":"Orchestrates iOS Live Activities integration with Pushwoosh push notifications.","type":"text"}],"kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PushwooshLiveActivitiesImplementationSetup","kind":"identifier"}],"title":"PushwooshLiveActivitiesImplementationSetup","identifier":"doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/PushwooshLiveActivitiesImplementationSetup","url":"\/documentation\/pushwooshliveactivities\/pushwooshliveactivitiesimplementationsetup","role":"symbol"},"doc://com.pushwoosh.PushwooshLiveActivities/documentation/PushwooshLiveActivities/PushwooshLiveActivitiesImplementationSetup/sendPushToStartLiveActivity(token:)-1pumn":{"kind":"symbol","type":"topic","url":"\/documentation\/pushwooshliveactivities\/pushwooshliveactivitiesimplementationsetup\/sendpushtostartliveactivity(token:)-1pumn","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sendPushToStartLiveActivity","kind":"identifier"},{"kind":"text","text":"("},{"text":"token","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/PushwooshLiveActivitiesImplementationSetup\/sendPushToStartLiveActivity(token:)-1pumn","navigatorTitle":[{"text":"sendPushToStartLiveActivityWithToken:","kind":"identifier"}],"abstract":[{"text":"Sends push-to-start token to enable remote activity initiation.","type":"text"}],"title":"sendPushToStartLiveActivity(token:)"},"doc://com.pushwoosh.PushwooshLiveActivities/documentation/PushwooshLiveActivities":{"type":"topic","title":"PushwooshLiveActivities","url":"\/documentation\/pushwooshliveactivities","kind":"symbol","abstract":[{"text":"Real-time iOS Live Activities powered by push notifications.","type":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"value":"sendPushToStartLiveActivityWithToken:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"text":"sendPushToStartLiveActivityWithToken:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"sendPushToStartLiveActivityWithToken:"},{"kind":"text","text":"("},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"token","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshLiveActivities~1documentation~1PushwooshLiveActivities~1PushwooshLiveActivitiesImplementationSetup\/title","value":"PushwooshLiveActivitiesImplementationSetup"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshLiveActivities~1documentation~1PushwooshLiveActivities~1PushwooshLiveActivitiesImplementationSetup\/fragments","value":[{"kind":"identifier","text":"PushwooshLiveActivitiesImplementationSetup"}]},{"op":"replace","value":"sendPushToStartLiveActivityWithToken:","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshLiveActivities~1documentation~1PushwooshLiveActivities~1PushwooshLiveActivitiesImplementationSetup~1sendPushToStartLiveActivity(token:)-1pumn\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshLiveActivities~1documentation~1PushwooshLiveActivities~1PushwooshLiveActivitiesImplementationSetup~1sendPushToStartLiveActivity(token:)-1pumn\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"sendPushToStartLiveActivityWithToken:","kind":"identifier"}]}]}]}