{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshliveactivities\/pushwooshliveactivitiesimplementationsetup\/stopliveactivity(activityid:)-96xj3"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshliveactivities\/pushwooshliveactivitiesimplementationsetup\/stopliveactivity(activityid:)-96xj3"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/PushwooshLiveActivitiesImplementationSetup\/stopLiveActivity(activityId:)-96xj3"},"kind":"symbol","metadata":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"stopLiveActivity"},{"text":"(","kind":"text"},{"text":"activityId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"stopLiveActivity(activityId:)","externalID":"c:@M@PushwooshLiveActivities@objc(cs)PushwooshLiveActivitiesImplementationSetup(cm)stopLiveActivityWithActivityId:","roleHeading":"Type Method","navigatorTitle":[{"kind":"identifier","text":"stopLiveActivityWithActivityId:"}],"modules":[{"name":"PushwooshLiveActivities"}],"role":"symbol","symbolKind":"method"},"abstract":[{"type":"text","text":"Notifies the server that a specific Live Activity has ended."}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities","doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/PushwooshLiveActivitiesImplementationSetup"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"stopLiveActivity"},{"text":"(","kind":"text"},{"text":"activityId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"activityId","content":[{"inlineContent":[{"type":"text","text":"The unique identifier of the activity that ended."}],"type":"paragraph"}]}]}],"references":{"doc://com.pushwoosh.PushwooshLiveActivities/documentation/PushwooshLiveActivities":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities","role":"collection","abstract":[{"type":"text","text":"Real-time iOS Live Activities powered by push notifications."}],"url":"\/documentation\/pushwooshliveactivities","title":"PushwooshLiveActivities"},"doc://com.pushwoosh.PushwooshLiveActivities/documentation/PushwooshLiveActivities/PushwooshLiveActivitiesImplementationSetup/stopLiveActivity(activityId:)-96xj3":{"title":"stopLiveActivity(activityId:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"stopLiveActivity","kind":"identifier"},{"kind":"text","text":"("},{"text":"activityId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"role":"symbol","url":"\/documentation\/pushwooshliveactivities\/pushwooshliveactivitiesimplementationsetup\/stopliveactivity(activityid:)-96xj3","identifier":"doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/PushwooshLiveActivitiesImplementationSetup\/stopLiveActivity(activityId:)-96xj3","type":"topic","kind":"symbol","abstract":[{"text":"Notifies the server that a specific Live Activity has ended.","type":"text"}],"navigatorTitle":[{"text":"stopLiveActivityWithActivityId:","kind":"identifier"}]},"doc://com.pushwoosh.PushwooshLiveActivities/documentation/PushwooshLiveActivities/PushwooshLiveActivitiesImplementationSetup":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/PushwooshLiveActivitiesImplementationSetup","role":"symbol","abstract":[{"type":"text","text":"Orchestrates iOS Live Activities integration with Pushwoosh push notifications."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PushwooshLiveActivitiesImplementationSetup"}],"url":"\/documentation\/pushwooshliveactivities\/pushwooshliveactivitiesimplementationsetup","navigatorTitle":[{"kind":"identifier","text":"PushwooshLiveActivitiesImplementationSetup"}],"title":"PushwooshLiveActivitiesImplementationSetup"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Type Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"stopLiveActivityWithActivityId:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"text":"stopLiveActivityWithActivityId:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"stopLiveActivityWithActivityId:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"activityId","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"value":"stopLiveActivityWithActivityId:","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshLiveActivities~1documentation~1PushwooshLiveActivities~1PushwooshLiveActivitiesImplementationSetup~1stopLiveActivity(activityId:)-96xj3\/title"},{"value":[{"text":"+ ","kind":"text"},{"text":"stopLiveActivityWithActivityId:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshLiveActivities~1documentation~1PushwooshLiveActivities~1PushwooshLiveActivitiesImplementationSetup~1stopLiveActivity(activityId:)-96xj3\/fragments"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshLiveActivities~1documentation~1PushwooshLiveActivities~1PushwooshLiveActivitiesImplementationSetup\/title","op":"replace","value":"PushwooshLiveActivitiesImplementationSetup"},{"value":[{"kind":"identifier","text":"PushwooshLiveActivitiesImplementationSetup"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshLiveActivities~1documentation~1PushwooshLiveActivities~1PushwooshLiveActivitiesImplementationSetup\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}