{"metadata":{"roleHeading":"Type Method","title":"stopLiveActivity()","externalID":"c:@M@PushwooshLiveActivities@objc(cs)PushwooshLiveActivitiesImplementationSetup(cm)stopLiveActivity","symbolKind":"method","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"stopLiveActivity","kind":"identifier"},{"text":"()","kind":"text"}],"modules":[{"name":"PushwooshLiveActivities"}],"navigatorTitle":[{"text":"stopLiveActivity","kind":"identifier"}]},"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"Notifies the server that all Live Activities have ended."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshliveactivities\/pushwooshliveactivitiesimplementationsetup\/stopliveactivity()-7riam"]},{"paths":["\/documentation\/pushwooshliveactivities\/pushwooshliveactivitiesimplementationsetup\/stopliveactivity()-7riam"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/PushwooshLiveActivitiesImplementationSetup\/stopLiveActivity()-7riam"},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities","doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/PushwooshLiveActivitiesImplementationSetup"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stopLiveActivity","kind":"identifier"},{"kind":"text","text":"()"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.pushwoosh.PushwooshLiveActivities/documentation/PushwooshLiveActivities/PushwooshLiveActivitiesImplementationSetup":{"title":"PushwooshLiveActivitiesImplementationSetup","identifier":"doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/PushwooshLiveActivitiesImplementationSetup","role":"symbol","type":"topic","navigatorTitle":[{"text":"PushwooshLiveActivitiesImplementationSetup","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PushwooshLiveActivitiesImplementationSetup","kind":"identifier"}],"url":"\/documentation\/pushwooshliveactivities\/pushwooshliveactivitiesimplementationsetup","kind":"symbol","abstract":[{"type":"text","text":"Orchestrates iOS Live Activities integration with Pushwoosh push notifications."}]},"doc://com.pushwoosh.PushwooshLiveActivities/documentation/PushwooshLiveActivities":{"url":"\/documentation\/pushwooshliveactivities","title":"PushwooshLiveActivities","kind":"symbol","abstract":[{"type":"text","text":"Real-time iOS Live Activities powered by push notifications."}],"identifier":"doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities","role":"collection","type":"topic"},"doc://com.pushwoosh.PushwooshLiveActivities/documentation/PushwooshLiveActivities/PushwooshLiveActivitiesImplementationSetup/stopLiveActivity()-7riam":{"kind":"symbol","role":"symbol","title":"stopLiveActivity()","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"stopLiveActivity"},{"text":"()","kind":"text"}],"abstract":[{"type":"text","text":"Notifies the server that all Live Activities have ended."}],"navigatorTitle":[{"kind":"identifier","text":"stopLiveActivity"}],"url":"\/documentation\/pushwooshliveactivities\/pushwooshliveactivitiesimplementationsetup\/stopliveactivity()-7riam","identifier":"doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/PushwooshLiveActivitiesImplementationSetup\/stopLiveActivity()-7riam","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"stopLiveActivity","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"stopLiveActivity"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"text":"stopLiveActivity","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"PushwooshLiveActivitiesImplementationSetup","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshLiveActivities~1documentation~1PushwooshLiveActivities~1PushwooshLiveActivitiesImplementationSetup\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshLiveActivities~1documentation~1PushwooshLiveActivities~1PushwooshLiveActivitiesImplementationSetup\/fragments","value":[{"text":"PushwooshLiveActivitiesImplementationSetup","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshLiveActivities~1documentation~1PushwooshLiveActivities~1PushwooshLiveActivitiesImplementationSetup~1stopLiveActivity()-7riam\/title","value":"stopLiveActivity"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshLiveActivities~1documentation~1PushwooshLiveActivities~1PushwooshLiveActivitiesImplementationSetup~1stopLiveActivity()-7riam\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"stopLiveActivity"}]}]}]}