{"kind":"symbol","identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/PushwooshLiveActivitiesImplementationSetup\/stopLiveActivity(completion:)-83ur3","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"stopLiveActivityWithCompletion:"}],"title":"stopLiveActivity(completion:)","symbolKind":"method","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"stopLiveActivity"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"text":")?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"role":"symbol","externalID":"c:@M@PushwooshLiveActivities@objc(cs)PushwooshLiveActivitiesImplementationSetup(cm)stopLiveActivityWithCompletion:","modules":[{"name":"PushwooshLiveActivities"}],"roleHeading":"Type Method"},"abstract":[{"text":"Notifies the server that all Live Activities have ended with completion handler.","type":"text"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities","doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/PushwooshLiveActivitiesImplementationSetup"]]},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stopLiveActivity","kind":"identifier"},{"kind":"text","text":"("},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" ((","kind":"text"},{"text":"any","kind":"keyword"},{"kind":"text","text":" "},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":")?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"text":"Completion handler called when the request finishes.","type":"text"}]}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshliveactivities\/pushwooshliveactivitiesimplementationsetup\/stopliveactivity(completion:)-83ur3"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshliveactivities\/pushwooshliveactivitiesimplementationsetup\/stopliveactivity(completion:)-83ur3"]}],"references":{"doc://com.pushwoosh.PushwooshLiveActivities/documentation/PushwooshLiveActivities/PushwooshLiveActivitiesImplementationSetup/stopLiveActivity(completion:)-83ur3":{"abstract":[{"type":"text","text":"Notifies the server that all Live Activities have ended with completion handler."}],"url":"\/documentation\/pushwooshliveactivities\/pushwooshliveactivitiesimplementationsetup\/stopliveactivity(completion:)-83ur3","kind":"symbol","navigatorTitle":[{"text":"stopLiveActivityWithCompletion:","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/PushwooshLiveActivitiesImplementationSetup\/stopLiveActivity(completion:)-83ur3","title":"stopLiveActivity(completion:)","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopLiveActivity"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"text":": ((","kind":"text"},{"kind":"keyword","text":"any"},{"kind":"text","text":" "},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":")?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"kind":"text","text":")"}],"role":"symbol","type":"topic"},"doc://com.pushwoosh.PushwooshLiveActivities/documentation/PushwooshLiveActivities/PushwooshLiveActivitiesImplementationSetup":{"identifier":"doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/PushwooshLiveActivitiesImplementationSetup","type":"topic","abstract":[{"text":"Orchestrates iOS Live Activities integration with Pushwoosh push notifications.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PushwooshLiveActivitiesImplementationSetup","kind":"identifier"}],"title":"PushwooshLiveActivitiesImplementationSetup","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PushwooshLiveActivitiesImplementationSetup"}],"url":"\/documentation\/pushwooshliveactivities\/pushwooshliveactivitiesimplementationsetup"},"doc://com.pushwoosh.PushwooshLiveActivities/documentation/PushwooshLiveActivities":{"role":"collection","identifier":"doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities","kind":"symbol","url":"\/documentation\/pushwooshliveactivities","abstract":[{"type":"text","text":"Real-time iOS Live Activities powered by push notifications."}],"type":"topic","title":"PushwooshLiveActivities"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"path":"\/metadata\/title","value":"stopLiveActivityWithCompletion:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"stopLiveActivityWithCompletion:"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"stopLiveActivityWithCompletion:"},{"kind":"text","text":"("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":" (^","kind":"text"},{"text":")(","kind":"text"},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"text":" * ","kind":"text"},{"kind":"internalParam","text":""},{"text":")) ","kind":"text"},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshLiveActivities~1documentation~1PushwooshLiveActivities~1PushwooshLiveActivitiesImplementationSetup~1stopLiveActivity(completion:)-83ur3\/title","value":"stopLiveActivityWithCompletion:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshLiveActivities~1documentation~1PushwooshLiveActivities~1PushwooshLiveActivitiesImplementationSetup~1stopLiveActivity(completion:)-83ur3\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"stopLiveActivityWithCompletion:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshLiveActivities~1documentation~1PushwooshLiveActivities~1PushwooshLiveActivitiesImplementationSetup\/title","value":"PushwooshLiveActivitiesImplementationSetup"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshLiveActivities~1documentation~1PushwooshLiveActivities~1PushwooshLiveActivitiesImplementationSetup\/fragments","value":[{"kind":"identifier","text":"PushwooshLiveActivitiesImplementationSetup"}],"op":"replace"}]}]}