{"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"stopLiveActivity"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"activityId"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" ((","kind":"text"},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":")?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The unique identifier of the activity that ended."}]}],"name":"activityId"},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Completion handler called when the request finishes."}]}]}],"kind":"parameters"}],"kind":"symbol","metadata":{"modules":[{"name":"PushwooshLiveActivities"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"stopLiveActivityWithActivityId:completion:"}],"symbolKind":"method","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopLiveActivity"},{"text":"(","kind":"text"},{"text":"activityId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":")?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"externalID":"c:@M@PushwooshLiveActivities@objc(cs)PushwooshLiveActivitiesImplementationSetup(cm)stopLiveActivityWithActivityId:completion:","title":"stopLiveActivity(activityId:completion:)","roleHeading":"Type Method"},"abstract":[{"type":"text","text":"Notifies the server that a specific Live Activity has ended with completion handler."}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities","doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/PushwooshLiveActivitiesImplementationSetup"]]},"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/PushwooshLiveActivitiesImplementationSetup\/stopLiveActivity(activityId:completion:)-85he3","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/pushwooshliveactivities\/pushwooshliveactivitiesimplementationsetup\/stopliveactivity(activityid:completion:)-85he3"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshliveactivities\/pushwooshliveactivitiesimplementationsetup\/stopliveactivity(activityid:completion:)-85he3"]}],"references":{"doc://com.pushwoosh.PushwooshLiveActivities/documentation/PushwooshLiveActivities/PushwooshLiveActivitiesImplementationSetup":{"title":"PushwooshLiveActivitiesImplementationSetup","role":"symbol","navigatorTitle":[{"text":"PushwooshLiveActivitiesImplementationSetup","kind":"identifier"}],"type":"topic","url":"\/documentation\/pushwooshliveactivities\/pushwooshliveactivitiesimplementationsetup","abstract":[{"text":"Orchestrates iOS Live Activities integration with Pushwoosh push notifications.","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PushwooshLiveActivitiesImplementationSetup","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/PushwooshLiveActivitiesImplementationSetup"},"doc://com.pushwoosh.PushwooshLiveActivities/documentation/PushwooshLiveActivities":{"url":"\/documentation\/pushwooshliveactivities","abstract":[{"text":"Real-time iOS Live Activities powered by push notifications.","type":"text"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities","type":"topic","title":"PushwooshLiveActivities"},"doc://com.pushwoosh.PushwooshLiveActivities/documentation/PushwooshLiveActivities/PushwooshLiveActivitiesImplementationSetup/stopLiveActivity(activityId:completion:)-85he3":{"url":"\/documentation\/pushwooshliveactivities\/pushwooshliveactivitiesimplementationsetup\/stopliveactivity(activityid:completion:)-85he3","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"stopLiveActivity","kind":"identifier"},{"text":"(","kind":"text"},{"text":"activityId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (("},{"kind":"keyword","text":"any"},{"text":" ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":")?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"title":"stopLiveActivity(activityId:completion:)","abstract":[{"text":"Notifies the server that a specific Live Activity has ended with completion handler.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshLiveActivities\/documentation\/PushwooshLiveActivities\/PushwooshLiveActivitiesImplementationSetup\/stopLiveActivity(activityId:completion:)-85he3","navigatorTitle":[{"kind":"identifier","text":"stopLiveActivityWithActivityId:completion:"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"stopLiveActivityWithActivityId:completion:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"text":"stopLiveActivityWithActivityId:completion:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"stopLiveActivityWithActivityId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"text":"activityId","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"completion:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":" (^"},{"text":")(","kind":"text"},{"text":"NSError","preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"internalParam","text":""},{"kind":"text","text":")) "},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshLiveActivities~1documentation~1PushwooshLiveActivities~1PushwooshLiveActivitiesImplementationSetup\/title","value":"PushwooshLiveActivitiesImplementationSetup"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshLiveActivities~1documentation~1PushwooshLiveActivities~1PushwooshLiveActivitiesImplementationSetup\/fragments","value":[{"text":"PushwooshLiveActivitiesImplementationSetup","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshLiveActivities~1documentation~1PushwooshLiveActivities~1PushwooshLiveActivitiesImplementationSetup~1stopLiveActivity(activityId:completion:)-85he3\/title","value":"stopLiveActivityWithActivityId:completion:"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"stopLiveActivityWithActivityId:completion:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshLiveActivities~1documentation~1PushwooshLiveActivities~1PushwooshLiveActivitiesImplementationSetup~1stopLiveActivity(activityId:completion:)-85he3\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}