{"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/PushwooshGRPCImplementation\/isAvailable","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/pushwooshgrpc\/pushwooshgrpcimplementation\/isavailable"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshgrpc\/pushwooshgrpcimplementation\/isavailable"]}],"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"PWTransport.isAvailable"},{"text":".","type":"text"}],"sections":[],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"isAvailable"}],"title":"isAvailable","externalID":"c:@M@PushwooshGRPC@objc(cs)PushwooshGRPCImplementation(cpy)isAvailable","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isAvailable","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"symbolKind":"property","role":"symbol","modules":[{"name":"PushwooshGRPC"}],"roleHeading":"Type Property"},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC","doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/PushwooshGRPCImplementation"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"isAvailable","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"kind":"symbol","references":{"doc://com.pushwoosh.PushwooshGRPC/documentation/PushwooshGRPC":{"identifier":"doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC","url":"\/documentation\/pushwooshgrpc","role":"collection","title":"PushwooshGRPC","type":"topic","kind":"symbol","abstract":[]},"doc://com.pushwoosh.PushwooshGRPC/documentation/PushwooshGRPC/PushwooshGRPCImplementation":{"navigatorTitle":[{"kind":"identifier","text":"PushwooshGRPCImplementation"}],"kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/PushwooshGRPCImplementation","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PushwooshGRPCImplementation","kind":"identifier"}],"abstract":[],"url":"\/documentation\/pushwooshgrpc\/pushwooshgrpcimplementation","type":"topic","title":"PushwooshGRPCImplementation"},"doc://com.pushwoosh.PushwooshGRPC/documentation/PushwooshGRPC/PushwooshGRPCImplementation/isAvailable":{"title":"isAvailable","identifier":"doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/PushwooshGRPCImplementation\/isAvailable","type":"topic","url":"\/documentation\/pushwooshgrpc\/pushwooshgrpcimplementation\/isavailable","abstract":[],"navigatorTitle":[{"text":"isAvailable","kind":"identifier"}],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isAvailable"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Type Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"isAvailable","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"isAvailable"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isAvailable"},{"text":";","kind":"text"}]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshGRPC~1documentation~1PushwooshGRPC~1PushwooshGRPCImplementation\/title","value":"PushwooshGRPCImplementation"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshGRPC~1documentation~1PushwooshGRPC~1PushwooshGRPCImplementation\/fragments","value":[{"kind":"identifier","text":"PushwooshGRPCImplementation"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshGRPC~1documentation~1PushwooshGRPC~1PushwooshGRPCImplementation~1isAvailable\/title","value":"isAvailable"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshGRPC~1documentation~1PushwooshGRPC~1PushwooshGRPCImplementation~1isAvailable\/fragments","value":[{"text":"isAvailable","kind":"identifier"}]}]}]}