{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/PushwooshGRPCImplementation\/sendRequest(_:completion:)"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendRequest"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"request"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PWRequest","text":"PWRequest"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" (","kind":"text"},{"kind":"typeIdentifier","text":"NSDictionary","preciseIdentifier":"c:objc(cs)NSDictionary"},{"text":"?, ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"modules":[{"name":"PushwooshGRPC"}],"externalID":"c:@M@PushwooshGRPC@objc(cs)PushwooshGRPCImplementation(cm)sendRequest:completion:","roleHeading":"Type Method","role":"symbol","symbolKind":"method","navigatorTitle":[{"text":"sendRequest:completion:","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sendRequest","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)PWRequest","text":"PWRequest","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"NSDictionary","preciseIdentifier":"c:objc(cs)NSDictionary","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"sendRequest(_:completion:)"},"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"PWTransport.sendRequest(_:completion:)"},{"type":"text","text":"."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshgrpc\/pushwooshgrpcimplementation\/sendrequest(_:completion:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshgrpc\/pushwooshgrpcimplementation\/sendrequest(_:completion:)"]}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC","doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/PushwooshGRPCImplementation"]]},"sections":[],"references":{"doc://com.pushwoosh.PushwooshGRPC/documentation/PushwooshGRPC/PushwooshGRPCImplementation":{"identifier":"doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/PushwooshGRPCImplementation","abstract":[],"role":"symbol","url":"\/documentation\/pushwooshgrpc\/pushwooshgrpcimplementation","title":"PushwooshGRPCImplementation","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PushwooshGRPCImplementation"}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PushwooshGRPCImplementation"}]},"doc://com.pushwoosh.PushwooshGRPC/documentation/PushwooshGRPC/PushwooshGRPCImplementation/sendRequest(_:completion:)":{"role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/PushwooshGRPCImplementation\/sendRequest(_:completion:)","url":"\/documentation\/pushwooshgrpc\/pushwooshgrpcimplementation\/sendrequest(_:completion:)","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"sendRequest","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)PWRequest","text":"PWRequest","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"NSDictionary","preciseIdentifier":"c:objc(cs)NSDictionary","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"sendRequest:completion:","kind":"identifier"}],"type":"topic","abstract":[],"title":"sendRequest(_:completion:)"},"doc://com.pushwoosh.PushwooshGRPC/documentation/PushwooshGRPC":{"url":"\/documentation\/pushwooshgrpc","type":"topic","abstract":[],"role":"collection","identifier":"doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC","kind":"symbol","title":"PushwooshGRPC"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"sendRequest:completion:","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"sendRequest:completion:"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"sendRequest:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"PWRequest","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PWRequest"},{"kind":"text","text":" *) "},{"text":"request","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"completion:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":" (^","kind":"text"},{"text":")(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSDictionary","text":"NSDictionary","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"internalParam","text":""},{"text":", ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"text":" * ","kind":"text"},{"kind":"internalParam","text":""},{"text":")) ","kind":"text"},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshGRPC~1documentation~1PushwooshGRPC~1PushwooshGRPCImplementation\/title","value":"PushwooshGRPCImplementation","op":"replace"},{"value":[{"kind":"identifier","text":"PushwooshGRPCImplementation"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshGRPC~1documentation~1PushwooshGRPC~1PushwooshGRPCImplementation\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshGRPC~1documentation~1PushwooshGRPC~1PushwooshGRPCImplementation~1sendRequest(_:completion:)\/title","value":"sendRequest:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshGRPC~1documentation~1PushwooshGRPC~1PushwooshGRPCImplementation~1sendRequest(_:completion:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"sendRequest:completion:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}