{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC","doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/PushwooshGRPCImplementation"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/PushwooshGRPCImplementation\/supportsMethod(_:)"},"metadata":{"modules":[{"name":"PushwooshGRPC"}],"navigatorTitle":[{"text":"supportsMethod:","kind":"identifier"}],"role":"symbol","externalID":"c:@M@PushwooshGRPC@objc(cs)PushwooshGRPCImplementation(cm)supportsMethod:","title":"supportsMethod(_:)","symbolKind":"method","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"supportsMethod"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"roleHeading":"Type Method"},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"supportsMethod","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"methodName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]}]}],"abstract":[{"type":"text","text":"Inherited from "},{"code":"PWTransport.supportsMethod(_:)","type":"codeVoice"},{"type":"text","text":"."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshgrpc\/pushwooshgrpcimplementation\/supportsmethod(_:)"]},{"paths":["\/documentation\/pushwooshgrpc\/pushwooshgrpcimplementation\/supportsmethod(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.pushwoosh.PushwooshGRPC/documentation/PushwooshGRPC/PushwooshGRPCImplementation":{"role":"symbol","title":"PushwooshGRPCImplementation","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PushwooshGRPCImplementation"}],"url":"\/documentation\/pushwooshgrpc\/pushwooshgrpcimplementation","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PushwooshGRPCImplementation"}],"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/PushwooshGRPCImplementation"},"doc://com.pushwoosh.PushwooshGRPC/documentation/PushwooshGRPC/PushwooshGRPCImplementation/supportsMethod(_:)":{"url":"\/documentation\/pushwooshgrpc\/pushwooshgrpcimplementation\/supportsmethod(_:)","title":"supportsMethod(_:)","navigatorTitle":[{"text":"supportsMethod:","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/PushwooshGRPCImplementation\/supportsMethod(_:)","role":"symbol","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"supportsMethod","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]},"doc://com.pushwoosh.PushwooshGRPC/documentation/PushwooshGRPC":{"title":"PushwooshGRPC","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC","role":"collection","abstract":[],"url":"\/documentation\/pushwooshgrpc","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"supportsMethod:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"text":"supportsMethod:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"supportsMethod:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"methodName","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshGRPC~1documentation~1PushwooshGRPC~1PushwooshGRPCImplementation\/title","value":"PushwooshGRPCImplementation","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshGRPC~1documentation~1PushwooshGRPC~1PushwooshGRPCImplementation\/fragments","value":[{"kind":"identifier","text":"PushwooshGRPCImplementation"}]},{"value":"supportsMethod:","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshGRPC~1documentation~1PushwooshGRPC~1PushwooshGRPCImplementation~1supportsMethod(_:)\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshGRPC~1documentation~1PushwooshGRPC~1PushwooshGRPCImplementation~1supportsMethod(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"text":"supportsMethod:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}