{"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPHandleType\/generic","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshvoip\/pwvoiphandletype\/generic"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshvoip\/pwvoiphandletype\/generic"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"generic"}],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","type":"heading","level":2,"text":"Discussion"},{"inlineContent":[{"text":"Use this type for non-standard identifiers such as usernames, display names, or custom user IDs.","type":"text"},{"text":" ","type":"text"},{"text":"CallKit will display the value exactly as provided without any special formatting.","type":"text"}],"type":"paragraph"},{"content":[{"inlineContent":[{"type":"text","text":"This is the default type if "},{"type":"codeVoice","code":"handleType"},{"text":" is not specified in the VoIP push payload.","type":"text"}],"type":"paragraph"}],"type":"aside","name":"Note","style":"note"}]}],"kind":"symbol","sections":[],"metadata":{"roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"PWVoIPHandleTypeGeneric"}],"title":"PWVoIPHandleType.generic","role":"symbol","symbolKind":"case","modules":[{"name":"PushwooshVoIP"}],"externalID":"c:@M@PushwooshVoIP@E@PWVoIPHandleType@PWVoIPHandleTypeGeneric","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"generic","kind":"identifier"}]},"abstract":[{"type":"text","text":"Generic identifier like username or custom ID."}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPHandleType"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP":{"kind":"symbol","url":"\/documentation\/pushwooshvoip","title":"PushwooshVoIP","role":"collection","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP","abstract":[{"text":"VoIP push notifications with native call UI for iOS applications.","type":"text"}]},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPHandleType":{"identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPHandleType","url":"\/documentation\/pushwooshvoip\/pwvoiphandletype","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PWVoIPHandleType"}],"type":"topic","title":"PWVoIPHandleType","abstract":[{"text":"Display format for caller information in CallKit UI.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PWVoIPHandleType"}]},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPHandleType/generic":{"url":"\/documentation\/pushwooshvoip\/pwvoiphandletype\/generic","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPHandleType\/generic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"generic","kind":"identifier"}],"title":"PWVoIPHandleType.generic","type":"topic","abstract":[{"type":"text","text":"Generic identifier like username or custom ID."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PWVoIPHandleTypeGeneric"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"PWVoIPHandleTypeGeneric"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"kind":"identifier","text":"PWVoIPHandleTypeGeneric"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"PWVoIPHandleTypeGeneric","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"PWVoIPHandleType","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPHandleType\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPHandleType\/fragments","value":[{"kind":"identifier","text":"PWVoIPHandleType"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPHandleType~1generic\/title","value":"PWVoIPHandleTypeGeneric"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPHandleType~1generic\/fragments","value":[{"text":"PWVoIPHandleTypeGeneric","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}