{"metadata":{"navigatorTitle":[{"kind":"identifier","text":"PWVoIPHandleTypePhoneNumber"}],"roleHeading":"Case","title":"PWVoIPHandleType.phoneNumber","symbolKind":"case","role":"symbol","externalID":"c:@M@PushwooshVoIP@E@PWVoIPHandleType@PWVoIPHandleTypePhoneNumber","modules":[{"name":"PushwooshVoIP"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"phoneNumber"}]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"phoneNumber","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]},{"content":[{"type":"heading","text":"Discussion","anchor":"discussion","level":2},{"type":"paragraph","inlineContent":[{"text":"Use this type when the caller identifier is a phone number. CallKit will automatically format","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"the number according to the user’s locale and system preferences."}]},{"style":"note","name":"Note","type":"aside","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The phone number should be provided in E.164 format (e.g., +1234567890) for best results."}]}]}],"kind":"content"}],"abstract":[{"type":"text","text":"Phone number with automatic formatting."}],"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPHandleType\/phoneNumber","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPHandleType"]]},"variants":[{"paths":["\/documentation\/pushwooshvoip\/pwvoiphandletype\/phonenumber"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshvoip\/pwvoiphandletype\/phonenumber"]}],"references":{"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPHandleType":{"url":"\/documentation\/pushwooshvoip\/pwvoiphandletype","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PWVoIPHandleType"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"PWVoIPHandleType","kind":"identifier"}],"title":"PWVoIPHandleType","type":"topic","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPHandleType","abstract":[{"type":"text","text":"Display format for caller information in CallKit UI."}]},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP":{"kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP","title":"PushwooshVoIP","type":"topic","role":"collection","abstract":[{"text":"VoIP push notifications with native call UI for iOS applications.","type":"text"}],"url":"\/documentation\/pushwooshvoip"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPHandleType/phoneNumber":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"phoneNumber"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPHandleType\/phoneNumber","navigatorTitle":[{"text":"PWVoIPHandleTypePhoneNumber","kind":"identifier"}],"url":"\/documentation\/pushwooshvoip\/pwvoiphandletype\/phonenumber","type":"topic","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Phone number with automatic formatting."}],"title":"PWVoIPHandleType.phoneNumber"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"PWVoIPHandleTypePhoneNumber"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","value":[{"text":"PWVoIPHandleTypePhoneNumber","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"PWVoIPHandleTypePhoneNumber","kind":"identifier"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPHandleType\/title","value":"PWVoIPHandleType","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPHandleType\/fragments","value":[{"text":"PWVoIPHandleType","kind":"identifier"}]},{"op":"replace","value":"PWVoIPHandleTypePhoneNumber","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPHandleType~1phoneNumber\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPHandleType~1phoneNumber\/fragments","op":"replace","value":[{"kind":"identifier","text":"PWVoIPHandleTypePhoneNumber"}]}]}]}