{"kind":"symbol","sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"text":"Subscribe for messages with no action performed count changes. @warning You need to unsubscribe by calling the removeObserver method, if you don’t want to receive notifications","type":"text"}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"addObserverForNoActionPerformedMessagesCountUsingBlock:"}],"title":"addObserverForNoActionPerformedMessagesCount(_:)","roleHeading":"Type Method","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addObserverForNoActionPerformedMessagesCount"},{"kind":"text","text":"((("},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":") -> "},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"kind":"text","text":")!) -> (any "},{"preciseIdentifier":"c:objc(pl)NSObject","text":"NSObjectProtocol","kind":"typeIdentifier"},{"kind":"text","text":")!"}],"role":"symbol","externalID":"c:objc(cs)PWInbox(cm)addObserverForNoActionPerformedMessagesCountUsingBlock:","symbolKind":"method","modules":[{"name":"PushwooshFramework"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addObserverForNoActionPerformedMessagesCount","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"block"},{"kind":"text","text":": (("},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")!) -> (any ","kind":"text"},{"text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier"},{"text":")!","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"block","content":[{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"return the count of unread messages."}]}]}],"type":"unorderedList"}]}],"kind":"parameters"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pwinbox\/addobserverfornoactionperformedmessagescount(_:)"]},{"paths":["\/documentation\/pushwooshframework\/pwinbox\/addobserverfornoactionperformedmessagescount(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox\/addObserverForNoActionPerformedMessagesCount(_:)"},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox"]]},"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInbox":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox","title":"PWInbox","type":"topic","navigatorTitle":[{"text":"PWInbox","kind":"identifier"}],"kind":"symbol","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PWInbox","kind":"identifier"}],"url":"\/documentation\/pushwooshframework\/pwinbox"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"kind":"symbol","abstract":[{"type":"text","text":"Push notification SDK for iOS applications."}],"type":"topic","role":"collection","url":"\/documentation\/pushwooshframework","title":"PushwooshFramework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInbox/addObserverForNoActionPerformedMessagesCount(_:)":{"url":"\/documentation\/pushwooshframework\/pwinbox\/addobserverfornoactionperformedmessagescount(_:)","role":"symbol","navigatorTitle":[{"text":"addObserverForNoActionPerformedMessagesCountUsingBlock:","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addObserverForNoActionPerformedMessagesCount","kind":"identifier"},{"text":"(((","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"kind":"text","text":") -> "},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")!) -> (any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject","text":"NSObjectProtocol"},{"kind":"text","text":")!"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox\/addObserverForNoActionPerformedMessagesCount(_:)","title":"addObserverForNoActionPerformedMessagesCount(_:)","abstract":[{"type":"text","text":"Subscribe for messages with no action performed count changes. @warning You need to unsubscribe by calling the removeObserver method, if you don’t want to receive notifications"}],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"addObserverForNoActionPerformedMessagesCountUsingBlock:","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"addObserverForNoActionPerformedMessagesCountUsingBlock:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)NSObject","text":"id<NSObject>"},{"kind":"text","text":") "},{"kind":"identifier","text":"addObserverForNoActionPerformedMessagesCountUsingBlock:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":" (^"},{"kind":"text","text":")("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger"},{"text":" ","kind":"text"},{"text":"count","kind":"internalParam"},{"text":")) ","kind":"text"},{"text":"block","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInbox\/title","op":"replace","value":"PWInbox"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInbox\/fragments","value":[{"text":"PWInbox","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInbox~1addObserverForNoActionPerformedMessagesCount(_:)\/title","value":"addObserverForNoActionPerformedMessagesCountUsingBlock:","op":"replace"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"addObserverForNoActionPerformedMessagesCountUsingBlock:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInbox~1addObserverForNoActionPerformedMessagesCount(_:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}