{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox\/addObserver(forUpdateMessagesCompletion:)"},"abstract":[{"type":"text","text":"Subscribe for messages arriving when a message is deleted, added, or updated. @warning You need to unsubscribe by calling the removeObserver method, if you don’t want to receive notifications"}],"metadata":{"modules":[{"name":"PushwooshFramework"}],"externalID":"c:objc(cs)PWInbox(cm)addObserverForUpdateInboxMessagesCompletion:","symbolKind":"method","roleHeading":"Type Method","title":"addObserver(forUpdateMessagesCompletion:)","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addObserver","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forUpdateMessagesCompletion"},{"kind":"text","text":": (([any "},{"kind":"typeIdentifier","text":"PWInboxMessageProtocol","preciseIdentifier":"c:objc(pl)PWInboxMessageProtocol"},{"text":"]?, [any ","kind":"text"},{"kind":"typeIdentifier","text":"PWInboxMessageProtocol","preciseIdentifier":"c:objc(pl)PWInboxMessageProtocol"},{"text":"]?, [any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)PWInboxMessageProtocol","kind":"typeIdentifier","text":"PWInboxMessageProtocol"},{"text":"]?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")!) -> (any "},{"preciseIdentifier":"c:objc(pl)NSObject","text":"NSObjectProtocol","kind":"typeIdentifier"},{"text":")!","kind":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"addObserverForUpdateInboxMessagesCompletion:"}]},"variants":[{"paths":["\/documentation\/pushwooshframework\/pwinbox\/addobserver(forupdatemessagescompletion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pushwooshframework\/pwinbox\/addobserver(forupdatemessagescompletion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"addObserver"},{"kind":"text","text":"("},{"text":"forUpdateMessagesCompletion","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"completion","kind":"internalParam"},{"kind":"text","text":": (([any "},{"text":"PWInboxMessageProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)PWInboxMessageProtocol"},{"text":"]?, [any ","kind":"text"},{"text":"PWInboxMessageProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)PWInboxMessageProtocol"},{"text":"]?, [any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)PWInboxMessageProtocol","text":"PWInboxMessageProtocol","kind":"typeIdentifier"},{"text":"]?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")!) -> (any "},{"text":"NSObjectProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"},{"text":")!","kind":"text"}]}]},{"parameters":[{"name":"completion","content":[{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"return the collection of the InboxMessages."}]}]}],"type":"unorderedList"}]}],"kind":"parameters"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"kind":"symbol","url":"\/documentation\/pushwooshframework","abstract":[{"type":"text","text":"Push notification SDK for iOS applications."}],"role":"collection","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","title":"PushwooshFramework","type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInbox/addObserver(forUpdateMessagesCompletion:)":{"abstract":[{"text":"Subscribe for messages arriving when a message is deleted, added, or updated. @warning You need to unsubscribe by calling the removeObserver method, if you don’t want to receive notifications","type":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox\/addObserver(forUpdateMessagesCompletion:)","type":"topic","kind":"symbol","url":"\/documentation\/pushwooshframework\/pwinbox\/addobserver(forupdatemessagescompletion:)","title":"addObserver(forUpdateMessagesCompletion:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"addObserver","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forUpdateMessagesCompletion"},{"text":": (([any ","kind":"text"},{"text":"PWInboxMessageProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)PWInboxMessageProtocol"},{"kind":"text","text":"]?, [any "},{"preciseIdentifier":"c:objc(pl)PWInboxMessageProtocol","text":"PWInboxMessageProtocol","kind":"typeIdentifier"},{"text":"]?, [any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)PWInboxMessageProtocol","text":"PWInboxMessageProtocol","kind":"typeIdentifier"},{"text":"]?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")!) -> (any ","kind":"text"},{"text":"NSObjectProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"},{"kind":"text","text":")!"}],"role":"symbol","navigatorTitle":[{"text":"addObserverForUpdateInboxMessagesCompletion:","kind":"identifier"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInbox":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PWInbox","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox","title":"PWInbox","url":"\/documentation\/pushwooshframework\/pwinbox","navigatorTitle":[{"text":"PWInbox","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic","abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","value":"addObserverForUpdateInboxMessagesCompletion:","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"addObserverForUpdateInboxMessagesCompletion:","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","text":"id<NSObject>","preciseIdentifier":"c:Qoobjc(pl)NSObject"},{"kind":"text","text":") "},{"text":"addObserverForUpdateInboxMessagesCompletion:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":" (^"},{"kind":"text","text":")("},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSObject<PWInboxMessageProtocol> *>","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"messagesDeleted","kind":"internalParam"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSObject<PWInboxMessageProtocol> *>"},{"text":" * ","kind":"text"},{"text":"messagesAdded","kind":"internalParam"},{"text":", ","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSObject<PWInboxMessageProtocol> *>","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"messagesUpdated","kind":"internalParam"},{"kind":"text","text":")) "},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInbox~1addObserver(forUpdateMessagesCompletion:)\/title","value":"addObserverForUpdateInboxMessagesCompletion:"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"addObserverForUpdateInboxMessagesCompletion:"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInbox~1addObserver(forUpdateMessagesCompletion:)\/fragments"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInbox\/title","value":"PWInbox","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInbox\/fragments","value":[{"kind":"identifier","text":"PWInbox"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}