{"abstract":[{"type":"text","text":"Subscribe for messages arriving with push notifications. @warning You need to unsubscribe by calling the removeObserver method, if you don’t want to receive notifications"}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pwinbox\/addobserverfordidreceive(inpushnotificationcompletion:)"]},{"paths":["\/documentation\/pushwooshframework\/pwinbox\/addobserverfordidreceive(inpushnotificationcompletion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox\/addObserverForDidReceive(inPushNotificationCompletion:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addObserverForDidReceive","kind":"identifier"},{"text":"(","kind":"text"},{"text":"inPushNotificationCompletion","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"completion"},{"text":": (([any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)PWInboxMessageProtocol","text":"PWInboxMessageProtocol","kind":"typeIdentifier"},{"text":"]?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")!) -> (any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject","text":"NSObjectProtocol"},{"text":")!","kind":"text"}]}]},{"kind":"parameters","parameters":[{"name":"completion","content":[{"items":[{"content":[{"inlineContent":[{"text":"return the collection of the InboxMessages.","type":"text"}],"type":"paragraph"}]}],"type":"unorderedList"}]}]}],"kind":"symbol","sections":[],"metadata":{"symbolKind":"method","role":"symbol","roleHeading":"Type Method","externalID":"c:objc(cs)PWInbox(cm)addObserverForDidReceiveInPushNotificationCompletion:","title":"addObserverForDidReceive(inPushNotificationCompletion:)","navigatorTitle":[{"text":"addObserverForDidReceiveInPushNotificationCompletion:","kind":"identifier"}],"modules":[{"name":"PushwooshFramework"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addObserverForDidReceive","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"inPushNotificationCompletion"},{"kind":"text","text":": (([any "},{"preciseIdentifier":"c:objc(pl)PWInboxMessageProtocol","text":"PWInboxMessageProtocol","kind":"typeIdentifier"},{"text":"]?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")!) -> (any "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"},{"kind":"text","text":")!"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"abstract":[],"url":"\/documentation\/pushwooshframework","role":"collection","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","title":"PushwooshFramework","kind":"symbol","type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInbox/addObserverForDidReceive(inPushNotificationCompletion:)":{"url":"\/documentation\/pushwooshframework\/pwinbox\/addobserverfordidreceive(inpushnotificationcompletion:)","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox\/addObserverForDidReceive(inPushNotificationCompletion:)","navigatorTitle":[{"kind":"identifier","text":"addObserverForDidReceiveInPushNotificationCompletion:"}],"kind":"symbol","type":"topic","abstract":[{"text":"Subscribe for messages arriving with push notifications. @warning You need to unsubscribe by calling the removeObserver method, if you don’t want to receive notifications","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addObserverForDidReceive","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"inPushNotificationCompletion"},{"text":": (([any ","kind":"text"},{"text":"PWInboxMessageProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)PWInboxMessageProtocol"},{"text":"]?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")!) -> (any "},{"preciseIdentifier":"c:objc(pl)NSObject","text":"NSObjectProtocol","kind":"typeIdentifier"},{"kind":"text","text":")!"}],"title":"addObserverForDidReceive(inPushNotificationCompletion:)","role":"symbol"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInbox":{"navigatorTitle":[{"text":"PWInbox","kind":"identifier"}],"abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PWInbox","kind":"identifier"}],"url":"\/documentation\/pushwooshframework\/pwinbox","title":"PWInbox","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox","type":"topic","role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"addObserverForDidReceiveInPushNotificationCompletion:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"+ ","kind":"text"},{"text":"addObserverForDidReceiveInPushNotificationCompletion:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"text":"id<NSObject>","kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)NSObject"},{"text":") ","kind":"text"},{"text":"addObserverForDidReceiveInPushNotificationCompletion:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":" (^"},{"kind":"text","text":")("},{"text":"NSArray<NSObject<PWInboxMessageProtocol> *>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"internalParam","text":"messagesAdded"},{"text":")) ","kind":"text"},{"kind":"internalParam","text":"completion"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInbox~1addObserverForDidReceive(inPushNotificationCompletion:)\/title","value":"addObserverForDidReceiveInPushNotificationCompletion:","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInbox~1addObserverForDidReceive(inPushNotificationCompletion:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"addObserverForDidReceiveInPushNotificationCompletion:","kind":"identifier"}]},{"value":"PWInbox","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInbox\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInbox\/fragments","value":[{"text":"PWInbox","kind":"identifier"}],"op":"replace"}]}]}