{"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox"]]},"sections":[],"abstract":[{"type":"text","text":"Subscribe for unread messages count changes. @warning You need to unsubscribe by calling the removeObserver method, if you don’t want to receive notifications"}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox\/addObserverForUnreadMessagesCount(_:)"},"metadata":{"title":"addObserverForUnreadMessagesCount(_:)","navigatorTitle":[{"text":"addObserverForUnreadMessagesCountUsingBlock:","kind":"identifier"}],"externalID":"c:objc(cs)PWInbox(cm)addObserverForUnreadMessagesCountUsingBlock:","role":"symbol","modules":[{"name":"PushwooshFramework"}],"symbolKind":"method","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"addObserverForUnreadMessagesCount","kind":"identifier"},{"kind":"text","text":"((("},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")!) -> (any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)NSObject","text":"NSObjectProtocol","kind":"typeIdentifier"},{"text":")!","kind":"text"}],"roleHeading":"Type Method"},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/pushwooshframework\/pwinbox\/addobserverforunreadmessagescount(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pwinbox\/addobserverforunreadmessagescount(_:)"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"addObserverForUnreadMessagesCount"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"block","kind":"internalParam"},{"kind":"text","text":": (("},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")!) -> (any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject","text":"NSObjectProtocol"},{"text":")!","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"block","content":[{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"return the count of unread messages."}],"type":"paragraph"}]}]}]}]}],"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInbox/addObserverForUnreadMessagesCount(_:)":{"navigatorTitle":[{"kind":"identifier","text":"addObserverForUnreadMessagesCountUsingBlock:"}],"url":"\/documentation\/pushwooshframework\/pwinbox\/addobserverforunreadmessagescount(_:)","role":"symbol","title":"addObserverForUnreadMessagesCount(_:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addObserverForUnreadMessagesCount","kind":"identifier"},{"text":"(((","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")!) -> (any "},{"preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier","text":"NSObjectProtocol"},{"kind":"text","text":")!"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox\/addObserverForUnreadMessagesCount(_:)","abstract":[{"type":"text","text":"Subscribe for unread messages count changes. @warning You need to unsubscribe by calling the removeObserver method, if you don’t want to receive notifications"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","kind":"symbol","role":"collection","title":"PushwooshFramework","url":"\/documentation\/pushwooshframework","type":"topic","abstract":[{"text":"Push notification SDK for iOS applications.","type":"text"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInbox":{"navigatorTitle":[{"kind":"identifier","text":"PWInbox"}],"url":"\/documentation\/pushwooshframework\/pwinbox","role":"symbol","title":"PWInbox","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PWInbox","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox","kind":"symbol","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"value":"addObserverForUnreadMessagesCountUsingBlock:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"addObserverForUnreadMessagesCountUsingBlock:"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:Qoobjc(pl)NSObject","kind":"typeIdentifier","text":"id<NSObject>"},{"kind":"text","text":") "},{"text":"addObserverForUnreadMessagesCountUsingBlock:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":" (^","kind":"text"},{"text":")(","kind":"text"},{"text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"count","kind":"internalParam"},{"kind":"text","text":")) "},{"kind":"internalParam","text":"block"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInbox~1addObserverForUnreadMessagesCount(_:)\/title","value":"addObserverForUnreadMessagesCountUsingBlock:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInbox~1addObserverForUnreadMessagesCount(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"addObserverForUnreadMessagesCountUsingBlock:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInbox\/title","value":"PWInbox"},{"value":[{"kind":"identifier","text":"PWInbox"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInbox\/fragments"}]}]}