{"variants":[{"paths":["\/documentation\/pushwooshframework\/pwinbox\/deletemessages(withcodes:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pwinbox\/deletemessages(withcodes:)"]}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"modules":[{"name":"PushwooshFramework"}],"title":"deleteMessages(withCodes:)","role":"symbol","roleHeading":"Type Method","navigatorTitle":[{"kind":"identifier","text":"deleteMessagesWithCodes:"}],"externalID":"c:objc(cs)PWInbox(cm)deleteMessagesWithCodes:","symbolKind":"method","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"deleteMessages","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withCodes"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"]!)","kind":"text"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox\/deleteMessages(withCodes:)"},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox"]]},"kind":"symbol","abstract":[{"type":"text","text":"Call this method, when the user deletes the list of InboxMessageProtocol manually"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"deleteMessages","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withCodes"},{"text":" ","kind":"text"},{"text":"codes","kind":"internalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]!)"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"of the list of InboxMessageProtocol.code that the user deleted","type":"text"}]}],"name":"codes"}]}],"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInbox/deleteMessages(withCodes:)":{"navigatorTitle":[{"kind":"identifier","text":"deleteMessagesWithCodes:"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"deleteMessages"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withCodes"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"]!)","kind":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox\/deleteMessages(withCodes:)","url":"\/documentation\/pushwooshframework\/pwinbox\/deletemessages(withcodes:)","type":"topic","kind":"symbol","title":"deleteMessages(withCodes:)","abstract":[{"text":"Call this method, when the user deletes the list of InboxMessageProtocol manually","type":"text"}],"role":"symbol"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInbox":{"kind":"symbol","title":"PWInbox","abstract":[],"url":"\/documentation\/pushwooshframework\/pwinbox","role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PWInbox"}],"navigatorTitle":[{"text":"PWInbox","kind":"identifier"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"title":"PushwooshFramework","role":"collection","type":"topic","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","kind":"symbol","abstract":[{"text":"Push notification SDK for iOS applications.","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Type Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"deleteMessagesWithCodes:","op":"replace","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"deleteMessagesWithCodes:"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"deleteMessagesWithCodes:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSString *>"},{"kind":"text","text":" *) "},{"text":"codes","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"deleteMessagesWithCodes:","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInbox~1deleteMessages(withCodes:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInbox~1deleteMessages(withCodes:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"deleteMessagesWithCodes:"}]},{"value":"PWInbox","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInbox\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInbox\/fragments","value":[{"text":"PWInbox","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}