{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pwinbox\/deleteallreadmessages()"]},{"paths":["\/documentation\/pushwooshframework\/pwinbox\/deleteallreadmessages()"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox\/deleteAllReadMessages()"},"sections":[],"abstract":[{"text":"Deletes every read inbox message in one call. Useful for “Clear read”","type":"text"},{"type":"text","text":" "},{"type":"text","text":"affordances. Unread and pinned-but-unread messages are preserved."}],"metadata":{"roleHeading":"Type Method","title":"deleteAllReadMessages()","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"deleteAllReadMessages","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"deleteAllReadMessages"}],"role":"symbol","modules":[{"name":"PushwooshFramework"}],"symbolKind":"method","externalID":"c:objc(cs)PWInbox(cm)deleteAllReadMessages"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"deleteAllReadMessages"},{"text":"()","kind":"text"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInbox":{"kind":"symbol","navigatorTitle":[{"text":"PWInbox","kind":"identifier"}],"abstract":[{"type":"text","text":"Conforms to "},{"code":"PWInboxBridge","type":"codeVoice"},{"type":"text","text":" so optional Swift modules"},{"text":" ","type":"text"},{"type":"text","text":"(e.g. "},{"type":"codeVoice","code":"PushwooshInboxKit"},{"type":"text","text":") can reach the storage-backed inbox API"},{"type":"text","text":" "},{"type":"text","text":"through "},{"type":"codeVoice","code":"PWManagerBridge.shared.inboxBridge as? PWInboxBridge.Type"},{"text":".","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Without the formal conformance the Swift cast returns "},{"code":"nil","type":"codeVoice"},{"type":"text","text":" at runtime"},{"type":"text","text":" "},{"text":"and every bridge call silently no-ops — mutations never reach disk.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox","title":"PWInbox","role":"symbol","url":"\/documentation\/pushwooshframework\/pwinbox","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PWInbox","kind":"identifier"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"type":"topic","kind":"symbol","title":"PushwooshFramework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","url":"\/documentation\/pushwooshframework","role":"collection","abstract":[{"type":"text","text":"Push notification SDK for iOS applications."}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInbox/deleteAllReadMessages()":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox\/deleteAllReadMessages()","kind":"symbol","title":"deleteAllReadMessages()","type":"topic","navigatorTitle":[{"kind":"identifier","text":"deleteAllReadMessages"}],"abstract":[{"type":"text","text":"Deletes every read inbox message in one call. Useful for “Clear read”"},{"text":" ","type":"text"},{"text":"affordances. Unread and pinned-but-unread messages are preserved.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"deleteAllReadMessages","kind":"identifier"},{"text":"()","kind":"text"}],"url":"\/documentation\/pushwooshframework\/pwinbox\/deleteallreadmessages()"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"value":"deleteAllReadMessages","path":"\/metadata\/title","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"deleteAllReadMessages"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"deleteAllReadMessages","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"PWInbox","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInbox\/title","op":"replace"},{"value":[{"text":"PWInbox","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInbox\/fragments"},{"value":"deleteAllReadMessages","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInbox~1deleteAllReadMessages()\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInbox~1deleteAllReadMessages()\/fragments","value":[{"kind":"text","text":"+ "},{"text":"deleteAllReadMessages","kind":"identifier"}],"op":"replace"}]}]}