{"kind":"symbol","abstract":[{"type":"text","text":"Marks every currently-stored unread inbox message as read in a single call."},{"text":" ","type":"text"},{"type":"text","text":"Convenience over filtering the result of "},{"type":"codeVoice","code":"loadMessagesWithCompletion:"},{"type":"text","text":" and"},{"type":"text","text":" "},{"text":"calling ","type":"text"},{"type":"codeVoice","code":"readMessagesWithCodes:"},{"text":" yourself.","type":"text"}],"sections":[],"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox\/markAllMessagesAsRead()","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox"]]},"metadata":{"modules":[{"name":"PushwooshFramework"}],"symbolKind":"method","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"markAllMessagesAsRead","kind":"identifier"},{"text":"()","kind":"text"}],"title":"markAllMessagesAsRead()","navigatorTitle":[{"kind":"identifier","text":"markAllMessagesAsRead"}],"roleHeading":"Type Method","externalID":"c:objc(cs)PWInbox(cm)markAllMessagesAsRead"},"variants":[{"paths":["\/documentation\/pushwooshframework\/pwinbox\/markallmessagesasread()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pushwooshframework\/pwinbox\/markallmessagesasread()"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"markAllMessagesAsRead"},{"text":"()","kind":"text"}],"languages":["swift"]}]}],"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInbox/markAllMessagesAsRead()":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox\/markAllMessagesAsRead()","role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/pushwooshframework\/pwinbox\/markallmessagesasread()","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"markAllMessagesAsRead","kind":"identifier"},{"text":"()","kind":"text"}],"title":"markAllMessagesAsRead()","abstract":[{"type":"text","text":"Marks every currently-stored unread inbox message as read in a single call."},{"text":" ","type":"text"},{"text":"Convenience over filtering the result of ","type":"text"},{"code":"loadMessagesWithCompletion:","type":"codeVoice"},{"type":"text","text":" and"},{"type":"text","text":" "},{"type":"text","text":"calling "},{"type":"codeVoice","code":"readMessagesWithCodes:"},{"type":"text","text":" yourself."}],"navigatorTitle":[{"kind":"identifier","text":"markAllMessagesAsRead"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInbox":{"kind":"symbol","title":"PWInbox","url":"\/documentation\/pushwooshframework\/pwinbox","abstract":[{"text":"Conforms to ","type":"text"},{"type":"codeVoice","code":"PWInboxBridge"},{"type":"text","text":" so optional Swift modules"},{"type":"text","text":" "},{"type":"text","text":"(e.g. "},{"type":"codeVoice","code":"PushwooshInboxKit"},{"type":"text","text":") can reach the storage-backed inbox API"},{"type":"text","text":" "},{"text":"through ","type":"text"},{"type":"codeVoice","code":"PWManagerBridge.shared.inboxBridge as? PWInboxBridge.Type"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Without the formal conformance the Swift cast returns "},{"type":"codeVoice","code":"nil"},{"text":" at runtime","type":"text"},{"type":"text","text":" "},{"text":"and every bridge call silently no-ops — mutations never reach disk.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PWInbox","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox","navigatorTitle":[{"kind":"identifier","text":"PWInbox"}],"type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"abstract":[{"text":"Push notification SDK for iOS applications.","type":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","title":"PushwooshFramework","kind":"symbol","role":"collection","url":"\/documentation\/pushwooshframework","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"markAllMessagesAsRead"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"markAllMessagesAsRead"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"markAllMessagesAsRead","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInbox~1markAllMessagesAsRead()\/title","value":"markAllMessagesAsRead","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"text":"markAllMessagesAsRead","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInbox~1markAllMessagesAsRead()\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInbox\/title","value":"PWInbox"},{"value":[{"text":"PWInbox","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInbox\/fragments"}]}]}