{"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"message"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forCode"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"!) -> (any "},{"text":"PWInboxMessageProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)PWInboxMessageProtocol"},{"kind":"text","text":")?"}],"roleHeading":"Type Method","title":"message(forCode:)","modules":[{"name":"PushwooshFramework"}],"navigatorTitle":[{"kind":"identifier","text":"messageForCode:"}],"externalID":"c:objc(cs)PWInbox(cm)messageForCode:","symbolKind":"method","role":"symbol"},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox\/message(forCode:)"},"abstract":[{"type":"text","text":"Returns a single inbox message identified by its code without loading the"},{"type":"text","text":" "},{"type":"text","text":"entire feed. Reads from the local "},{"code":"PWInboxStorage","type":"codeVoice"},{"text":" cache. Returns ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":" if","type":"text"},{"text":" ","type":"text"},{"text":"the message has not been seen yet, has been deleted, or has expired.","type":"text"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pwinbox\/message(forcode:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pwinbox\/message(forcode:)"]}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"message"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"forCode"},{"text":" ","kind":"text"},{"text":"code","kind":"internalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"!) -> (any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)PWInboxMessageProtocol","text":"PWInboxMessageProtocol"},{"text":")?","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"code","content":[{"inlineContent":[{"type":"text","text":"of the inboxMessage"}],"type":"paragraph"}]}],"kind":"parameters"}],"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInbox":{"kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox","abstract":[{"type":"text","text":"Conforms to "},{"code":"PWInboxBridge","type":"codeVoice"},{"type":"text","text":" so optional Swift modules"},{"type":"text","text":" "},{"type":"text","text":"(e.g. "},{"type":"codeVoice","code":"PushwooshInboxKit"},{"type":"text","text":") can reach the storage-backed inbox API"},{"type":"text","text":" "},{"type":"text","text":"through "},{"type":"codeVoice","code":"PWManagerBridge.shared.inboxBridge as? PWInboxBridge.Type"},{"type":"text","text":"."},{"text":" ","type":"text"},{"text":"Without the formal conformance the Swift cast returns ","type":"text"},{"type":"codeVoice","code":"nil"},{"type":"text","text":" at runtime"},{"text":" ","type":"text"},{"text":"and every bridge call silently no-ops — mutations never reach disk.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PWInbox","kind":"identifier"}],"title":"PWInbox","navigatorTitle":[{"kind":"identifier","text":"PWInbox"}],"type":"topic","url":"\/documentation\/pushwooshframework\/pwinbox","role":"symbol"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"title":"PushwooshFramework","url":"\/documentation\/pushwooshframework","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","abstract":[{"text":"Push notification SDK for iOS applications.","type":"text"}],"type":"topic","role":"collection"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInbox/message(forCode:)":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox\/message(forCode:)","role":"symbol","abstract":[{"text":"Returns a single inbox message identified by its code without loading the","type":"text"},{"type":"text","text":" "},{"type":"text","text":"entire feed. Reads from the local "},{"code":"PWInboxStorage","type":"codeVoice"},{"type":"text","text":" cache. Returns "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if"},{"type":"text","text":" "},{"text":"the message has not been seen yet, has been deleted, or has expired.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"message"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!) -> (any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)PWInboxMessageProtocol","text":"PWInboxMessageProtocol"},{"kind":"text","text":")?"}],"kind":"symbol","navigatorTitle":[{"text":"messageForCode:","kind":"identifier"}],"type":"topic","url":"\/documentation\/pushwooshframework\/pwinbox\/message(forcode:)","title":"message(forCode:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"value":"messageForCode:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"messageForCode:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"text":"id<PWInboxMessageProtocol>","preciseIdentifier":"c:Qoobjc(pl)PWInboxMessageProtocol","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"messageForCode:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"code","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":"PWInbox","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInbox\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInbox\/fragments","value":[{"text":"PWInbox","kind":"identifier"}],"op":"replace"},{"value":"messageForCode:","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInbox~1message(forCode:)\/title","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"text":"messageForCode:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInbox~1message(forCode:)\/fragments"}]}]}