{"abstract":[{"text":"Call this method, when the user clicks on the InboxMessageProtocol and the message’s action is performed","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox"]]},"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"performActionForMessage","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"!)"}],"navigatorTitle":[{"kind":"identifier","text":"performActionForMessageWithCode:"}],"modules":[{"name":"PushwooshFramework"}],"title":"performActionForMessage(withCode:)","externalID":"c:objc(cs)PWInbox(cm)performActionForMessageWithCode:","symbolKind":"method","roleHeading":"Type Method","role":"symbol"},"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox\/performActionForMessage(withCode:)","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"performActionForMessage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withCode","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"code"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"!)","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"of the inboxMessage that the user tapped","type":"text"}]}],"name":"code"}],"kind":"parameters"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pwinbox\/performactionformessage(withcode:)"]},{"paths":["\/documentation\/pushwooshframework\/pwinbox\/performactionformessage(withcode:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInbox":{"kind":"symbol","title":"PWInbox","url":"\/documentation\/pushwooshframework\/pwinbox","abstract":[{"text":"Conforms to ","type":"text"},{"type":"codeVoice","code":"PWInboxBridge"},{"type":"text","text":" so optional Swift modules"},{"type":"text","text":" "},{"type":"text","text":"(e.g. "},{"type":"codeVoice","code":"PushwooshInboxKit"},{"type":"text","text":") can reach the storage-backed inbox API"},{"type":"text","text":" "},{"text":"through ","type":"text"},{"type":"codeVoice","code":"PWManagerBridge.shared.inboxBridge as? PWInboxBridge.Type"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Without the formal conformance the Swift cast returns "},{"type":"codeVoice","code":"nil"},{"text":" at runtime","type":"text"},{"type":"text","text":" "},{"text":"and every bridge call silently no-ops — mutations never reach disk.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PWInbox","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox","navigatorTitle":[{"kind":"identifier","text":"PWInbox"}],"type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInbox/performActionForMessage(withCode:)":{"title":"performActionForMessage(withCode:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"performActionForMessage"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withCode"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"!)","kind":"text"}],"abstract":[{"type":"text","text":"Call this method, when the user clicks on the InboxMessageProtocol and the message’s action is performed"}],"url":"\/documentation\/pushwooshframework\/pwinbox\/performactionformessage(withcode:)","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox\/performActionForMessage(withCode:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"performActionForMessageWithCode:"}],"type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"abstract":[{"text":"Push notification SDK for iOS applications.","type":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","title":"PushwooshFramework","kind":"symbol","role":"collection","url":"\/documentation\/pushwooshframework","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"performActionForMessageWithCode:","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"kind":"text","text":"+ "},{"text":"performActionForMessageWithCode:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"text":"performActionForMessageWithCode:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"code"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"PWInbox","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInbox\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInbox\/fragments","value":[{"text":"PWInbox","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInbox~1performActionForMessage(withCode:)\/title","value":"performActionForMessageWithCode:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInbox~1performActionForMessage(withCode:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"performActionForMessageWithCode:"}]}]}]}