{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pwinbox\/readmessages(withcodes:)"]},{"paths":["\/documentation\/pushwooshframework\/pwinbox\/readmessages(withcodes:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"readMessages"},{"text":"(","kind":"text"},{"text":"withCodes","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"codes"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"]!)","kind":"text"}],"platforms":["iOS"]}]},{"parameters":[{"name":"codes","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"of the inboxMessages"}]}]}],"kind":"parameters"}],"sections":[],"metadata":{"navigatorTitle":[{"text":"readMessagesWithCodes:","kind":"identifier"}],"title":"readMessages(withCodes:)","symbolKind":"method","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"readMessages"},{"text":"(","kind":"text"},{"text":"withCodes","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"]!)","kind":"text"}],"roleHeading":"Type Method","role":"symbol","modules":[{"name":"PushwooshFramework"}],"externalID":"c:objc(cs)PWInbox(cm)readMessagesWithCodes:"},"abstract":[{"type":"text","text":"Call this method to mark the list of InboxMessageProtocol as read"}],"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox\/readMessages(withCodes:)","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox"]]},"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInbox/readMessages(withCodes:)":{"role":"symbol","abstract":[{"type":"text","text":"Call this method to mark the list of InboxMessageProtocol as read"}],"type":"topic","kind":"symbol","title":"readMessages(withCodes:)","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox\/readMessages(withCodes:)","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"readMessages","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withCodes"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]!)"}],"url":"\/documentation\/pushwooshframework\/pwinbox\/readmessages(withcodes:)","navigatorTitle":[{"text":"readMessagesWithCodes:","kind":"identifier"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"url":"\/documentation\/pushwooshframework","role":"collection","title":"PushwooshFramework","kind":"symbol","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","abstract":[{"text":"Push notification SDK for iOS applications.","type":"text"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInbox":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PWInbox","kind":"identifier"}],"url":"\/documentation\/pushwooshframework\/pwinbox","navigatorTitle":[{"text":"PWInbox","kind":"identifier"}],"title":"PWInbox","abstract":[{"type":"text","text":"Conforms to "},{"type":"codeVoice","code":"PWInboxBridge"},{"text":" so optional Swift modules","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"(e.g. "},{"code":"PushwooshInboxKit","type":"codeVoice"},{"type":"text","text":") can reach the storage-backed inbox API"},{"type":"text","text":" "},{"type":"text","text":"through "},{"code":"PWManagerBridge.shared.inboxBridge as? PWInboxBridge.Type","type":"codeVoice"},{"text":".","type":"text"},{"type":"text","text":" "},{"text":"Without the formal conformance the Swift cast returns ","type":"text"},{"type":"codeVoice","code":"nil"},{"type":"text","text":" at runtime"},{"text":" ","type":"text"},{"text":"and every bridge call silently no-ops — mutations never reach disk.","type":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox","kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"readMessagesWithCodes:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"+ ","kind":"text"},{"text":"readMessagesWithCodes:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"readMessagesWithCodes:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSString *>"},{"text":" *) ","kind":"text"},{"text":"codes","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInbox~1readMessages(withCodes:)\/title","value":"readMessagesWithCodes:","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInbox~1readMessages(withCodes:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"readMessagesWithCodes:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInbox\/title","op":"replace","value":"PWInbox"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInbox\/fragments","value":[{"kind":"identifier","text":"PWInbox"}]}]}]}