{"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","abstract":[{"type":"text","text":"Unsubscribes from notifications"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"removeObserver","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"observer","kind":"internalParam"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)NSObject","text":"NSObjectProtocol","kind":"typeIdentifier"},{"kind":"text","text":")!)"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"observer","content":[{"items":[{"content":[{"inlineContent":[{"type":"text","text":"Unsubscribes observer"}],"type":"paragraph"}]}],"type":"unorderedList"}]}]}],"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"removeObserver","kind":"identifier"},{"kind":"text","text":"((any "},{"preciseIdentifier":"c:objc(pl)NSObject","text":"NSObjectProtocol","kind":"typeIdentifier"},{"text":")!)","kind":"text"}],"navigatorTitle":[{"text":"removeObserver:","kind":"identifier"}],"roleHeading":"Type Method","role":"symbol","title":"removeObserver(_:)","modules":[{"name":"PushwooshFramework"}],"externalID":"c:objc(cs)PWInbox(cm)removeObserver:","symbolKind":"method"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pwinbox\/removeobserver(_:)"]},{"paths":["\/documentation\/pushwooshframework\/pwinbox\/removeobserver(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox\/removeObserver(_:)"},"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInbox/removeObserver(_:)":{"url":"\/documentation\/pushwooshframework\/pwinbox\/removeobserver(_:)","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox\/removeObserver(_:)","navigatorTitle":[{"kind":"identifier","text":"removeObserver:"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Unsubscribes from notifications"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removeObserver","kind":"identifier"},{"kind":"text","text":"((any "},{"preciseIdentifier":"c:objc(pl)NSObject","text":"NSObjectProtocol","kind":"typeIdentifier"},{"text":")!)","kind":"text"}],"title":"removeObserver(_:)","role":"symbol"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"abstract":[],"url":"\/documentation\/pushwooshframework","role":"collection","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","title":"PushwooshFramework","kind":"symbol","type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInbox":{"navigatorTitle":[{"text":"PWInbox","kind":"identifier"}],"abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PWInbox","kind":"identifier"}],"url":"\/documentation\/pushwooshframework\/pwinbox","title":"PWInbox","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox","type":"topic","role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Type Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"removeObserver:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"text":"removeObserver:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"removeObserver:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"id<NSObject>","preciseIdentifier":"c:Qoobjc(pl)NSObject"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"observer"},{"kind":"text","text":";"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInbox~1removeObserver(_:)\/title","value":"removeObserver:"},{"value":[{"text":"+ ","kind":"text"},{"text":"removeObserver:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInbox~1removeObserver(_:)\/fragments"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInbox\/title","value":"PWInbox","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInbox\/fragments","value":[{"kind":"identifier","text":"PWInbox"}],"op":"replace"}]}]}