{"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"updates observers","type":"text"}],"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox\/updateInbox(forNewUserId:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pwinbox\/updateinbox(fornewuserid:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pwinbox\/updateinbox(fornewuserid:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateInbox"},{"kind":"text","text":"("},{"text":"forNewUserId","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"completion"},{"text":": ((","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"},{"kind":"text","text":") -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")!)","kind":"text"}]}]}],"metadata":{"modules":[{"name":"PushwooshFramework"}],"externalID":"c:objc(cs)PWInbox(cm)updateInboxForNewUserId:","title":"updateInbox(forNewUserId:)","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"updateInbox"},{"kind":"text","text":"("},{"text":"forNewUserId","kind":"externalParam"},{"text":": ((","kind":"text"},{"preciseIdentifier":"s:Su","kind":"typeIdentifier","text":"UInt"},{"kind":"text","text":") -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")!)","kind":"text"}],"roleHeading":"Type Method","navigatorTitle":[{"kind":"identifier","text":"updateInboxForNewUserId:"}],"symbolKind":"method","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox"]]},"kind":"symbol","sections":[],"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"url":"\/documentation\/pushwooshframework","kind":"symbol","type":"topic","title":"PushwooshFramework","role":"collection","abstract":[{"text":"Push notification SDK for iOS applications.","type":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInbox":{"url":"\/documentation\/pushwooshframework\/pwinbox","type":"topic","abstract":[{"type":"text","text":"Conforms to "},{"type":"codeVoice","code":"PWInboxBridge"},{"type":"text","text":" so optional Swift modules"},{"text":" ","type":"text"},{"type":"text","text":"(e.g. "},{"type":"codeVoice","code":"PushwooshInboxKit"},{"text":") can reach the storage-backed inbox API","type":"text"},{"type":"text","text":" "},{"type":"text","text":"through "},{"code":"PWManagerBridge.shared.inboxBridge as? PWInboxBridge.Type","type":"codeVoice"},{"type":"text","text":"."},{"type":"text","text":" "},{"text":"Without the formal conformance the Swift cast returns ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":" at runtime","type":"text"},{"type":"text","text":" "},{"type":"text","text":"and every bridge call silently no-ops — mutations never reach disk."}],"title":"PWInbox","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PWInbox"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PWInbox","kind":"identifier"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWInbox/updateInbox(forNewUserId:)":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWInbox\/updateInbox(forNewUserId:)","navigatorTitle":[{"text":"updateInboxForNewUserId:","kind":"identifier"}],"url":"\/documentation\/pushwooshframework\/pwinbox\/updateinbox(fornewuserid:)","role":"symbol","title":"updateInbox(forNewUserId:)","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"updateInbox","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"forNewUserId"},{"kind":"text","text":": (("},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")!)","kind":"text"}],"type":"topic","abstract":[{"type":"text","text":"updates observers"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"updateInboxForNewUserId:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"text":"updateInboxForNewUserId:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"text":"updateInboxForNewUserId:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":" (^"},{"kind":"text","text":")("},{"preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"messagesCount","kind":"internalParam"},{"text":")) ","kind":"text"},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace"},{"value":"PWInbox","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInbox\/title"},{"value":[{"kind":"identifier","text":"PWInbox"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInbox\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInbox~1updateInbox(forNewUserId:)\/title","value":"updateInboxForNewUserId:"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"updateInboxForNewUserId:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWInbox~1updateInbox(forNewUserId:)\/fragments"}]}]}