{"variants":[{"paths":["\/documentation\/pushwooshframework\/pushnotificationdelegate\/on(inappclosed:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pushnotificationdelegate\/on(inappclosed:)"]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","metadata":{"title":"on(inAppClosed:)","symbolKind":"method","navigatorTitle":[{"text":"onInAppClosed:","kind":"identifier"}],"roleHeading":"Instance Method","role":"symbol","required":true,"platforms":[],"modules":[{"name":"PushwooshFramework"}],"externalID":"c:objc(pl)PushNotificationDelegate(im)onInAppClosed:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"on"},{"kind":"text","text":"("},{"text":"inAppClosed","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"!)","kind":"text"}]},"abstract":[{"type":"text","text":"Tells the delegate that In-App with specified code has been closed"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"optional"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"on"},{"text":"(","kind":"text"},{"text":"inAppClosed","kind":"externalParam"},{"kind":"text","text":" "},{"text":"code","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"!)"}]}]},{"parameters":[{"content":[{"inlineContent":[{"text":"In-App code","type":"text"}],"type":"paragraph"}],"name":"code"}],"kind":"parameters"}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationDelegate"]]},"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationDelegate\/on(inAppClosed:)","interfaceLanguage":"swift"},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"text":"Use PWRichMediaPresentingDelegate protocol from PWRichMediaManager.h","type":"text"}]}],"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","type":"topic","role":"collection","abstract":[{"text":"Push notification SDK for iOS applications.","type":"text"}],"title":"PushwooshFramework","url":"\/documentation\/pushwooshframework"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationDelegate":{"navigatorTitle":[{"kind":"identifier","text":"PushNotificationDelegate"}],"url":"\/documentation\/pushwooshframework\/pushnotificationdelegate","abstract":[{"type":"codeVoice","code":"PushNotificationDelegate"},{"text":" protocol defines the methods that can be implemented in the delegate of the ","type":"text"},{"type":"codeVoice","code":"PushNotificationManager"},{"text":" class’ singleton object.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"These methods provide information about the key events for push notification manager such as registering with APS services, receiving push notifications or working with the received notification."},{"text":" ","type":"text"},{"text":"These methods implementation allows to react on these events properly.","type":"text"}],"kind":"symbol","title":"PushNotificationDelegate","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationDelegate","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushNotificationDelegate"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationDelegate/on(inAppClosed:)":{"navigatorTitle":[{"text":"onInAppClosed:","kind":"identifier"}],"url":"\/documentation\/pushwooshframework\/pushnotificationdelegate\/on(inappclosed:)","abstract":[{"type":"text","text":"Tells the delegate that In-App with specified code has been closed"}],"kind":"symbol","deprecated":true,"required":true,"title":"on(inAppClosed:)","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationDelegate\/on(inAppClosed:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"on","kind":"identifier"},{"kind":"text","text":"("},{"text":"inAppClosed","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"!)","kind":"text"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"onInAppClosed:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"onInAppClosed:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"onInAppClosed:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"code","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"PushNotificationDelegate","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationDelegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationDelegate\/fragments","value":[{"text":"PushNotificationDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationDelegate~1on(inAppClosed:)\/title","value":"onInAppClosed:"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationDelegate~1on(inAppClosed:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"onInAppClosed:","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}