{"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationDelegate\/on(inAppDisplayed:)","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationDelegate"]]},"kind":"symbol","metadata":{"roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"onInAppDisplayed:"}],"platforms":[],"externalID":"c:objc(pl)PushNotificationDelegate(im)onInAppDisplayed:","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"on"},{"text":"(","kind":"text"},{"text":"inAppDisplayed","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"!)"}],"role":"symbol","title":"on(inAppDisplayed:)","modules":[{"name":"PushwooshFramework"}],"symbolKind":"method"},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Tells the delegate that In-App with specified code has been displayed"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"on","kind":"identifier"},{"kind":"text","text":"("},{"text":"inAppDisplayed","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"code"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"!)","kind":"text"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"In-App code","type":"text"}]}],"name":"code"}]}],"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use PWRichMediaPresentingDelegate protocol from PWRichMediaManager.h"}]}],"variants":[{"paths":["\/documentation\/pushwooshframework\/pushnotificationdelegate\/on(inappdisplayed:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pushwooshframework\/pushnotificationdelegate\/on(inappdisplayed:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"url":"\/documentation\/pushwooshframework","type":"topic","abstract":[{"text":"Push notification SDK for iOS applications.","type":"text"}],"title":"PushwooshFramework","kind":"symbol","role":"collection","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationDelegate/on(inAppDisplayed:)":{"role":"symbol","url":"\/documentation\/pushwooshframework\/pushnotificationdelegate\/on(inappdisplayed:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"on","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"inAppDisplayed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"!)"}],"title":"on(inAppDisplayed:)","navigatorTitle":[{"kind":"identifier","text":"onInAppDisplayed:"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationDelegate\/on(inAppDisplayed:)","abstract":[{"text":"Tells the delegate that In-App with specified code has been displayed","type":"text"}],"kind":"symbol","deprecated":true},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationDelegate":{"type":"topic","kind":"symbol","abstract":[{"type":"codeVoice","code":"PushNotificationDelegate"},{"type":"text","text":" protocol defines the methods that can be implemented in the delegate of the "},{"type":"codeVoice","code":"PushNotificationManager"},{"type":"text","text":" class’ singleton object."},{"type":"text","text":" "},{"type":"text","text":"These methods provide information about the key events for push notification manager such as registering with APS services, receiving push notifications or working with the received notification."},{"text":" ","type":"text"},{"text":"These methods implementation allows to react on these events properly.","type":"text"}],"url":"\/documentation\/pushwooshframework\/pushnotificationdelegate","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationDelegate","navigatorTitle":[{"kind":"identifier","text":"PushNotificationDelegate"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"PushNotificationDelegate","kind":"identifier"}],"role":"symbol","title":"PushNotificationDelegate"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"onInAppDisplayed:","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onInAppDisplayed:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"onInAppDisplayed:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"code"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationDelegate~1on(inAppDisplayed:)\/title","value":"onInAppDisplayed:"},{"value":[{"text":"- ","kind":"text"},{"text":"onInAppDisplayed:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationDelegate~1on(inAppDisplayed:)\/fragments"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationDelegate\/title","op":"replace","value":"PushNotificationDelegate"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationDelegate\/fragments","op":"replace","value":[{"text":"PushNotificationDelegate","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}