{"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationDelegate"]]},"metadata":{"navigatorTitle":[{"text":"onActionIdentifierReceived:withNotification:","kind":"identifier"}],"title":"onActionIdentifierReceived(_:withNotification:)","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onActionIdentifierReceived","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"!, ","kind":"text"},{"kind":"externalParam","text":"withNotification"},{"text":": [","kind":"text"},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"text":"]!)","kind":"text"}],"required":true,"roleHeading":"Instance Method","modules":[{"name":"PushwooshFramework"}],"role":"symbol","externalID":"c:objc(pl)PushNotificationDelegate(im)onActionIdentifierReceived:withNotification:"},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationDelegate\/onActionIdentifierReceived(_:withNotification:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pushnotificationdelegate\/onactionidentifierreceived(_:withnotification:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pushnotificationdelegate\/onactionidentifierreceived(_:withnotification:)"]}],"sections":[],"kind":"symbol","abstract":[{"text":"Tells the delegate that a custom action was triggered when opening a notification.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onActionIdentifierReceived","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"!, ","kind":"text"},{"text":"withNotification","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"notification"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!)"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"identifier","content":[{"inlineContent":[{"text":"NSString containing an ID of a clicked button. This ID is set by a user when creating a category in the Pushwoosh Control Panel","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"NSDictionary with push payload."}],"type":"paragraph"}],"name":"notification"}]}],"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","title":"PushwooshFramework","url":"\/documentation\/pushwooshframework","kind":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationDelegate/onActionIdentifierReceived(_:withNotification:)":{"url":"\/documentation\/pushwooshframework\/pushnotificationdelegate\/onactionidentifierreceived(_:withnotification:)","navigatorTitle":[{"text":"onActionIdentifierReceived:withNotification:","kind":"identifier"}],"type":"topic","title":"onActionIdentifierReceived(_:withNotification:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onActionIdentifierReceived","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"!, ","kind":"text"},{"text":"withNotification","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"]!)","kind":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationDelegate\/onActionIdentifierReceived(_:withNotification:)","kind":"symbol","abstract":[{"type":"text","text":"Tells the delegate that a custom action was triggered when opening a notification."}],"required":true,"role":"symbol"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationDelegate":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PushNotificationDelegate"}],"url":"\/documentation\/pushwooshframework\/pushnotificationdelegate","navigatorTitle":[{"kind":"identifier","text":"PushNotificationDelegate"}],"abstract":[{"type":"codeVoice","code":"PushNotificationDelegate"},{"text":" protocol defines the methods that can be implemented in the delegate of the ","type":"text"},{"type":"codeVoice","code":"PushNotificationManager"},{"text":" class’ singleton object.","type":"text"},{"text":" ","type":"text"},{"text":"These methods provide information about the key events for push notification manager such as registering with APS services, receiving push notifications or working with the received notification.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"These methods implementation allows to react on these events properly."}],"kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationDelegate","title":"PushNotificationDelegate","type":"topic","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"onActionIdentifierReceived:withNotification:"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"onActionIdentifierReceived:withNotification:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"onActionIdentifierReceived:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"identifier","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"withNotification:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDictionary","text":"NSDictionary"},{"text":" *) ","kind":"text"},{"text":"notification","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationDelegate~1onActionIdentifierReceived(_:withNotification:)\/title","value":"onActionIdentifierReceived:withNotification:"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationDelegate~1onActionIdentifierReceived(_:withNotification:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onActionIdentifierReceived:withNotification:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationDelegate\/title","value":"PushNotificationDelegate","op":"replace"},{"value":[{"text":"PushNotificationDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationDelegate\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}