{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"optional"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onDidFailToRegisterForRemoteNotificationsWithError"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"error"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":")!)","kind":"text"}]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"An NSError object encapsulating the information about the reason of the registration failure. Within this method you can define application’s behaviour in case of registration failure."}],"type":"paragraph"}],"name":"error"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"onDidFailToRegisterForRemoteNotificationsWithError:"}],"externalID":"c:objc(pl)PushNotificationDelegate(im)onDidFailToRegisterForRemoteNotificationsWithError:","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onDidFailToRegisterForRemoteNotificationsWithError","kind":"identifier"},{"text":"((any ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":")!)","kind":"text"}],"title":"onDidFailToRegisterForRemoteNotificationsWithError(_:)","role":"symbol","roleHeading":"Instance Method","modules":[{"name":"PushwooshFramework"}]},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationDelegate"]]},"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationDelegate\/onDidFailToRegisterForRemoteNotificationsWithError(_:)","interfaceLanguage":"swift"},"sections":[],"variants":[{"paths":["\/documentation\/pushwooshframework\/pushnotificationdelegate\/ondidfailtoregisterforremotenotificationswitherror(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pushnotificationdelegate\/ondidfailtoregisterforremotenotificationswitherror(_:)"]}],"kind":"symbol","abstract":[{"type":"text","text":"Sent to the delegate when Apple Push Service (APS) could not complete the registration process successfully."}],"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationDelegate":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PushNotificationDelegate"}],"role":"symbol","title":"PushNotificationDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushNotificationDelegate"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationDelegate","type":"topic","abstract":[{"code":"PushNotificationDelegate","type":"codeVoice"},{"type":"text","text":" protocol defines the methods that can be implemented in the delegate of the "},{"type":"codeVoice","code":"PushNotificationManager"},{"type":"text","text":" class’ singleton object."},{"type":"text","text":" "},{"text":"These methods provide information about the key events for push notification manager such as registering with APS services, receiving push notifications or working with the received notification.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"These methods implementation allows to react on these events properly."}],"url":"\/documentation\/pushwooshframework\/pushnotificationdelegate"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"abstract":[],"url":"\/documentation\/pushwooshframework","role":"collection","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","title":"PushwooshFramework","kind":"symbol","type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationDelegate/onDidFailToRegisterForRemoteNotificationsWithError(_:)":{"type":"topic","role":"symbol","url":"\/documentation\/pushwooshframework\/pushnotificationdelegate\/ondidfailtoregisterforremotenotificationswitherror(_:)","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationDelegate\/onDidFailToRegisterForRemoteNotificationsWithError(_:)","navigatorTitle":[{"text":"onDidFailToRegisterForRemoteNotificationsWithError:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onDidFailToRegisterForRemoteNotificationsWithError","kind":"identifier"},{"kind":"text","text":"((any "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":")!)","kind":"text"}],"kind":"symbol","abstract":[{"type":"text","text":"Sent to the delegate when Apple Push Service (APS) could not complete the registration process successfully."}],"title":"onDidFailToRegisterForRemoteNotificationsWithError(_:)"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"onDidFailToRegisterForRemoteNotificationsWithError:"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onDidFailToRegisterForRemoteNotificationsWithError:"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"onDidFailToRegisterForRemoteNotificationsWithError:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationDelegate\/title","value":"PushNotificationDelegate"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationDelegate\/fragments","value":[{"kind":"identifier","text":"PushNotificationDelegate"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationDelegate~1onDidFailToRegisterForRemoteNotificationsWithError(_:)\/title","value":"onDidFailToRegisterForRemoteNotificationsWithError:"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationDelegate~1onDidFailToRegisterForRemoteNotificationsWithError(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"onDidFailToRegisterForRemoteNotificationsWithError:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}