{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationDelegate"]]},"sections":[],"variants":[{"paths":["\/documentation\/pushwooshframework\/pushnotificationdelegate\/ondidregisterforremotenotifications(withdevicetoken:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pushwooshframework\/pushnotificationdelegate\/ondidregisterforremotenotifications(withdevicetoken:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Tells the delegate that the application has registered with Apple Push Service (APS) successfully.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"onDidRegisterForRemoteNotifications","kind":"identifier"},{"kind":"text","text":"("},{"text":"withDeviceToken","kind":"externalParam"},{"kind":"text","text":" "},{"text":"token","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"!)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"token","content":[{"inlineContent":[{"type":"text","text":"A token used for identifying the device with APS."}],"type":"paragraph"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationDelegate\/onDidRegisterForRemoteNotifications(withDeviceToken:)"},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onDidRegisterForRemoteNotifications","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withDeviceToken"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"!)"}],"symbolKind":"method","externalID":"c:objc(pl)PushNotificationDelegate(im)onDidRegisterForRemoteNotificationsWithDeviceToken:","roleHeading":"Instance Method","modules":[{"name":"PushwooshFramework"}],"title":"onDidRegisterForRemoteNotifications(withDeviceToken:)","role":"symbol","navigatorTitle":[{"text":"onDidRegisterForRemoteNotificationsWithDeviceToken:","kind":"identifier"}]},"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationDelegate/onDidRegisterForRemoteNotifications(withDeviceToken:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onDidRegisterForRemoteNotifications"},{"kind":"text","text":"("},{"text":"withDeviceToken","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"!)","kind":"text"}],"navigatorTitle":[{"text":"onDidRegisterForRemoteNotificationsWithDeviceToken:","kind":"identifier"}],"kind":"symbol","title":"onDidRegisterForRemoteNotifications(withDeviceToken:)","url":"\/documentation\/pushwooshframework\/pushnotificationdelegate\/ondidregisterforremotenotifications(withdevicetoken:)","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationDelegate\/onDidRegisterForRemoteNotifications(withDeviceToken:)","abstract":[{"type":"text","text":"Tells the delegate that the application has registered with Apple Push Service (APS) successfully."}],"role":"symbol","type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationDelegate":{"kind":"symbol","role":"symbol","abstract":[{"code":"PushNotificationDelegate","type":"codeVoice"},{"text":" protocol defines the methods that can be implemented in the delegate of the ","type":"text"},{"type":"codeVoice","code":"PushNotificationManager"},{"type":"text","text":" class’ singleton object."},{"type":"text","text":" "},{"type":"text","text":"These methods provide information about the key events for push notification manager such as registering with APS services, receiving push notifications or working with the received notification."},{"text":" ","type":"text"},{"type":"text","text":"These methods implementation allows to react on these events properly."}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PushNotificationDelegate","kind":"identifier"}],"title":"PushNotificationDelegate","navigatorTitle":[{"text":"PushNotificationDelegate","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationDelegate","type":"topic","url":"\/documentation\/pushwooshframework\/pushnotificationdelegate"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","type":"topic","kind":"symbol","abstract":[],"title":"PushwooshFramework","url":"\/documentation\/pushwooshframework"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"onDidRegisterForRemoteNotificationsWithDeviceToken:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onDidRegisterForRemoteNotificationsWithDeviceToken:"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"onDidRegisterForRemoteNotificationsWithDeviceToken:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"token","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"onDidRegisterForRemoteNotificationsWithDeviceToken:","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationDelegate~1onDidRegisterForRemoteNotifications(withDeviceToken:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationDelegate~1onDidRegisterForRemoteNotifications(withDeviceToken:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onDidRegisterForRemoteNotificationsWithDeviceToken:"}]},{"value":"PushNotificationDelegate","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationDelegate\/title","op":"replace"},{"op":"replace","value":[{"text":"PushNotificationDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationDelegate\/fragments"}]}]}