{"abstract":[{"type":"text","text":"Tells the delegate that the user has pressed OK on the push notification."},{"text":" ","type":"text"},{"type":"text","text":"IMPORTANT: This method is used for backwards compatibility and is deprecated. Please use the "},{"type":"codeVoice","code":"onPushAccepted:withNotification:onStart:"},{"text":" method instead","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pushnotificationdelegate\/onpushaccepted(_:withnotification:)"]},{"paths":["\/documentation\/pushwooshframework\/pushnotificationdelegate\/onpushaccepted(_:withnotification:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationDelegate\/onPushAccepted(_:withNotification:)","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onPushAccepted","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"pushManager","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)PushNotificationManager","text":"PushNotificationManager","kind":"typeIdentifier","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager"},{"text":"!, ","kind":"text"},{"text":"withNotification","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"pushNotification"},{"text":": [","kind":"text"},{"text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]!)"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The push manager that received the remote notification."}]}],"name":"pushManager"},{"name":"pushNotification","content":[{"inlineContent":[{"type":"text","text":"A dictionary that contains information referring to the remote notification, potentially including a badge number for the application icon, an alert sound, an alert message to display to the user, a notification identifier, and custom data."},{"type":"text","text":" "},{"type":"text","text":"The provider originates it as a JSON-defined dictionary that iOS converts to an NSDictionary object; the dictionary may contain only property-list objects plus NSNull."},{"text":" ","type":"text"},{"type":"text","text":"Push dictionary sample:"}],"type":"paragraph"}]}]},{"content":[{"level":2,"type":"heading","anchor":"discussion","text":"Discussion"},{"type":"codeListing","syntax":null,"code":["p = 1pb;"]},{"type":"paragraph","inlineContent":[{"text":"}","type":"text"}]}],"kind":"content"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationDelegate"]]},"kind":"symbol","metadata":{"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onPushAccepted"},{"text":"(","kind":"text"},{"text":"PushNotificationManager","preciseIdentifier":"c:objc(cs)PushNotificationManager","kind":"typeIdentifier"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"withNotification"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]!)","kind":"text"}],"title":"onPushAccepted(_:withNotification:)","platforms":[],"required":true,"externalID":"c:objc(pl)PushNotificationDelegate(im)onPushAccepted:withNotification:","role":"symbol","symbolKind":"method","modules":[{"name":"PushwooshFramework"}],"navigatorTitle":[{"text":"onPushAccepted:withNotification:","kind":"identifier"}]},"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationDelegate/onPushAccepted(_:withNotification:)":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationDelegate\/onPushAccepted(_:withNotification:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onPushAccepted"},{"text":"(","kind":"text"},{"text":"PushNotificationManager","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PushNotificationManager"},{"kind":"text","text":"!, "},{"text":"withNotification","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"text":"]!)","kind":"text"}],"abstract":[{"type":"text","text":"Tells the delegate that the user has pressed OK on the push notification."},{"text":" ","type":"text"},{"type":"text","text":"IMPORTANT: This method is used for backwards compatibility and is deprecated. Please use the "},{"code":"onPushAccepted:withNotification:onStart:","type":"codeVoice"},{"type":"text","text":" method instead"}],"type":"topic","deprecated":true,"title":"onPushAccepted(_:withNotification:)","url":"\/documentation\/pushwooshframework\/pushnotificationdelegate\/onpushaccepted(_:withnotification:)","kind":"symbol","required":true,"role":"symbol","navigatorTitle":[{"text":"onPushAccepted:withNotification:","kind":"identifier"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"url":"\/documentation\/pushwooshframework","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","kind":"symbol","abstract":[{"text":"Push notification SDK for iOS applications.","type":"text"}],"role":"collection","title":"PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationDelegate":{"kind":"symbol","title":"PushNotificationDelegate","url":"\/documentation\/pushwooshframework\/pushnotificationdelegate","type":"topic","abstract":[{"code":"PushNotificationDelegate","type":"codeVoice"},{"text":" protocol defines the methods that can be implemented in the delegate of the ","type":"text"},{"type":"codeVoice","code":"PushNotificationManager"},{"type":"text","text":" class’ singleton object."},{"type":"text","text":" "},{"type":"text","text":"These methods provide information about the key events for push notification manager such as registering with APS services, receiving push notifications or working with the received notification."},{"text":" ","type":"text"},{"type":"text","text":"These methods implementation allows to react on these events properly."}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushNotificationDelegate"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PushNotificationDelegate"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationDelegate"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationManager":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PushNotificationManager","kind":"identifier"}],"type":"topic","abstract":[{"code":"PushNotificationManager","type":"codeVoice"},{"type":"text","text":" class offers access to the singleton-instance of the push manager responsible for registering the device with the APS servers, receiving and processing push notifications."}],"title":"PushNotificationManager","url":"\/documentation\/pushwooshframework\/pushnotificationmanager","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"PushNotificationManager","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"onPushAccepted:withNotification:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onPushAccepted:withNotification:","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"text":"onPushAccepted:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PushNotificationManager","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager","preciseIdentifier":"c:objc(cs)PushNotificationManager"},{"kind":"text","text":" *) "},{"text":"pushManager","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"withNotification:"},{"kind":"text","text":"("},{"text":"NSDictionary","preciseIdentifier":"c:objc(cs)NSDictionary","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"pushNotification","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationDelegate~1onPushAccepted(_:withNotification:)\/title","value":"onPushAccepted:withNotification:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onPushAccepted:withNotification:"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationDelegate~1onPushAccepted(_:withNotification:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationDelegate\/title","value":"PushNotificationDelegate"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationDelegate\/fragments","value":[{"text":"PushNotificationDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager\/title","op":"replace","value":"PushNotificationManager"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager\/fragments","op":"replace","value":[{"kind":"identifier","text":"PushNotificationManager"}]}]}]}