{"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"required":true,"navigatorTitle":[{"text":"onPushReceived:withNotification:onStart:","kind":"identifier"}],"modules":[{"name":"PushwooshFramework"}],"symbolKind":"method","title":"onPushReceived(_:withNotification:onStart:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onPushReceived","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PushNotificationManager","preciseIdentifier":"c:objc(cs)PushNotificationManager"},{"kind":"text","text":"!, "},{"text":"withNotification","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier","text":"AnyHashable"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"]!, ","kind":"text"},{"kind":"externalParam","text":"onStart"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","roleHeading":"Instance Method","externalID":"c:objc(pl)PushNotificationDelegate(im)onPushReceived:withNotification:onStart:"},"abstract":[{"type":"text","text":"Tells the delegate that the push manager has received a remote notification."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationDelegate\/onPushReceived(_:withNotification:onStart:)"},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationDelegate"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pushnotificationdelegate\/onpushreceived(_:withnotification:onstart:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pushnotificationdelegate\/onpushreceived(_:withnotification:onstart:)"]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onPushReceived"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"pushManager","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"PushNotificationManager","kind":"typeIdentifier","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager","preciseIdentifier":"c:objc(cs)PushNotificationManager"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"withNotification"},{"kind":"text","text":" "},{"text":"pushNotification","kind":"internalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!, "},{"kind":"externalParam","text":"onStart"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"text":"The push manager that received the remote notification.","type":"text"}],"type":"paragraph"}],"name":"pushManager"},{"name":"pushNotification","content":[{"type":"paragraph","inlineContent":[{"text":"A dictionary that contains information referring to the remote notification, potentially including a badge number for the application icon, an alert sound, an alert message to display to the user, a notification identifier, and custom data.","type":"text"},{"text":" ","type":"text"},{"text":"The provider originates it as a JSON-defined dictionary that iOS converts to an NSDictionary object; the dictionary may contain only property-list objects plus NSNull.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If the application was not foreground when the push notification was received, the application will be opened with this parameter equal to "},{"type":"codeVoice","code":"YES"},{"type":"text","text":", otherwise the parameter will be "},{"code":"NO","type":"codeVoice"},{"text":".","type":"text"}]}],"name":"onStart"}],"kind":"parameters"}],"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationDelegate/onPushReceived(_:withNotification:onStart:)":{"required":true,"role":"symbol","title":"onPushReceived(_:withNotification:onStart:)","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"onPushReceived:withNotification:onStart:"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onPushReceived","kind":"identifier"},{"text":"(","kind":"text"},{"text":"PushNotificationManager","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PushNotificationManager"},{"text":"!, ","kind":"text"},{"text":"withNotification","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!, "},{"text":"onStart","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationDelegate\/onPushReceived(_:withNotification:onStart:)","abstract":[{"text":"Tells the delegate that the push manager has received a remote notification.","type":"text"}],"url":"\/documentation\/pushwooshframework\/pushnotificationdelegate\/onpushreceived(_:withnotification:onstart:)"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationDelegate":{"navigatorTitle":[{"kind":"identifier","text":"PushNotificationDelegate"}],"role":"symbol","url":"\/documentation\/pushwooshframework\/pushnotificationdelegate","abstract":[{"type":"codeVoice","code":"PushNotificationDelegate"},{"text":" protocol defines the methods that can be implemented in the delegate of the ","type":"text"},{"type":"codeVoice","code":"PushNotificationManager"},{"text":" class’ singleton object.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"These methods provide information about the key events for push notification manager such as registering with APS services, receiving push notifications or working with the received notification."},{"text":" ","type":"text"},{"text":"These methods implementation allows to react on these events properly.","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushNotificationDelegate"}],"title":"PushNotificationDelegate"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationManager":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PushNotificationManager"}],"abstract":[{"type":"codeVoice","code":"PushNotificationManager"},{"type":"text","text":" class offers access to the singleton-instance of the push manager responsible for registering the device with the APS servers, receiving and processing push notifications."}],"title":"PushNotificationManager","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PushNotificationManager","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager","url":"\/documentation\/pushwooshframework\/pushnotificationmanager"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","kind":"symbol","abstract":[],"title":"PushwooshFramework","url":"\/documentation\/pushwooshframework","type":"topic","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"onPushReceived:withNotification:onStart:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"onPushReceived:withNotification:onStart:","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"onPushReceived:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)PushNotificationManager","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager","text":"PushNotificationManager","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"pushManager"},{"text":" ","kind":"text"},{"kind":"identifier","text":"withNotification:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDictionary","text":"NSDictionary"},{"text":" *) ","kind":"text"},{"text":"pushNotification","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"onStart:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":") ","kind":"text"},{"text":"onStart","kind":"internalParam"},{"kind":"text","text":";"}]}]}},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationDelegate~1onPushReceived(_:withNotification:onStart:)\/title","value":"onPushReceived:withNotification:onStart:","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationDelegate~1onPushReceived(_:withNotification:onStart:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onPushReceived:withNotification:onStart:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationDelegate\/title","value":"PushNotificationDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationDelegate\/fragments","value":[{"text":"PushNotificationDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager\/title","value":"PushNotificationManager"},{"value":[{"kind":"identifier","text":"PushNotificationManager"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager\/fragments","op":"replace"}]}]}