{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pushnotificationdelegate\/onpushaccepted(_:withnotification:onstart:)"]},{"paths":["\/documentation\/pushwooshframework\/pushnotificationdelegate\/onpushaccepted(_:withnotification:onstart:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onPushAccepted","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"pushManager","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PushNotificationManager","text":"PushNotificationManager","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager"},{"kind":"text","text":"!, "},{"text":"withNotification","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"pushNotification","kind":"internalParam"},{"kind":"text","text":": ["},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!, "},{"kind":"externalParam","text":"onStart"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}]}],"kind":"declarations"},{"parameters":[{"name":"pushManager","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The push manager that received the remote notification."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"A dictionary that contains information about the remote notification, potentially including a badge number for the application icon, an alert sound, an alert message to display to the user, a notification identifier, and custom data.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"The provider originates it as a JSON-defined dictionary that iOS converts to an NSDictionary object; the dictionary may contain only property-list objects plus NSNull."},{"type":"text","text":" "},{"type":"text","text":"Push dictionary sample:"}]}],"name":"pushNotification"},{"name":"onStart","content":[{"type":"paragraph","inlineContent":[{"text":"If the application was not foreground when the push notification was received, the application will be opened with this parameter equal to ","type":"text"},{"code":"YES","type":"codeVoice"},{"text":", otherwise the parameter will be ","type":"text"},{"type":"codeVoice","code":"NO"},{"type":"text","text":"."}]}]}],"kind":"parameters"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationDelegate"]]},"abstract":[{"text":"Tells the delegate that the user has pressed on the push notification banner.","type":"text"}],"metadata":{"required":true,"title":"onPushAccepted(_:withNotification:onStart:)","modules":[{"name":"PushwooshFramework"}],"symbolKind":"method","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onPushAccepted"},{"kind":"text","text":"("},{"text":"PushNotificationManager","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PushNotificationManager"},{"text":"!, ","kind":"text"},{"kind":"externalParam","text":"withNotification"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]!, "},{"kind":"externalParam","text":"onStart"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":")"}],"externalID":"c:objc(pl)PushNotificationDelegate(im)onPushAccepted:withNotification:onStart:","role":"symbol","navigatorTitle":[{"text":"onPushAccepted:withNotification:onStart:","kind":"identifier"}]},"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationDelegate\/onPushAccepted(_:withNotification:onStart:)","interfaceLanguage":"swift"},"sections":[],"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"kind":"symbol","abstract":[{"type":"text","text":"Push notification SDK for iOS applications."}],"type":"topic","role":"collection","url":"\/documentation\/pushwooshframework","title":"PushwooshFramework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationManager":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager","role":"symbol","abstract":[{"type":"codeVoice","code":"PushNotificationManager"},{"text":" class offers access to the singleton-instance of the push manager responsible for registering the device with the APS servers, receiving and processing push notifications.","type":"text"}],"type":"topic","kind":"symbol","url":"\/documentation\/pushwooshframework\/pushnotificationmanager","navigatorTitle":[{"kind":"identifier","text":"PushNotificationManager"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushNotificationManager"}],"title":"PushNotificationManager"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationDelegate/onPushAccepted(_:withNotification:onStart:)":{"kind":"symbol","abstract":[{"type":"text","text":"Tells the delegate that the user has pressed on the push notification banner."}],"type":"topic","role":"symbol","url":"\/documentation\/pushwooshframework\/pushnotificationdelegate\/onpushaccepted(_:withnotification:onstart:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onPushAccepted"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)PushNotificationManager","text":"PushNotificationManager","kind":"typeIdentifier"},{"text":"!, ","kind":"text"},{"kind":"externalParam","text":"withNotification"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]!, "},{"text":"onStart","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"onPushAccepted:withNotification:onStart:"}],"title":"onPushAccepted(_:withNotification:onStart:)","required":true,"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationDelegate\/onPushAccepted(_:withNotification:onStart:)"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationDelegate":{"abstract":[{"code":"PushNotificationDelegate","type":"codeVoice"},{"type":"text","text":" protocol defines the methods that can be implemented in the delegate of the "},{"code":"PushNotificationManager","type":"codeVoice"},{"text":" class’ singleton object.","type":"text"},{"type":"text","text":" "},{"text":"These methods provide information about the key events for push notification manager such as registering with APS services, receiving push notifications or working with the received notification.","type":"text"},{"type":"text","text":" "},{"text":"These methods implementation allows to react on these events properly.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"PushNotificationDelegate"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushNotificationDelegate"}],"kind":"symbol","title":"PushNotificationDelegate","type":"topic","role":"symbol","url":"\/documentation\/pushwooshframework\/pushnotificationdelegate"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"onPushAccepted:withNotification:onStart:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onPushAccepted:withNotification:onStart:"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"text":"onPushAccepted:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PushNotificationManager","text":"PushNotificationManager","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager"},{"text":" *) ","kind":"text"},{"text":"pushManager","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"withNotification:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSDictionary","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDictionary"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"pushNotification"},{"kind":"text","text":" "},{"kind":"identifier","text":"onStart:"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"onStart","kind":"internalParam"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager\/title","value":"PushNotificationManager"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager\/fragments","value":[{"text":"PushNotificationManager","kind":"identifier"}]},{"value":"onPushAccepted:withNotification:onStart:","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationDelegate~1onPushAccepted(_:withNotification:onStart:)\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationDelegate~1onPushAccepted(_:withNotification:onStart:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"onPushAccepted:withNotification:onStart:","kind":"identifier"}]},{"value":"PushNotificationDelegate","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationDelegate\/title"},{"value":[{"kind":"identifier","text":"PushNotificationDelegate"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationDelegate\/fragments","op":"replace"}]}]}