{"kind":"symbol","abstract":[{"type":"text","text":"Sent to the delegate when push manager could not complete the tags receiving process successfully."}],"metadata":{"externalID":"c:objc(pl)PushNotificationDelegate(im)onTagsFailedToReceive:","required":true,"roleHeading":"Instance Method","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onTagsFailed"},{"kind":"text","text":"("},{"kind":"externalParam","text":"toReceive"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":")!)","kind":"text"}],"modules":[{"name":"PushwooshFramework"}],"title":"onTagsFailed(toReceive:)","navigatorTitle":[{"text":"onTagsFailedToReceive:","kind":"identifier"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationDelegate"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onTagsFailed"},{"text":"(","kind":"text"},{"text":"toReceive","kind":"externalParam"},{"kind":"text","text":" "},{"text":"error","kind":"internalParam"},{"text":": (any ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"text":")!)","kind":"text"}]}]},{"parameters":[{"name":"error","content":[{"inlineContent":[{"type":"text","text":"An NSError object that encapsulates information why receiving tags did not succeed."}],"type":"paragraph"}]}],"kind":"parameters"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pushnotificationdelegate\/ontagsfailed(toreceive:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pushnotificationdelegate\/ontagsfailed(toreceive:)"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationDelegate\/onTagsFailed(toReceive:)","interfaceLanguage":"swift"},"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"type":"topic","kind":"symbol","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","title":"PushwooshFramework","abstract":[{"type":"text","text":"Push notification SDK for iOS applications."}],"role":"collection"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationDelegate/onTagsFailed(toReceive:)":{"kind":"symbol","abstract":[{"type":"text","text":"Sent to the delegate when push manager could not complete the tags receiving process successfully."}],"role":"symbol","url":"\/documentation\/pushwooshframework\/pushnotificationdelegate\/ontagsfailed(toreceive:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"onTagsFailed","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"toReceive"},{"text":": (any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")!)","kind":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationDelegate\/onTagsFailed(toReceive:)","required":true,"title":"onTagsFailed(toReceive:)","navigatorTitle":[{"kind":"identifier","text":"onTagsFailedToReceive:"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationDelegate":{"type":"topic","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"PushNotificationDelegate","kind":"identifier"}],"abstract":[{"type":"codeVoice","code":"PushNotificationDelegate"},{"type":"text","text":" protocol defines the methods that can be implemented in the delegate of the "},{"type":"codeVoice","code":"PushNotificationManager"},{"type":"text","text":" class’ singleton object."},{"text":" ","type":"text"},{"text":"These methods provide information about the key events for push notification manager such as registering with APS services, receiving push notifications or working with the received notification.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"These methods implementation allows to react on these events properly."}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationDelegate","url":"\/documentation\/pushwooshframework\/pushnotificationdelegate","title":"PushNotificationDelegate","navigatorTitle":[{"kind":"identifier","text":"PushNotificationDelegate"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"onTagsFailedToReceive:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onTagsFailedToReceive:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"onTagsFailedToReceive:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" *) "},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}]}]}},{"value":"onTagsFailedToReceive:","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationDelegate~1onTagsFailed(toReceive:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onTagsFailedToReceive:"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationDelegate~1onTagsFailed(toReceive:)\/fragments"},{"value":"PushNotificationDelegate","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationDelegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationDelegate\/fragments","value":[{"text":"PushNotificationDelegate","kind":"identifier"}]}]}]}