{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"push","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"pushManager"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)PushNotificationManager","kind":"typeIdentifier","text":"PushNotificationManager","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager"},{"text":"!, ","kind":"text"},{"kind":"externalParam","text":"openSettingsFor"},{"kind":"text","text":" "},{"text":"notification","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UNNotification","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UNNotification"},{"text":"!)","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"parameters":[{"name":"pushManager","content":[{"inlineContent":[{"text":"PushNotificationManager instance","type":"text"}],"type":"paragraph"}]},{"name":"notification","content":[{"inlineContent":[{"type":"text","text":"Source notification"}],"type":"paragraph"}]}],"kind":"parameters"}],"abstract":[{"text":"The method will be called on the delegate when the application is launched in response to the user’s request to view in-app notification settings.","type":"text"},{"type":"text","text":" "},{"text":"Add UNAuthorizationOptionProvidesAppNotificationSettings as an option in [PushNotificationManager pushManager].additionalAuthorizationOptions to add a button to inline notification settings view and the notification settings view in Settings.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"The notification will be nil when opened from Settings."}],"metadata":{"externalID":"c:objc(pl)PushNotificationDelegate(im)pushManager:openSettingsForNotification:","platforms":[{"beta":false,"name":"iOS","introducedAt":"12.0","unavailable":false,"deprecated":false}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"push"},{"kind":"text","text":"("},{"text":"PushNotificationManager","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PushNotificationManager"},{"text":"!, ","kind":"text"},{"kind":"externalParam","text":"openSettingsFor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UNNotification","text":"UNNotification"},{"kind":"text","text":"!)"}],"roleHeading":"Instance Method","title":"push(_:openSettingsFor:)","navigatorTitle":[{"kind":"identifier","text":"pushManager:openSettingsForNotification:"}],"symbolKind":"method","role":"symbol","modules":[{"name":"PushwooshFramework"}]},"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationDelegate\/push(_:openSettingsFor:)","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationDelegate"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pushnotificationdelegate\/push(_:opensettingsfor:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pushnotificationdelegate\/push(_:opensettingsfor:)"]}],"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationDelegate/push(_:openSettingsFor:)":{"kind":"symbol","navigatorTitle":[{"text":"pushManager:openSettingsForNotification:","kind":"identifier"}],"abstract":[{"type":"text","text":"The method will be called on the delegate when the application is launched in response to the user’s request to view in-app notification settings."},{"type":"text","text":" "},{"type":"text","text":"Add UNAuthorizationOptionProvidesAppNotificationSettings as an option in [PushNotificationManager pushManager].additionalAuthorizationOptions to add a button to inline notification settings view and the notification settings view in Settings."},{"type":"text","text":" "},{"type":"text","text":"The notification will be nil when opened from Settings."}],"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationDelegate\/push(_:openSettingsFor:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"push","kind":"identifier"},{"text":"(","kind":"text"},{"text":"PushNotificationManager","preciseIdentifier":"c:objc(cs)PushNotificationManager","kind":"typeIdentifier"},{"text":"!, ","kind":"text"},{"text":"openSettingsFor","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UNNotification","text":"UNNotification","kind":"typeIdentifier"},{"text":"!)","kind":"text"}],"title":"push(_:openSettingsFor:)","url":"\/documentation\/pushwooshframework\/pushnotificationdelegate\/push(_:opensettingsfor:)"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationDelegate":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationDelegate","kind":"symbol","abstract":[{"type":"codeVoice","code":"PushNotificationDelegate"},{"type":"text","text":" protocol defines the methods that can be implemented in the delegate of the "},{"code":"PushNotificationManager","type":"codeVoice"},{"type":"text","text":" class’ singleton object."},{"text":" ","type":"text"},{"text":"These methods provide information about the key events for push notification manager such as registering with APS services, receiving push notifications or working with the received notification.","type":"text"},{"text":" ","type":"text"},{"text":"These methods implementation allows to react on these events properly.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"PushNotificationDelegate","kind":"identifier"}],"url":"\/documentation\/pushwooshframework\/pushnotificationdelegate","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"PushNotificationDelegate","kind":"identifier"}],"title":"PushNotificationDelegate"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationManager":{"url":"\/documentation\/pushwooshframework\/pushnotificationmanager","kind":"symbol","abstract":[{"code":"PushNotificationManager","type":"codeVoice"},{"text":" class offers access to the singleton-instance of the push manager responsible for registering the device with the APS servers, receiving and processing push notifications.","type":"text"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager","navigatorTitle":[{"text":"PushNotificationManager","kind":"identifier"}],"title":"PushNotificationManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PushNotificationManager","kind":"identifier"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"url":"\/documentation\/pushwooshframework","kind":"symbol","abstract":[{"text":"Push notification SDK for iOS applications.","type":"text"}],"type":"topic","role":"collection","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","title":"PushwooshFramework"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":[{"name":"iOS","unavailable":false,"beta":false,"deprecated":false,"introducedAt":"12.0"}],"path":"\/metadata\/platforms"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","value":"pushManager:openSettingsForNotification:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"pushManager:openSettingsForNotification:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"pushManager:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)PushNotificationManager","kind":"typeIdentifier","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager","text":"PushNotificationManager"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"pushManager"},{"text":" ","kind":"text"},{"kind":"identifier","text":"openSettingsForNotification:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"UNNotification","preciseIdentifier":"c:objc(cs)UNNotification"},{"kind":"text","text":" *) "},{"text":"notification","kind":"internalParam"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationDelegate~1push(_:openSettingsFor:)\/title","value":"pushManager:openSettingsForNotification:","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationDelegate~1push(_:openSettingsFor:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"pushManager:openSettingsForNotification:","kind":"identifier"}]},{"value":"PushNotificationDelegate","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationDelegate\/title","op":"replace"},{"value":[{"kind":"identifier","text":"PushNotificationDelegate"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationDelegate\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager\/title","value":"PushNotificationManager"},{"value":[{"text":"PushNotificationManager","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}