{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitViewController\/clearReadMessages()"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitViewController"]]},"abstract":[{"text":"Deletes every read message from the inbox in one batch. Useful for a","type":"text"},{"type":"text","text":" "},{"type":"text","text":"“Clear read” affordance in the nav bar. Unread (and pinned-unread)"},{"type":"text","text":" "},{"text":"messages are preserved.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"clearReadMessages"},{"kind":"text","text":"()"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","metadata":{"externalID":"c:@M@PushwooshInboxKit@objc(cs)PushwooshInboxKitViewController(im)clearReadMessages","title":"clearReadMessages()","modules":[{"name":"PushwooshInboxKit"}],"role":"symbol","roleHeading":"Instance Method","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"clearReadMessages","kind":"identifier"},{"kind":"text","text":"()"}],"navigatorTitle":[{"kind":"identifier","text":"clearReadMessages"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshinboxkit\/pushwooshinboxkitviewcontroller\/clearreadmessages()"]},{"paths":["\/documentation\/pushwooshinboxkit\/pushwooshinboxkitviewcontroller\/clearreadmessages()"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit":{"role":"collection","abstract":[{"text":"Modern UIKit inbox UI powered by Pushwoosh.","type":"text"}],"title":"PushwooshInboxKit","type":"topic","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit","url":"\/documentation\/pushwooshinboxkit"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxKitViewController":{"navigatorTitle":[{"kind":"identifier","text":"PushwooshInboxKitViewController"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitViewController","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushwooshInboxKitViewController"}],"abstract":[{"text":"Modern UIKit inbox controller backed by ","type":"text"},{"code":"PWInboxService","type":"codeVoice"},{"text":".","type":"text"}],"role":"symbol","title":"PushwooshInboxKitViewController","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxkitviewcontroller","type":"topic"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxKitViewController/clearReadMessages()":{"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxkitviewcontroller\/clearreadmessages()","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Deletes every read message from the inbox in one batch. Useful for a"},{"type":"text","text":" "},{"text":"“Clear read” affordance in the nav bar. Unread (and pinned-unread)","type":"text"},{"type":"text","text":" "},{"type":"text","text":"messages are preserved."}],"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitViewController\/clearReadMessages()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"clearReadMessages"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"clearReadMessages","kind":"identifier"}],"role":"symbol","title":"clearReadMessages()"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"clearReadMessages","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"clearReadMessages"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"clearReadMessages"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxKitViewController\/title","op":"replace","value":"PushwooshInboxKitViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxKitViewController\/fragments","value":[{"text":"PushwooshInboxKitViewController","kind":"identifier"}]},{"op":"replace","value":"clearReadMessages","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxKitViewController~1clearReadMessages()\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxKitViewController~1clearReadMessages()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"clearReadMessages"}]}]}]}