{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshinboxkit\/pushwooshinboxkitviewcontroller\/deleteallmessages()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshinboxkit\/pushwooshinboxkitviewcontroller\/deleteallmessages()"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitViewController"]]},"abstract":[{"type":"text","text":"Deletes every message in the inbox — read AND unread — in one batch and refreshes the"},{"text":" ","type":"text"},{"text":"open table immediately. Use for a “Clear all” \/ trash affordance, where the user expects","type":"text"},{"type":"text","text":" "},{"type":"text","text":"the whole inbox to empty (unlike "},{"type":"reference","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitViewController\/clearReadMessages()","isActive":true},{"text":", which keeps unread messages).","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"deleteAllMessages"},{"text":"()","kind":"text"}]}]}],"kind":"symbol","identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitViewController\/deleteAllMessages()","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"PushwooshInboxKit"}],"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"deleteAllMessages"},{"text":"()","kind":"text"}],"role":"symbol","title":"deleteAllMessages()","navigatorTitle":[{"text":"deleteAllMessages","kind":"identifier"}],"symbolKind":"method","externalID":"c:@M@PushwooshInboxKit@objc(cs)PushwooshInboxKitViewController(im)deleteAllMessages"},"sections":[],"references":{"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxKitViewController/deleteAllMessages()":{"abstract":[{"text":"Deletes every message in the inbox — read AND unread — in one batch and refreshes the","type":"text"},{"type":"text","text":" "},{"type":"text","text":"open table immediately. Use for a “Clear all” \/ trash affordance, where the user expects"},{"text":" ","type":"text"},{"text":"the whole inbox to empty (unlike ","type":"text"},{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitViewController\/clearReadMessages()","type":"reference","isActive":true},{"text":", which keeps unread messages).","type":"text"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitViewController\/deleteAllMessages()","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxkitviewcontroller\/deleteallmessages()","kind":"symbol","navigatorTitle":[{"text":"deleteAllMessages","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"deleteAllMessages","kind":"identifier"},{"kind":"text","text":"()"}],"title":"deleteAllMessages()"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit":{"kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit","title":"PushwooshInboxKit","url":"\/documentation\/pushwooshinboxkit","role":"collection","abstract":[{"text":"Modern UIKit inbox UI powered by Pushwoosh.","type":"text"}],"type":"topic"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxKitViewController/clearReadMessages()":{"abstract":[{"type":"text","text":"Deletes every read message from the inbox in one batch. Useful for a"},{"text":" ","type":"text"},{"text":"“Clear read” affordance in the nav bar. Unread (and pinned-unread)","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"messages are preserved."}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitViewController\/clearReadMessages()","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxkitviewcontroller\/clearreadmessages()","kind":"symbol","navigatorTitle":[{"text":"clearReadMessages","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"clearReadMessages","kind":"identifier"},{"kind":"text","text":"()"}],"title":"clearReadMessages()"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxKitViewController":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PushwooshInboxKitViewController","kind":"identifier"}],"navigatorTitle":[{"text":"PushwooshInboxKitViewController","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitViewController","title":"PushwooshInboxKitViewController","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxkitviewcontroller","role":"symbol","abstract":[{"type":"text","text":"Modern UIKit inbox controller backed by "},{"type":"codeVoice","code":"PWInboxService"},{"type":"text","text":"."}],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"deleteAllMessages"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"deleteAllMessages","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"text":"deleteAllMessages","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"value":"deleteAllMessages","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxKitViewController~1deleteAllMessages()\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxKitViewController~1deleteAllMessages()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"deleteAllMessages","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"clearReadMessages","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxKitViewController~1clearReadMessages()\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"clearReadMessages","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxKitViewController~1clearReadMessages()\/fragments"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxKitViewController\/title","op":"replace","value":"PushwooshInboxKitViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxKitViewController\/fragments","value":[{"text":"PushwooshInboxKitViewController","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}