{"metadata":{"roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"markReadWithMessages:"}],"symbolKind":"method","title":"markRead(messages:)","modules":[{"name":"PushwooshInboxKit"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"markRead"},{"text":"(","kind":"text"},{"text":"messages","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(pl)PWInboxMessageProtocol","text":"PWInboxMessageProtocol","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"externalID":"c:@M@PushwooshInboxKit@objc(cs)PushwooshInboxKitViewController(im)markReadWithMessages:"},"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"Marks the given messages as read both server-side and locally"},{"text":" ","type":"text"},{"type":"text","text":"(persisted to "},{"type":"codeVoice","code":"PWInboxStorage"},{"text":").","type":"text"}],"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitViewController\/markRead(messages:)","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"markRead","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"messages"},{"kind":"text","text":": ["},{"text":"PWInboxMessageProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)PWInboxMessageProtocol"},{"text":"])","kind":"text"}]}]},{"content":[{"text":"Discussion","level":2,"anchor":"discussion","type":"heading"},{"inlineContent":[{"text":"Use this from a custom delegate handler when you returned ","type":"text"},{"type":"codeVoice","code":"false"},{"type":"text","text":" "},{"text":"from ","type":"text"},{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitDelegate\/inboxKit(_:didSelect:)-2pkgo","type":"reference","isActive":true},{"type":"text","text":" (skipping"},{"type":"text","text":" "},{"text":"the default action) but still want the row to reflect the read","type":"text"},{"type":"text","text":" "},{"text":"state immediately. Idempotent — already-read messages are skipped.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Survives process restart even if the network request is still"},{"text":" ","type":"text"},{"type":"text","text":"pending acknowledgment."}],"type":"paragraph"}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshinboxkit\/pushwooshinboxkitviewcontroller\/markread(messages:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshinboxkit\/pushwooshinboxkitviewcontroller\/markread(messages:)"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitViewController"]]},"references":{"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxKitViewController/markRead(messages:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"markRead","kind":"identifier"},{"text":"(","kind":"text"},{"text":"messages","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)PWInboxMessageProtocol","text":"PWInboxMessageProtocol"},{"text":"])","kind":"text"}],"kind":"symbol","role":"symbol","title":"markRead(messages:)","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitViewController\/markRead(messages:)","navigatorTitle":[{"kind":"identifier","text":"markReadWithMessages:"}],"abstract":[{"text":"Marks the given messages as read both server-side and locally","type":"text"},{"type":"text","text":" "},{"type":"text","text":"(persisted to "},{"type":"codeVoice","code":"PWInboxStorage"},{"text":").","type":"text"}],"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxkitviewcontroller\/markread(messages:)"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxKitDelegate/inboxKit(_:didSelect:)-2pkgo":{"title":"inboxKit(_:didSelect:)","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxkitdelegate\/inboxkit(_:didselect:)-2pkgo","abstract":[{"type":"text","text":"Invoked on tap. Return "},{"type":"codeVoice","code":"true"},{"text":" to let the SDK perform the default action","type":"text"},{"type":"text","text":" "},{"text":"(richmedia, URL, or deeplink). Return ","type":"text"},{"code":"false","type":"codeVoice"},{"type":"text","text":" if the host has handled"},{"type":"text","text":" "},{"type":"text","text":"the tap itself."}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"inboxKit","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PushwooshInboxKitViewController","preciseIdentifier":"c:@M@PushwooshInboxKit@objc(cs)PushwooshInboxKitViewController"},{"text":", ","kind":"text"},{"text":"didSelect","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(pl)PWInboxMessageProtocol","text":"PWInboxMessageProtocol","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"type":"topic","required":true,"defaultImplementations":1,"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitDelegate\/inboxKit(_:didSelect:)-2pkgo"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxKitViewController":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PushwooshInboxKitViewController","kind":"identifier"}],"abstract":[{"text":"Modern UIKit inbox controller backed by ","type":"text"},{"type":"codeVoice","code":"PWInboxService"},{"type":"text","text":"."}],"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxkitviewcontroller","title":"PushwooshInboxKitViewController","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PushwooshInboxKitViewController"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitViewController"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit":{"kind":"symbol","type":"topic","title":"PushwooshInboxKit","role":"collection","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit","abstract":[{"type":"text","text":"Modern UIKit inbox UI powered by Pushwoosh."}],"url":"\/documentation\/pushwooshinboxkit"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"markReadWithMessages:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"markReadWithMessages:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"markReadWithMessages:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSArray<id<PWInboxMessageProtocol>>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"text":"messages","kind":"internalParam"},{"kind":"text","text":";"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxKitViewController~1markRead(messages:)\/title","value":"markReadWithMessages:"},{"value":[{"text":"- ","kind":"text"},{"text":"markReadWithMessages:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxKitViewController~1markRead(messages:)\/fragments"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxKitViewController\/title","op":"replace","value":"PushwooshInboxKitViewController"},{"value":[{"kind":"identifier","text":"PushwooshInboxKitViewController"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxKitViewController\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}