{"variants":[{"paths":["\/documentation\/pushwooshinboxkit\/pushwooshinboxkitviewcontroller\/setbuttontextcolor(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshinboxkit\/pushwooshinboxkitviewcontroller\/setbuttontextcolor(_:)"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"modules":[{"name":"PushwooshInboxKit"}],"navigatorTitle":[{"text":"setButtonTextColor:","kind":"identifier"}],"externalID":"c:@M@PushwooshInboxKit@objc(cs)PushwooshInboxKitViewController(im)setButtonTextColor:","role":"symbol","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setButtonTextColor","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"text":")","kind":"text"}],"roleHeading":"Instance Method","title":"setButtonTextColor(_:)"},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitViewController"]]},"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitViewController\/setButtonTextColor(_:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setButtonTextColor"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"color"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","sections":[],"references":{"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxKitViewController":{"kind":"symbol","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxkitviewcontroller","title":"PushwooshInboxKitViewController","navigatorTitle":[{"text":"PushwooshInboxKitViewController","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitViewController","abstract":[{"type":"text","text":"Modern UIKit inbox controller backed by "},{"type":"codeVoice","code":"PWInboxService"},{"type":"text","text":"."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PushwooshInboxKitViewController"}],"type":"topic"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxKitViewController/setButtonTextColor(_:)":{"type":"topic","navigatorTitle":[{"text":"setButtonTextColor:","kind":"identifier"}],"kind":"symbol","role":"symbol","abstract":[],"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitViewController\/setButtonTextColor(_:)","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxkitviewcontroller\/setbuttontextcolor(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setButtonTextColor"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"kind":"text","text":")"}],"title":"setButtonTextColor(_:)"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit":{"url":"\/documentation\/pushwooshinboxkit","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit","abstract":[{"type":"text","text":"Modern UIKit inbox UI powered by Pushwoosh."}],"kind":"symbol","role":"collection","title":"PushwooshInboxKit"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"setButtonTextColor:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"setButtonTextColor:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"setButtonTextColor:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"text":" *) ","kind":"text"},{"text":"color","kind":"internalParam"},{"text":";","kind":"text"}]}]}},{"value":"PushwooshInboxKitViewController","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxKitViewController\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxKitViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"PushwooshInboxKitViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxKitViewController~1setButtonTextColor(_:)\/title","value":"setButtonTextColor:"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxKitViewController~1setButtonTextColor(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setButtonTextColor:"}]}]}]}