{"abstract":[{"text":"Forces every message to render with the named cell kind. Pass ","type":"text"},{"type":"codeVoice","code":"nil"},{"type":"text","text":" "},{"text":"(or an unknown name) to revert to the server-driven resolver.","type":"text"}],"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/pushwooshinboxkit\/pushwooshinboxkitviewcontroller\/setforcecellkind(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshinboxkit\/pushwooshinboxkitviewcontroller\/setforcecellkind(_:)"]}],"metadata":{"symbolKind":"method","roleHeading":"Instance Method","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setForceCellKind"},{"kind":"text","text":"("},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?)","kind":"text"}],"modules":[{"name":"PushwooshInboxKit"}],"externalID":"c:@M@PushwooshInboxKit@objc(cs)PushwooshInboxKitViewController(im)setForceCellKind:","navigatorTitle":[{"kind":"identifier","text":"setForceCellKind:"}],"title":"setForceCellKind(_:)"},"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitViewController\/setForceCellKind(_:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setForceCellKind","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?)","kind":"text"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitViewController"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxKitViewController":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PushwooshInboxKitViewController","kind":"identifier"}],"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxkitviewcontroller","type":"topic","navigatorTitle":[{"text":"PushwooshInboxKitViewController","kind":"identifier"}],"kind":"symbol","title":"PushwooshInboxKitViewController","role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitViewController","abstract":[{"type":"text","text":"Modern UIKit inbox controller backed by "},{"code":"PWInboxService","type":"codeVoice"},{"text":".","type":"text"}]},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit":{"role":"collection","kind":"symbol","url":"\/documentation\/pushwooshinboxkit","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit","title":"PushwooshInboxKit","type":"topic","abstract":[{"text":"Modern UIKit inbox UI powered by Pushwoosh.","type":"text"}]},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxKitViewController/setForceCellKind(_:)":{"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitViewController\/setForceCellKind(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setForceCellKind"},{"kind":"text","text":"("},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxkitviewcontroller\/setforcecellkind(_:)","kind":"symbol","abstract":[{"text":"Forces every message to render with the named cell kind. Pass ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":" ","type":"text"},{"text":"(or an unknown name) to revert to the server-driven resolver.","type":"text"}],"navigatorTitle":[{"text":"setForceCellKind:","kind":"identifier"}],"title":"setForceCellKind(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"setForceCellKind:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"setForceCellKind:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"setForceCellKind:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"rawValue","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"PushwooshInboxKitViewController","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxKitViewController\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxKitViewController\/fragments","value":[{"text":"PushwooshInboxKitViewController","kind":"identifier"}]},{"op":"replace","value":"setForceCellKind:","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxKitViewController~1setForceCellKind(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxKitViewController~1setForceCellKind(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setForceCellKind:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}