{"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitViewController\/setPinIndicatorImage(_:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setPinIndicatorImage","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"image"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","text":"UIImage"},{"text":"?)","kind":"text"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitViewController"]]},"sections":[],"variants":[{"paths":["\/documentation\/pushwooshinboxkit\/pushwooshinboxkitviewcontroller\/setpinindicatorimage(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pushwooshinboxkit\/pushwooshinboxkitviewcontroller\/setpinindicatorimage(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"method","navigatorTitle":[{"text":"setPinIndicatorImage:","kind":"identifier"}],"roleHeading":"Instance Method","role":"symbol","externalID":"c:@M@PushwooshInboxKit@objc(cs)PushwooshInboxKitViewController(im)setPinIndicatorImage:","modules":[{"name":"PushwooshInboxKit"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setPinIndicatorImage"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"kind":"text","text":"?)"}],"title":"setPinIndicatorImage(_:)"},"references":{"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxKitViewController":{"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxkitviewcontroller","navigatorTitle":[{"text":"PushwooshInboxKitViewController","kind":"identifier"}],"abstract":[{"text":"Modern UIKit inbox controller backed by ","type":"text"},{"type":"codeVoice","code":"PWInboxService"},{"text":".","type":"text"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitViewController","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PushwooshInboxKitViewController"}],"type":"topic","title":"PushwooshInboxKitViewController"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxKitViewController/setPinIndicatorImage(_:)":{"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxkitviewcontroller\/setpinindicatorimage(_:)","navigatorTitle":[{"text":"setPinIndicatorImage:","kind":"identifier"}],"abstract":[],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitViewController\/setPinIndicatorImage(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setPinIndicatorImage"},{"text":"(","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?)"}],"type":"topic","title":"setPinIndicatorImage(_:)"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit":{"kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit","role":"collection","type":"topic","url":"\/documentation\/pushwooshinboxkit","title":"PushwooshInboxKit","abstract":[{"type":"text","text":"Modern UIKit inbox UI powered by Pushwoosh."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"setPinIndicatorImage:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setPinIndicatorImage:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"setPinIndicatorImage:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"image"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxKitViewController\/title","value":"PushwooshInboxKitViewController"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxKitViewController\/fragments","value":[{"text":"PushwooshInboxKitViewController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxKitViewController~1setPinIndicatorImage(_:)\/title","value":"setPinIndicatorImage:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setPinIndicatorImage:"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxKitViewController~1setPinIndicatorImage(_:)\/fragments","op":"replace"}]}]}