{"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"role":"symbol","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setPinningEnabled","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"title":"setPinningEnabled(_:)","externalID":"c:@M@PushwooshInboxKit@objc(cs)PushwooshInboxKitViewController(im)setPinningEnabled:","modules":[{"name":"PushwooshInboxKit"}],"navigatorTitle":[{"text":"setPinningEnabled:","kind":"identifier"}],"roleHeading":"Instance Method"},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitViewController"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitViewController\/setPinningEnabled(_:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setPinningEnabled"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"enabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshinboxkit\/pushwooshinboxkitviewcontroller\/setpinningenabled(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshinboxkit\/pushwooshinboxkitviewcontroller\/setpinningenabled(_:)"]}],"kind":"symbol","sections":[],"references":{"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxKitViewController/setPinningEnabled(_:)":{"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxkitviewcontroller\/setpinningenabled(_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setPinningEnabled","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"kind":"symbol","title":"setPinningEnabled(_:)","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitViewController\/setPinningEnabled(_:)","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"setPinningEnabled:"}]},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxKitViewController":{"kind":"symbol","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxkitviewcontroller","abstract":[{"type":"text","text":"Modern UIKit inbox controller backed by "},{"code":"PWInboxService","type":"codeVoice"},{"type":"text","text":"."}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"PushwooshInboxKitViewController"}],"title":"PushwooshInboxKitViewController","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitViewController","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PushwooshInboxKitViewController","kind":"identifier"}],"role":"symbol"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit":{"role":"collection","url":"\/documentation\/pushwooshinboxkit","title":"PushwooshInboxKit","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Modern UIKit inbox UI powered by Pushwoosh."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"setPinningEnabled:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"setPinningEnabled:","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"setPinningEnabled:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"enabled"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxKitViewController~1setPinningEnabled(_:)\/title","value":"setPinningEnabled:","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxKitViewController~1setPinningEnabled(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"setPinningEnabled:","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"PushwooshInboxKitViewController","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxKitViewController\/title"},{"value":[{"kind":"identifier","text":"PushwooshInboxKitViewController"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxKitViewController\/fragments"}]}]}