{"metadata":{"navigatorTitle":[{"text":"tableView:willDisplayCell:forRowAtIndexPath:","kind":"identifier"}],"modules":[{"name":"PushwooshInboxKit"}],"title":"tableView(_:willDisplay:forRowAt:)","symbolKind":"method","role":"symbol","externalID":"c:@CM@PushwooshInboxKit@objc(cs)PushwooshInboxKitViewController(im)tableView:willDisplayCell:forRowAtIndexPath:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tableView","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UITableView","text":"UITableView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"willDisplay","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableViewCell","text":"UITableViewCell"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"forRowAt"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath"},{"text":")","kind":"text"}],"roleHeading":"Instance Method"},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitViewController\/tableView(_:willDisplay:forRowAt:)"},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"tableView","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableView","text":"UITableView"},{"text":", ","kind":"text"},{"text":"willDisplay","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"cell"},{"kind":"text","text":": "},{"text":"UITableViewCell","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableViewCell"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"forRowAt"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"indexPath"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation9IndexPathV","kind":"typeIdentifier","text":"IndexPath"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/pushwooshinboxkit\/pushwooshinboxkitviewcontroller\/tableview(_:willdisplay:forrowat:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshinboxkit\/pushwooshinboxkitviewcontroller\/tableview(_:willdisplay:forrowat:)"]}],"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"UITableViewDelegate.tableView(_:willDisplay:forRowAt:)"},{"text":".","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitViewController","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitViewController\/UITableViewDelegate-Implementations"]]},"references":{"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxKitViewController/UITableViewDelegate-Implementations":{"type":"topic","abstract":[],"title":"UITableViewDelegate Implementations","kind":"article","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxkitviewcontroller\/uitableviewdelegate-implementations","role":"collectionGroup","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitViewController\/UITableViewDelegate-Implementations"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit":{"identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit","kind":"symbol","url":"\/documentation\/pushwooshinboxkit","title":"PushwooshInboxKit","role":"collection","abstract":[{"text":"Modern UIKit inbox UI powered by Pushwoosh.","type":"text"}],"type":"topic"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxKitViewController/tableView(_:willDisplay:forRowAt:)":{"type":"topic","abstract":[],"title":"tableView(_:willDisplay:forRowAt:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"tableView:willDisplayCell:forRowAtIndexPath:"}],"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxkitviewcontroller\/tableview(_:willdisplay:forrowat:)","role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitViewController\/tableView(_:willDisplay:forRowAt:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"tableView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UITableView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"willDisplay"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UITableViewCell","text":"UITableViewCell","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"forRowAt","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation9IndexPathV","kind":"typeIdentifier","text":"IndexPath"},{"kind":"text","text":")"}]},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxKitViewController":{"type":"topic","navigatorTitle":[{"text":"PushwooshInboxKitViewController","kind":"identifier"}],"abstract":[{"type":"text","text":"Modern UIKit inbox controller backed by "},{"code":"PWInboxService","type":"codeVoice"},{"text":".","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PushwooshInboxKitViewController","kind":"identifier"}],"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxkitviewcontroller","role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitViewController","title":"PushwooshInboxKitViewController"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"tableView:willDisplayCell:forRowAtIndexPath:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"tableView:willDisplayCell:forRowAtIndexPath:"}],"path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"tableView:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableView","text":"UITableView"},{"kind":"text","text":" *) "},{"text":"tableView","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"willDisplayCell:"},{"text":"(","kind":"text"},{"text":"UITableViewCell","preciseIdentifier":"c:objc(cs)UITableViewCell","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"cell","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"forRowAtIndexPath:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSIndexPath","text":"NSIndexPath","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"indexPath","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxKitViewController~1tableView(_:willDisplay:forRowAt:)\/title","op":"replace","value":"tableView:willDisplayCell:forRowAtIndexPath:"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxKitViewController~1tableView(_:willDisplay:forRowAt:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"tableView:willDisplayCell:forRowAtIndexPath:","kind":"identifier"}]},{"op":"replace","value":"PushwooshInboxKitViewController","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxKitViewController\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxKitViewController\/fragments","value":[{"kind":"identifier","text":"PushwooshInboxKitViewController"}]}]}]}