{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"tableView","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"tableView"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UITableView","text":"UITableView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"cellForRowAt","kind":"externalParam"},{"kind":"text","text":" "},{"text":"indexPath","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"IndexPath","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableViewCell","text":"UITableViewCell"}],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/pushwooshinboxkit\/pushwooshinboxkitviewcontroller\/tableview(_:cellforrowat:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshinboxkit\/pushwooshinboxkitviewcontroller\/tableview(_:cellforrowat:)"]}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitViewController","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitViewController\/UITableViewDataSource-Implementations"]]},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UITableViewDataSource.tableView(_:cellForRowAt:)"},{"text":".","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitViewController\/tableView(_:cellForRowAt:)"},"metadata":{"roleHeading":"Instance Method","externalID":"c:@CM@PushwooshInboxKit@objc(cs)PushwooshInboxKitViewController(im)tableView:cellForRowAtIndexPath:","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"tableView","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UITableView","kind":"typeIdentifier","text":"UITableView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cellForRowAt"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UITableViewCell","kind":"typeIdentifier","text":"UITableViewCell"}],"extendedModule":"PushwooshInboxKit","role":"symbol","navigatorTitle":[{"text":"tableView:cellForRowAtIndexPath:","kind":"identifier"}],"modules":[{"name":"PushwooshInboxKit"}],"symbolKind":"method","title":"tableView(_:cellForRowAt:)"},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxKitViewController/UITableViewDataSource-Implementations":{"type":"topic","url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxkitviewcontroller\/uitableviewdatasource-implementations","abstract":[],"role":"collectionGroup","kind":"article","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitViewController\/UITableViewDataSource-Implementations","title":"UITableViewDataSource Implementations"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit":{"role":"collection","kind":"symbol","url":"\/documentation\/pushwooshinboxkit","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit","title":"PushwooshInboxKit","type":"topic","abstract":[{"text":"Modern UIKit inbox UI powered by Pushwoosh.","type":"text"}]},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxKitViewController/tableView(_:cellForRowAt:)":{"abstract":[],"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxkitviewcontroller\/tableview(_:cellforrowat:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tableView","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"cellForRowAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableViewCell","text":"UITableViewCell"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitViewController\/tableView(_:cellForRowAt:)","navigatorTitle":[{"text":"tableView:cellForRowAtIndexPath:","kind":"identifier"}],"title":"tableView(_:cellForRowAt:)"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxKitViewController":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PushwooshInboxKitViewController","kind":"identifier"}],"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxkitviewcontroller","type":"topic","navigatorTitle":[{"text":"PushwooshInboxKitViewController","kind":"identifier"}],"kind":"symbol","title":"PushwooshInboxKitViewController","role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxKitViewController","abstract":[{"type":"text","text":"Modern UIKit inbox controller backed by "},{"code":"PWInboxService","type":"codeVoice"},{"text":".","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"tableView:cellForRowAtIndexPath:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"tableView:cellForRowAtIndexPath:"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:objc(cs)UITableViewCell","text":"UITableViewCell","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"tableView:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UITableView","text":"UITableView","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"tableView","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cellForRowAtIndexPath:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSIndexPath","text":"NSIndexPath","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"indexPath"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"tableView:cellForRowAtIndexPath:","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxKitViewController~1tableView(_:cellForRowAt:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"tableView:cellForRowAtIndexPath:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxKitViewController~1tableView(_:cellForRowAt:)\/fragments"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxKitViewController\/title","value":"PushwooshInboxKitViewController","op":"replace"},{"op":"replace","value":[{"text":"PushwooshInboxKitViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxKitViewController\/fragments"}]}]}