{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWTags\/appendValues(toListTag:)"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"appendValues","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"toListTag"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"array"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"]!) -> [","kind":"text"},{"preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier","text":"AnyHashable"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]!"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"array","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Array of values to be added to the tag."}]}]}],"kind":"parameters"},{"content":[{"type":"heading","anchor":"return-value","text":"Return Value","level":2},{"inlineContent":[{"type":"text","text":"Dictionary to be sent as the value for the tag"}],"type":"paragraph"}],"kind":"content"},{"kind":"content","content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"inlineContent":[{"type":"text","text":"Example:"}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"text":"NSDictionary *tags = @{","type":"text"},{"type":"text","text":" "},{"type":"text","text":"@“Alias” : aliasField.text,"},{"text":" ","type":"text"},{"type":"text","text":"@“FavNumber” : @([favNumField.text intValue]),"},{"text":" ","type":"text"},{"text":"@“List” : [PWTags appendValuesToListTag:@[ @“Item1” ]]","type":"text"},{"text":" ","type":"text"},{"text":"};","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"[[PushNotificationManager pushManager] setTags:tags];"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWTags"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Creates a dictionary for extending Tag’s values list with additional values"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pwtags\/appendvalues(tolisttag:)"]},{"paths":["\/documentation\/pushwooshframework\/pwtags\/appendvalues(tolisttag:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"PushwooshFramework"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"appendValues","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"toListTag"},{"kind":"text","text":": ["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"]!) -> [","kind":"text"},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!"}],"title":"appendValues(toListTag:)","roleHeading":"Type Method","navigatorTitle":[{"text":"appendValuesToListTag:","kind":"identifier"}],"role":"symbol","symbolKind":"method","externalID":"c:objc(cs)PWTags(cm)appendValuesToListTag:"},"kind":"symbol","sections":[],"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWTags":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PWTags"}],"navigatorTitle":[{"text":"PWTags","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWTags","title":"PWTags","abstract":[{"code":"PWTags","type":"codeVoice"},{"type":"text","text":" class encapsulates the methods for creating tags parameters for sending them to the server."}],"type":"topic","url":"\/documentation\/pushwooshframework\/pwtags","role":"symbol","kind":"symbol"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWTags/appendValues(toListTag:)":{"type":"topic","url":"\/documentation\/pushwooshframework\/pwtags\/appendvalues(tolisttag:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"appendValues"},{"text":"(","kind":"text"},{"text":"toListTag","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]!) -> ["},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]!","kind":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWTags\/appendValues(toListTag:)","title":"appendValues(toListTag:)","navigatorTitle":[{"kind":"identifier","text":"appendValuesToListTag:"}],"kind":"symbol","abstract":[{"type":"text","text":"Creates a dictionary for extending Tag’s values list with additional values"}],"role":"symbol"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"abstract":[],"kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","url":"\/documentation\/pushwooshframework","type":"topic","role":"collection","title":"PushwooshFramework"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"value":"appendValuesToListTag:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"appendValuesToListTag:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:objc(cs)NSDictionary","kind":"typeIdentifier","text":"NSDictionary"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"appendValuesToListTag:"},{"kind":"text","text":"("},{"text":"NSArray<NSString *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"text":"array","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWTags\/title","op":"replace","value":"PWTags"},{"value":[{"kind":"identifier","text":"PWTags"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWTags\/fragments","op":"replace"},{"value":"appendValuesToListTag:","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWTags~1appendValues(toListTag:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWTags~1appendValues(toListTag:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"appendValuesToListTag:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}