{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWTags"]]},"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeValues"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"fromListTag"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"]!) -> ["},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!"}],"externalID":"c:objc(cs)PWTags(cm)removeValuesFromListTag:","symbolKind":"method","navigatorTitle":[{"text":"removeValuesFromListTag:","kind":"identifier"}],"title":"removeValues(fromListTag:)","roleHeading":"Type Method","role":"symbol","modules":[{"name":"PushwooshFramework"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"removeValues","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fromListTag"},{"kind":"text","text":" "},{"text":"array","kind":"internalParam"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"]!) -> [","kind":"text"},{"text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]!"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"array","content":[{"inlineContent":[{"type":"text","text":"Array of values to be removed from the tag."}],"type":"paragraph"}]}]},{"kind":"content","content":[{"level":2,"anchor":"return-value","text":"Return Value","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"Dictionary to be sent as the value for the tag","type":"text"}]}]},{"kind":"content","content":[{"type":"heading","text":"Discussion","anchor":"discussion","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Example:"}]},{"inlineContent":[{"type":"text","text":"NSDictionary *tags = @{"},{"type":"text","text":" "},{"type":"text","text":"@“Alias” : aliasField.text,"},{"text":" ","type":"text"},{"text":"@“FavNumber” : @([favNumField.text intValue]),","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"@“List” : [PWTags removeValuesFromListTag:@[ @“Item1” ]]"},{"type":"text","text":" "},{"text":"};","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"[[PushNotificationManager pushManager] setTags:tags];","type":"text"}],"type":"paragraph"}]}],"kind":"symbol","abstract":[{"text":"Creates a dictionary for removing Tag’s values from existing values list","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWTags\/removeValues(fromListTag:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pwtags\/removevalues(fromlisttag:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pwtags\/removevalues(fromlisttag:)"]}],"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWTags/removeValues(fromListTag:)":{"type":"topic","title":"removeValues(fromListTag:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeValues"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"fromListTag"},{"text":": [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"]!) -> ["},{"kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"text":"]!","kind":"text"}],"kind":"symbol","abstract":[{"text":"Creates a dictionary for removing Tag’s values from existing values list","type":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWTags\/removeValues(fromListTag:)","url":"\/documentation\/pushwooshframework\/pwtags\/removevalues(fromlisttag:)","role":"symbol","navigatorTitle":[{"text":"removeValuesFromListTag:","kind":"identifier"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWTags":{"type":"topic","abstract":[{"code":"PWTags","type":"codeVoice"},{"type":"text","text":" class encapsulates the methods for creating tags parameters for sending them to the server."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PWTags","kind":"identifier"}],"navigatorTitle":[{"text":"PWTags","kind":"identifier"}],"url":"\/documentation\/pushwooshframework\/pwtags","title":"PWTags","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWTags","role":"symbol"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"kind":"symbol","role":"collection","abstract":[{"text":"Push notification SDK for iOS applications.","type":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","type":"topic","url":"\/documentation\/pushwooshframework","title":"PushwooshFramework"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"value":"removeValuesFromListTag:","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"removeValuesFromListTag:"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDictionary","text":"NSDictionary"},{"text":" *) ","kind":"text"},{"text":"removeValuesFromListTag:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSString *>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"array"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWTags~1removeValues(fromListTag:)\/title","value":"removeValuesFromListTag:"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"removeValuesFromListTag:"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWTags~1removeValues(fromListTag:)\/fragments"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWTags\/title","value":"PWTags","op":"replace"},{"value":[{"kind":"identifier","text":"PWTags"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWTags\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}