{"sections":[],"metadata":{"roleHeading":"Article","role":"article","title":"Getting Started","modules":[{"name":"PushwooshVoIP"}]},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/GettingStarted"},"kind":"article","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshvoip\/gettingstarted"]},{"paths":["\/documentation\/pushwooshvoip\/gettingstarted"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Set up VoIP push notifications with CallKit in your iOS app.","type":"text"}],"primaryContentSections":[{"content":[{"anchor":"Installation","type":"heading","text":"Installation","level":2},{"type":"tabNavigator","tabs":[{"content":[{"inlineContent":[{"text":"In Xcode, use the following URL to add the Pushwoosh dependency:","type":"text"}],"type":"paragraph"},{"code":["https:\/\/github.com\/Pushwoosh\/Pushwoosh-XCFramework"],"type":"codeListing","syntax":null},{"type":"paragraph","inlineContent":[{"text":"Select the required modules in your target:","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"image","identifier":"ios-voip-1.png"}]},{"style":"note","name":"Note","type":"aside","content":[{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Important"}]},{"text":": The modules PushwooshFramework, PushwooshCore, PushwooshBridge, and PushwooshVoIP are required.","type":"text"}]}]}],"title":"Swift Package Manager"},{"title":"CocoaPods","content":[{"inlineContent":[{"text":"Add to your Podfile:","type":"text"}],"type":"paragraph"},{"type":"codeListing","code":["pod 'PushwooshXCFramework'","pod 'PushwooshXCFramework\/PushwooshVoIP'"],"syntax":"ruby"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Then run:"}]},{"code":["pod install"],"type":"codeListing","syntax":"bash"}]}]},{"text":"Prerequisites","level":2,"type":"heading","anchor":"Prerequisites"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Before you begin, ensure you have:"}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"A Pushwoosh account"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A Pushwoosh project set up in your account"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"An iOS platform configured in your Pushwoosh project. We recommend using the Token-Based Authentication configuration as the simplest approach","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"A separate VoIP Application created in your Pushwoosh project","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Your Pushwoosh Application Code and VoIP Application Code from the Control Panel"}]}]},{"content":[{"inlineContent":[{"text":"VoIP Services Certificate (.p12) created in Apple Developer Portal","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"iOS 14.0+ deployment target"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"PushwooshFramework, PushwooshCore, and PushwooshBridge frameworks integrated in your project"}],"type":"paragraph"}]}]},{"content":[{"inlineContent":[{"type":"strong","inlineContent":[{"text":"Important","type":"text"}]},{"type":"text","text":": VoIP Applications are separate from regular push applications in Pushwoosh. You must create a dedicated VoIP Application and use its Application Code."}],"type":"paragraph"}],"style":"note","name":"Note","type":"aside"},{"type":"heading","level":2,"text":"Step 1: Add Required Capabilities","anchor":"Step-1-Add-Required-Capabilities"},{"type":"paragraph","inlineContent":[{"text":"In Xcode:","type":"text"}]},{"type":"orderedList","items":[{"content":[{"inlineContent":[{"text":"Select your target","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Go to "},{"inlineContent":[{"type":"text","text":"Signing & Capabilities"}],"type":"strong"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"Click ","type":"text"},{"inlineContent":[{"type":"text","text":"+ Capability"}],"type":"strong"},{"text":" and add ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"Push Notifications"}]}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Click "},{"type":"strong","inlineContent":[{"text":"+ Capability","type":"text"}]},{"type":"text","text":" and add "},{"inlineContent":[{"type":"text","text":"Background Modes"}],"type":"strong"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"In Background Modes, enable "},{"type":"strong","inlineContent":[{"type":"text","text":"Remote notifications"}]},{"text":" checkbox","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"In Background Modes, enable "},{"type":"strong","inlineContent":[{"type":"text","text":"Voice over IP"}]},{"type":"text","text":" checkbox"}],"type":"paragraph"}]}]},{"type":"paragraph","inlineContent":[{"identifier":"ios-voip-2.png","type":"image"}]},{"text":"Step 2: Initialize the Module","level":2,"type":"heading","anchor":"Step-2-Initialize-the-Module"},{"type":"paragraph","inlineContent":[{"text":"Initialize in ","type":"text"},{"code":"application(_:didFinishLaunchingWithOptions:)","type":"codeVoice"},{"type":"text","text":":"}]},{"type":"codeListing","syntax":"swift","code":["import UIKit","import PushwooshFramework","import PushwooshVoIP","import CallKit","import PushKit","","@main","class AppDelegate: UIResponder, UIApplicationDelegate, PWVoIPCallDelegate {","","    func application(","        _ application: UIApplication,","        didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?","    ) -> Bool {","","        Pushwoosh.VoIP.initializeVoIP(true, ringtoneSound: \"mySound.caf\", handleTypes: 1)","        Pushwoosh.VoIP.setPushwooshVoIPAppId(\"YOUR-VOIP-APP-CODE\")","        Pushwoosh.VoIP.delegate = self","","        return true","    }","","    \/\/ MARK: - Required PWVoIPCallDelegate Callbacks","","    func voipDidReceiveIncomingCall(payload: PushwooshVoIP.PWVoIPMessage) {","        \/\/ Handle incoming VoIP push","    }","","    func pwProviderDidReset(_ provider: CXProvider) {","        \/\/ Handle provider reset","    }","","    func pwProviderDidBegin(_ provider: CXProvider) {","        \/\/ Handle provider activation","    }","}"]},{"level":3,"anchor":"Parameters","text":"Parameters","type":"heading"},{"type":"table","header":"row","rows":[[[{"type":"paragraph","inlineContent":[{"type":"text","text":"Parameter"}]}],[{"type":"paragraph","inlineContent":[{"text":"Type","type":"text"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"Description"}]}]],[[{"inlineContent":[{"type":"codeVoice","code":"supportVideo"}],"type":"paragraph"}],[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"Bool"}]}],[{"inlineContent":[{"type":"text","text":"Enable video calling in CallKit UI"}],"type":"paragraph"}]],[[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"ringtoneSound"}]}],[{"inlineContent":[{"type":"codeVoice","code":"String?"}],"type":"paragraph"}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"Custom ringtone filename from app bundle (e.g., "},{"code":"\"mySound.caf\"","type":"codeVoice"},{"text":"). Pass ","type":"text"},{"type":"codeVoice","code":"nil"},{"type":"text","text":" for system default"}]}]],[[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"handleTypes"}]}],[{"type":"paragraph","inlineContent":[{"code":"Int","type":"codeVoice"}]}],[{"inlineContent":[{"type":"text","text":"Caller ID display format:"},{"text":"• ","type":"text"},{"type":"codeVoice","code":"1"},{"type":"text","text":" – Generic (usernames, custom IDs)"},{"type":"text","text":"• "},{"type":"codeVoice","code":"2"},{"type":"text","text":" – Phone Number (formatted phone numbers)"},{"type":"text","text":"• "},{"code":"3","type":"codeVoice"},{"type":"text","text":" – Email (email addresses)"}],"type":"paragraph"}]]]},{"level":2,"anchor":"Step-3-Delegate-Methods","type":"heading","text":"Step 3: Delegate Methods"},{"inlineContent":[{"type":"text","text":"The "},{"identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate","isActive":true,"type":"reference"},{"type":"text","text":" protocol provides callbacks for VoIP events:"}],"type":"paragraph"},{"type":"table","header":"row","rows":[[[{"type":"paragraph","inlineContent":[{"text":"Method","type":"text"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"Description"}]}]],[[{"type":"paragraph","inlineContent":[{"code":"voipDidReceiveIncomingCall(payload:)","type":"codeVoice"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"Called when VoIP push arrives with call information"}]}]],[[{"inlineContent":[{"type":"codeVoice","code":"pwProviderDidReset(_:)"}],"type":"paragraph"}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"Called when CallKit provider resets (end all active calls here)"}]}]],[[{"inlineContent":[{"type":"codeVoice","code":"pwProviderDidBegin(_:)"}],"type":"paragraph"}],[{"type":"paragraph","inlineContent":[{"text":"Called when CallKit provider is ready","type":"text"}]}]]]},{"text":"Step 4: Upload VoIP Certificate","level":2,"type":"heading","anchor":"Step-4-Upload-VoIP-Certificate"},{"type":"orderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Create VoIP Services Certificate in Apple Developer Portal"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Export as .p12 file"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"In Pushwoosh Control Panel, go to your VoIP Application settings"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Upload the .p12 certificate"}]}]}]},{"style":"note","type":"aside","content":[{"type":"paragraph","inlineContent":[{"inlineContent":[{"text":"Important","type":"text"}],"type":"strong"},{"text":": VoIP pushes require production gateway certificate. Sandbox certificates are not supported.","type":"text"}]}],"name":"Note"},{"type":"heading","level":2,"anchor":"Testing","text":"Testing"},{"type":"paragraph","inlineContent":[{"type":"text","text":"VoIP pushes only work on physical devices. Simulator is not supported."}]},{"inlineContent":[{"text":"Build and run your app on a physical device, then send a test VoIP push from the Pushwoosh Control Panel.","type":"text"}],"type":"paragraph"},{"level":2,"text":"Next Steps","type":"heading","anchor":"Next-Steps"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/Examples","isActive":true,"type":"reference"},{"type":"text","text":" - Code examples for common use cases"}]}]},{"content":[{"inlineContent":[{"identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate","isActive":true,"type":"reference"},{"type":"text","text":" - Full protocol reference"}],"type":"paragraph"}]}]}],"kind":"content"}],"seeAlsoSections":[{"title":"Getting Started","identifiers":["doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/Examples"],"generated":true}],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP":{"kind":"symbol","url":"\/documentation\/pushwooshvoip","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP","abstract":[{"type":"text","text":"VoIP push notifications with native call UI for iOS applications."}],"role":"collection","title":"PushwooshVoIP"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPCallDelegate":{"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PWVoIPCallDelegate"}],"type":"topic","kind":"symbol","title":"PWVoIPCallDelegate","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate","navigatorTitle":[{"text":"PWVoIPCallDelegate","kind":"identifier"}],"url":"\/documentation\/pushwooshvoip\/pwvoipcalldelegate","abstract":[{"type":"text","text":"Delegate protocol for receiving VoIP call events and CallKit callbacks."}]},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/Examples":{"role":"article","abstract":[{"text":"Practical examples for common VoIP integration scenarios.","type":"text"}],"kind":"article","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/Examples","url":"\/documentation\/pushwooshvoip\/examples","type":"topic","title":"Code Examples"},"ios-voip-1.png":{"alt":"Choose package products: PushwooshBridge, PushwooshCore, PushwooshFramework, and PushwooshVoIP","variants":[{"url":"\/images\/ios-voip-1.png","traits":["1x","light"]}],"identifier":"ios-voip-1.png","type":"image"},"ios-voip-2.png":{"alt":"Required capabilities: Push Notifications and Background Modes with Remote notifications and Voice over IP enabled","variants":[{"url":"\/images\/ios-voip-2.png","traits":["1x","light"]}],"type":"image","identifier":"ios-voip-2.png"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/seeAlsoSections","op":"replace","value":[{"generated":true,"identifiers":["doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/Examples"],"title":"Getting Started"}]},{"op":"replace","value":"PWVoIPCallDelegate","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate\/fragments","value":[{"kind":"identifier","text":"PWVoIPCallDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}