{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"abstract":[{"text":"Delegate protocol for receiving VoIP call events and CallKit callbacks.","type":"text"}],"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate","interfaceLanguage":"swift"},"metadata":{"title":"PWVoIPCallDelegate","navigatorTitle":[{"text":"PWVoIPCallDelegate","kind":"identifier"}],"role":"symbol","externalID":"c:@M@PushwooshVoIP@objc(pl)PWVoIPCallDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"PWVoIPCallDelegate","kind":"identifier"}],"roleHeading":"Protocol","modules":[{"name":"PushwooshVoIP"}],"symbolKind":"protocol"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate\/activatedAudioSession(_:didActivate:)","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate\/answerCall(_:perform:voipMessage:)","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate\/deactivatedAudioSession(_:didDeactivate:)","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate\/endCall(_:perform:voipMessage:)","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate\/heldCall(_:perform:)","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate\/mutedCall(_:perform:)","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate\/playDTMF(_:perform:)","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate\/pwProviderDidBegin(_:)","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate\/pwProviderDidReset(_:)","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate\/returnedCallController(_:)","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate\/returnedProvider(_:)","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate\/startCall(_:perform:)","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate\/voipDidCancelCall(voipMessage:)","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate\/voipDidFailToCancelCall(callId:reason:)","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate\/voipDidFailToRegisterToken(error:)","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate\/voipDidFailToReportIncomingCall(error:)","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate\/voipDidReceiveIncomingCall(payload:)","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate\/voipDidRegisterTokenSuccessfully()","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate\/voipDidReportIncomingCallSuccessfully(voipMessage:)"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"PWVoIPCallDelegate","kind":"identifier"},{"kind":"text","text":" : "},{"text":"NSObjectProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"]}],"kind":"declarations"},{"content":[{"level":2,"type":"heading","anchor":"overview","text":"Overview"},{"type":"paragraph","inlineContent":[{"text":"Implement this protocol to handle VoIP push notifications, CallKit interactions, and call lifecycle events.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Set your delegate implementation via "},{"code":"PWVoIP.delegate","type":"codeVoice"},{"text":" to receive these callbacks.","type":"text"}]}],"kind":"content"}],"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.pushwoosh.PushwooshVoIP\/objc(pl)NSObject"],"title":"Inherits From","kind":"relationships"}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP"]]},"variants":[{"paths":["\/documentation\/pushwooshvoip\/pwvoipcalldelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshvoip\/pwvoipcalldelegate"]}],"kind":"symbol","references":{"doc://com.pushwoosh.PushwooshVoIP/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/objc(pl)NSObject","title":"NSObject"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPCallDelegate/endCall(_:perform:voipMessage:)":{"navigatorTitle":[{"kind":"identifier","text":"endCall:perform:voipMessage:"}],"kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate\/endCall(_:perform:voipMessage:)","role":"symbol","type":"topic","abstract":[{"text":"Called when user ends a call.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"endCall"},{"kind":"text","text":"("},{"text":"CXProvider","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CXProvider"},{"kind":"text","text":", "},{"kind":"externalParam","text":"perform"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)CXEndCallAction","kind":"typeIdentifier","text":"CXEndCallAction"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"voipMessage"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@PushwooshVoIP@objc(cs)PWVoIPMessage","text":"PWVoIPMessage"},{"text":"?)","kind":"text"}],"url":"\/documentation\/pushwooshvoip\/pwvoipcalldelegate\/endcall(_:perform:voipmessage:)","title":"endCall(_:perform:voipMessage:)"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPCallDelegate/returnedProvider(_:)":{"title":"returnedProvider(_:)","type":"topic","abstract":[{"type":"text","text":"Called to provide the CallKit provider instance."}],"navigatorTitle":[{"kind":"identifier","text":"returnedProvider:"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"returnedProvider","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"CXProvider","preciseIdentifier":"c:objc(cs)CXProvider"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate\/returnedProvider(_:)","role":"symbol","url":"\/documentation\/pushwooshvoip\/pwvoipcalldelegate\/returnedprovider(_:)"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPCallDelegate/activatedAudioSession(_:didActivate:)":{"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate\/activatedAudioSession(_:didActivate:)","navigatorTitle":[{"text":"activatedAudioSession:didActivate:","kind":"identifier"}],"abstract":[{"text":"Called when audio session is activated.","type":"text"}],"url":"\/documentation\/pushwooshvoip\/pwvoipcalldelegate\/activatedaudiosession(_:didactivate:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"activatedAudioSession","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)CXProvider","text":"CXProvider","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"didActivate","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)AVAudioSession","text":"AVAudioSession","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","title":"activatedAudioSession(_:didActivate:)","kind":"symbol"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPCallDelegate/voipDidFailToRegisterToken(error:)":{"type":"topic","url":"\/documentation\/pushwooshvoip\/pwvoipcalldelegate\/voipdidfailtoregistertoken(error:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"voipDidFailToRegisterToken","kind":"identifier"},{"text":"(","kind":"text"},{"text":"error","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"text":")","kind":"text"}],"kind":"symbol","role":"symbol","required":true,"abstract":[{"type":"text","text":"Called when VoIP token registration fails."}],"identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate\/voipDidFailToRegisterToken(error:)","title":"voipDidFailToRegisterToken(error:)","navigatorTitle":[{"kind":"identifier","text":"voipDidFailToRegisterTokenWithError:"}]},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPCallDelegate/playDTMF(_:perform:)":{"type":"topic","url":"\/documentation\/pushwooshvoip\/pwvoipcalldelegate\/playdtmf(_:perform:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"playDTMF"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)CXProvider","text":"CXProvider","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"perform","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CXPlayDTMFCallAction","text":"CXPlayDTMFCallAction"},{"kind":"text","text":")"}],"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Called when user plays DTMF tone during the call."}],"identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate\/playDTMF(_:perform:)","title":"playDTMF(_:perform:)","navigatorTitle":[{"text":"playDTMF:perform:","kind":"identifier"}]},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPCallDelegate/deactivatedAudioSession(_:didDeactivate:)":{"type":"topic","url":"\/documentation\/pushwooshvoip\/pwvoipcalldelegate\/deactivatedaudiosession(_:diddeactivate:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"deactivatedAudioSession"},{"kind":"text","text":"("},{"text":"CXProvider","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CXProvider"},{"text":", ","kind":"text"},{"text":"didDeactivate","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AVAudioSession","preciseIdentifier":"c:objc(cs)AVAudioSession"},{"text":")","kind":"text"}],"kind":"symbol","role":"symbol","required":true,"abstract":[{"type":"text","text":"Called when audio session is deactivated."}],"identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate\/deactivatedAudioSession(_:didDeactivate:)","title":"deactivatedAudioSession(_:didDeactivate:)","navigatorTitle":[{"text":"deactivatedAudioSession:didDeactivate:","kind":"identifier"}]},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPCallDelegate/voipDidFailToCancelCall(callId:reason:)":{"url":"\/documentation\/pushwooshvoip\/pwvoipcalldelegate\/voipdidfailtocancelcall(callid:reason:)","role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate\/voipDidFailToCancelCall(callId:reason:)","abstract":[{"type":"text","text":"Called when a call cancellation attempt fails."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"voipDidFailToCancelCall"},{"kind":"text","text":"("},{"kind":"externalParam","text":"callId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"reason","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"voipDidFailToCancelCall(callId:reason:)","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"voipDidFailToCancelCallWithCallId:reason:"}]},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPCallDelegate/voipDidRegisterTokenSuccessfully()":{"abstract":[{"type":"text","text":"Called when VoIP token is successfully registered with Pushwoosh servers."}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"voipDidRegisterTokenSuccessfully"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"voipDidRegisterTokenSuccessfully","kind":"identifier"}],"role":"symbol","url":"\/documentation\/pushwooshvoip\/pwvoipcalldelegate\/voipdidregistertokensuccessfully()","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate\/voipDidRegisterTokenSuccessfully()","title":"voipDidRegisterTokenSuccessfully()"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPCallDelegate/pwProviderDidReset(_:)":{"type":"topic","navigatorTitle":[{"text":"pwProviderDidReset:","kind":"identifier"}],"abstract":[{"type":"text","text":"Called when the CallKit provider resets."}],"identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate\/pwProviderDidReset(_:)","title":"pwProviderDidReset(_:)","url":"\/documentation\/pushwooshvoip\/pwvoipcalldelegate\/pwproviderdidreset(_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pwProviderDidReset"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)CXProvider","text":"CXProvider","kind":"typeIdentifier"},{"text":")","kind":"text"}],"required":true,"kind":"symbol"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPCallDelegate/voipDidFailToReportIncomingCall(error:)":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"voipDidFailToReportIncomingCallWithError:"}],"abstract":[{"text":"Called when reporting incoming call to CallKit fails.","type":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate\/voipDidFailToReportIncomingCall(error:)","title":"voipDidFailToReportIncomingCall(error:)","url":"\/documentation\/pushwooshvoip\/pwvoipcalldelegate\/voipdidfailtoreportincomingcall(error:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"voipDidFailToReportIncomingCall"},{"text":"(","kind":"text"},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"required":true,"type":"topic"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPCallDelegate/startCall(_:perform:)":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"startCall:perform:"}],"abstract":[{"text":"Called when user initiates an outgoing call.","type":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate\/startCall(_:perform:)","title":"startCall(_:perform:)","url":"\/documentation\/pushwooshvoip\/pwvoipcalldelegate\/startcall(_:perform:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startCall","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"CXProvider","preciseIdentifier":"c:objc(cs)CXProvider"},{"kind":"text","text":", "},{"text":"perform","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CXStartCallAction","text":"CXStartCallAction"},{"kind":"text","text":")"}],"kind":"symbol"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPCallDelegate/voipDidReceiveIncomingCall(payload:)":{"kind":"symbol","navigatorTitle":[{"text":"voipDidReceiveIncomingCallWithPayload:","kind":"identifier"}],"abstract":[{"type":"text","text":"Called when a VoIP push notification arrives."}],"identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate\/voipDidReceiveIncomingCall(payload:)","title":"voipDidReceiveIncomingCall(payload:)","url":"\/documentation\/pushwooshvoip\/pwvoipcalldelegate\/voipdidreceiveincomingcall(payload:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"voipDidReceiveIncomingCall","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"payload"},{"text":": ","kind":"text"},{"text":"PWVoIPMessage","kind":"typeIdentifier","preciseIdentifier":"c:@M@PushwooshVoIP@objc(cs)PWVoIPMessage"},{"text":")","kind":"text"}],"required":true,"type":"topic"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPCallDelegate/heldCall(_:perform:)":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"heldCall:perform:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"heldCall"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"CXProvider","preciseIdentifier":"c:objc(cs)CXProvider"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"perform"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)CXSetHeldCallAction","kind":"typeIdentifier","text":"CXSetHeldCallAction"},{"text":")","kind":"text"}],"url":"\/documentation\/pushwooshvoip\/pwvoipcalldelegate\/heldcall(_:perform:)","role":"symbol","abstract":[{"type":"text","text":"Called when user puts the call on hold or resumes it."}],"kind":"symbol","title":"heldCall(_:perform:)","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate\/heldCall(_:perform:)"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPCallDelegate":{"navigatorTitle":[{"text":"PWVoIPCallDelegate","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Delegate protocol for receiving VoIP call events and CallKit callbacks."}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PWVoIPCallDelegate"}],"title":"PWVoIPCallDelegate","url":"\/documentation\/pushwooshvoip\/pwvoipcalldelegate"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPCallDelegate/answerCall(_:perform:voipMessage:)":{"title":"answerCall(_:perform:voipMessage:)","abstract":[{"type":"text","text":"Called when user answers an incoming call."}],"identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate\/answerCall(_:perform:voipMessage:)","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"answerCall:perform:voipMessage:","kind":"identifier"}],"url":"\/documentation\/pushwooshvoip\/pwvoipcalldelegate\/answercall(_:perform:voipmessage:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"answerCall"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)CXProvider","kind":"typeIdentifier","text":"CXProvider"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"perform"},{"kind":"text","text":": "},{"text":"CXAnswerCallAction","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CXAnswerCallAction"},{"kind":"text","text":", "},{"kind":"externalParam","text":"voipMessage"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"PWVoIPMessage","preciseIdentifier":"c:@M@PushwooshVoIP@objc(cs)PWVoIPMessage"},{"kind":"text","text":"?)"}]},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPCallDelegate/voipDidCancelCall(voipMessage:)":{"title":"voipDidCancelCall(voipMessage:)","navigatorTitle":[{"kind":"identifier","text":"voipDidCancelCallWithVoipMessage:"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"voipDidCancelCall"},{"kind":"text","text":"("},{"text":"voipMessage","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"PWVoIPMessage","preciseIdentifier":"c:@M@PushwooshVoIP@objc(cs)PWVoIPMessage"},{"text":")","kind":"text"}],"abstract":[{"text":"Called when a call is remotely cancelled via VoIP push before the user answers.","type":"text"}],"type":"topic","url":"\/documentation\/pushwooshvoip\/pwvoipcalldelegate\/voipdidcancelcall(voipmessage:)","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate\/voipDidCancelCall(voipMessage:)"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPCallDelegate/returnedCallController(_:)":{"navigatorTitle":[{"kind":"identifier","text":"returnedCallController:"}],"title":"returnedCallController(_:)","type":"topic","abstract":[{"type":"text","text":"Called to provide the call controller instance."}],"role":"symbol","url":"\/documentation\/pushwooshvoip\/pwvoipcalldelegate\/returnedcallcontroller(_:)","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate\/returnedCallController(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"returnedCallController"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)CXCallController","kind":"typeIdentifier","text":"CXCallController"},{"text":")","kind":"text"}]},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPCallDelegate/voipDidReportIncomingCallSuccessfully(voipMessage:)":{"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate\/voipDidReportIncomingCallSuccessfully(voipMessage:)","required":true,"navigatorTitle":[{"text":"voipDidReportIncomingCallSuccessfullyWithVoipMessage:","kind":"identifier"}],"abstract":[{"type":"text","text":"Called when incoming call is successfully reported to CallKit."}],"url":"\/documentation\/pushwooshvoip\/pwvoipcalldelegate\/voipdidreportincomingcallsuccessfully(voipmessage:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"voipDidReportIncomingCallSuccessfully"},{"kind":"text","text":"("},{"kind":"externalParam","text":"voipMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PWVoIPMessage","preciseIdentifier":"c:@M@PushwooshVoIP@objc(cs)PWVoIPMessage"},{"text":")","kind":"text"}],"role":"symbol","kind":"symbol","title":"voipDidReportIncomingCallSuccessfully(voipMessage:)"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP":{"url":"\/documentation\/pushwooshvoip","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP","abstract":[{"type":"text","text":"VoIP push notifications with native call UI for iOS applications."}],"title":"PushwooshVoIP","type":"topic","role":"collection","kind":"symbol"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPCallDelegate/pwProviderDidBegin(_:)":{"type":"topic","url":"\/documentation\/pushwooshvoip\/pwvoipcalldelegate\/pwproviderdidbegin(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pwProviderDidBegin"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)CXProvider","text":"CXProvider","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","role":"symbol","required":true,"abstract":[{"type":"text","text":"Called when the CallKit provider is ready to handle calls."}],"identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate\/pwProviderDidBegin(_:)","title":"pwProviderDidBegin(_:)","navigatorTitle":[{"kind":"identifier","text":"pwProviderDidBegin:"}]},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPCallDelegate/mutedCall(_:perform:)":{"type":"topic","url":"\/documentation\/pushwooshvoip\/pwvoipcalldelegate\/mutedcall(_:perform:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mutedCall","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CXProvider","preciseIdentifier":"c:objc(cs)CXProvider"},{"text":", ","kind":"text"},{"text":"perform","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CXSetMutedCallAction","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CXSetMutedCallAction"},{"kind":"text","text":")"}],"kind":"symbol","role":"symbol","abstract":[{"text":"Called when user mutes or unmutes the call.","type":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate\/mutedCall(_:perform:)","title":"mutedCall(_:perform:)","navigatorTitle":[{"kind":"identifier","text":"mutedCall:perform:"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Protocol","path":"\/metadata\/roleHeading"},{"value":"PWVoIPCallDelegate","path":"\/metadata\/title","op":"replace"},{"value":"protocol","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"PWVoIPCallDelegate","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"PWVoIPCallDelegate"}]},{"op":"replace","value":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate\/activatedAudioSession(_:didActivate:)","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate\/answerCall(_:perform:voipMessage:)","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate\/deactivatedAudioSession(_:didDeactivate:)","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate\/endCall(_:perform:voipMessage:)","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate\/heldCall(_:perform:)","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate\/mutedCall(_:perform:)","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate\/playDTMF(_:perform:)","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate\/pwProviderDidBegin(_:)","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate\/pwProviderDidReset(_:)","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate\/returnedCallController(_:)","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate\/returnedProvider(_:)","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate\/startCall(_:perform:)","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate\/voipDidCancelCall(voipMessage:)","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate\/voipDidFailToCancelCall(callId:reason:)","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate\/voipDidFailToRegisterToken(error:)","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate\/voipDidFailToReportIncomingCall(error:)","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate\/voipDidReceiveIncomingCall(payload:)","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate\/voipDidRegisterTokenSuccessfully()","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate\/voipDidReportIncomingCallSuccessfully(voipMessage:)"],"title":"Instance Methods"}],"path":"\/topicSections"},{"path":"\/relationshipsSections","value":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.pushwoosh.PushwooshVoIP\/objc(pl)NSObject"],"title":"Inherits From","kind":"relationships"}],"op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PWVoIPCallDelegate"},{"kind":"text","text":" <"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(pl)NSObject"},{"text":">","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate~1endCall(_:perform:voipMessage:)\/title","value":"endCall:perform:voipMessage:"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate~1endCall(_:perform:voipMessage:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"endCall:perform:voipMessage:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate~1returnedProvider(_:)\/title","value":"returnedProvider:"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate~1returnedProvider(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"returnedProvider:","kind":"identifier"}]},{"value":"activatedAudioSession:didActivate:","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate~1activatedAudioSession(_:didActivate:)\/title","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"activatedAudioSession:didActivate:"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate~1activatedAudioSession(_:didActivate:)\/fragments"},{"value":"voipDidFailToRegisterTokenWithError:","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate~1voipDidFailToRegisterToken(error:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate~1voipDidFailToRegisterToken(error:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"voipDidFailToRegisterTokenWithError:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate~1playDTMF(_:perform:)\/title","value":"playDTMF:perform:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"playDTMF:perform:"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate~1playDTMF(_:perform:)\/fragments"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate~1deactivatedAudioSession(_:didDeactivate:)\/title","value":"deactivatedAudioSession:didDeactivate:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate~1deactivatedAudioSession(_:didDeactivate:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"deactivatedAudioSession:didDeactivate:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate~1voipDidFailToCancelCall(callId:reason:)\/title","value":"voipDidFailToCancelCallWithCallId:reason:","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate~1voipDidFailToCancelCall(callId:reason:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"voipDidFailToCancelCallWithCallId:reason:"}]},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate~1voipDidRegisterTokenSuccessfully()\/title","value":"voipDidRegisterTokenSuccessfully","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"voipDidRegisterTokenSuccessfully","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate~1voipDidRegisterTokenSuccessfully()\/fragments"},{"op":"replace","value":"pwProviderDidReset:","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate~1pwProviderDidReset(_:)\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate~1pwProviderDidReset(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"pwProviderDidReset:","kind":"identifier"}]},{"op":"replace","value":"voipDidFailToReportIncomingCallWithError:","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate~1voipDidFailToReportIncomingCall(error:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate~1voipDidFailToReportIncomingCall(error:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"voipDidFailToReportIncomingCallWithError:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate~1startCall(_:perform:)\/title","value":"startCall:perform:"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate~1startCall(_:perform:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"startCall:perform:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate~1voipDidReceiveIncomingCall(payload:)\/title","value":"voipDidReceiveIncomingCallWithPayload:"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate~1voipDidReceiveIncomingCall(payload:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"voipDidReceiveIncomingCallWithPayload:"}],"op":"replace"},{"value":"heldCall:perform:","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate~1heldCall(_:perform:)\/title","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"heldCall:perform:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate~1heldCall(_:perform:)\/fragments"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate\/title","value":"PWVoIPCallDelegate","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate\/fragments","value":[{"text":"PWVoIPCallDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate~1answerCall(_:perform:voipMessage:)\/title","value":"answerCall:perform:voipMessage:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"answerCall:perform:voipMessage:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate~1answerCall(_:perform:voipMessage:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate~1voipDidCancelCall(voipMessage:)\/title","value":"voipDidCancelCallWithVoipMessage:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"voipDidCancelCallWithVoipMessage:"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate~1voipDidCancelCall(voipMessage:)\/fragments"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate~1returnedCallController(_:)\/title","value":"returnedCallController:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"returnedCallController:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate~1returnedCallController(_:)\/fragments","op":"replace"},{"value":"voipDidReportIncomingCallSuccessfullyWithVoipMessage:","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate~1voipDidReportIncomingCallSuccessfully(voipMessage:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate~1voipDidReportIncomingCallSuccessfully(voipMessage:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"voipDidReportIncomingCallSuccessfullyWithVoipMessage:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate~1pwProviderDidBegin(_:)\/title","value":"pwProviderDidBegin:"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate~1pwProviderDidBegin(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"pwProviderDidBegin:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate~1mutedCall(_:perform:)\/title","value":"mutedCall:perform:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate~1mutedCall(_:perform:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"mutedCall:perform:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}