{"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"role":"collection","title":"PushwooshGRPC","roleHeading":"Framework","symbolKind":"module","externalID":"PushwooshGRPC","modules":[{"name":"PushwooshGRPC"}]},"sections":[],"topicSections":[{"title":"Classes","identifiers":["doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/PushwooshGRPCImplementation"]},{"title":"Structures","identifiers":["doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_ApplicationOpenRequest","doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_ApplicationOpenResponse","doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_CheckDeviceRequest","doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_CheckDeviceResponse","doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_DeleteDeviceRequest","doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_DeleteDeviceResponse","doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_DeleteUserRequest","doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_DeleteUserResponse","doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_Device","doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_EmailLinkClickRequest","doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_EmailLinkClickResponse","doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_FCMKey","doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_GetInAppsRequest","doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_GetInAppsResponse","doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_GetPlatformConfigurationRequest","doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_GetPlatformConfigurationResponse","doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_GetTagsRequest","doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_GetTagsResponse","doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_GetUnregisteredDevicesRequest","doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_GetUnregisteredDevicesResponse","doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_LoadDevicesRequest","doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_LoadDevicesResponse","doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_Location","doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_MessageDeliveryRequest","doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_MessageDeliveryResponse","doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_MultiRegisterDeviceRequest","doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_MultiRegisterDeviceResponse","doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_PushStatRequest","doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_PushStatResponse","doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_RegisterDeviceRequest","doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_RegisterDeviceResponse","doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_RegisterUserRequest","doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_RegisterUserResponse","doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_RichMediaActionRequest","doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_RichMediaActionResponse","doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_SetActivityPushToStartTokenRequest","doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_SetActivityPushToStartTokenResponse","doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_SetActivityTokenRequest","doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_SetActivityTokenResponse","doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_SetAttributesRequest","doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_SetAttributesResponse","doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_SetBadgeRequest","doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_SetBadgeResponse","doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_SetTagsRequest","doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_SetTagsResponse","doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_StringList","doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_Tag","doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_TagList","doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_UnregisterDeviceRequest","doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_UnregisterDeviceResponse","doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_User","doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_WebKey","doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_PostEventApi_PostEventRequest","doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_PostEventApi_PostEventResponse","doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_PostEventApi_RichMedia","doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_PostEventApi_ShowInappMessageRequest","doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_PostEventApi_ShowInappMessageResponse"]}],"kind":"symbol","hierarchy":{"paths":[[]]},"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshgrpc"]},{"paths":["\/documentation\/pushwooshgrpc"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.pushwoosh.PushwooshGRPC/documentation/PushwooshGRPC/Pushwoosh_DeviceApi_V2_EmailLinkClickRequest":{"abstract":[],"role":"symbol","title":"Pushwoosh_DeviceApi_V2_EmailLinkClickRequest","navigatorTitle":[{"text":"Pushwoosh_DeviceApi_V2_EmailLinkClickRequest","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_EmailLinkClickRequest","kind":"symbol","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Pushwoosh_DeviceApi_V2_EmailLinkClickRequest","kind":"identifier"}],"url":"\/documentation\/pushwooshgrpc\/pushwoosh_deviceapi_v2_emaillinkclickrequest"},"doc://com.pushwoosh.PushwooshGRPC/documentation/PushwooshGRPC/PushwooshGRPCImplementation":{"abstract":[],"role":"symbol","title":"PushwooshGRPCImplementation","navigatorTitle":[{"text":"PushwooshGRPCImplementation","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/PushwooshGRPCImplementation","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PushwooshGRPCImplementation"}],"url":"\/documentation\/pushwooshgrpc\/pushwooshgrpcimplementation"},"doc://com.pushwoosh.PushwooshGRPC/documentation/PushwooshGRPC/Pushwoosh_DeviceApi_V2_RegisterUserResponse":{"role":"symbol","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Pushwoosh_DeviceApi_V2_RegisterUserResponse","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_RegisterUserResponse","abstract":[],"url":"\/documentation\/pushwooshgrpc\/pushwoosh_deviceapi_v2_registeruserresponse","title":"Pushwoosh_DeviceApi_V2_RegisterUserResponse","type":"topic","navigatorTitle":[{"text":"Pushwoosh_DeviceApi_V2_RegisterUserResponse","kind":"identifier"}]},"doc://com.pushwoosh.PushwooshGRPC/documentation/PushwooshGRPC/Pushwoosh_DeviceApi_V2_RichMediaActionRequest":{"url":"\/documentation\/pushwooshgrpc\/pushwoosh_deviceapi_v2_richmediaactionrequest","identifier":"doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_RichMediaActionRequest","type":"topic","kind":"symbol","abstract":[],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Pushwoosh_DeviceApi_V2_RichMediaActionRequest","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Pushwoosh_DeviceApi_V2_RichMediaActionRequest"}],"role":"symbol","title":"Pushwoosh_DeviceApi_V2_RichMediaActionRequest"},"doc://com.pushwoosh.PushwooshGRPC/documentation/PushwooshGRPC/Pushwoosh_PostEventApi_PostEventResponse":{"identifier":"doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_PostEventApi_PostEventResponse","navigatorTitle":[{"text":"Pushwoosh_PostEventApi_PostEventResponse","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"Pushwoosh_PostEventApi_PostEventResponse","url":"\/documentation\/pushwooshgrpc\/pushwoosh_posteventapi_posteventresponse","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"Pushwoosh_PostEventApi_PostEventResponse","kind":"identifier"}],"abstract":[],"type":"topic"},"doc://com.pushwoosh.PushwooshGRPC/documentation/PushwooshGRPC/Pushwoosh_DeviceApi_V2_SetActivityPushToStartTokenResponse":{"url":"\/documentation\/pushwooshgrpc\/pushwoosh_deviceapi_v2_setactivitypushtostarttokenresponse","identifier":"doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_SetActivityPushToStartTokenResponse","type":"topic","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Pushwoosh_DeviceApi_V2_SetActivityPushToStartTokenResponse"}],"navigatorTitle":[{"text":"Pushwoosh_DeviceApi_V2_SetActivityPushToStartTokenResponse","kind":"identifier"}],"role":"symbol","title":"Pushwoosh_DeviceApi_V2_SetActivityPushToStartTokenResponse"},"doc://com.pushwoosh.PushwooshGRPC/documentation/PushwooshGRPC/Pushwoosh_DeviceApi_V2_DeleteDeviceRequest":{"role":"symbol","abstract":[],"identifier":"doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_DeleteDeviceRequest","type":"topic","title":"Pushwoosh_DeviceApi_V2_DeleteDeviceRequest","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Pushwoosh_DeviceApi_V2_DeleteDeviceRequest"}],"url":"\/documentation\/pushwooshgrpc\/pushwoosh_deviceapi_v2_deletedevicerequest","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"Pushwoosh_DeviceApi_V2_DeleteDeviceRequest","kind":"identifier"}]},"doc://com.pushwoosh.PushwooshGRPC/documentation/PushwooshGRPC/Pushwoosh_DeviceApi_V2_SetBadgeRequest":{"role":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_SetBadgeRequest","title":"Pushwoosh_DeviceApi_V2_SetBadgeRequest","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Pushwoosh_DeviceApi_V2_SetBadgeRequest"}],"url":"\/documentation\/pushwooshgrpc\/pushwoosh_deviceapi_v2_setbadgerequest","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"Pushwoosh_DeviceApi_V2_SetBadgeRequest","kind":"identifier"}]},"doc://com.pushwoosh.PushwooshGRPC/documentation/PushwooshGRPC/Pushwoosh_DeviceApi_V2_WebKey":{"role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Pushwoosh_DeviceApi_V2_WebKey"}],"abstract":[],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Pushwoosh_DeviceApi_V2_WebKey"}],"url":"\/documentation\/pushwooshgrpc\/pushwoosh_deviceapi_v2_webkey","title":"Pushwoosh_DeviceApi_V2_WebKey","identifier":"doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_WebKey"},"doc://com.pushwoosh.PushwooshGRPC/documentation/PushwooshGRPC/Pushwoosh_DeviceApi_V2_RegisterUserRequest":{"type":"topic","abstract":[],"url":"\/documentation\/pushwooshgrpc\/pushwoosh_deviceapi_v2_registeruserrequest","identifier":"doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_RegisterUserRequest","title":"Pushwoosh_DeviceApi_V2_RegisterUserRequest","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"Pushwoosh_DeviceApi_V2_RegisterUserRequest","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Pushwoosh_DeviceApi_V2_RegisterUserRequest"}]},"doc://com.pushwoosh.PushwooshGRPC/documentation/PushwooshGRPC/Pushwoosh_DeviceApi_V2_DeleteUserRequest":{"url":"\/documentation\/pushwooshgrpc\/pushwoosh_deviceapi_v2_deleteuserrequest","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Pushwoosh_DeviceApi_V2_DeleteUserRequest"}],"navigatorTitle":[{"kind":"identifier","text":"Pushwoosh_DeviceApi_V2_DeleteUserRequest"}],"kind":"symbol","abstract":[],"role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_DeleteUserRequest","title":"Pushwoosh_DeviceApi_V2_DeleteUserRequest"},"doc://com.pushwoosh.PushwooshGRPC/documentation/PushwooshGRPC/Pushwoosh_DeviceApi_V2_GetTagsRequest":{"kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Pushwoosh_DeviceApi_V2_GetTagsRequest","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_GetTagsRequest","title":"Pushwoosh_DeviceApi_V2_GetTagsRequest","abstract":[],"type":"topic","url":"\/documentation\/pushwooshgrpc\/pushwoosh_deviceapi_v2_gettagsrequest","role":"symbol","navigatorTitle":[{"text":"Pushwoosh_DeviceApi_V2_GetTagsRequest","kind":"identifier"}]},"doc://com.pushwoosh.PushwooshGRPC/documentation/PushwooshGRPC/Pushwoosh_DeviceApi_V2_Location":{"navigatorTitle":[{"kind":"identifier","text":"Pushwoosh_DeviceApi_V2_Location"}],"url":"\/documentation\/pushwooshgrpc\/pushwoosh_deviceapi_v2_location","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Pushwoosh_DeviceApi_V2_Location"}],"role":"symbol","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_Location","title":"Pushwoosh_DeviceApi_V2_Location"},"doc://com.pushwoosh.PushwooshGRPC/documentation/PushwooshGRPC/Pushwoosh_DeviceApi_V2_SetTagsRequest":{"kind":"symbol","abstract":[],"identifier":"doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_SetTagsRequest","role":"symbol","navigatorTitle":[{"text":"Pushwoosh_DeviceApi_V2_SetTagsRequest","kind":"identifier"}],"title":"Pushwoosh_DeviceApi_V2_SetTagsRequest","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Pushwoosh_DeviceApi_V2_SetTagsRequest"}],"type":"topic","url":"\/documentation\/pushwooshgrpc\/pushwoosh_deviceapi_v2_settagsrequest"},"doc://com.pushwoosh.PushwooshGRPC/documentation/PushwooshGRPC/Pushwoosh_DeviceApi_V2_GetUnregisteredDevicesRequest":{"url":"\/documentation\/pushwooshgrpc\/pushwoosh_deviceapi_v2_getunregistereddevicesrequest","title":"Pushwoosh_DeviceApi_V2_GetUnregisteredDevicesRequest","role":"symbol","abstract":[],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"Pushwoosh_DeviceApi_V2_GetUnregisteredDevicesRequest","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Pushwoosh_DeviceApi_V2_GetUnregisteredDevicesRequest"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_GetUnregisteredDevicesRequest","type":"topic"},"doc://com.pushwoosh.PushwooshGRPC/documentation/PushwooshGRPC/Pushwoosh_DeviceApi_V2_MultiRegisterDeviceRequest":{"url":"\/documentation\/pushwooshgrpc\/pushwoosh_deviceapi_v2_multiregisterdevicerequest","identifier":"doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_MultiRegisterDeviceRequest","type":"topic","abstract":[],"kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Pushwoosh_DeviceApi_V2_MultiRegisterDeviceRequest"}],"navigatorTitle":[{"text":"Pushwoosh_DeviceApi_V2_MultiRegisterDeviceRequest","kind":"identifier"}],"role":"symbol","title":"Pushwoosh_DeviceApi_V2_MultiRegisterDeviceRequest"},"doc://com.pushwoosh.PushwooshGRPC/documentation/PushwooshGRPC/Pushwoosh_PostEventApi_RichMedia":{"title":"Pushwoosh_PostEventApi_RichMedia","identifier":"doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_PostEventApi_RichMedia","type":"topic","url":"\/documentation\/pushwooshgrpc\/pushwoosh_posteventapi_richmedia","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Pushwoosh_PostEventApi_RichMedia"}],"abstract":[],"navigatorTitle":[{"text":"Pushwoosh_PostEventApi_RichMedia","kind":"identifier"}],"role":"symbol"},"doc://com.pushwoosh.PushwooshGRPC/documentation/PushwooshGRPC/Pushwoosh_DeviceApi_V2_SetBadgeResponse":{"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Pushwoosh_DeviceApi_V2_SetBadgeResponse"}],"abstract":[],"kind":"symbol","title":"Pushwoosh_DeviceApi_V2_SetBadgeResponse","identifier":"doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_SetBadgeResponse","url":"\/documentation\/pushwooshgrpc\/pushwoosh_deviceapi_v2_setbadgeresponse","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Pushwoosh_DeviceApi_V2_SetBadgeResponse"}]},"doc://com.pushwoosh.PushwooshGRPC/documentation/PushwooshGRPC/Pushwoosh_DeviceApi_V2_GetPlatformConfigurationRequest":{"role":"symbol","abstract":[],"identifier":"doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_GetPlatformConfigurationRequest","type":"topic","title":"Pushwoosh_DeviceApi_V2_GetPlatformConfigurationRequest","kind":"symbol","navigatorTitle":[{"text":"Pushwoosh_DeviceApi_V2_GetPlatformConfigurationRequest","kind":"identifier"}],"url":"\/documentation\/pushwooshgrpc\/pushwoosh_deviceapi_v2_getplatformconfigurationrequest","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"Pushwoosh_DeviceApi_V2_GetPlatformConfigurationRequest","kind":"identifier"}]},"doc://com.pushwoosh.PushwooshGRPC/documentation/PushwooshGRPC/Pushwoosh_DeviceApi_V2_PushStatResponse":{"url":"\/documentation\/pushwooshgrpc\/pushwoosh_deviceapi_v2_pushstatresponse","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"Pushwoosh_DeviceApi_V2_PushStatResponse","kind":"identifier"}],"navigatorTitle":[{"text":"Pushwoosh_DeviceApi_V2_PushStatResponse","kind":"identifier"}],"type":"topic","title":"Pushwoosh_DeviceApi_V2_PushStatResponse","identifier":"doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_PushStatResponse","kind":"symbol"},"doc://com.pushwoosh.PushwooshGRPC/documentation/PushwooshGRPC/Pushwoosh_DeviceApi_V2_GetPlatformConfigurationResponse":{"title":"Pushwoosh_DeviceApi_V2_GetPlatformConfigurationResponse","url":"\/documentation\/pushwooshgrpc\/pushwoosh_deviceapi_v2_getplatformconfigurationresponse","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"Pushwoosh_DeviceApi_V2_GetPlatformConfigurationResponse","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"Pushwoosh_DeviceApi_V2_GetPlatformConfigurationResponse","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_GetPlatformConfigurationResponse"},"doc://com.pushwoosh.PushwooshGRPC/documentation/PushwooshGRPC/Pushwoosh_PostEventApi_ShowInappMessageResponse":{"identifier":"doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_PostEventApi_ShowInappMessageResponse","abstract":[],"role":"symbol","kind":"symbol","title":"Pushwoosh_PostEventApi_ShowInappMessageResponse","navigatorTitle":[{"kind":"identifier","text":"Pushwoosh_PostEventApi_ShowInappMessageResponse"}],"type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Pushwoosh_PostEventApi_ShowInappMessageResponse"}],"url":"\/documentation\/pushwooshgrpc\/pushwoosh_posteventapi_showinappmessageresponse"},"doc://com.pushwoosh.PushwooshGRPC/documentation/PushwooshGRPC/Pushwoosh_DeviceApi_V2_MessageDeliveryRequest":{"role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Pushwoosh_DeviceApi_V2_MessageDeliveryRequest"}],"navigatorTitle":[{"text":"Pushwoosh_DeviceApi_V2_MessageDeliveryRequest","kind":"identifier"}],"title":"Pushwoosh_DeviceApi_V2_MessageDeliveryRequest","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_MessageDeliveryRequest","url":"\/documentation\/pushwooshgrpc\/pushwoosh_deviceapi_v2_messagedeliveryrequest","kind":"symbol","abstract":[]},"doc://com.pushwoosh.PushwooshGRPC/documentation/PushwooshGRPC/Pushwoosh_DeviceApi_V2_TagList":{"navigatorTitle":[{"text":"Pushwoosh_DeviceApi_V2_TagList","kind":"identifier"}],"url":"\/documentation\/pushwooshgrpc\/pushwoosh_deviceapi_v2_taglist","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Pushwoosh_DeviceApi_V2_TagList"}],"role":"symbol","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_TagList","title":"Pushwoosh_DeviceApi_V2_TagList"},"doc://com.pushwoosh.PushwooshGRPC/documentation/PushwooshGRPC/Pushwoosh_DeviceApi_V2_FCMKey":{"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Pushwoosh_DeviceApi_V2_FCMKey"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_FCMKey","title":"Pushwoosh_DeviceApi_V2_FCMKey","abstract":[],"type":"topic","url":"\/documentation\/pushwooshgrpc\/pushwoosh_deviceapi_v2_fcmkey","navigatorTitle":[{"kind":"identifier","text":"Pushwoosh_DeviceApi_V2_FCMKey"}]},"doc://com.pushwoosh.PushwooshGRPC/documentation/PushwooshGRPC":{"role":"collection","abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/pushwooshgrpc","title":"PushwooshGRPC","identifier":"doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC"},"doc://com.pushwoosh.PushwooshGRPC/documentation/PushwooshGRPC/Pushwoosh_DeviceApi_V2_UnregisterDeviceRequest":{"identifier":"doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_UnregisterDeviceRequest","abstract":[],"role":"symbol","kind":"symbol","title":"Pushwoosh_DeviceApi_V2_UnregisterDeviceRequest","navigatorTitle":[{"kind":"identifier","text":"Pushwoosh_DeviceApi_V2_UnregisterDeviceRequest"}],"type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Pushwoosh_DeviceApi_V2_UnregisterDeviceRequest","kind":"identifier"}],"url":"\/documentation\/pushwooshgrpc\/pushwoosh_deviceapi_v2_unregisterdevicerequest"},"doc://com.pushwoosh.PushwooshGRPC/documentation/PushwooshGRPC/Pushwoosh_DeviceApi_V2_CheckDeviceResponse":{"title":"Pushwoosh_DeviceApi_V2_CheckDeviceResponse","identifier":"doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_CheckDeviceResponse","abstract":[],"type":"topic","url":"\/documentation\/pushwooshgrpc\/pushwoosh_deviceapi_v2_checkdeviceresponse","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Pushwoosh_DeviceApi_V2_CheckDeviceResponse","kind":"identifier"}],"navigatorTitle":[{"text":"Pushwoosh_DeviceApi_V2_CheckDeviceResponse","kind":"identifier"}],"kind":"symbol"},"doc://com.pushwoosh.PushwooshGRPC/documentation/PushwooshGRPC/Pushwoosh_DeviceApi_V2_MessageDeliveryResponse":{"abstract":[],"role":"symbol","title":"Pushwoosh_DeviceApi_V2_MessageDeliveryResponse","navigatorTitle":[{"text":"Pushwoosh_DeviceApi_V2_MessageDeliveryResponse","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_MessageDeliveryResponse","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"Pushwoosh_DeviceApi_V2_MessageDeliveryResponse","kind":"identifier"}],"url":"\/documentation\/pushwooshgrpc\/pushwoosh_deviceapi_v2_messagedeliveryresponse"},"doc://com.pushwoosh.PushwooshGRPC/documentation/PushwooshGRPC/Pushwoosh_DeviceApi_V2_UnregisterDeviceResponse":{"kind":"symbol","title":"Pushwoosh_DeviceApi_V2_UnregisterDeviceResponse","url":"\/documentation\/pushwooshgrpc\/pushwoosh_deviceapi_v2_unregisterdeviceresponse","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Pushwoosh_DeviceApi_V2_UnregisterDeviceResponse"}],"navigatorTitle":[{"text":"Pushwoosh_DeviceApi_V2_UnregisterDeviceResponse","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_UnregisterDeviceResponse","type":"topic"},"doc://com.pushwoosh.PushwooshGRPC/documentation/PushwooshGRPC/Pushwoosh_DeviceApi_V2_RichMediaActionResponse":{"navigatorTitle":[{"kind":"identifier","text":"Pushwoosh_DeviceApi_V2_RichMediaActionResponse"}],"url":"\/documentation\/pushwooshgrpc\/pushwoosh_deviceapi_v2_richmediaactionresponse","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Pushwoosh_DeviceApi_V2_RichMediaActionResponse"}],"role":"symbol","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_RichMediaActionResponse","title":"Pushwoosh_DeviceApi_V2_RichMediaActionResponse"},"doc://com.pushwoosh.PushwooshGRPC/documentation/PushwooshGRPC/Pushwoosh_DeviceApi_V2_SetActivityTokenResponse":{"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"Pushwoosh_DeviceApi_V2_SetActivityTokenResponse","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_SetActivityTokenResponse","abstract":[],"url":"\/documentation\/pushwooshgrpc\/pushwoosh_deviceapi_v2_setactivitytokenresponse","type":"topic","title":"Pushwoosh_DeviceApi_V2_SetActivityTokenResponse","navigatorTitle":[{"text":"Pushwoosh_DeviceApi_V2_SetActivityTokenResponse","kind":"identifier"}]},"doc://com.pushwoosh.PushwooshGRPC/documentation/PushwooshGRPC/Pushwoosh_DeviceApi_V2_ApplicationOpenResponse":{"role":"symbol","abstract":[],"identifier":"doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_ApplicationOpenResponse","type":"topic","title":"Pushwoosh_DeviceApi_V2_ApplicationOpenResponse","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Pushwoosh_DeviceApi_V2_ApplicationOpenResponse"}],"url":"\/documentation\/pushwooshgrpc\/pushwoosh_deviceapi_v2_applicationopenresponse","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Pushwoosh_DeviceApi_V2_ApplicationOpenResponse","kind":"identifier"}]},"doc://com.pushwoosh.PushwooshGRPC/documentation/PushwooshGRPC/Pushwoosh_DeviceApi_V2_StringList":{"title":"Pushwoosh_DeviceApi_V2_StringList","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Pushwoosh_DeviceApi_V2_StringList","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"Pushwoosh_DeviceApi_V2_StringList","kind":"identifier"}],"type":"topic","url":"\/documentation\/pushwooshgrpc\/pushwoosh_deviceapi_v2_stringlist","abstract":[],"identifier":"doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_StringList"},"doc://com.pushwoosh.PushwooshGRPC/documentation/PushwooshGRPC/Pushwoosh_DeviceApi_V2_DeleteUserResponse":{"title":"Pushwoosh_DeviceApi_V2_DeleteUserResponse","abstract":[],"identifier":"doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_DeleteUserResponse","type":"topic","url":"\/documentation\/pushwooshgrpc\/pushwoosh_deviceapi_v2_deleteuserresponse","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Pushwoosh_DeviceApi_V2_DeleteUserResponse"}],"navigatorTitle":[{"kind":"identifier","text":"Pushwoosh_DeviceApi_V2_DeleteUserResponse"}],"kind":"symbol"},"doc://com.pushwoosh.PushwooshGRPC/documentation/PushwooshGRPC/Pushwoosh_DeviceApi_V2_User":{"url":"\/documentation\/pushwooshgrpc\/pushwoosh_deviceapi_v2_user","role":"symbol","title":"Pushwoosh_DeviceApi_V2_User","navigatorTitle":[{"text":"Pushwoosh_DeviceApi_V2_User","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_User","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"Pushwoosh_DeviceApi_V2_User","kind":"identifier"}],"abstract":[]},"doc://com.pushwoosh.PushwooshGRPC/documentation/PushwooshGRPC/Pushwoosh_DeviceApi_V2_LoadDevicesResponse":{"url":"\/documentation\/pushwooshgrpc\/pushwoosh_deviceapi_v2_loaddevicesresponse","kind":"symbol","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Pushwoosh_DeviceApi_V2_LoadDevicesResponse"}],"navigatorTitle":[{"kind":"identifier","text":"Pushwoosh_DeviceApi_V2_LoadDevicesResponse"}],"title":"Pushwoosh_DeviceApi_V2_LoadDevicesResponse","identifier":"doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_LoadDevicesResponse","type":"topic"},"doc://com.pushwoosh.PushwooshGRPC/documentation/PushwooshGRPC/Pushwoosh_PostEventApi_ShowInappMessageRequest":{"url":"\/documentation\/pushwooshgrpc\/pushwoosh_posteventapi_showinappmessagerequest","identifier":"doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_PostEventApi_ShowInappMessageRequest","type":"topic","kind":"symbol","abstract":[],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Pushwoosh_PostEventApi_ShowInappMessageRequest"}],"navigatorTitle":[{"text":"Pushwoosh_PostEventApi_ShowInappMessageRequest","kind":"identifier"}],"role":"symbol","title":"Pushwoosh_PostEventApi_ShowInappMessageRequest"},"doc://com.pushwoosh.PushwooshGRPC/documentation/PushwooshGRPC/Pushwoosh_DeviceApi_V2_SetAttributesRequest":{"navigatorTitle":[{"kind":"identifier","text":"Pushwoosh_DeviceApi_V2_SetAttributesRequest"}],"kind":"symbol","url":"\/documentation\/pushwooshgrpc\/pushwoosh_deviceapi_v2_setattributesrequest","role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_SetAttributesRequest","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"Pushwoosh_DeviceApi_V2_SetAttributesRequest","kind":"identifier"}],"abstract":[],"title":"Pushwoosh_DeviceApi_V2_SetAttributesRequest","type":"topic"},"doc://com.pushwoosh.PushwooshGRPC/documentation/PushwooshGRPC/Pushwoosh_DeviceApi_V2_GetInAppsResponse":{"type":"topic","url":"\/documentation\/pushwooshgrpc\/pushwoosh_deviceapi_v2_getinappsresponse","abstract":[],"title":"Pushwoosh_DeviceApi_V2_GetInAppsResponse","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Pushwoosh_DeviceApi_V2_GetInAppsResponse"}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"Pushwoosh_DeviceApi_V2_GetInAppsResponse","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_GetInAppsResponse"},"doc://com.pushwoosh.PushwooshGRPC/documentation/PushwooshGRPC/PushwooshGRPCVersionNumber":{"role":"symbol","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/PushwooshGRPCVersionNumber","abstract":[{"type":"text","text":"Project version number for PushwooshGRPC."}],"kind":"symbol","url":"\/documentation\/pushwooshgrpc\/pushwooshgrpcversionnumber","title":"PushwooshGRPCVersionNumber","fragments":[{"text":"PushwooshGRPCVersionNumber","kind":"identifier"}]},"doc://com.pushwoosh.PushwooshGRPC/documentation/PushwooshGRPC/Pushwoosh_DeviceApi_V2_MultiRegisterDeviceResponse":{"abstract":[],"url":"\/documentation\/pushwooshgrpc\/pushwoosh_deviceapi_v2_multiregisterdeviceresponse","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Pushwoosh_DeviceApi_V2_MultiRegisterDeviceResponse"}],"navigatorTitle":[{"text":"Pushwoosh_DeviceApi_V2_MultiRegisterDeviceResponse","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_MultiRegisterDeviceResponse","kind":"symbol","title":"Pushwoosh_DeviceApi_V2_MultiRegisterDeviceResponse"},"doc://com.pushwoosh.PushwooshGRPC/documentation/PushwooshGRPC/Pushwoosh_DeviceApi_V2_Tag":{"kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Pushwoosh_DeviceApi_V2_Tag"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_Tag","title":"Pushwoosh_DeviceApi_V2_Tag","abstract":[],"type":"topic","url":"\/documentation\/pushwooshgrpc\/pushwoosh_deviceapi_v2_tag","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Pushwoosh_DeviceApi_V2_Tag"}]},"doc://com.pushwoosh.PushwooshGRPC/documentation/PushwooshGRPC/Pushwoosh_DeviceApi_V2_EmailLinkClickResponse":{"kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Pushwoosh_DeviceApi_V2_EmailLinkClickResponse"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_EmailLinkClickResponse","title":"Pushwoosh_DeviceApi_V2_EmailLinkClickResponse","abstract":[],"type":"topic","url":"\/documentation\/pushwooshgrpc\/pushwoosh_deviceapi_v2_emaillinkclickresponse","role":"symbol","navigatorTitle":[{"text":"Pushwoosh_DeviceApi_V2_EmailLinkClickResponse","kind":"identifier"}]},"doc://com.pushwoosh.PushwooshGRPC/documentation/PushwooshGRPC/Pushwoosh_DeviceApi_V2_SetAttributesResponse":{"url":"\/documentation\/pushwooshgrpc\/pushwoosh_deviceapi_v2_setattributesresponse","role":"symbol","kind":"symbol","abstract":[],"title":"Pushwoosh_DeviceApi_V2_SetAttributesResponse","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_SetAttributesResponse","navigatorTitle":[{"kind":"identifier","text":"Pushwoosh_DeviceApi_V2_SetAttributesResponse"}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"Pushwoosh_DeviceApi_V2_SetAttributesResponse","kind":"identifier"}]},"doc://com.pushwoosh.PushwooshGRPC/documentation/PushwooshGRPC/Pushwoosh_DeviceApi_V2_SetTagsResponse":{"kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Pushwoosh_DeviceApi_V2_SetTagsResponse"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_SetTagsResponse","title":"Pushwoosh_DeviceApi_V2_SetTagsResponse","abstract":[],"url":"\/documentation\/pushwooshgrpc\/pushwoosh_deviceapi_v2_settagsresponse","type":"topic","role":"symbol","navigatorTitle":[{"text":"Pushwoosh_DeviceApi_V2_SetTagsResponse","kind":"identifier"}]},"doc://com.pushwoosh.PushwooshGRPC/documentation/PushwooshGRPC/PushwooshGRPCVersionString":{"url":"\/documentation\/pushwooshgrpc\/pushwooshgrpcversionstring","role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/PushwooshGRPCVersionString","type":"topic","abstract":[{"text":"Project version string for PushwooshGRPC.","type":"text"}],"title":"PushwooshGRPCVersionString","fragments":[{"text":"PushwooshGRPCVersionString","kind":"identifier"}],"kind":"symbol"},"doc://com.pushwoosh.PushwooshGRPC/documentation/PushwooshGRPC/Pushwoosh_DeviceApi_V2_RegisterDeviceRequest":{"identifier":"doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_RegisterDeviceRequest","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Pushwoosh_DeviceApi_V2_RegisterDeviceRequest"}],"title":"Pushwoosh_DeviceApi_V2_RegisterDeviceRequest","kind":"symbol","type":"topic","url":"\/documentation\/pushwooshgrpc\/pushwoosh_deviceapi_v2_registerdevicerequest","navigatorTitle":[{"kind":"identifier","text":"Pushwoosh_DeviceApi_V2_RegisterDeviceRequest"}]},"doc://com.pushwoosh.PushwooshGRPC/documentation/PushwooshGRPC/Pushwoosh_DeviceApi_V2_GetInAppsRequest":{"url":"\/documentation\/pushwooshgrpc\/pushwoosh_deviceapi_v2_getinappsrequest","identifier":"doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_GetInAppsRequest","type":"topic","abstract":[],"kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Pushwoosh_DeviceApi_V2_GetInAppsRequest"}],"navigatorTitle":[{"text":"Pushwoosh_DeviceApi_V2_GetInAppsRequest","kind":"identifier"}],"role":"symbol","title":"Pushwoosh_DeviceApi_V2_GetInAppsRequest"},"doc://com.pushwoosh.PushwooshGRPC/documentation/PushwooshGRPC/Pushwoosh_DeviceApi_V2_CheckDeviceRequest":{"type":"topic","abstract":[],"navigatorTitle":[{"text":"Pushwoosh_DeviceApi_V2_CheckDeviceRequest","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_CheckDeviceRequest","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"Pushwoosh_DeviceApi_V2_CheckDeviceRequest","kind":"identifier"}],"kind":"symbol","title":"Pushwoosh_DeviceApi_V2_CheckDeviceRequest","url":"\/documentation\/pushwooshgrpc\/pushwoosh_deviceapi_v2_checkdevicerequest","role":"symbol"},"doc://com.pushwoosh.PushwooshGRPC/documentation/PushwooshGRPC/Pushwoosh_DeviceApi_V2_DeleteDeviceResponse":{"url":"\/documentation\/pushwooshgrpc\/pushwoosh_deviceapi_v2_deletedeviceresponse","identifier":"doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_DeleteDeviceResponse","type":"topic","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Pushwoosh_DeviceApi_V2_DeleteDeviceResponse"}],"navigatorTitle":[{"text":"Pushwoosh_DeviceApi_V2_DeleteDeviceResponse","kind":"identifier"}],"role":"symbol","title":"Pushwoosh_DeviceApi_V2_DeleteDeviceResponse"},"doc://com.pushwoosh.PushwooshGRPC/documentation/PushwooshGRPC/Pushwoosh_DeviceApi_V2_GetUnregisteredDevicesResponse":{"kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Pushwoosh_DeviceApi_V2_GetUnregisteredDevicesResponse"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_GetUnregisteredDevicesResponse","title":"Pushwoosh_DeviceApi_V2_GetUnregisteredDevicesResponse","url":"\/documentation\/pushwooshgrpc\/pushwoosh_deviceapi_v2_getunregistereddevicesresponse","type":"topic","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Pushwoosh_DeviceApi_V2_GetUnregisteredDevicesResponse"}]},"doc://com.pushwoosh.PushwooshGRPC/documentation/PushwooshGRPC/Pushwoosh_DeviceApi_V2_SetActivityPushToStartTokenRequest":{"role":"symbol","abstract":[],"identifier":"doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_SetActivityPushToStartTokenRequest","type":"topic","title":"Pushwoosh_DeviceApi_V2_SetActivityPushToStartTokenRequest","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Pushwoosh_DeviceApi_V2_SetActivityPushToStartTokenRequest"}],"url":"\/documentation\/pushwooshgrpc\/pushwoosh_deviceapi_v2_setactivitypushtostarttokenrequest","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"Pushwoosh_DeviceApi_V2_SetActivityPushToStartTokenRequest","kind":"identifier"}]},"doc://com.pushwoosh.PushwooshGRPC/documentation/PushwooshGRPC/Pushwoosh_PostEventApi_PostEventRequest":{"abstract":[],"role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_PostEventApi_PostEventRequest","type":"topic","url":"\/documentation\/pushwooshgrpc\/pushwoosh_posteventapi_posteventrequest","navigatorTitle":[{"kind":"identifier","text":"Pushwoosh_PostEventApi_PostEventRequest"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"Pushwoosh_PostEventApi_PostEventRequest","kind":"identifier"}],"title":"Pushwoosh_PostEventApi_PostEventRequest","kind":"symbol"},"doc://com.pushwoosh.PushwooshGRPC/documentation/PushwooshGRPC/Pushwoosh_DeviceApi_V2_SetActivityTokenRequest":{"identifier":"doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_SetActivityTokenRequest","url":"\/documentation\/pushwooshgrpc\/pushwoosh_deviceapi_v2_setactivitytokenrequest","abstract":[],"role":"symbol","title":"Pushwoosh_DeviceApi_V2_SetActivityTokenRequest","kind":"symbol","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Pushwoosh_DeviceApi_V2_SetActivityTokenRequest","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Pushwoosh_DeviceApi_V2_SetActivityTokenRequest"}]},"doc://com.pushwoosh.PushwooshGRPC/documentation/PushwooshGRPC/Pushwoosh_DeviceApi_V2_GetTagsResponse":{"kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Pushwoosh_DeviceApi_V2_GetTagsResponse"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_GetTagsResponse","title":"Pushwoosh_DeviceApi_V2_GetTagsResponse","abstract":[],"type":"topic","url":"\/documentation\/pushwooshgrpc\/pushwoosh_deviceapi_v2_gettagsresponse","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Pushwoosh_DeviceApi_V2_GetTagsResponse"}]},"doc://com.pushwoosh.PushwooshGRPC/documentation/PushwooshGRPC/Pushwoosh_DeviceApi_V2_ApplicationOpenRequest":{"navigatorTitle":[{"kind":"identifier","text":"Pushwoosh_DeviceApi_V2_ApplicationOpenRequest"}],"url":"\/documentation\/pushwooshgrpc\/pushwoosh_deviceapi_v2_applicationopenrequest","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Pushwoosh_DeviceApi_V2_ApplicationOpenRequest","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_ApplicationOpenRequest","title":"Pushwoosh_DeviceApi_V2_ApplicationOpenRequest"},"doc://com.pushwoosh.PushwooshGRPC/documentation/PushwooshGRPC/Pushwoosh_DeviceApi_V2_PushStatRequest":{"navigatorTitle":[{"kind":"identifier","text":"Pushwoosh_DeviceApi_V2_PushStatRequest"}],"kind":"symbol","url":"\/documentation\/pushwooshgrpc\/pushwoosh_deviceapi_v2_pushstatrequest","role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_PushStatRequest","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Pushwoosh_DeviceApi_V2_PushStatRequest"}],"abstract":[],"title":"Pushwoosh_DeviceApi_V2_PushStatRequest","type":"topic"},"doc://com.pushwoosh.PushwooshGRPC/documentation/PushwooshGRPC/Pushwoosh_DeviceApi_V2_LoadDevicesRequest":{"abstract":[],"identifier":"doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_LoadDevicesRequest","type":"topic","navigatorTitle":[{"text":"Pushwoosh_DeviceApi_V2_LoadDevicesRequest","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Pushwoosh_DeviceApi_V2_LoadDevicesRequest"}],"title":"Pushwoosh_DeviceApi_V2_LoadDevicesRequest","url":"\/documentation\/pushwooshgrpc\/pushwoosh_deviceapi_v2_loaddevicesrequest","kind":"symbol","role":"symbol"},"doc://com.pushwoosh.PushwooshGRPC/documentation/PushwooshGRPC/Pushwoosh_DeviceApi_V2_RegisterDeviceResponse":{"url":"\/documentation\/pushwooshgrpc\/pushwoosh_deviceapi_v2_registerdeviceresponse","abstract":[],"role":"symbol","kind":"symbol","title":"Pushwoosh_DeviceApi_V2_RegisterDeviceResponse","navigatorTitle":[{"kind":"identifier","text":"Pushwoosh_DeviceApi_V2_RegisterDeviceResponse"}],"type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"Pushwoosh_DeviceApi_V2_RegisterDeviceResponse","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_RegisterDeviceResponse"},"doc://com.pushwoosh.PushwooshGRPC/documentation/PushwooshGRPC/Pushwoosh_DeviceApi_V2_Device":{"identifier":"doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/Pushwoosh_DeviceApi_V2_Device","title":"Pushwoosh_DeviceApi_V2_Device","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"Pushwoosh_DeviceApi_V2_Device","kind":"identifier"}],"url":"\/documentation\/pushwooshgrpc\/pushwoosh_deviceapi_v2_device","navigatorTitle":[{"kind":"identifier","text":"Pushwoosh_DeviceApi_V2_Device"}],"abstract":[],"type":"topic","kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/PushwooshGRPCImplementation"],"title":"Classes"},{"identifiers":["doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/PushwooshGRPCVersionNumber","doc:\/\/com.pushwoosh.PushwooshGRPC\/documentation\/PushwooshGRPC\/PushwooshGRPCVersionString"],"title":"Variables"}]},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":"PushwooshGRPCImplementation","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshGRPC~1documentation~1PushwooshGRPC~1PushwooshGRPCImplementation\/title"},{"value":[{"text":"PushwooshGRPCImplementation","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshGRPC~1documentation~1PushwooshGRPC~1PushwooshGRPCImplementation\/fragments","op":"replace"}]}]}