{"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS"]]},"seeAlsoSections":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/GettingStarted","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/Examples"],"generated":true,"title":"Getting Started"}],"primaryContentSections":[{"kind":"content","content":[{"text":"Overview","type":"heading","anchor":"Overview","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Pushwoosh tvOS Rich Media supports HTML content in Unlayer format. The parser recognizes special id attributes and inline styles to create native tvOS interface elements with automatic focus navigation support."}]},{"text":"Basic Structure","type":"heading","anchor":"Basic-Structure","level":2},{"inlineContent":[{"text":"Every Rich Media HTML must have this basic structure:","type":"text"}],"type":"paragraph"},{"type":"codeListing","syntax":"html","code":["<div id=\"u_body\" style=\"background-color: #1a1a2e; border-radius: 30px;\">","  <div id=\"u_column_1\">","    <!-- Your content here -->","  <\/div>","<\/div>"]},{"anchor":"Supported-Styles-for-ubody","type":"heading","level":3,"text":"Supported Styles for u_body"},{"rows":[[[{"type":"paragraph","inlineContent":[{"type":"text","text":"Style"}]}],[{"inlineContent":[{"type":"text","text":"Description"}],"type":"paragraph"}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"Example"}]}]],[[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"background-color"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"Background color"}]}],[{"inlineContent":[{"code":"#1a1a2e","type":"codeVoice"},{"type":"text","text":", "},{"code":"rgb(26, 26, 46)","type":"codeVoice"},{"type":"text","text":", "},{"code":"rgba(26, 26, 46, 0.9)","type":"codeVoice"}],"type":"paragraph"}]],[[{"inlineContent":[{"type":"codeVoice","code":"border-radius"}],"type":"paragraph"}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"Corner radius"}]}],[{"inlineContent":[{"type":"codeVoice","code":"30px"}],"type":"paragraph"}]],[[{"inlineContent":[{"type":"codeVoice","code":"background-image"}],"type":"paragraph"}],[{"type":"paragraph","inlineContent":[{"text":"Background image","type":"text"}]}],[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"url('https:\/\/example.com\/bg.jpg')"}]}]]],"type":"table","header":"row"},{"level":2,"type":"heading","text":"Content Types","anchor":"Content-Types"},{"anchor":"Images","type":"heading","text":"Images","level":3},{"inlineContent":[{"type":"text","text":"Display images using "},{"type":"codeVoice","code":"u_content_image_*"},{"type":"text","text":" id:"}],"type":"paragraph"},{"code":["<div id=\"u_content_image_1\">","  <img src=\"https:\/\/example.com\/image.jpg\" \/>","<\/div>"],"syntax":"html","type":"codeListing"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Or use background-image:"}]},{"syntax":"html","type":"codeListing","code":["<div id=\"u_content_image_1\" style=\"background-image: url('https:\/\/example.com\/image.jpg');\">","<\/div>"]},{"level":3,"anchor":"Headings","text":"Headings","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"Create headings with ","type":"text"},{"code":"u_content_heading_*","type":"codeVoice"},{"type":"text","text":" id:"}]},{"code":["<div id=\"u_content_heading_1\" style=\"font-size: 32px; color: #ffffff; text-align: center;\">","  <h1>Your Heading<\/h1>","<\/div>"],"syntax":"html","type":"codeListing"},{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Supported styles:"}]}]},{"items":[{"content":[{"inlineContent":[{"type":"codeVoice","code":"font-size"},{"text":" - Font size in pixels (automatically increased by 20% for tvOS)","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"color"},{"text":" - Text color (hex, rgb, rgba)","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"codeVoice","code":"text-align"},{"text":" - Alignment (","type":"text"},{"code":"left","type":"codeVoice"},{"type":"text","text":", "},{"type":"codeVoice","code":"center"},{"type":"text","text":", "},{"type":"codeVoice","code":"right"},{"type":"text","text":", "},{"code":"justify","type":"codeVoice"},{"type":"text","text":")"}],"type":"paragraph"}]}],"type":"unorderedList"},{"type":"heading","text":"Text","level":3,"anchor":"Text"},{"inlineContent":[{"text":"Display text content with ","type":"text"},{"type":"codeVoice","code":"u_content_text_*"},{"type":"text","text":" id:"}],"type":"paragraph"},{"type":"codeListing","syntax":"html","code":["<div id=\"u_content_text_1\" style=\"font-size: 18px; color: #cccccc; text-align: left;\">","  <p>Your text here<\/p>","<\/div>"]},{"type":"paragraph","inlineContent":[{"text":"Supports the same styles as headings.","type":"text"}]},{"text":"Buttons","type":"heading","level":3,"anchor":"Buttons"},{"type":"paragraph","inlineContent":[{"text":"Buttons use ","type":"text"},{"code":"u_content_button_*","type":"codeVoice"},{"text":" id and support various actions:","type":"text"}]},{"text":"Track Event Button","level":4,"anchor":"Track-Event-Button","type":"heading"},{"code":["<div id=\"u_content_button_1\">","  <a href=\"#\"","     data-event=\"button_clicked\"","     data-attributes='{\"source\": \"rich_media\", \"action\": \"subscribe\"}'","     style=\"background-color: #4a5ff7; color: #ffffff; border-radius: 12px;\">","    Subscribe","  <\/a>","<\/div>"],"type":"codeListing","syntax":"html"},{"anchor":"Close-Button","type":"heading","level":4,"text":"Close Button"},{"syntax":"html","type":"codeListing","code":["<div id=\"u_content_button_2\">","  <a href=\"closeInApp\" style=\"background-color: transparent; color: #ffffff; border-bottom-color: #ffffff;\">","    Close","  <\/a>","<\/div>"]},{"anchor":"Open-Settings-Button","text":"Open Settings Button","type":"heading","level":4},{"type":"codeListing","syntax":"html","code":["<div id=\"u_content_button_3\">","  <a href=\"openAppSettings\" style=\"background-color: #4a5ff7; color: #ffffff;\">","    Open Settings","  <\/a>","<\/div>"]},{"text":"Send Tags Button","anchor":"Send-Tags-Button","type":"heading","level":4},{"type":"codeListing","syntax":"html","code":["<div id=\"u_content_button_4\">","  <a href=\"sendTags\"","     data-tags='{\"subscribed\": true, \"source\": \"tv_promo\"}'","     style=\"background-color: #4a5ff7; color: #ffffff;\">","    Save","  <\/a>","<\/div>"]},{"text":"Get Tags Button","type":"heading","level":4,"anchor":"Get-Tags-Button"},{"code":["<div id=\"u_content_button_5\">","  <a href=\"getTags\" style=\"background-color: #4a5ff7; color: #ffffff;\">","    Get Tags","  <\/a>","<\/div>"],"syntax":"html","type":"codeListing"},{"anchor":"Button-Styles","level":4,"type":"heading","text":"Button Styles"},{"type":"table","header":"row","rows":[[[{"type":"paragraph","inlineContent":[{"text":"Style","type":"text"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"Description"}]}]],[[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"background-color"}]}],[{"inlineContent":[{"text":"Background color (use ","type":"text"},{"type":"codeVoice","code":"transparent"},{"type":"text","text":" for transparent button)"}],"type":"paragraph"}]],[[{"inlineContent":[{"code":"color","type":"codeVoice"}],"type":"paragraph"}],[{"inlineContent":[{"type":"text","text":"Text color"}],"type":"paragraph"}]],[[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"border-bottom-color"},{"type":"text","text":" or "},{"code":"border-color","type":"codeVoice"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"Border color"}]}]],[[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"border-radius"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"Corner radius (applied to button, not container)"}]}]]]},{"anchor":"Text-Fields","text":"Text Fields","type":"heading","level":3},{"type":"paragraph","inlineContent":[{"type":"text","text":"Create input fields with "},{"code":"u_content_textfield_*","type":"codeVoice"},{"type":"text","text":" id:"}]},{"code":["<div id=\"u_content_textfield_1\">","  <input type=\"text\"","         placeholder=\"Enter email\"","         data-field-name=\"email\"","         style=\"font-size: 18px; color: #ffffff; background-color: rgba(255,255,255,0.1); border-color: #4a5ff7; text-align: left;\" \/>","<\/div>"],"type":"codeListing","syntax":"html"},{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"text":"Required attributes:","type":"text"}]}]},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"code":"data-field-name","type":"codeVoice"},{"text":" - Field name used to retrieve value","type":"text"}]}]}],"type":"unorderedList"},{"inlineContent":[{"type":"strong","inlineContent":[{"text":"Supported styles:","type":"text"}]}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"code":"font-size","type":"codeVoice"},{"text":" - Font size","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"code":"color","type":"codeVoice"},{"text":" - Text color","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"code":"background-color","type":"codeVoice"},{"type":"text","text":" - Background color"}]}]},{"content":[{"inlineContent":[{"type":"codeVoice","code":"border-color"},{"type":"text","text":" - Border color"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"codeVoice","code":"text-align"},{"text":" - Text alignment","type":"text"}],"type":"paragraph"}]}]},{"text":"Layout Options","level":2,"type":"heading","anchor":"Layout-Options"},{"level":3,"type":"heading","anchor":"Horizontal-Layout-Two-Columns","text":"Horizontal Layout (Two Columns)"},{"type":"paragraph","inlineContent":[{"text":"Create a horizontal layout using ","type":"text"},{"code":"flex-direction: row","type":"codeVoice"},{"type":"text","text":" in "},{"type":"codeVoice","code":"u_column_1"},{"type":"text","text":":"}]},{"syntax":"html","code":["<div id=\"u_body\" style=\"background-color: #1a1a2e; border-radius: 30px;\">","  <div id=\"u_column_1\" style=\"display: flex; flex-direction: row;\">","","    <!-- Left column -->","    <div>","      <div id=\"u_content_heading_1\" style=\"font-size: 32px; color: #ffffff;\">","        <h1>Heading<\/h1>","      <\/div>","      <div id=\"u_content_text_1\" style=\"font-size: 18px; color: #cccccc;\">","        <p>Description<\/p>","      <\/div>","      <div id=\"u_content_button_1\">","        <a href=\"#\" data-event=\"action\" style=\"background-color: #4a5ff7; color: #ffffff;\">","          Button","        <\/a>","      <\/div>","    <\/div>","","    <!-- Right column -->","    <div>","      <div id=\"u_content_image_1\">","        <img src=\"https:\/\/example.com\/image.jpg\" \/>","      <\/div>","    <\/div>","","  <\/div>","<\/div>"],"type":"codeListing"},{"text":"Vertical Layout (Default)","type":"heading","anchor":"Vertical-Layout-Default","level":3},{"inlineContent":[{"text":"By default, content flows vertically. No special configuration needed.","type":"text"}],"type":"paragraph"},{"anchor":"Color-Formats","level":2,"type":"heading","text":"Color Formats"},{"inlineContent":[{"type":"text","text":"All color formats are supported:"}],"type":"paragraph"},{"header":"row","type":"table","rows":[[[{"type":"paragraph","inlineContent":[{"text":"Format","type":"text"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"Example"}]}]],[[{"inlineContent":[{"type":"text","text":"Hex"}],"type":"paragraph"}],[{"inlineContent":[{"type":"codeVoice","code":"#ff0000"},{"text":", ","type":"text"},{"type":"codeVoice","code":"#f00"}],"type":"paragraph"}]],[[{"inlineContent":[{"type":"text","text":"RGB"}],"type":"paragraph"}],[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"rgb(255, 0, 0)"}]}]],[[{"type":"paragraph","inlineContent":[{"type":"text","text":"RGBA"}]}],[{"inlineContent":[{"code":"rgba(255, 0, 0, 0.5)","type":"codeVoice"}],"type":"paragraph"}]]]},{"anchor":"Important-Requirements","text":"Important Requirements","level":2,"type":"heading"},{"type":"heading","anchor":"Element-IDs","text":"Element IDs","level":3},{"inlineContent":[{"text":"All content elements ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"must"}]},{"type":"text","text":" have id in the format "},{"code":"u_content_[type]_[number]","type":"codeVoice"},{"text":":","type":"text"}],"type":"paragraph"},{"items":[{"content":[{"inlineContent":[{"type":"text","text":"Images: "},{"type":"codeVoice","code":"u_content_image_1"},{"type":"text","text":", "},{"code":"u_content_image_2","type":"codeVoice"},{"text":", …","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Headings: "},{"type":"codeVoice","code":"u_content_heading_1"},{"text":", ","type":"text"},{"type":"codeVoice","code":"u_content_heading_2"},{"text":", …","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Text: ","type":"text"},{"code":"u_content_text_1","type":"codeVoice"},{"text":", ","type":"text"},{"type":"codeVoice","code":"u_content_text_2"},{"text":", …","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Buttons: ","type":"text"},{"type":"codeVoice","code":"u_content_button_1"},{"text":", ","type":"text"},{"code":"u_content_button_2","type":"codeVoice"},{"type":"text","text":", …"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Text fields: "},{"type":"codeVoice","code":"u_content_textfield_1"},{"text":", ","type":"text"},{"type":"codeVoice","code":"u_content_textfield_2"},{"type":"text","text":", …"}]}]}],"type":"unorderedList"},{"content":[{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"text":"Important","type":"text"}]},{"type":"text","text":": Elements without proper id format will not be displayed."}]}],"type":"aside","name":"Note","style":"note"},{"level":3,"type":"heading","text":"Dividers","anchor":"Dividers"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Elements with "},{"type":"codeVoice","code":"u_content_divider_*"},{"type":"text","text":" id are ignored and not displayed."}]},{"type":"heading","text":"HTML Entities","anchor":"HTML-Entities","level":3},{"inlineContent":[{"text":"Supported HTML entities:","type":"text"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"&nbsp;"},{"type":"text","text":" - Non-breaking space"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"code":"&amp;","type":"codeVoice"},{"type":"text","text":" - Ampersand"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"&lt;"},{"text":" - Less than","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"code":"&gt;","type":"codeVoice"},{"type":"text","text":" - Greater than"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"code":"&quot;","type":"codeVoice"},{"type":"text","text":" - Quote"}]}]}]},{"anchor":"Font-Size-Adjustment","type":"heading","level":3,"text":"Font Size Adjustment"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Font sizes are automatically increased by 20% for better readability on Apple TV screens."}]},{"level":3,"type":"heading","anchor":"Focus-Navigation","text":"Focus Navigation"},{"inlineContent":[{"type":"text","text":"Buttons and text fields automatically become focusable for Apple TV remote navigation. Elements are navigated in the order they appear in the HTML."}],"type":"paragraph"},{"anchor":"Inline-Styles-Only","level":3,"type":"heading","text":"Inline Styles Only"},{"type":"paragraph","inlineContent":[{"text":"Use only inline styles in ","type":"text"},{"code":"style=\"\"","type":"codeVoice"},{"text":" attribute. External CSS files and ","type":"text"},{"type":"codeVoice","code":"<style>"},{"text":" tags are not supported.","type":"text"}]},{"text":"Localization Support","type":"heading","anchor":"Localization-Support","level":3},{"inlineContent":[{"text":"Placeholders in format ","type":"text"},{"type":"codeVoice","code":"{{key|text|default value}}"},{"text":" are supported for localized content.","type":"text"}],"type":"paragraph"},{"level":2,"text":"Complete Example","type":"heading","anchor":"Complete-Example"},{"code":["<div id=\"u_body\" style=\"background-color: linear-gradient(135deg, #667eea 0%, #764ba2 100%); border-radius: 30px; padding: 40px;\">","  <div id=\"u_column_1\" style=\"display: flex; flex-direction: row;\">","","    <!-- Content column -->","    <div style=\"flex: 1;\">","      <div id=\"u_content_heading_1\" style=\"font-size: 48px; color: #ffffff; text-align: left;\">","        <h1>Exclusive Offer<\/h1>","      <\/div>","","      <div id=\"u_content_text_1\" style=\"font-size: 24px; color: rgba(255,255,255,0.9); text-align: left;\">","        <p>Subscribe now and get 30 days free<\/p>","      <\/div>","","      <div id=\"u_content_textfield_1\">","        <input type=\"text\"","               placeholder=\"Enter your email\"","               data-field-name=\"email\"","               style=\"font-size: 18px; color: #ffffff; background-color: rgba(255,255,255,0.1); border-color: rgba(255,255,255,0.3);\" \/>","      <\/div>","","      <div id=\"u_content_button_1\">","        <a href=\"#\"","           data-event=\"subscription_started\"","           data-attributes='{\"source\": \"tv_promo\", \"plan\": \"premium\"}'","           style=\"background-color: #4a5ff7; color: #ffffff; border-radius: 12px;\">","          Start Free Trial","        <\/a>","      <\/div>","","      <div id=\"u_content_button_2\">","        <a href=\"closeInApp\" style=\"background-color: transparent; color: rgba(255,255,255,0.7); border-bottom-color: rgba(255,255,255,0.3);\">","          Later","        <\/a>","      <\/div>","    <\/div>","","    <!-- Image column -->","    <div style=\"flex: 1;\">","      <div id=\"u_content_image_1\">","        <img src=\"https:\/\/example.com\/tv-promo.jpg\" \/>","      <\/div>","    <\/div>","","  <\/div>","<\/div>"],"syntax":"html","type":"codeListing"},{"anchor":"Best-Practices","level":2,"text":"Best Practices","type":"heading"},{"items":[{"content":[{"inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Keep it simple"}]},{"type":"text","text":": Avoid complex nested structures"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"inlineContent":[{"type":"text","text":"Test focus order"}],"type":"strong"},{"text":": Verify navigation flow with Apple TV remote","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"inlineContent":[{"text":"Use semantic HTML","type":"text"}],"type":"strong"},{"type":"text","text":": Use proper heading tags ("},{"type":"codeVoice","code":"<h1>"},{"text":", ","type":"text"},{"type":"codeVoice","code":"<h2>"},{"type":"text","text":", etc.)"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"inlineContent":[{"type":"text","text":"Provide placeholders"}],"type":"strong"},{"text":": Always include placeholder text for input fields","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Clear call-to-action"}]},{"text":": Make buttons visually distinct with good contrast","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Adequate spacing"}]},{"type":"text","text":": Maintain 20-30px spacing between interactive elements"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Minimum sizes"}]},{"type":"text","text":": Buttons should be at least 250pt wide for easy selection"}]}]}],"type":"unorderedList"},{"text":"Troubleshooting","type":"heading","anchor":"Troubleshooting","level":2},{"level":3,"anchor":"Element-Not-Appearing","text":"Element Not Appearing","type":"heading"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Check that the element has proper "},{"type":"codeVoice","code":"u_content_*"},{"text":" id","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Verify inline styles are present"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"Ensure there are no syntax errors in style attribute","type":"text"}],"type":"paragraph"}]}],"type":"unorderedList"},{"text":"Button Not Working","anchor":"Button-Not-Working","type":"heading","level":3},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"text":"Verify ","type":"text"},{"code":"href","type":"codeVoice"},{"text":" attribute has correct action (","type":"text"},{"code":"closeInApp","type":"codeVoice"},{"type":"text","text":", "},{"type":"codeVoice","code":"sendTags"},{"text":", ","type":"text"},{"type":"codeVoice","code":"getTags"},{"text":", ","type":"text"},{"type":"codeVoice","code":"openAppSettings"},{"type":"text","text":")"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"Check ","type":"text"},{"type":"codeVoice","code":"data-event"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"data-attributes"},{"text":" JSON format","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Ensure button is inside "},{"code":"u_content_button_*","type":"codeVoice"},{"text":" div","type":"text"}]}]}]},{"level":3,"text":"Focus Navigation Issues","anchor":"Focus-Navigation-Issues","type":"heading"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Verify buttons and inputs are in logical order in HTML","type":"text"}]}]},{"content":[{"inlineContent":[{"text":"Check that focusable elements have sufficient size","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Test on physical Apple TV device","type":"text"}]}]}]},{"type":"heading","anchor":"Next-Steps","level":2,"text":"Next Steps"},{"items":[{"content":[{"inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/GettingStarted"},{"text":" - Integration guide","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/Examples","isActive":true,"type":"reference"},{"type":"text","text":" - Code examples"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PWTVOSRichMediaManager"},{"type":"text","text":" - Rich Media manager reference"}]}]}],"type":"unorderedList"}]}],"kind":"article","schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"role":"article","modules":[{"name":"PushwooshTVOS"}],"roleHeading":"Article","title":"HTML Guide for tvOS Rich Media"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/HTMLGuide"},"abstract":[{"type":"text","text":"Create Rich Media content using Unlayer HTML format for tvOS."}],"variants":[{"paths":["\/documentation\/pushwooshtvos\/htmlguide"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshtvos\/htmlguide"]}],"sections":[],"references":{"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS":{"type":"topic","role":"collection","title":"PushwooshTVOS","identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS","abstract":[{"text":"Push notifications and Rich Media for tvOS apps.","type":"text"}],"kind":"symbol","url":"\/documentation\/pushwooshtvos"},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PWTVOSRichMediaManager":{"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PWTVOSRichMediaManager","abstract":[{"text":"Manager for displaying Rich Media content on tvOS.","type":"text"}],"url":"\/documentation\/pushwooshtvos\/pwtvosrichmediamanager","navigatorTitle":[{"text":"PWTVOSRichMediaManager","kind":"identifier"}],"title":"PWTVOSRichMediaManager","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PWTVOSRichMediaManager"}],"role":"symbol"},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/GettingStarted":{"role":"article","title":"Getting Started","type":"topic","abstract":[{"text":"Integrate Modal Rich Media for your tvOS app.","type":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/GettingStarted","kind":"article","url":"\/documentation\/pushwooshtvos\/gettingstarted"},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/Examples":{"url":"\/documentation\/pushwooshtvos\/examples","abstract":[{"text":"Code samples demonstrating common tvOS integration scenarios.","type":"text"}],"kind":"article","title":"Examples","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/Examples","role":"article"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":[{"generated":true,"identifiers":["doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/GettingStarted","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/Examples"],"title":"Getting Started"}],"op":"replace","path":"\/seeAlsoSections"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PWTVOSRichMediaManager\/title","value":"PWTVOSRichMediaManager"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PWTVOSRichMediaManager\/fragments","value":[{"text":"PWTVOSRichMediaManager","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}