{"topicSections":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/setAppCode(_:)","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/registerForTvPushNotifications()","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/registerForPushNotifications(withToken:completion:)"],"title":"Configuration"},{"title":"Push Handling","identifiers":["doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/handleTvPushToken(_:)","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/handleTvPushRegistrationFailure(_:)","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/handleTvPushReceived(userInfo:completionHandler:)","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/handleTVOSPush(userInfo:)"]},{"identifiers":["doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/richMediaManager","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/configureRichMediaWith(position:presentAnimation:dismissAnimation:)","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/configureCloseButton(_:)","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/setRichMediaGetTagsHandler(_:)"],"title":"Rich Media"},{"identifiers":["doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/unregisterForPushNotifications(completion:)"],"title":"Instance Methods"},{"title":"Type Properties","identifiers":["doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/shared"]},{"identifiers":["doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/tvos()"],"title":"Type Methods"}],"kind":"symbol","metadata":{"modules":[{"name":"PushwooshTVOS"}],"roleHeading":"Class","title":"PushwooshTVOSImplementation","navigatorTitle":[{"kind":"identifier","text":"PushwooshTVOSImplementation"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PushwooshTVOSImplementation","kind":"identifier"}],"role":"symbol","platforms":[{"beta":false,"introducedAt":"11.0","name":"tvOS","deprecated":false,"unavailable":false}],"symbolKind":"class","externalID":"c:@M@PushwooshTVOS@objc(cs)PushwooshTVOSImplementation"},"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/pushwooshtvos\/pushwooshtvosimplementation"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pushwooshtvos\/pushwooshtvosimplementation"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["tvOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(PushwooshTVOSImplementation) ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PushwooshTVOSImplementation","kind":"identifier"}],"languages":["swift"]}]},{"content":[{"text":"Overview","level":2,"type":"heading","anchor":"overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This class provides the core functionality for integrating Pushwoosh push notifications"},{"text":" ","type":"text"},{"text":"and Rich Media content into tvOS applications. It handles device registration, push","type":"text"},{"text":" ","type":"text"},{"text":"notification processing, and Rich Media display with tvOS-specific optimizations.","type":"text"}]},{"text":"Usage","type":"heading","anchor":"Usage","level":2},{"inlineContent":[{"type":"text","text":"Initialize and configure during app launch:"}],"type":"paragraph"},{"type":"codeListing","syntax":"swift","code":["Pushwoosh.TVoS.setAppCode(\"YOUR-APP-CODE\")","Pushwoosh.TVoS.registerForTvPushNotifications()"]}],"kind":"content"}],"sections":[],"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS"]]},"abstract":[{"text":"Main implementation class for tvOS push notifications and Rich Media.","type":"text"}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.pushwoosh.PushwooshTVOS\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From"},{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/com.pushwoosh.PushwooshTVOS\/objc(pl)NSObject","doc:\/\/com.pushwoosh.PushwooshTVOS\/s7CVarArgP","doc:\/\/com.pushwoosh.PushwooshTVOS\/s28CustomDebugStringConvertibleP","doc:\/\/com.pushwoosh.PushwooshTVOS\/s23CustomStringConvertibleP","doc:\/\/com.pushwoosh.PushwooshTVOS\/SQ","doc:\/\/com.pushwoosh.PushwooshTVOS\/SH"],"kind":"relationships"}],"references":{"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PushwooshTVOSImplementation/setAppCode(_:)":{"role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/setAppCode(_:)","navigatorTitle":[{"text":"setAppCode:","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Sets the Pushwoosh application code for tvOS.","type":"text"}],"url":"\/documentation\/pushwooshtvos\/pushwooshtvosimplementation\/setappcode(_:)","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setAppCode","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}],"type":"topic","title":"setAppCode(_:)"},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PushwooshTVOSImplementation/handleTvPushRegistrationFailure(_:)":{"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"handleTvPushRegistrationFailure","kind":"identifier"},{"kind":"text","text":"("},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"handleTvPushRegistrationFailure:"}],"abstract":[{"text":"Handles push registration failure on tvOS.","type":"text"}],"title":"handleTvPushRegistrationFailure(_:)","url":"\/documentation\/pushwooshtvos\/pushwooshtvosimplementation\/handletvpushregistrationfailure(_:)","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/handleTvPushRegistrationFailure(_:)","role":"symbol"},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PushwooshTVOSImplementation/handleTvPushToken(_:)":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"handleTvPushToken","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"kind":"text","text":")"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"handleTvPushToken:"}],"abstract":[{"text":"Handles the device token received from tvOS push registration.","type":"text"}],"title":"handleTvPushToken(_:)","url":"\/documentation\/pushwooshtvos\/pushwooshtvosimplementation\/handletvpushtoken(_:)","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/handleTvPushToken(_:)","role":"symbol"},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PushwooshTVOSImplementation/shared":{"navigatorTitle":[{"kind":"identifier","text":"shared"}],"title":"shared","kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/pushwooshtvos\/pushwooshtvosimplementation\/shared","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"shared","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@PushwooshTVOS@objc(cs)PushwooshTVOSImplementation","text":"PushwooshTVOSImplementation"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/shared","abstract":[{"type":"text","text":"Shared singleton instance of the tvOS implementation."}]},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PushwooshTVOSImplementation/registerForTvPushNotifications()":{"abstract":[{"type":"text","text":"Registers for tvOS push notifications."}],"url":"\/documentation\/pushwooshtvos\/pushwooshtvosimplementation\/registerfortvpushnotifications()","type":"topic","role":"symbol","title":"registerForTvPushNotifications()","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/registerForTvPushNotifications()","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"registerForTvPushNotifications","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"registerForTvPushNotifications","kind":"identifier"}]},"doc://com.pushwoosh.PushwooshTVOS/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/objc(cs)NSObject"},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PushwooshTVOSImplementation/setRichMediaGetTagsHandler(_:)":{"url":"\/documentation\/pushwooshtvos\/pushwooshtvosimplementation\/setrichmediagettagshandler(_:)","abstract":[{"text":"Sets a handler to receive tags when requested from rich media content.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setRichMediaGetTagsHandler"},{"text":"(([","kind":"text"},{"text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"setRichMediaGetTagsHandler:"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/setRichMediaGetTagsHandler(_:)","kind":"symbol","title":"setRichMediaGetTagsHandler(_:)"},"doc://com.pushwoosh.PushwooshTVOS/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/objc(pl)NSObject"},"doc://com.pushwoosh.PushwooshTVOS/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/s7CVarArgP"},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS":{"role":"collection","identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS","kind":"symbol","abstract":[{"text":"Push notifications and Rich Media for tvOS apps.","type":"text"}],"url":"\/documentation\/pushwooshtvos","type":"topic","title":"PushwooshTVOS"},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PushwooshTVOSImplementation/tvos()":{"abstract":[],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"tvos","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/tvos()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"tvos","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"AnyClass","preciseIdentifier":"s:s8AnyClassa"}],"title":"tvos()","url":"\/documentation\/pushwooshtvos\/pushwooshtvosimplementation\/tvos()"},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PushwooshTVOSImplementation/configureRichMediaWith(position:presentAnimation:dismissAnimation:)":{"url":"\/documentation\/pushwooshtvos\/pushwooshtvosimplementation\/configurerichmediawith(position:presentanimation:dismissanimation:)","abstract":[{"text":"Configures rich media presentation, positioning, and dismissal animations for tvOS.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"configureRichMediaWith","kind":"identifier"},{"text":"(","kind":"text"},{"text":"position","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PWTVOSRichMediaPosition","preciseIdentifier":"c:@M@PushwooshBridge@E@PWTVOSRichMediaPosition"},{"kind":"text","text":", "},{"kind":"externalParam","text":"presentAnimation"},{"text":": ","kind":"text"},{"text":"PWTVOSRichMediaPresentAnimation","kind":"typeIdentifier","preciseIdentifier":"c:@M@PushwooshBridge@E@PWTVOSRichMediaPresentAnimation"},{"kind":"text","text":", "},{"kind":"externalParam","text":"dismissAnimation"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@PushwooshBridge@E@PWTVOSRichMediaDismissAnimation","kind":"typeIdentifier","text":"PWTVOSRichMediaDismissAnimation"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"configureRichMediaWithPosition:presentAnimation:dismissAnimation:","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/configureRichMediaWith(position:presentAnimation:dismissAnimation:)","title":"configureRichMediaWith(position:presentAnimation:dismissAnimation:)","kind":"symbol"},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PushwooshTVOSImplementation/unregisterForPushNotifications(completion:)":{"title":"unregisterForPushNotifications(completion:)","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"unregisterForPushNotifications","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"unregisterForPushNotificationsWithCompletion:"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/unregisterForPushNotifications(completion:)","url":"\/documentation\/pushwooshtvos\/pushwooshtvosimplementation\/unregisterforpushnotifications(completion:)","abstract":[{"type":"text","text":"Unregisters the tvOS device from receiving push notifications."}]},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PushwooshTVOSImplementation/configureCloseButton(_:)":{"url":"\/documentation\/pushwooshtvos\/pushwooshtvosimplementation\/configureclosebutton(_:)","abstract":[{"text":"Controls whether the Close button is displayed on rich media content.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"configureCloseButton"},{"text":"(","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"configureCloseButton:"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/configureCloseButton(_:)","title":"configureCloseButton(_:)","kind":"symbol"},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PushwooshTVOSImplementation":{"type":"topic","abstract":[{"text":"Main implementation class for tvOS push notifications and Rich Media.","type":"text"}],"url":"\/documentation\/pushwooshtvos\/pushwooshtvosimplementation","role":"symbol","title":"PushwooshTVOSImplementation","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PushwooshTVOSImplementation","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PushwooshTVOSImplementation"}]},"doc://com.pushwoosh.PushwooshTVOS/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/SQ"},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PushwooshTVOSImplementation/registerForPushNotifications(withToken:completion:)":{"type":"topic","abstract":[{"text":"Registers the tvOS device for push notifications with the Pushwoosh server.","type":"text"}],"url":"\/documentation\/pushwooshtvos\/pushwooshtvosimplementation\/registerforpushnotifications(withtoken:completion:)","role":"symbol","title":"registerForPushNotifications(withToken:completion:)","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/registerForPushNotifications(withToken:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"registerForPushNotifications","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withToken"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"navigatorTitle":[{"text":"registerForPushNotificationsWithToken:completion:","kind":"identifier"}]},"doc://com.pushwoosh.PushwooshTVOS/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/SH"},"doc://com.pushwoosh.PushwooshTVOS/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/s23CustomStringConvertibleP"},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PushwooshTVOSImplementation/handleTvPushReceived(userInfo:completionHandler:)":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"handleTvPushReceived","kind":"identifier"},{"text":"(","kind":"text"},{"text":"userInfo","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"], "},{"text":"completionHandler","kind":"externalParam"},{"kind":"text","text":": ("},{"text":"UIBackgroundFetchResult","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIBackgroundFetchResult"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")","kind":"text"}],"type":"topic","navigatorTitle":[{"text":"handleTvPushReceivedWithUserInfo:completionHandler:","kind":"identifier"}],"abstract":[{"text":"Handles incoming push notification on tvOS.","type":"text"}],"title":"handleTvPushReceived(userInfo:completionHandler:)","url":"\/documentation\/pushwooshtvos\/pushwooshtvosimplementation\/handletvpushreceived(userinfo:completionhandler:)","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/handleTvPushReceived(userInfo:completionHandler:)","role":"symbol"},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PushwooshTVOSImplementation/handleTVOSPush(userInfo:)":{"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handleTVOSPush"},{"kind":"text","text":"("},{"kind":"externalParam","text":"userInfo"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"type":"topic","navigatorTitle":[{"text":"handleTVOSPushWithUserInfo:","kind":"identifier"}],"abstract":[{"text":"Handles incoming push notifications with rich media content for tvOS.","type":"text"}],"title":"handleTVOSPush(userInfo:)","url":"\/documentation\/pushwooshtvos\/pushwooshtvosimplementation\/handletvospush(userinfo:)","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/handleTVOSPush(userInfo:)","role":"symbol"},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PushwooshTVOSImplementation/richMediaManager":{"url":"\/documentation\/pushwooshtvos\/pushwooshtvosimplementation\/richmediamanager","abstract":[{"text":"Rich Media manager instance for displaying HTML content.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"richMediaManager"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@PushwooshTVOS@objc(cs)PWTVOSRichMediaManager","text":"PWTVOSRichMediaManager"}],"navigatorTitle":[{"text":"richMediaManager","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/richMediaManager","kind":"symbol","title":"richMediaManager"},"doc://com.pushwoosh.PushwooshTVOS/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/platforms","value":[{"unavailable":false,"beta":false,"introducedAt":"11.0","deprecated":false,"name":"tvOS"}],"op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"PushwooshTVOSImplementation"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"PushwooshTVOSImplementation","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"PushwooshTVOSImplementation"}],"op":"replace"},{"value":[{"title":"Configuration","identifiers":["doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/setAppCode(_:)","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/registerForTvPushNotifications()","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/registerForPushNotifications(withToken:completion:)"]},{"identifiers":["doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/handleTvPushToken(_:)","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/handleTvPushRegistrationFailure(_:)","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/handleTvPushReceived(userInfo:completionHandler:)","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/handleTVOSPush(userInfo:)"],"title":"Push Handling"},{"title":"Rich Media","identifiers":["doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/richMediaManager","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/configureRichMediaWith(position:presentAnimation:dismissAnimation:)","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/configureCloseButton(_:)","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/setRichMediaGetTagsHandler(_:)"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/unregisterForPushNotifications(completion:)"]},{"identifiers":["doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/shared"],"title":"Type Properties"},{"identifiers":["doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation\/tvos()"],"title":"Type Methods"}],"path":"\/topicSections","op":"replace"},{"path":"\/relationshipsSections","value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.pushwoosh.PushwooshTVOS\/objc(cs)NSObject"],"type":"inheritsFrom"}],"op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PushwooshTVOSImplementation","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"platforms":["tvOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"setAppCode:","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1setAppCode(_:)\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1setAppCode(_:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"setAppCode:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1handleTvPushRegistrationFailure(_:)\/title","value":"handleTvPushRegistrationFailure:","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1handleTvPushRegistrationFailure(_:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"handleTvPushRegistrationFailure:"}]},{"op":"replace","value":"handleTvPushToken:","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1handleTvPushToken(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1handleTvPushToken(_:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"handleTvPushToken:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1shared\/title","value":"shared"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1shared\/fragments","value":[{"text":"shared","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1registerForTvPushNotifications()\/title","value":"registerForTvPushNotifications"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"registerForTvPushNotifications"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1registerForTvPushNotifications()\/fragments"},{"value":"setRichMediaGetTagsHandler:","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1setRichMediaGetTagsHandler(_:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1setRichMediaGetTagsHandler(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"setRichMediaGetTagsHandler:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1tvos()\/title","value":"tvos","op":"replace"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"tvos"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1tvos()\/fragments"},{"op":"replace","value":"configureRichMediaWithPosition:presentAnimation:dismissAnimation:","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1configureRichMediaWith(position:presentAnimation:dismissAnimation:)\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1configureRichMediaWith(position:presentAnimation:dismissAnimation:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"configureRichMediaWithPosition:presentAnimation:dismissAnimation:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1unregisterForPushNotifications(completion:)\/title","value":"unregisterForPushNotificationsWithCompletion:"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1unregisterForPushNotifications(completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"unregisterForPushNotificationsWithCompletion:"}]},{"value":"configureCloseButton:","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1configureCloseButton(_:)\/title"},{"value":[{"kind":"text","text":"+ "},{"text":"configureCloseButton:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1configureCloseButton(_:)\/fragments","op":"replace"},{"value":"PushwooshTVOSImplementation","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation\/fragments","value":[{"text":"PushwooshTVOSImplementation","kind":"identifier"}]},{"value":"registerForPushNotificationsWithToken:completion:","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1registerForPushNotifications(withToken:completion:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1registerForPushNotifications(withToken:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"registerForPushNotificationsWithToken:completion:"}]},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1handleTvPushReceived(userInfo:completionHandler:)\/title","value":"handleTvPushReceivedWithUserInfo:completionHandler:","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1handleTvPushReceived(userInfo:completionHandler:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"handleTvPushReceivedWithUserInfo:completionHandler:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1handleTVOSPush(userInfo:)\/title","value":"handleTVOSPushWithUserInfo:"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1handleTVOSPush(userInfo:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"handleTVOSPushWithUserInfo:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1richMediaManager\/title","value":"richMediaManager"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation~1richMediaManager\/fragments","value":[{"text":"richMediaManager","kind":"identifier"}]}]}]}