{"topicSections":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PWTVOSRichMediaManager\/animationType","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PWTVOSRichMediaManager\/dismissAnimationType","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PWTVOSRichMediaManager\/position"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PWTVOSRichMediaManager\/configureCloseButton(_:)","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PWTVOSRichMediaManager\/configureRichMediaWith(position:presentAnimation:dismissAnimation:)","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PWTVOSRichMediaManager\/dismiss(animated:)","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PWTVOSRichMediaManager\/handleInAppResource(_:)","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PWTVOSRichMediaManager\/setGetTagsHandler(_:)"]}],"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.pushwoosh.PushwooshTVOS\/objc(cs)NSObject"]},{"title":"Conforms To","identifiers":["doc:\/\/com.pushwoosh.PushwooshTVOS\/objc(pl)NSObject","doc:\/\/com.pushwoosh.PushwooshTVOS\/s7CVarArgP","doc:\/\/com.pushwoosh.PushwooshTVOS\/s28CustomDebugStringConvertibleP","doc:\/\/com.pushwoosh.PushwooshTVOS\/s23CustomStringConvertibleP","doc:\/\/com.pushwoosh.PushwooshTVOS\/SQ","doc:\/\/com.pushwoosh.PushwooshTVOS\/SH"],"type":"conformsTo","kind":"relationships"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"role":"symbol","symbolKind":"class","navigatorTitle":[{"kind":"identifier","text":"PWTVOSRichMediaManager"}],"roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PWTVOSRichMediaManager","kind":"identifier"}],"externalID":"c:@M@PushwooshTVOS@objc(cs)PWTVOSRichMediaManager","modules":[{"name":"PushwooshTVOS"}],"platforms":[{"name":"tvOS","deprecated":false,"unavailable":false,"introducedAt":"11.0","beta":false}],"title":"PWTVOSRichMediaManager"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshtvos\/pwtvosrichmediamanager"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshtvos\/pwtvosrichmediamanager"]}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["tvOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(PWTVOSRichMediaManager) "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PWTVOSRichMediaManager"}],"languages":["swift"]}]},{"kind":"content","content":[{"text":"Overview","type":"heading","anchor":"overview","level":2},{"inlineContent":[{"type":"text","text":"This class handles the parsing, rendering, and display of HTML-based Rich Media"},{"type":"text","text":" "},{"type":"text","text":"content with full support for tvOS Focus Engine and Apple TV remote navigation."}],"type":"paragraph"},{"text":"Overview","level":2,"anchor":"Overview","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The Rich Media manager automatically:"}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"Parses HTML content with inline styles"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Renders native UIKit components"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Configures focus navigation for tvOS remote","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Handles button actions (events, tags, close)"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Manages presentation and dismissal animations","type":"text"}]}]}]},{"anchor":"Usage","level":2,"text":"Usage","type":"heading"},{"inlineContent":[{"text":"Configure Rich Media behavior during app initialization:","type":"text"}],"type":"paragraph"},{"syntax":"swift","code":["Pushwoosh.TVoS.configureRichMediaWith(","    position: .center,","    presentAnimation: .fromBottom,","    dismissAnimation: .toBottom",")"],"type":"codeListing"}]}],"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PWTVOSRichMediaManager","interfaceLanguage":"swift"},"sections":[],"abstract":[{"text":"Manager for displaying Rich Media content on tvOS.","type":"text"}],"references":{"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS":{"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS","title":"PushwooshTVOS","url":"\/documentation\/pushwooshtvos","role":"collection","kind":"symbol","abstract":[{"text":"Push notifications and Rich Media for tvOS apps.","type":"text"}]},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PWTVOSRichMediaManager/handleInAppResource(_:)":{"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"handleInAppResource:"}],"url":"\/documentation\/pushwooshtvos\/pwtvosrichmediamanager\/handleinappresource(_:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handleInAppResource"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s9AnyObjecta","text":"AnyObject"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PWTVOSRichMediaManager\/handleInAppResource(_:)","title":"handleInAppResource(_:)","abstract":[{"text":"Handles in-app resource for Rich Media display.","type":"text"}]},"doc://com.pushwoosh.PushwooshTVOS/objc(cs)NSObject":{"identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PWTVOSRichMediaManager/setGetTagsHandler(_:)":{"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setGetTagsHandler:"}],"url":"\/documentation\/pushwooshtvos\/pwtvosrichmediamanager\/setgettagshandler(_:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setGetTagsHandler"},{"kind":"text","text":"((["},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PWTVOSRichMediaManager\/setGetTagsHandler(_:)","title":"setGetTagsHandler(_:)","abstract":[{"type":"text","text":"Sets a handler for getTags button actions in Rich Media."}]},"doc://com.pushwoosh.PushwooshTVOS/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PWTVOSRichMediaManager/dismissAnimationType":{"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"dismissAnimationType"}],"url":"\/documentation\/pushwooshtvos\/pwtvosrichmediamanager\/dismissanimationtype","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dismissAnimationType"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"PWTVOSRichMediaDismissAnimation","preciseIdentifier":"c:@M@PushwooshBridge@E@PWTVOSRichMediaDismissAnimation"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PWTVOSRichMediaManager\/dismissAnimationType","title":"dismissAnimationType","abstract":[{"text":"The animation type used when dismissing Rich Media.","type":"text"}]},"doc://com.pushwoosh.PushwooshTVOS/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.pushwoosh.PushwooshTVOS/s7CVarArgP":{"identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PWTVOSRichMediaManager/dismiss(animated:)":{"role":"symbol","type":"topic","navigatorTitle":[{"text":"dismissWithAnimated:","kind":"identifier"}],"url":"\/documentation\/pushwooshtvos\/pwtvosrichmediamanager\/dismiss(animated:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dismiss"},{"kind":"text","text":"("},{"kind":"externalParam","text":"animated"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PWTVOSRichMediaManager\/dismiss(animated:)","title":"dismiss(animated:)","abstract":[{"text":"Dismisses currently displayed Rich Media.","type":"text"}]},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PWTVOSRichMediaManager/animationType":{"abstract":[{"text":"The animation type used when presenting Rich Media.","type":"text"}],"title":"animationType","type":"topic","role":"symbol","navigatorTitle":[{"text":"animationType","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"animationType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PWTVOSRichMediaPresentAnimation","kind":"typeIdentifier","preciseIdentifier":"c:@M@PushwooshBridge@E@PWTVOSRichMediaPresentAnimation"}],"url":"\/documentation\/pushwooshtvos\/pwtvosrichmediamanager\/animationtype","identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PWTVOSRichMediaManager\/animationType","kind":"symbol"},"doc://com.pushwoosh.PushwooshTVOS/objc(pl)NSObject":{"identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.pushwoosh.PushwooshTVOS/SH":{"identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.pushwoosh.PushwooshTVOS/SQ":{"identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PWTVOSRichMediaManager/configureCloseButton(_:)":{"role":"symbol","type":"topic","navigatorTitle":[{"text":"configureCloseButton:","kind":"identifier"}],"url":"\/documentation\/pushwooshtvos\/pwtvosrichmediamanager\/configureclosebutton(_:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"configureCloseButton"},{"kind":"text","text":"("},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PWTVOSRichMediaManager\/configureCloseButton(_:)","title":"configureCloseButton(_:)","abstract":[{"text":"Controls visibility of the Close button on Rich Media.","type":"text"}]},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PWTVOSRichMediaManager/init":{"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/pushwooshtvos\/pwtvosrichmediamanager\/init","kind":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PWTVOSRichMediaManager\/init","title":"init","abstract":[]},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PWTVOSRichMediaManager":{"title":"PWTVOSRichMediaManager","identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PWTVOSRichMediaManager","kind":"symbol","type":"topic","url":"\/documentation\/pushwooshtvos\/pwtvosrichmediamanager","role":"symbol","navigatorTitle":[{"text":"PWTVOSRichMediaManager","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PWTVOSRichMediaManager"}],"abstract":[{"type":"text","text":"Manager for displaying Rich Media content on tvOS."}]},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PWTVOSRichMediaManager/configureRichMediaWith(position:presentAnimation:dismissAnimation:)":{"title":"configureRichMediaWith(position:presentAnimation:dismissAnimation:)","identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PWTVOSRichMediaManager\/configureRichMediaWith(position:presentAnimation:dismissAnimation:)","kind":"symbol","type":"topic","url":"\/documentation\/pushwooshtvos\/pwtvosrichmediamanager\/configurerichmediawith(position:presentanimation:dismissanimation:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"configureRichMediaWithPosition:presentAnimation:dismissAnimation:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"configureRichMediaWith","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"position"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@PushwooshBridge@E@PWTVOSRichMediaPosition","text":"PWTVOSRichMediaPosition"},{"kind":"text","text":", "},{"kind":"externalParam","text":"presentAnimation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PWTVOSRichMediaPresentAnimation","preciseIdentifier":"c:@M@PushwooshBridge@E@PWTVOSRichMediaPresentAnimation"},{"kind":"text","text":", "},{"text":"dismissAnimation","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@PushwooshBridge@E@PWTVOSRichMediaDismissAnimation","text":"PWTVOSRichMediaDismissAnimation","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Configures Rich Media presentation settings."}]},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PWTVOSRichMediaManager/position":{"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"position"}],"url":"\/documentation\/pushwooshtvos\/pwtvosrichmediamanager\/position","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"position"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@PushwooshBridge@E@PWTVOSRichMediaPosition","text":"PWTVOSRichMediaPosition"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PWTVOSRichMediaManager\/position","title":"position","abstract":[{"text":"The screen position where Rich Media will be displayed.","type":"text"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/platforms","value":[{"beta":false,"name":"tvOS","deprecated":false,"unavailable":false,"introducedAt":"11.0"}]},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"PWTVOSRichMediaManager"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"PWTVOSRichMediaManager"}]},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"PWTVOSRichMediaManager"}],"op":"replace"},{"op":"replace","value":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PWTVOSRichMediaManager\/animationType","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PWTVOSRichMediaManager\/dismissAnimationType","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PWTVOSRichMediaManager\/position"],"title":"Instance Properties"},{"identifiers":["doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PWTVOSRichMediaManager\/configureCloseButton(_:)","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PWTVOSRichMediaManager\/configureRichMediaWith(position:presentAnimation:dismissAnimation:)","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PWTVOSRichMediaManager\/dismiss(animated:)","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PWTVOSRichMediaManager\/handleInAppResource(_:)","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PWTVOSRichMediaManager\/init","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PWTVOSRichMediaManager\/setGetTagsHandler(_:)"],"title":"Instance Methods"}],"path":"\/topicSections"},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshTVOS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"PWTVOSRichMediaManager","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"languages":["occ"],"platforms":["tvOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PWTVOSRichMediaManager~1handleInAppResource(_:)\/title","value":"handleInAppResource:"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PWTVOSRichMediaManager~1handleInAppResource(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"handleInAppResource:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PWTVOSRichMediaManager~1setGetTagsHandler(_:)\/title","value":"setGetTagsHandler:"},{"value":[{"kind":"text","text":"- "},{"text":"setGetTagsHandler:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PWTVOSRichMediaManager~1setGetTagsHandler(_:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PWTVOSRichMediaManager~1dismissAnimationType\/title","value":"dismissAnimationType","op":"replace"},{"value":[{"text":"dismissAnimationType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PWTVOSRichMediaManager~1dismissAnimationType\/fragments"},{"value":"dismissWithAnimated:","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PWTVOSRichMediaManager~1dismiss(animated:)\/title","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"dismissWithAnimated:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PWTVOSRichMediaManager~1dismiss(animated:)\/fragments"},{"value":"animationType","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PWTVOSRichMediaManager~1animationType\/title","op":"replace"},{"value":[{"kind":"identifier","text":"animationType"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PWTVOSRichMediaManager~1animationType\/fragments","op":"replace"},{"value":"configureCloseButton:","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PWTVOSRichMediaManager~1configureCloseButton(_:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"configureCloseButton:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PWTVOSRichMediaManager~1configureCloseButton(_:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PWTVOSRichMediaManager\/title","op":"replace","value":"PWTVOSRichMediaManager"},{"op":"replace","value":[{"text":"PWTVOSRichMediaManager","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PWTVOSRichMediaManager\/fragments"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PWTVOSRichMediaManager~1configureRichMediaWith(position:presentAnimation:dismissAnimation:)\/title","value":"configureRichMediaWithPosition:presentAnimation:dismissAnimation:","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"configureRichMediaWithPosition:presentAnimation:dismissAnimation:"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PWTVOSRichMediaManager~1configureRichMediaWith(position:presentAnimation:dismissAnimation:)\/fragments"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PWTVOSRichMediaManager~1position\/title","value":"position","op":"replace"},{"value":[{"kind":"identifier","text":"position"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PWTVOSRichMediaManager~1position\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}