{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshvoip\/pwvoipcalldelegate\/answercall(_:perform:voipmessage:)"]},{"paths":["\/documentation\/pushwooshvoip\/pwvoipcalldelegate\/answercall(_:perform:voipmessage:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate\/answerCall(_:perform:voipMessage:)"},"sections":[],"metadata":{"required":true,"externalID":"c:@M@PushwooshVoIP@objc(pl)PWVoIPCallDelegate(im)answerCall:perform:voipMessage:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"answerCall"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CXProvider","text":"CXProvider"},{"kind":"text","text":", "},{"text":"perform","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CXAnswerCallAction","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CXAnswerCallAction"},{"kind":"text","text":", "},{"kind":"externalParam","text":"voipMessage"},{"text":": ","kind":"text"},{"text":"PWVoIPMessage","kind":"typeIdentifier","preciseIdentifier":"c:@M@PushwooshVoIP@objc(cs)PWVoIPMessage"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"text":"answerCall:perform:voipMessage:","kind":"identifier"}],"roleHeading":"Instance Method","title":"answerCall(_:perform:voipMessage:)","role":"symbol","modules":[{"name":"PushwooshVoIP"}],"symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate"]]},"abstract":[{"text":"Called when user answers an incoming call.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"optional"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"answerCall"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"provider"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CXProvider","preciseIdentifier":"c:objc(cs)CXProvider"},{"text":", ","kind":"text"},{"text":"perform","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"action","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)CXAnswerCallAction","text":"CXAnswerCallAction","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"voipMessage"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@PushwooshVoIP@objc(cs)PWVoIPMessage","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPMessage","kind":"typeIdentifier","text":"PWVoIPMessage"},{"text":"?)","kind":"text"}],"languages":["swift"]}]}],"references":{"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPCallDelegate/answerCall(_:perform:voipMessage:)":{"required":true,"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"answerCall","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)CXProvider","text":"CXProvider","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"perform","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)CXAnswerCallAction","text":"CXAnswerCallAction","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"voipMessage","kind":"externalParam"},{"kind":"text","text":": "},{"text":"PWVoIPMessage","kind":"typeIdentifier","preciseIdentifier":"c:@M@PushwooshVoIP@objc(cs)PWVoIPMessage"},{"kind":"text","text":"?)"}],"url":"\/documentation\/pushwooshvoip\/pwvoipcalldelegate\/answercall(_:perform:voipmessage:)","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate\/answerCall(_:perform:voipMessage:)","navigatorTitle":[{"text":"answerCall:perform:voipMessage:","kind":"identifier"}],"title":"answerCall(_:perform:voipMessage:)","role":"symbol","abstract":[{"type":"text","text":"Called when user answers an incoming call."}],"kind":"symbol","type":"topic"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP":{"title":"PushwooshVoIP","kind":"symbol","type":"topic","url":"\/documentation\/pushwooshvoip","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP","abstract":[{"type":"text","text":"VoIP push notifications with native call UI for iOS applications."}],"role":"collection"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPCallDelegate":{"identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate","type":"topic","abstract":[{"type":"text","text":"Delegate protocol for receiving VoIP call events and CallKit callbacks."}],"url":"\/documentation\/pushwooshvoip\/pwvoipcalldelegate","role":"symbol","kind":"symbol","title":"PWVoIPCallDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PWVoIPCallDelegate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PWVoIPCallDelegate"}]},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPMessage":{"type":"topic","navigatorTitle":[{"text":"PWVoIPMessage","kind":"identifier"}],"abstract":[{"text":"An encapsulation of VoIP push notification payload data.","type":"text"}],"kind":"symbol","role":"symbol","url":"\/documentation\/pushwooshvoip\/pwvoipmessage","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPMessage","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PWVoIPMessage","kind":"identifier"}],"title":"PWVoIPMessage"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"answerCall:perform:voipMessage:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"answerCall:perform:voipMessage:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"text":"answerCall:","kind":"identifier"},{"kind":"text","text":"("},{"text":"CXProvider","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CXProvider"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"provider"},{"text":" ","kind":"text"},{"text":"perform:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)CXAnswerCallAction","kind":"typeIdentifier","text":"CXAnswerCallAction"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"action"},{"text":" ","kind":"text"},{"text":"voipMessage:","kind":"identifier"},{"kind":"text","text":"("},{"text":"PWVoIPMessage","kind":"typeIdentifier","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPMessage","preciseIdentifier":"c:@M@PushwooshVoIP@objc(cs)PWVoIPMessage"},{"text":" *) ","kind":"text"},{"text":"voipMessage","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate~1answerCall(_:perform:voipMessage:)\/title","value":"answerCall:perform:voipMessage:","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate~1answerCall(_:perform:voipMessage:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"answerCall:perform:voipMessage:"}]},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate\/title","value":"PWVoIPCallDelegate","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate\/fragments","value":[{"text":"PWVoIPCallDelegate","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPMessage\/title","value":"PWVoIPMessage"},{"value":[{"text":"PWVoIPMessage","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPMessage\/fragments","op":"replace"}]}]}