{"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWNotificationCenterDelegateProxy"]]},"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWNotificationCenterDelegateProxy\/add(_:)","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"metadata":{"modules":[{"name":"PushwooshFramework"}],"roleHeading":"Instance Method","title":"add(_:)","navigatorTitle":[{"text":"addNotificationCenterDelegate:","kind":"identifier"}],"externalID":"c:objc(cs)PWNotificationCenterDelegateProxy(im)addNotificationCenterDelegate:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"add","kind":"identifier"},{"kind":"text","text":"(any "},{"text":"UNUserNotificationCenterDelegate","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UNUserNotificationCenterDelegate"},{"kind":"text","text":")"}],"symbolKind":"method","role":"symbol"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"add"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"delegate","kind":"internalParam"},{"text":": any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UNUserNotificationCenterDelegate","text":"UNUserNotificationCenterDelegate"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/pushwooshframework\/pwnotificationcenterdelegateproxy\/add(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pushwooshframework\/pwnotificationcenterdelegateproxy\/add(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Adds extra UNUserNotificationCenterDelegate that handles foreground push notifications on iOS10.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWNotificationCenterDelegateProxy/add(_:)":{"navigatorTitle":[{"text":"addNotificationCenterDelegate:","kind":"identifier"}],"kind":"symbol","title":"add(_:)","abstract":[{"type":"text","text":"Adds extra UNUserNotificationCenterDelegate that handles foreground push notifications on iOS10."}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWNotificationCenterDelegateProxy\/add(_:)","url":"\/documentation\/pushwooshframework\/pwnotificationcenterdelegateproxy\/add(_:)","type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"add"},{"text":"(any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UNUserNotificationCenterDelegate","text":"UNUserNotificationCenterDelegate"},{"text":")","kind":"text"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWNotificationCenterDelegateProxy":{"navigatorTitle":[{"text":"PWNotificationCenterDelegateProxy","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PWNotificationCenterDelegateProxy"}],"title":"PWNotificationCenterDelegateProxy","role":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWNotificationCenterDelegateProxy","url":"\/documentation\/pushwooshframework\/pwnotificationcenterdelegateproxy","kind":"symbol"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","kind":"symbol","abstract":[],"title":"PushwooshFramework","url":"\/documentation\/pushwooshframework","type":"topic","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"addNotificationCenterDelegate:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"addNotificationCenterDelegate:","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"addNotificationCenterDelegate:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)UNUserNotificationCenterDelegate","text":"id<UNUserNotificationCenterDelegate>"},{"text":") ","kind":"text"},{"text":"delegate","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"addNotificationCenterDelegate:","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWNotificationCenterDelegateProxy~1add(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWNotificationCenterDelegateProxy~1add(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addNotificationCenterDelegate:"}]},{"value":"PWNotificationCenterDelegateProxy","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWNotificationCenterDelegateProxy\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWNotificationCenterDelegateProxy\/fragments","value":[{"kind":"identifier","text":"PWNotificationCenterDelegateProxy"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}