{"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWNotificationCenterDelegateProxy"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWNotificationCenterDelegateProxy\/defaultNotificationCenterDelegate","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","abstract":[{"text":"Returns UNUserNotificationCenterDelegate that handles foreground push notifications on iOS10","type":"text"}],"metadata":{"navigatorTitle":[{"text":"defaultNotificationCenterDelegate","kind":"identifier"}],"roleHeading":"Instance Property","symbolKind":"property","modules":[{"name":"PushwooshFramework"}],"title":"defaultNotificationCenterDelegate","role":"symbol","externalID":"c:objc(cs)PWNotificationCenterDelegateProxy(py)defaultNotificationCenterDelegate","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"defaultNotificationCenterDelegate","kind":"identifier"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UNUserNotificationCenterDelegate","text":"UNUserNotificationCenterDelegate"}]},"variants":[{"paths":["\/documentation\/pushwooshframework\/pwnotificationcenterdelegateproxy\/defaultnotificationcenterdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pushwooshframework\/pwnotificationcenterdelegateproxy\/defaultnotificationcenterdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"defaultNotificationCenterDelegate","kind":"identifier"},{"text":": any ","kind":"text"},{"text":"UNUserNotificationCenterDelegate","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UNUserNotificationCenterDelegate"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWNotificationCenterDelegateProxy/defaultNotificationCenterDelegate":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"defaultNotificationCenterDelegate","kind":"identifier"},{"text":": any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)UNUserNotificationCenterDelegate","kind":"typeIdentifier","text":"UNUserNotificationCenterDelegate"}],"url":"\/documentation\/pushwooshframework\/pwnotificationcenterdelegateproxy\/defaultnotificationcenterdelegate","kind":"symbol","navigatorTitle":[{"text":"defaultNotificationCenterDelegate","kind":"identifier"}],"title":"defaultNotificationCenterDelegate","abstract":[{"text":"Returns UNUserNotificationCenterDelegate that handles foreground push notifications on iOS10","type":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWNotificationCenterDelegateProxy\/defaultNotificationCenterDelegate","role":"symbol","type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"abstract":[{"type":"text","text":"Push notification SDK for iOS applications."}],"role":"collection","kind":"symbol","url":"\/documentation\/pushwooshframework","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","title":"PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWNotificationCenterDelegateProxy":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PWNotificationCenterDelegateProxy","kind":"identifier"}],"url":"\/documentation\/pushwooshframework\/pwnotificationcenterdelegateproxy","kind":"symbol","navigatorTitle":[{"text":"PWNotificationCenterDelegateProxy","kind":"identifier"}],"abstract":[],"title":"PWNotificationCenterDelegateProxy","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWNotificationCenterDelegateProxy","role":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","value":"defaultNotificationCenterDelegate","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","value":[{"text":"defaultNotificationCenterDelegate","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"id<UNUserNotificationCenterDelegate>","preciseIdentifier":"c:Qoobjc(pl)UNUserNotificationCenterDelegate","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"defaultNotificationCenterDelegate"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"defaultNotificationCenterDelegate","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWNotificationCenterDelegateProxy~1defaultNotificationCenterDelegate\/title"},{"value":[{"kind":"identifier","text":"defaultNotificationCenterDelegate"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWNotificationCenterDelegateProxy~1defaultNotificationCenterDelegate\/fragments"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWNotificationCenterDelegateProxy\/title","value":"PWNotificationCenterDelegateProxy","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWNotificationCenterDelegateProxy\/fragments","value":[{"kind":"identifier","text":"PWNotificationCenterDelegateProxy"}],"op":"replace"}]}]}