{"variants":[{"paths":["\/documentation\/pushwooshinboxkit\/pushwooshinboxcaptionedcell\/init(style:reuseidentifier:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pushwooshinboxkit\/pushwooshinboxcaptionedcell\/init(style:reuseidentifier:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"role":"symbol","roleHeading":"Initializer","navigatorTitle":[{"kind":"identifier","text":"initWithStyle:reuseIdentifier:"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"style","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableViewCell","text":"UITableViewCell"},{"text":".","kind":"text"},{"kind":"typeIdentifier","text":"CellStyle","preciseIdentifier":"c:@E@UITableViewCellStyle"},{"kind":"text","text":", "},{"kind":"externalParam","text":"reuseIdentifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?)","kind":"text"}],"modules":[{"name":"PushwooshInboxKit"}],"title":"init(style:reuseIdentifier:)","externalID":"c:@M@PushwooshInboxKit@objc(cs)PushwooshInboxCaptionedCell(im)initWithStyle:reuseIdentifier:","symbolKind":"init"},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit","doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCaptionedCell"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"style","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableViewCell","text":"UITableViewCell"},{"text":".","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@UITableViewCellStyle","text":"CellStyle"},{"kind":"text","text":", "},{"text":"reuseIdentifier","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCaptionedCell\/init(style:reuseIdentifier:)"},"references":{"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit":{"title":"PushwooshInboxKit","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit","type":"topic","abstract":[{"type":"text","text":"Modern UIKit inbox UI powered by Pushwoosh."}],"kind":"symbol","role":"collection","url":"\/documentation\/pushwooshinboxkit"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxCaptionedCell/init(style:reuseIdentifier:)":{"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxcaptionedcell\/init(style:reuseidentifier:)","type":"topic","title":"init(style:reuseIdentifier:)","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"style","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UITableViewCell","preciseIdentifier":"c:objc(cs)UITableViewCell","kind":"typeIdentifier"},{"kind":"text","text":"."},{"text":"CellStyle","preciseIdentifier":"c:@E@UITableViewCellStyle","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"reuseIdentifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"text":"initWithStyle:reuseIdentifier:","kind":"identifier"}],"abstract":[],"role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCaptionedCell\/init(style:reuseIdentifier:)"},"doc://com.pushwoosh.PushwooshInboxKit/documentation/PushwooshInboxKit/PushwooshInboxCaptionedCell":{"url":"\/documentation\/pushwooshinboxkit\/pushwooshinboxcaptionedcell","type":"topic","kind":"symbol","title":"PushwooshInboxCaptionedCell","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushwooshInboxCaptionedCell"}],"navigatorTitle":[{"text":"PushwooshInboxCaptionedCell","kind":"identifier"}],"abstract":[],"role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshInboxKit\/documentation\/PushwooshInboxKit\/PushwooshInboxCaptionedCell"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithStyle:reuseIdentifier:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithStyle:reuseIdentifier:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithStyle:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@UITableViewCellStyle","text":"UITableViewCellStyle"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"style"},{"text":" ","kind":"text"},{"kind":"identifier","text":"reuseIdentifier:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"reuseIdentifier"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxCaptionedCell~1init(style:reuseIdentifier:)\/title","op":"replace","value":"initWithStyle:reuseIdentifier:"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxCaptionedCell~1init(style:reuseIdentifier:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithStyle:reuseIdentifier:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxCaptionedCell\/title","value":"PushwooshInboxCaptionedCell"},{"value":[{"kind":"identifier","text":"PushwooshInboxCaptionedCell"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshInboxKit~1documentation~1PushwooshInboxKit~1PushwooshInboxCaptionedCell\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}