{"metadata":{"symbolKind":"method","roleHeading":"Type Method","externalID":"c:objc(cs)PWTagsBuilder(cm)appendValuesToListTag:","modules":[{"name":"PushwooshFramework"}],"title":"appendValues(toListTag:)","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"appendValues","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"toListTag"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]) -> ["},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]?","kind":"text"}],"navigatorTitle":[{"text":"appendValuesToListTag:","kind":"identifier"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"appendValues","kind":"identifier"},{"kind":"text","text":"("},{"text":"toListTag","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"array","kind":"internalParam"},{"text":": [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"]) -> [","kind":"text"},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"]?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Array of values to be added to the tag.","type":"text"}]}],"name":"array"}]},{"content":[{"text":"Return Value","anchor":"return-value","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"Dictionary to be sent as the value for the tag"}],"type":"paragraph"}],"kind":"content"},{"kind":"content","content":[{"anchor":"discussion","text":"Discussion","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"Example:"}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"type":"text","text":"NSDictionary *tags = @{"},{"type":"text","text":" "},{"type":"text","text":"@“Alias” : aliasField.text,"},{"text":" ","type":"text"},{"type":"text","text":"@“FavNumber” : @([favNumField.text intValue]),"},{"text":" ","type":"text"},{"text":"@“List” : [PWTags appendValuesToListTag:@[ @“Item1” ]]","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"};"}]},{"type":"paragraph","inlineContent":[{"text":"[[PushNotificationManager pushManager] setTags:tags];","type":"text"}]}]}],"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWTagsBuilder\/appendValues(toListTag:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWTagsBuilder"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pwtagsbuilder\/appendvalues(tolisttag:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pwtagsbuilder\/appendvalues(tolisttag:)"]}],"sections":[],"abstract":[{"type":"text","text":"Creates a dictionary for extending Tag’s values list with additional values"}],"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWTagsBuilder/appendValues(toListTag:)":{"title":"appendValues(toListTag:)","type":"topic","role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWTagsBuilder\/appendValues(toListTag:)","url":"\/documentation\/pushwooshframework\/pwtagsbuilder\/appendvalues(tolisttag:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"appendValues","kind":"identifier"},{"text":"(","kind":"text"},{"text":"toListTag","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"]) -> [","kind":"text"},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]?"}],"navigatorTitle":[{"kind":"identifier","text":"appendValuesToListTag:"}],"kind":"symbol","abstract":[{"type":"text","text":"Creates a dictionary for extending Tag’s values list with additional values"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"title":"PushwooshFramework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","kind":"symbol","type":"topic","url":"\/documentation\/pushwooshframework","role":"collection","abstract":[]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWTagsBuilder":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PWTagsBuilder"}],"title":"PWTagsBuilder","abstract":[{"type":"codeVoice","code":"PWTagsBuilder"},{"type":"text","text":" class encapsulates the methods for creating tags parameters for sending them to the server."}],"navigatorTitle":[{"text":"PWTagsBuilder","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWTagsBuilder","kind":"symbol","url":"\/documentation\/pushwooshframework\/pwtagsbuilder","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"appendValuesToListTag:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"text":"appendValuesToListTag:","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:objc(cs)NSDictionary","text":"NSDictionary","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"appendValuesToListTag:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSString *>"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"array"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"appendValuesToListTag:","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWTagsBuilder~1appendValues(toListTag:)\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWTagsBuilder~1appendValues(toListTag:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"text":"appendValuesToListTag:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWTagsBuilder\/title","value":"PWTagsBuilder"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWTagsBuilder\/fragments","value":[{"kind":"identifier","text":"PWTagsBuilder"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}