{"kind":"symbol","sections":[],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"incrementalTagWithInteger:"}],"role":"symbol","title":"incrementalTag(with:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"incrementalTag"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"with"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?"}],"roleHeading":"Type Method","symbolKind":"method","modules":[{"name":"PushwooshFramework"}],"externalID":"c:objc(cs)PWTagsBuilder(cm)incrementalTagWithInteger:"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pwtagsbuilder\/incrementaltag(with:)"]},{"paths":["\/documentation\/pushwooshframework\/pwtagsbuilder\/incrementaltag(with:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWTagsBuilder"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWTagsBuilder\/incrementalTag(with:)"},"abstract":[{"text":"Creates a dictionary for incrementing\/decrementing a numeric tag on the server.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"incrementalTag","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"delta","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":") -> ["},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]?","kind":"text"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"delta","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Difference that needs to be applied to the tag’s counter."}]}]}]},{"kind":"content","content":[{"text":"Return Value","type":"heading","level":2,"anchor":"return-value"},{"inlineContent":[{"text":"Dictionary, that needs to be sent as the value for the tag","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"heading","anchor":"discussion","text":"Discussion","level":2},{"inlineContent":[{"text":"Example:","type":"text"}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"text":"NSDictionary *tags = @{","type":"text"},{"type":"text","text":" "},{"type":"text","text":"@“Alias” : aliasField.text,"},{"type":"text","text":" "},{"text":"@“FavNumber” : @([favNumField.text intValue]),","type":"text"},{"type":"text","text":" "},{"type":"text","text":"@“price”: [PWTags incrementalTagWithInteger:5],"},{"text":" ","type":"text"},{"text":"};","type":"text"}]},{"inlineContent":[{"type":"text","text":"[[PushNotificationManager pushManager] setTags:tags];"}],"type":"paragraph"}],"kind":"content"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWTagsBuilder":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PWTagsBuilder"}],"navigatorTitle":[{"text":"PWTagsBuilder","kind":"identifier"}],"title":"PWTagsBuilder","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWTagsBuilder","abstract":[{"type":"codeVoice","code":"PWTagsBuilder"},{"type":"text","text":" class encapsulates the methods for creating tags parameters for sending them to the server."}],"kind":"symbol","url":"\/documentation\/pushwooshframework\/pwtagsbuilder","type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWTagsBuilder/incrementalTag(with:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"incrementalTag"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"text":") -> [","kind":"text"},{"text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]?"}],"navigatorTitle":[{"text":"incrementalTagWithInteger:","kind":"identifier"}],"title":"incrementalTag(with:)","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWTagsBuilder\/incrementalTag(with:)","abstract":[{"type":"text","text":"Creates a dictionary for incrementing\/decrementing a numeric tag on the server."}],"kind":"symbol","type":"topic","url":"\/documentation\/pushwooshframework\/pwtagsbuilder\/incrementaltag(with:)"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","title":"PushwooshFramework","url":"\/documentation\/pushwooshframework","kind":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"incrementalTagWithInteger:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"incrementalTagWithInteger:"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"text":"NSDictionary","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDictionary"},{"kind":"text","text":" *) "},{"text":"incrementalTagWithInteger:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"text":"delta","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWTagsBuilder\/title","op":"replace","value":"PWTagsBuilder"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWTagsBuilder\/fragments","value":[{"text":"PWTagsBuilder","kind":"identifier"}]},{"op":"replace","value":"incrementalTagWithInteger:","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWTagsBuilder~1incrementalTag(with:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWTagsBuilder~1incrementalTag(with:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"incrementalTagWithInteger:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}