{"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWTagsBuilder"]]},"sections":[],"variants":[{"paths":["\/documentation\/pushwooshframework\/pwtagsbuilder\/removevalues(fromlisttag:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pwtagsbuilder\/removevalues(fromlisttag:)"]}],"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWTagsBuilder\/removeValues(fromListTag:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"role":"symbol","externalID":"c:objc(cs)PWTagsBuilder(cm)removeValuesFromListTag:","modules":[{"name":"PushwooshFramework"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"removeValues","kind":"identifier"},{"text":"(","kind":"text"},{"text":"fromListTag","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"]) -> [","kind":"text"},{"preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier","text":"AnyHashable"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]?","kind":"text"}],"roleHeading":"Type Method","navigatorTitle":[{"kind":"identifier","text":"removeValuesFromListTag:"}],"title":"removeValues(fromListTag:)","symbolKind":"method"},"abstract":[{"text":"Creates a dictionary for removing Tag’s values from existing values list","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removeValues","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fromListTag"},{"text":" ","kind":"text"},{"text":"array","kind":"internalParam"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"]) -> ["},{"preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier","text":"AnyHashable"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"array","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Array of values to be removed from the tag."}]}]}]},{"kind":"content","content":[{"type":"heading","text":"Return Value","anchor":"return-value","level":2},{"type":"paragraph","inlineContent":[{"text":"Dictionary to be sent as the value for the tag","type":"text"}]}]},{"kind":"content","content":[{"type":"heading","anchor":"discussion","level":2,"text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"Example:","type":"text"}]},{"type":"codeListing","code":["func removeInterest(_ interest: String) {","    let tags: [AnyHashable: Any] = [","        \"interests\": PWTagsBuilder.removeValues(fromListTag: [interest])","    ]","    Pushwoosh.configure.setTags(tags)","}"],"syntax":"swift"}]}],"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"abstract":[{"text":"Push notification SDK for iOS applications.","type":"text"}],"title":"PushwooshFramework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","kind":"symbol","type":"topic","url":"\/documentation\/pushwooshframework","role":"collection"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWTagsBuilder/removeValues(fromListTag:)":{"role":"symbol","url":"\/documentation\/pushwooshframework\/pwtagsbuilder\/removevalues(fromlisttag:)","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Creates a dictionary for removing Tag’s values from existing values list"}],"title":"removeValues(fromListTag:)","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removeValues","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"fromListTag"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"]) -> [","kind":"text"},{"text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWTagsBuilder\/removeValues(fromListTag:)","navigatorTitle":[{"kind":"identifier","text":"removeValuesFromListTag:"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PWTagsBuilder":{"role":"symbol","type":"topic","url":"\/documentation\/pushwooshframework\/pwtagsbuilder","kind":"symbol","abstract":[{"type":"codeVoice","code":"PWTagsBuilder"},{"type":"text","text":" class encapsulates the methods for creating tags parameters for sending them to the server."}],"title":"PWTagsBuilder","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PWTagsBuilder","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PWTagsBuilder","navigatorTitle":[{"text":"PWTagsBuilder","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"value":"removeValuesFromListTag:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"removeValuesFromListTag:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"text":"NSDictionary","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDictionary"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"removeValuesFromListTag:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<NSString *>"},{"kind":"text","text":" *) "},{"text":"array","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"removeValuesFromListTag:","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWTagsBuilder~1removeValues(fromListTag:)\/title"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"text":"removeValuesFromListTag:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWTagsBuilder~1removeValues(fromListTag:)\/fragments"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWTagsBuilder\/title","value":"PWTagsBuilder","op":"replace"},{"value":[{"text":"PWTagsBuilder","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PWTagsBuilder\/fragments"}]}]}