{"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/additionalAuthorizationOptions"},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"abstract":[{"type":"text","text":"Authorization options in addition to UNAuthorizationOptionBadge | UNAuthorizationOptionSound | UNAuthorizationOptionAlert | UNAuthorizationOptionCarPlay."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"additionalAuthorizationOptions","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UNAuthorizationOptions","kind":"typeIdentifier","preciseIdentifier":"c:@E@UNAuthorizationOptions"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/pushwooshframework\/pushnotificationmanager\/additionalauthorizationoptions"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pushnotificationmanager\/additionalauthorizationoptions"]}],"metadata":{"externalID":"c:objc(cs)PushNotificationManager(py)additionalAuthorizationOptions","modules":[{"name":"PushwooshFramework"}],"role":"symbol","platforms":[{"name":"iOS","introducedAt":"12.0","unavailable":false,"deprecated":false,"beta":false}],"title":"additionalAuthorizationOptions","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"additionalAuthorizationOptions","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UNAuthorizationOptions","kind":"typeIdentifier","preciseIdentifier":"c:@E@UNAuthorizationOptions"}],"navigatorTitle":[{"kind":"identifier","text":"additionalAuthorizationOptions"}],"symbolKind":"property","roleHeading":"Instance Property"},"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"abstract":[{"text":"Push notification SDK for iOS applications.","type":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","type":"topic","title":"PushwooshFramework","url":"\/documentation\/pushwooshframework","kind":"symbol","role":"collection"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationManager":{"title":"PushNotificationManager","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager","kind":"symbol","url":"\/documentation\/pushwooshframework\/pushnotificationmanager","role":"symbol","abstract":[{"code":"PushNotificationManager","type":"codeVoice"},{"type":"text","text":" class offers access to the singleton-instance of the push manager responsible for registering the device with the APS servers, receiving and processing push notifications."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PushNotificationManager","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PushNotificationManager"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationManager/additionalAuthorizationOptions":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"additionalAuthorizationOptions"},{"text":": ","kind":"text"},{"text":"UNAuthorizationOptions","kind":"typeIdentifier","preciseIdentifier":"c:@E@UNAuthorizationOptions"}],"title":"additionalAuthorizationOptions","navigatorTitle":[{"text":"additionalAuthorizationOptions","kind":"identifier"}],"type":"topic","abstract":[{"text":"Authorization options in addition to UNAuthorizationOptionBadge | UNAuthorizationOptionSound | UNAuthorizationOptionAlert | UNAuthorizationOptionCarPlay.","type":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/additionalAuthorizationOptions","url":"\/documentation\/pushwooshframework\/pushnotificationmanager\/additionalauthorizationoptions","kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":[{"name":"iOS","introducedAt":"12.0","unavailable":false,"deprecated":false,"beta":false}],"op":"replace","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"additionalAuthorizationOptions","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"additionalAuthorizationOptions","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"UNAuthorizationOptions","kind":"typeIdentifier","preciseIdentifier":"c:@E@UNAuthorizationOptions"},{"text":" ","kind":"text"},{"text":"additionalAuthorizationOptions","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager\/title","value":"PushNotificationManager"},{"value":[{"text":"PushNotificationManager","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager\/fragments"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1additionalAuthorizationOptions\/title","op":"replace","value":"additionalAuthorizationOptions"},{"value":[{"text":"additionalAuthorizationOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1additionalAuthorizationOptions\/fragments","op":"replace"}]}]}