{"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/clearNotificationCenter()","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"clearNotificationCenter","kind":"identifier"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager"]]},"metadata":{"modules":[{"name":"PushwooshFramework"}],"roleHeading":"Type Method","externalID":"c:objc(cs)PushNotificationManager(cm)clearNotificationCenter","title":"clearNotificationCenter()","symbolKind":"method","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"clearNotificationCenter","kind":"identifier"},{"kind":"text","text":"()"}],"navigatorTitle":[{"text":"clearNotificationCenter","kind":"identifier"}]},"variants":[{"paths":["\/documentation\/pushwooshframework\/pushnotificationmanager\/clearnotificationcenter()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pushnotificationmanager\/clearnotificationcenter()"]}],"sections":[],"abstract":[{"text":"Clears the notifications from the notification center.","type":"text"}],"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationManager":{"url":"\/documentation\/pushwooshframework\/pushnotificationmanager","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushNotificationManager"}],"navigatorTitle":[{"text":"PushNotificationManager","kind":"identifier"}],"abstract":[{"code":"PushNotificationManager","type":"codeVoice"},{"type":"text","text":" class offers access to the singleton-instance of the push manager responsible for registering the device with the APS servers, receiving and processing push notifications."}],"role":"symbol","kind":"symbol","title":"PushNotificationManager"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationManager/clearNotificationCenter()":{"url":"\/documentation\/pushwooshframework\/pushnotificationmanager\/clearnotificationcenter()","abstract":[{"text":"Clears the notifications from the notification center.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"clearNotificationCenter","kind":"identifier"},{"text":"()","kind":"text"}],"title":"clearNotificationCenter()","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/clearNotificationCenter()","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"clearNotificationCenter"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"abstract":[{"text":"Push notification SDK for iOS applications.","type":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","title":"PushwooshFramework","kind":"symbol","role":"collection","url":"\/documentation\/pushwooshframework","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"clearNotificationCenter"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"+ "},{"text":"clearNotificationCenter","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"clearNotificationCenter","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager\/title","value":"PushNotificationManager"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager\/fragments","value":[{"kind":"identifier","text":"PushNotificationManager"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1clearNotificationCenter()\/title","op":"replace","value":"clearNotificationCenter"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1clearNotificationCenter()\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"clearNotificationCenter"}]}]}]}