{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pushnotificationmanager\/delegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pushnotificationmanager\/delegate"]}],"metadata":{"externalID":"c:objc(cs)PushNotificationManager(py)delegate","roleHeading":"Instance Property","navigatorTitle":[{"text":"delegate","kind":"identifier"}],"symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"kind":"text","text":": (any "},{"preciseIdentifier":"c:objc(pl)NSObject","text":"NSObjectProtocol","kind":"typeIdentifier"},{"kind":"text","text":" & "},{"text":"PushNotificationDelegate","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)PushNotificationDelegate"},{"text":")!","kind":"text"}],"role":"symbol","modules":[{"name":"PushwooshFramework"}],"title":"delegate"},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"weak","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"text":": (any ","kind":"text"},{"text":"NSObjectProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"},{"kind":"text","text":" & "},{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationDelegate","text":"PushNotificationDelegate","preciseIdentifier":"c:objc(pl)PushNotificationDelegate","kind":"typeIdentifier"},{"kind":"text","text":")! { "},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/delegate"},"kind":"symbol","abstract":[{"code":"PushNotificationDelegate","type":"codeVoice"},{"type":"text","text":" protocol delegate that would receive the information about events for push notification manager such as registering with APS services, receiving push notifications or working with the received notification."},{"type":"text","text":" "},{"text":"Pushwoosh Runtime sets it to ApplicationDelegate by default","type":"text"}],"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationManager":{"title":"PushNotificationManager","navigatorTitle":[{"text":"PushNotificationManager","kind":"identifier"}],"role":"symbol","abstract":[{"type":"codeVoice","code":"PushNotificationManager"},{"type":"text","text":" class offers access to the singleton-instance of the push manager responsible for registering the device with the APS servers, receiving and processing push notifications."}],"kind":"symbol","url":"\/documentation\/pushwooshframework\/pushnotificationmanager","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PushNotificationManager","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"kind":"symbol","type":"topic","abstract":[{"text":"Push notification SDK for iOS applications.","type":"text"}],"url":"\/documentation\/pushwooshframework","title":"PushwooshFramework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","role":"collection"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationManager/delegate":{"navigatorTitle":[{"text":"delegate","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/delegate","abstract":[{"code":"PushNotificationDelegate","type":"codeVoice"},{"text":" protocol delegate that would receive the information about events for push notification manager such as registering with APS services, receiving push notifications or working with the received notification.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Pushwoosh Runtime sets it to ApplicationDelegate by default"}],"url":"\/documentation\/pushwooshframework\/pushnotificationmanager\/delegate","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier","text":"NSObjectProtocol"},{"text":" & ","kind":"text"},{"text":"PushNotificationDelegate","preciseIdentifier":"c:objc(pl)PushNotificationDelegate","kind":"typeIdentifier"},{"text":")!","kind":"text"}],"title":"delegate","type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationDelegate":{"type":"topic","kind":"symbol","abstract":[{"type":"codeVoice","code":"PushNotificationDelegate"},{"type":"text","text":" protocol defines the methods that can be implemented in the delegate of the "},{"code":"PushNotificationManager","type":"codeVoice"},{"text":" class’ singleton object.","type":"text"},{"type":"text","text":" "},{"text":"These methods provide information about the key events for push notification manager such as registering with APS services, receiving push notifications or working with the received notification.","type":"text"},{"text":" ","type":"text"},{"text":"These methods implementation allows to react on these events properly.","type":"text"}],"url":"\/documentation\/pushwooshframework\/pushnotificationdelegate","title":"PushNotificationDelegate","navigatorTitle":[{"text":"PushNotificationDelegate","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PushNotificationDelegate","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationDelegate","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"delegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"delegate","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"weak","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:Q$objc(cs)NSObjectobjc(pl)PushNotificationDelegate","kind":"typeIdentifier","text":"NSObject<PushNotificationDelegate>"},{"kind":"text","text":" * "},{"kind":"identifier","text":"delegate"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager\/title","op":"replace","value":"PushNotificationManager"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager\/fragments","op":"replace","value":[{"text":"PushNotificationManager","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1delegate\/title","value":"delegate","op":"replace"},{"value":[{"text":"delegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1delegate\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationDelegate\/title","value":"PushNotificationDelegate","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationDelegate\/fragments","value":[{"kind":"identifier","text":"PushNotificationDelegate"}]}]}]}