{"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"getCustomPushData","kind":"identifier"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"text":"]!) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"!","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"getCustomPushData:"}],"symbolKind":"method","roleHeading":"Instance Method","modules":[{"name":"PushwooshFramework"}],"externalID":"c:objc(cs)PushNotificationManager(im)getCustomPushData:","title":"getCustomPushData(_:)","role":"symbol"},"variants":[{"paths":["\/documentation\/pushwooshframework\/pushnotificationmanager\/getcustompushdata(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pushnotificationmanager\/getcustompushdata(_:)"]}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"getCustomPushData","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"pushNotification","kind":"internalParam"},{"kind":"text","text":": ["},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!) -> "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"!","kind":"text"}]}]},{"parameters":[{"name":"pushNotification","content":[{"type":"paragraph","inlineContent":[{"text":"Push notifications dictionary as received in ","type":"text"},{"code":"onPushAccepted: withNotification: onStart:","type":"codeVoice"}]}]}],"kind":"parameters"},{"content":[{"anchor":"discussion","type":"heading","text":"Discussion","level":2},{"inlineContent":[{"text":"Example:","type":"text"}],"type":"paragraph"},{"items":[{"content":[{"inlineContent":[{"type":"text","text":"(void)onPushAccepted:(PushNotificationManager *)pushManager withNotification:(NSDictionary *)pushNotification onStart:(BOOL)onStart {"},{"type":"text","text":" "},{"type":"text","text":"NSString * customData = [[PushNotificationsManager pushManager] getCustomPushData:pushNotification];"},{"text":" ","type":"text"},{"type":"text","text":"NSLog(@”%@”, customData);"},{"type":"text","text":" "},{"type":"text","text":"}"}],"type":"paragraph"}]}],"type":"unorderedList"}],"kind":"content"}],"abstract":[{"text":"Gets custom JSON string data from push notifications dictionary as specified in Pushwoosh Control Panel.","type":"text"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/getCustomPushData(_:)"},"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationManager":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PushNotificationManager"}],"abstract":[{"type":"codeVoice","code":"PushNotificationManager"},{"type":"text","text":" class offers access to the singleton-instance of the push manager responsible for registering the device with the APS servers, receiving and processing push notifications."}],"title":"PushNotificationManager","type":"topic","url":"\/documentation\/pushwooshframework\/pushnotificationmanager","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushNotificationManager"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","abstract":[{"text":"Push notification SDK for iOS applications.","type":"text"}],"title":"PushwooshFramework","type":"topic","url":"\/documentation\/pushwooshframework","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationManager/getCustomPushData(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"getCustomPushData","kind":"identifier"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]!) -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"!","kind":"text"}],"abstract":[{"type":"text","text":"Gets custom JSON string data from push notifications dictionary as specified in Pushwoosh Control Panel."}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/getCustomPushData(_:)","type":"topic","kind":"symbol","url":"\/documentation\/pushwooshframework\/pushnotificationmanager\/getcustompushdata(_:)","navigatorTitle":[{"text":"getCustomPushData:","kind":"identifier"}],"title":"getCustomPushData(_:)","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"getCustomPushData:","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"getCustomPushData:"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"getCustomPushData:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSDictionary","text":"NSDictionary","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"pushNotification","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager\/title","value":"PushNotificationManager"},{"value":[{"kind":"identifier","text":"PushNotificationManager"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager\/fragments"},{"op":"replace","value":"getCustomPushData:","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1getCustomPushData(_:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"getCustomPushData:"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1getCustomPushData(_:)\/fragments"}]}]}