{"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager"]]},"kind":"symbol","metadata":{"modules":[{"name":"PushwooshFramework"}],"navigatorTitle":[{"text":"getRemoteNotificationStatus","kind":"identifier"}],"symbolKind":"method","role":"symbol","title":"getRemoteNotificationStatus()","externalID":"c:objc(cs)PushNotificationManager(cm)getRemoteNotificationStatus","roleHeading":"Type Method","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"getRemoteNotificationStatus","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSMutableDictionary","text":"NSMutableDictionary"},{"text":"!","kind":"text"}]},"sections":[],"abstract":[{"text":"Returns dictionary with enabled remove notificaton types.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pushnotificationmanager\/getremotenotificationstatus()"]},{"paths":["\/documentation\/pushwooshframework\/pushnotificationmanager\/getremotenotificationstatus()"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getRemoteNotificationStatus"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSMutableDictionary","text":"NSMutableDictionary"},{"kind":"text","text":"!"}],"languages":["swift"]}],"kind":"declarations"},{"content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Example enabled push:"}]},{"inlineContent":[{"text":"where “type” field is UIUserNotificationType","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"Disabled push:"}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Note: In the latter example “enabled” field means that device can receive push notification but could not display alerts (ex: silent push)"}]}],"kind":"content"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/getRemoteNotificationStatus()"},"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","kind":"symbol","abstract":[],"title":"PushwooshFramework","url":"\/documentation\/pushwooshframework","type":"topic","role":"collection"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationManager":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PushNotificationManager"}],"abstract":[{"type":"codeVoice","code":"PushNotificationManager"},{"type":"text","text":" class offers access to the singleton-instance of the push manager responsible for registering the device with the APS servers, receiving and processing push notifications."}],"title":"PushNotificationManager","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PushNotificationManager","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager","url":"\/documentation\/pushwooshframework\/pushnotificationmanager"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationManager/getRemoteNotificationStatus()":{"type":"topic","abstract":[{"type":"text","text":"Returns dictionary with enabled remove notificaton types."}],"navigatorTitle":[{"text":"getRemoteNotificationStatus","kind":"identifier"}],"url":"\/documentation\/pushwooshframework\/pushnotificationmanager\/getremotenotificationstatus()","role":"symbol","title":"getRemoteNotificationStatus()","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/getRemoteNotificationStatus()","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"getRemoteNotificationStatus","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"NSMutableDictionary","preciseIdentifier":"c:objc(cs)NSMutableDictionary"},{"kind":"text","text":"!"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Type Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"getRemoteNotificationStatus","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"getRemoteNotificationStatus","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSMutableDictionary","text":"NSMutableDictionary"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"getRemoteNotificationStatus"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager\/title","value":"PushNotificationManager","op":"replace"},{"value":[{"kind":"identifier","text":"PushNotificationManager"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1getRemoteNotificationStatus()\/title","op":"replace","value":"getRemoteNotificationStatus"},{"value":[{"kind":"text","text":"+ "},{"text":"getRemoteNotificationStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1getRemoteNotificationStatus()\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}