{"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handlePushRegistrationFailure"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":")!)","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/handlePushRegistrationFailure(_:)"},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pushnotificationmanager\/handlepushregistrationfailure(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pushnotificationmanager\/handlepushregistrationfailure(_:)"]}],"metadata":{"externalID":"c:objc(cs)PushNotificationManager(im)handlePushRegistrationFailure:","symbolKind":"method","navigatorTitle":[{"text":"handlePushRegistrationFailure:","kind":"identifier"}],"modules":[{"name":"PushwooshFramework"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"handlePushRegistrationFailure"},{"text":"((any ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")!)"}],"role":"symbol","title":"handlePushRegistrationFailure(_:)","roleHeading":"Instance Method"},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager"]]},"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationManager":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushNotificationManager"}],"type":"topic","kind":"symbol","title":"PushNotificationManager","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager","url":"\/documentation\/pushwooshframework\/pushnotificationmanager","role":"symbol","abstract":[{"type":"codeVoice","code":"PushNotificationManager"},{"text":" class offers access to the singleton-instance of the push manager responsible for registering the device with the APS servers, receiving and processing push notifications.","type":"text"}],"navigatorTitle":[{"text":"PushNotificationManager","kind":"identifier"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"type":"topic","kind":"symbol","title":"PushwooshFramework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","url":"\/documentation\/pushwooshframework","role":"collection","abstract":[{"type":"text","text":"Push notification SDK for iOS applications."}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationManager/handlePushRegistrationFailure(_:)":{"navigatorTitle":[{"kind":"identifier","text":"handlePushRegistrationFailure:"}],"abstract":[],"url":"\/documentation\/pushwooshframework\/pushnotificationmanager\/handlepushregistrationfailure(_:)","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/handlePushRegistrationFailure(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"handlePushRegistrationFailure","kind":"identifier"},{"text":"((any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":")!)","kind":"text"}],"type":"topic","title":"handlePushRegistrationFailure(_:)","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"handlePushRegistrationFailure:","path":"\/metadata\/title","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"handlePushRegistrationFailure:"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"handlePushRegistrationFailure:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager\/title","value":"PushNotificationManager"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager\/fragments","op":"replace","value":[{"text":"PushNotificationManager","kind":"identifier"}]},{"value":"handlePushRegistrationFailure:","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1handlePushRegistrationFailure(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1handlePushRegistrationFailure(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"handlePushRegistrationFailure:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}