{"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager"]]},"metadata":{"modules":[{"name":"PushwooshFramework"}],"roleHeading":"Instance Method","title":"handlePushReceived(_:)","navigatorTitle":[{"text":"handlePushReceived:","kind":"identifier"}],"externalID":"c:objc(cs)PushNotificationManager(im)handlePushReceived:","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"handlePushReceived","kind":"identifier"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"]!) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"symbolKind":"method","role":"symbol"},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/handlePushReceived(_:)"},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"handlePushReceived","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"userInfo"},{"kind":"text","text":": ["},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]!) -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pushnotificationmanager\/handlepushreceived(_:)"]},{"paths":["\/documentation\/pushwooshframework\/pushnotificationmanager\/handlepushreceived(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationManager/handlePushReceived(_:)":{"role":"symbol","title":"handlePushReceived(_:)","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"handlePushReceived:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"handlePushReceived","kind":"identifier"},{"kind":"text","text":"(["},{"text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]!) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/handlePushReceived(_:)","abstract":[],"url":"\/documentation\/pushwooshframework\/pushnotificationmanager\/handlepushreceived(_:)"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","kind":"symbol","abstract":[],"title":"PushwooshFramework","url":"\/documentation\/pushwooshframework","type":"topic","role":"collection"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationManager":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PushNotificationManager"}],"abstract":[{"type":"codeVoice","code":"PushNotificationManager"},{"type":"text","text":" class offers access to the singleton-instance of the push manager responsible for registering the device with the APS servers, receiving and processing push notifications."}],"title":"PushNotificationManager","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PushNotificationManager","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager","url":"\/documentation\/pushwooshframework\/pushnotificationmanager"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"handlePushReceived:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"handlePushReceived:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"handlePushReceived:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSDictionary","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDictionary"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"userInfo"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1handlePushReceived(_:)\/title","value":"handlePushReceived:"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1handlePushReceived(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"handlePushReceived:"}]},{"value":"PushNotificationManager","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager\/fragments","value":[{"text":"PushNotificationManager","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}