{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pushnotificationmanager\/loadtags(_:error:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pushnotificationmanager\/loadtags(_:error:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"loadTags","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"successHandler"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:PushNotificationManager.h@T@PushwooshGetTagsHandler","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushwooshGetTagsHandler","text":"PushwooshGetTagsHandler"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"error"},{"kind":"text","text":" "},{"text":"errorHandler","kind":"internalParam"},{"kind":"text","text":": "},{"text":"PushwooshErrorHandler","kind":"typeIdentifier","preciseIdentifier":"c:PushNotificationManager.h@T@PushwooshErrorHandler","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushwooshErrorHandler"},{"text":"!)","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"name":"successHandler","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The block is executed on the successful completion of the request. This block has no return value and takes one argument: the dictionary representation of the recieved tags."},{"type":"text","text":" "},{"type":"text","text":"Example of the dictionary representation of the received tags:"},{"text":" ","type":"text"},{"type":"text","text":"{"},{"text":" ","type":"text"},{"text":"Country = ru;","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Language = ru;"},{"text":" ","type":"text"},{"type":"text","text":"}"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The block is executed on the unsuccessful completion of the request. This block has no return value and takes one argument: the error that occurred during the request."}]}],"name":"errorHandler"}],"kind":"parameters"}],"metadata":{"roleHeading":"Instance Method","title":"loadTags(_:error:)","role":"symbol","navigatorTitle":[{"text":"loadTags:error:","kind":"identifier"}],"externalID":"c:objc(cs)PushNotificationManager(im)loadTags:error:","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loadTags","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:PushNotificationManager.h@T@PushwooshGetTagsHandler","text":"PushwooshGetTagsHandler","kind":"typeIdentifier"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"error"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:PushNotificationManager.h@T@PushwooshErrorHandler","text":"PushwooshErrorHandler","kind":"typeIdentifier"},{"text":"!)","kind":"text"}],"modules":[{"name":"PushwooshFramework"}]},"abstract":[{"type":"text","text":"Get tags from server. Calls delegate method if exists and handler (block)."}],"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/loadTags(_:error:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager"]]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationManager/loadTags(_:error:)":{"title":"loadTags(_:error:)","url":"\/documentation\/pushwooshframework\/pushnotificationmanager\/loadtags(_:error:)","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/loadTags(_:error:)","type":"topic","abstract":[{"type":"text","text":"Get tags from server. Calls delegate method if exists and handler (block)."}],"navigatorTitle":[{"text":"loadTags:error:","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"loadTags"},{"text":"(","kind":"text"},{"text":"PushwooshGetTagsHandler","preciseIdentifier":"c:PushNotificationManager.h@T@PushwooshGetTagsHandler","kind":"typeIdentifier"},{"text":"!, ","kind":"text"},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:PushNotificationManager.h@T@PushwooshErrorHandler","text":"PushwooshErrorHandler","kind":"typeIdentifier"},{"kind":"text","text":"!)"}],"role":"symbol"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushwooshErrorHandler":{"title":"PushwooshErrorHandler","abstract":[{"text":"Completion handler called when an operation fails.","type":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushwooshErrorHandler","url":"\/documentation\/pushwooshframework\/pushwoosherrorhandler","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushwooshErrorHandler"}],"kind":"symbol","navigatorTitle":[{"text":"PushwooshErrorHandler","kind":"identifier"}],"type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushwooshGetTagsHandler":{"title":"PushwooshGetTagsHandler","abstract":[{"type":"text","text":"Completion handler called when tags are successfully retrieved from the server."}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushwooshGetTagsHandler","url":"\/documentation\/pushwooshframework\/pushwooshgettagshandler","role":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"PushwooshGetTagsHandler","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"PushwooshGetTagsHandler","kind":"identifier"}],"type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationManager":{"title":"PushNotificationManager","url":"\/documentation\/pushwooshframework\/pushnotificationmanager","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager","type":"topic","abstract":[{"type":"codeVoice","code":"PushNotificationManager"},{"type":"text","text":" class offers access to the singleton-instance of the push manager responsible for registering the device with the APS servers, receiving and processing push notifications."}],"navigatorTitle":[{"kind":"identifier","text":"PushNotificationManager"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PushNotificationManager","kind":"identifier"}],"role":"symbol"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"kind":"symbol","url":"\/documentation\/pushwooshframework","abstract":[{"type":"text","text":"Push notification SDK for iOS applications."}],"role":"collection","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","title":"PushwooshFramework","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"loadTags:error:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"loadTags:error:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"text":"loadTags:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:PushNotificationManager.h@T@PushwooshGetTagsHandler","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushwooshGetTagsHandler","text":"PushwooshGetTagsHandler"},{"text":") ","kind":"text"},{"text":"successHandler","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"text":"PushwooshErrorHandler","kind":"typeIdentifier","preciseIdentifier":"c:PushNotificationManager.h@T@PushwooshErrorHandler","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushwooshErrorHandler"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"errorHandler"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1loadTags(_:error:)\/title","op":"replace","value":"loadTags:error:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"loadTags:error:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1loadTags(_:error:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushwooshErrorHandler\/title","value":"PushwooshErrorHandler"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushwooshErrorHandler\/fragments","value":[{"kind":"identifier","text":"PushwooshErrorHandler"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushwooshGetTagsHandler\/title","value":"PushwooshGetTagsHandler"},{"value":[{"kind":"identifier","text":"PushwooshGetTagsHandler"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushwooshGetTagsHandler\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager\/title","value":"PushNotificationManager","op":"replace"},{"value":[{"text":"PushNotificationManager","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}