{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mergeUserId"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"oldUserId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"!, ","kind":"text"},{"text":"to","kind":"externalParam"},{"kind":"text","text":" "},{"text":"newUserId","kind":"internalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"doMerge"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (((any ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":")?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")!)","kind":"text"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"source user","type":"text"}],"type":"paragraph"}],"name":"oldUserId"},{"name":"newUserId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"destination user"}]}]},{"name":"doMerge","content":[{"inlineContent":[{"type":"text","text":"if false all events for oldUserId are removed, if true all events for oldUserId are moved to newUserId"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"callback"}]}],"name":"completion"}]},{"content":[{"anchor":"discussion","type":"heading","level":2,"text":"Discussion"},{"inlineContent":[{"type":"text","text":"Deprecated. Use PWInAppManager mergeUserId method instead"}],"type":"paragraph"}],"kind":"content"}],"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/mergeUserId(_:to:doMerge:completion:)","interfaceLanguage":"swift"},"metadata":{"symbolKind":"method","roleHeading":"Instance Method","externalID":"c:objc(cs)PushNotificationManager(im)mergeUserId:to:doMerge:completion:","navigatorTitle":[{"text":"mergeUserId:to:doMerge:completion:","kind":"identifier"}],"title":"mergeUserId(_:to:doMerge:completion:)","modules":[{"name":"PushwooshFramework"}],"platforms":[],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"mergeUserId","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"!, ","kind":"text"},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"doMerge"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (((any "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"text":")?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")!)"}],"role":"symbol"},"abstract":[{"text":"Move all events from oldUserId to newUserId if doMerge is true. If doMerge is false all events for oldUserId are removed.","type":"text"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/pushwooshframework\/pushnotificationmanager\/mergeuserid(_:to:domerge:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pushwooshframework\/pushnotificationmanager\/mergeuserid(_:to:domerge:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager"]]},"sections":[],"kind":"symbol","references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationManager/mergeUserId(_:to:doMerge:completion:)":{"url":"\/documentation\/pushwooshframework\/pushnotificationmanager\/mergeuserid(_:to:domerge:completion:)","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/mergeUserId(_:to:doMerge:completion:)","type":"topic","navigatorTitle":[{"text":"mergeUserId:to:doMerge:completion:","kind":"identifier"}],"title":"mergeUserId(_:to:doMerge:completion:)","abstract":[{"type":"text","text":"Move all events from oldUserId to newUserId if doMerge is true. If doMerge is false all events for oldUserId are removed."}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mergeUserId"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"!, ","kind":"text"},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"!, ","kind":"text"},{"text":"doMerge","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"text":": (((any ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":")?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")!)"}],"deprecated":true,"role":"symbol","kind":"symbol"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","url":"\/documentation\/pushwooshframework","title":"PushwooshFramework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","type":"topic","abstract":[{"type":"text","text":"Push notification SDK for iOS applications."}],"kind":"symbol"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationManager":{"role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager","navigatorTitle":[{"kind":"identifier","text":"PushNotificationManager"}],"kind":"symbol","abstract":[{"code":"PushNotificationManager","type":"codeVoice"},{"text":" class offers access to the singleton-instance of the push manager responsible for registering the device with the APS servers, receiving and processing push notifications.","type":"text"}],"type":"topic","url":"\/documentation\/pushwooshframework\/pushnotificationmanager","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PushNotificationManager","kind":"identifier"}],"title":"PushNotificationManager"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"mergeUserId:to:doMerge:completion:","path":"\/metadata\/title","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mergeUserId:to:doMerge:completion:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"mergeUserId:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"oldUserId","kind":"internalParam"},{"kind":"text","text":" "},{"text":"to:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"newUserId","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"doMerge:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":") ","kind":"text"},{"text":"doMerge","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"completion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":" (^"},{"text":")(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"kind":"text","text":" * "},{"text":"error","kind":"internalParam"},{"kind":"text","text":")) "},{"text":"completion","kind":"internalParam"},{"kind":"text","text":";"}]}]}},{"value":"mergeUserId:to:doMerge:completion:","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1mergeUserId(_:to:doMerge:completion:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"mergeUserId:to:doMerge:completion:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1mergeUserId(_:to:doMerge:completion:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager\/title","value":"PushNotificationManager"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager\/fragments","value":[{"text":"PushNotificationManager","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}