{"abstract":[{"type":"text","text":"Returns UNUserNotificationCenterDelegate that handles foreground push notifications on iOS10"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/notificationCenterDelegate"},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"notificationCenterDelegate","kind":"identifier"},{"kind":"text","text":": (any "},{"text":"UNUserNotificationCenterDelegate","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UNUserNotificationCenterDelegate"},{"text":")! { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager"]]},"kind":"symbol","metadata":{"title":"notificationCenterDelegate","symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"PushwooshFramework"}],"externalID":"c:objc(cs)PushNotificationManager(py)notificationCenterDelegate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"notificationCenterDelegate"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"notificationCenterDelegate","kind":"identifier"},{"text":": (any ","kind":"text"},{"text":"UNUserNotificationCenterDelegate","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UNUserNotificationCenterDelegate"},{"text":")!","kind":"text"}]},"sections":[],"variants":[{"paths":["\/documentation\/pushwooshframework\/pushnotificationmanager\/notificationcenterdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pushnotificationmanager\/notificationcenterdelegate"]}],"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationManager/notificationCenterDelegate":{"kind":"symbol","url":"\/documentation\/pushwooshframework\/pushnotificationmanager\/notificationcenterdelegate","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/notificationCenterDelegate","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"notificationCenterDelegate"},{"text":": (any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UNUserNotificationCenterDelegate","text":"UNUserNotificationCenterDelegate"},{"text":")!","kind":"text"}],"navigatorTitle":[{"text":"notificationCenterDelegate","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Returns UNUserNotificationCenterDelegate that handles foreground push notifications on iOS10","type":"text"}],"title":"notificationCenterDelegate","type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationManager":{"abstract":[{"code":"PushNotificationManager","type":"codeVoice"},{"text":" class offers access to the singleton-instance of the push manager responsible for registering the device with the APS servers, receiving and processing push notifications.","type":"text"}],"kind":"symbol","url":"\/documentation\/pushwooshframework\/pushnotificationmanager","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager","navigatorTitle":[{"text":"PushNotificationManager","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PushNotificationManager","kind":"identifier"}],"type":"topic","role":"symbol","title":"PushNotificationManager"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"abstract":[],"kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","url":"\/documentation\/pushwooshframework","type":"topic","role":"collection","title":"PushwooshFramework"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","value":"notificationCenterDelegate","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"notificationCenterDelegate"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"id<UNUserNotificationCenterDelegate>","kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)UNUserNotificationCenterDelegate"},{"kind":"text","text":" "},{"text":"notificationCenterDelegate","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1notificationCenterDelegate\/title","value":"notificationCenterDelegate"},{"value":[{"kind":"identifier","text":"notificationCenterDelegate"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1notificationCenterDelegate\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager\/title","value":"PushNotificationManager","op":"replace"},{"value":[{"text":"PushNotificationManager","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager\/fragments"}]}]}