{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"push"},{"kind":"text","text":"() -> "},{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager","text":"PushNotificationManager","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PushNotificationManager"},{"text":"!","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","text":"Return Value","anchor":"return-value","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"A singleton object that represents the push manager."}]}]}],"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/push()","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pushnotificationmanager\/push()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pushnotificationmanager\/push()"]}],"metadata":{"roleHeading":"Type Method","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"push","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)PushNotificationManager","kind":"typeIdentifier","text":"PushNotificationManager"},{"kind":"text","text":"!"}],"title":"push()","externalID":"c:objc(cs)PushNotificationManager(cm)pushManager","modules":[{"name":"PushwooshFramework"}],"symbolKind":"method","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"pushManager"}]},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager"]]},"kind":"symbol","abstract":[{"text":"Returns an object representing the current push manager.","type":"text"}],"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationManager/push()":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"push","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"PushNotificationManager","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PushNotificationManager"},{"text":"!","kind":"text"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/push()","title":"push()","role":"symbol","type":"topic","navigatorTitle":[{"text":"pushManager","kind":"identifier"}],"abstract":[{"text":"Returns an object representing the current push manager.","type":"text"}],"url":"\/documentation\/pushwooshframework\/pushnotificationmanager\/push()"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"url":"\/documentation\/pushwooshframework","role":"collection","title":"PushwooshFramework","kind":"symbol","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","abstract":[{"text":"Push notification SDK for iOS applications.","type":"text"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationManager":{"kind":"symbol","navigatorTitle":[{"text":"PushNotificationManager","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager","url":"\/documentation\/pushwooshframework\/pushnotificationmanager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PushNotificationManager","kind":"identifier"}],"abstract":[{"code":"PushNotificationManager","type":"codeVoice"},{"type":"text","text":" class offers access to the singleton-instance of the push manager responsible for registering the device with the APS servers, receiving and processing push notifications."}],"type":"topic","title":"PushNotificationManager","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"value":"pushManager","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"text":"+ ","kind":"text"},{"text":"pushManager","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager","preciseIdentifier":"c:objc(cs)PushNotificationManager","text":"PushNotificationManager"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"pushManager"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"value":"pushManager","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1push()\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1push()\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"text":"pushManager","kind":"identifier"}]},{"op":"replace","value":"PushNotificationManager","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager\/title"},{"op":"replace","value":[{"text":"PushNotificationManager","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager\/fragments"}]}]}