{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/sendPurchase(_:withPrice:currencyCode:andDate:)"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendPurchase"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"productIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"!, ","kind":"text"},{"text":"withPrice","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"price"},{"text":": ","kind":"text"},{"text":"NSDecimalNumber","preciseIdentifier":"c:objc(cs)NSDecimalNumber","kind":"typeIdentifier"},{"kind":"text","text":"!, "},{"text":"currencyCode","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"!, "},{"text":"andDate","kind":"externalParam"},{"kind":"text","text":" "},{"text":"date","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"},{"kind":"text","text":"!)"}]}],"kind":"declarations"},{"parameters":[{"name":"productIdentifier","content":[{"inlineContent":[{"text":"purchased product ID","type":"text"}],"type":"paragraph"}]},{"name":"price","content":[{"inlineContent":[{"type":"text","text":"price for the product"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"currency of the price (ex: @“USD”)"}],"type":"paragraph"}],"name":"currencyCode"},{"name":"date","content":[{"inlineContent":[{"text":"time of the purchase (ex: [NSDate now])","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"}],"abstract":[{"type":"text","text":"Tracks individual in-app purchase. See recommended "},{"type":"codeVoice","code":"sendSKPaymentTransactions:"},{"type":"text","text":" method."}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pushnotificationmanager\/sendpurchase(_:withprice:currencycode:anddate:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pushnotificationmanager\/sendpurchase(_:withprice:currencycode:anddate:)"]}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"roleHeading":"Instance Method","modules":[{"name":"PushwooshFramework"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sendPurchase"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"text":"withPrice","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSDecimalNumber","kind":"typeIdentifier","text":"NSDecimalNumber"},{"text":"!, ","kind":"text"},{"kind":"externalParam","text":"currencyCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"text":"andDate","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"},{"text":"!)","kind":"text"}],"title":"sendPurchase(_:withPrice:currencyCode:andDate:)","externalID":"c:objc(cs)PushNotificationManager(im)sendPurchase:withPrice:currencyCode:andDate:","symbolKind":"method","navigatorTitle":[{"text":"sendPurchase:withPrice:currencyCode:andDate:","kind":"identifier"}]},"kind":"symbol","references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationManager/sendPurchase(_:withPrice:currencyCode:andDate:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sendPurchase"},{"kind":"text","text":"("},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"!, "},{"text":"withPrice","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSDecimalNumber","preciseIdentifier":"c:objc(cs)NSDecimalNumber","kind":"typeIdentifier"},{"kind":"text","text":"!, "},{"text":"currencyCode","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"!, "},{"text":"andDate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Date","preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier"},{"text":"!)","kind":"text"}],"type":"topic","abstract":[{"text":"Tracks individual in-app purchase. See recommended ","type":"text"},{"type":"codeVoice","code":"sendSKPaymentTransactions:"},{"type":"text","text":" method."}],"kind":"symbol","title":"sendPurchase(_:withPrice:currencyCode:andDate:)","navigatorTitle":[{"text":"sendPurchase:withPrice:currencyCode:andDate:","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/sendPurchase(_:withPrice:currencyCode:andDate:)","role":"symbol","url":"\/documentation\/pushwooshframework\/pushnotificationmanager\/sendpurchase(_:withprice:currencycode:anddate:)"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"kind":"symbol","url":"\/documentation\/pushwooshframework","abstract":[{"type":"text","text":"Push notification SDK for iOS applications."}],"role":"collection","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","title":"PushwooshFramework","type":"topic"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationManager":{"title":"PushNotificationManager","url":"\/documentation\/pushwooshframework\/pushnotificationmanager","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager","type":"topic","abstract":[{"type":"codeVoice","code":"PushNotificationManager"},{"type":"text","text":" class offers access to the singleton-instance of the push manager responsible for registering the device with the APS servers, receiving and processing push notifications."}],"navigatorTitle":[{"kind":"identifier","text":"PushNotificationManager"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PushNotificationManager","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"sendPurchase:withPrice:currencyCode:andDate:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"text":"sendPurchase:withPrice:currencyCode:andDate:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"sendPurchase:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"productIdentifier"},{"kind":"text","text":" "},{"text":"withPrice:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDecimalNumber","text":"NSDecimalNumber"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"price"},{"text":" ","kind":"text"},{"text":"currencyCode:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"text":"currencyCode","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"andDate:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSDate","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDate"},{"kind":"text","text":" *) "},{"text":"date","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace"},{"value":"sendPurchase:withPrice:currencyCode:andDate:","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1sendPurchase(_:withPrice:currencyCode:andDate:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1sendPurchase(_:withPrice:currencyCode:andDate:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"sendPurchase:withPrice:currencyCode:andDate:"}],"op":"replace"},{"op":"replace","value":"PushNotificationManager","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager\/title"},{"value":[{"text":"PushNotificationManager","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}