{"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"metadata":{"role":"symbol","roleHeading":"Instance Method","title":"sendAppOpen()","symbolKind":"method","externalID":"c:objc(cs)PushNotificationManager(im)sendAppOpen","navigatorTitle":[{"kind":"identifier","text":"sendAppOpen"}],"modules":[{"name":"PushwooshFramework"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sendAppOpen"},{"text":"()","kind":"text"}]},"variants":[{"paths":["\/documentation\/pushwooshframework\/pushnotificationmanager\/sendappopen()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pushwooshframework\/pushnotificationmanager\/sendappopen()"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sendAppOpen","kind":"identifier"},{"text":"()","kind":"text"}]}],"kind":"declarations"}],"abstract":[{"text":"Informs the Pushwoosh about the app being launched. Usually called internally by SDK Runtime.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/sendAppOpen()"},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager"]]},"kind":"symbol","references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","kind":"symbol","type":"topic","url":"\/documentation\/pushwooshframework","role":"collection","title":"PushwooshFramework","abstract":[{"text":"Push notification SDK for iOS applications.","type":"text"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationManager":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PushNotificationManager"}],"type":"topic","url":"\/documentation\/pushwooshframework\/pushnotificationmanager","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PushNotificationManager"}],"title":"PushNotificationManager","abstract":[{"type":"codeVoice","code":"PushNotificationManager"},{"type":"text","text":" class offers access to the singleton-instance of the push manager responsible for registering the device with the APS servers, receiving and processing push notifications."}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationManager/sendAppOpen()":{"abstract":[{"type":"text","text":"Informs the Pushwoosh about the app being launched. Usually called internally by SDK Runtime."}],"role":"symbol","type":"topic","title":"sendAppOpen()","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/sendAppOpen()","navigatorTitle":[{"kind":"identifier","text":"sendAppOpen"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sendAppOpen","kind":"identifier"},{"text":"()","kind":"text"}],"url":"\/documentation\/pushwooshframework\/pushnotificationmanager\/sendappopen()"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"sendAppOpen"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"text":"sendAppOpen","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"sendAppOpen"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"PushNotificationManager","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager\/title"},{"op":"replace","value":[{"text":"PushNotificationManager","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1sendAppOpen()\/title","value":"sendAppOpen"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1sendAppOpen()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"sendAppOpen","kind":"identifier"}],"op":"replace"}]}]}