{"sections":[],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"externalID":"c:objc(cs)PushNotificationManager(im)sendSKPaymentTransactions:","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"sendSKPaymentTransactions","kind":"identifier"},{"kind":"text","text":"(["},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]!)"}],"symbolKind":"method","title":"sendSKPaymentTransactions(_:)","modules":[{"name":"PushwooshFramework"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"sendSKPaymentTransactions:"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/sendSKPaymentTransactions(_:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pushnotificationmanager\/sendskpaymenttransactions(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pushnotificationmanager\/sendskpaymenttransactions(_:)"]}],"abstract":[{"text":"Sends in-app purchases to Pushwoosh. Use in paymentQueue:updatedTransactions: payment queue method (see example).","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sendSKPaymentTransactions"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"transactions","kind":"internalParam"},{"kind":"text","text":": ["},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]!)"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"transactions","content":[{"type":"paragraph","inlineContent":[{"text":"Array of SKPaymentTransaction items as received in the payment queue.","type":"text"}]}]}]},{"content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"inlineContent":[{"type":"text","text":"Example:"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"(void)paymentQueue:(SKPaymentQueue *)queue updatedTransactions:(NSArray *)transactions {","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"[[PushNotificationManager pushManager] sendSKPaymentTransactions:transactions];"},{"type":"text","text":" "},{"text":"}","type":"text"}]}]}]}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager"]]},"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationManager":{"url":"\/documentation\/pushwooshframework\/pushnotificationmanager","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PushNotificationManager"}],"title":"PushNotificationManager","role":"symbol","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager","abstract":[{"code":"PushNotificationManager","type":"codeVoice"},{"type":"text","text":" class offers access to the singleton-instance of the push manager responsible for registering the device with the APS servers, receiving and processing push notifications."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PushNotificationManager"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"abstract":[],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","kind":"symbol","url":"\/documentation\/pushwooshframework","title":"PushwooshFramework","type":"topic","role":"collection"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationManager/sendSKPaymentTransactions(_:)":{"navigatorTitle":[{"kind":"identifier","text":"sendSKPaymentTransactions:"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/sendSKPaymentTransactions(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"sendSKPaymentTransactions","kind":"identifier"},{"kind":"text","text":"(["},{"kind":"keyword","text":"Any"},{"text":"]!)","kind":"text"}],"type":"topic","title":"sendSKPaymentTransactions(_:)","url":"\/documentation\/pushwooshframework\/pushnotificationmanager\/sendskpaymenttransactions(_:)","abstract":[{"type":"text","text":"Sends in-app purchases to Pushwoosh. Use in paymentQueue:updatedTransactions: payment queue method (see example)."}],"role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"sendSKPaymentTransactions:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"text":"sendSKPaymentTransactions:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"sendSKPaymentTransactions:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSArray","text":"NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"transactions"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"PushNotificationManager","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager\/fragments","value":[{"kind":"identifier","text":"PushNotificationManager"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1sendSKPaymentTransactions(_:)\/title","value":"sendSKPaymentTransactions:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"sendSKPaymentTransactions:"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1sendSKPaymentTransactions(_:)\/fragments","op":"replace"}]}]}