{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pushnotificationmanager\/startlocationtracking()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pushnotificationmanager\/startlocationtracking()"]}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"startLocationTracking"},{"kind":"text","text":"()"}],"languages":["swift"]}],"kind":"declarations"},{"content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Deprecated. Use PushwooshGeozones framework."}]}],"kind":"content"}],"deprecationSummary":[{"inlineContent":[{"type":"text","text":"Use PushwooshGeozones framework"}],"type":"paragraph"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/startLocationTracking()"},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"Start location tracking."}],"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"startLocationTracking"},{"text":"()","kind":"text"}],"roleHeading":"Instance Method","platforms":[],"symbolKind":"method","modules":[{"name":"PushwooshFramework"}],"title":"startLocationTracking()","navigatorTitle":[{"text":"startLocationTracking","kind":"identifier"}],"externalID":"c:objc(cs)PushNotificationManager(im)startLocationTracking","role":"symbol"},"sections":[],"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationManager/startLocationTracking()":{"title":"startLocationTracking()","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startLocationTracking"}],"kind":"symbol","abstract":[{"type":"text","text":"Start location tracking."}],"role":"symbol","url":"\/documentation\/pushwooshframework\/pushnotificationmanager\/startlocationtracking()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"startLocationTracking","kind":"identifier"},{"kind":"text","text":"()"}],"deprecated":true,"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/startLocationTracking()"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","url":"\/documentation\/pushwooshframework","title":"PushwooshFramework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","type":"topic","abstract":[{"type":"text","text":"Push notification SDK for iOS applications."}],"kind":"symbol"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationManager":{"role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager","navigatorTitle":[{"kind":"identifier","text":"PushNotificationManager"}],"kind":"symbol","abstract":[{"code":"PushNotificationManager","type":"codeVoice"},{"text":" class offers access to the singleton-instance of the push manager responsible for registering the device with the APS servers, receiving and processing push notifications.","type":"text"}],"type":"topic","url":"\/documentation\/pushwooshframework\/pushnotificationmanager","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PushNotificationManager","kind":"identifier"}],"title":"PushNotificationManager"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"startLocationTracking","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startLocationTracking"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"startLocationTracking","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","value":"startLocationTracking","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1startLocationTracking()\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startLocationTracking"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1startLocationTracking()\/fragments","op":"replace"},{"value":"PushNotificationManager","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager\/fragments","op":"replace","value":[{"text":"PushNotificationManager","kind":"identifier"}]}]}]}