{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unregisterForPushNotifications"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (((any ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")!)","kind":"text"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pushnotificationmanager\/unregisterforpushnotifications(completion:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pushnotificationmanager\/unregisterforpushnotifications(completion:)"]}],"metadata":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"unregisterForPushNotifications"},{"kind":"text","text":"("},{"text":"completion","kind":"externalParam"},{"text":": (((any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")!)"}],"navigatorTitle":[{"text":"unregisterForPushNotificationsWithCompletion:","kind":"identifier"}],"symbolKind":"method","title":"unregisterForPushNotifications(completion:)","roleHeading":"Instance Method","modules":[{"name":"PushwooshFramework"}],"externalID":"c:objc(cs)PushNotificationManager(im)unregisterForPushNotificationsWithCompletion:"},"abstract":[{"type":"text","text":"Unregisters from push notifications."}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/unregisterForPushNotifications(completion:)"},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationManager":{"navigatorTitle":[{"text":"PushNotificationManager","kind":"identifier"}],"title":"PushNotificationManager","role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PushNotificationManager","kind":"identifier"}],"url":"\/documentation\/pushwooshframework\/pushnotificationmanager","abstract":[{"code":"PushNotificationManager","type":"codeVoice"},{"text":" class offers access to the singleton-instance of the push manager responsible for registering the device with the APS servers, receiving and processing push notifications.","type":"text"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","abstract":[{"text":"Push notification SDK for iOS applications.","type":"text"}],"url":"\/documentation\/pushwooshframework","role":"collection","title":"PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationManager/unregisterForPushNotifications(completion:)":{"url":"\/documentation\/pushwooshframework\/pushnotificationmanager\/unregisterforpushnotifications(completion:)","title":"unregisterForPushNotifications(completion:)","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/unregisterForPushNotifications(completion:)","navigatorTitle":[{"kind":"identifier","text":"unregisterForPushNotificationsWithCompletion:"}],"abstract":[{"text":"Unregisters from push notifications.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unregisterForPushNotifications"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (((any ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":")?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")!)"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"unregisterForPushNotificationsWithCompletion:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"unregisterForPushNotificationsWithCompletion:","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"unregisterForPushNotificationsWithCompletion:","kind":"identifier"},{"kind":"text","text":"("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":" (^","kind":"text"},{"text":")(","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":" * ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":")) ","kind":"text"},{"text":"completion","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager\/title","value":"PushNotificationManager","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager\/fragments","value":[{"kind":"identifier","text":"PushNotificationManager"}]},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1unregisterForPushNotifications(completion:)\/title","value":"unregisterForPushNotificationsWithCompletion:","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1unregisterForPushNotifications(completion:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"unregisterForPushNotificationsWithCompletion:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}