{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pushnotificationmanager\/unregisterforpushnotifications()"]},{"paths":["\/documentation\/pushwooshframework\/pushnotificationmanager\/unregisterforpushnotifications()"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"unregisterForPushNotifications","kind":"identifier"},{"text":"()","kind":"text"}],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager"]]},"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/unregisterForPushNotifications()","interfaceLanguage":"swift"},"metadata":{"role":"symbol","modules":[{"name":"PushwooshFramework"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unregisterForPushNotifications"},{"text":"()","kind":"text"}],"externalID":"c:objc(cs)PushNotificationManager(im)unregisterForPushNotifications","title":"unregisterForPushNotifications()","platforms":[],"roleHeading":"Instance Method","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"unregisterForPushNotifications"}]},"kind":"symbol","abstract":[{"type":"text","text":"Deprecated. Use unregisterForPushNotificationsWithCompletion: method instead"}],"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationManager":{"navigatorTitle":[{"text":"PushNotificationManager","kind":"identifier"}],"url":"\/documentation\/pushwooshframework\/pushnotificationmanager","type":"topic","abstract":[{"code":"PushNotificationManager","type":"codeVoice"},{"type":"text","text":" class offers access to the singleton-instance of the push manager responsible for registering the device with the APS servers, receiving and processing push notifications."}],"title":"PushNotificationManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushNotificationManager"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushNotificationManager/unregisterForPushNotifications()":{"role":"symbol","url":"\/documentation\/pushwooshframework\/pushnotificationmanager\/unregisterforpushnotifications()","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unregisterForPushNotifications"},{"text":"()","kind":"text"}],"title":"unregisterForPushNotifications()","navigatorTitle":[{"kind":"identifier","text":"unregisterForPushNotifications"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushNotificationManager\/unregisterForPushNotifications()","abstract":[{"type":"text","text":"Deprecated. Use unregisterForPushNotificationsWithCompletion: method instead"}],"kind":"symbol","deprecated":true},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"url":"\/documentation\/pushwooshframework","type":"topic","abstract":[{"text":"Push notification SDK for iOS applications.","type":"text"}],"title":"PushwooshFramework","kind":"symbol","role":"collection","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"unregisterForPushNotifications","op":"replace","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"unregisterForPushNotifications"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"unregisterForPushNotifications"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager\/title","value":"PushNotificationManager","op":"replace"},{"value":[{"text":"PushNotificationManager","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager\/fragments","op":"replace"},{"value":"unregisterForPushNotifications","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1unregisterForPushNotifications()\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushNotificationManager~1unregisterForPushNotifications()\/fragments","value":[{"kind":"text","text":"- "},{"text":"unregisterForPushNotifications","kind":"identifier"}]}]}]}