{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshvoip\/pwvoipmessage"]},{"paths":["\/documentation\/pushwooshvoip\/pwvoipmessage"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPMessage","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"symbolKind":"class","navigatorTitle":[{"text":"PWVoIPMessage","kind":"identifier"}],"roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PWVoIPMessage","kind":"identifier"}],"modules":[{"name":"PushwooshVoIP"}],"role":"symbol","title":"PWVoIPMessage","externalID":"c:@M@PushwooshVoIP@objc(cs)PWVoIPMessage"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP"]]},"abstract":[{"type":"text","text":"An encapsulation of VoIP push notification payload data."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PWVoIPMessage"}],"languages":["swift"]}]}],"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.pushwoosh.PushwooshVoIP\/objc(cs)NSObject"]},{"identifiers":["doc:\/\/com.pushwoosh.PushwooshVoIP\/objc(pl)NSObject","doc:\/\/com.pushwoosh.PushwooshVoIP\/s7CVarArgP","doc:\/\/com.pushwoosh.PushwooshVoIP\/s28CustomDebugStringConvertibleP","doc:\/\/com.pushwoosh.PushwooshVoIP\/s23CustomStringConvertibleP","doc:\/\/com.pushwoosh.PushwooshVoIP\/SQ","doc:\/\/com.pushwoosh.PushwooshVoIP\/SH"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"topicSections":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPMessage\/init(rawPayload:)"],"title":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPMessage\/callerName","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPMessage\/handleType","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPMessage\/hasVideo","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPMessage\/rawPayload","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPMessage\/supportsDTMF","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPMessage\/supportsHolding","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPMessage\/uuid"]}],"references":{"doc://com.pushwoosh.PushwooshVoIP/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/objc(pl)NSObject"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPMessage/callerName":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"callerName"}],"abstract":[{"type":"text","text":"The caller’s display name or identifier."}],"kind":"symbol","role":"symbol","url":"\/documentation\/pushwooshvoip\/pwvoipmessage\/callername","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPMessage\/callerName","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"callerName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"title":"callerName"},"doc://com.pushwoosh.PushwooshVoIP/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/s23CustomStringConvertibleP"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPMessage/rawPayload":{"url":"\/documentation\/pushwooshvoip\/pwvoipmessage\/rawpayload","abstract":[{"type":"text","text":"The raw push notification payload."}],"kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPMessage\/rawPayload","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"rawPayload","kind":"identifier"},{"kind":"text","text":": ["},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"text":"]","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"rawPayload"}],"title":"rawPayload"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP":{"title":"PushwooshVoIP","kind":"symbol","type":"topic","url":"\/documentation\/pushwooshvoip","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP","abstract":[{"type":"text","text":"VoIP push notifications with native call UI for iOS applications."}],"role":"collection"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPMessage/uuid":{"url":"\/documentation\/pushwooshvoip\/pwvoipmessage\/uuid","abstract":[{"type":"text","text":"The unique identifier for the call."}],"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPMessage\/uuid","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"uuid"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"uuid","kind":"identifier"}],"title":"uuid"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPMessage/supportsDTMF":{"url":"\/documentation\/pushwooshvoip\/pwvoipmessage\/supportsdtmf","abstract":[{"type":"text","text":"A Boolean value that indicates whether the call supports DTMF tones."}],"kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPMessage\/supportsDTMF","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"supportsDTMF"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"kind":"identifier","text":"supportsDTMF"}],"title":"supportsDTMF"},"doc://com.pushwoosh.PushwooshVoIP/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/s28CustomDebugStringConvertibleP"},"doc://com.pushwoosh.PushwooshVoIP/SH":{"identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPMessage":{"type":"topic","navigatorTitle":[{"text":"PWVoIPMessage","kind":"identifier"}],"abstract":[{"text":"An encapsulation of VoIP push notification payload data.","type":"text"}],"kind":"symbol","role":"symbol","url":"\/documentation\/pushwooshvoip\/pwvoipmessage","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPMessage","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PWVoIPMessage","kind":"identifier"}],"title":"PWVoIPMessage"},"doc://com.pushwoosh.PushwooshVoIP/objc(cs)NSObject":{"identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.pushwoosh.PushwooshVoIP/s7CVarArgP":{"identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPMessage/handleType":{"type":"topic","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"handleType"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"PWVoIPHandleType","preciseIdentifier":"c:@M@PushwooshVoIP@E@PWVoIPHandleType"}],"kind":"symbol","navigatorTitle":[{"text":"handleType","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPMessage\/handleType","abstract":[{"type":"text","text":"The display format for caller information."}],"url":"\/documentation\/pushwooshvoip\/pwvoipmessage\/handletype","title":"handleType","role":"symbol"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPMessage/hasVideo":{"title":"hasVideo","abstract":[{"type":"text","text":"A Boolean value that indicates whether the call supports video."}],"type":"topic","url":"\/documentation\/pushwooshvoip\/pwvoipmessage\/hasvideo","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"hasVideo"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPMessage\/hasVideo","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"hasVideo"}]},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPMessage/supportsHolding":{"title":"supportsHolding","type":"topic","url":"\/documentation\/pushwooshvoip\/pwvoipmessage\/supportsholding","abstract":[{"type":"text","text":"A Boolean value that indicates whether the call supports hold functionality."}],"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"supportsHolding"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPMessage\/supportsHolding","kind":"symbol","navigatorTitle":[{"text":"supportsHolding","kind":"identifier"}]},"doc://com.pushwoosh.PushwooshVoIP/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/SQ","title":"Swift.Equatable"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPMessage/init(rawPayload:)":{"title":"init(rawPayload:)","url":"\/documentation\/pushwooshvoip\/pwvoipmessage\/init(rawpayload:)","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Creates a VoIP message from push notification payload."}],"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"rawPayload"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"kind":"text","text":"])"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPMessage\/init(rawPayload:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"PWVoIPMessage","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"value":[{"text":"PWVoIPMessage","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"PWVoIPMessage"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPMessage\/callerName","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPMessage\/handleType","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPMessage\/hasVideo","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPMessage\/rawPayload","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPMessage\/supportsDTMF","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPMessage\/supportsHolding","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPMessage\/uuid"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.pushwoosh.PushwooshVoIP\/objc(cs)NSObject"]}]},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"PWVoIPMessage","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPMessage~1callerName\/title","value":"callerName"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPMessage~1callerName\/fragments","value":[{"text":"callerName","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPMessage~1rawPayload\/title","value":"rawPayload"},{"value":[{"text":"rawPayload","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPMessage~1rawPayload\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPMessage~1uuid\/title","value":"uuid"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPMessage~1uuid\/fragments","op":"replace","value":[{"kind":"identifier","text":"uuid"}]},{"value":"supportsDTMF","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPMessage~1supportsDTMF\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPMessage~1supportsDTMF\/fragments","op":"replace","value":[{"text":"supportsDTMF","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPMessage\/title","value":"PWVoIPMessage"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPMessage\/fragments","value":[{"kind":"identifier","text":"PWVoIPMessage"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPMessage~1handleType\/title","value":"handleType"},{"op":"replace","value":[{"text":"handleType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPMessage~1handleType\/fragments"},{"value":"hasVideo","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPMessage~1hasVideo\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPMessage~1hasVideo\/fragments","op":"replace","value":[{"kind":"identifier","text":"hasVideo"}]},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPMessage~1supportsHolding\/title","value":"supportsHolding","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPMessage~1supportsHolding\/fragments","value":[{"kind":"identifier","text":"supportsHolding"}]}]}]}