{"topicSections":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPHandleType\/email","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPHandleType\/generic","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPHandleType\/phoneNumber"],"title":"Enumeration Cases"},{"title":"Initializers","identifiers":["doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPHandleType\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPHandleType\/Equatable-Implementations","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPHandleType\/RawRepresentable-Implementations"],"generated":true}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PWVoIPHandleType","kind":"identifier"}]}],"kind":"declarations"}],"abstract":[{"text":"Display format for caller information in CallKit UI.","type":"text"}],"relationshipsSections":[{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/com.pushwoosh.PushwooshVoIP\/SQ","doc:\/\/com.pushwoosh.PushwooshVoIP\/SH","doc:\/\/com.pushwoosh.PushwooshVoIP\/SY"],"kind":"relationships"}],"metadata":{"navigatorTitle":[{"text":"PWVoIPHandleType","kind":"identifier"}],"externalID":"c:@M@PushwooshVoIP@E@PWVoIPHandleType","symbolKind":"enum","role":"symbol","title":"PWVoIPHandleType","roleHeading":"Enumeration","modules":[{"name":"PushwooshVoIP"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"PWVoIPHandleType","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshvoip\/pwvoiphandletype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshvoip\/pwvoiphandletype"]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPHandleType","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP"]]},"references":{"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPHandleType/init(rawValue:)":{"url":"\/documentation\/pushwooshvoip\/pwvoiphandletype\/init(rawvalue:)","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPHandleType\/init(rawValue:)","role":"symbol","title":"init(rawValue:)","type":"topic","abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPHandleType/phoneNumber":{"url":"\/documentation\/pushwooshvoip\/pwvoiphandletype\/phonenumber","navigatorTitle":[{"text":"PWVoIPHandleTypePhoneNumber","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPHandleType\/phoneNumber","kind":"symbol","role":"symbol","title":"PWVoIPHandleType.phoneNumber","type":"topic","abstract":[{"type":"text","text":"Phone number with automatic formatting."}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"phoneNumber","kind":"identifier"}]},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPHandleType/RawRepresentable-Implementations":{"role":"collectionGroup","type":"topic","title":"RawRepresentable Implementations","kind":"article","url":"\/documentation\/pushwooshvoip\/pwvoiphandletype\/rawrepresentable-implementations","abstract":[],"identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPHandleType\/RawRepresentable-Implementations"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPHandleType/Equatable-Implementations":{"role":"collectionGroup","type":"topic","title":"Equatable Implementations","kind":"article","abstract":[],"url":"\/documentation\/pushwooshvoip\/pwvoiphandletype\/equatable-implementations","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPHandleType\/Equatable-Implementations"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPHandleType/generic":{"url":"\/documentation\/pushwooshvoip\/pwvoiphandletype\/generic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"generic","kind":"identifier"}],"navigatorTitle":[{"text":"PWVoIPHandleTypeGeneric","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPHandleType\/generic","abstract":[{"text":"Generic identifier like username or custom ID.","type":"text"}],"title":"PWVoIPHandleType.generic"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP":{"title":"PushwooshVoIP","kind":"symbol","type":"topic","url":"\/documentation\/pushwooshvoip","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP","abstract":[{"type":"text","text":"VoIP push notifications with native call UI for iOS applications."}],"role":"collection"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPHandleType":{"title":"PWVoIPHandleType","url":"\/documentation\/pushwooshvoip\/pwvoiphandletype","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PWVoIPHandleType","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PWVoIPHandleType"}],"type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPHandleType","abstract":[{"text":"Display format for caller information in CallKit UI.","type":"text"}],"kind":"symbol"},"doc://com.pushwoosh.PushwooshVoIP/SY":{"identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://com.pushwoosh.PushwooshVoIP/SQ":{"identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.pushwoosh.PushwooshVoIP/SH":{"identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPHandleType/email":{"navigatorTitle":[{"text":"PWVoIPHandleTypeEmail","kind":"identifier"}],"role":"symbol","type":"topic","title":"PWVoIPHandleType.email","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"email"}],"kind":"symbol","abstract":[{"text":"Email address format.","type":"text"}],"url":"\/documentation\/pushwooshvoip\/pwvoiphandletype\/email","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPHandleType\/email"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"path":"\/metadata\/title","op":"replace","value":"PWVoIPHandleType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"PWVoIPHandleType"}]},{"path":"\/metadata\/navigatorTitle","value":[{"text":"PWVoIPHandleType","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPHandleType\/email","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPHandleType\/generic","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPHandleType\/phoneNumber"],"title":"Enumeration Cases"}]},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PWVoIPHandleType"},{"kind":"text","text":": "},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"PWVoIPHandleTypePhoneNumber","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPHandleType~1phoneNumber\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPHandleType~1phoneNumber\/fragments","value":[{"text":"PWVoIPHandleTypePhoneNumber","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPHandleType~1generic\/title","op":"replace","value":"PWVoIPHandleTypeGeneric"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPHandleType~1generic\/fragments","value":[{"text":"PWVoIPHandleTypeGeneric","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"PWVoIPHandleType","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPHandleType\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPHandleType\/fragments","op":"replace","value":[{"kind":"identifier","text":"PWVoIPHandleType"}]},{"value":"PWVoIPHandleTypeEmail","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPHandleType~1email\/title","op":"replace"},{"value":[{"kind":"identifier","text":"PWVoIPHandleTypeEmail"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPHandleType~1email\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}