{"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshtvos\/examples"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshtvos\/examples"]}],"metadata":{"title":"Examples","role":"article","roleHeading":"Article","modules":[{"name":"PushwooshTVOS"}]},"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/Examples","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"seeAlsoSections":[{"title":"Related Documentation","identifiers":["doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/GettingStarted","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/HTMLGuide","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PWTVOSRichMediaManager"]},{"title":"Getting Started","generated":true,"identifiers":["doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/GettingStarted","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/HTMLGuide"]}],"abstract":[{"text":"Code samples demonstrating common tvOS integration scenarios.","type":"text"}],"kind":"article","primaryContentSections":[{"kind":"content","content":[{"level":2,"anchor":"Overview","type":"heading","text":"Overview"},{"inlineContent":[{"text":"This page provides ready-to-use code examples for integrating Pushwoosh into your tvOS application. Examples cover basic setup, Rich Media configuration, custom push handling, and advanced scenarios.","type":"text"}],"type":"paragraph"},{"anchor":"Basic-Setup","text":"Basic Setup","type":"heading","level":2},{"text":"Minimal AppDelegate Setup","anchor":"Minimal-AppDelegate-Setup","level":3,"type":"heading"},{"type":"paragraph","inlineContent":[{"text":"The simplest way to integrate Pushwoosh into your tvOS app:","type":"text"}]},{"code":["import UIKit","import Pushwoosh","import PushwooshTVOS","","@main","class AppDelegate: UIResponder, UIApplicationDelegate {","","    func application(_ application: UIApplication,","                     didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {","","        Pushwoosh.TVoS.setAppCode(\"XXXXX-XXXXX\")","","        \/\/ Register for push notifications","        Pushwoosh.TVoS.registerForTvPushNotifications()","","        return true","    }","","    func application(_ application: UIApplication,","                     didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {","        Pushwoosh.TVoS.handleTvPushToken(deviceToken)","    }","","    func application(_ application: UIApplication,","                     didFailToRegisterForRemoteNotificationsWithError error: Error) {","        Pushwoosh.TVoS.handleTvPushRegistrationFailure(error)","    }","","    func application(_ application: UIApplication,","                     didReceiveRemoteNotification userInfo: [AnyHashable: Any],","                     fetchCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult) -> Void) {","        Pushwoosh.TVoS.handleTvPushReceived(userInfo: userInfo, completionHandler: completionHandler)","    }","}"],"type":"codeListing","syntax":"swift"},{"type":"heading","text":"Rich Media Configuration","level":2,"anchor":"Rich-Media-Configuration"},{"type":"heading","level":3,"text":"Center Position with Bottom Animation","anchor":"Center-Position-with-Bottom-Animation"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Display Rich Media in the center with slide-in animation from bottom:"}]},{"type":"codeListing","code":["func application(_ application: UIApplication,","                 didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {","","    Pushwoosh.TVoS.setAppCode(\"XXXXX-XXXXX\")","","    \/\/ Configure Rich Media","    Pushwoosh.TVoS.configureRichMediaWith(","        position: .center,","        presentAnimation: .fromBottom,","        dismissAnimation: .toBottom","    )","","    Pushwoosh.TVoS.configureCloseButton(true)","    Pushwoosh.TVoS.registerForTvPushNotifications()","","    return true","}"],"syntax":"swift"},{"anchor":"Left-Side-Panel","type":"heading","text":"Left Side Panel","level":3},{"type":"paragraph","inlineContent":[{"text":"Display Rich Media as a left-side panel:","type":"text"}]},{"syntax":"swift","code":["Pushwoosh.TVoS.configureRichMediaWith(","    position: .left,","    presentAnimation: .fromLeft,","    dismissAnimation: .toLeft",")"],"type":"codeListing"},{"level":3,"anchor":"Top-Banner","type":"heading","text":"Top Banner"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Display Rich Media as a top banner with slide-down animation:"}]},{"type":"codeListing","code":["Pushwoosh.TVoS.configureRichMediaWith(","    position: .top,","    presentAnimation: .fromTop,","    dismissAnimation: .toTop",")"],"syntax":"swift"},{"level":3,"text":"No Close Button","type":"heading","anchor":"No-Close-Button"},{"type":"paragraph","inlineContent":[{"text":"Hide the Close button if your Rich Media has custom dismiss logic:","type":"text"}]},{"syntax":"swift","type":"codeListing","code":["Pushwoosh.TVoS.configureRichMediaWith(","    position: .center,","    presentAnimation: .fromBottom,","    dismissAnimation: .toBottom",")","","Pushwoosh.TVoS.configureCloseButton(false)"]},{"text":"Custom Push Handling","type":"heading","anchor":"Custom-Push-Handling","level":2},{"text":"Selective Rich Media Display","anchor":"Selective-Rich-Media-Display","type":"heading","level":3},{"type":"paragraph","inlineContent":[{"text":"Display Rich Media only for specific push types:","type":"text"}]},{"type":"codeListing","syntax":"swift","code":["func application(_ application: UIApplication,","                 didReceiveRemoteNotification userInfo: [AnyHashable: Any],","                 fetchCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult) -> Void) {","","    \/\/ Check if push contains Rich Media","    if let rm = userInfo[\"rm\"] as? [String: Any],","       let url = rm[\"url\"] as? String {","","        \/\/ Check URL or other criteria","        if url.contains(\"special-offer\") {","            \/\/ Display Rich Media","            if Pushwoosh.TVoS.handleTVOSPush(userInfo: userInfo) {","                completionHandler(.newData)","                return","            }","        }","    }","","    \/\/ Handle as regular push","    Pushwoosh.TVoS.handleTvPushReceived(userInfo: userInfo, completionHandler: completionHandler)","}"]},{"level":2,"type":"heading","anchor":"Registration-with-Completion-Handler","text":"Registration with Completion Handler"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Register with device token and handle success\/failure:"}]},{"type":"codeListing","code":["func application(_ application: UIApplication,","                 didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {","    Pushwoosh.TVoS.registerForTvPushNotifications(withToken: deviceToken) { error in","        if let error = error {","            print(\"Failed to register: \\(error.localizedDescription)\")","        } else {","            print(\"Successfully registered for push notifications\")","        }","    }","}"],"syntax":"swift"},{"level":2,"text":"Unregister from Push Notifications","anchor":"Unregister-from-Push-Notifications","type":"heading"},{"inlineContent":[{"text":"Unregister the device from receiving push notifications:","type":"text"}],"type":"paragraph"},{"code":["Pushwoosh.TVoS.unregisterForTvPushNotifications { error in","    if let error = error {","        print(\"Failed to unregister: \\(error.localizedDescription)\")","    } else {","        print(\"Successfully unregistered from push notifications\")","    }","}"],"type":"codeListing","syntax":"swift"},{"text":"getTags Handler","level":2,"anchor":"getTags-Handler","type":"heading"},{"inlineContent":[{"text":"Handle tags retrieved from Rich Media:","type":"text"}],"type":"paragraph"},{"type":"codeListing","syntax":"swift","code":["func application(_ application: UIApplication,","                 didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {","","    Pushwoosh.TVoS.setAppCode(\"XXXXX-XXXXX\")","","    \/\/ Set getTags handler","    Pushwoosh.TVoS.setRichMediaGetTagsHandler { tags in","        print(\"Received tags from Rich Media:\")","        for (key, value) in tags {","            print(\"  \\(key): \\(value)\")","        }","    }","","    Pushwoosh.TVoS.registerForTvPushNotifications()","","    return true","}"]}]}],"references":{"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS":{"identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS","role":"collection","type":"topic","kind":"symbol","abstract":[{"text":"Push notifications and Rich Media for tvOS apps.","type":"text"}],"url":"\/documentation\/pushwooshtvos","title":"PushwooshTVOS"},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/GettingStarted":{"title":"Getting Started","type":"topic","role":"article","identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/GettingStarted","abstract":[{"type":"text","text":"Integrate Modal Rich Media for your tvOS app."}],"url":"\/documentation\/pushwooshtvos\/gettingstarted","kind":"article"},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PWTVOSRichMediaManager":{"title":"PWTVOSRichMediaManager","role":"symbol","abstract":[{"type":"text","text":"Manager for displaying Rich Media content on tvOS."}],"kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PWTVOSRichMediaManager","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PWTVOSRichMediaManager"}],"navigatorTitle":[{"text":"PWTVOSRichMediaManager","kind":"identifier"}],"url":"\/documentation\/pushwooshtvos\/pwtvosrichmediamanager","type":"topic"},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/HTMLGuide":{"title":"HTML Guide for tvOS Rich Media","type":"topic","role":"article","identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/HTMLGuide","url":"\/documentation\/pushwooshtvos\/htmlguide","abstract":[{"type":"text","text":"Create Rich Media content using Unlayer HTML format for tvOS."}],"kind":"article"},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PushwooshTVOSImplementation":{"identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation","type":"topic","role":"symbol","navigatorTitle":[{"text":"PushwooshTVOSImplementation","kind":"identifier"}],"abstract":[{"type":"text","text":"Main implementation class for tvOS push notifications and Rich Media."}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PushwooshTVOSImplementation","kind":"identifier"}],"url":"\/documentation\/pushwooshtvos\/pushwooshtvosimplementation","title":"PushwooshTVOSImplementation"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/seeAlsoSections","value":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/GettingStarted","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/HTMLGuide","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PWTVOSRichMediaManager"],"title":"Related Documentation"},{"generated":true,"title":"Getting Started","identifiers":["doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/GettingStarted","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/HTMLGuide"]}],"op":"replace"},{"value":"PWTVOSRichMediaManager","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PWTVOSRichMediaManager\/title"},{"value":[{"text":"PWTVOSRichMediaManager","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PWTVOSRichMediaManager\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation\/title","value":"PushwooshTVOSImplementation"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation\/fragments","value":[{"kind":"identifier","text":"PushwooshTVOSImplementation"}]}]}]}