{"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/GettingStarted","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshtvos\/gettingstarted"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshtvos\/gettingstarted"]}],"sections":[],"abstract":[{"type":"text","text":"Integrate Modal Rich Media for your tvOS app."}],"primaryContentSections":[{"content":[{"text":"Overview","type":"heading","anchor":"Overview","level":2},{"type":"paragraph","inlineContent":[{"text":"Modal Rich Media for tvOS provides interactive HTML-based content display optimized for Apple TV’s remote control navigation. Starting from SDK version 6.11.0, you can deliver rich media to tvOS devices.","type":"text"}]},{"name":"Note","style":"note","type":"aside","content":[{"type":"paragraph","inlineContent":[{"inlineContent":[{"text":"Important","type":"text"}],"type":"strong"},{"text":": Traditional push notifications are not supported on Apple TV. Only silent notifications with rich media content work on tvOS.","type":"text"}]}]},{"level":2,"type":"heading","anchor":"Installation","text":"Installation"},{"type":"tabNavigator","tabs":[{"title":"Swift Package Manager","content":[{"inlineContent":[{"type":"text","text":"In Xcode, use the following URL to add the Pushwoosh dependency:"}],"type":"paragraph"},{"type":"codeListing","syntax":null,"code":["https:\/\/github.com\/Pushwoosh\/Pushwoosh-XCFramework"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Select the required modules in your target:"}]},{"inlineContent":[],"type":"paragraph"},{"name":"Note","style":"note","type":"aside","content":[{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Important"}]},{"text":": The modules PushwooshFramework, PushwooshCore, PushwooshBridge, and PushwooshTVOS are required.","type":"text"}]}]}]},{"title":"CocoaPods","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Add to your Podfile:"}]},{"type":"codeListing","syntax":"ruby","code":["platform :tvos, '11.0'","use_frameworks!","","target 'YourTVOSApp' do","  pod 'PushwooshXCFramework'","  pod 'PushwooshXCFramework\/PushwooshTVOS'","end"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Then run:"}]},{"type":"codeListing","code":["pod install"],"syntax":"bash"}]}]},{"type":"heading","level":2,"anchor":"Prerequisites","text":"Prerequisites"},{"inlineContent":[{"text":"Before you begin, ensure you have:","type":"text"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A Pushwoosh account"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A Pushwoosh project set up in your account"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A tvOS platform configured in your Pushwoosh project. We recommend using the Token-Based Authentication configuration as the simplest approach"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Your Pushwoosh Application Code from the Control Panel"}]}]},{"content":[{"inlineContent":[{"text":"tvOS 11.0+ deployment target","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"PushwooshFramework, PushwooshCore, and PushwooshBridge frameworks integrated in your project","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"SDK version 6.11.0 or higher"}],"type":"paragraph"}]}]},{"style":"note","content":[{"inlineContent":[{"type":"strong","inlineContent":[{"text":"Important","type":"text"}]},{"type":"text","text":": Rich Media HTML content must be hosted on a web server accessible from your tvOS devices."}],"type":"paragraph"}],"name":"Note","type":"aside"},{"text":"Step 1: Add Required Capabilities","level":2,"type":"heading","anchor":"Step-1-Add-Required-Capabilities"},{"type":"paragraph","inlineContent":[{"text":"In Xcode:","type":"text"}]},{"type":"orderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Select your tvOS target","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Go to "},{"type":"strong","inlineContent":[{"text":"Signing & Capabilities","type":"text"}]}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Click "},{"type":"strong","inlineContent":[{"type":"text","text":"+ Capability"}]},{"type":"text","text":" and add "},{"inlineContent":[{"text":"Push Notifications","type":"text"}],"type":"strong"}],"type":"paragraph"}]}]},{"inlineContent":[],"type":"paragraph"},{"text":"Step 2: Configure AppDelegate","anchor":"Step-2-Configure-AppDelegate","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"text":"Initialize Pushwoosh in ","type":"text"},{"type":"codeVoice","code":"application(_:didFinishLaunchingWithOptions:)"},{"type":"text","text":":"}]},{"type":"codeListing","code":["import UIKit","import Pushwoosh","import PushwooshTVOS","","@main","class AppDelegate: UIResponder, UIApplicationDelegate {","","    func application(","        _ application: UIApplication,","        didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?","    ) -> Bool {","","        Pushwoosh.TVoS.setAppCode(\"XXXXX-XXXXX\")","        Pushwoosh.TVoS.registerForTvPushNotifications()","","        return true","    }","}"],"syntax":"swift"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Replace "},{"type":"codeVoice","code":"XXXXX-XXXXX"},{"text":" with your actual Pushwoosh Application Code.","type":"text"}]},{"level":2,"type":"heading","anchor":"Step-3-Handle-Device-Token-Registration","text":"Step 3: Handle Device Token Registration"},{"type":"paragraph","inlineContent":[{"text":"Implement token registration methods:","type":"text"}]},{"code":["import UIKit","import Pushwoosh","import PushwooshTVOS","","@main","class AppDelegate: UIResponder, UIApplicationDelegate {","","    func application(","        _ application: UIApplication,","        didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data","    ) {","        Pushwoosh.TVoS.handleTvPushToken(deviceToken)","    }","","    func application(","        _ application: UIApplication,","        didFailToRegisterForRemoteNotificationsWithError error: Error","    ) {","        Pushwoosh.TVoS.handleTvPushRegistrationFailure(error)","    }","}"],"type":"codeListing","syntax":"swift"},{"anchor":"Step-4-Process-Incoming-Notifications","type":"heading","text":"Step 4: Process Incoming Notifications","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Handle incoming push notifications with rich media:"}]},{"type":"codeListing","syntax":"swift","code":["func application(","    _ application: UIApplication,","    didReceiveRemoteNotification userInfo: [AnyHashable: Any],","    fetchCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult) -> Void",") {","    \/\/ Check if push contains Rich Media and handle it","    if Pushwoosh.TVoS.handleTVOSPush(userInfo: userInfo) {","        \/\/ Rich Media was successfully displayed","        completionHandler(.newData)","    } else {","        \/\/ No Rich Media in notification","        completionHandler(.noData)","    }","}"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"codeVoice","code":"handleTVOSPush(userInfo:)"},{"type":"text","text":" method returns a boolean indicating whether the notification contained rich media and was handled successfully."}]},{"text":"Step 5: Configure Rich Media (Optional)","anchor":"Step-5-Configure-Rich-Media-Optional","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Customize the position and animations for Rich Media display:"}]},{"code":["func application(","    _ application: UIApplication,","    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?",") -> Bool {","","    Pushwoosh.TVoS.setAppCode(\"XXXXX-XXXXX\")","","    \/\/ Configure Rich Media appearance","    Pushwoosh.TVoS.configureRichMediaWith(","        position: .center,","        presentAnimation: .fromBottom,","        dismissAnimation: .toBottom","    )","","    \/\/ Show or hide the system Close button","    Pushwoosh.TVoS.configureCloseButton(true)","","    Pushwoosh.TVoS.registerForTvPushNotifications()","","    return true","}"],"type":"codeListing","syntax":"swift"},{"text":"Rich Media Position Options","anchor":"Rich-Media-Position-Options","level":3,"type":"heading"},{"header":"row","rows":[[[{"type":"paragraph","inlineContent":[{"type":"text","text":"Position"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"Description"}]}]],[[{"inlineContent":[{"code":".center","type":"codeVoice"}],"type":"paragraph"}],[{"inlineContent":[{"type":"text","text":"Display in the center of the screen (default)"}],"type":"paragraph"}]],[[{"type":"paragraph","inlineContent":[{"code":".left","type":"codeVoice"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"Display on the left side"}]}]],[[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":".right"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"Display on the right side"}]}]],[[{"inlineContent":[{"code":".top","type":"codeVoice"}],"type":"paragraph"}],[{"inlineContent":[{"text":"Display at the top","type":"text"}],"type":"paragraph"}]],[[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":".bottom"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"Display at the bottom"}]}]]],"type":"table"},{"anchor":"Animation-Options","text":"Animation Options","type":"heading","level":3},{"type":"table","header":"row","rows":[[[{"inlineContent":[{"text":"Present Animation","type":"text"}],"type":"paragraph"}],[{"inlineContent":[{"type":"text","text":"Dismiss Animation"}],"type":"paragraph"}],[{"inlineContent":[{"type":"text","text":"Description"}],"type":"paragraph"}]],[[{"inlineContent":[{"code":".none","type":"codeVoice"}],"type":"paragraph"}],[{"inlineContent":[{"type":"codeVoice","code":".none"}],"type":"paragraph"}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"No animation, appears\/disappears immediately (default)"}]}]],[[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":".fromTop"}]}],[{"type":"paragraph","inlineContent":[{"code":".toTop","type":"codeVoice"}]}],[{"type":"paragraph","inlineContent":[{"text":"Slides in from \/ out to the top","type":"text"}]}]],[[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":".fromBottom"}]}],[{"inlineContent":[{"code":".toBottom","type":"codeVoice"}],"type":"paragraph"}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"Slides in from \/ out to the bottom"}]}]],[[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":".fromLeft"}]}],[{"inlineContent":[{"type":"codeVoice","code":".toLeft"}],"type":"paragraph"}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"Slides in from \/ out to the left"}]}]],[[{"type":"paragraph","inlineContent":[{"code":".fromRight","type":"codeVoice"}]}],[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":".toRight"}]}],[{"type":"paragraph","inlineContent":[{"text":"Slides in from \/ out to the right","type":"text"}]}]]]},{"level":3,"text":"Close Button Configuration","anchor":"Close-Button-Configuration","type":"heading"},{"inlineContent":[{"type":"text","text":"If you hide the system close button with "},{"type":"codeVoice","code":"configureCloseButton(false)"},{"text":", ensure your Rich Media HTML includes a custom button with the ","type":"text"},{"type":"codeVoice","code":"closeInApp()"},{"text":" action:","type":"text"}],"type":"paragraph"},{"type":"codeListing","syntax":"html","code":["<a href=\"#\" onclick=\"closeInApp()\">Close<\/a>"]},{"level":2,"anchor":"Step-6-Create-Rich-Media-HTML-Content","type":"heading","text":"Step 6: Create Rich Media HTML Content"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Rich Media content uses HTML with inline styles. The SDK parses HTML and renders it natively with tvOS Focus Engine support."}]},{"anchor":"Focus-Navigation","type":"heading","level":3,"text":"Focus Navigation"},{"inlineContent":[{"text":"Focusable elements are automatically detected in the HTML content. Users can navigate between elements using the directional pad on the Apple TV remote. Standard elements like ","type":"text"},{"code":"<button>","type":"codeVoice"},{"type":"text","text":", "},{"type":"codeVoice","code":"<a>"},{"type":"text","text":", and "},{"type":"codeVoice","code":"<input>"},{"text":" receive automatic focus support.","type":"text"}],"type":"paragraph"},{"level":3,"type":"heading","text":"Basic Example","anchor":"Basic-Example"},{"code":["<!DOCTYPE html>","<html>","<body style=\"margin: 0; padding: 0;\">","    <div style=\"width: 1600px; height: 600px; padding: 50px; background-color: #667eea; display: flex; flex-direction: column; align-items: center; justify-content: center;\">","","        <h1 style=\"color: #ffffff; font-size: 48px; margin-bottom: 20px;\">","            Welcome to Our Service","        <\/h1>","","        <p style=\"color: #e0e7ff; font-size: 22px; margin-bottom: 30px; text-align: center;\">","            Discover amazing content tailored for your Apple TV","        <\/p>","","        <div style=\"display: flex; gap: 15px;\">","            <a href=\"#\" data-event=\"subscribe_clicked\" style=\"padding: 16px 30px; background-color: #ffffff; color: #667eea; text-align: center; border-radius: 10px; text-decoration: none;\">","                Subscribe Now","            <\/a>","","            <a href=\"#\" onclick=\"closeInApp()\" style=\"padding: 16px 30px; background-color: transparent; color: #ffffff; border: 2px solid #ffffff; border-radius: 10px; text-decoration: none;\">","                Close","            <\/a>","        <\/div>","","    <\/div>","<\/body>","<\/html>"],"type":"codeListing","syntax":"html"},{"text":"HTML Best Practices","type":"heading","level":3,"anchor":"HTML-Best-Practices"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"inlineContent":[{"text":"Use standard interactive elements","type":"text"}],"type":"strong"},{"text":": ","type":"text"},{"code":"<button>","type":"codeVoice"},{"type":"text","text":", "},{"type":"codeVoice","code":"<a>"},{"text":", ","type":"text"},{"type":"codeVoice","code":"<input>"},{"type":"text","text":" receive automatic focus support"}]}]},{"content":[{"inlineContent":[{"type":"strong","inlineContent":[{"text":"Maintain adequate spacing","type":"text"}]},{"text":": Keep at least 20-30px between interactive components for easy navigation","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"strong","inlineContent":[{"text":"Minimum element width","type":"text"}]},{"type":"text","text":": Target minimum 250pt width for interactive elements"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"inlineContent":[{"type":"text","text":"Test focus navigation"}],"type":"strong"},{"type":"text","text":": Always test in Apple TV simulator to verify navigation flow"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"inlineContent":[{"text":"Use inline styles","type":"text"}],"type":"strong"},{"type":"text","text":": All styles must be inline, external CSS is not supported"}]}]},{"content":[{"inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Use larger fonts"}]},{"type":"text","text":": Minimum 22px for body text, 48px+ for headings"}],"type":"paragraph"}]}]},{"anchor":"Supported-Elements","text":"Supported Elements","type":"heading","level":3},{"items":[{"content":[{"inlineContent":[{"inlineContent":[{"type":"text","text":"Headings"}],"type":"strong"},{"text":": ","type":"text"},{"type":"codeVoice","code":"<h1>"},{"text":" through ","type":"text"},{"type":"codeVoice","code":"<h6>"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Text"}]},{"type":"text","text":": "},{"code":"<p>","type":"codeVoice"},{"type":"text","text":", "},{"code":"<div>","type":"codeVoice"},{"type":"text","text":", "},{"code":"<span>","type":"codeVoice"}]}]},{"content":[{"inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Images"}]},{"text":": ","type":"text"},{"type":"codeVoice","code":"<img src=\"...\">"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"inlineContent":[{"type":"text","text":"Buttons"}],"type":"strong"},{"text":": ","type":"text"},{"type":"codeVoice","code":"<a>"},{"type":"text","text":", "},{"code":"<button>","type":"codeVoice"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Text Fields"}]},{"type":"text","text":": "},{"code":"<input type=\"text\">","type":"codeVoice"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"text":"Containers","type":"text"}]},{"type":"text","text":": "},{"type":"codeVoice","code":"<div>"},{"type":"text","text":" with flexbox support"}]}]}],"type":"unorderedList"},{"anchor":"Button-Actions","text":"Button Actions","level":3,"type":"heading"},{"rows":[[[{"type":"paragraph","inlineContent":[{"type":"text","text":"Action"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"Description"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"Example"}]}]],[[{"type":"paragraph","inlineContent":[{"text":"Close","type":"text"}]}],[{"type":"paragraph","inlineContent":[{"code":"onclick=\"closeInApp()\"","type":"codeVoice"}]}],[{"inlineContent":[{"type":"codeVoice","code":"<a href=\"#\" onclick=\"closeInApp()\">Close<\/a>"}],"type":"paragraph"}]],[[{"type":"paragraph","inlineContent":[{"type":"text","text":"Track Event"}]}],[{"inlineContent":[{"type":"codeVoice","code":"data-event"},{"text":" + ","type":"text"},{"type":"codeVoice","code":"data-attributes"}],"type":"paragraph"}],[{"inlineContent":[{"type":"codeVoice","code":"<a data-event=\"event_name\" data-attributes='{\"key\":\"value\"}'>Button<\/a>"}],"type":"paragraph"}]],[[{"type":"paragraph","inlineContent":[{"text":"Send Tags","type":"text"}]}],[{"type":"paragraph","inlineContent":[{"code":"data-action=\"sendTags\"","type":"codeVoice"},{"type":"text","text":" + "},{"type":"codeVoice","code":"data-tags"}]}],[{"inlineContent":[{"code":"<button data-action=\"sendTags\" data-tags='{\"tag\":\"value\"}'>Set Tags<\/button>","type":"codeVoice"}],"type":"paragraph"}]],[[{"type":"paragraph","inlineContent":[{"type":"text","text":"Get Tags"}]}],[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"data-action=\"getTags\""}]}],[{"inlineContent":[{"type":"codeVoice","code":"<button data-action=\"getTags\">Get Tags<\/button>"}],"type":"paragraph"}]],[[{"inlineContent":[{"text":"Open Settings","type":"text"}],"type":"paragraph"}],[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"data-action=\"openSettings\""}]}],[{"inlineContent":[{"code":"<button data-action=\"openSettings\">Settings<\/button>","type":"codeVoice"}],"type":"paragraph"}]]],"type":"table","header":"row"},{"anchor":"Step-7-Send-Push-Notifications","type":"heading","text":"Step 7: Send Push Notifications","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Send silent notifications with rich media using the Pushwoosh REST API."}]},{"name":"Note","type":"aside","style":"note","content":[{"inlineContent":[{"inlineContent":[{"type":"text","text":"Important"}],"type":"strong"},{"type":"text","text":": Only silent notifications with rich media work on Apple TV. Traditional alert notifications are not supported."}],"type":"paragraph"}]},{"syntax":"bash","type":"codeListing","code":["curl -X POST https:\/\/api.pushwoosh.com\/json\/1.3\/createMessage \\","  -H \"Content-Type: application\/json\" \\","  -d '{","    \"request\": {","      \"application\": \"YOUR-APP-CODE\",","      \"auth\": \"YOUR-API-TOKEN\",","      \"notifications\": [{","        \"send_date\": \"now\",","        \"content\": \"Rich Media Message\",","        \"tvos_root_params\": {","          \"aps\": {","            \"content-available\": 1","          },","          \"rm\": {","            \"url\": \"https:\/\/example.com\/richmedia.html\",","            \"code\": \"unique_message_id\"","          }","        }","      }]","    }","  }'"]},{"type":"paragraph","inlineContent":[{"text":"Replace ","type":"text"},{"type":"codeVoice","code":"YOUR-APP-CODE"},{"type":"text","text":" and "},{"type":"codeVoice","code":"YOUR-API-TOKEN"},{"type":"text","text":" with your actual credentials."}]},{"text":"Payload Structure","level":3,"anchor":"Payload-Structure","type":"heading"},{"header":"row","rows":[[[{"inlineContent":[{"type":"text","text":"Field"}],"type":"paragraph"}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"Description"}]}]],[[{"type":"paragraph","inlineContent":[{"code":"content-available: 1","type":"codeVoice"}]}],[{"type":"paragraph","inlineContent":[{"text":"Required for silent notifications on tvOS","type":"text"}]}]],[[{"inlineContent":[{"type":"codeVoice","code":"rm.url"}],"type":"paragraph"}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"URL to your hosted Rich Media HTML file"}]}]],[[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"rm.code"}]}],[{"inlineContent":[{"type":"text","text":"Unique identifier for this rich media message"}],"type":"paragraph"}]]],"type":"table"},{"text":"Testing","type":"heading","level":2,"anchor":"Testing"},{"type":"heading","level":3,"text":"Testing on Simulator","anchor":"Testing-on-Simulator"},{"type":"paragraph","inlineContent":[{"type":"text","text":"tvOS simulators do not support APNs. You can test:"}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"SDK initialization and configuration"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Rich Media display by calling methods directly"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"UI and focus navigation"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"HTML content rendering","type":"text"}],"type":"paragraph"}]}]},{"inlineContent":[{"identifier":"tv_os_simulator.png","type":"image"}],"type":"paragraph"},{"type":"heading","level":3,"anchor":"Testing-on-Physical-Apple-TV","text":"Testing on Physical Apple TV"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Build and run your app on a physical Apple TV device","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Send a test silent notification with rich media from the Pushwoosh Control Panel","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Verify the Rich Media appears on the device"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Test focus navigation with Apple TV remote","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Verify all button actions work correctly"}],"type":"paragraph"}]}],"type":"orderedList"},{"level":3,"text":"Verifying Push Token Registration","type":"heading","anchor":"Verifying-Push-Token-Registration"},{"type":"paragraph","inlineContent":[{"text":"Check Xcode console logs:","type":"text"}]},{"code":["[PW] PUSH TV TOKEN: <your-device-token>","Device successfully registered for push notifications"],"syntax":null,"type":"codeListing"},{"level":3,"type":"heading","text":"Focus Navigation Testing","anchor":"Focus-Navigation-Testing"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Test the following on physical Apple TV:"}]},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Navigate between focusable elements using directional pad","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Verify proper focus highlighting","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Test button activation with the select button","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Ensure smooth navigation flow without focus traps"}],"type":"paragraph"}]}],"type":"unorderedList"},{"text":"Troubleshooting","anchor":"Troubleshooting","type":"heading","level":2},{"type":"heading","anchor":"Push-Notifications-Not-Received","text":"Push Notifications Not Received","level":3},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Verify Push Notifications capability is enabled in Xcode","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Check that your provisioning profile includes push notification entitlement"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Ensure the App Code matches your Pushwoosh Control Panel"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Verify you’re sending "},{"type":"strong","inlineContent":[{"type":"text","text":"silent notifications"}]},{"type":"text","text":" ("},{"code":"content-available: 1","type":"codeVoice"},{"type":"text","text":")"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Check that the device token is being sent to Pushwoosh servers"}],"type":"paragraph"}]}]},{"text":"Rich Media Not Displaying","level":3,"type":"heading","anchor":"Rich-Media-Not-Displaying"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Verify the Rich Media URL is accessible from tvOS device","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Check HTML structure and inline styles","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Ensure the "},{"type":"codeVoice","code":"rm"},{"text":" payload is correctly formatted in the notification","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"Test HTML rendering in a browser first","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"Check console logs for parsing errors","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Verify ","type":"text"},{"type":"codeVoice","code":"handleTVOSPush(userInfo:)"},{"type":"text","text":" returns "},{"code":"true","type":"codeVoice"}]}]}],"type":"unorderedList"},{"anchor":"Focus-Navigation-Issues","text":"Focus Navigation Issues","level":3,"type":"heading"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Ensure interactive elements have minimum 250pt width"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Maintain adequate spacing (20-30px) between focusable elements","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Verify elements are standard HTML interactive elements (","type":"text"},{"type":"codeVoice","code":"<button>"},{"type":"text","text":", "},{"code":"<a>","type":"codeVoice"},{"type":"text","text":", "},{"type":"codeVoice","code":"<input>"},{"type":"text","text":")"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Test with physical Apple TV remote, not simulator"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Check that "},{"code":"onclick","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"data-","type":"codeVoice"},{"text":" attributes are correctly set","type":"text"}],"type":"paragraph"}]}]},{"anchor":"HTML-Content-Not-Rendering","type":"heading","level":3,"text":"HTML Content Not Rendering"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use only inline styles, no external CSS"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Avoid complex CSS selectors"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Keep HTML structure simple and flat (max 3-4 nesting levels)","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Ensure image URLs use HTTPS"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"Test HTML in a browser to verify structure","type":"text"}],"type":"paragraph"}]}]},{"text":"Next Steps","level":2,"type":"heading","anchor":"Next-Steps"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/Examples","type":"reference"},{"type":"text","text":" - Code examples for common use cases"}]}]},{"content":[{"inlineContent":[{"type":"reference","identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation","isActive":true},{"text":" - Full API reference","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PWTVOSRichMediaManager","isActive":true,"type":"reference"},{"type":"text","text":" - Rich Media manager reference"}]}]}],"type":"unorderedList"}],"kind":"content"}],"metadata":{"role":"article","modules":[{"name":"PushwooshTVOS"}],"title":"Getting Started","roleHeading":"Article"},"kind":"article","seeAlsoSections":[{"identifiers":["doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/Examples","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/HTMLGuide"],"generated":true,"title":"Getting Started"}],"references":{"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS","role":"collection","url":"\/documentation\/pushwooshtvos","title":"PushwooshTVOS","abstract":[{"type":"text","text":"Push notifications and Rich Media for tvOS apps."}]},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PushwooshTVOSImplementation":{"abstract":[{"type":"text","text":"Main implementation class for tvOS push notifications and Rich Media."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PushwooshTVOSImplementation","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PushwooshTVOSImplementation","navigatorTitle":[{"text":"PushwooshTVOSImplementation","kind":"identifier"}],"title":"PushwooshTVOSImplementation","url":"\/documentation\/pushwooshtvos\/pushwooshtvosimplementation","type":"topic","kind":"symbol"},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/PWTVOSRichMediaManager":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/PWTVOSRichMediaManager","role":"symbol","url":"\/documentation\/pushwooshtvos\/pwtvosrichmediamanager","title":"PWTVOSRichMediaManager","abstract":[{"type":"text","text":"Manager for displaying Rich Media content on tvOS."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PWTVOSRichMediaManager"}],"navigatorTitle":[{"text":"PWTVOSRichMediaManager","kind":"identifier"}]},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/HTMLGuide":{"title":"HTML Guide for tvOS Rich Media","url":"\/documentation\/pushwooshtvos\/htmlguide","kind":"article","role":"article","type":"topic","abstract":[{"type":"text","text":"Create Rich Media content using Unlayer HTML format for tvOS."}],"identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/HTMLGuide"},"doc://com.pushwoosh.PushwooshTVOS/documentation/PushwooshTVOS/Examples":{"title":"Examples","url":"\/documentation\/pushwooshtvos\/examples","kind":"article","role":"article","type":"topic","abstract":[{"type":"text","text":"Code samples demonstrating common tvOS integration scenarios."}],"identifier":"doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/Examples"},"tv_os_simulator.png":{"variants":[{"url":"\/images\/tv_os_simulator.png","traits":["1x","light"]}],"alt":"tvOS Simulator testing with Rich Media display","type":"image","identifier":"tv_os_simulator.png"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":null,"op":"add","path":"\/topicSections"},{"value":[{"title":"Getting Started","generated":true,"identifiers":["doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/Examples","doc:\/\/com.pushwoosh.PushwooshTVOS\/documentation\/PushwooshTVOS\/HTMLGuide"]}],"op":"replace","path":"\/seeAlsoSections"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation\/title","op":"replace","value":"PushwooshTVOSImplementation"},{"value":[{"text":"PushwooshTVOSImplementation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PushwooshTVOSImplementation\/fragments"},{"value":"PWTVOSRichMediaManager","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PWTVOSRichMediaManager\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshTVOS~1documentation~1PushwooshTVOS~1PWTVOSRichMediaManager\/fragments","value":[{"kind":"identifier","text":"PWTVOSRichMediaManager"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}