{"kind":"symbol","identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Foundation\/NSNotification\/Name\/PWInboxMessagesDidUpdate","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"]]},"abstract":[{"text":"The notification arriving on the Inbox messages renewal","type":"text"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/foundation\/nsnotification\/name\/pwinboxmessagesdidupdate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/foundation\/nsnotification\/name\/pwinboxmessagesdidupdate"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"PWInboxMessagesDidUpdate"},{"kind":"text","text":": "},{"text":"NSNotification","preciseIdentifier":"c:objc(cs)NSNotification","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"Name","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSNotificationName"}],"platforms":["iOS"]}]}],"metadata":{"externalID":"c:@PWInboxMessagesDidUpdateNotification","roleHeading":"Type Property","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PWInboxMessagesDidUpdate"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNotification","text":"NSNotification","kind":"typeIdentifier"},{"text":".","kind":"text"},{"kind":"typeIdentifier","text":"Name","preciseIdentifier":"c:@T@NSNotificationName"}],"title":"PWInboxMessagesDidUpdate","navigatorTitle":[{"kind":"identifier","text":"PWInboxMessagesDidUpdateNotification"}],"extendedModule":"Foundation","modules":[{"relatedModules":["Foundation"],"name":"PushwooshFramework"}],"role":"symbol","symbolKind":"property"},"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Foundation/NSNotification/Name/PWInboxMessagesDidUpdate":{"role":"symbol","abstract":[{"type":"text","text":"The notification arriving on the Inbox messages renewal"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PWInboxMessagesDidUpdate","kind":"identifier"},{"kind":"text","text":": "},{"text":"NSNotification","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNotification"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@T@NSNotificationName","text":"Name","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Foundation\/NSNotification\/Name\/PWInboxMessagesDidUpdate","title":"PWInboxMessagesDidUpdate","navigatorTitle":[{"text":"PWInboxMessagesDidUpdateNotification","kind":"identifier"}],"type":"topic","url":"\/documentation\/pushwooshframework\/foundation\/nsnotification\/name\/pwinboxmessagesdidupdate"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","kind":"symbol","role":"collection","title":"PushwooshFramework","url":"\/documentation\/pushwooshframework","type":"topic","abstract":[{"text":"Push notification SDK for iOS applications.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Global Variable","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"PWInboxMessagesDidUpdateNotification"},{"path":"\/metadata\/symbolKind","op":"replace","value":"var"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"PWInboxMessagesDidUpdateNotification","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"extern"},{"text":" ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PWInboxMessagesDidUpdateNotification"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"value":"PWInboxMessagesDidUpdateNotification","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Foundation~1NSNotification~1Name~1PWInboxMessagesDidUpdate\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Foundation~1NSNotification~1Name~1PWInboxMessagesDidUpdate\/fragments","value":[{"text":"PWInboxMessagesDidUpdateNotification","kind":"identifier"}],"op":"replace"}]}]}