{"variants":[{"paths":["\/documentation\/pushwooshframework\/foundation\/nsnotification\/name\/pwinboxmessagesdidreceiveinpush"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pushwooshframework\/foundation\/nsnotification\/name\/pwinboxmessagesdidreceiveinpush"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"The notification arriving when a push message is added to Inbox"}],"metadata":{"externalID":"c:@PWInboxMessagesDidReceiveInPushNotification","navigatorTitle":[{"kind":"identifier","text":"PWInboxMessagesDidReceiveInPushNotification"}],"roleHeading":"Type Property","title":"PWInboxMessagesDidReceiveInPush","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PWInboxMessagesDidReceiveInPush"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNotification","text":"NSNotification"},{"kind":"text","text":"."},{"text":"Name","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSNotificationName"}],"role":"symbol","symbolKind":"property","modules":[{"name":"PushwooshFramework"}]},"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Foundation\/NSNotification\/Name\/PWInboxMessagesDidReceiveInPush","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Foundation","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Foundation\/NSNotification","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Foundation\/NSNotification\/Name"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"PWInboxMessagesDidReceiveInPush","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNotification","text":"NSNotification"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Name","preciseIdentifier":"c:@T@NSNotificationName"}]}],"kind":"declarations"}],"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Foundation/NSNotification/Name":{"url":"\/documentation\/pushwooshframework\/foundation\/nsnotification\/name","navigatorTitle":[{"text":"Name","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Foundation\/NSNotification\/Name","title":"NSNotification.Name","fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNotification","text":"NSNotification","kind":"identifier"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@T@NSNotificationName","text":"Name","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[],"kind":"symbol"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"role":"collection","kind":"symbol","abstract":[{"type":"text","text":"Push notification SDK for iOS applications."}],"title":"PushwooshFramework","type":"topic","url":"\/documentation\/pushwooshframework","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Foundation":{"type":"topic","url":"\/documentation\/pushwooshframework\/foundation","title":"Foundation","role":"collection","abstract":[],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Foundation","kind":"symbol"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Foundation/NSNotification":{"navigatorTitle":[{"text":"NSNotification","kind":"identifier"}],"type":"topic","url":"\/documentation\/pushwooshframework\/foundation\/nsnotification","title":"NSNotification","role":"symbol","abstract":[],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Foundation\/NSNotification","kind":"symbol"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/Foundation/NSNotification/Name/PWInboxMessagesDidReceiveInPush":{"url":"\/documentation\/pushwooshframework\/foundation\/nsnotification\/name\/pwinboxmessagesdidreceiveinpush","navigatorTitle":[{"kind":"identifier","text":"PWInboxMessagesDidReceiveInPushNotification"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/Foundation\/NSNotification\/Name\/PWInboxMessagesDidReceiveInPush","title":"PWInboxMessagesDidReceiveInPush","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"PWInboxMessagesDidReceiveInPush"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNotification","text":"NSNotification"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@T@NSNotificationName","text":"Name","kind":"typeIdentifier"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"The notification arriving when a push message is added to Inbox"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Global Variable","path":"\/metadata\/roleHeading","op":"replace"},{"value":"PWInboxMessagesDidReceiveInPushNotification","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"var"},{"value":[{"kind":"identifier","text":"PWInboxMessagesDidReceiveInPushNotification"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"extern"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" * ","kind":"text"},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"identifier","text":"PWInboxMessagesDidReceiveInPushNotification"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace"},{"value":"PWInboxMessagesDidReceiveInPushNotification","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Foundation~1NSNotification~1Name~1PWInboxMessagesDidReceiveInPush\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1Foundation~1NSNotification~1Name~1PWInboxMessagesDidReceiveInPush\/fragments","value":[{"kind":"identifier","text":"PWInboxMessagesDidReceiveInPushNotification"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}