{"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate\/mutedCall(_:perform:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"modules":[{"name":"PushwooshVoIP"}],"title":"mutedCall(_:perform:)","navigatorTitle":[{"text":"mutedCall:perform:","kind":"identifier"}],"required":true,"role":"symbol","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mutedCall"},{"text":"(","kind":"text"},{"text":"CXProvider","preciseIdentifier":"c:objc(cs)CXProvider","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"perform","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)CXSetMutedCallAction","text":"CXSetMutedCallAction","kind":"typeIdentifier"},{"text":")","kind":"text"}],"externalID":"c:@M@PushwooshVoIP@objc(pl)PWVoIPCallDelegate(im)mutedCall:perform:","roleHeading":"Instance Method"},"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"text":"Called when user mutes or unmutes the call.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mutedCall","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"provider"},{"kind":"text","text":": "},{"text":"CXProvider","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CXProvider"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"perform"},{"kind":"text","text":" "},{"text":"action","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CXSetMutedCallAction","preciseIdentifier":"c:objc(cs)CXSetMutedCallAction"},{"text":")","kind":"text"}]}],"kind":"declarations"},{"parameters":[{"name":"provider","content":[{"type":"paragraph","inlineContent":[{"text":"The CallKit provider managing the call.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"The action containing mute state. Use ","type":"text"},{"type":"codeVoice","code":"action.isMuted"},{"text":" to determine the new mute state.","type":"text"},{"type":"text","text":" "},{"text":"Call ","type":"text"},{"code":"action.fulfill()","type":"codeVoice"},{"text":" after updating the audio state.","type":"text"}]}],"name":"action"}],"kind":"parameters"},{"content":[{"text":"Discussion","level":2,"type":"heading","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This method is invoked when the user toggles the mute button in CallKit UI. Implement this method"},{"type":"text","text":" "},{"type":"text","text":"to mute or unmute the local audio stream accordingly."}]},{"style":"note","type":"aside","name":"Note","content":[{"inlineContent":[{"text":"This is an optional delegate method. Implement it to control microphone muting during the call.","type":"text"}],"type":"paragraph"}]}],"kind":"content"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshvoip\/pwvoipcalldelegate\/mutedcall(_:perform:)"]},{"paths":["\/documentation\/pushwooshvoip\/pwvoipcalldelegate\/mutedcall(_:perform:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPCallDelegate/mutedCall(_:perform:)":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mutedCall","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CXProvider","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CXProvider"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"perform"},{"text":": ","kind":"text"},{"text":"CXSetMutedCallAction","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CXSetMutedCallAction"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"mutedCall:perform:","kind":"identifier"}],"type":"topic","url":"\/documentation\/pushwooshvoip\/pwvoipcalldelegate\/mutedcall(_:perform:)","abstract":[{"type":"text","text":"Called when user mutes or unmutes the call."}],"title":"mutedCall(_:perform:)","required":true,"kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate\/mutedCall(_:perform:)"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PWVoIPCallDelegate":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"PWVoIPCallDelegate","kind":"identifier"}],"url":"\/documentation\/pushwooshvoip\/pwvoipcalldelegate","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Delegate protocol for receiving VoIP call events and CallKit callbacks."}],"identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PWVoIPCallDelegate","title":"PWVoIPCallDelegate","navigatorTitle":[{"kind":"identifier","text":"PWVoIPCallDelegate"}],"role":"symbol"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP":{"kind":"symbol","type":"topic","role":"collection","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP","url":"\/documentation\/pushwooshvoip","abstract":[{"type":"text","text":"VoIP push notifications with native call UI for iOS applications."}],"title":"PushwooshVoIP"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"mutedCall:perform:","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"mutedCall:perform:"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"text":"mutedCall:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)CXProvider","kind":"typeIdentifier","text":"CXProvider"},{"kind":"text","text":" *) "},{"text":"provider","kind":"internalParam"},{"kind":"text","text":" "},{"text":"perform:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CXSetMutedCallAction","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CXSetMutedCallAction"},{"text":" *) ","kind":"text"},{"text":"action","kind":"internalParam"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate~1mutedCall(_:perform:)\/title","op":"replace","value":"mutedCall:perform:"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate~1mutedCall(_:perform:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mutedCall:perform:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate\/title","value":"PWVoIPCallDelegate"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PWVoIPCallDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"PWVoIPCallDelegate"}]}]}]}