{"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushwooshNotificationServiceExtension\/pushwooshAppGroupsName()"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"pushwooshAppGroupsName","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}]}]},{"kind":"content","content":[{"type":"heading","anchor":"discussion","text":"Discussion","level":2},{"inlineContent":[{"type":"text","text":"Default returns "},{"code":"nil","type":"codeVoice"},{"text":", in which case Pushwoosh reads ","type":"text"},{"type":"codeVoice","code":"PW_APP_GROUPS_NAME"},{"type":"text","text":" from the extension"},{"text":" ","type":"text"},{"type":"text","text":"Info.plist. Override to provide the App Group programmatically."}],"type":"paragraph"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushwooshNotificationServiceExtension"]]},"abstract":[{"type":"text","text":"The App Group used to sync badge count and reverse-proxy settings with the host app."}],"metadata":{"modules":[{"name":"PushwooshFramework"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pushwooshAppGroupsName","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"role":"symbol","title":"pushwooshAppGroupsName()","platforms":[{"beta":false,"name":"iOS","deprecated":false,"unavailable":false,"introducedAt":"10.0"}],"roleHeading":"Instance Method","externalID":"c:objc(cs)PushwooshNotificationServiceExtension(im)pushwooshAppGroupsName","navigatorTitle":[{"text":"pushwooshAppGroupsName","kind":"identifier"}],"symbolKind":"method"},"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshframework\/pushwooshnotificationserviceextension\/pushwooshappgroupsname()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pushwooshnotificationserviceextension\/pushwooshappgroupsname()"]}],"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushwooshNotificationServiceExtension/pushwooshAppGroupsName()":{"role":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pushwooshAppGroupsName","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"The App Group used to sync badge count and reverse-proxy settings with the host app."}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushwooshNotificationServiceExtension\/pushwooshAppGroupsName()","navigatorTitle":[{"text":"pushwooshAppGroupsName","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/pushwooshframework\/pushwooshnotificationserviceextension\/pushwooshappgroupsname()","title":"pushwooshAppGroupsName()"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"url":"\/documentation\/pushwooshframework","role":"collection","title":"PushwooshFramework","kind":"symbol","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","abstract":[{"text":"Push notification SDK for iOS applications.","type":"text"}]},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushwooshNotificationServiceExtension":{"role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PushwooshNotificationServiceExtension"}],"abstract":[{"text":"Drop-in base class for a Notification Service Extension. Subclass it (or set it directly as","type":"text"},{"type":"text","text":" "},{"type":"text","text":"the extension’s "},{"type":"codeVoice","code":"NSExtensionPrincipalClass"},{"type":"text","text":") and Pushwoosh handles everything required for a"},{"type":"text","text":" "},{"type":"text","text":"push: sending the message delivery event, badge counting, downloading the media attachment,"},{"text":" ","type":"text"},{"type":"text","text":"and the mandatory "},{"type":"codeVoice","code":"serviceExtensionTimeWillExpire"},{"type":"text","text":" fallback."}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushwooshNotificationServiceExtension","navigatorTitle":[{"text":"PushwooshNotificationServiceExtension","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/pushwooshframework\/pushwooshnotificationserviceextension","title":"PushwooshNotificationServiceExtension"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"pushwooshAppGroupsName"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"pushwooshAppGroupsName","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"pushwooshAppGroupsName","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushwooshNotificationServiceExtension~1pushwooshAppGroupsName()\/title","op":"replace","value":"pushwooshAppGroupsName"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushwooshNotificationServiceExtension~1pushwooshAppGroupsName()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"pushwooshAppGroupsName"}]},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushwooshNotificationServiceExtension\/title","value":"PushwooshNotificationServiceExtension","op":"replace"},{"value":[{"kind":"identifier","text":"PushwooshNotificationServiceExtension"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushwooshNotificationServiceExtension\/fragments","op":"replace"}]}]}