{"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushwooshNotificationServiceExtension\/pushwooshPrepare(for:completion:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"pushwooshPrepare"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":" "},{"kind":"internalParam","text":"request"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UNNotificationRequest","text":"UNNotificationRequest"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"keyword"},{"text":" () -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}]}]},{"kind":"parameters","parameters":[{"name":"request","content":[{"inlineContent":[{"type":"text","text":"The original notification request."}],"type":"paragraph"}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Block to invoke when preparation is finished. Call it exactly once, on the main"},{"type":"text","text":" "},{"text":"thread (the thread the system delivers ","type":"text"},{"type":"codeVoice","code":"didReceive"},{"type":"text","text":" on)."}]}]}]},{"kind":"content","content":[{"text":"Discussion","anchor":"discussion","level":2,"type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Default implementation calls "},{"type":"codeVoice","code":"completion"},{"type":"text","text":" immediately."}]}]}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushwooshNotificationServiceExtension"]]},"abstract":[{"type":"text","text":"Called before Pushwoosh processes the push. Override to run asynchronous preparation — for"},{"text":" ","type":"text"},{"type":"text","text":"example, prefetching Push Stories media into a shared App Group container — without overriding"},{"text":" ","type":"text"},{"type":"text","text":"the standard "},{"type":"codeVoice","code":"didReceive"},{"text":". Processing (delivery event, badge, attachment) continues only after","type":"text"},{"text":" ","type":"text"},{"code":"completion","type":"codeVoice"},{"text":" fires, so always call it exactly once, on the main thread.","type":"text"}],"variants":[{"paths":["\/documentation\/pushwooshframework\/pushwooshnotificationserviceextension\/pushwooshprepare(for:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshframework\/pushwooshnotificationserviceextension\/pushwooshprepare(for:completion:)"]}],"sections":[],"metadata":{"role":"symbol","navigatorTitle":[{"text":"pushwooshPrepareForRequest:completion:","kind":"identifier"}],"externalID":"c:objc(cs)PushwooshNotificationServiceExtension(im)pushwooshPrepareForRequest:completion:","roleHeading":"Instance Method","symbolKind":"method","platforms":[{"deprecated":false,"introducedAt":"10.0","unavailable":false,"beta":false,"name":"iOS"}],"modules":[{"name":"PushwooshFramework"}],"title":"pushwooshPrepare(for:completion:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"pushwooshPrepare","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UNNotificationRequest","text":"UNNotificationRequest"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": () -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}]},"references":{"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushwooshNotificationServiceExtension":{"type":"topic","abstract":[{"type":"text","text":"Drop-in base class for a Notification Service Extension. Subclass it (or set it directly as"},{"text":" ","type":"text"},{"text":"the extension’s ","type":"text"},{"code":"NSExtensionPrincipalClass","type":"codeVoice"},{"type":"text","text":") and Pushwoosh handles everything required for a"},{"type":"text","text":" "},{"text":"push: sending the message delivery event, badge counting, downloading the media attachment,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"and the mandatory "},{"code":"serviceExtensionTimeWillExpire","type":"codeVoice"},{"text":" fallback.","type":"text"}],"role":"symbol","url":"\/documentation\/pushwooshframework\/pushwooshnotificationserviceextension","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushwooshNotificationServiceExtension","title":"PushwooshNotificationServiceExtension","navigatorTitle":[{"text":"PushwooshNotificationServiceExtension","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PushwooshNotificationServiceExtension","kind":"identifier"}],"kind":"symbol"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework":{"kind":"symbol","identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework","type":"topic","role":"collection","abstract":[{"text":"Push notification SDK for iOS applications.","type":"text"}],"title":"PushwooshFramework","url":"\/documentation\/pushwooshframework"},"doc://com.pushwoosh.PushwooshiOS/documentation/PushwooshFramework/PushwooshNotificationServiceExtension/pushwooshPrepare(for:completion:)":{"role":"symbol","abstract":[{"type":"text","text":"Called before Pushwoosh processes the push. Override to run asynchronous preparation — for"},{"text":" ","type":"text"},{"text":"example, prefetching Push Stories media into a shared App Group container — without overriding","type":"text"},{"type":"text","text":" "},{"text":"the standard ","type":"text"},{"type":"codeVoice","code":"didReceive"},{"text":". Processing (delivery event, badge, attachment) continues only after","type":"text"},{"text":" ","type":"text"},{"type":"codeVoice","code":"completion"},{"type":"text","text":" fires, so always call it exactly once, on the main thread."}],"identifier":"doc:\/\/com.pushwoosh.PushwooshiOS\/documentation\/PushwooshFramework\/PushwooshNotificationServiceExtension\/pushwooshPrepare(for:completion:)","type":"topic","url":"\/documentation\/pushwooshframework\/pushwooshnotificationserviceextension\/pushwooshprepare(for:completion:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pushwooshPrepare"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UNNotificationRequest","text":"UNNotificationRequest"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": () -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")","kind":"text"}],"title":"pushwooshPrepare(for:completion:)","navigatorTitle":[{"kind":"identifier","text":"pushwooshPrepareForRequest:completion:"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"pushwooshPrepareForRequest:completion:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"pushwooshPrepareForRequest:completion:"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"pushwooshPrepareForRequest:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UNNotificationRequest","kind":"typeIdentifier","text":"UNNotificationRequest"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"request"},{"text":" ","kind":"text"},{"text":"completion:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":" (^","kind":"text"},{"kind":"text","text":")()) "},{"text":"completion","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushwooshNotificationServiceExtension\/title","op":"replace","value":"PushwooshNotificationServiceExtension"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushwooshNotificationServiceExtension\/fragments","value":[{"text":"PushwooshNotificationServiceExtension","kind":"identifier"}]},{"value":"pushwooshPrepareForRequest:completion:","op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushwooshNotificationServiceExtension~1pushwooshPrepare(for:completion:)\/title"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshiOS~1documentation~1PushwooshFramework~1PushwooshNotificationServiceExtension~1pushwooshPrepare(for:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"pushwooshPrepareForRequest:completion:"}],"op":"replace"}]}]}